### ISSUE TITLE
Multi drag support

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#10]
Support the dragging of multiple Draggables. There are still a lot of open questions about this one. 

- Currently the library has no concept of *selecting* a `Draggable`. What would this look like to support 'select' - is this handled by the library - or is it a pattern?
- What is the expected visual experience for a multi drag
- What would the api for `onDragStart` and `onDragEnd` look like?

**Comment by alexreardon** [comment]
We will be starting work on this soon 💖

**Comment by souporserious** [comment]
Excited to see this is on the radar! Have you seen Google drive's multi drag interactions? I really love how they feel native when using them.

![multi-dnd](https://user-images.githubusercontent.com/2762082/37180712-e0e6d4a0-22de-11e8-8254-1e51fbd655ae.gif)

Maybe react-beautiful-dnd could provide some extra methods/components to achieve something similar? It would be awesome to somehow grab a bunch of nodes and have them animate towards the cursor.

**Comment by alexreardon** [comment]
This has landed :) #383

**Comment by dileepkeeppalli** [comment]
Can we have a documentation to use this feature?

**Comment by alexreardon** [comment]
Here it is: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

**Comment by doubleedev** [comment]
Has anyone had any joy with getting this to work in react functional components (no typescript)?
