### ISSUE TITLE
Draggables moving behaviour inverted in some cases

### ISSUE THREAD

**Issue by jesstelford** [atlassian/react-beautiful-dnd#1013]
## Bug or feature request?

Bug

### Expected behavior

1. Draggable moves out of the way once center of gravity of dragged item moves over it.
2. Draggable only moves out of the way when dragging toward it

### Actual behavior

1. Draggable is moving out of the way _before_ center of gravity of dragged item has moved over it, because...
2. moving the dragged item _away from_ a draggable makes that draggable move out of the way (or, rather; into the way).

### Steps to reproduce

*Gif*:
![screen recording 2018-12-14 at 2 26 06 pm](https://user-images.githubusercontent.com/612020/49981780-b2439a00-ffad-11e8-8e8f-5229fb62baee.gif)

### What version of `React` are you using?

`16.7.0-alpha`

### What version of `react-beautiful-dnd` are you running?

`10.0.1`

### What browser are you using?

Chrome `71.0.3578.98 (Official Build) (64-bit)`

### Demo

I haven't taken time to extract a demo yet, but @alexreardon feel free to come look over my shoulder at my setup next time we're in the same place 👍

**Comment by alexreardon** [comment]
Let's look at together when you are in our office next 😊

**Comment by alexreardon** [comment]
I suspect it is a rough edge of our algorithm for displacement.

**Comment by alexreardon** [comment]
Tracking here: #930
