### ISSUE TITLE
Component gets stuck when reordering items too quickly

### ISSUE THREAD

**Issue by qcz** [atlassian/react-beautiful-dnd#1026]
## Bug or feature request?

Bug

### Expected behavior
No problems while reordering items.

### Actual behavior
If I reorder the items too quickly, the component gets stuck in Chrome, Firefox, Edge and Internet Explorer.

### Steps to reproduce
- Clone https://github.com/qcz/react-beautiful-dnd-stuck-bug
- Optional: Run `npm install gulp-cli yarn typescript -g`
- Run `yarn`
- Run `gulp dev`
- Open `http://localhost:8080` in Chrome, Firefox or Internet Explorer
- Try to rearrange the items quickly.

### What version of `React` are you using?
16.3.2

### What version of `react-beautiful-dnd` are you running?
10.0.3

### What browser are you using?
Google Chrome 71.0.3578.98
Firefox Nighly 66
Microsoft Edge
Internet Explorer 11

### Demo
Repository: https://github.com/qcz/react-beautiful-dnd-stuck-bug
Video: https://github.com/qcz/react-beautiful-dnd-stuck-bug/releases/download/release%2F0.0.1/2018-12-20_08-48-01.mp4

**Comment by treshugart** [comment]
Hey @qcz, cheers for reporting. Alex is out on holiday at the moment but we'll have a look at this as soon as we can. Cheers.

**Comment by qcz** [comment]
Hello @alexreardon!
Here it is: https://codesandbox.io/s/p5q5qy1llj

**Comment by alexreardon** [comment]
Your issue is being caused by using an `index` as a `key` for a react component. 

Here is a fixed version https://codesandbox.io/s/m7n4v1r2jy

Further reading:

- https://reactjs.org/docs/lists-and-keys.html#keys
- https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318
