### ISSUE TITLE
Language is unacceptible

### ISSUE THREAD

**Issue by yairEO** [atlassian/react-beautiful-dnd#1028]
Stop with this new-age PC crap, I am doing you a favor reporting bugs. 

Be a man and accept good-old bad language as an honest and true way of communicating between humans. 

What I type reflects what I feel, and bugs makes me feel horrible, like seeing a car accident across the road while driving. You feel such shit should happen. 

If you're that PC-gone and wouldn't accept my manly-language, so be it.

## Code of conduct

While you raise some issues that I would have been happy to discuss, the language used in this issue is unacceptable. As such, I will be locking this issue.

*Excerpt from our [Code of Conduct](https://github.com/atlassian/react-beautiful-dnd/blob/master/CODE_OF_CONDUCT.md)*

> ### Our Standards
> 
> Examples of behavior that contributes to creating a positive environment include:
> 
> - Using welcoming and inclusive language
> - Being respectful of differing viewpoints and experiences
> - Gracefully accepting constructive criticism
> - Focusing on what is best for the community
> - Showing empathy towards other community members
> 
> Examples of unacceptable behavior by participants include:
> 
> - The use of sexualized language or imagery and unwelcome sexual attention or advances
> - Trolling, insulting/derogatory comments, and personal or political attacks
> - Public or private harassment
> - Publishing others' private information, such as a physical or electronic address, without explicit permission
> - Other conduct which could reasonably be considered inappropriate in a professional setting

## Your issues

1. we are fixing that 'snapping' soon #77 
2. it looks like the app is not correctly reordering the list. Here is a guide: https://egghead.io/lessons/react-persist-list-reordering-with-react-beautiful-dnd-using-the-ondragend-callback

Regarding `(2)`: Why are you pointing me to egghead's React lesson?? This bug happens in **your** demo page, I have no access to the source code. I simply clicked on your demo linked and playing around of the Trello app for a single minute and saw all those bugs and felt compelled to report imminently and using non-pc language as I am trying to bring back the good old 80's! 

long-live non-PC world, may the good old days come back already.. peace brother

_Originally posted by @alexreardon in https://github.com/atlassian/react-beautiful-dnd/issues/992#issuecomment-445576434_

**Comment by treshugart** [comment]
@yairEO if you are unable to filter your frustration in a manner that complies with our code of conduct, then we'd prefer that you don't participate at all. You have been warned. If we see further harassment, we will not hesitate to take action.
