### ISSUE TITLE
Destination null when dropping onto an icon

### ISSUE THREAD

**Issue by michaloslav** [atlassian/react-beautiful-dnd#1029]
(probably a bug or maybe just me being an idiot)

Hey, I'm trying to implement a pretty basic feature but I'm stuck for some reason. The idea is to let users drag an item onto a trash can to delete it. I already implemented dnd for moving items around and it works perfectly, all I did now was I added a second droppable and put the icon inside of it. For some reason though when I drop onto it, I get destination: null. It might have something to do with the width of each droppable, the icon is obviously not as wide as the other droppable (which is essentially fullscreen and so are the draggables).

Is there something I'm missing here? It could be a bug or maybe you're just supposed to use icons as droppables in a different way. And is width really an issue?

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by alexreardon** [comment]
The fact that it is an icon should not really matter, but it is hard to know without being able to have a look

**Comment by alexreardon** [comment]
I'll close this for now. Please reopen if you still need assistance
