### ISSUE TITLE
Touch doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by lilymatcha** [atlassian/react-beautiful-dnd#1036]
### Expected behavior

You long-press to select in order to initiate the drag.

### Actual behavior

When you long-press, it simply selects and does not drag.

### Steps to reproduce

Open Microsoft Edge, go to any of the examples, and attempt to use touch to drag.

### What version of `React` are you using?

16.6.3

### What version of `react-beautiful-dnd` are you running?

10.0.3

### What browser are you using?

Microsoft Edge (v. HTML 17.17134)

### Demo

On [Youtube](https://www.youtube.com/watch?v=oLTnS_j6vGU&feature=youtu.be).

**Comment by Weffe** [comment]
What device is that demo running on? Microsoft Surface Pro?

**Comment by lilymatcha** [comment]
@Weffe Microsoft Surface Laptop

**Comment by treshugart** [comment]
Alex will be back mid-Jan. See #1010 for more details.

**Comment by alexreardon** [comment]
I tested this and it seemed to work for me.. Strange. Should continue to investigate!

I will try to get access to appropriate hardware

**Comment by lilymatcha** [comment]
@alexreardon What hardware are you testing on? I think it shouldn't be a hardware (i.e. lack of drivers, etc.) issue, because the library works fine for me on Chrome, just not on Edge. Furthermore, adding the pointer sensor (#1045) fixed the issue for me, so I'm curious what's different that could be allowing it to work on your end.

**Comment by alexreardon** [comment]
I mentioned this in #1045:

> Edge is moving to Chromium and there are already beta Edge builds. My expectation is that Edge moving to Chromium will fix #1036. Please let me know if that is not the case and I am more than happy to revisit this.
> I want to stress how thankful I am @lilymatcha for your input. Let me know if there are other parts of this library you are keen to get involved in

[Side thought about edge](https://twitter.com/alexandereardon/status/1117583118423056384)
