### ISSUE TITLE
Auto-scroll moves up constantly during horizontal dragging!

### ISSUE THREAD

**Issue by matttk** [atlassian/react-beautiful-dnd#1040]
## Bug or feature request?

Bug

### Expected behavior

Scrolling horizontally should never activate vertical autoscroll, unless you actually try to scroll vertically.

### Actual behavior

Scrolling horizontally instantly activates vertical autoscroll up (until the top of the page is reached) under certain circumstances.

### Steps to reproduce

I actually can't figure out how to reproduce it normally but I did manage to get the exact same behaviour in this [codesandbox.io](https://codesandbox.io/s/20n9r15050), using the example as a basis and building in my own code.

I still couldn't reproduce it until I noticed that if you shrink the vertical width of the screen, it eventually starts happening. This goes to my theory that there is something going on in the autoscroll calculations, involving the height of various divs...

Make the window as small as in the below picture and then drag a card left or right. The screen will start moving up slowly.

![image](https://user-images.githubusercontent.com/28646175/50640160-4e850f00-0f64-11e9-94db-ef9324c645f8.png)

### What version of `React` are you using?

16.3.1

### What version of `react-beautiful-dnd` are you running?

10.0.3

### What browser are you using?

Chrome, latest version for Windows 10.

### Demo

[My demo](https://codesandbox.io/s/20n9r15050) is based on [your boilerplate](https://codesandbox.io/s/k260nyxq9v) and another one that included SCSS support.

Again, make sure to shrink the screen enough (like in the above picture) and then start dragging.

However, in my actual code, I get the problem always, even with the browser window maximised. It's only that I couldn't figure out how to reproduce it in the code sandbox.

I can imagine that I am missing something necessary in the CSS, which is tripping up the autoscroll calculations but I can't find the problem... I'm hoping that this too small screen version I did find in the code sandbox is the same problem or at least related to mine.

**Comment by treshugart** [comment]
Hey @matttk, just want to let you know we'll look into this as soon as we can. Alex, the maintainer, will be back soon. For more info, see #1010.

**Comment by alexreardon** [comment]
Sounds bad @matttk

**Comment by alexreardon** [comment]
Okay, so this has to do with how auto scrolling works. If you drag something near the edge of a browser, we will scroll the browser if it can be scrolled. This is true even when the movement is on any plane (vertical or horizontal).

In your posted example, i am not sure why the auto scroll only goes up and not also down as you move the item lower. This is worth looking into

**Comment by alexreardon** [comment]
I'll take a deeper look @matttk

**Comment by alexreardon** [comment]
This one is confusing. When I moved it onto my local everything worked as expected...

But there is an issue on the codesandbox one 🤔

**Comment by alexreardon** [comment]
Something strange going on. If I add this style it seems to work fine:

```css
html, body {
    width: 100%;
    height: 100%;
}
```

**Comment by alexreardon** [comment]
This one is really hard to get right given there are so many ways a document can be setup 😲

**Comment by matttk** [comment]
> Something strange going on. If I add this style it seems to work fine:
> 
> ```css
> html, body {
>     width: 100%;
>     height: 100%;
> }
> ```

I readly thought I tried something like this but maybe I only applied it to the body or html... at any rate, this gets rid of the problem, even if it isn't really the solution. Thanks! :+1:

**Comment by alexreardon** [comment]
I am working on a fix @matttk that will avoid you needing to add those styles

**Comment by alexreardon** [comment]
I have added a new doc section encouraging people to use the html5 doctype

**Comment by ds-martinso** [comment]
Hi,
I seem to still have this issue. Could someone help me understand why my table scrolls up when I want to drag horizontally? (First scroll the table a bit down, and then try to drag a column horizontally. You will see that the table autoscrolls up, but I don't want it to)
Please see this modified sandbox https://codesandbox.io/s/gargroh-v7-drag-column-beautiful-react-dnd-forked-p0rm8?file=/src/index.css
Thanks!
