### ISSUE TITLE
Create function component guide

### ISSUE THREAD

**Issue by EdmundsEcho** [atlassian/react-beautiful-dnd#1043]
I'm hoping to get some guidance on how to generate the required `innerRef` prop using a functional component with the hook `useRef`.  Thank you in advance.

**Comment by alexreardon** [comment]
It would be worth putting together a guide on how to use `react-beautiful-dnd` using function components + hooks

**Comment by alexreardon** [comment]
This would not be needed if we just moved to hooks #871

**Comment by alexreardon** [comment]
Here is an example I put together: https://codesandbox.io/s/zqwz5n5p9x

**Comment by alexreardon** [comment]
I think I will also add a story example

**Comment by alexreardon** [comment]
#1167

**Comment by ChangoMan** [comment]
Thank you! I was looking for this exact example, works great!
