### ISSUE TITLE
Augment the `result` object with user-defined props set for `droppables` and `draggables`

### ISSUE THREAD

**Issue by EdmundsEcho** [atlassian/react-beautiful-dnd#1049]
Request - thinking out loud with all that this library has inspired...

**Goal** 
Expand the channel that currently sends the `type` prop (for instance) of a `droppable` to the `result` object, with whatever additional props the user might set for `droppable`.  Ditto for `draggable`.

An approach to enriching the API would be to create `getProvider` that would take user props as arguments while returning the `provider` object.  

My use case is to use the `custom` prop to provide a more detailed description of the type separate from the implications of using the current `droppable type` prop.

Does that make sense?

**Comment by alexreardon** [comment]
Yes it does! It is one of the options we are considering in #498
