### ISSUE TITLE
I'd like to ask you a question. @markdon thanks

### ISSUE THREAD

**Issue by zhangshuai0101** [atlassian/react-beautiful-dnd#1054]
I have consulted you before, but I don't understand what you mean.
demo： https://0qrxp521zp.codesandbox.io/
Well, when the element is dragged from the right to the left, The left element is occluded when it moves to the right element. This is caused by position: relation. What can we do now? Can you give me a code example to refer to the solution, I would like to flexbox layout will also occur this imagination Thank you very much @markdon @alexreardon

**Comment by markdon** [comment]
So continuing from [my last comment](https://github.com/atlassian/react-beautiful-dnd/issues/998#issuecomment-446377973) on this: I figured out how to open the editor for codesandbox and tried out what I was thinking.  

The draggable items have a new class `.bwizard-step-item` and css has been changed to target that class instead of `li` (mostly). This avoids giving the element that was covering one of your draggables a background colour.
https://codesandbox.io/s/y3xvp8z71v

**Comment by zhangshuai0101** [comment]
> 继续[我上次对此的评论](https://github.com/atlassian/react-beautiful-dnd/issues/998#issuecomment-446377973)：我想出了如何打开编码盒的编辑器并尝试了我的想法。
> 
> 可拖动的项目有一个新的类，`.bwizard-step-item`并且css已被更改为目标该类而不是`li`（大多数）。这样可以避免为覆盖其中一个可拖动元素的元素提供背景颜色。
> https://codesandbox.io/s/y3xvp8z71v

Thank you very much !

**Comment by zhangshuai0101** [comment]
> So continuing from [my last comment](https://github.com/atlassian/react-beautiful-dnd/issues/998#issuecomment-446377973) on this: I figured out how to open the editor for codesandbox and tried out what I was thinking.
> 
> The draggable items have a new class `.bwizard-step-item` and css has been changed to target that class instead of `li` (mostly). This avoids giving the element that was covering one of your draggables a background colour.
> https://codesandbox.io/s/y3xvp8z71v

Thank you very much !

**Comment by markdon** [comment]
Regarding flexbox, it's definitely the best way to get the layout you're looking for and will be of great value to you after learning how to use it. The CSS Tricks guide should include everything you need to learn flexbox. 

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by zhangshuai0101** [comment]
> Regarding flexbox, it's definitely the best way to get the layout you're looking for and will be of great value to you after learning how to use it. The CSS Tricks guide should include everything you need to learn flexbox.
> 
> https://css-tricks.com/snippets/css/a-guide-to-flexbox/
I tried to use flexbox to lay out the layout before, but it didn't work as expected. I will continue to learn to improve the front-end skills. Thank you, markdon
