### ISSUE TITLE
Drag and drop fires off onClick function

### ISSUE THREAD

**Issue by Robert-Fish** [atlassian/react-beautiful-dnd#1066]
I have attached on OnClick to the droppable component and my issue is that the drag and drop is causing my onClick to fire off. What can i do to prevent this?

**Comment by alexreardon** [comment]
This should provide the information you are after: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/how-we-use-dom-events.md

**Comment by Robert-Fish** [comment]
Cheers!
