### ISSUE TITLE
Perf impact of using Draggable

### ISSUE THREAD

**Issue by navneet-g** [atlassian/react-beautiful-dnd#1069]
## Bug or feature request?
While measuring performance for our app, that renders 100s of draggable cards, we noticed that Draggable adds about 1.2ms render time. I measured it in non-minified scripts as it is easier to see in the User timings section of Chrome dev tools, I assume it will be about 0.5ms - 0.8ms in minified scripts. It still feels little high. 
Has any one else done performance profiling and saw similar results, or am I missing something? 

![image](https://user-images.githubusercontent.com/13487927/51781966-6e2bd500-20d5-11e9-81dc-59cfd321dabf.png)

### Steps to reproduce
I measured using the simple list example of react-beautiful DnD as well and got similar results.

### What version of `React` are you using?
16.3.2

### What version of `react-beautiful-dnd` are you running?
10.0.2

### What browser are you using?
Chrome 71.0.3578.98

### Demo
![image](https://user-images.githubusercontent.com/13487927/51781966-6e2bd500-20d5-11e9-81dc-59cfd321dabf.png)

**Comment by alexreardon** [comment]
It sort of makes sense. There is a bit of startup registration that happens. Is that 1.2ms per Draggable? I would also try running in production mode. There might be some dev tools work slowing things down. Also keep in mind that the dev tools themselves can add some minor overhead.

**Comment by navneet-g** [comment]
Thanks @alexreardon , I tried in production mode and in Chrome incognito where no extensions are installed. I still see about 0.3ms to 0.4ms, per Draggable. This still adds up when we have >200 cards to render. Is there a way to delay initialize Draggable without causing re-render of the Card?

**Comment by alexreardon** [comment]
I don't think so @navneet-g. However, this scale issue will go away once we support virtual lists #68 

Options:

1. Use a double render to delay the initialization
2. Use a virtual list to reduce the amount of items

The registration of 0.3ms does sound like a lot. It effectively just adds an entry to a map..
