### ISSUE TITLE
Animations inside table are not show on Edge

### ISSUE THREAD

**Issue by kimmoahola** [atlassian/react-beautiful-dnd#1073]
## Bug

On the table examples at https://react-beautiful-dnd.netlify.com/?selectedKind=Tables&selectedStory=with%20dimension%20locking&full=0&addons=1&stories=1&panelRight=0 I don't see any animations on Microsoft Edge. Everything seems to work, just no animations and thus things feel broken.

The items are moved after the release of mouse button.

### Expected behavior

Animations should show.

### Actual behavior

Animations do not show.

### What browser are you using?

Microsoft Edge 42

### Demo

The table examples at https://react-beautiful-dnd.netlify.com/?selectedKind=Tables&selectedStory=with%20dimension%20locking&full=0&addons=1&stories=1&panelRight=0

**Comment by tajo** [comment]
It's a bug in Edge (and IE11), confirmed 3 years ago but never fixed: https://stackoverflow.com/questions/34718443/ie-edge-not-applying-transform-translate-to-table-row

**Comment by alexreardon** [comment]
It is possible to get the animations working with tables in ie11: https://atlaskit.atlassian.com/packages/core/dynamic-table/example/with-lots-of-pages-rankable

There are a few CSS properties required - you are welcome to go digging!

**Comment by alexreardon** [comment]
I don't have capacity to dig myself right now, but somebody else is welcome to!

**Comment by alexreardon** [comment]
Given that Edge is going away, I see no pressing need to fix this one
