### ISSUE TITLE
Add `isDropAnimating` to DroppableStateSnapshot

### ISSUE THREAD

**Issue by mnquintana** [atlassian/react-beautiful-dnd#1074]
## Bug or feature request?

Feature request

## Feature request

It would be super helpful to have access to the same `isDropAnimating` provided to the `Draggable` child function in the `Droppable` child function. My use case: I have a component that I want to respond to changes in `isDropAnimating` that isn't a `Draggable`, but is contained by a `Droppable` (let me know if this is too vague and I can elaborate)

### What version of `React` are you using?
16.6.3

### What version of `react-beautiful-dnd` are you running?
react-beautiful-dnd@10.0.3

### What browser are you using?
Chrome

**Comment by MikaelCarpenter** [comment]
@alexreardon Revisiting this now that 10.1 is out, looks like `isDropAnimating` has been added to `snapshot` for `Draggable`s. This can probably be closed
