### ISSUE TITLE
Invariant failed: provided.innerRef has not been provided with a HTMLElement

### ISSUE THREAD

**Issue by JESii** [atlassian/react-beautiful-dnd#1079]
## Bug or feature request?

Bug

### Expected behavior
Expected to be able to simply display my existing list after applying the Draggable  - not even trying to drag-n-drop any items yet.

### Actual behavior
I've tried it with `ref={provided.innerRef}` and also with` innerRef={provided.innerRef}`

When opening a list of Draggable items, and using `innerRef={provided.innerRef}`, I get the error:
`Invariant failed: Cannot get Draggable ref from drag handle`

When using `ref={provided.innerRef}` I get the error:
`Invariant failed: provided.innerRef has not been provided with a HTMLElement`

Tried both even though I'm not using styledComponents

### What version of `React` are you using?
16.3.1

### What version of `react-beautiful-dnd` are you running?
10.0.4

### What browser are you using?
Chrome

### Demo
I wish I could give you a demo, but I've got four components, rather than a single simple instance as in your demo... I'll try but don't hold out much hope. Also, this is an internal application for a client of mine so cannot share all the code.

What I can do for starters is provide key elements of the code and hope that this will be sufficient for some pointers. I'm guessing that I may just have a n00b issue here.

#### Data Structure
Each category is a Droppable element, and each individual errorString is a Draggable:
```
[
  {
    "category": "Data",
    "errorStrings": [
      {
        "id": "initial-5",
        "value": "ERROR - DATA"
      },
      {
        "id": "initial-9",
        "value": "Data refresh"
      }
    ],
    "id": "initial-1"
  },
  {
    "category": "Time ENV",
    "errorStrings": [
      {
        "id": "initial-10",
        "value": "The expected element was not visible after performing a hover 3 times"
      },
    ],
    "id": "initial-2"
...etc
```
#### ErrorCategoriesParameters
```
    return (
      <div>
        <DragDropContext
          onDragStart={onDragStart}
          onDragUpdate={onDragUpdate}
          onDragEnd={onDragEnd}
        >
          <ErrorCategories />
        </DragDropContext>
      </div>
    );
```
#### ErrorCategories
``` 
             <Droppable droppableId={category.id}>
                {provided => (
                  <ErrorItems
                    ref={provided.innerRef}
                    {...provided.droppableProps}
                    errorItems={category.errorStrings}
                    errorCategory={category.category}
                    handleNewItem={this.handleNewItem}
                    saveNewItem={this.saveNewItem}
                    handleDeleteItem={this.handleDeleteItem}
                  >
                    {provided.placeholder}
                  </ErrorItems>
                )}
                </Droppable>
```
#### ErrorItems
```
      itemJSX.push(
        <Draggable key={item.id} draggableId={item.id} index={index}>
          {(provided) => (
            <div style={{ textAlign: 'left', padding: '0px 24px' }}
              ref={provided.innerRef}
              {...provided.draggableProps}
              {...provided.dragHandleProps}
            >
              <span style={{ textAlign: 'left', width: '80%', fontWeight: 'bold' }}>
                <TextField
                  required
                  id={item.id}
                  name={item.value}
                  value={item.value}
                  style={errorItemsStyle}
                  margin="normal"
                  onChange={event => handleChangeItem(event, item, title, errorItemSlug)}
                  onBlur={event => validateField(event, item, title)}
                />
              </span>
              <span>
                [
                <button type="button" onClick={event => handleDeleteItem(event, item, title)} style={{ padding: '0px 12px' }}>
                  {themeIcons.delete}
                </button>
                ]
              </span>
            </div>
          )}
        </Draggable>
      );
```
#### Output
Categories are initially closed, like so:
![image](https://user-images.githubusercontent.com/486/51943024-54d4a280-23cd-11e9-99af-f072ac4d9928.png)

When opening a category, the errorStrings are displayed,
![image](https://user-images.githubusercontent.com/486/51944051-e6ddaa80-23cf-11e9-8ece-d394518870d9.png)

Then it immediately crashes with the titled error:
![image](https://user-images.githubusercontent.com/486/51942943-1dfe8c80-23cd-11e9-8c8a-341dc498394a.png)

**Comment by alexreardon** [comment]
Have you had a read through our [using inner ref guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md)?

**Comment by JESii** [comment]
Perfect; I just wrapped `<ErrorItems...>` in a `<div>` and now it's displaying. Thanks for the quick response :=)

**Comment by nomanoff** [comment]
In my case, I had the same problem and I noticed that in the video he was using the older version of styled-components where he was using **innerRef** prop. Later that was updated to just **ref**  then it just worked.

**Comment by maiya-22** [comment]
I still get this issue randomly, and then it goes away (not sure why).

**Comment by developerdesigner18** [comment]
I too faced this issue. Does anyone find a solution?

**Comment by Ashu525** [comment]
Guys just rap your ul and li into a return like this in both draggable and droppable
`
{(provided) => {
              return (
                <li
                  key={index}
                  index={index}
                  {...provided.draggableProps}
                  {...provided.dragHandleProps}
                  ref={provided.innerRef}
                >
                  {item.title}
                </li>
              );
            }}
`

**Comment by rutikwankhade** [comment]
> Guys just rap your ul and li into a return like this in both draggable and droppable `{(provided) => { return ( <li key={index} index={index} {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef} > {item.title} </li> ); }}`

Thank you so much for this. You saved my day!

**Comment by sigespweb22** [comment]
Change from `innerRef={provided.innerRef}` to `ref={provided.innerRef}`, provided to me. Thanks!

**Comment by abhisheksharmayt** [comment]
> Guys just rap your ul and li into a return like this in both draggable and droppable `{(provided) => { return ( <li key={index} index={index} {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef} > {item.title} </li> ); }}`

Thank You, I was stuck here for the last 3hr but now it's working fine.

**Comment by naveenbasyal** [comment]
> Guys just rap your ul and li into a return like this in both draggable and droppable `{(provided) => { return ( <li key={index} index={index} {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef} > {item.title} </li> ); }}`

Thanks !! you saved my time !!
