### ISSUE TITLE
Drag big element

### ISSUE THREAD

**Issue by Silent777** [atlassian/react-beautiful-dnd#1093]
I'm not able to move an item when it is too big.
I have an item that not fit in the viewport, and when I'm trying to move it down, the item that located below don't want to move up.

**Comment by Jannikdam** [comment]
The center of the top element needs to go below the top edge of the lower element, for them to switch places. If your top element is very tall you might not be able to drag it far enough down.

In that case you are dealing with this issue:
https://github.com/atlassian/react-beautiful-dnd/issues/930

**Comment by alexreardon** [comment]
Duplicate: #930
