### ISSUE TITLE
Feature idea: Use a higher-order function to set how "equality" between types is determined

### ISSUE THREAD

**Issue by EdmundsEcho** [atlassian/react-beautiful-dnd#1095]
## feature request

Currently: Types must match between `source` and `destination`.  The basis for determining equality between types is `===` (likely).

Future: Types must match between `source` and `destination`.  However, the basis for determining equality is set by the user.  This would require replacing the current fixed `===` with a higher-order function (a function that takes a function as a parameter).  The default would be as it is now `===`, but could be set to any function `:: Type -> Type -> Bool`.  

This way I accomplish the need for more flexibility in determining what is and isn't an equivalent type without impinging on the design constraint of requiring that the types "match".

Is that feasible?

**Comment by alexreardon** [comment]
It could be - but you could also use `isDropDisabled`

**Comment by alexreardon** [comment]
Given that `isDropDisabled` exists, I don't see a pressing need for this one. Feel free to continue the discussion and I can reopen this if needed
