### ISSUE TITLE
How to allow drop only at bottom of the list

### ISSUE THREAD

**Issue by navneet-g** [atlassian/react-beautiful-dnd#1098]
## Bug or feature request?
Question, I could not find a duplicate issue.

I have multiple side by side lists on a board. When moving a card from List A to List B, I want to allow only dropping the card at the bottom of List B.

I could not find any props where I can specify it. One way I could think is somehow I can notify the library during onDragUpdate, similar how we can provide value for announce in HookProvided.

Is there any other solution that I am missing?

**Comment by alexreardon** [comment]
When you say the bottom of a list, do you mean underneith the target list?

If so you could just create a droppable under the list

**Comment by navneet-g** [comment]
I have a droppable, that is also a list of draggable. If I start dragging an item from the same list I want it to be dropped anywhere, but if I start dragging an item from a different list I want to allow dropping only at bottom. I do not want to rerender the target droppable as that will have perf impact.

**Comment by alexreardon** [comment]
Could you have a hidden droppable at the end of the list that is only activated when dragging from a different list? But I guess you want to be able to drop anywhere on the source list. 

For now this falls outside of our [design thinking](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/design-principles.md)
