### ISSUE TITLE
Add ability to override default z-index for Draggables

### ISSUE THREAD

**Issue by mnquintana** [atlassian/react-beautiful-dnd#1099]
## Bug or feature request?

Feature request

## Feature request

It would be really helpful if it was possible to override the default z-index for Draggables when dragging (which looks like `5000`, from what I can tell). 

My use case – we have a modal component that has a base z-index less than `Draggable`'s z-index, and a pseudo element that must be rendered with a z-index above `Draggable`'s z-index during a drag, but below our base modal's z-index. This isn't possible at the moment, so we currently reset the pseudo element's z-index when a modal's open, which feels pretty gnarly. Ideally, I'd like to be able to configure `react-beautiful-dnd` to use a z-index lower than our base modal's z-index.

Let me know if this is too vague and I can elaborate!

### What version of `React` are you using?
16.6.3

### What version of `react-beautiful-dnd` are you running?
10.0.3

### What browser are you using?
Chrome

**Comment by MikaelCarpenter** [comment]
Would overriding the styles in your `Draggable` suffice?

You can check out [`task.js`](https://codesandbox.io/s/rr318p74pq?module=%2Fsrc%2Ftask.js) in this codesandbox to see an example. It should successfully override your zIndex.

If that's not applicable, I can try to implement something for your use case.

**Comment by alexreardon** [comment]
All of the `style`s are provided to you. 

```js
export type DraggableProps = {|
  style: ?DraggableStyle,
  'data-react-beautiful-dnd-draggable': string,
  onTransitionEnd: ?(event: TransitionEvent) => void,
|};
```

[see our types guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/types.md)

You can overwrite and manipulate the styles 👍
