### ISSUE TITLE
How to properly handle dragging into a nested droppable?

### ISSUE THREAD

**Issue by jdsmith2816** [atlassian/react-beautiful-dnd#1107]
## Bug or feature request?
Draggable1 and Droppable2 are contained by Droppable1.
Droppable1 and Droppable2 are both valid targets for Draggable1.

I'm currently experiencing a behavior where a drag from above Droppable2 causes Droppable2 to bounce upwards and become displaced from the location rbdnd allows the drop.

This [gif demonstrating the issue](https://giphy.com/gifs/8Fc89VxCFFzbnK6ENw) is probably worth about 5,000 of my words.

Do you have any advice on how to handle this properly?

If this is surprising un-seen before behavior then I will create an isolated demo on codesandbox that reproduces the issue.

### Expected Behavior
I expect to be able to drop the draggable onto the droppable in it's current location.

### What version of `React` are you using?
16.3.2

### What version of `react-beautiful-dnd` are you running?
9.0.1 however this is reproducible using latest as well

### What browser are you using?
Mac OSX Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by alexreardon** [comment]
Right now it is not possible to drag into different levels of droppable

Duplicate: #1001
