### ISSUE TITLE
Allow passing of dimensions for fixed width/height draggables? (Potential performance enhancement)

### ISSUE THREAD

**Issue by tjramage** [atlassian/react-beautiful-dnd#1111]
## Feature request

I understand that a lot of work is done during dimension capturing immediately prior to a drag starting. Forgive me, as I am not fully informed here, but I assume that this stage is interested in getting the dimensions of droppables AND draggables? 

If so, I was wondering if a potential performance enhancement would be to allow the passing of a `draggableWidth` and `draggableHeight` prop to the `DragDropContext` (or `Droppable`) component for cases where the draggable items have fixed dimensions.

This would (hopefully) remove the need to, at the very least, calculate the dimensions of each draggable every time a drag action occurs, which may help squeeze a bit more out in terms of performance? Obviously this would only be applicable to implementations where draggable item dimensions are indeed fixed...

**Comment by alexreardon** [comment]
Possibly. We collect a lot of information including padding, margin etc. 

From my investigations the collection is not bad. Doing it with too many things is expensive. I expect that for when you have a list > 500 things using a virtual list would resolve any performance issues like this

**Comment by alexreardon** [comment]
#68

**Comment by tjramage** [comment]
Hey @alexreardon, hope the presentation in Sydney went well! 😉 

No worries. I guess I was just thinking of ways we could improve performance in order to get around the need for virtualisation (in the short-term). The thinking behind that being it might be quicker and easier to support parameterised widths/heights. I'm definitely onboard with virtual lists being the 'real' solution to this issue though (and I'd love to see support for that over this!).

**Comment by alexreardon** [comment]
Thanks @tjramage. Please keep the suggestions coming!
