### ISSUE TITLE
 Cannot remove the dragging item during a drag

### ISSUE THREAD

**Issue by pureZjr** [atlassian/react-beautiful-dnd#1113]
## Bug or feature request?

hello，i use react-beautiful-dnd and react-virtualized ，when i scroll ，it is error ‘ Cannot remove the dragging item during a drag’。 i think is the react-virtualized remove the dragging item。Do you have any solutions，thank you。

**Comment by alexreardon** [comment]
We plan on supporting virtual lists soon #68
