### ISSUE TITLE
isCombineEnabled with no sorting

### ISSUE THREAD

**Issue by YurkaninRyan** [atlassian/react-beautiful-dnd#1116]
## Feature request

`isCombineEnabled` assumes that items that can combine can also be dropped in the list.  Would i tbe possible to split that logic up?

My usecase if I have two lists, and I want to be able to combine items from one to the other, but not allow the user to drag and drop in between the items.

My current solution involves intercepting styles based on what's currently dragged, and not rendering the placeholder, but it appears that the library underneath still treats the items like they are moving and that the styles are just sugar.

1. Is this something that fits the philosophy of this library?
2. If I wanted to contribute to this issue where should I begin?

Thanks again for all your hard work : )

**Comment by YurkaninRyan** [comment]
https://www.useloom.com/share/ffcca97889fc44e8b85bf8cdebb96000

Here's a video demonstrating what i'd like to be able to do

You can see at one point I drop an item into another, and it actually misses.  I believe this is because of me overriding the styles and is totally self inflicted

**Comment by YurkaninRyan** [comment]
Perhaps creating a 3rd flag is heavy but:

isDropDisabled          - No Combine or Sort
  isCombineEnabled  - defaults to false, allows combine drag and drop
  isSortEnabled          - defaults to true, allows dropping among items

**Comment by alexreardon** [comment]
I have been thinking about this too

**Comment by alexreardon** [comment]
Let's track this as a part of #1116
