### ISSUE TITLE
Doesn't play nice with react-dnd

### ISSUE THREAD

**Issue by jaredreich** [atlassian/react-beautiful-dnd#1123]
## Bug or feature request?

Bug

### Expected behavior

Does not clash with react-dnd

### Actual behavior

Clashes with react-dnd (if a react-dnd drag source is the same element (or nested element) as a react-beautiful-dnd draggable, the react-beautiful-dnd draggable behaviour wins and no react-dnd behaviour will occur).

### What version of `React` are you using?

16.7.0

### What version of `react-beautiful-dnd` are you running?

10.0.3

### What browser are you using?

Chrome 71 (macOS)

### Other:

Not sure if this is expected but thought I'd bring it up in case the maintainers are aware of it or have an opinion on whether this is expected and why.

Thanks folks!

**Comment by alexreardon** [comment]
You could take a look at [how we use DOM events](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/how-we-use-dom-events.md) to see exactly what events we use and when.

For *drag handles* we do put a `draggable="false"` on the element to opt out of html5 drag and drop. So you would not be able to have a single drag handle work with both. You could try to override `draggable="false"` on your component and see what happens :|

Let me know if there is any other input you needed
