### ISSUE TITLE
Problem with @atlaskit/tree

### ISSUE THREAD

**Issue by eddyhdzg** [atlassian/react-beautiful-dnd#1136]
I'm trying to replicate the functionality of dragging a **PARENT LIST** from this demo [demo_with_nesting](https://atlaskit.atlassian.com/packages/core/tree/example/drag_and_drop_with_nesting)

![dnd-nesting](https://user-images.githubusercontent.com/20821459/53769726-67e20300-3ea2-11e9-8cb6-cb737577132c.gif)

In the pure tree demo without all the CSS from 
[demo_pure_tree](https://atlaskit.atlassian.com/packages/core/tree/example/pure-tree)

![pure-tree](https://user-images.githubusercontent.com/20821459/53769752-79c3a600-3ea2-11e9-9053-04b8c8f0c14a.gif)

Any Ideas?

**Comment by markdon** [comment]
Not sure if it's actually current, but the [docs here](https://atlaskit.atlassian.com/packages/core/tree) say:

> Current limitations = Plans: Currently it's not possible to drag a parent, which is already expanded. Addition to this, it's not possible to hover over another item to expand it or drop on top to nest. We are actively working on these features and we will update the documentation once they are ready.

**Comment by markdon** [comment]
Having said that... There is some code in Tree that looks like it should handle this [59](https://bitbucket.org/atlassian/atlaskit-mk-2/src/a11f95c73d47551bafcc673dd6dd32ec712cb308/packages/core/tree/src/components/Tree/Tree.js?at=master#lines-59) [68](https://bitbucket.org/atlassian/atlaskit-mk-2/src/a11f95c73d47551bafcc673dd6dd32ec712cb308/packages/core/tree/src/components/Tree/Tree.js?at=master#lines-68)

I need to make this work in the near future 😉

**Comment by alexreardon** [comment]
@balnagy ^

**Comment by eddyhdzg** [comment]
I still can't make it work like in this [demo](https://atlaskit.atlassian.com/packages/core/tree/example/drag_and_drop_with_nesting)

![gif](https://user-images.githubusercontent.com/20821459/54074933-73487c00-425e-11e9-9541-9f9a5f57b0ca.gif)

Can you please help me with some working code 👀?

**Comment by balnagy** [comment]
Hi @eddyhdzg,

As @markdon pointed out in the documentation, this was a limitation earlier, but the docs needs to be updated as this feature already implemented.

To make pure list work, you need to create a scrollable container. Here is one working example: https://codesandbox.io/s/v6m657wk70?fontsize=14
