### ISSUE TITLE
Controlled input loses focus onChange

### ISSUE THREAD

**Issue by milkman4** [atlassian/react-beautiful-dnd#1138]
## Bug or feature request?

Bug

### Expected behavior

When using a controlled text field inside a draggable component, editing the field works as expected, with the edits to maintain in state with the onChange handler.

### Actual behavior

When using a controlled text field inside a draggable component, editing the field works causes focus to be lost - specifically when the state is being controlled.

### What version of `React` are you using?

Latest

### What version of `react-beautiful-dnd` are you running?

Latest

### What browser are you using?

Chrome

### Demo

https://codesandbox.io/s/rmrnqlolwp

**Comment by alexreardon** [comment]
Here you go: https://codesandbox.io/s/kon8qyy6qo

Your issue is that you are using the `value` of the input as part of the key for the draggable. This is causing the component to mount and remount which is the root of your issue.

**Comment by Karan02** [comment]
@alexreardon thanks it worked
