### ISSUE TITLE
New blog!

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#114]
Hi everyone,

I have written a new blog: ["Natural keyboard movement between lists"](https://medium.com/@alexandereardon/friction-gravity-and-collisions-3adac3a94e19). It goes into the algorithms that we created in building keyboard movement between lists. 

![collision](https://user-images.githubusercontent.com/2182637/30778999-a41fdf9c-a126-11e7-9423-762f286d6643.gif)

Enjoy!

**Comment by tim-soft** [comment]
You guys are wizards. The illustrations are fantastic!
