### ISSUE TITLE
Change height of droppable area if draggable is too small

### ISSUE THREAD

**Issue by RinatRezyapov** [atlassian/react-beautiful-dnd#1141]
When I drag divider element which has small height I would like to increase height of area where I want to drop that element. Right now the drop area too narrow and people with touch pads experience problems. 
I believe this problem is related to #981 in terms of onBeforeDragStart handler, but maybe, for my particular case, there is a simple solution?

![dnd](https://user-images.githubusercontent.com/19992386/53870892-e95da080-401c-11e9-8f83-e5c5f107151a.gif)

**Comment by alexreardon** [comment]
Right now this is not supported. This seems to be similar to #930 so we can track it there
