### ISSUE TITLE
Dynamically created droppables don't work

### ISSUE THREAD

**Issue by flopes89** [atlassian/react-beautiful-dnd#1142]
## Bug or feature request?

Bug (?)

### Expected behavior

I should be able to drop draggables into elements that were dynamically created by state changes from an `onBeforeDragStart` responder.

### Actual behavior

Draggables cannot be dropped into Droppables whose contents changed in response to a state change triggered by an `onBeforeDragStart` responder.

### Steps to reproduce

See demo

### What version of `React` are you using?

16.8.3

### What version of `react-beautiful-dnd` are you running?

10.0.4

### What browser are you using?

Firefox Quantum 65

### Demo

https://codesandbox.io/s/lp8wpp2vwq

**Comment by alexreardon** [comment]
We are only supporting the dynamic addition of draggables for now https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/changes-while-dragging.md#rules

`onBeforeDragStart`: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/responders.md#secondary-onbeforedragstart

✅ Can apply modifications to existing components to lock their sizes
❌ Cannot remove or add any <Draggable /> or <Droppable />
❌ Cannot modify the sizes of any <Draggable /> or <Droppable />
❌ No screen reader announcement yet
