### ISSUE TITLE
 Can't resolve 'react-dnd/lib/DragDropContext' 

### ISSUE THREAD

**Issue by ravi123shanker** [atlassian/react-beautiful-dnd#1144]
/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
Module not found: Can't resolve 'react-dnd/lib/DragDropContext' in '/GitRepo/node_modules/frontend-collective-react-dnd-scrollzone/lib'

Please help. My app is crashing.

**Comment by TrySound** [comment]
@ravi123shanker This is a different library. Ask in https://github.com/react-dnd/react-dnd

**Comment by ravi123shanker** [comment]
@TrySound Thanks.
