### ISSUE TITLE
Set max level of nesting to 1

### ISSUE THREAD

**Issue by eddyhdzg** [atlassian/react-beautiful-dnd#1150]
I want to make a tree with only one level of nesting

My idea is to make children not nestable, any ideas on how to do this?

This is the code I have now [https://codesandbox.io/s/v6m657wk70 ](https://codesandbox.io/s/v6m657wk70 )

**Comment by alexreardon** [comment]
For `@atlaskit/tree` questions you will need to head over here: https://ecosystem.atlassian.net/servicedesk/customer/portal/24

**Comment by antoniojps** [comment]
@eddyhdzg Have you found a solution? I'm having the same issue.
