### ISSUE TITLE
Please remove noisy console message in development.

### ISSUE THREAD

**Issue by iMerica** [atlassian/react-beautiful-dnd#1152]
Hi,

Thanks for building this, I'm really liking it so far except for one thing:

<img width="948" alt="Screen Shot 2019-03-10 at 9 53 32 PM" src="https://user-images.githubusercontent.com/487897/54097622-07aa0000-437f-11e9-9c08-2df7b3b731fb.png">

It's not appropriate to pollute everyones console with noisy messages like this. According to my count (`find . -name 'package.json'  | wc -l`), I have 1,855 dependencies in my project and out of all of these dependencies, only ONE is polluting my console with messages by default: `react-beautiful-dnd`.

I shouldn't have to enable production builds in my webpack configuration just to make one dependency not emit a noisy marketing banner 😃 .

Thank you,

Michael

**Comment by alexreardon** [comment]
Here you go: https://github.com/atlassian/react-beautiful-dnd#disable-warnings

**Comment by alexreardon** [comment]
Also, it is not a marketing banner. Nested scroll containers is not supported and can lead to bugs 👍

**Comment by alexreardon** [comment]
I linked to the issue in the message to show that we plan on overcoming the limitation

**Comment by alexreardon** [comment]
Perhaps we could add a link to the disable warnings guide in the messages? Thoughts @iMerica ?

**Comment by iMerica** [comment]
Maybe the warnings could look a little less banner-y and more warning-y

For example, in React:

![console2](https://user-images.githubusercontent.com/487897/54103115-25845e80-4399-11e9-8edc-efaf61f35d0e.png)

### Proposed changes
- Remove the "react-beautiful-dnd" green text so this warning looks less like an advertisement and more like a warning.
- Replace "This is a development only message." with "This is a development only warning"
- Example: 
<img width="1009" alt="Screen Shot 2019-03-11 at 1 08 38 AM" src="https://user-images.githubusercontent.com/487897/54103408-51ecaa80-439a-11e9-8c2f-13e594361a9f.png">

**Comment by iMerica** [comment]
Looks like the next version of React will include a native way of reporting these things so they look consistent (the crux of this issue).

https://github.com/facebook/react/pull/15170 

cc/ @alexreardon
