### ISSUE TITLE
disable items snapping together

### ISSUE THREAD

**Issue by Robert-Fish** [atlassian/react-beautiful-dnd#1153]
Is disabling snapping to each other for items possible?

**Comment by alexreardon** [comment]
Can you please provide a bit more information? I am not sure what snapping to each other means :D

**Comment by Robert-Fish** [comment]
Currently in a horizontal list, all the items allow no whitespace to exist between them. How can i make it so that they can be dropped freely anywhere in the list?

**Comment by alexreardon** [comment]
They should be able to be dropped anywhere in the list..

**Comment by alexreardon** [comment]
Feel free to reopen if you need some more input
