### ISSUE TITLE
For vertical lists layout, is it possible to merge multiple vertical lists dynamically into less number of lists depending on screen-width and using breakpoints, so the lists don't overflow the page ?

### ISSUE THREAD

**Issue by lokeshkanagala** [atlassian/react-beautiful-dnd#1155]
## Bug or feature request?
Feature Request
 For vertical lists layout, is it possible to merge multiple vertical lists dynamically into less number of lists depending on screen-width and using breakpoints, so the lists don't overflow the page ? **For example, scenarios like, show 3 columns on `lg`,  merge them to 2 columns in `md` ?**

**Comment by alexreardon** [comment]
I am not following sorry. Can you please provide some more context?

**Comment by lokeshkanagala** [comment]
Ah. Sorry. I have a 3 column layout and wanted to achieve a CSS masonry kind of layout with left-to-right content flow. Any idea what's the effective way to achieve this? Sorry to mark it as issue, thought this is the right way to get opinions. 

For example, my 3 column layout looks like this..consider the numbers to be actual widgets(Draggables)
[
1 2 3
4 5 6
7 8 9
]

If window is minimized, I want the number of columns to be two, so the content fits on the screen and also want to keep the left-to-right ordering.
[
1 2
3 4
5 6
7 8
9
]

**Comment by alexreardon** [comment]
You could use `flex-wrap` or `grid`. Grid is currently not supported #1009 

You *could* get your feature working by rendering different layouts for different break points. They key is that a single droppable cannot wrap right now. So you would only be able to reorder within a single row

**Comment by lokeshkanagala** [comment]
Yep. Got you. Thanks Alex.
