### ISSUE TITLE
Draggable snapshot dropAnimation.moveTo the place it was dropped

### ISSUE THREAD

**Issue by cocacrave** [atlassian/react-beautiful-dnd#1157]
Is it possible to drop the draggable without animating?
I'm removing an item from list if dropped onto a specific droppable but it tries to animate it to the center of that droppable.
I checked the `snapshot` of the draggable's `dropAnimation` and its `moveTo` property is set to some `x` and `y`. Would it be possible to set it to the last `translate(x,y)` value on certain conditions?

A workaround would be great. Thanks!

**Comment by alexreardon** [comment]
Here you go :)

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/drop-animation.md

**Comment by ajainarayanan** [comment]
@alexreardon The example you have linked only removes the animation. The issue of dropping the draggable at the same place it was dropped still seems to be not possible (or not from the example). Is it possible to provide an example on how to get the moveTo be the x, y of the cursor where it is dropped?
