### ISSUE TITLE
Dragging between two lists with each list in a different component file

### ISSUE THREAD

**Issue by Robert-Fish** [atlassian/react-beautiful-dnd#1159]
Is it possible to drag and drop between two list with each list  in a different file?

**Comment by alexreardon** [comment]
I'm not sure what you mean

**Comment by Robert-Fish** [comment]
If i have two lists and i want to allow drag and drop between the lists but they exist in different components, what can i do to allow the drag and drop between the lists. I know the example file shows them in the same component.

**Comment by alexreardon** [comment]
It should just work. As long as they are in the same `DragDropContext` and have the same `type`

**Comment by Robert-Fish** [comment]
Do they have to be direct children of the dragDropContext?

**Comment by vitorcominato** [comment]
I have the same problem, it is possible to comunicate betwwen two dragDropContext?
