### ISSUE TITLE
RFD: shouldRespectForceTouch default value

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#1160]
## Background

`react-beautiful-dnd` ties to respect standard browser interactions as much as possible. Currently, the library plays well with force touch interactions:

> If the user force presses on the element before they have moved the element (even if a drag has already started) then the drag is cancelled and the standard force press action occurs. For an anchor, this is a website preview.

Unfortunately, heavy presses can cancel a drag. It can be tricky at times to get the right amount of pressure to correctly use touch dragging. This can be frustrating for users.

**We have added an option for you to opt-out of respecting force touch interactions**. This option will disable force press interactions on the *drag handle*. However, it allows for a more consistent touch dragging interaction.

## Question

Right now `shouldRespectForceTouch` defaults to `true` in order to respect browser interactions. However, for this specific use case, I am thinking that the default could be to not respect force touch in order to have a more consistent touch dragging experience out of the box.

**Comment by alexreardon** [comment]
In case the existing behaviour is not clear:

If the user has already moved a dragging item then force press events are prevented.

What `shouldRespectForceTouch` does is prevent force touch events when lifting and before any movement has occurred

**Comment by markbrown4** [comment]
It won't be a surprise but `shouldRespectForceTouch: false` makes most sense as a default to me.

FWIW I asked a few people around the office to try and use the Draggable with it enabled and they weren't able to - It's natural for someone intending to drag something to press hard.
It seems like the force touch interaction is getting in the way of the core function of the library.

Appreciate the update, we can remove our patch and use the prop now 👍

**Comment by alexreardon** [comment]
I am thinking the same thing @markbrown4. My current thinking is that in the next major version I will flip the default value

**Comment by alexreardon** [comment]
This is going out in 11.0
