### ISSUE TITLE
New version of RBD logs too much errors

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#1163]
I wrap all of my app with `<DrapDropContext>` to perform drag and drops everywhere.
I upgraded to the last version of react-beautifull-dnd. 

Right know when a child component has an error while developping, my console is overflowed with react-beautifull-dnd errors like this :

![image](https://user-images.githubusercontent.com/25119847/54272388-e49c6d80-4583-11e9-8eec-9e12ecbea349.png)

# Do you know a way to fix it ? 

Thanks for your help !

**Comment by alexreardon** [comment]
Can you please expand the error and paste the stack trace?

Is there any other message text?

**Comment by Aarbel** [comment]
@alexreardon 

As you can see the error is not inside RBD, but inside the component i am working on `<PopupFileVersions>`. 
Here it's just a simple undefined variable `onClose` error, but it's loggued by RBD.

![image](https://user-images.githubusercontent.com/25119847/54281151-634fd580-4599-11e9-9422-1564bb12fe8c.png)

**Comment by alexreardon** [comment]
Is this still an issue? It looks like `react-dom` double renders errors which is kind of lame. I did some work in `11.0` to clean this up somewhat. I would be interested to know if it is more acceptable now

**Comment by alexreardon** [comment]
I'll close this for now, but we can reopen with some more info

**Comment by Aarbel** [comment]
I'll check thank you @alexreardon
