### ISSUE TITLE
Uncaught Error: Invariant failed: Cannot unregister Droppable with id

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#1165]
I'v got this error, do you know a way to fix it ?

Looks like bad behavior with react unmounting

```
Uncaught Error: Invariant failed: Cannot unregister Droppable with id STUB as as it is not registered
```

![image](https://user-images.githubusercontent.com/25119847/54292232-19bdb580-45ae-11e9-9386-0fbdd8f64b26.png)

**Comment by zainxyz** [comment]
I agree, I've been running into the same error.

In my case, we have two views. One that displays a list of Accordions (view-1), and another which lets the user 'edit' and move them around (view-2).

In `view-2`, after moving reordering the accordions, and clicking 'save', we redirect the user back to `view-1`. During the redirect cycle, we run into a similar error, about the rearranged droppables that we touched in `view-2` not being able to unregister.

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by Aarbel** [comment]
@alexreardon 

I was displaying two `Droppable` zones with the same id (one was displayed by a popup above the other one). So RBD was confused to unmount them.

**Comment by alexreardon** [comment]
I am glad you got it sorted
