### ISSUE TITLE
After dragging a Dragable and let it go in Dropable, it has no margin, but after half a second the margin gets applied instantly.

### ISSUE THREAD

**Issue by SelfDevTV** [atlassian/react-beautiful-dnd#1168]
## Bug or feature request?

Bug

When I drag my card around and let go, it takes a while after it applies the margin (about half a second). So there is a some weird lag after dropping ends. 
It's hard to describe but you can play around with it in the demo and see what I mean.
At first I thought it had to do something with JSS so I switched to styled-components but still same problem. 

### Expected behavior

When I move a card it should smoothly go into position without a margin applied after half a second.

### Actual behavior

When I move the card from the example and I let go in a droppable, there is no marginBottom at first, but after about half a second the margin gets applied instantly. 

### Steps to reproduce

Move the cards from the demo inside the lists around a bit. If you drag a card to the bottom of the list you won't see that behaviour. 

### What version of `React` are you using?

^16.8.3

### What version of `react-beautiful-dnd` are you running?
^10.1.0
Also tried with one version below, same behaviour. 

### What browser are you using?
Google Chrome - newest version

### Demo

https://selfdevtv.github.io/trello-clone/

And the github Repo with the code: https://github.com/SelfDevTV/trello-clone
It's the "DND" branch.

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by SelfDevTV** [comment]
Hi,

I have created an example: https://codesandbox.io/s/xp32j520rz?fontsize=14

The only thing I changed was on line 27

`margin: 8,` from `margin: 0 0 ${grid}px 0`

Now you can see the behaviour I mentioned.

**Comment by alexreardon** [comment]
It has to do with margin collapsing:

https://codesandbox.io/s/l54no9x1y7

Ensure there is no margin collapsing and you will be good to go

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#unsupported-margin-setups
