### ISSUE TITLE
Remove Warning : DroppableProvided > placeholder could not be found

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#1170]
```
Droppable setup issue: DroppableProvided > placeholder could not be found. Please be
sure to add the {provided.placeholder} Node as a child of your Droppable

More information: https://github.com/atlassian/react-beautiful-dnd#1-provided
droppableprovided
```

1. `https://github.com/atlassian/react-beautiful-dnd#1-provided-droppableprovided` is a dead link
2. I don't want to use `{provider.placeholder}` and don't want to show a space under the droppable, how can i remove this warning ? 

Thanks for your help ! 

![image](https://user-images.githubusercontent.com/25119847/54381978-50b7c800-468f-11e9-8441-c08903dc45f3.png)

**Comment by alexreardon** [comment]
Please update to 10.1 It will then not be a dead link

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#1-provided-droppableprovided
