### ISSUE TITLE
Question: How to put drag anchor on top-left of draggable ? 

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#1172]
For the moment the drag anchor is centered in the `Draggable` component.

Is there a way to put it on top left ? 

Thanks a lot for your help

**Comment by n8-sd** [comment]
In the [egghead demo,](https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd) there's a section on [draghandle](https://egghead.io/lessons/react-designate-control-of-dragging-for-a-react-beautiful-dnd-draggable-with-draghandleprops) props.

If you set this and add the element to the top left of your `Draggable` component you'll acheive what you want.

**Comment by alexreardon** [comment]
Thanks @n8-sd!
