### ISSUE TITLE
Creating whitespace items between

### ISSUE THREAD

**Issue by Robert-Fish** [atlassian/react-beautiful-dnd#1175]
Is it possible to have whitespace items between items?

**Comment by ldwstyle** [comment]
> Is it possible to have whitespace items between items?

how to have whitespace items between items? thank you

**Comment by alexreardon** [comment]
You can put a `margin` on items. Also, you could have `Draggable`s that are just white between other `Draggable`s 💃🔥

Is that what you are after?
