### ISSUE TITLE
draggableSnapshot.draggingOver when dropping over nothing

### ISSUE THREAD

**Issue by zmi-jlblatt** [atlassian/react-beautiful-dnd#1178]
## Bug
The behavior of `draggableSnapshot.draggingOver` seems to have changed in `10.1.0`.  I updated from `10.0.3` and found that when dropping an item outside of a droppable area,
`draggableSnapshot.draggingOver` now reports the source droppable id, instead of `null`.  This occurs only while `draggableSnapshot.isDropAnimating` is `true` - the value is `null` before and after the drop.  

To me this makes it impossible to discern a drop outside of the source container vs. a drop inside of it.  I am using a combination of `draggingOver` and `isDropAnimating` to apply a class to the draggable item while it is animating, but only when dropped outside of it's source container.  It also seems inconsistent as the value is `null` before and after the drop, while I am outside of valid droppable containers.  It still correctly reports the ids of droppable containers as I am dragging/dropping over them.

Thanks in advance, stellar library overall 👍 

### Expected behavior
`draggingOver === null` <--- this is the behavior in `10.0.3`

### Actual behavior
`draggingOver === "[droppable_id_of_source_container]"` <--- this is the behavior in `10.1.0`

### What version of `React` are you using?
`16.8.0`

### What version of `react-beautiful-dnd` are you running?
`10.1.0`

**Comment by alexreardon** [comment]
This was intentional but not thought through fully. The hooks still report `null` as the destination, but I did not anticipate the draggable snapshot being used like this

**Comment by zmi-jlblatt** [comment]
No worries, thanks for checking it out.  `10.0.3` works for our purposes right now, but I do like the animation changes in `10.1.0`.  I could likely work around this issue via `onDragEnd` if I get the time, but still wanted to raise it as it seemed counter-intuitive to me.

**Comment by alexreardon** [comment]
I have a fix for this that should be landing in `10.1.1`

**Comment by zmi-jlblatt** [comment]
Great news, thanks so much!

**Comment by alexreardon** [comment]
I hope to do a patch release tomorrow @zmi-jlblatt

**Comment by zmi-jlblatt** [comment]
Many thanks again!
