### ISSUE TITLE
Destination null when dropping onto a smaller area

### ISSUE THREAD

**Issue by lulious** [atlassian/react-beautiful-dnd#1182]
## Bug or feature request?
Hey, I'm trying to implement a pretty basic feature but I'm stuck for some reason. The idea is to let users drag an item onto a trash can to delete it. I already implemented dnd for moving items around and it works perfectly, all I did now was I added a second droppable and put the icon inside of it. For some reason though when I drop onto it, I get destination: null. It might have something to do with the width of each droppable. when the width of the draggable is smaller than the droppable, the destination is null?
Is there something I'm missing here? It could be a bug or maybe you're just supposed to use icons as droppables in a different way. And is width really an issue?

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by alexreardon** [comment]
It might be an area thing: try dropping the center of the dragging item onto your trash bin. If that works, try increasing the space your trash bin Droppable element takes up, even if it is visually the same size

**Comment by alexreardon** [comment]
This is related to #930
