### ISSUE TITLE
Nested dropp and draggables with different types

### ISSUE THREAD

**Issue by entiendoNull** [atlassian/react-beautiful-dnd#1183]
### Expected behavior
I wish to be able to drag an item into any droppable.

### Actual behavior
I have several nested draggables and droppables.

![Screen Shot 2019-03-20 at 09 50 31](https://user-images.githubusercontent.com/13820994/54671168-a65bfc80-4af5-11e9-8df5-f19603c9882b.png)

Let me explain:

- Blue container is a droppable
- Black container is droppable and draggable
- Red container is droppable
- Green container is draggable

I can:
- Switch place of a black container within the blue container
- Switch place of a green container within a red container
- Switch a green container from a red container to another red container

I can't:
- Drag a green container into the blue container
- Drag a green container into the black container

If I:
- Drag a green container into the black container the `destination` will still be the green container's original red container.
- Drag a green container into the blue container `destination` is null

### Goal

I want to:

- Be able to drag a green container into blue, black red containers
- Be able to drag a green container from a blue container into a black or red container. That said, it should also be able from the other way around.
- Be able to swap places between black containers, but not drag a black container into another black container

Facts:

- A green container will always be wrapped in a red container
- A red container will always be wrapped in a black container
- A black container will always be wrapped in a blue container
- 

I planned to handle that logic by updating my state accordingly when an item is dropped.

### Thoughts

I have been playing around with setting `type` on the droppables. But no combination seems to give me the outcome that I am hoping for. I am unsure if what I am hoping to achieve does not fall under the scope for this library.

Any guidance is much appriciated.

### What version of `React` are you using?

16.8.0

### What version of `react-beautiful-dnd` are you running?
^10.1.0

**Comment by alexreardon** [comment]
Thanks for all this detail. Right now we do not support multi-level drop. We can track it here: #1001

**Comment by alexreardon** [comment]
I think that is what you are after. Let me know if that is not the case

**Comment by entiendoNull** [comment]
Hey Alex, thanks for your reply :)
I did begin to write own logic to achieve my very specific use case. It's not done yet however. Your library provided some really good ideas though.

I will definitely check your recommendation out. I'll get back to you. 

Keep up the great work :)

**Comment by ishikaagarwal25** [comment]
Hey @entiendoNull I know it’s been years but did you manage to figure out a solution? We are stuck with the exact same issues in the same usecase with beautiful dnd. Any help will br highly appreciated.

**Comment by entiendoNull** [comment]
> Hey @entiendoNull I know it’s been years but did you manage to figure out a solution? We are stuck with the exact same issues in the same usecase with beautiful dnd. Any help will br highly appreciated.

Hey, 

I did resolve the issue at the time, but not with this library (which has also been deprecated now it seems). I wrote an own solution that accomodated all our needs.

I would probably have a look at react-dnd instead if I were to do the same thing again today.

Best regards
