### ISSUE TITLE
How to change animation for dragged over items

### ISSUE THREAD

**Issue by DhirajKhot** [atlassian/react-beautiful-dnd#1185]
## Bug or feature request?

Feature 

### Expected behavior

When an item is being dragged in the list, the dragged over items should remain intact to their position until the dragged item is not released at the target location. Once it is released then the all the items (except the one being dragged) should animate and move away to make a place for the dragged item at the target location.

### Actual behavior

When an item is being dragged in the list, the dragged over items animate and move away making place for the dragged item (placeholder is created) even when the dragged item is not released.

### What version of `React` are you using?
^16.4.0

### What version of `react-beautiful-dnd` are you running?
^10.1.0

### What browser are you using?
Chrome, Edge, IE

### Demo

Please check this demo, I want the exact same functionality.

[To-do DnD.zip](https://github.com/atlassian/react-beautiful-dnd/files/2995131/To-do.DnD.zip)

**Comment by DhirajKhot** [comment]
Hello @alexreardon. I have attached a demo. This might be helpful.

**Comment by alexreardon** [comment]
Hi there!

Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

That way I can just open it in a browser and have a play

Cheers!

**Comment by DhirajKhot** [comment]
Hello @alexreardon  
Can you please help me understand the information you need? 
I checked the link you mentioned and it already has an example (10 items - item 0 to 9 can be dragged and dropped ).

**Comment by alexreardon** [comment]
I generally do not run projects on my computer. But I can see that the zip file is a .mov file. 

We avoid this style of interaction as it goes against our [guiding design principle](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/design-principles.md) of physicality. In the real world items move out the way naturally.

This is the design language that we are supporting. You are welcome to try and hack it though 🕺
