### ISSUE TITLE
Warning: Prop `data-react-beautiful-dnd-droppable` did not match. Server: "9" Client: "0"

### ISSUE THREAD

**Issue by ravinder-aika** [atlassian/react-beautiful-dnd#1196]
## Bug?
Showing the above warning when I implemented that into a simple vertical list.

## My Code

> <DragDropContext onDragEnd={this.onDragEnd}>
                <Droppable droppableId="droppable">
                  {provided => (
                    <div {...provided.droppableProps} ref={provided.innerRef}>
                      {!is_fetching &&
                        posts.map((post, i) => {
                          return (
                            <Draggable
                              key={post.id}
                              draggableId={post.id}
                              index={i}
                            >
                              {provided => (
                                <div
                                  ref={provided.innerRef}
                                  {...provided.draggableProps}
                                  {...provided.dragHandleProps}
                                >
                                  <PostContainer
                                    pagination={pagination}
                                    index={i}
                                    is_edit={true}
                                    is_post_immediately={true}
                                    can_rearrange={true}
                                    key={`post_${i}`}
                                    post={post}
                                    className="mb-2"
                                  />
                                </div>
                              )}
                            </Draggable>
                          );
                        })}
                      {provided.placeholder}
                    </div>
                  )}
                </Droppable>
              </DragDropContext>

## Version 

> "react-beautiful-dnd": "^10.1.0"

**Comment by alexreardon** [comment]
Hi @ravinder-aika,

Please see [`resetServerContext](/docs/api/reset-server-context.md)

**Comment by kayluhb** [comment]
That link actually returns.

```
Not Found
```

Correct URL is https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/reset-server-context.md

**Comment by Chris533** [comment]
https://github.com/mbrn/material-table/issues/1453#issuecomment-588103879

**Comment by commanderz** [comment]
Another solution:

```
const [isBrowser, setIsBrowser] = useState(false);

useEffect(() => {
  setIsBrowser(process.browser);
}, [])

function Home() {
  return(
   <>
    {isBrowser ? <DragDropContext> { /* all rbd code */ } </DragDropContext> : null}
   </>
  )
}
```
