### ISSUE TITLE
Architectural Question

### ISSUE THREAD

**Issue by OmriAharon** [atlassian/react-beautiful-dnd#120]
First of all - great library! Thank you for this.

Out of all the examples I've seen, the Droppable/Draggables existed in the same place with the DragDropContext - thus making reordering logic very straightforward.

In my app, as you suggested, I would place the `DragDropContext` in `App.js` - topmost file that renders the app (well, almost, main route that envelops all others).

The drag & drop part, though, exists in some of the other routes, and could even get to up to 10 hierarchies down the chain. What is your suggested way to use the `onDragEnd`, since you suggest to never change that function once it's registered? 
Ideally, I'd like this to reside as close as possible to the drag & drop components.

As I see it today, my `onDragEnd` is in `App.js`, and doing the logic with the list of items which are so far below looks very out of place. I'd have to access redux and do the changes there. If I have multiple drag & drop areas in my app, I'd have to do a switch case to recognize where the drag & drop is happening.

How do you suggest to handle this real-world scenario?

**Comment by alexreardon** [comment]
Hi @OmriAharon there are lot of different ways you could go about this. You mentioned that you are using `Redux`. My suggestion would be to fire an `action` from within your `onDragEnd` function and then do the correct update in your `reducer`. You could break your reducer down into sub reducers to handle changes in a targeted way. You will know what needs updating by looking at the `type`, `source`, and `destination` values of the `onDragEnd` function call. At some point you will need a conditional (such as a `switch`) to determine which list needs updating in your application. This can be done in your `reducer` / sub reducers.

The situation would be different if you did no have a global state container: eg redux.

**Comment by ianschmitz** [comment]
@alexreardon How would you suggest handling the case for users without Redux/MobX etc? I share the same scenario as @OmriAharon.

Thanks!

**Comment by alexreardon** [comment]
It depends on where you are storing your state. There are too many possible combinations for me to go through them all. The gist would be you need to publish the change to where the data is so that you can update the lists.
