### ISSUE TITLE
Columns overlapped when start dragging in the board example

### ISSUE THREAD

**Issue by lukyth** [atlassian/react-beautiful-dnd#1201]
## Bug or feature request?

Bug

### Expected behavior

When start dragging a board at https://react-beautiful-dnd.netlify.com/?path=/story/board--scrollable-columns on a small width screen, "Finn" and "Princess bubblegum" column are not overlapped.

### Actual behavior

"Finn" and "Princess bubblegum" column will be overlapped when start dragging.

### Steps to reproduce

1. Visit https://react-beautiful-dnd.netlify.com/?path=/story/board--scrollable-columns
2. Reduce the browser width until "Princess bubblegum" column is out of the viewport.
3. Start dragging "Jake" or "BMO" column.
4. "Finn" and "Princess bubblegum" column will be overlapped.

### What version of `React` are you using?

16.8.5

### What version of `react-beautiful-dnd` are you running?

10.1.0

### What browser are you using?

Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### Demo

<img width="663" src="https://media.giphy.com/media/1pAhA4Hqfu3yegu59s/giphy.gif">

Not sure if this's related to https://github.com/atlassian/react-beautiful-dnd/issues/131 and https://github.com/atlassian/react-beautiful-dnd/issues/268 or not. But this's probably not the same issue as those two imo 😅

**Comment by driescroons** [comment]
Running into the same problem. I had setup multiple demos to check if it was just my incompetence 😄 
https://codesandbox.io/s/rlx319390q

**Comment by alexreardon** [comment]
This is fixed in 11.0.4

**Comment by lukyth** [comment]
Thanks! 💯
