### ISSUE TITLE
Quick Question: How To

### ISSUE THREAD

**Issue by lifeiscontent** [atlassian/react-beautiful-dnd#1204]
I'm implementing a Window Splitter with react-beautiful-dnd

I noticed you guys extend react-beautiful-dnd with your tree component so I'm wondering if its possible to do something like this.

a few concepts:

WindowSplitter - The Window Splitter Container
WindowSplitterResizer - The Element to Resize a Pane
WindowSplitterPane - The Pane

Tabs - Tabs component to hold many windows
TabsNav - Container
TabsNavList - List for Tabs
TabsNavListItem - Tab Item
TabsNavHandle - Handle to drag all tabs in list
TabsPanel - Window Container

Window - Generic view container (anything can go here)

I'm wondering how to use react-beautiful-dnd to handle the case where someone Drags a TabsNavListItem onto the TabsPanel and how to visually inform a user of the direction the Tab will split into e.g. Up/Down/Left/Right kind of like how VSCode does window splitting.

is this possible? currently in react-beautiful-dnd you can specify a direction and you need to specify a placeholder but is there a way to customize the display of the placeholder and potentially patch this functionality to support multiple split directions?

**Comment by alexreardon** [comment]
I am not sure this is the best forum for this discussion. It is hard to answer you well as I am not sure what each of your components map to visually and what visual experience you are trying to achieve

**Comment by lifeiscontent** [comment]
@alexreardon basically, I'm recreating the UX of Visual Studio Code

it has tabs, and if you drag one of those tabs into a code editor it splits the tab into a new pane

**Comment by alexreardon** [comment]
I suspect you can, but it hard to tell for sure without seeing a more mature standalone example

**Comment by alexreardon** [comment]
Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
