### ISSUE TITLE
shouldn't this be touchSensor instead of mouseSensor?

### ISSUE THREAD

**Issue by lifeiscontent** [atlassian/react-beautiful-dnd#1206]
https://github.com/atlassian/react-beautiful-dnd/blob/67b96c8d04f64af6b63ae1315f74fc02b5db032b/src/view/drag-handle/drag-handle.jsx#L205

**Comment by alexreardon** [comment]
Yep! I have fixed this in the hooks branch

**Comment by alexreardon** [comment]
We do things a bit differently

**Comment by lifeiscontent** [comment]
@alexreardon I've been spending some time learning how react-beautiful-dnd works.

do you know how I could change the way placeholder works so I can visualize to my users that if they drag a `Tab` into a `Pane` it'll potentially split into 2 Panes depending on the direction that they drop it in.

**Comment by alexreardon** [comment]
This is fixed in #1208 so I won't action this issue directly.

**Comment by alexreardon** [comment]
@lifeiscontent I am not totally across the effect you are after. Can you please provide some more information?
