### ISSUE TITLE
when I drag card,the bottom card move

### ISSUE THREAD

**Issue by ldwstyle** [atlassian/react-beautiful-dnd#1214]
example1：
when I drag card,the bottom card don't move
![TIM图片20190403181705](https://user-images.githubusercontent.com/30330931/55471695-eb774700-563c-11e9-931f-d1001f52b752.png)

example2:
when I drag card,the bottom card  move
![TIM图片20190403181801](https://user-images.githubusercontent.com/30330931/55471729-f9c56300-563c-11e9-935b-792c7c5c1974.png)

how to achieve the example1?(如何实现例子1中的效果？)

**Comment by alexreardon** [comment]
This behaviour changed in [`10.1.0`](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0)

You can read more about the change here: [beautiful interactions](https://medium.com/@alexandereardon/beautiful-interactions-8f67502ccf73)
