### ISSUE TITLE
Testing with jsdom and react-testing-library

### ISSUE THREAD

**Issue by lourenci** [atlassian/react-beautiful-dnd#1215]
Hi. Thanks for the library.

I'm trying to move a Draggable in `jsdom` with `react-testing-library` and I'm getting this error:

![image](https://user-images.githubusercontent.com/2339362/55494522-4c892580-5611-11e9-9965-e0fca9a2ac56.png)

Do you guys know anything about this error? It looks like something related with `css-box-model`. It just happens when I try to move the Draggable. All other specs are ok.

```js
fireEvent.keyDown(card, { key: 'Tab', keyCode: 9, which: 9 })
fireEvent.keyDown(card, { key: ' ', keyCode: 32, which: 32 })
fireEvent.keyDown(card, { key: 'ArrowRight', keyCode: 39, which: 39 })
fireEvent.keyDown(card, { key: ' ', keyCode: 32, which: 32 })
```
I tried to move through `mouseMove` too.

Thank you.

**Comment by alexreardon** [comment]
Because we use `window.getComputedStyles` and `element.getBoundingClientRect` you will need to mock these DOM apis. Currently jsdom does not support these well.

We do this all over this place in our tests, and here is one example:

https://github.com/atlassian/react-beautiful-dnd/blob/hooks/test/unit/integration/responders-integration.spec.js#L58-L66

**Comment by colinrcummings** [comment]
@lourenci, did you manage to get this working?

**Comment by lourenci** [comment]
@colinrcummings I gave up. I mocked the library to return the children and to expose some helpers for some unit tests. You can check it out here: https://github.com/lourenci/react-kanban/blob/master/__mocks__/react-beautiful-dnd.js. Although, this will be a problem for who will use the library (if they want to test it). 

The draggable moving itself I tested on Cypress without any big problem. You can check it out here: https://github.com/lourenci/react-kanban/blob/master/cypress/integration/board.spec.js.

**Comment by colinrcummings** [comment]
Thanks for your response, @lourenci. I actually managed to figure something out with `react-testing-library`. @alexreardon, I’d be happy to document it. Would you be willing to give it a look if I make a minimal repo?

**Comment by lourenci** [comment]
@colinrcummings I gave up struggling against `jsdom` issues. I'm looking forward to see your repo, I use `react-testing-library` too.

**Comment by colinrcummings** [comment]
@lourenci, that was the hard part. I'll put the repo together early this week; hopefully it can be useful for issue #623, @alexreardon.

**Comment by colinrcummings** [comment]
@lourenci, I wrapped my approach in [`react-beautiful-dnd-test-utils`](https://github.com/colinrcummings/react-beautiful-dnd-test-utils). It currently supports moving a `<Draggable />` _n_ positions up or down inside a `<Droppable />`, which was my use case. Also see [react-beautiful-dnd-test-utils-example](https://github.com/colinrcummings/react-beautiful-dnd-test-utils-example), which includes an [example test](https://github.com/colinrcummings/react-beautiful-dnd-test-utils-example/blob/master/src/App.test.js). Let me know what you think. cc: @alexreardon
