### ISSUE TITLE
Dragging only within parent container

### ISSUE THREAD

**Issue by stelasido** [atlassian/react-beautiful-dnd#1216]
Hi, thx for the library. Is there a way to drag only inside the parent container ?
For the example, all dragged elements are with the width of its parent and they can't be dragged horizontally,  because of that (outside of the parent container).

**Comment by stelasido** [comment]
I mean restriction to the parent container or X/y axis. I see that there is a way with `react-dnd`, because there is update prop from where you can get the position, but here the prop for updating is not called on movement.

**Comment by alexreardon** [comment]
We currently do not support any locking out of the box as it goes against our [design principles](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/design-principles.md)
