### ISSUE TITLE
Dragging to Bottom of a "Full" Foreign List Not Working

### ISSUE THREAD

**Issue by OmriAharon** [atlassian/react-beautiful-dnd#122]
## Bug or feature request?
Bug - Can't drag to a new list from the bottom when the list is "full" (no extra droppable space)

### Expected behaviour
Should be able to drop to a list from below, and a placeholder should appear.

### Actual behaviour
Can't drop to a new list from its end.

### Steps to reproduce
Please see attached gif.

### Browser version
Version 60.0.3112.113 (Official Build) (64-bit)

### Demo
![dragbelow](https://user-images.githubusercontent.com/12033595/30900114-51f25ab4-a36b-11e7-9a17-36c1dccf29da.gif)

**Comment by alexreardon** [comment]
The quick workaround is to use padding for your list container spacing rather than margins. However, we should fix this so that if you hover over the margin of a list then you are considered in the list

**Comment by gkrinc** [comment]
I updated to v2.6.4 and am still experiencing something similar to OP. When dragging an object from below the droppable I have to drag so far onto the last draggable that the object I'm dragging becomes the second last item in the droppable and then I have to adjust it to become the last item.

If I we're going to add padding/margins to something to help with there where would it go? Would I add padding to the droppable? Would I add margins to the draggables in droppable? Would I adding margins to the draggable that is being dragged?

**Comment by alexreardon** [comment]
Hi @gkrinc, can you please post a link with a reproducible demo of your issue? You can start with our boilerplate here:

https://www.webpackbin.com/bins/-Kr9aE9jnUeWlphY8wsw

**Comment by gkrinc** [comment]
Thanks. I think I figured out where I was going wrong.

By adding a tonne of marginBottom to the droppable it's MUCH easier to drag a new item to the bottom of the droppable. I have an "add" component button at the bottom of that droppable list, which is what was causing some confusion in terms of styling.

Thanks for the amazing library, jumped the gun on asking my question.
