### ISSUE TITLE
Auto-scroll breaks when scroll parent is `overflow: overlay`

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [atlassian/react-beautiful-dnd#1234]
## Bug or feature request?

Bug

### Expected behavior
Auto-scroll should work even if the scroll parent has `overflow: overlay`, just as with `overflow: scroll/auto`

### Actual behavior
Doesn't auto-scroll when the parent container has `overflow: overlay`

### Steps to reproduce

1. Make fixed-height container, that has `overflow: overlay` applied;
2. Make sure that the draggable area has sufficient items inside so that there's something to scroll through;
3. Try to drag & move the top item to bottom of the list (Not so easy, isn't it?)

P.S. For now, `overflow: auto` is used, but it has a less appealing interface now with the flickering when scrollbar shows/hides.

### What version of `React` are you using?

`"react": "16.8.3"`

### What version of `react-beautiful-dnd` are you running?

`"react-beautiful-dnd": "^10.1.0"`

### What browser are you using?

Google Chrome 73.0.3683.103

### Demo

https://codesandbox.io/s/kx079w7ppo

**Comment by alexreardon** [comment]
According to MDN `overflow:overlay` is deprecated

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

Given that it is deprecated, I am not sure if it is worth adding support for

**Comment by alexreardon** [comment]
Thoughts?

**Comment by mbs-zanas-stundys** [comment]
Oh, I didn't know that :) It is a pity, that it won't be fixed, because in my project I'm having a sticky/fixed header that aligns with the columns of the draggable items. I guess i'll have to use padding or something to counter that.

![image](https://user-images.githubusercontent.com/41042117/55776053-17af1f80-5aa4-11e9-99ca-0a2133b2d1d3.png)

**Comment by mbs-zanas-stundys** [comment]
Thanks for the reply :)

**Comment by alexreardon** [comment]
It would be trivial to add support (i suspect)

**Comment by alexreardon** [comment]
But it is a dark path to start adding support for deprecated features

**Comment by gyz0072004** [comment]
As 2 years goes by, overlay is still supported by webkit and blink-based browsers, and they are sharing a big (or say even bigger than 2 years ago) crowd of consumers, shall we re-consider adding support?
