### ISSUE TITLE
aria-roledescription is not read for draggable items

### ISSUE THREAD

**Issue by ccveer** [atlassian/react-beautiful-dnd#1238]
## Bug or feature request?

Bug

### Expected behavior
The aria-roledescription for a draggable item is read by Mac voice over 

### Actual behavior
The aria-roledescription for a draggable item is NOT read by Mac voice over.  It appears that this has also been mentioned as an issue with JAWS in the comments here: https://github.com/atlassian/react-beautiful-dnd/issues/865
![image](https://user-images.githubusercontent.com/49158600/55823272-00355e00-5ac7-11e9-8371-eb73515d4a50.png)

### Steps to reproduce
1. Turn on Mac voice over
2. Open Chrome
3. Navigate to https://react-beautiful-dnd.netlify.com/?path=/story/tables--with-fixed-width-columns
4. Press the "TAB" key on the keyboard until you reach the draggable row
5. Notice that the instructions about how to activate the draggable row are not read

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
Try opening it out of the iframe. Aria in the iframe seems to get confused

**Comment by alexreardon** [comment]
[Out of the iframe](https://react-beautiful-dnd.netlify.com/iframe.html?id=tables--with-fixed-width-columns)

**Comment by alexreardon** [comment]
It seems to only effect the table example

**Comment by alexreardon** [comment]
Let's track it here: #865
