### ISSUE TITLE
Discussion: What should our React peer dep be for 11.0?

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#1244]
I am about to ship `11.0` #1193. I was hoping to have a peer dependency on `React` of `^16.8.0`. We rely on `react-redux@7` which shipped with a peer dependency on `React` of `^16.8.4`. 

So if `react-beautiful-dnd` has a peer dependency is `^16.8.0` and a consumer uses `16.8.0` they will get a big old warning, and perhaps bundler issues. 

I asked if `react-redux` could lower their peer dependency to `^16.8.0` but they have rejected the proposal https://github.com/reduxjs/react-redux/pull/1229.

So either we use `^16.8.0` and potentially give consumers issues, or go up to `^16.8.4` to be in step with `react-redux`.

Maybe there is another option I am not considering?

**Comment by theKashey** [comment]
`16.8.0-4` were not quite usable due to various bugs, especially around enzyme testing.

I would say `^16.8.5`

**Comment by theKashey** [comment]
Oh, it will also force all customers to bump their React version, as long as it's not possible to have two different versions of React since hooks.

**Comment by lukebatchelor** [comment]
I think either solution is fine.

If you use `^16.8.0` and a consumer has `16.8.1` and they get a warning, well, that warning comes from react-redux, and is easily solved, so not a big deal to upgrade.

Likewise, depending on the later version is not really an issue right? Its a major bump already so any consumer is already going to be upgrading, moving the extra 4 patch versions won't make much of a difference.

If I had to choose, I'd probably say `^16.8.0`, for most people it'll resolve to a later version anyway when they bump, for anyone who happens to be on one of those 4 patch versions, it's not a huge deal to bump. :+1:

**Comment by lukebatchelor** [comment]
Ah, given @theKashey 's thoughts, later is fine too. 🤷‍♂️

**Comment by alexreardon** [comment]
It seems like using `16.8.5` is the strongest option right now given the enzyme issues with previous versions

**Comment by alexreardon** [comment]
We went for `^16.8.5`
