### ISSUE TITLE
TypeScript Error with isDragging Prop on Styled Component div element

### ISSUE THREAD

**Issue by smeads** [atlassian/react-beautiful-dnd#1245]
I'm new to react-beautiful-dnd and have enjoyed working with the library thus far.  

I've been following the egghead tutorial and got to the point where you pass down the `isDragging` props to a styled `div`.  However, I get TypeScript errors on the styled component when adding `isDragging` as a prop and when trying to access it for dynamic styling.

I have updated all packages and peer dependencies (see versions below), looked through documentation and other resources to find a resolve, and have attempted to create type interfaces to extend the Styled Components types specifically for the `isDragging` props.

#### Code
![image](https://user-images.githubusercontent.com/18606144/55932288-564cf300-5be6-11e9-939e-bda3e608aec6.png)

#### TS Error on the Component
```
Type '{ children: Element; isDragging: boolean; style?: DraggingStyle | NotDraggingStyle | undefined; 'data-react-beautiful-dnd-draggable': string; ref: (element?: HTMLElement | null | undefined) => any; } | { ...; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | ... 247 more ... | "onTransitionEndCapture"> & { ...; }, "style" | ... 253 more ... | "onTransitionEndCapture"> & Partial<...>, "style" ...'.
  Type '{ children: Element; isDragging: boolean; style?: DraggingStyle | NotDraggingStyle | undefined; 'data-react-beautiful-dnd-draggable': string; ref: (element?: HTMLElement | null | undefined) => any; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | ... 247 more ... | "onTransitionEndCapture"> & { ...; }, "style" | ... 253 more ... | "onTransitionEndCapture"> & Partial<...>, "style" ...'.
    Property 'isDragging' does not exist on type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | ... 247 more ... | "onTransitionEndCapture"> & { ...; }, "style" | ... 253 more ... | "onTransitionEndCapture"> & Partial<...>, "style" ...'.ts(2322)
```

#### TS Error on the `isDragging` prop in the styled component
```
Property 'isDragging' does not exist on type 'ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 246 more ... | "onTransitionEndCapture"> & { ...; }, any>'.ts(2339)
```

I've gone through all my packages to make sure there aren't any unmet peer dependencies.
##### React Beautiful DND - ^11.0.0-beta.3

All TypeScript typing packages are up to date as well.

Again, I've just been following the egghead tutorial and have been blocked by the TypeScript error triggered by passing the `isDragging` props to the styled component.

Let me know if there is anymore information I can provide.

**Comment by alexreardon** [comment]
It looks like a typing issue with styled-components. I suspect there might be some hoops you need to jump through to get the correct typescript type on a styled component

**Comment by alexreardon** [comment]
I think this is what you are after: https://github.com/styled-components/styled-components/issues/630

**Comment by smeads** [comment]
@alexreardon thank you for the quick reply and I apologize for wasting your time. After playing with the interfaces and adding them to the styled div I was able to get it to work.

For anyone who might come across this:

```
interface StyledDivProps {
  isDragging: boolean;
}

const DraggableContainer = styled.div<StyledDivProps>`
  background-color: ${props => (props.isDragging ? "blue" : "#fafafa")};
`;
```
or simply

```
const DraggableContainer = styled.div<{ isDragging: boolean }>`
  background-color: ${props => (props.isDragging ? "blue" : "#fafafa")};
`;
```

@alexreardon thank you for this library!

**Comment by alexreardon** [comment]
You're most welcome!
