### ISSUE TITLE
In case of Multi Drag dragging, behavior differs in above and below areas of the dragged item source location

### ISSUE THREAD

**Issue by DhirajKhot** [atlassian/react-beautiful-dnd#1246]
## Bug or feature request?
I am using this library and implementing multi drag support on top of it referring to the example mentioned in storybook in this repository itself.

On top of it I have added a below change - 
Assume there are 10 tasks in the list and I have selected 3 tasks and start dragging one of it, during the drag the remaining 2 selected tasks should disappear from the list and should come back only after the drop at destination.

I am able to achieve this but I have a slight weird behavior while dragging the Draggable.
During the drag, the tasks in the palette move out and open the area for the dragged task perfectly well in case if I am dragging the item above the source location of the dragged item.
But if I drag the item in below area of the source location of the dragged item, the tasks in the palette are not moving out and open the area for the dragged item correctly. There is a kind of distance before the tasks on the palette start moving. This distance is equal the number of tasks selected for drag.

Please check attached videos for the demo.

Can you help me figure out the reason for such behavior?

### What version of `React` are you using?
16.8.4

### What version of `react-beautiful-dnd` are you running?
10.1.0

### What browser are you using?
Chrome

### Demo

This zip file has 2 videos - one showing the above area (correct behavior)
and the other showing the below area (incorrect behavior)

[Multi Drag issue.zip](https://github.com/atlassian/react-beautiful-dnd/files/3068510/Multi.Drag.issue.zip)

**Comment by DhirajKhot** [comment]
@alexreardon  Can you please help me fix this issue?

Thanks in advance.

**Comment by alexreardon** [comment]
Fascinating! It looks like you are using the dynamic removal/addition behaviour to achieve this

**Comment by alexreardon** [comment]
Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by DhirajKhot** [comment]
Hello @alexreardon Please check this example as requested - 
https://codesandbox.io/s/vq4mol27r0

Hope you can help here. :)

**Comment by DhirajKhot** [comment]
Hello @alexreardon Did you get a chance to have a look at this issue?
Please let me know if you need any more information.

Thanks in advance :)

**Comment by alexreardon** [comment]
I hope to look into this today

**Comment by alexreardon** [comment]
Here is your error:

> Invariant failed: Can only recollect Droppable client for Droppables that have a scroll container

You are currently violating one of our rules:

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/changes-while-dragging.md#rules
