### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by PBDCompany** [atlassian/react-beautiful-dnd#1247]
## Bug or feature request?

Bug

### Expected behavior

I took the community made example from https://codesandbox.io/s/ql08j35j3q and tried adding it to my project.

### Actual behavior

The component doesn't render, instead the page crashes with the error 'Object(...) is not a function'.

### Steps to reproduce

Copy the example from https://codesandbox.io/s/ql08j35j3q, instead of user ReactDOM.render export the class and use it inside another component.

### What version of `React` are you using?

16.7.0

### What version of `react-beautiful-dnd` are you running?

11.0.0-beta.3

### What browser are you using?

Chrome

### Demo

I created a demo but the error didn't reproduce.
![Screenshot_1](https://user-images.githubusercontent.com/45166438/55971185-a3ce6c00-5c89-11e9-8ba1-53ef57decadf.png)

EDIT: I rolled back to version 10.1.1 and now everything works. If you need more details I'll happily provice.

**Comment by alexreardon** [comment]
For the beta you will need react > 16.8 👍

**Comment by DawnPaladin** [comment]
I had the same problem. It took me a few hours to find this issue and @DatrixCompany's solution (thank you!) I was using React 16.6.3 and react-beautiful-dnd 11.0.1, which was the version Yarn installed by default.

Can something be done to prevent future coders from having this problem? `yarn install react-beautiful-dnd` shouldn't install an unusable version.

**Comment by alexreardon** [comment]
This was a mistake in publishing the betas. I was not aware that they needed to be published on a separate npm channel. I am not sure if these old versions should be purged or not. They correctly state their peer dependency..

**Comment by BhavyaLight** [comment]
Faced this issue and checked the github bug list and found this solution luckily
