### ISSUE TITLE
How can I stop auto scrolling when I mouse over some element？

### ISSUE THREAD

**Issue by yangchch6** [atlassian/react-beautiful-dnd#1252]
### Expected behavior
- Stop auto scrolling when I mouse over some element。And ondrop event can be triggered when the mouse key is released。

I want to realize function like this, but I don't know what event should be added on the delete button.
![image](https://user-images.githubusercontent.com/33412781/56024075-da67bd80-5d41-11e9-9853-721069f8747f.png)

### What version of `react-beautiful-dnd` are you running?
- v 9.0.2

### What browser are you using?
- Chrome

### Demo
```
<Droppable droppableId={`droppable_${id}`} direction='vertical'>
          {(provided, snapshot) => (
            <div ref={provided.innerRef} key={id} className={`${prefixCls}-content`}>
              {/* Animate component is a list container. And it's scrollable. */}
              <Animate
                component="ul"
                transitionName={this.state.mounted ? `${prefixCls}-content-item-highlight` : ''}
                transitionLeave={false}
              >
                {showItems}
              </Animate>
              {/* div component is the delete button at the bottom of container */}
              <div 
                className={dragging ? `${prefixCls}-delete-selected-btn` : ''}
                ondragenter={()=>{debugger}} //ondragenter and ondrop events won't be triggered when the mouse key is released。
                ondrop={this.handleDeleteSelected}
                >
                <Icon type="uf-del"></Icon>
              </div>
            </div>
          )}
        </Droppable>
```

**Comment by alexreardon** [comment]
Interesting! We do not support this, but you might be able to hack it. 

Our auto scroller triggers scroll events on scroll containers and on window. You could try to block these updates. 

This might be helpful: https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily

**Comment by yangchch6** [comment]
> Interesting! We do not support this, but you might be able to hack it.
> 
> Our auto scroller triggers scroll events on scroll containers and on window. You could try to block these updates.
> 
> This might be helpful: https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily

Thank you. By the way,can I use the multi-drag and single-drag functions in the same time？

**Comment by alexreardon** [comment]
yep - have a play with our multi drag example: https://react-beautiful-dnd.netlify.com/iframe.html?id=multi-drag--pattern

And here is our guide: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

**Comment by jooj123** [comment]
@alexreardon we use react dnd here at Domain - wondering if you can give us some rough pointers on how we would support this if we opened a PR ? 
We need it for a specific use case 

cc @kyawsiesein

**Comment by alexreardon** [comment]
👋 Hey! Where abouts on domain? It would be cool to have a play!

Did you mean `react-beautiful-dnd`? If it is `react-dnd` then I won't be able to help you here 😊.

I think you should be able to achieve what you are after by adding your own scroll listener.

Something like this: (it might not run, i am just typing it straight into the textbox)

```js
function onScroll(event) {
  // get what element the user is currently over
  // if the user is over the element you don't want to scroll from
  // then call event.preventDefault();
}

// capture: true, do this so *all* scroll events bubble up to the listener
// passive: false: we want to be able to block scrolling.

// You only need to have this bound while a drag is occurring
window.addEventListener('scroll', onScroll, {capture: true, passive: false})
```

To get the element you are over you might be able to use [getElementFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint), or add a `mousenter` / `mouseleave` event to the element so you know when you are over it

**Comment by kyawsiesein** [comment]
@alexreardon Thanks for pointing me the direction. I get it solved my use case from your [comment](https://github.com/atlassian/react-beautiful-dnd/issues/757). I just changed my container to `position: fixed`.

**Comment by jooj123** [comment]
Sorry i meant `react-beautiful-dnd` 😆 

As @kyawsiesein mentioned, we hacked around it for now.

We have a few use cases that are in development - ill share once they are live 👍

**Comment by olanMbakop** [comment]
In my case, I have a fixed container with offset with scroll as well, and apparently, both the global/window and the container I have are conflicting with autoscroll.
