### ISSUE TITLE
Restrict the drop areas for the dragged task on top of ghosted task

### ISSUE THREAD

**Issue by DhirajKhot** [atlassian/react-beautiful-dnd#1253]
## Bug or feature request?

I am using this library and implementing multi drag support on top of it referring to the example mentioned in storybook in this repository itself.

On top of it I have added a below change -
Assume there are 10 tasks in the list and I have selected 3 tasks and start dragging one of it, during the drag the remaining 2 selected tasks should be ghosted (turn grey to present themselves as ghosted) from the list. This will represent as they are dragged too.

I am able to achieve this and have provided the codesandbox link below in the Demo.

But I am looking for one more change here. 
Lets say I have 10 tasks in the list. The list is Droppable and individual Task is Draggable.
I select 4 top consecutive tasks (Task 1, 2, 3 and 4) in a list and start dragging the top first task (Task 1). 
I do not want the task 2, 3, and 4 move away to allow the drop for dragged task 1.
I can drop the Task 1 only in the area between task 5  - task 10. 
The goal here is I do not want to allow the dragged task to be dropped in the area from where the tasks were actually selected for multiple tasks dragging.

Can this behavior be achieved ?

### What version of `React` are you using?
16.8.4

### What version of `react-beautiful-dnd` are you running?
10.1.0

### What browser are you using?
Chrome

### Demo

Please check the example - 
https://codesandbox.io/s/zq35w0ww6p

**Comment by alexreardon** [comment]
Right now the behaviour you are after is not supported. You might be able to hack it. It would involve watching the mouse position during a drag.

- set `isDropDisabled` while over the first 5 items
- set `isDropDisabled` to `false` when over bottom items

This would not play well for keyboard usage, but it might get you where you want to go
