### ISSUE TITLE
Can't drop card on list title ("handle")

### ISSUE THREAD

**Issue by TylerL-uxai** [atlassian/react-beautiful-dnd#126]
Can't drop the card on the title of the list in the 'task board' demo

**Comment by alexreardon** [comment]
Aye, it is not part of the Droppable area. You will find that the `Droppable` sits within the list. You could set it up differently, but that is how we did it in the examples

**Comment by TylerL-uxai** [comment]
Thanks @alexreardon . Here's what I've been doing for my own To-Do/Project Management software (hopefully it inspires Trello/Atlassian)

https://www.youtube.com/watch?v=K389QWUp4zo

https://codepen.io/TylerL-uxai/full/ZJqwXR/

**Comment by tim-soft** [comment]
@TylerL-uxai this is an Atlassian repo. If this doesn't weasel it's way into bitbucket I'll be really disappointed

**Comment by alexreardon** [comment]
I am not sure if this is an issue, suggestion or other. You can change the droppable area by composing the components in a different way. In our examples we have not set it up so you can drop on the column headers

**Comment by bradleyayers** [comment]
I tried doing this too (allowing a column title to be within the droppable region), and I encountered a problem with the animation.

![2017-11-02 react-beautiful-dnd](https://user-images.githubusercontent.com/105820/32310661-1c0f2078-bfe8-11e7-890c-b11b5f634e0e.gif)

I given the column container element to Droppable's `provided.innerRef`, and it looks like react-beautiful-dnd assumes that the top of the droppable is where the the first item should be placed?

**Comment by alexreardon** [comment]
That is correct - it assumes the top. So to get around your issue make the droppable area just the part of the list that can contain items. I cannot think of another reasonable way to get around that

**Comment by bradleyayers** [comment]
There's a couple of problems with making the the droppable area just the items region:

- empty lists have a tiny drop zone
- it requires more precision than feels natural

In my case it'd be ideal if the position of the placeholder was used to determine the target position for the draggable animation. Can you think of any scenarios where that wouldn't be appropriate?

**Comment by alexreardon** [comment]
We add a min height to the inner area to allow a nice empty drop zone

**Comment by alexreardon** [comment]
Otherwise how we know where the start of the droppable region is (without adding a tonne of complexity)?

**Comment by bradleyayers** [comment]
Is it possible to just use the top of the placeholder in the droppable? The placeholder gets rendered while the draggable is lifted, so there should be time to calculate its position before its needed for the drop animation.

**Comment by felixaa** [comment]
Any updates on this? I have a similar issue. Tried to set min-height on empty droppables

![out](https://user-images.githubusercontent.com/5445088/32553737-fe3c5dcc-c497-11e7-854f-84ca7eb1a9cd.gif)

**Comment by alexreardon** [comment]
I am not sure what the issue is here. Can somebody please explain to me a little bit more about what the expected behaviour could be?

**Comment by felixaa** [comment]
Problem is the glitch when dropping a draggable onto an empty droppable. It doesn’t seem to know where to position itself. This does not happen when the droppable is already populated by another draggable-item. I can provide some code regarding this asap🙌🏽

**Comment by alexreardon** [comment]
@felixaa if you add the inner margin/padding on the droppables themselves and add a min-height you should be good. As you said, it thinks the corner of the droppable is the top left

**Comment by alexreardon** [comment]
Also, this might be relevant: #158

**Comment by alicnik** [comment]
For anyone coming to this now, a workable solution is to add `ignoreContainerClipping` to the `<Droppable />`. The resulting behaviour is that you can drop a card onto an empty list in the area where the `<Droppable />` zone is placed in your markup, even though the height of that zone is `0`. You can't drop it on the title still, but the UX is pretty satisfactory.

```tsx
<Droppable droppableId={list.id} type="card" ignoreContainerClipping>
  {(dropProvided) => (
    <div
      className={styles.cardsContainer}
      ref={dropProvided.innerRef}
      {...dropProvided.droppableProps}
    >
      {list.cards.map((card, index) => (
        <Card key={card.id} card={card} index={index} />
      ))}
      {dropProvided.placeholder}
    </div>
  )}
</Droppable>
```

It's likely important to note that [this seems to be intended for another use-case](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#optional-props), namely where the parent is a scrollable container, and there is a warning that it may result in unexpected behaviour if you have multiple `<Droppable />`s, however it is working fine with multiple draggable lists each containing a droppable zone, like Trello.
