### ISSUE TITLE
Bottom item being hidden under scrollbar during dragging

### ISSUE THREAD

**Issue by micaww** [atlassian/react-beautiful-dnd#1260]
I'm trying to integrate this library with `react-table` and have successfully made it work, other than this annoying visual bug I can't seem to figure out how to get around.

When I pick up an item, the height of the item I'm holding is reduced from the table, which causes the bottom item to be hidden under scroll. This makes it hard to move an item to the bottom of the list.

I would assume this has something to do with the `transform` css that's applied an all of the rows under the one being held. For some reason, this wasn't an issue with an older version of dnd.

Is there some prop I'm missing or any kind of CSS trick to help mitigate this issue? I know I can manually set the height of the table body based on how many rows are visible, but this seems too hacky.

Here is a CodeSandbox demonstrating this issue: https://codesandbox.io/s/olyq499vx5

**Comment by alexreardon** [comment]
Check your console

**Comment by micaww** [comment]
@alexreardon thanks for the tip! Adding the placeholder on the inside of the TbodyComponent did it. I knew I was missing something 😄
