### ISSUE TITLE
In a multi-column react-beautiful-dnd drag/drop, is it possible to preserve the dragged item in original column?

### ISSUE THREAD

**Issue by NickEmpetvee** [atlassian/react-beautiful-dnd#1261]
As an example, a playlist builder where there's a column of all possible songs and a second playlist column. When you drag a song from the column 1 to column 2, it displays in column 2, but you can still drag the song from column 1 to column 2 again in case you want to play the song twice in the playlist.

I leverage react-beautiful-dnd elsewhere, so would like to make the above work with the same library rather than looking for another option. The multi-column examples I've seen only show how to move the Draggable from one column to another, not 'copy' it.

**Comment by alexreardon** [comment]
See #1120
