### ISSUE TITLE
onDragEnd with reason cancel in returnvalue

### ISSUE THREAD

**Issue by abuetergerds** [atlassian/react-beautiful-dnd#1263]
### Expected behavior

Drag the item from a droppable to another droppable and get new destination for the item in the onDragEnd returnvalue

### Actual behavior

drag into the other droppable cancel the drag and onDragEnd return value with destination = null and reason: "CANCEL"

### What version of `React` are you using?

16.8.1

### What version of `react-beautiful-dnd` are you running?

10.0.4

### What browser are you using?

Chrome

### Demo

![9oShiF8b00](https://user-images.githubusercontent.com/21362491/56214733-b61c2180-605e-11e9-938d-29b93a0efc12.png)
![01ilI1u7lD](https://user-images.githubusercontent.com/21362491/56215391-e44e3100-605f-11e9-8702-46a3154a1366.gif)

**Comment by alexreardon** [comment]
> drag into the other droppable cancel the drag and onDragEnd return value with destination = null and reason: "CANCEL"

That sounds correct to me. Can you please provide some more details?

**Comment by alexreardon** [comment]
When a drag is cancelled we clear the `destination`

**Comment by alexreardon** [comment]
I thought this was called out in the docs. I'll have a look and add it if it is not

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/commit/207e798f30c8e17e9eab4c053dc846f05d1a3ad1
