### ISSUE TITLE
Dragged Item disappear in dragging state

### ISSUE THREAD

**Issue by rzkhosroshahi** [atlassian/react-beautiful-dnd#1267]
### Actual behavior
In my case dragged Item it will disappear. It seems style position fixed from the top of the window. I didn't use a special style position for the dragDropContext parent.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11410506/56434506-1d99d180-62ea-11e9-9e50-559ba7affb51.gif)

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
^11.0.0

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by alexreardon** [comment]
Also, see here: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md

You might need to use a portal

**Comment by Paul6552** [comment]
I think this is the same problem like we have here: https://github.com/atlassian/react-beautiful-dnd/issues/1003

I think to use a portal isn`t a good workaround. You destroy the drag and drop functionality on touch devices.

**Comment by alexreardon** [comment]
Portals now work correctly with touch. You can also use our new cloning api rather than using your own portal. See our [reparenting guide](/docs/guides/reparenting.md)

**Comment by pushkingav** [comment]
See our [reparenting guide](/docs/guides/reparenting.md)
It seems that the link is broken. The correct [one](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/reparenting.md).

**Comment by kaanbayram** [comment]
> Also, see here: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md
> 
> You might need to use a portal

this link is broken. Can someone send new link?

**Comment by pushkingav** [comment]
See the correct link in my previous comment
https://github.com/atlassian/react-beautiful-dnd/issues/1267#issuecomment-550978624

**Comment by kaanbayram** [comment]
thank you but i think https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md this one contain diffrent content, i am not pretty sure.

**Comment by mrap** [comment]
How was this resolved? I'm having the same issue.

**Comment by ConorTighe1995** [comment]
The using a portal example being linked here has since been deleted, is there a alternative for this fix?

**Comment by kadirisani** [comment]
Recently I come across this issue and noticed that will-change: transform was giving me this problem. i set the style as will-change: unset and that fixed the issue.
