### ISSUE TITLE
Noncontiguous/paginated lists

### ISSUE THREAD

**Issue by dzucconi** [atlassian/react-beautiful-dnd#1268]
### Expected behavior

Sorting a vertical list as normal.

### Actual behavior

Weird placeholder behavior + unexpected drop behavior.

### Steps to reproduce

Break up the list into a set of chunks (ie: `[[1,2,3], [4,5,6], [7]]`), each chunk wrapped in a fragment. This ultimately renders as a straight list of nodes in the DOM.

The situation is that I have a list of IDs that are are getting rendered out into a sortable list, but I want to lazily load the representations of each list item in chunks. The entire list is sortable with just those IDs present, the extra data is just visual information for the user doing the sorting.

### What version of `React` are you using?

16.8.6

### What version of `react-beautiful-dnd` are you running?

11.0.0

### What browser are you using?

Chrome 73.0.3683.103 / macOS 10.14.3

### Demo

https://codesandbox.io/s/pk7pmlzr60

**Comment by alexreardon** [comment]
I think your issue is that you have items that reusing an index. Each draggable needs a unique and sequential index

**Comment by dzucconi** [comment]
Of course, You are absolutely correct. Thanks!
