### ISSUE TITLE
react-beautiful-dnd always moves focus to new draggable element

### ISSUE THREAD

**Issue by mDibyo** [atlassian/react-beautiful-dnd#1269]
Not sure if this is a bug, or a breaking change between v10 and v11.

On adding a new draggable,

### Expected behavior

react-beautiful-dnd should not mess with focus handling if an element inside new element is getting focused.

### Actual behavior

react-beautiful-dnd always moves focus to new draggable element

### Steps to reproduce

See codesandbox example: https://codesandbox.io/s/5zr34lkv0k
In example, each item has a textarea that gets autofocused when first created.
- With react-beautiful-dnd v10.1, see that when a new item is added, focus is on textarea inside item.
![rbd_focus_v10](https://user-images.githubusercontent.com/4902438/56556527-1a525000-654d-11e9-97ce-94611fa7502f.gif)

- With react-beautiful-dnd v11, see that when a new item is added, focus is moved to the entire item.
![rbd_focus_v11](https://user-images.githubusercontent.com/4902438/56556529-1a525000-654d-11e9-98e1-d4fdfdefcd4c.gif)

### Suggested solution?

Stop moving focus. :D

### What version of `React` are you using?

16.8.6

### What version of `react-beautiful-dnd` are you running?

11.0

### What browser are you using?

Chrome

### Demo

https://codesandbox.io/s/5zr34lkv0k

**Comment by alexreardon** [comment]
The issue is caused by the `autoFocus`. I can see the lines causing issues. I am trying to come up with a resilient path forward

**Comment by mDibyo** [comment]
@alexreardon Thanks for the lightning-quick fix! We reverted our codebase to use v10 yesterday night, but maybe that wasn't necessary.

Will look to re-upgrade to v11. Keep up the awesome work! <3

**Comment by alexreardon** [comment]
Thanks @mDibyo
