### ISSUE TITLE
DnD Between Components

### ISSUE THREAD

**Issue by Ayberkone** [atlassian/react-beautiful-dnd#1276]
Well hello!

Is there any way to drag and drop between components? I have two components exactly the same ( in terms of data structure and UI). One button on first component expands the second component and I want to drag and drop items among them. I believe it cannot be achieved by using only react but, still I have hope in you! 

Have a good one.

**Comment by crapthings** [comment]
https://user-images.githubusercontent.com/2182637/53614150-efbed780-3c2c-11e9-9204-a5d2e746faca.gif

**Comment by Ayberkone** [comment]
@crapthings They are in the same component.

**Comment by Ayberkone** [comment]
By using props and loosing some hair, I've managed to solve the problem.

**Comment by crapthings** [comment]
hello @Ayberkone  i'm facing the similar problem but i think its just two different components with drag drop hoc.
