### ISSUE TITLE
Prevent *source* draggables from animating

### ISSUE THREAD

**Issue by oznekenzo** [atlassian/react-beautiful-dnd#1279]
Is there a way of preventing the source draggable components from moving within the droppable?  I've gone through the documentation and haven't found anything.  Most issues with animation, I understand, is in opposition to keeping R-B-D lifelike, but preventing the source list from moving actually fits under this framework!

Thanks for your great lib!!

React v16.8.4

RBD v11.0.0-beta

**Comment by alexreardon** [comment]
You can set `isDropDisabled` to `true` on the home list to prevent reordering or dropping in it

**Comment by oznekenzo** [comment]
That did help!  But I should clarify my question.
I would like to prevent the home list draggable components from rearranging after I take one component out of it.  Is this possible?
