### ISSUE TITLE
Adding `Draggable`s with `isCombineEnabled` forces placeholder to start position

### ISSUE THREAD

**Issue by ekfn** [atlassian/react-beautiful-dnd#1282]
### Expected behavior

Adding `Draggable`s when dragging item over another one, with `isCombineEnabled=true`, doesn't forces placeholder to start positions.

### Actual behavior

Adding `Draggable`s when dragging item, with `isCombineEnabled=true`, forces placeholder to start positions.

### Steps to reproduce

1. open https://react-beautiful-dnd.netlify.com/iframe.html?id=dynamic-changes-during-a-drag--with-controls
2. Enable `Combine items`;
3. Press `b` twice;
4. Drag first item over last one, don't release mouse button;
5. Press `b` one more time;

After this placeholder returns to first position and this may cause a loss of current position if placeholder was on the last position.

### What version of `React` are you using?

16.8.0

### What version of `react-beautiful-dnd` are you running?

10.0.4

### What browser are you using?

Chrome:latest

### Demo

https://react-beautiful-dnd.netlify.com/iframe.html?id=dynamic-changes-during-a-drag--with-controls

Same behavior for `@atlaskit/tree`: collapse branch `Title 2`, start dragging `Title 1-7`, drag it over `Title 2`, wait while it expand. After `Title 2` is expanded all `Draggable` elements reflows.
https://codesandbox.io/s/88m7ojnq82?module=/example.js

**Comment by alexreardon** [comment]
I am looking at this logic for #1317. So I can take a look at this issue as a part of that

**Comment by alexreardon** [comment]
Is this still an issue?

**Comment by ekfn** [comment]
yes, with `11.0.5` it's works same way

**Comment by ekfn** [comment]
with `12.0.0-alpha.7` the placeholder does not lose its position, but after adding `Draggable`, the second placeholder appears, but maybe this is the problem of my example (the tree of nested folders), I think it need to be tested further on @atlaskit/tree when it updates the dependency

**Comment by alexreardon** [comment]
okay sure. Right now tree will not work with the alpha.

At this stage tree might not work with the initial 12.0 release. This is to get 12.0 out the door. We have plans to readd support for tree in a later 12.x feature release. That is the current plan anyway

**Comment by alexreardon** [comment]
Tracking resupporting trees here: #1547
