### ISSUE TITLE
Could not find required context

### ISSUE THREAD

**Issue by dovydaskukalis** [atlassian/react-beautiful-dnd#1285]
Starting from 11.0.0, if `<Draggable>` is not inside `<Droppable>`, it throws `Invariant failed: Could not find required context` even when `<Draggable>` is disabled. Is it intended behaviour? As I remember it was always working fine and I didn't see anything mentioned in release notes.

Demo: https://codesandbox.io/s/km9zl2yyj3

**Comment by claycoleman** [comment]
If nothing else, maybe some additional error text here would be really useful.

**Comment by alexreardon** [comment]
This behaviour has not changed from 10.x (or ~1.x?). Draggables must always be in a Droppable

> "`<Draggable />` components can be dragged around and dropped onto `<Droppable />`s. A `<Draggable />` must always be contained within a `<Droppable />`."

It is in the first sentence of the [Draggable docs](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#draggable-) 🚀

**Comment by alexreardon** [comment]
I am not sure if we could add more clarity 🤷‍♀️

**Comment by peisenmann** [comment]
It's a bit of a wall of text at the top of those docs. It'd probably be best to feature the `<Droppable>` somewhere in at least one of the examples on the page. Seeing the nested structure would do a lot more than saying it in the text wall.

I don't know that anything can really be done about the missing context message, as that comes from React itself.

**Comment by alexreardon** [comment]
Perhaps I could add a bigger warning at the top? This is also this gif at the root:

https://github.com/atlassian/react-beautiful-dnd#api-%EF%B8%8F

![](https://user-images.githubusercontent.com/2182637/53607406-c8f3a780-3c12-11e9-979c-7f3b5bd1bfbd.gif)

**Comment by peisenmann** [comment]
@alexreardon I certainly do appreciate the gif. I think the challenge comes from logically thinking that I might want to place draggables in a container that isn't itself ever droppable. Imagine a palette of options one might drag from onto a canvas, but would never consider dropping anything onto that palette.

The gif alone doesn't convey that a Draggable MUST be contained inside a Droppable, only that it should be if you want to rearrange items.

It's a one-time lesson that users have to learn, so maybe the existing docs are not worth altering.

**Comment by lwhite1** [comment]
>  I might want to place draggables in a container that isn't itself ever droppable. Imagine a palette of options one might drag from onto a canvas, but would never consider dropping anything onto that palette.

This is exactly my use-case. My palette is divided into "trays". I'm considering trying to make every tray a non-functioning droppable. Is that the best workaround for this?

**Comment by Tush2890** [comment]
> I might want to place draggables in a container that isn't itself ever droppable. Imagine a palette of options one might drag from onto a canvas, but would never consider dropping anything onto that palette.

Is the ticket still open because I am also looking for similar use case ?

**Comment by slugmandrew** [comment]
Another right here 👍

**Comment by cactusjosh** [comment]
For those of you with this use case, this library works in a pinch: https://www.npmjs.com/package/react-draggable. It lets you drag something around without necessarily 're-ordering it in a list' which I think is what rbd is really focussed on (at least for now).

**Comment by gregg-cbs** [comment]
I find this the most complex package to make sense of.
The documentation completely contradicts its usage because the documentation doesn't have any examples of how to use it because the examples you have only showcase using the `<Draggable>` component which is incorrect.

There is no example anywhere on your readme of how this is supposed to be structured - its mind boggling.

Then there is your storybooks - which is great to look at but does not provide any code so its useless.
We need code snippets.

And all this is a pity because im sure you put hard work into this, it looks great! but I cant seem to make sense of anything.

I've tried `react-sortablejs` its buggy as hell.
I was hoping this would work for me :(
And now im going to try `react-draggable`

If you need documentation help, i will be glad to assist someone in putting code snippets together so the community can make better use of this.

**Comment by frank1003A** [comment]
Can a draggable container not be droppable

>I think the challenge comes from logically thinking that I might want to place draggables in a container that isn't itself ever droppable. Imagine a palette of options one might drag from onto a canvas, but would never consider dropping anything onto that palette.

This is exactly my issue. I have a container that does not need to be reordered or even droppable.
The whole library accounts for just one specific use case droppable-to-droppable.
Is there a hack around this ?

**Comment by kyleholgate** [comment]
> I am not sure if we could add more clarity 🤷‍♀️

You don't think you could make the error say "A Draggable must be contained within a Droppable" instead of "Invariant failed: Could not find required context"?
