### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by amraei** [atlassian/react-beautiful-dnd#1289]
There is a problem with horizontal drag and dropping while the page direction is RTL. Vertical drag and drop is working correctly as expected, even when dragging from one column to another one (which is basically a horizontal move).

It would be really nice if it could support RTL pages with horizontal columns.

**Comment by alexreardon** [comment]
Duplicate: #270

**Comment by mamadoo** [comment]
@amraei do you find any solution?

**Comment by amraei** [comment]
@mamadoo I find it better to use alternatives. Atlassian won't care about RTL.

**Comment by mamadoo** [comment]
@amraei which library supports rtl?
