### ISSUE TITLE
Incompatible with react-redux@^6.0.0 or @^7.0.0

### ISSUE THREAD

**Issue by ejerry** [atlassian/react-beautiful-dnd#1291]
**Describe the bug**
Error on import of `react-beautiful-dnd` together with `react-redux@^6.0.0` or `react-redux@^7.0.0`.

This seems to be stemming from the react-redux **"Breaking Changes"** point #2  [noted here.](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0)

**Error message**
`Uncaught Invariant Violation: storeKey has been removed and does not do anything. To use a custom Redux store for specific components, create a custom React context with React.createContext(), and pass the context object to React Redux's Provider and specific components like: <Provider context={MyContext}><ConnectedComponent context={MyContext} /></Provider>. You may also pass a {context : MyContext} option to connect`

Please see attached log files:
[localhost-1556994978137.log](https://github.com/atlassian/react-beautiful-dnd/files/3144689/localhost-1556994978137.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/11894358/57183308-a0309e00-6e5f-11e9-83c4-b9a694a559bc.png)

**To Reproduce**
1. `create-react-app`
2. `yarn add react`
3. `yarn add react-redux`
4. `yarn add react-beautiful-dnd`
5. add `import { DragDropContext } from 'react-beautiful-dnd';` to App.js
6. `yarn start`

**Expected behavior**
It should work with `react-redux@^6.0.0` or `react-redux@^7.0.0`

**react-beautiful-dnd version**
`react-beautiful-dnd@11.0.2`

**react-redux versions tested**
I get this same error with any of these versions:
`react-redux@6.0.0`
`react-redux@7.0.0`
`react-redux@7.0.2`
`react-redux@7.0.3`

**react version**
`react@^16.8.6`

**Comment by alexreardon** [comment]
See here: https://github.com/atlassian/react-beautiful-dnd/issues/1056#issuecomment-464555260

Please do not override `react-beautiful-dnd`'s version of `redux`. It is an internal dependency
