### ISSUE TITLE
Traslating to Russian language

### ISSUE THREAD

**Issue by vtereshyn** [atlassian/react-beautiful-dnd#1298]
Hi! I've started translating [react-beauriful-dnd](https://github.com/atlassian/react-beautiful-dnd) documentation to the Russian language. It would be incredible if people who want to help submitted Pull requests to this [repo](https://github.com/vtereshyn/react-beautiful-dnd-ru). Also, would be great if you can paste this link in your README file with the new translation in Russian.

https://github.com/vtereshyn/react-beautiful-dnd-ru

Thanks!

**Comment by alexreardon** [comment]
Feel free to add a PR to add the link to our docs!

**Comment by alexreardon** [comment]
Well done @vtereshyn!! #1317
