### ISSUE TITLE
When leaving Droppable area, placeholder is moved to the bottom of the list

### ISSUE THREAD

**Issue by cwmacdon** [atlassian/react-beautiful-dnd#1299]
### Expected behaviour
Prior to 10.1:
- When dragging a list item outside of the home Droppable area, but not over another Droppable, the placeholder would remain at the index of the place you grabbed it from. 

https://github.com/atlassian/react-beautiful-dnd/issues/94
> Full placeholder rules:
> - when dragging over a home list - use the Draggable placeholder
> - when dragging over no list - use the Draggable placeholder
> - when dragging over a foreign list - use the Droppable placeholder in both the home and foreign Droppable.

Assuming that the "Draggable placeholder" is the original location of the dragged list item, then the placeholder should remain there until it has a new place to go (i.e. dragging over a foreign Droppable that does not have `isDropDisabled`.

### Actual behaviour
The placeholder is moved to the bottom of the list as soon as you leave the home Droppable area.

### Steps to reproduce
Drag a list item outside of the home droppable area.
Behaviour is the same regardless of whether you hover over a foreign list or no list.

### Suggested solution?
> - when dragging over no list - use the Draggable placeholder

### What version of `React` are you using?
react@16.8.6

### What version of `react-beautiful-dnd` are you running?
Occurs in: ^10.1.1
Does not occur in 10.0.4

### What browser are you using?
Chrome browser

### Demo
This is visible in the storybook:
https://react-beautiful-dnd.netlify.com/?path=/story/board--simple
https://react-beautiful-dnd.netlify.com/?path=/story/single-vertical-list--basic

**Comment by alexreardon** [comment]
This was an intentional change in [v10.1](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0) 

You can read about the details in ["Beautiful interactions"](https://medium.com/@alexandereardon/beautiful-interactions-8f67502ccf73)

**Comment by alexreardon** [comment]
Please have a read of the pages and let me know if you think there are any issues with the thinking
