### ISSUE TITLE
Custom drag preview?

### ISSUE THREAD

**Issue by thewebsitedev** [atlassian/react-beautiful-dnd#130]
Thank you for this great library!! Great work!

Would love to see support for custom drag layer preview as provided by react-dnd.

Thanks!

**Comment by alexreardon** [comment]
You can update your component while dragging in response to the `snapshot.isDragging` property. Technically you could render a different component in response to this prop. However, it is recommended not to do this as it is important that your component remains the same dimensions while dragging.

**Comment by thewebsitedev** [comment]
Thanks! And congratulations to you and your family on the birth of a baby girl. :)

I have some components that can cover the entire page and so in that case dragging a big component is not very pleasant. I am currently using React DND but will be happy to move once some more features are added like auto scrolling.
