### ISSUE TITLE
When the chrome devtool is open, image will flash on dropped

### ISSUE THREAD

**Issue by fernandoxu** [atlassian/react-beautiful-dnd#1305]
### Actual behavior
![StorybookGoogleChrome20190](https://user-images.githubusercontent.com/20871468/57710450-90a32780-769f-11e9-82a3-b69fbefdffdb.gif)
![reactbeautifuldnd_flashondr](https://user-images.githubusercontent.com/20871468/57710469-939e1800-769f-11e9-8b4a-7308a81f168d.gif)

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
11.0.3

### What browser are you using?
chrome 74.0.3729.131

### Demo
[https://codesandbox.io/s/yqq6jp3ryj](url)
[https://react-beautiful-dnd.netlify.com/iframe.html?id=board--simple](url)

**Comment by alexreardon** [comment]
See #1311
