### ISSUE TITLE
Draggables inside of portals are broken with touch

### ISSUE THREAD

**Issue by TrySound** [atlassian/react-beautiful-dnd#1310]
### Expected behavior

Draggables inside of portals should work

### Actual behavior

Draggables inside of portals don't work

### Steps to reproduce

1. open this page in chrome https://react-beautiful-dnd.netlify.com/?path=/story/portals--using-your-own-portal
2. enable iphone mode
3. start dragging items (they are stuck)

### What version of `React` are you using?

16.8.6

### What version of `react-beautiful-dnd` are you running?

10.0.3, same on 11.0.3

### What browser are you using?

chrome 73

**Comment by alexreardon** [comment]
Duplicate: #582

I am hoping to fix this as a part of #1293
