### ISSUE TITLE
How to prohibit to drop an item into a particular list

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [atlassian/react-beautiful-dnd#1313]
Hi ,

How to drop item only to a specified list ? not all the list .

For eg:
I need to drag and drop item from ToDo to Done not in In progress .

pls refer this url : 

https://codesandbox.io/s/gszpx

And help me. Do the needfull .

**Comment by alexreardon** [comment]
Here you go: https://egghead.io/lessons/react-conditionally-allow-movement-using-react-beautiful-dnd-draggable-and-droppable-props

**Comment by DhanushkumarSivaji** [comment]
Is i need to pay for that tutorial?

**Comment by alexreardon** [comment]
Nope, it is free

**Comment by alexreardon** [comment]
Here are the docs if you prefer that:
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#conditionally-dropping

**Comment by DhanushkumarSivaji** [comment]
Sure.. thanks.. i tried to see the video , but its not playing

**Comment by DhanushkumarSivaji** [comment]
Thanks Sir

**Comment by alexreardon** [comment]
You are welcome

**Comment by amihalopoulos** [comment]
I am following along with this tutorial on version 11.0.0 and am getting the error:
`Error: Invariant failed: Cannot add a Droppable during a drag`

any ideas what I'm doing wrong?
