### ISSUE TITLE
[11.0.3] Scrolling over draggable elements is broken on iOS Safari

### ISSUE THREAD

**Issue by dovydaskukalis** [atlassian/react-beautiful-dnd#1314]
Latest update (11.0.3) seems to have broken scrolling over draggable elements in iOS Safari. Works fine on 11.0.2. Tested on iOS 12.2 and 12.3.

Video from iOS app (same happens in browser): https://streamable.com/kuc22

**Comment by alexreardon** [comment]
Sounds bad! Thankfully the new event system works fine. I tested it today. It is lame that safari releases regressions like this

#1293

**Comment by alexreardon** [comment]
Tracking in #1401
