### ISSUE TITLE
How do I stop other draggables from moving when dragging another one in the same container

### ISSUE THREAD

**Issue by jullyolima** [atlassian/react-beautiful-dnd#1315]
I'm making a card game where you attack by dragging a card on top of another card. All cards are draggables and droppables and it works correctly. However, I want to make it so the card thats being dropped on doesn't shift over. Is that possible??

Heres a gif of what I mean:
https://imgur.com/a/7j9nwyg

**Comment by alexreardon** [comment]
Great art style!

You could try using isCombineEnabled.. If you can create an independent example I might be able to show you some potential solutions

**Comment by alexreardon** [comment]
Here is out boilerplate: https://codesandbox.io/s/k260nyxq9v

**Comment by jullyolima** [comment]
Thank you for answering! 

So I've tried the combine feature, and while it sort of worked, it still does that shifting over due to the 1/3 of the draggable being pushed over. I also saw that in the documentation that it's not possible to use combine only without the reordering. So, my follow up question is, is it possible to alter the packages CSS files to turn off the transform when something is being dragged over? If so, where would I be able to do that? Thank you in advance.

**Comment by Morphexe** [comment]
This is something that should be enabled by default,  being able to use combine without the reordering, some lists are not meant to be reorderable =)

**Comment by alexreardon** [comment]
We can track it here: #1390

**Comment by 100terres** [comment]
If anyone has the time to the investigate and open a pull request, you can to it on this fork https://github.com/hello-pangea/dnd/issues/438#issuecomment-1328090710 of react-beautiful-dnd. PRs are more than welcome on our repo :slightly_smiling_face:
