### ISSUE TITLE
12.0 Release 🎁

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#1317]
Want to play with the beta? See https://github.com/atlassian/react-beautiful-dnd/issues/1317#issuecomment-534946979

I am using this issue as a linking point for things going out in `12.0`

[Virutal list project](https://github.com/atlassian/react-beautiful-dnd/projects/1)

- #1225
- #1310 
- #1104

**Comment by alexreardon** [comment]
Also need to bump to flow 0.99+

**Comment by alexreardon** [comment]
`react-beautiful-dnd@12.0.0-alpha.1` is out.

Some wins of using the alpha:

- portals now work on mobile
- considerably reduced memory usage (~50%)

Do not use if:

- using dynamic additions and removals (it is currently broken)
- using data-* attributes (they have changed)
- monkey patching event handlers on a drag handle (they are gone now)

I am really interested to find an example of dragging an item in an iframe. Right now I think our code will not work with it - so I am keen to get an example

**Comment by makaGeroge** [comment]
Hi, I just tried using portals to solve an issue where parent components use transform but on mobile I cannot drag the elements... is it necessary to add anything else so it works on mobile? Thanks!

**Comment by tjramage** [comment]
@alexreardon — Updated to this on our dev branch yesterday, all working great 👌

**Comment by tjramage** [comment]
@alexreardon — we've just seen the [latest tweet](https://twitter.com/alexandereardon/status/1138960614447915014) showing off all your hard work — just incredible! So great to see.

However, I just wanted to clarify the exact conditions under which we'll be able to make use of virtualisation. You'll have to forgive me, as I'm only just getting up to speed with the concept of windowing, etc, but it appears that each individual list must have its own scrollable container in order for it to determine which children it can virtualise. Is that correct?

Our situation is actually quite different. We have (potentially) anywhere up to 1000 lists, each with a varying amount of items inside them. Each list's height is determined by its contents, and nothing is scrollable apart from the whole document window itself.

Having seen the demo in action, I've only just twigged now that this may not be able to solve our performance issues unless we set the lists to a fixed height and allow each one to be individually scrollable. My problem is that this wouldn't work for us, as our lists scale out both horizontally and vertically (think Trello, but with multiple slices of lists).

Another thing I'd like to ask is whether virtualisation could be applied to the lists themselves, rather than their contents? If this was possible, we could at least benefit from only rendering ~50 lists at a time...

Sorry for the mammoth! Keep up the great work ✌️

**Comment by dcporter44** [comment]
Is virtualization available in `react-beautiful-dnd@12.0.0-alpha.1`? If so, is there any documentation on how to use it?

**Comment by alexreardon** [comment]
`12.0.0-alpha.2` is now out which contains the first cut of virtual list support. There are no docs yet - you will need to take a look a `stories/virtual` if you want to see how to set it up

**Comment by alexreardon** [comment]
@tjramage 

> Each list's height is determined by its contents, and nothing is scrollable apart from the whole document window itself.

What we are building is support with existing virtual list solutions. If you can set it up with `react-window` then we should be able to support it

**Comment by tjramage** [comment]
Thanks for clarifying @alexreardon. Is it just `react-window` that is supported? I've done some digging and it looks like there could be a working solution but it makes use of `react-virtualized` along with `WindowScroller` and `Grid`.

**Comment by alexreardon** [comment]
We plan to also support `react-virtualized`. It uses the same technique as `react-window`: https://github.com/atlassian/react-beautiful-dnd/issues/1225#issuecomment-500624339

We will be adding guides and examples for `react-window` and `react-virtualized` at this stage. The other virtual list libraries out there should work, but we won't be testing them initially

**Comment by tjramage** [comment]
Fantastic! Thanks @alexreardon – I'll give the latest v12 alpha release a go later on 👍

**Comment by tjramage** [comment]
@alexreardon — I gave `v12.0.0-alpha.3` a spin today. Managed to get it working successfully with `react-virtualised` and `WindowScroller`. Great work! However, it seems like only draggables can be virtualised, which means we will still have potentially have anywhere up to 1000 droppables on the page... Do you have any plans to support virtualising droppables, also?

**Comment by alexreardon** [comment]
For `12.0` we won't be supporting adding droppables. However, we could look at adding support in a future release!

**Comment by Martaver** [comment]
Trying `12.0.0-alpha.6` since I need the mobile portal support, but I get `ReferenceError: process is not defined` trying to load `react-beautiful-dnd`. Offending line is:
```
var isProduction = process.env.NODE_ENV === 'production';
```

Is this just in there for debugging in alpha vers or something?

**Comment by alexreardon** [comment]
Strange. This should be taken care of my our / your bundler.

How are you consuming `rbd`?

**Comment by Martaver** [comment]
Fusebox. I can probably inject env vars into my vendor bundle, but point is
that I shouldn’t have to in a published package. Also, this isn’t an issue
with 11.0.2

**Comment by alexreardon** [comment]
Interesting that it is only an issue for 12.0. It might be due to a bumped
dependency relating to our build

**Comment by piehouserat** [comment]
have you guys seen https://github.com/petyosi/react-virtuoso ?
it looks pretty neat, hopefully uses the same technique as the others and therefore can be supported relatively easily

**Comment by Martaver** [comment]
@alexreardon would it be possible to get a build out without the process.env dependency? Would like to evaluate the alpha for our purposes...

**Comment by Martaver** [comment]
Got a chance to take another look at this. In your `rollub.config.js` you use this instruction:
```
replace({ 'process.env.NODE_ENV': JSON.stringify('production') }),
```
... in your UMD builds, but not in commonjs.

I'm using commonjs, so `process.env.NODE_ENV` was remaining untouched.

**Comment by alexreardon** [comment]
@TrySound ^

Thoughts?

**Comment by TrySound** [comment]
@Martaver It's a convention actively used in react apps. React has the same https://unpkg.com/react@16.8.6/index.js. Your bundler should replace these NODE_ENV with specific value. Webpack does it automatically depending on passed `--mode`.

**Comment by Martaver** [comment]
Figured it would be something like that. Then the real problem is fuse-box
not injecting process.env into my vendor bundle.

**Comment by TrySound** [comment]
Use replace plugin for that
https://fuse-box.org/docs/plugins/replace-plugin

**Comment by Martaver** [comment]
Sure, that’s another option too! Thanks!

EnvPlugin should inject into all bundles though. I’ll poke @nchanged about
it.

**Comment by nchanged** [comment]
@Martaver please use `v4` it's being handled gracefully there

**Comment by Martaver** [comment]
Cool, I'll give it a try :D Thanks @nchanged!

**Comment by alexreardon** [comment]
Big milestone: the build went green!

<img width="472" alt="Screen Shot 2019-09-11 at 8 00 45 am" src="https://user-images.githubusercontent.com/2182637/64660294-01f2bb80-d483-11e9-8247-cde5ca7d1d17.png">

There is still a fair bit to go and lots of documentation to write. But it is a nice win to celebrate!

Given that the build has gone green, I will now start publishing `beta` releases for `12.0`

**Comment by alexreardon** [comment]
`12.0.0-beta.1` is out

**Comment by alexreardon** [comment]
`12.0.0-beta.2`. It fixes a few issues.

**Comment by alexreardon** [comment]
Here is the current change list:

## Changes

### `<Draggable /> | DraggableProvided | DraggableProps`

> This is a `major` change 💥. For most consumers this will be safe as these data attributes should generally not be leaned on

```diff
type DraggableProps = {|
  // inline style
  style: ?DraggableStyle,

-  'data-react-beautiful-dnd-draggable': string,

+  // used for shared global styles
+  'data-rbd-draggable-context-id': string,
+  // used for lookups
+  'data-rbd-draggable-id': string,
  // used to know when a transition ends
  onTransitionEnd: ?(event: TransitionEvent) => void,
|};
```

### `<Draggable /> | children`

> This is a `minor` change

Adding a third argument to `children` function: `DraggableDescriptor`

> The `children` function now has a type! `DraggableChildrenFn`

```diff
type DraggableChildrenFn = (
  DraggableProvided,
  DraggableStateSnapshot,
+  DraggableDescriptor) =>
Node

+ type DraggableDescriptor = {|
+   id: DraggableId,
+   index: number,
+   // Inherited from Droppable
+   droppableId: DroppableId,
+   // This is technically redundant but it avoids
+   // needing to look up a parent droppable just to get its type
+   type: TypeId,
+ |};
```

But what is it for? It allows you to retrieve all the information about the `<Draggable />` from within your `children` function. Sometimes it can be nice to have all the information at your fingertips, such as what `<Droppable />` the `<Draggable />` is currently in. The new `DraggableDescriptor` is especially useful when using the new `<Droppable /> | renderClone` api. See our new [reparenting guide](/docs/guides/reparenting.md)


### `<Draggable /> | DragHandleProps`

> This is a `major` change 💥. The most likely this to break people is the removal of the on element event listeners. These are no longer required with our new [`sensor`](/docs/sensors/programmatic.md) approach. So you no longer need to patch event listeners to add your own. We will still call `event.preventDefault()` on events that we use so you know whether they are being used for a drag. See [how we use dom events](/docs/guides/how-we-use-dom-events.md)

```diff
type DragHandleProps = {|
+  // focus management is now handled without needing these handlers
-  onFocus: () => void,
-  onBlur: () => void,

+  // new sensor api does not require on element event handlers
-  onMouseDown: (event: MouseEvent) => void,
-  onKeyDown: (event: KeyboardEvent) => void,
-  onTouchStart: (event: TouchEvent) => void,

+  // Moving to new data-* format
-  'data-react-beautiful-dnd-drag-handle': string,
+  // what draggable the handle belongs to
+  'data-rbd-drag-handle-draggable-id': DraggableId,
+  // What DragDropContext the drag handle is in
+  'data-rbd-drag-handle-context-id': ContextId,

+  // New way of doing lift announcements
-  'aria-roledescription': string,
+  // id of drag handle aria description for screen readers
+  'aria-labelledby': ElementId,

  tabIndex: number,
  draggable: boolean,
  onDragStart: (event: DragEvent) => void,
|};
```

### `<Droppable />`

> This is a `minor` change. It enables [using a clone](/docs/patterns/reparenting.md) as well as [virtual lists](/docs/guides/virtual-lists.md)

```diff
type Props = {|
  // required
  droppableId: DroppableId,
  // optional
  type?: TypeId,
+  mode?: DroppableMode,
  isDropDisabled?: boolean,
  isCombineEnabled?: boolean,
  direction?: Direction,
  ignoreContainerClipping?: boolean,
+  renderClone?: DraggableChildrenFn,
+  getContainerForClone?: () => HTMLElement,
  children: (DroppableProvided, DroppableStateSnapshot) => Node,
+  type DroppableMode = 'standard' | 'virtual';
|};
```

### `<Droppable /> | DroppableProps`

> This is a `major` change 💥. For most consumers, this will be safe as these data attributes should generally not be leaned on

```diff
type DroppableProps = {|
  // used for shared global styles
-  'data-react-beautiful-dnd-droppable': string,
+  'data-rbd-droppable-context-id': ContextId,
+  // Used to lookup
+  'data-rbd-droppable-id': DroppableId,
|};
```

### `<Droppable /> | DroppableStateSnapshot`

> This is a `minor` change. It adds some more information that is useful when building [virtual lists](/docs/guides/virtual-lists.md)

```diff
type DroppableStateSnapshot = {|
  // Is the Droppable being dragged over?
  isDraggingOver: boolean,
  // What is the id of the draggable that is dragging over the Droppable?
  draggingOverWith: ?DraggableId,
  // What is the id of the draggable that is dragging from this list?
  // Useful for styling the home list when not being dragged over
  draggingFromThisWith: ?DraggableId,
+  // Whether or not the placeholder is actively being used.
+  // This is useful information when working with virtual lists
+  isUsingPlaceholder: boolean,
|};

```

### `<DragDropContext />`

```diff
type Props = {|
  onBeforeDragStart?: OnBeforeDragStartResponder,
  onDragStart?: OnDragStartResponder,
  onDragUpdate?: OnDragUpdateResponder,
  onDragEnd: OnDragEndResponder,
  children: Node | null,

+  errorMode?: ErrorMode,
+  sensors?: Sensor[],
+  enableDefaultSensors?: ?boolean,
+  liftInstruction?: string,
|};
```

TODO

### `Id`s

> Might break people, but we are simply enforcing pre-exiting types

It has always required that `draggableId` and a `droppableId` be a `string`. Technically you could maybe, possibly, sometimes, get away with using a `number` when nobody was looking and mum was in the other room. However, due to internal changes that is no longer possible. So we will now explicitly `throw` an error if a `string` is not provided.

**Comment by alexreardon** [comment]
You can also play with virtual lists here: https://deploy-preview-1487--react-beautiful-dnd.netlify.com/iframe.html?id=virtual--board-with-react-window

**Comment by suanmei** [comment]
> You can also play with virtual lists here: https://deploy-preview-1487--react-beautiful-dnd.netlify.com/iframe.html?id=virtual--board-with-react-window

This link cannot be accessed

**Comment by alexreardon** [comment]
Try here: https://deploy-preview-1487--react-beautiful-dnd.netlify.com/?path=/story/virtual-react-window--board

**Comment by nathanpower** [comment]
Just checked the storybook preview for v12, looks like the issue that https://github.com/atlassian/react-beautiful-dnd/pull/1394 attempts to address is still present.

To repro, open the storybook with IE11 and open `fixed list with fixed sidebar`. Try to drag an item such that scrolling is triggered

**Comment by alexreardon** [comment]
Thanks @nathanpower. I haven't tackled that one. We won't ship `12.0` with open bugs, and it sounds like this is one, so i'll look at it soon

**Comment by sage911** [comment]
It seems the change to `<Draggable /> | DragHandleProps` no longer allows me to use an svg as a drag handle. eg:

```jsx
<div {...provided.dragHandleProps}>
  <DragHandle />  {/* DragHandle icon from @material-ui/core/icons, root element is an svg */
</div>
```
 was working, but after updating to `12.0.0-alpha.7` I'm unable to drag and receive this warning: 

`event.target must be a HTMLElement`

**Comment by alexreardon** [comment]
Thanks! Can you try beta.5?

**Comment by sage911** [comment]
Same error with `beta.5`

**Comment by alexreardon** [comment]
Thanks for checking. I’ll resolve this early next week

**Comment by alexreardon** [comment]
@sage911 this should be fixed in `12.0.0-beta.7`. Let me know how you go. Thanks for raising the issue. I have added a test to cover the use case and the fix to the code

**Comment by sage911** [comment]
Yup all fixed, thank you! And thank you for all of your work on this excellent library.

**Comment by richard-buckingham** [comment]
@alexreardon  - Firstly, I'd like to express my appeciation for your work on react-beautiful-dnd, it is awesome :-)

Also, apologies if this is not the appropriate place to ask this question.

I'd like to ask a question about version 12 of react-beautiful-dnd.

Will react-beautiful-dnd support dynamic row heights with react-virtualized? E.g, a virtualised version of https://deploy-preview-1487--react-beautiful-dnd.netlify.com/?path=/story/nested-interative-elements--stress-test ?

I've had a look at https://deploy-preview-1487--react-beautiful-dnd.netlify.com/?path=/story/virtual-react-virtualized--window-list, but the items are of fixed height.

I'm using react-virtualized 9.21.1 to render a list of interactive elements using AutoSizer, List, CellMeasurer and WindowScroller, similar to https://github.com/bvaughn/tweets/blob/37d0139736346db16b9681d5b859a4e127964518/src/components/TweetList.js#L126-L132
A list of 12 items displays ok, but when I try to drag item 1 below item 2, both items disappear.  

I've checked out https://github.com/atlassian/react-beautiful-dnd/blob/dev/docs/patterns/virtual-lists.md, and the samples at https://github.com/atlassian/react-beautiful-dnd/tree/dev/stories/src/virtual/react-virtualized, but no luck as yet.

Btw, I updated to react-beautiful-dnd@12.0.0-beta.9 this morning.

**Comment by alexreardon** [comment]
Yum: https://codesandbox.io/s/simple-virtual-list-feeyu

**Comment by nathanpower** [comment]
> Just checked the storybook preview for v12, looks like the issue that #1394 attempts to address is still present.

Seems to be fixed now, thanks! 👍

**Comment by alexreardon** [comment]
Boya! @nathanpower

**Comment by alexreardon** [comment]
The plan is to ship tomorrow 🤫

**Comment by alexreardon** [comment]
Shipped! Thanks so much everyone for your input and support https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.0.0

**Comment by paulhan221** [comment]
@richard-buckingham were you able to find an answer/fix to your CellMeasurer issue? Having a similar problem
