### ISSUE TITLE
Implement warn-once for your dev warnings

### ISSUE THREAD

**Issue by leantide** [atlassian/react-beautiful-dnd#1321]
Only give your dev warnings once per session by keeping a key-value record of the warnings you have already provided. 

For example:

In a new warn-once.js:

```
const printed = {};

export default function warnOnce(message) {
  if (printed[message]) return;
  printed[message] = true;

  if (typeof console !== 'undefined' && console.warn) console.warn(message);
}
```

In each module that prints a warning to the console:
```
import warnOnce from './warn-once';

const yourCode = () =>{
   ...
   warnOnce("I give warnings, but only once!!!"); // this will print
   warnOnce("I warn you, do not do it."); // this will print
   warnOnce("I give warnings, but only once!!!"); // this will not print
   ...
}
```

**Comment by leantide** [comment]
If you had a warning ID, you would key off the ID instead of the message.

**Comment by alexreardon** [comment]
Brilliant!

**Comment by alexreardon** [comment]
The more I think about this - the less sure I am. If we make a cache for all the warnings then if there is anything dynamic in a message it can quickly create a memory leak. I wonder what warnings are painful for people. We don't log warnings for no reason...

**Comment by leantide** [comment]
Yes, dynamic parts of a general message would create additional key-value pairs. Keying off an ID for the generic message would avoid this. Anyway, up to you. I just thought about it after seeing 40 instances of the same dev message, when I understood the message after reading the first one.

```
warningA = {
   id: new uuid.v4( ),
   message: 'Measure twice, cut once!'
}
```

```
const printed = {};

export default function warnOnce(warning) {
  if (printed[warning.id]) return;
  printed[warning.id] = true;

  if (typeof console !== 'undefined' && console.warn) console.warn(warning.message);
}
```

**Comment by alexreardon** [comment]
What message did you see 40 times? I think using performance.now() would be fine for an id. This seems like a good direction. Perhaps the warning could take a `string` or `Object {id, message}` so dynamic messages can opt into the id thingo

**Comment by leantide** [comment]
I am using a nested scroll. I have 4 list columns. Every time I move an item into another column, I see 4 of the following messages. If I move 10 items, I see 40, etc. If I don't have other logging, Chrome console will group them so it isn't as bad. But if I have other console messages in between, the log is littered with the repeated dev messages.

Droppable: unsupported nested scroll container detected.A Droppable can only have one scroll parent (which can be itself)Nested scroll containers are currently not supported...

**Comment by alexreardon** [comment]
sure

**Comment by atomiks** [comment]
What about hot reloading? The cache won't be invalidated, so if you clear the console and do something wrong later on (without a page reload), there won't be a warning right?

**Comment by leantide** [comment]
I'm using create-react-app, and after every file save, I get a re-compile and browser reload. And here I was thinking that was a hot load. 

So there is hot reload that doesn't have the browser refreshing? Does it provide the software with any event?

**Comment by alexreardon** [comment]
Let's do this as a part of #1108

**Comment by alexreardon** [comment]
I think this might be the wrong way to go. I suspect we need to keep a tight rein on our warnings and move to reduce the cases where people can see them
