### ISSUE TITLE
How to group tasks ?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [atlassian/react-beautiful-dnd#1325]
Hi ,

How to group todo tasks ?

For eg:
In todo column i need to group 'Take out the garbage' and 'Watch my favorite show' as a single DnD.
          -------------------------
         Take out the garbage  
         --------------------------
        Watch my favorite show 
        ---------------------------

Please use this url for to see the image :

https://user-images.githubusercontent.com/36889650/58464577-90049980-8153-11e9-993f-fd035e255434.png

when user drag the item , both should move .

Is it possible to make?

pls refer this url :

https://codesandbox.io/s/gszpx

And help me. Do the needfull .

**Comment by alexreardon** [comment]
If you want to combine two items into one you could use our combining api: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/combining.md

If you want to drag two things at a time you can use our multi drag pattern: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

**Comment by DhanushkumarSivaji** [comment]
Hi,

is there any working example for @atlaskit/tree ?

**Comment by alexreardon** [comment]
https://atlaskit.atlassian.com/packages/core/tree

**Comment by Radzell** [comment]
@DhanushkumarSivaji did you ever figure out a hack to do this.
