### ISSUE TITLE
Horizontal visibility detection looks off

### ISSUE THREAD

**Issue by FrontendMetis** [atlassian/react-beautiful-dnd#1326]
### Demo
Video https://www.youtube.com/watch?v=EMfRFy5fcPI&feature=youtu.be
Code https://codesandbox.io/s/horizontal-list-78cj1

**Comment by alexreardon** [comment]
Need to fix for #1317

**Comment by lukyth** [comment]
Seems similar to this https://github.com/atlassian/react-beautiful-dnd/issues/1201

The problem starts occurring on 10.1.0 ([ref](https://github.com/atlassian/react-beautiful-dnd/issues/1201#issuecomment-489324821)).

**Comment by alexreardon** [comment]
Fixed in `11.0.4`
