### ISSUE TITLE
Material ui menu

### ISSUE THREAD

**Issue by rayray93** [atlassian/react-beautiful-dnd#1329]
Hi there, thumbs up for ur job here ! :)

Im currently using this package with material-ui i have problems understanding whats wrong with this concept! 

I have icon with dropdown menu with List items but items appear hidden on right side out of menu list or/and on scroll it looses position...

Can anyone take look and give some hints or examples of this ussage! How can i attach item on mouse? 
https://codesandbox.io/s/vibrant-heyrovsky-uc4n8

Thanks Ray

**Comment by alexreardon** [comment]
Let me know if this works for you: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md

**Comment by rayray93** [comment]
@alexreardon still got same bug... am i doing it right? 

https://codesandbox.io/s/vibrant-heyrovsky-uc4n8

**Comment by rayray93** [comment]
@alexreardon Thanks all good, solved with css no need for portal :)
transform: none did the trick !

**Comment by gijsbotje** [comment]
i fixed the drawer in https://github.com/mui-org/material-ui/pull/16281 for the future 😉

**Comment by oliviertassinari** [comment]
Shouldn't it work, even with a transform: translate prop applied?

**Comment by oliviertassinari** [comment]
Shouldn't it work, even with a transform: translate prop applied?

**Comment by gijsbotje** [comment]
@oliviertassinari maybe this demo will illustrate it better https://cs48m.codesandbox.io/. You can't see the dragged element unless you move your mouse over to the left side of the window.
it's the same issue as with the slide transition component, which is now merged.
in https://github.com/mui-org/material-ui/pull/16297 i fixed the grow component and also the zoom to fix all of the issues.
@rayray93 i also changed your DraggableList component so the pencil is also included in the dragged element. :)
