### ISSUE TITLE
Grid Layout?

### ISSUE THREAD

**Issue by a15n** [atlassian/react-beautiful-dnd#133]
## Feature Request

I'm looking to create a drag-and-drop **grid** system. I'm able to do this using react-dnd and a column/row layout, but I would love to use react-beautiful-dnd and leverage all the great features you've all built. 

In [this issue](https://github.com/atlassian/react-beautiful-dnd/issues/4) @oyeanuj mentions a grid layout. You say that grids are "out of scope" and I was just checking in to see if grids are anywhere on the roadmap? Or if you have any recommendations on other libraries or approaches to make a dnd grid. 

Great work on this library @alexreardon! Thanks for your help.

### Demo
![grid-dnd](https://user-images.githubusercontent.com/7050871/31140337-f8575a6e-a828-11e7-835c-deadd9bd7068.gif)

**Comment by jaredcrowe** [comment]
Hey @a15n :) At the moment the focus for this library is on sorting lists, so we only support reordering along a single axis. Reordering across multiple axes is something we might consider implementing in the future but for now we're focused on nailing the experience for lists, so this isn't on the immediate roadmap.

**Comment by krvajal** [comment]
You can emulate this using several horizontal lists.

**Comment by lmenus** [comment]
+1

**Comment by acomito** [comment]
+1

**Comment by raRaRa** [comment]
Would love to see this implemented. Any good alternatives?

**Comment by krvajal** [comment]
Maybe take a look at react-sortable-hoc.

**Comment by raRaRa** [comment]
> Maybe take a look at react-sortable-hoc.

I tried them real quick and was quickly disappointed that they are dependent on fixed size elements 😢

**Comment by alex-shatalov** [comment]
this feature whould be great!, has the same problem of grid dragging

**Comment by dumistoklus** [comment]
@jaredcrowe after one year you are ready to reconsider your decision about grid?

**Comment by prakashsvmx** [comment]
+1

**Comment by domtes** [comment]
+1

**Comment by lenastshaleb** [comment]
+1

**Comment by CharlieBickerton** [comment]
+1

**Comment by hckhanh** [comment]
+1

**Comment by Rennie1213** [comment]
+1

**Comment by GGantulga** [comment]
similar to this one
http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=lptm8r

**Comment by bedhed** [comment]
+1

**Comment by cocacrave** [comment]
+1 just in case

**Comment by JamieWilliamsHackIT** [comment]
+1

**Comment by mrondon** [comment]
+1

**Comment by dogrultan** [comment]
+1

**Comment by LucasMatuszewski** [comment]
+1

**Comment by wejrox** [comment]
+1

**Comment by Crypto2557** [comment]
+1

**Comment by miuchan** [comment]
+1

**Comment by joshuaiz** [comment]
+1

**Comment by arthurpankiewicz** [comment]
+1

**Comment by alexey-pravdin** [comment]
+ 1

**Comment by c10ckw0rk** [comment]
+ 1

**Comment by Ashar2shahid** [comment]
+1

**Comment by crapthings** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/316

**Comment by erikkjernlie** [comment]
+1

**Comment by abtx** [comment]
+1

**Comment by sherfruit** [comment]
+1

**Comment by LoicGoyet** [comment]
+1

**Comment by hckhanh** [comment]
+1

**Comment by lucbas** [comment]
+1

**Comment by rbreahna** [comment]
+1

**Comment by borokhnatalia** [comment]
+1

**Comment by hckhanh** [comment]
+1

**Comment by alexreardon** [comment]
> Still not possible .After 3 years? Wow..

I find comments like this really demoralising

**Comment by alexreardon** [comment]
Locking this to avoid spam. Tracking this feature here: #316 💃
