### ISSUE TITLE
Drop somewhere else to delete/remove

### ISSUE THREAD

**Issue by seanyesmunt** [atlassian/react-beautiful-dnd#1331]
### Description

I feel like this must be mentioned somewhere, either in an issue or in the docs but I can not find anything. Sorry if I missed it.

I'm planning to a drop zone that deletes an item when I drop something into it.

I was hoping I could just use something like this (simplified for readability)
```
    <DragDropContext onDragEnd={handleDragEnd}>
      <Droppable droppableId="droppable" direction="horizontal">
        {(provided, snapshot) => (
          <div ref={provided.innerRef} {...provided.droppableProps}>
            {items.map((item, index) => 
                <Draggable key={item} draggableId={item} index={index}>
                  {(provided, snapshot) => <div ... />}
                </Draggable>
            ))}
          </div>
        )}
      </Droppable>
      <Droppable droppableId="delete">
        {(provided, snapshot) => (
          <div ...>
            Drop to delete
            ...
          </div>
        )}
      </Droppable>
    </DragDropContext>
```

But I saw that `Droppable`'s must contain a `Draggable`. My delete zone doesn't need to be a draggable, and I'm not adding an item to a list, which is what the example for dragging to a different droppable does.

I'm mostly looking for documentation on if this is possible and or a recommended way to go about it.

**Comment by alexreardon** [comment]
Sure it is possible! Just set up a droppable that is your delete target. Make sure it is has a height and width so that a user can drag over it

**Comment by alexreardon** [comment]
And then in your onDragEnd you can remove the item

**Comment by seanyesmunt** [comment]
Where would the `Droppable` go? Would it be listed inside of the other `Droppable`?

I'd be happy to add this to the docs somewhere (if it isn't already listed somewhere)?

**Comment by alexreardon** [comment]
Your droppable can just be empty - and you can drop things into it. Then in your onDragEnd you can remove the item
