### ISSUE TITLE
Layout thrashing while dragging

### ISSUE THREAD

**Issue by saravanan10393** [atlassian/react-beautiful-dnd#1339]
### Expected behavior
No un-necessary layout work should happen

### Actual behavior
Un-necessary layout work slows down my dragging when i have list item of 100+ items,
though I followed the optimization strategies in the given optimization help github page

### Steps to reproduce
I recorded the attached video demo while using lazily loading list example

### What version of `React` are you using?
^React 16.8.0

### What version of `react-beautiful-dnd` are you running?
Latest

### What browser are you using?
Chrome 74

### Demo
https://youtu.be/q6ZHUnph53M

**Comment by alexreardon** [comment]
That looks quite laggy. The big flashes are caused by recollecting the droppable dimension for dynamic changes during a drag. We will be moving away from this strategy for #68
