### ISSUE TITLE
Dragging Items Between Nested Lists

### ISSUE THREAD

**Issue by kgorgi** [atlassian/react-beautiful-dnd#134]
## Bug or feature request?
Question/Feature Request

In one of your provided examples, [nested vertical list](https://react-beautiful-dnd.netlify.com/?selectedKind=complex%20vertical%20list&selectedStory=nested%20vertical%20lists&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel), a user can drag within a nested list but not drag between nested lists (dragging an item from _second level_ to the _top level_ or vice versa in the linked example above). Is this use-case currently possible with react-beautiful-dnd, dragging items between nested lists?

**Comment by kgorgi** [comment]
I just found in the README.md that the library does not support this (see below). Thus answering my own question. 

> Independent nested lists - a list can be a child of another list, but you cannot drag items from the parent list into a child list

So let me change my question: Is there are plans for this type of feature in the future?

**Comment by jaredcrowe** [comment]
hey @kgorgi, this is definitely something which we'd be open to adding in the future, but it's not on our immediate roadmap. right now we're focused on nailing the experience for sorting flat lists :)

**Comment by williaster** [comment]
we have a huge need for this, any pointers on direction / would you accept a PR for this?

**Comment by williaster** [comment]
@jaredcrowe wanted to bump my ^question

**Comment by jaredcrowe** [comment]
Hey @williaster this isn't on our roadmap right now, and at this stage I'd say we'd consider it out of scope for this library.

**Comment by ajay-gandhi** [comment]
@williaster You might be able to use the technique mentioned in #212

**Comment by krisl** [comment]
is it supported to drag items between two sibling lists? eg drag item between two second level containers?
