### ISSUE TITLE
Nested scroll container inside droppable

### ISSUE THREAD

**Issue by ggunia** [atlassian/react-beautiful-dnd#1348]
### Expected behavior
Auto scroll as item gets near to scroll container bottom

### Actual behavior
I know that to be able to auto scroll I should set droppableProps and innerRef on scrollContainer, but then it's hard to move one item in another section. You can check it on sandbox example.

### Steps to reproduce
drag element at the end of the scroll container

### Suggested solution?
differentiate droppable element and scroll container 

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
11.0.3

### What browser are you using?
Google chrome

### Demo
https://codesandbox.io/s/board-vmffc

**Comment by alexreardon** [comment]
This is not supported right now

**Comment by alexreardon** [comment]
Let's consider this as a part of #131

**Comment by InstantHuman** [comment]
POSSIBLE SOLUTION to 'NESTED SCROLLING CONTAINER DETECTED' error
This fix only applies if Overflow-X or Overflow-Y is being set on any parent container of the Droppable container

A fellow react developer and myself just spent several hours trying to solve this one.
Here is what we discovered.

OUR SETUP
We are using 'react-beautiful-dnd' with a 'react-virtualized' list, and using 'ant-design' as our UI Library.

WHAT TRIGGERS THE ERROR:
==> IF a parent to the Droppable container has Overflow-X or Overflow-Y set to (hidden or auto), without also setting the other 'X' or 'Y' to hidden. THEN react 'assumes on its own' and auto-sets the one you DID NOT SET, (either Overflow-Y or Overflow-X) to 'auto' ...triggering the error.

It is automatically setting the one you did not set, to 'auto', turning the parent into a 'Scrolling Container'.

TO FIX THIS:
- In our case, we removed the Overflow-X (hidden or auto) style from the parent container, and replaced it with (Overflow: 'hidden'). You could also just ensure that NO OVERFLOW setting is set, or set BOTH overflow X & Y to 'hidden'.
- Just DO NOT set one without the other!
