### ISSUE TITLE
No animation in the list the item was moved from in the board example

### ISSUE THREAD

**Issue by thupi** [atlassian/react-beautiful-dnd#135]
## Bug or feature request?
Bug

### Expected behaviour
The expected behaviour would be that the list the item was removed from also have a nice animation. 

### Actual behaviour
Right now the list the item is moved to have a expected animation. However the list the the item is leaving is note aniamted which leads to a slightly less satisfying experience.

### Steps to reproduce
1. Go to https://react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=task%20board&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

2. Drag a item from the last list list to the first list.

3. Observe the animation in the last list.

### Browser version
Google Chrome - Version 61.0.3163.100

### Demo
https://react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=task%20board&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by jaredcrowe** [comment]
Thanks for bringing this up as a feature you'd like to see @thupi. It's something we're keen to add soon too - we're already tracking this in #77 :)
