### ISSUE TITLE
Table Row space lost on drag  (v10.1 onwards)

### ISSUE THREAD

**Issue by Ajaay** [atlassian/react-beautiful-dnd#1350]
### Expected behavior

Table row space maintained on Drag.

### Actual behavior

Table row space lost on drag. 10.0.4 works as expected. 10.1 and onwards it does not. However I notice in the stories it works fine. I couldn't find any info in the change log.

**Comment by alexreardon** [comment]
You need to add the `DroppableProvided.placeholder`

https://codesandbox.io/s/react-table-react-beautiful-dnd-simple-table-5ns7t
