### ISSUE TITLE
Is the code for the egghead.io tutorials available from another location?

### ISSUE THREAD

**Issue by AndrewMayer** [atlassian/react-beautiful-dnd#1356]
I've been following the tutorial on egghead.io but it seems like at some point the base code used in the demos diverged from the previous lessons (lesson 12). Specifically the start and finish consts are changed home and foreign. I think there are some other changes as well and I can't get my code to function..

I'd love to check the code and update, especially since the functionality being described here is very similar to my intended use for the library, but the code is only available to paying members. Is there anywhere else that the code for these tutorials has been posted so I can check it against the version I'm working with?

**Comment by alexreardon** [comment]
This one? https://egghead.io/lessons/react-customize-screen-reader-messages-for-drag-and-drop-with-react-beautiful-dnd

**Comment by AndrewMayer** [comment]
> This one? https://egghead.io/lessons/react-customize-screen-reader-messages-for-drag-and-drop-with-react-beautiful-dnd

That's it. If possible I wanted to find a public code repository for those examples since the code there is behind a paywall.

**Comment by alexreardon** [comment]
Here is the repo I worked from.

It will not be exactly the same as the egghead one as they wrote that one

The different branches = different lessons

https://github.com/alexreardon/react-beautiful-dnd-task-app/tree/lesson-12/src
