### ISSUE TITLE
Providing innerRef as a prop to Draggable and Droppable

### ISSUE THREAD

**Issue by schabluk** [atlassian/react-beautiful-dnd#1359]
### Disclaimer

I have read the [Using innerRef](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md) guide.

### Description
Would it be possible to allow providing `innerRef` as a prop to `Draggable` and `Droppable`? Like:

```javascript
<Draggable draggableId="draggable-1" index={0} innerRef={refFrom3rdParty}>
  {(provided, snapshot) => <div ref={provided.innerRef}>Drag me!</div>}
</Draggable>
```

[Some libraries](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#breaking) already provide their mandatory references:

> You must now assign attributes.ref to a DOM node. This new attribute that is passed to the rendering functions must be passed into a native DOM component (...).

I could get around this, just by wrapping a div with a div, but that makes DOM tree too deep, in case I have nested Lists:

```javascript
<Draggable draggableId={node.key} index={index}>
  {(provided, snapshot) => (
    <div
      ref={provided.innerRef}
      {...provided.draggableProps}
      {...provided.dragHandleProps}
    >
      <div {...attributes}> // <-- passing reference from attributes.ref
        {children}
      </div>
    </div>
  )}
</Draggable>
```
Ideally, it could be done like this:
```javascript
const { ref, ...rest } = attributes
// ...
<Draggable draggableId={node.key} index={index} innerRef={ref}> // <-- passing reference
  {(provided, snapshot) => (
    <div
      ref={provided.innerRef}
      {...provided.draggableProps}
      {...provided.dragHandleProps}
      {...rest}
    >
      {children}
    </div>
  )}
</Draggable>
```

**Comment by alexreardon** [comment]
Interesting!

**Comment by moonray** [comment]
Using forwardRef is probably the better way to go at this point, but the functionality would be welcome.

**Comment by schabluk** [comment]
@moonray could you please explain how would that work?

From what I see in the [code](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable/draggable.jsx#L29), there is no option for forwarding ref, as it is set internally by a [callback ref](https://pl.reactjs.org/docs/refs-and-the-dom.html#callback-refs). Am I missing something obvious here?

**Comment by moonray** [comment]
Rather than doing `const ref = useRef<?HTMLElement>(null);` it would conditionally take a passed in (forwarded) ref.

e.g. 
```
export default function React.forwardRef(
  Draggable(props: Props, ref: React.Ref< HTMLElement >) {
    const actualRef = ref ? ref : useRef<?HTMLElement>(null);
    ...
  }
);
```

**Comment by alexreardon** [comment]
Can you not just monkey patch the provided.innerRef function?

**Comment by schabluk** [comment]
@alexreardon that was also my idea, but the mutable `ref` property that I need to assign to, is a local const of the `Draggable` function:

```javascript
const ref = useRef<?HTMLElement>(null);
```

So, I would need to do something like:
```javascript
const setRefMonkey = useCallback((el: ?HTMLElement) => {
  ref.current = attributes.ref.current; // <--- ref in local scope?
}, []);

return (
  <Draggable draggableId={node.key} index={index}>
    {(provided, snapshot) => {
      provided.innerRef = setRefMonkey
      return (
        <div
          ref={provided.innerRef}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
          {...rest}
        >
          {children}
        </div>
      )
    }}
  </Draggable>
)
```
Would that be the way?

**Comment by alexreardon** [comment]
```diff
const setRefMonkey = useCallback((el: ?HTMLElement) => {
  ref.current = attributes.ref.current; // <--- ref in local scope?
}, []);

return (
  <Draggable draggableId={node.key} index={index}>
    {(provided, snapshot) => {
      provided.innerRef = setRefMonkey
      return (
        <div
+          ref={(ref) => {
+            setRefMonkey(ref);
+            provided.innerRef(ref);
+          }}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
          {...rest}
        >
          {children}
        </div>
      )
    }}
  </Draggable>
)
```
