### ISSUE TITLE
Transitioning between lists with the keyboard does not respect container clipping

### ISSUE THREAD

**Issue by jaredcrowe** [atlassian/react-beautiful-dnd#136]
### Bug or feature request?
Bug

### Expected behaviour
When moving between lists with the keyboard, a droppable's dimension will be clipped if it's within in a scroll container.

### Actual behaviour
A droppable's dimensions do not appear to be clipped by a scrollable parent.

### Steps to reproduce
On the multiple vertical lists stress test story:
1. Add a lot of items to the epsilon board
2. Scroll all the way to the bottom of epsilon's container
3. Try to move an item into the delta board with the keyboard

### Browser version
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Demo
https://drive.google.com/file/d/0B9It2FnzHQ-vSmFvVGZOVW5OTE0/view

**Comment by jaredcrowe** [comment]
Hoping this will be an easy fix once #132 gets in.

**Comment by alexreardon** [comment]
Was this created by the last clipping change?

**Comment by jaredcrowe** [comment]
Yeah I expect it probably would have been :( This issue only pops up when you've got long droppables inside scroll containers sitting on the same main axis - I'll add some tests to make sure we cover this case.
