### ISSUE TITLE
Add support for removing a draggable during a drag

### ISSUE THREAD

**Issue by rickdzekman** [atlassian/react-beautiful-dnd#1362]
It would be good if removing a draggable during a drag didn't cause an error.

**Our use case**

We're implementing realtime updates in our app so that if one user modifies a board then another user looking at the same board receives an update with those changes.

For the most-part this works fine _except_ if you are dragging a card as it is removed by another user. e.g. 
1. Another user moves a card from `list-1` to `list-2`
2. That update is pushed to you via a websocket
3. In the meantime you pick up that same card from `list-1` to move it elsewhere
4. The update comes through and removes the card from `list-1` while it's being dragged

That crashes with `Error: Invariant failed: Cannot remove the dragging item during a drag`.

Appreciate that an item disappearing while it's being dragged might break physicality but that feels better than crashing.

**Comment by alexreardon** [comment]
I would suggest blocking updates while a drag is occurring. Otherwise it is a fairly strange user interaction.

You could keep your current behaviour by explicitly cancelling a drag if the dragging item is being removed. You can do this by firing an 'escape' event
