### ISSUE TITLE
Broken item indexes

### ISSUE THREAD

**Issue by ggunia** [atlassian/react-beautiful-dnd#1366]
### Expected behavior
When indexes of draggable items are not sequential (for example: 1, 3, 5, 7), when I drag Item to be second position (but that item's index is 3 actually) it should return index in final destination which is 3 not 2

### Actual behavior
Actual behavior is that it does not look at indexes defined by user

### Steps to reproduce
drag item and look at console

### Suggested solution?
Take in count indexes passed to draggable items. Actually in version 9, it was working properly.

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
11.0.4

### What browser are you using?
chrome

### Demo
https://codesandbox.io/s/board-u0fy8

**Comment by alexreardon** [comment]
We [require indexes to be sequential](https://github.com/atlassian/react-beautiful-dnd/blob/ce8a68cdbfdb71502faed5fefa421f4b28334893/docs/guides/common-setup-issues.md#draggable--indexes)

**Comment by alexreardon** [comment]
I am planning on adding a dev warning for this gotcha
