### ISSUE TITLE
Cannot get onClick event to fire on a draggable element in latest ios safari

### ISSUE THREAD

**Issue by jimmybillings** [atlassian/react-beautiful-dnd#1367]
### Expected behavior
I should be able to add an onClick handle to a draggable element and see it fire when I click on the draggable element without dragging it. 

### Actual behavior
Almost never fires the click event. If I keep persisting it will. 

### Steps to reproduce
Visit the example for a simple list on an ios device using safari - https://react-beautiful-dnd.netlify.com/iframe.html?id=single-vertical-list--basic

On a desktop if you click one of the items it will link you to another url, but on a ios mobile using safari if you touch one of the items it doesn't go anywhere. I haven't confirmed this is only with IOS and safari and not all mobile. I'm also wondering if there is any correlation with this and the following issue which I'm also experiencing: https://github.com/atlassian/react-beautiful-dnd/issues/1314

**Comment by alexreardon** [comment]
Is this an issue?

**Comment by jimmybillings** [comment]
Potentially, I'm not sure how it's intended as I didn't find a ton of documentation on using onClick with dnd on a mobile device. 

I moved to onTouchEnd with some prevent default logic to make it work on mobile that works but using onClick never seemed to work, not just safari but all browsers. I've never run into this before doing responsive sites with react, onClick has always seemed to work fine but this solution is fine for me with onTouchEnd if that's how you designed it.

**Comment by alexreardon** [comment]
My expectation is that clicking should be unaffected by `rbd`. Let me know how you go

**Comment by jimmybillings** [comment]
Ok. After more testing onClick is definitely not working on ios with all browsers, at least in my case. Seems to work fine on android. I will put together a code sample on stackblitz to reproduce shortly. Thanks.

**Comment by alexreardon** [comment]
Thanks!

**Comment by jimmybillings** [comment]
Ok I have a code example. I have copied the simple list example and added an onClick handle to the element inside of Draggable that creates a browser alert. Works fine in the desktop browser but not in ios. Of course you will need to look at this from an iphone/ipad to view the potential bug. 

App url here: https://react-ub51sd.stackblitz.io
Editor Url here: https://stackblitz.com/edit/react-ub51sd

**Comment by alexreardon** [comment]
Before I dig into it more, can you please try using `react-beautiful-dnd@12.0.0-alpha.4` and see if that fixes the issue?

**Comment by jimmybillings** [comment]
I gave it a go but no luck unfortunately, same deal.

**Comment by alexreardon** [comment]
Did this only just start happening in the latest ios safari?

**Comment by alexreardon** [comment]
(it is okay if you are not sure)

**Comment by jimmybillings** [comment]
This is happening on Chrome, Firefox & Safari on IOS. Android seems to be fine across the board. I have an iphone 7 with the latest safari, chrome & firefox and happens on all. I also have an older iPad and I'm seeing the same thing there. I have several other QA members that have experienced the same (working on Android, not working on ios) both with our production code and the simpler code example I sent you just to be sure.

**Comment by alexreardon** [comment]
I am testing on latest safari and `onClick={() => alert('click')}` is working fine on a `Draggable`...

**Comment by alexreardon** [comment]
> On a desktop if you click one of the items it will link you to another url, but on a ios mobile using safari if you touch one of the items it doesn't go anywhere.

It is working fine on my iphone .. 😕

**Comment by jimmybillings** [comment]
When you visit this url on your iPhone and tap on an item you get an alert?

https://react-ub51sd.stackblitz.io/

**Comment by jimmybillings** [comment]
I’m testing that url above on multiple iPhone versions and still don’t get an alert on click. I’m not really sure how to proceed here but clearly something is off. I can create a video of this just to prove it but it’s not going to help anything I imagine. Thanks!

**Comment by alexreardon** [comment]
Maybe there is something going on with the stackblitz platform?

Given that `onClick={() => alert('click')}` is working... 🤔

**Comment by dovydaskukalis** [comment]
Our "solution" was to downgrade to 10.1.1 which is the latest version that works... All the later versions including 12 alphas are not working. All touch/click events seems to be swallowed when you touch draggable element. Even the official examples like https://react-beautiful-dnd.netlify.com/iframe.html?id=single-vertical-list--basic and https://react-beautiful-dnd.netlify.com/iframe.html?id=board--simple are not working for me. Running Safari on iOS 12.3.1.

**Comment by jimmybillings** [comment]
Good to know @dovydaskukalis thank you.

**Comment by alexreardon** [comment]
It is interesting that 11.x is not working too 🤔

**Comment by alexreardon** [comment]
> "All touch/click events seems to be swallowed when you touch draggable element"

That is worrying

**Comment by alexreardon** [comment]
Can you please change `shouldRespectForcePress` to `true` and see if that fixes your issue?

**Comment by dovydaskukalis** [comment]
Unfortunately it didn't fix it, I tried on 11.0.4 and nothing changed, except now force touch works with it's default action of opening a preview popup.

**Comment by gavrichards** [comment]
> "All touch/click events seems to be swallowed when you touch draggable element"

This aligns with the issue I have reported regarding scrolling the container of draggable items:
https://github.com/atlassian/react-beautiful-dnd/issues/1396

**Comment by jimmybillings** [comment]
I'm also experiencing #1396, hopefully the fix well get both bugs resolved then. Thanks for the input.

**Comment by alexreardon** [comment]
https://bugs.webkit.org/show_bug.cgi?id=199658

**Comment by alexreardon** [comment]
I have shipped the workaround in an alpha for validation: 

`12.0.0-alpha.7`

Please try it out and let me know how it goes

**Comment by jimmybillings** [comment]
So far this has fixed all the problems for me. The screen is now scrolling correctly on a mobile and click is working as expected. Thank you for your hard work, this is a great product!

**Comment by alexreardon** [comment]
Fixed by #1407. Will also ship in 12.0 #1317
