### ISSUE TITLE
Expecting similar behaviour in React-beautiful-dnd.

### ISSUE THREAD

**Issue by sohansarma** [atlassian/react-beautiful-dnd#1368]
As I am using react-beautiful-dnd for quite a long time now but few issue I am getting that I am unable to solve. I want the behaviour of the board to be exactly like "https://edulan.github.io/react-virtual-kanban/". What can I do for the same?

**Comment by alexreardon** [comment]
What issues are you unable to solve?
What behaviour from react-virtual-kanban are you trying to achieve?

**Comment by sohansarma** [comment]
The page should be fixed while drag a card vertically outside the view port and scroll while dragging the card horizontally outside the view port.

**Comment by sohansarma** [comment]
> The page should be fixed while drag a card vertically outside the view port and scroll while dragging the card horizontally outside the view port.

@alexreardon Is there any possible solution for this ?
As I am seeing almost everyone with drag and drop package is having the behaviour.

**Comment by markdon** [comment]
I think you'd run into the single scroll container limitation trying to make something like the link. It looks like it's [next on the list](https://github.com/atlassian/react-beautiful-dnd/issues/131) though!

**Comment by alexreardon** [comment]
#131
