### ISSUE TITLE
children is not a function at Droppable

### ISSUE THREAD

**Issue by chafikchaban** [atlassian/react-beautiful-dnd#1372]
### Expected behavior
should be working fine, i followed the tutorial
### Actual behavior
An error has occurred while a drag is occurring.Any existing drag will be cancelled.> children is not a function
### Steps to reproduce
please review my code
### Suggested solution?
no idea

 i do have no idea!
### What version of `React` are you using?
"react": "16.8.6"

### What version of `react-beautiful-dnd` are you running?
"react-beautiful-dnd": "^11.0.3"

### What browser are you using?
chrome
Version 75.0.3770.90 (Official Build ) (64 bits)

### Demo
here's my code :

<Modal isOpen={modalIsOpen} onCancel={this.handleCloseModal} size="md">
        <ModalHeader onClose={this.handleCloseModal}>
          <Svg className="m-right--x-small" icon="gear" size="xx-large" />
          <span className="align-middle">
            <span className="text-bold">
              <FormattedMessage id="FacetsConfiguration.modalTitleStrong" />
            </span>{' '}
            <FormattedMessage id="Analytics.excel" />{' '}
            <FormattedMessage id="Analytics.exportMiniscule" />
          </span>
        </ModalHeader>
        <ModalBody>
          <div className="c-facets-configuration clearfix">
            <DragDropContext onDragEnd={this.onDragEnd}>
              {availableFacetGroups.length || windowWidth > BREAKPOINT.md ? (
                <div
                  className={classnames('c-facets-configuration__column', {
                    'p-bottom--medium': windowWidth < BREAKPOINT.md,
                  })}
                >
                  <div className="c-form-element__label">
                    <FormattedMessage id="ExcelExportConfiguration.availableSectionTitle" />
                  </div>
                  <Droppable droppableId={'1'}>
                    {provided => (
                      <ul
                        ref={provided.innerRef}
                        {...provided.droppableProps}
                        className="c-facets-configuration__options list-unstyled"
                        role="listbox"
                      >
                        {modalIsOpen &&
                          availableFacetGroups.map((facetGroupItem, index) => (
                            <Draggable
                              key={facetGroupItem.id}
                              draggableId={facetGroupItem.id}
                              index={index}
                            >
                              {provided => (
                                <ExportExcelConfigurationItem
                                  ref={provided.innerRef}
                                  {...provided.draggableProps}
                                  {...provided.dragHandleProps}
                                  isLast={
                                    availableFacetGroups.length === index + 1
                                  }
                                  item={facetGroupItem}
                                  key={facetGroupItem.id}
                                  onClick={this.handleItemClick}
                                  onToggle={this.handleToggle}
                                  selected={
                                    selectedFacetGroupId === facetGroupItem.id
                                  }
                                  windowWidth={windowWidth}
                                />
                              )}
                            </Draggable>
                          ))}
                        {provided.placeholder}
                      </ul>
                    )}
                  </Droppable>
                </div>
              ) : null}
              {windowWidth > BREAKPOINT.md ? (
                <div className="c-facets-configuration__controls">
                  <div className="c-facets-configuration__button-group button-group">
                    <Button
                      className="c-facets-configuration__button"
                      disabled={
                        selectedFacetGroupId == null ||
                        isSelectedFacetGroupIsDisplayed
                      }
                      onClick={this.handleRightClick}
                    >
                      <Svg icon="chevron-right" />
                    </Button>
                    <Button
                      className="c-facets-configuration__button"
                      disabled={
                        selectedFacetGroupId == null ||
                        !isSelectedFacetGroupIsDisplayed
                      }
                      onClick={this.handleLeftClick}
                    >
                      <Svg icon="chevron-left" />
                    </Button>
                  </div>
                </div>
              ) : null}
              <div className="c-facets-configuration__column">
                <div className="c-form-element__label">
                  <FormattedMessage id="ExcelExportConfiguration.selectedSectionTitle" />
                </div>
                <Droppable droppableId={'2'}>
                  <ul
                    className="c-facets-configuration__options list-unstyled"
                    role="listbox"
                  >
                    {displayedFacetGroups.map((facetGroupItem, index) => (
                      <ExportExcelConfigurationItem
                        isLast={displayedFacetGroups.length === index + 1}
                        item={facetGroupItem}
                        key={facetGroupItem.id}
                        onClick={this.handleItemClick}
                        onDownClick={this.handleDownClick}
                        onToggle={this.handleToggle}
                        onUpClick={this.handleUpClick}
                        selected={selectedFacetGroupId === facetGroupItem.id}
                        windowWidth={windowWidth}
                      />
                    ))}
                  </ul>
                </Droppable>
              </div>
              {windowWidth > BREAKPOINT.md ? (
                <div className="c-facets-configuration__controls">
                  <div className="c-facets-configuration__button-group button-group">
                    <Button
                      className="c-facets-configuration__button"
                      disabled={indexOfSelectedDisplayedFacetGroup < 1}
                      onClick={this.handleUpClick}
                    >
                      <Svg icon="chevron-up" />
                    </Button>
                    <Button
                      className="c-facets-configuration__button"
                      disabled={
                        indexOfSelectedDisplayedFacetGroup === -1 ||
                        indexOfSelectedDisplayedFacetGroup ===
                          displayedFacetGroups.length - 1
                      }
                      onClick={this.handleDownClick}
                    >
                      <Svg icon="chevron-down" />
                    </Button>
                  </div>
                </div>
              ) : null}
            </DragDropContext>
          </div>
        </ModalBody>
        <ModalFooter className="text-right">
          <Button onClick={this.handleCloseModal} type="link">
            <FormattedMessage id="Global.cancel" />
          </Button>
          <Button onClick={this.handleValidationClick} type="success">
            <FormattedMessage id="Global.validate" />
          </Button>
        </ModalFooter>
      </Modal>

![image](https://user-images.githubusercontent.com/30408070/59921439-eb156d80-942d-11e9-944a-55865b3325d9.png)

**Comment by chafikchaban** [comment]
![image](https://user-images.githubusercontent.com/30408070/59921508-27e16480-942e-11e9-8cf1-22e37828859c.png)

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by chafikchaban** [comment]
i fixed it. thanks for your attention @alexreardon

**Comment by samullman** [comment]
I am now getting this.

TypeError: children is not a function
```
Droppable
node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8343

renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:16319

mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:18734
``` 

Gatsby 2.16.1
React 16.10.2
React-Beautiful-Dnd 12.0.0

I scoped it so that:
```
if (typeof window !== undefined) {
  <DragDropContext >
    <Droppable >
      <Draggable >
        <div>
           Hello
        </div>
       </Draggable>
     </Droppable>
   </DragDropContext>
}
```
same error

**Comment by alexreardon** [comment]
Hi there! We expect the child of a `<Droppable>` and `<Draggable>` to be a function:

- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#children-function
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#children-function-render-props--function-as-child

**Comment by DZGoldman** [comment]
It looks like the children of the `<Droppable>` and `<Draggable>` components are both functions in @chafikchaban 's example, no?
