### ISSUE TITLE
[12.0.0-alpha.4] Dragging on iOS Safari

### ISSUE THREAD

**Issue by petermikitsh** [atlassian/react-beautiful-dnd#1374]
### Expected behavior

The viewport remains stationary. This is 11.0.4:

![11 0 4](https://user-images.githubusercontent.com/1571918/59967993-9cc4a500-94e7-11e9-8423-58e537a56497.gif)

### Actual behavior

Viewport moves around when selecting Draggables. This is 12.0.0-alpha.4:

![12 0 0-alpha 4](https://user-images.githubusercontent.com/1571918/59967999-b534bf80-94e7-11e9-8888-c7de318d1406.gif)

### Steps to reproduce

Exact same code, upgraded to `12.0.0-alpha.4`.

### Suggested solution?

Not sure.

### What version of `React` are you using?

`16.8.6`

### What version of `react-beautiful-dnd` are you running?

`12.0.0-alpha.4`

### What browser are you using?

iOS Safari

**Comment by alexreardon** [comment]
😲

Thanks! We will need to fix this in the `alpha`!!

**Comment by alexreardon** [comment]
Need to fix for: #1317

**Comment by alexreardon** [comment]
I have reproduced this locally

**Comment by alexreardon** [comment]
I have fixed this locally with a webkit hack :|

Sigh

Anyway, i'll do another alpha release soon

**Comment by alexreardon** [comment]
@petermikitsh can you please try `react-beautiful-dnd@12.0.0-alpha.6`?

**Comment by petermikitsh** [comment]
I have verified `react-beautiful-dnd@12.0.0-alpha.6` fixes the issue, thanks!

**Comment by neooleg** [comment]
@alexreardon @petermikitsh  what do you think -- current issue is related to #1684?
