### ISSUE TITLE
Can I force the result.source.index to be re-calculated even without adding/removing draggables during drag?

### ISSUE THREAD

**Issue by ZYinMD** [atlassian/react-beautiful-dnd#1375]
Suppose I have a list like this:
```
<List>
  <Item />
  <Item />
  <Item />
  <Item />
<List />
```

Scenario A: 
After some user interaction, the list becomes this:
```
<List>
  <Item hide />
  <Item hide />
  <Item />
  <Item />
<List />
```
The `Item` component has `if (hide) return null`, so there are only 2 items rendered on the screen, note the underlying data (array of 4) didn't change, and `List` didn't re-render. 

If I drag the last item, `result.source.index` will be 3

Scenario B:
I drag the last item without hiding the first 2 items before drag, but I hide them onDragStart. This time there are also 2 items on the screen after drag, underlying data still didn't change, but `result.source.index` will be 1. 

In my project, the inconsistency between A and B becomes an issue, because sometimes I hide some items onDragStart, sometimes I don't. I prefer the behavior of B, can I force the index to update in A?

Thanks!

**Comment by alexreardon** [comment]
In this case you seem to be deviating from our scope. Would it be possible for you to account for the hiding in your own reorder function? You should know which items are hidden and adjust accordingly

**Comment by ZYinMD** [comment]
Thanks @alexreardon , yes I found that instead of using `result.source.index`, I can use `result.draggableId` to get all information about the item dragged, including the true source index. Thanks for your help.
