### ISSUE TITLE
Nested list, Drop sub item in both parent and sub container

### ISSUE THREAD

**Issue by jamsheerkrd** [atlassian/react-beautiful-dnd#1393]
I was trying to implement drag and drop for html grid system ( row and col arranged divisions) using react beautiful dnd.

The code can be viewed at https://codesandbox.io/s/nested-dnd-across-parent-pvkzj ( this is forked from https://codesandbox.io/s/5v2yvpjn7n )

The changes i made is remove the type from droppable as I want columns also to be drop in parent container .

The problem I'm facing is that the sub item can't drag upward and drop in parent container, It can drag to downward without no issues. The parent container can drag up and Down

**Comment by alexreardon** [comment]
See #316
