### ISSUE TITLE
Delete an element by key from Array

### ISSUE THREAD

**Issue by yaverm** [atlassian/react-beautiful-dnd#1398]
I used library [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) for drag and drop element, but the library documentation does not have any actions for delete items. I want to delete, drag and drop item when click on close button. Which method is right for removing elements by key from object?

```
const SortableItem = SortableElement(({ value }: { value: string }, onRemove: any) =>
    <div className="dragItems" style={{ background: 'gray' }}>
        <img src={value} alt="" />
        <button className="dragCloseBtn" onClick={() => onRemove(any)} />
    </div>

);

const SortableList = SortableContainer(({ items }: { items: string[] }) => {
    return (
        <div className="dragAndDrop">
            {items.map((value, index) => (
                <SortableItem key={'item-${index}'} index={index} value={value} />
            ))}
        </div>
    );
});

constructor(props: any) {
    super(props);
    this.state = {
        items: [
            { 
                "id": 0, 
                "link": "https://via.placeholder.com/150"
            },
            { 
                "id": 1, 
                "link": "https://via.placeholder.com/150"
            }
        ],
    };
}

public onSortEnd = ({ oldIndex, newIndex }: { oldIndex: number, newIndex: number }) => {
    this.setState({
        items: arrayMove(this.state.items, oldIndex, newIndex),
    });
};

public onRemove(e: { target: { value: any; }; }) {
    const array = [...this.state.items]; 
    const index = array.indexOf(e.target.value)
    if (index !== -1) {
        array.splice(index, 1);
        this.setState({items: array});
    }
}

<SortableList items={this.state.items}
              onSortEnd={this.onSortEnd}
              lockAxis="xy"
              axis="xy" />
```

**Comment by alexreardon** [comment]
https://love2dev.com/blog/javascript-remove-from-array/

**Comment by alexreardon** [comment]
Is that what you are after?

**Comment by alexreardon** [comment]
https://stackoverflow.com/questions/5767325/how-do-i-remove-a-particular-element-from-an-array-in-javascript

**Comment by alexreardon** [comment]
Let me know if that is not what you were after

**Comment by hariria** [comment]
I want to remove an element when I click this trashcan icon. Currently, it doesn't rerender when I set the state. It only rerenders afterward when I begin to drag on a new object

this is my trashOnClick function
`const trashOnClick = (index) => {
        var tempItems = items;
        tempItems.splice(index, 1);
        setItems(tempItems);
    }`

`<div className="trash-container" >
                                                        <IconButton onClick={(event) => {trashOnClick(index)}} style={{padding: "0px"}} aria-label="delete">
                                                            <DeleteIcon fontSize="small" />
                                                        </IconButton>
                                                    </div>`

How do I force a rerender when I delete an element?

**Comment by alexreardon** [comment]
tempItems.splice(index, 1) is modifying your original array. So there is no reference change, so react won't re-render.

Try:

```js
var shallowCopy = [...items];
shallowCopy.splice(index, 1);
setItems(shallowCopy)
```

**Comment by hariria** [comment]
Got it thanks!
