### ISSUE TITLE
Responder is not a function

### ISSUE THREAD

**Issue by xcmcpx** [atlassian/react-beautiful-dnd#1400]
### Expected behavior
Drag item to another droppable list like in many examples and tutorials. I am trying to create my own kanban or trello board, and I'm almost there.
### Actual behavior
Item is dragged over, then a quick pause, item is cleared and errors are shown.

This doesn't break the application, but it does repeat the error every drag and drop. Doesn't matter which droppable zone or which item is dragged. They all give the same error.

### Steps to reproduce
Drag an item from any column/droppable and drop in another.
This also happens when you drag an item and drop it where it previously was or in the same column.
### Suggested solution?
I wish I knew but I don't :(

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
11.0.4

### What browser are you using?
Google Chrome

### Demo
I can provide a snippet of my code if need be! However, from the screenshots I believe the error isn't in my code? See for yourself!

You can see the attempted drag over via the blurred out draggable in the "in progress" column, and then the final screen shot is a picture of the beginning and end results. The item will drop into the new column, delay for a second, and then reset to the beginning and present the error.

![ResponderNotFunction](https://user-images.githubusercontent.com/29145704/61016980-9d6e8f80-a35f-11e9-85e1-24d442cb5aad.PNG)
![attemptedDnD](https://user-images.githubusercontent.com/29145704/61017105-05bd7100-a360-11e9-87a2-4e7cf9d603d3.PNG)
![endResult](https://user-images.githubusercontent.com/29145704/61017106-06560780-a360-11e9-948d-97d50ae8fb27.PNG)

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by xcmcpx** [comment]
Yes I will try to get that done today!

**Comment by xcmcpx** [comment]
Here is a link to the issue! It's still giving an error, but it's not as detailed in this...

https://codesandbox.io/s/chrispcodes-kanban-error-ewxdz

**Comment by xcmcpx** [comment]
Anyone got any clues?

**Comment by alexreardon** [comment]
`onDragEnd` needs to be a function

https://codesandbox.io/s/chrispcodes-kanban-error-8md08
