### ISSUE TITLE
onDragEnd not firing until you attempt to drag another item

### ISSUE THREAD

**Issue by tn3rb** [atlassian/react-beautiful-dnd#1408]
First time using `react-beautiful-dnd` and everything has been working GREAT...
right up until I need to actually reorder the items in my list.

I'll confess right up front that I have another project dependency that is forcing my React version to stay at `16.8.4` and I am trying to get that resolved through other channels but still wanted to raise this issue in the hopes that you might have some insights that will help me in the meantime (so plz plz don't just boot me immediately for that).

So what's happening is that I can drag an item, but upon dropping... nothing happens... ie: my callback for reordering the list just does not get called. As well, the list item visually still looks the same as when it was being dragged. 

However, as soon as I attempt to drag another item, my reorder callback is triggered and the logic within that function appears to work without any other issues.

It is also worth noting that my list is rendered as an HTML table, but I have passed the appropriate refs through using an `innerRef` prop. (at least I think I have).

Does it logically make sense that this issue would be occurring simply because my React version is a single patch behind? If you don't think that is likely, then I can attempt to recreate the issue on codesandbox.io with as much of my code as possible.

### Expected behavior
`onDragEnd` getting called as soon as an item is dropped

### Actual behavior
`onDragEnd` for dragged item does not get called until a second item is dragged

### What version of `React` are you using?
`16.8.4` i know i know... don't crucify me plz !

### What version of `react-beautiful-dnd` are you running?
`11.0.4`

### What browser are you using?
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

Thank you for your time, effort, and talent, as well as any assistance you can provide me with regards to this issue. It is greatly appreciated.

**Comment by heatherbooker** [comment]
I seem to be running into this too, with React `16.8.6` and react-beautiful-dnd `11.0.4`. The onDragStart and onDragUpdate fire as expected, but onDragEnd doesn't fire until I start to drag a different item.

**Comment by tn3rb** [comment]
oh? with 16.8.6? crazy...

what kind of DOM elements are you using for your list? 
my setup is using HTML tables so ultimately it's `<tr>` elements I'm moving, but as I stated in my initial post I've added the appropriate refs via an `innerRef` prop.

**Comment by heatherbooker** [comment]
I'm using just `div`s; I'm trying to get a code sandbox set up to demonstrate but I can't get one to even not have errors. 😞

**Comment by sivadass** [comment]
@heatherbooker thanks for your suggestion, i also had the same problem. I missed to spread the `provided.draggableProps` but directly using `provided.draggableProps.style`.

```
<Draggable
     id={elementId}
     draggableId={elementId}
     index={index}
>
     {(provided, snapshot) => (
          <div
                ref={provided.innerRef}
                {...provided.draggableProps} // missed this line
                style={getItemStyle(
                    snapshot.isDragging,
                    provided.draggableProps.style
                 )}
           >
               <span {...provided.dragHandleProps}>
                    <i className="material-icons">drag_indicator</i>
               </span>
   ....
```

**Comment by tn3rb** [comment]
@heatherbooker and @sivadass  thanks for the feedback 👍 

unfortunately that was not the issue for me :(

I was already applying the draggable styles correctly:

```jsx
<DragDropContext
	onBeforeDragStart={ onBeforeDragStart }
	onDragStart={ onDragStart }
	onDragUpdate={ onDragUpdate }
	onDragEnd={ onDragEnd }
>
	<Table
		tableId={ this.tableId }
		tableClass={ this.classes.tableClass }
		captionID={ this.captionID }
		captionText={ this.tableCaption }
	>
		<TableHeader htmlClass={ this.classes.headerClass }>
			{ tableHeader }
		</TableHeader>
		<Droppable droppableId={ droppableId }>
			{ (
				{ innerRef, droppableProps, placeholder },
				{ isDraggingOver }
			) => (
				<TableBody
					innerRef={ innerRef }
					htmlClass={ this.classes.bodyClass }
					style={ {
						border: isDraggingOver ?
							'1px solid var(--ee-color-bright-green)' :
							'none',
						borderSpacing: isDraggingOver ?
							'2px' :
							'0',
					} }
					{ ...droppableProps }
				>
					{ rowData.map(
						( dataRow, index ) => (
							<Draggable
								key={ dataRow[ 0 ].id }
								draggableId={ dataRow[ 0 ].id }
								index={ index }
							>
								{ ( provided, snapshot ) => (
									renderDataRow(
										dataRow,
										provided,
										snapshot
									)
								) }
							</Draggable>
						)
					) }
					{ placeholder }
				</TableBody>
			) }
		</Droppable>
		<TableFooter
			showFooter={ this.showTableFooter }
			htmlClass={ this.classes.footerClass }
		>
			{ this.tableHeader( footerData, true ) }
		</TableFooter>
	</Table>
</DragDropContext>
```

the `renderDataRow()` performs some data massaging and then passes the props along to:

```jsx
	/**
	 * @function
	 * @param {Array} cells
	 * @param {Object} rowProps
	 * @param {Object} provided
	 * @param {Object} snapshot
	 * @return {Object} rendered <tr> element
	 */
	tableRow = ( cells, rowProps = {}, provided = {}, snapshot = {} ) => {
		const draggableProps = provided.draggableProps || {};
		const dragHandleProps = provided.dragHandleProps || {};
		return (
			<TableRow
				innerRef={ provided.innerRef }
				key={ this.rowNumber }
				rowNumber={ this.rowNumber }
				rowType={ rowProps.rowType || 'body' }
				htmlId={ rowProps.id || this.tableId }
				htmlClass={ rowProps.class || '' }
				classes={ this.classes }
				{ ...draggableProps }
				{ ...dragHandleProps }
				style={ this.getRowStyle(
					snapshot.isDragging,
					draggableProps.style || {}
				) }
			>
				{ cells }
			</TableRow>
		);
	};
```

which also utilizes the following for compiling the styles:

```jsx
	getRowStyle = ( isDragging, style = {} ) => {
		style.border = isDragging ?
			'1px solid var(--ee-color-bright-blue)' :
			'none';
		return style
	};
```

I've confirmed via console logging that my refs and styles are all getting set correctly

**Comment by tn3rb** [comment]
forgot to mention that those `innerRef` props as well as all of the others are getting passed through to the actual HTML elements:

```jsx
class TableRow extends Component {
	render() {
		const {
			children,
			rowNumber,
			htmlId = '',
			htmlClass = '',
			classes = {},
			rowType = 'body',
			innerRef = null,
			...extraProps
		} = this.props;
		const id = htmlId ?
			`${ htmlId }-row-${ rowNumber }` :
			`ee-rspnsv-table-row-${ rowNumber }`;
		const css = classNames(
			htmlClass,
			`ee-rspnsv-table-${ rowType }-row`,
			`ee-row-${ rowNumber }`,
			classes[ `${ rowType }RowClass` ],
		);
		return (
			<tr ref={ innerRef } id={ id } className={ css } { ...extraProps } >
				{ children }
			</tr>
		);
	};
}
```

similar thing is happening with the `TableBody` component

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by tn3rb** [comment]
sorry for the delayed response.
My project had a dependency that was forcing my React version to stay at 16.8.4 and I didn't want to waste any more of anyone's time until that was resolved. Once I was able to upgrade React to a version that was compatible with react-beautiful-dnd, I started receiving error messages that lead me to the problem. 

Turns out I accidentally had some duplicate keys in my table data that were in turn being used for indexes on my Draggables. OOPS!!!

Anyways, everything is working great now.

Thanks so much for a great project.

**Comment by gutzy** [comment]
If this still happens to anybody, my issue was that I was missing the **style** definitions for the dragged element (the one inside Draggable)

**Comment by barhantas** [comment]
If you want to set some quick style for your Draggable component, be careful. The order of Draggable component props is important!
The usage below reproduces the error you get. For make it work uncomment the line `// provided.draggableProps.style`.

```javascript
const getItemStyle = (isDragging, draggableStyle) => ({
    // some basic styles to make the items look a bit nicer
    userSelect: "none",
    padding: 8 * 2,
    margin: `0 0 ${8}px 0`,

    // change background colour if dragging
    background: isDragging ? "lightgreen" : "grey",

    // styles we need to apply on draggables
    ...draggableStyle,
  });


<Draggable draggableId={`${index}`} index={index}>
{(provided, snapshot) => (
  <div
    ref={provided.innerRef}
    {...provided.draggableProps}
    {...provided.dragHandleProps}
    style={getItemStyle(
      snapshot.isDragging
      // provided.draggableProps.style
    )}
  >
    {tag.id}
  </div>
)}
</Draggable>
```

**Comment by urosran** [comment]
@barhantas great answer! 👏  

@others who stumble upon this -- you cannot set just style={something} it will not drag and it will not update! You have to do it as explained above.

**Comment by AmarTrebinjac** [comment]
I had this issue when using the portal approach. Initially when I created the child to append to the portal I created a react functional component rather than a plain jsx-element as shown [here](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/portal/portal-app.jsx) - changing it to a jsx-element solved the issue for me.

**Comment by pragmaeuge** [comment]
In my case, I solved the issue removing the "key" property assigment in the nested div of the draggable item.
