### ISSUE TITLE
Don't scrolling by sub-droppable element

### ISSUE THREAD

**Issue by Yan-Sonerim** [atlassian/react-beautiful-dnd#1411]
Hi! I Have two lavels of droppable block in my DnDContent, (Droppable-Draggable -> Droppable-Draggable). Like in trello (columns and cards). When i move column it scroll my DnDContent, by when i move card it don't want to scroll it. How i'm understand it's through two levels of nesting. How i can do scroll by card in table?   

Details in a [video](https://youtu.be/-TpHVRI1HX4)

**Comment by alexreardon** [comment]
Check your `console`. It looks like you are hitting our nested scroll container limitation

#131

**Comment by Yan-Sonerim** [comment]
How i understand, nested draggable container can scroll only body container?

**Comment by alexreardon** [comment]
Can you please rephrase the question? I am struggling to understand
