### ISSUE TITLE
i can't pushing the drag object in any order to an another list.

### ISSUE THREAD

**Issue by bikoocto** [atlassian/react-beautiful-dnd#1415]
hey, what I want to do, push the drag object to any order of another list by cloning not removing.
what I have done, 
![dnd3](https://user-images.githubusercontent.com/52039944/61437683-4ec28600-a95b-11e9-9ec1-a7d19195f9e0.png)

right container element push to any header that's ok.
but the problem is that how can I drag the left object into right in any order or under any header with cloning.
my goal is
1.=>drag object from left to right and push into any order where the user wants to push(incompleted)
2.=>dag the object from the header and push into another header in aby order(completed)
 1st, one is not completed.
help me to do this,
here is the example what I have done 
https://codesandbox.io/s/hardcore-kare-2pozs

**Comment by alexreardon** [comment]
See #216
