### ISSUE TITLE
Distribution files?

### ISSUE THREAD

**Issue by Frozenlock** [atlassian/react-beautiful-dnd#142]
In the Clojurescript world we often [package JS libraries](https://cljsjs.github.io/) for ease of use.

When doing so, [it's encouraged](https://github.com/cljsjs/packages/wiki/Creating-Packages#2-find-the-librarys-source-code) to use the official distribution files (`dist/`). This helps us upgrade packages and keep them in sync with the JS libraries.

I was ready to package and use this project but couldn't find those files :cry: 

Would it be possible to add this into react-beautiful-dnd?

**Comment by jaredcrowe** [comment]
Hey @Frozenlock thanks for raising this. We investigated this in the past (#81) and it's something we'd be happy to add at some point. Right now we are focused on priorities from our immediate roadmap so we won't be able to address this right away, but we'd be open to PRs from anyone from the community who would like to work on this :)

**Comment by vinifala** [comment]
I'd like to contribute to solve this issue. However, I am not entirely sure how to approach it. At first I thought to remove `./lib` from git ignore. But after brief research, looks like Clojurescript expect a bundle. Would a rollup/webpack bundle be a viable option?

**Comment by alexreardon** [comment]
Great to hear @vinifala!! I am not familiar with the particulars of what is needed for Clojurescript. The ideal would be if we also built a single bundle for distribution. Eg in `/dist`

**Comment by alexreardon** [comment]
Please take a look at the prior work here: #81

**Comment by alexreardon** [comment]
Closed by #186

**Comment by alexreardon** [comment]
@Frozenlock let me know how you go getting it onto https://cljsjs.github.io/ . I can add a link from this repo when it is up. Cheers

**Comment by alexreardon** [comment]
@Frozenlock any update on this?

**Comment by Frozenlock** [comment]
@alexreardon Sorry for the delay, I'll try to do it in the next few days.

**Comment by alexreardon** [comment]
All good!

**Comment by Frozenlock** [comment]
Done!
React-beautiful-dnd is now available as a [cljsjs package](https://cljsjs.github.io/).

Thank you so much for the distribution files!

**Comment by alexreardon** [comment]
So great @Frozenlock !!! I'll add a link to the readme!
