### ISSUE TITLE
Drag table row only from one column

### ISSUE THREAD

**Issue by sT0pe** [atlassian/react-beautiful-dnd#1421]
Hello!

Couldn't find such example. Is it posible to drag whole row in the table but only if we start from the first column? And show drag cursor only on that column?

Thanks!

**Comment by alexreardon** [comment]
We have not found a good way for `column` dragging in a html `<table>` element as yet. There is no element which is considered the `column` of the table which makes it hard to drag. If you could find such an element, then you could simply use `isDragDisabled`
