### ISSUE TITLE
Get the bunch of warnings during dragging item

### ISSUE THREAD

**Issue by dev-acc1** [atlassian/react-beautiful-dnd#1424]
When I'm randomly dragging an item through the other, I get the next bunch of warnings package "@atlaskit/tree". It happens since "^5.0.1" versions, where is "5.0.0" works correctly. Here it is:
![warning_message](https://user-images.githubusercontent.com/46819646/61890382-e3e2f300-aef6-11e9-8465-e483287d5625.png)
I used the example at https://codesandbox.io/s/atlaskittree-6-draganddropwithnesting-fl8ld.

**Comment by alexreardon** [comment]
Please head to the [`@atlaskit/tree` issue tracker](https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236).

We do not track `@atlaskit/tree` issues in the `react-beautiful-dnd` project
