### ISSUE TITLE
Which version changed how placeholders work?

### ISSUE THREAD

**Issue by MitchEff** [atlassian/react-beautiful-dnd#1429]
I've just updated to 11.0.5, and it's caused us a lotta headache. Admittedly it's on us, as we were blocking `translate` (so items could be dragged between lists without re-ordering). 

This was fine when placeholders were at the correct position, but they now appear to be appended to the end, everything is more heavily reliant on `translate`. 

@alexreardon, do you happen to know what version we can roll back to for everything to work again? I've checked the release notes but there's nothing too relevant I can spot.

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0

We cannot guarantee that non-api behaviours work between versions. You are welcome to watch #216 for the true fix
