### ISSUE TITLE
Customizable DropResult

### ISSUE THREAD

**Issue by NotAmaan** [atlassian/react-beautiful-dnd#143]
## Feature request

I have a multi level nested setup, lets call them Rows, Columns and Blocks (hierarchical order).
I can move a Block to a different row, but right now I have a pretty hacky method (JSON.stringify, parse) of getting the destination Column ID and Row ID.
It would have been much easier if I could customize the `result: DropResult` which is a prop of `onDragEnd()`
Adding another prop on <Droppable> could be one way of achieving this. That prop would be added to the result Object.

**Comment by alexreardon** [comment]
Can you please add some more explanation for this one? Also, some example code would be helpful to see the pain point as well as your suggestion.

Cheers!

**Comment by NotAmaan** [comment]
@alexreardon Here you go: https://www.webpackbin.com/bins/-Kx6cpTfejn4FO1iYpWl
There are three draggable types, trying dragging a "BLOCK" (blue button) with the console open. I am able to drag the source and destination column ID and Row ID which I need to update my state.
However, I send them in `droppableId` as stringified JSON which is super hacky.

Let me know if anything is not clear.

**Comment by alexreardon** [comment]
The position we took was that if you provide an 'id' then you should be able to look up that extra data when you drop based on that id. If you do need to provide extra data as you have then you can serialise / deserialise it which you have done. How we achieved nesting in our examples is that we use the `type` in combination with the `id` to know what data set we are looking at

**Comment by NotAmaan** [comment]
@alexreardon The second method you mentioned (looking at the `type` and `id`) doesn't sound like a reasonable approach in my case because it would cause alot of unnecessary loops. For instance, if I had to find and element using its `elementId`, I'd have to loop through every row and every column inside that row). And if I had flattened data store, i.e. `{rows: [], columns: [], elements:[]}` that would slow down the rendering.
The first approach you suggested which I'm using right now works but its really not elegant, especially if I had to add some more stuff (which I probably would have to).

I think this could be something which would probably be a common requirement for anyone trying to build a more complex interface. I could probably submit a pull request for it as soon as I get back to working on the project I'm using beautiful-dnd in if you think its worth adding.

**Comment by alexreardon** [comment]
Conceptually an `id` should be able to be used to look up something in a system. It sounds like the way you have structured your data does not allow a simple id lookup of items. It sounds like you are structuring data in a particular way to allow for fast rendering, but this structure makes it hard to look things up easily by id. This is common problem which goes outside of just this library. The simplest path would be to leave you data structured as is and do the nested loop to look up. I would be very surprised if this would actually have any significant performance problems.

You could go further by creating a fast lookup map for your normalised data {id: item} (as well as other techniques)

I touched on this issue at React Sydney: https://www.youtube.com/watch?v=jm81fmVr3co .

I hope you find that helpful!
