### ISSUE TITLE
Using the same container both for `Draggable` and `Droppable`.

### ISSUE THREAD

**Issue by p-himik** [atlassian/react-beautiful-dnd#1445]
### Expected behavior
It's possible to provide a set of properties to a container like
```
<tbody
  ref={(r) => {draggableProvided.innerRef(r); droppableProvided.innerRef(r);}}
  {...draggableProvided.draggableProps}
  {...droppableProvided.droppableProps}
[...]
</tbody>
```

### Actual behavior
When attempting to drag the `tbody`, the pages crashes with multiple error messages with "Cannot fire onDragMove when onDragStart has not been called" being the first one.

To be honest, I think this is probably something that has never been considered and for a good reason. So feel free to close the issue right away.

The only reason I decided to try it is that I need to be able to group ordered rows in a table and drag rows into and out of the groups, as well as be able to drag the groups themselves. And because it's impossible to insert anything between `table` and `tbody` and between `tbody` and `tr`, I wanted to try this out.
Right now I think that my best bet is to go with the approach of @atlaskit/tree and track the groups manually. Although it remains to be seen if I can have `Draggable` within a `Draggable`.

**Comment by alexreardon** [comment]
It sounds like you have a use case. But as you mentioned, we have not explored having them as the same element...

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by danieldelcore** [comment]
Closing this one due to inactivity. Please feel free to reopen if you need.
