### ISSUE TITLE
Please remove the chinese translation, it maybe just translated by google

### ISSUE THREAD

**Issue by jinboker** [atlassian/react-beautiful-dnd#1450]

**Comment by jinboker** [comment]
https://github.com/chinanf-boy/react-beautiful-dnd-zh/issues/3

I could not confirm this translator completed with google, but in fact, it is more difficult to understand than English, i do not think it have enough quality to hang on the home page.

**Comment by weiyuxuan** [comment]
As a Chinese developer, I dare to say the Chinese documents are translated by machine with a little bit polish, it just couldn't be understood.

**Comment by duziten** [comment]
absolute agree!!!

**Comment by alexreardon** [comment]
Oh no! Happy to remove it. PR anyone?
