### ISSUE TITLE
Limit dragging in x-axis or y-axis not working

### ISSUE THREAD

**Issue by suryarsp** [atlassian/react-beautiful-dnd#1455]
I am using the code as described in the above bug #985 
### Expected behavior
When I drag and drop an item out of the container it drags the element but it's not returning to its original position because I have disabled the drag if it was happening inside the container.

` if (!destination || source.droppableId === destination.droppableId) {
         return;
}`
The dragged element is not re-positioning at its own place rather it stays out of the content where the element is left

### Actual behavior
The element crosses the container boundary and it is placed anywhere the element is dropped.

### Steps to reproduce
https://codesandbox.io/s/vertical-list-with-multiple-drop-targets-phbmr?fontsize=14
### Suggested solution?
The dragged element should return back to its original position with defined transform ( the dragging axis should be y locked )

### What version of `React` are you using?

"react-dom": "16.7.0",
 "react": "16.7.0",

### What version of `react-beautiful-dnd` are you running?

Version used: **^11.0.4**

### What browser are you using?

I am using it on IE11, Chrome as well as Safari

### Demo
https://codesandbox.io/s/vertical-list-with-multiple-drop-targets-phbmr?fontsize=14

**Comment by Frimko** [comment]
correct? https://codesandbox.io/s/vertical-list-with-multiple-drop-targets-v2q1f

**Comment by suryarsp** [comment]
Yeah that's the solution I was expecting for @Frimko

**Comment by oauo** [comment]
You need to not allow moving tiles between collections though. If you use keyboard you can move items between the collections.
