### ISSUE TITLE
Ability to customize long press timeout for more responsive dragging

### ISSUE THREAD

**Issue by ItsWendell** [atlassian/react-beautiful-dnd#1464]
### Description
 
During a test we've had with about 20 test subjects on Safari iOS IPads, we noticed that the `120ms` long press delay in the touch driver feels a bit too long to feel intuitive to use. I've forked react-beautiful-dnd to add support for a custom property in `<Draggable />` component called 'longPressTimeout' that defaults to the default assigned `120ms`.

Since we do not need to support to keep long presses enabled and since we don't have any scrolling on this page, we brought the `120ms` down to only just a few milliseconds which drastically made our app and use-case feel smoother.

I would love to discuss the possibility of making `timeForLongPress` customizeable using properties in either `Draggable` or the `DragDropContext`, would love to hear your opinion on this!

**Comment by spiritsack** [comment]
Seems to have been brought up earlier https://github.com/atlassian/react-beautiful-dnd/issues/415

**Comment by alexreardon** [comment]
Tracking in #415
