### ISSUE TITLE
onDragEnd firing twice when using useReducer

### ISSUE THREAD

**Issue by atomicpages** [atlassian/react-beautiful-dnd#1465]
### Expected behavior
`useReducer` dispatch should not fire twice

### Actual behavior
`useReducer` dispatch is firing twice which is causing side effects when moving items in the same container or between two `Draggable` containers.

### Steps to reproduce
https://codesandbox.io/s/practical-fermat-x5uhn

### Suggested solution?
No idea 🤷‍♂️

### What version of `React` are you using?
16.9.0

### What version of `react-beautiful-dnd` are you running?
11.0.5

### What browser are you using?
Chrome 76

### Demo
See repro steps

**Comment by alexreardon** [comment]
I had a look, it is not actually `onDragEnd` that is firing twice. Rather, in your example, the action is being reduced twice

**Comment by atomicpages** [comment]
Correct. But the _root_ cause is `onDragEnd` firing twice. It doesn't with `useState`. The two examples are functionally equivalent.

**Comment by atomicpages** [comment]
Example updated. I had to move the reducer to a separate function to prevent the duplicate call 😢

**Comment by alexreardon** [comment]
I did a console.log in the onDragEnd and found it was only being called once
