### ISSUE TITLE
React beautiful dnd in material-ui Swipeable drawer doesn't work as expected on touch

### ISSUE THREAD

**Issue by nischayv** [atlassian/react-beautiful-dnd#1468]
I am using a react-beautiful-dnd list in a material-ui swipeable drawer.

### Expected behavior
Upon dragging an element in the list using touch, the element should move without affecting the parent (Swipeable drawer).

### Actual behavior
On dragging an element from the list using touch, the material-ui swipeable drawer also gets dragged.

### Steps to reproduce
Use the codesandbox link and simply drag an element in the list using touch (use chrome devtools to emulate mobile if needed)

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/embed/react-beautiful-dnd-swipeable-drawer-y0dqw

**Comment by Gittew** [comment]
styles theme "paper" in backbone.js affect directly the list component.  paper.height : calc 100%-12px is fine. Should it be specified as a relative position？

**Comment by oliviertassinari** [comment]
We can reproduce the problem without Material-UI: https://codesandbox.io/s/react-beautiful-dnd-swipeable-drawer-x5688.

**Comment by alexreardon** [comment]
Can you please check in 12.0? our approach to touch has changed

**Comment by oliviertassinari** [comment]
I couldn't see a difference, same none responsive behavior. Maybe it's related to the CSS styles?

**Comment by alexreardon** [comment]
It could have something to do with how material ui is handling touch events. Here is what we are doing: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/how-we-use-dom-events.md

**Comment by oliviertassinari** [comment]
@alexreardon https://codesandbox.io/s/react-beautiful-dnd-swipeable-drawer-x5688. doesn't include Material-UI. Can you reproduce with it?

**Comment by alexreardon** [comment]
Ah, sorry - this is not using material ui. I'll take a look soon

**Comment by alexreardon** [comment]
In your event handler - only toggle if `event.defaultPrevented` is false. This is the signal we use to indicate that an event has been consumed by rbd: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/how-we-use-dom-events.md

**Comment by alexreardon** [comment]
Add that check and see how you go

**Comment by oliviertassinari** [comment]
> only toggle if event.defaultPrevented is false. 

@alexreardon Yes! I'm happy you mention this approach. We have recently fixed a related issue in Material-UI, this seemed to be our best option, and here we might have a confirmation that it was indeed not a too bad approach:
https://github.com/mui-org/material-ui/blob/7f09ea46f380eed609ca9d348022f77a67e787bb/packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js#L403-L408

**Comment by alexreardon** [comment]
Perfect! In order to play well with others we try not to stop any events - but just use event.preventDefault() to signal the event has been used. This is detailed in our how we use dom events guide :)
