### ISSUE TITLE
Space being created to drop element when isDropDisabled is true

### ISSUE THREAD

**Issue by baronnoraz** [atlassian/react-beautiful-dnd#1471]
Goal is to create a static list that will allow users to drag copies of elements "out" of the static list to other lists.  The desired behavior can be seen in the `ITEMS` list here [ https://codesandbox.io/s/q3717y1jq4](https://codesandbox.io/s/q3717y1jq4).

### Expected behavior

When setting `isDropDisabled={true}` on a `Droppable`, I would expect that droppable to remain visually unchanged when an element is being dragged over the droppable.

### Actual behavior
If `isDropDisabled={true}` is set on a list and you start dragging an element of that list, the list temporarily allocates space for the element to be dropped resulting in the list to expand but then contract immediately. It's like the list starts to allow dropping behavior and then realizes it shouldn't and stops.

### Steps to reproduce
See [https://codesandbox.io/s/react-codesandbox-j6q1e](https://codesandbox.io/s/react-codesandbox-j6q1e?fontsize=14)

Start dragging any of the topic elements (except the last one).  You'll see the space allocated then removed.

### Suggested solution?

Since I don't see the space allocated in the referenced Code Sandbox link I'm clearly doing something wrong.  My first inclination is to think that something is wrong with my usage of `innerRef` as I'm not using Styled Components, but what that might be I don't know.  That's 100% a guess though.

### What version of `React` are you using?
^16.9.0

### What version of `react-beautiful-dnd` are you running?
11.0.5

### What browser are you using?
Chrome 76+

### Demo

[https://codesandbox.io/s/react-codesandbox-j6q1e](https://codesandbox.io/s/react-codesandbox-j6q1e?fontsize=14)

**Comment by alexreardon** [comment]
> Goal is to create a static list that will allow users to drag copies of elements "out" of the static list to other lists

#216 

I can confirm that isDropDisabled is working as expected for lists

**Comment by alexreardon** [comment]
You are inserting a new element into the list during a drag which is not supported.

See #216 for tracking the feature you are after

For reparenting a draggable, see You are inserting a new element into the list during a drag which is not supported.

See

**Comment by baronnoraz** [comment]
I wish that I were smart enough to follow along.  I don't see where I'm inserting a new element into the list. I don't want to reparent the item.

My goal was to simply not have the list flicker when I start dragging an element. I don't want to add it to the list (that it's already in).  If I grab "Topic3" and start dragging it, "Topic4" will jump down in the list as though the list is trying to allocate space for "Topic3" to be dropped.

It happens when I start dragging any of the topics.  Every topic below will briefly jump.  

If you can point out where the erroneous element insertion is happening, I'll do my best to figure out how to fix it.  I just don't see what you're saying.

I do appreciate the help and the fact that you looked.  I've read #216 about a million times and don't see what I'm doing wrong.

**Comment by lennerd** [comment]
This library does net yet support dragging a clone of the element you are dragging. This is why it's flickering.
