### ISSUE TITLE
"An error has occurred while a drag is occurring." when there's no drag occurring.

### ISSUE THREAD

**Issue by MitchEff** [atlassian/react-beautiful-dnd#1472]
Ever since updating to the lasted version of react-beautiful-dnd, every single error reported anywhere in the app is always preceded by the "An error has occurred while a drag is occurring." message.

It's not a huge deal as I can still read the error, but there's certainly no drag occurring. I'm not going to spend all day setting up a repro for something this minor, I was just wondering if anyone else has encountered this?

**Comment by mattkrick** [comment]
can confirm. 
`window.addEventListener('error', this.onFatalError);` fires on mount.

`this.onFatalError` doesn't actually check to see if a drag is in progress. it should.

**Comment by alexreardon** [comment]
Yes it should! We'll track this here: #1108
