### ISSUE TITLE
Problem with conditional Portal pattern, upgrading to v11 > causes "provided.innerRef has not been provided with a HTMLElement"

### ISSUE THREAD

**Issue by Anwardo** [atlassian/react-beautiful-dnd#1473]
### Expected behavior
Normal dragging and dropping in the list. Using this pattern in v10 doesn't cause any issues. 

### Actual behavior
Getting this error: Uncaught Error: Invariant failed: provided.innerRef has not been provided with a HTMLElement.

### Steps to reproduce
Render the draggable ref inside a conditional portal.

### Suggested solution?
-

### What version of `React` are you using?
16.8.5

### What version of `react-beautiful-dnd` are you running?
11.0.5

### What browser are you using?
Chrome

### Demo
See this codesandbox with v11: https://codesandbox.io/s/material-ui-list-with-react-beautiful-dnd-7hgfg

Just changing the version to 10 makes it work as expected again.

**Comment by alexreardon** [comment]
Strange! It looks like it is working with `12.0.0-alpha.7` so I am not sure if it is worth investigating as `11.x` is soon to be superseded

**Comment by Anwardo** [comment]
Ah yeah I didn't check with the alpha versions but seems to work fine again in v12. I agree investigating is not worth it with it working in v12. I'll just hold off on updating until v12 rolls around.
