### ISSUE TITLE
use react-beautiful-dnd with plain javascript

### ISSUE THREAD

**Issue by domnulnopcea** [atlassian/react-beautiful-dnd#1477]
hello,

is there a way to use this library in an existing application that is not built with reactjs but jquery?

how can I create components like DragDropContext, Droppable, Draggable and so on using a plain javascript approach? Is this doable?

if yes, it would be great if you could offer some examples in the documentation

there is a load of "old" web applications not built on react (but jquery for example) that could make use of this great dnd library.

thanks

**Comment by alexreardon** [comment]
See #1217

Thanks for your compliment! It would be great to take what we have and make it useable outside of a react ecosystem. There is still so much we want to do and improve. For now supporting technologies other than react is not a priority for us and so we won't be able to get to this for the foreseeable future
