### ISSUE TITLE
Removing testcafe packages

### ISSUE THREAD

**Issue by nutboltu** [atlassian/react-beautiful-dnd#1480]
After reviewing this PR https://github.com/atlassian/react-beautiful-dnd/pull/1122, it seems like this library has already migrated from **testcafe** to **cypress**.

I found this package (**testcafe-reporter-xunit**) https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L132 in the package.json which should be removed from this library.

There are also a few places where I found dead codes for testcafe. We can remove those as well.

**Comment by alexreardon** [comment]
Cheers! PR welcome too (if we don't get to it first :D)

**Comment by nutboltu** [comment]
@alexreardon Just curious, what's the benefits of migrating from testcafe to cypress as testcafe supports cross-browser testing which is still missing in cypress.
