### ISSUE TITLE
Elements must only use allowed ARIA attributes (.gripper.root-211[data-icon-name="GripperBarVertical"])

### ISSUE THREAD

**Issue by Vividha-Khandelwal** [atlassian/react-beautiful-dnd#1488]
### Actual behavior

Target application title: Microsoft Partner Connect - Order Management

Element path: .ms-Grid[data-react-beautiful-dnd-draggable="\30 "][dir="ltr"]:nth-child(1) > .ms-Grid-row > .gripper.root-211[data-icon-name="GripperBarVertical"]

![22107961_A11y_UniversalPriceListunderMPC_Customize Columns_K4W  Elements must only use allowed ARIA attributes ( gripper root-211 data-icon-name=G](https://user-images.githubusercontent.com/48586069/64701720-f1fccb00-d4c6-11e9-86c0-1dcec63461f5.png)

Snippet: 
1. <i data-icon-name="GripperBarVertical" tabindex="0" data-react-beautiful-dnd-drag-handle="0" aria-roledescription="Draggable item. Press space bar to lift" draggable="false" class="gripper root-211" aria-label="Change the order of Pricelist Name. Press Up or Down after selecting to change order.">
2. <i tabindex="0" class="gripper root-211" draggable="false" aria-roledescription="Draggable item. Press space bar to lift" aria-label="Change the order of Part Number. Press Up or Down after selecting to change order." data-icon-name="GripperBarVertical" data-react-beautiful-dnd-drag-handle="0">
3. <i tabindex="0" class="gripper root-211" draggable="false" aria-roledescription="Draggable item. Press space bar to lift" aria-label="Change the order of Item Name. Press Up or Down after selecting to change order." data-icon-name="GripperBarVertical" data-react-beautiful-dnd-drag-handle="0">

### Steps to reproduce
====

This accessibility issue was found using Accessibility Insights for Web 2.4.1 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

### Suggested solution?

 
ARIA attribute is not widely supported in screen readers and assistive technologies:  aria-roledescription

### What browser are you using?
Chrome version 75.0.3770.80

**Comment by alexreardon** [comment]
Good news - this is being fixed in `12.0`. Try `12.0.0-beta.1`
