### ISSUE TITLE
Why ref works with material-ui components?

### ISSUE THREAD

**Issue by BirukovAleksandr48** [atlassian/react-beautiful-dnd#1489]
I tried to create my draggable list and get stucked. Then I found [this warning](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md#a-common-error-)
and realized that this is my case. So, I suply `provided` object into my component and assign `provided.innerRef` to my root container as explained in example. All works! But then I realized that my root element is MaterialUI/Grid component (also a component)! and then I wondered why MaterialUI/Grid can accept `ref={provided.innerRef}`, but my component not.

**Comment by TrySound** [comment]
https://reactjs.org/docs/react-api.html#reactforwardref

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md
