### ISSUE TITLE
Can't use spacebar in inputs inside a Draggable

### ISSUE THREAD

**Issue by hungle88** [atlassian/react-beautiful-dnd#149]
### Expected behaviour
Should be able to use spacebar as other characters

### Actual behaviour
Looks like spacebar is being reserved as a shortcut.

### Steps to reproduce
* Create an input inside a Draggle
* Add patch
```
<input onMouseDown={e => e.stopPropagation()} />
```
* Start typing, you'll notice the spacebar won't register

### Browser version
`electron` v1.7.9
`react` v16.0.0
`react-beautiful-dnd` v2.5.3

### Demo

![Bug](https://thumbs.gfycat.com/TanFavoriteKingbird-size_restricted.gif)
[HD Version](https://gfycat.com/gifs/detail/TanFavoriteKingbird)

### _withDraggable HOC

```
// Libs
import React from 'react';
import {Draggable} from 'react-beautiful-dnd';

const _withDraggable = ComposedComponent => props => (
  <Draggable draggableId={props.item.id}>
    {(provided, snapshot) => {
      const draggableStyle = {
        ...provided.draggableStyle,
        margin: '0 0 14px 0',
      };
      return (
        <div>
          <div
            ref={provided.innerRef}
            style={draggableStyle}
            {...provided.dragHandleProps}>
            <ComposedComponent {...props} />
          </div>
          {provided.placeholder}
        </div>
      );
    }}
  </Draggable>
);

export default _withDraggable;
```

**Comment by bradleyayers** [comment]
This is similar to https://github.com/atlassian/react-beautiful-dnd/issues/61#issuecomment-325068145, I just pass a patched `onKeyDown` e.g.

```ts
onKeyDown: e => {
  if (dragHandleProps && e.target.nodeName !== "INPUT") {
    dragHandleProps.onKeyDown(e);
  }
}
```

**Comment by hungle88** [comment]
Thanks @bradleyayers. I patched the HOC as you suggested and it's working now. 
Here's the reference for those who might run into this.

```
// Libs
import React from 'react';
import {Draggable} from 'react-beautiful-dnd';

const _withDraggable = ComposedComponent => props => (
  <Draggable draggableId={props.item.id}>
    {(provided, snapshot) => {
      // Patch
      const onKeyDown = e => {
        if (provided.dragHandleProps && e.target.nodeName !== 'INPUT') {
          provided.dragHandleProps.onKeyDown(e);
        }
      };
      const patched = {
        ...provided.dragHandleProps,
        onKeyDown,
      };
      // Draggable Style
      const draggableStyle = {
        ...provided.draggableStyle,
        margin: '0 0 14px 0',
      };
      return (
        <div>
          <div
            ref={provided.innerRef}
            style={draggableStyle}
            {...provided.dragHandleProps}
            {...patched}>
            <ComposedComponent {...props} />
          </div>
          {provided.placeholder}
        </div>
      );
    }}
  </Draggable>
);

export default _withDraggable;
```

**Comment by bradleyayers** [comment]
I think I'd like this behaviour built into the library. It seems to be a common gotcha, and I can't think of any counter examples where you actually want the user wants clicks on `input`/`select`/`textarea`/`[contenteditable]`/`button` to initiate drag behaviour. In those scenarios I'd recommend just overlaying the input with a non-interactive element that can act as the target for the event.

**Comment by alexreardon** [comment]
I have been thinking the same thing @bradleyayers. For now we will just call it out - but it could be handled in a nicer way. Being un opinionated has advantages though as it lets people craft the interactions how they like

**Comment by alexreardon** [comment]
We call this out in the docs: https://github.com/atlassian/react-beautiful-dnd#interactive-child-elements-within-a-draggable

**Comment by hungle88** [comment]
@alexreardon Should we add an example for `onKeyDown` event in this section as well? Because it can be not obvious for new users at first. I can make an PR on this.

**Comment by alexreardon** [comment]
That sounds great

**Comment by hungle88** [comment]
Cool, just [Added patching inputs inside Draggable example](https://github.com/atlassian/react-beautiful-dnd/pull/152) PR.
