### ISSUE TITLE
How to show  draggable items in the mix of rows and columns inside the container?

### ISSUE THREAD

**Issue by Aravindraj92** [atlassian/react-beautiful-dnd#1494]
Hi,

I want to show the draggable items like a grid.here each and every image is a draggable item, when I leave the dragged item, it relocates to a different position.
![download](https://user-images.githubusercontent.com/27267876/64907849-996f3d00-d715-11e9-8aa2-906bd2370718.png)

**Comment by tamar-meital** [comment]
I encountered the exact same issue!! 
The end index is wrong when using multi-line/wrapped elements.
@Aravindraj92 Any idea how to solve this? Or a workaround?

**Comment by Aravindraj92** [comment]
> I encountered the exact same issue!!
> The end index is wrong when using multi-line/wrapped elements.
> @Aravindraj92 Any idea how to solve this? Or a workaround?

I have planned to wait for a couple of days to get a possible solution. if you get to know something let me know.

**Comment by tamar-meital** [comment]
@alexreardon @jinboker Any updates regarding this issue?

**Comment by jasp402** [comment]
Any updates?

**Comment by alexreardon** [comment]
Duplicate: https://github.com/atlassian/react-beautiful-dnd/issues/316
