### ISSUE TITLE
Touch not able to drag and drop in mobile devices

### ISSUE THREAD

**Issue by rawris** [atlassian/react-beautiful-dnd#1498]
**Expected behavior**
Normal drag and drop on mobile devices

**Actual behavior**
Not able to drag and drop on mobile, Console.log says the drag was canceled
![ezgif com-crop](https://user-images.githubusercontent.com/27147880/64934203-c8e18f00-d866-11e9-969b-13614537ad78.gif)

**Steps to reproduce it**
just try any simple list on mobile and add a list of custom HTML elements inside a list, it will drag and drop if you drag it from the part where the row is empty but if try to drag it from the custom elements, it will fail

React: 16.9.0
react-beautiful-dnd: ^11.0.5

Chrome

**Comment by alexreardon** [comment]
Can you please try our beta? `12.0.0-beta.1`?

**Comment by rawris** [comment]
@alexreardon Hi, Thanks for replying and updating the library to the latest version did work. When can we expect the stable version for this build? and is it safe to use this beta version for production build for now?

**Comment by alexreardon** [comment]
`beta` = all tests are passing but docs are not updated. It is safe to use, but some API's might not be as currently documented

**Comment by rawris** [comment]
Okay, Thank you so much @alexreardon. I'm closing this issue now.

**Comment by alexreardon** [comment]
#1487
