### ISSUE TITLE
needs to be updated ?

### ISSUE THREAD

**Issue by bikoocto** [atlassian/react-beautiful-dnd#1500]
Hey,
 I just want to say that the react beautiful dnd is an awesome npm .i am working on it since 4 months .it is really nice, but when I install ReactFlip npm or any other npm for flip then the object reflection is not on the pointer it seems like this.

![dndprob](https://user-images.githubusercontent.com/52039944/65020354-aaed5a80-d94a-11e9-9584-a2bea0471360.png)

*Mouse pointer is in one place and the dragged object reflection is in another place.
*my goal is, there is a card which can clip both sides and it contains the draggable objects in both sides and there is a  dropable area in the right side where cards both side object can be dropped.

*problem- for flip I tried many npm but the problem got common, so I thought you guys need to be aware of this issue, otherwise, you guys waste your time in this to make it possible.
can anybody help me out?

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
