### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by pixelass** [atlassian/react-beautiful-dnd#1501]
### Expected behavior

RBD should render correctly.

### Actual behavior

When adding RBD I encounter the following error:

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

The error only occurs when using RBD. I removed and reinstalled all `node_modules` to ensure there is no version conflict 

### Steps to reproduce

I made a sandbox but could not reproduce the issue.

I'm not sure why this happens and why I cannot reproduce the issue. 
I tried using this very simple section. **(using an empty array to reduce error sources)**

```jsx

<DragDropContext onDragEnd={() => {/* just here for validity */}>
    <Droppable droppableId="thumbnails">
        {(provided, snapshot) => (
            <div {...provided.droppableProps} ref={provided.innerRef}>
                {[].map((slide, index) => (
                    <Draggable
                        key={slide.id}
                        draggableId={slide.id}
                        index={index}>
                        {(provided, snapshot) => (
                            <div
                                ref={provided.innerRef}
                                {...provided.draggableProps}
                                {...provided.dragHandleProps}
                                style={provided.draggableProps.style}>
                                {index}: {slide.id}
                            </div>
                        )}
                    </Draggable>
                ))}
                {provided.placeholder}
            </div>
        )}
    </Droppable>
</DragDropContext>
```

### Suggested solution?

Any help (in form of solutions or hints on me providing better info) is appreciated.

### What version of `React` are you using?

`16.9.0`

### What version of `react-beautiful-dnd` are you running?

`11.0.5`

### What browser are you using?

`chromium via electron 6.0.9`

**Comment by pixelass** [comment]
The error does not occur on `v10.1.1`

**Comment by pixelass** [comment]
Looks like I was able to resolve the issue via https://github.com/facebook/react/issues/13991#issuecomment-521903787

**Comment by pixelass** [comment]
Closing since it seems to be related to electron-webpack

**Comment by dkeesey** [comment]
@pixelass - is that React Beautiful DnD v.10.1.1?

**Comment by pixelass** [comment]
@dkeesey I'm not sure what the question is.

I had issues with RBDND v11 which did not occur in RBDND v10. 
My issue was related to "electron-webpack" which is a package that adds webpack to electron. 

* What is your setup?
* What is the actual issue.
