### ISSUE TITLE
 Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by wakeupSu** [atlassian/react-beautiful-dnd#1507]
version:
  react-beautiful-dnd: 11.0.5
there is the error:
「/node_modules/react-beautiful-dnd/node_modules/react-redux/es/components/connectAdvanced.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/node_modules/react-beautiful-dnd/node_modules/react-redux/es/components'」
but @babel/runtime/helpers/esm/extends is exist in react-beautiful-dnd/node_modules

**Comment by TrySound** [comment]
Something wrong with your build tool. Show us your config.

**Comment by wakeupSu** [comment]
@TrySound

**Comment by wakeupSu** [comment]
@TrySound thanks, there is my webpackrc.js
{
  "entry": "src/index.js",
  "extraBabelPlugins": [
    "transform-decorators-legacy",
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  },
  "ignoreMomentLocale": true,
  "theme": "./src/theme.js",
  "html": {
    "template": "./src/index.ejs"
  },
  "disableDynamicImport": true,
  "hash": true,
  "alias": {
    '@': path.resolve(__dirname, 'src/'),
  },
  "define": {
    "NODE_ENV": "'production'"
  },
}

**Comment by TrySound** [comment]
What is this tool exactly? A wrapper around webpack? If packages in node_modules are on their place you should forward this issue to your build tool.

**Comment by wakeupSu** [comment]
@TrySound ok, thank you.

**Comment by alexreardon** [comment]
Thanks @TrySound
