### ISSUE TITLE
IconButton was not dragged

### ISSUE THREAD

**Issue by project-owner** [atlassian/react-beautiful-dnd#1509]
### Expected behavior

The whole ListItem content should be dragged

### Actual behavior

The example shows that IconButton (pen) was not dragged:
https://codesandbox.io/s/4qp6vjp319?from-embed

### Steps to reproduce

https://codesandbox.io/s/4qp6vjp319?from-embed

### What version of `React` are you using?

16.8.6

### What version of `react-beautiful-dnd` are you running?

11.0.5

### What browser are you using?

Firefox 69.0.1

### Demo

https://codesandbox.io/s/4qp6vjp319?from-embed

**Comment by alexreardon** [comment]
<img width="516" alt="Screen Shot 2019-11-05 at 1 52 48 pm" src="https://user-images.githubusercontent.com/2182637/68174878-91c06c00-ffd3-11e9-84bb-52aaf229baed.png">

The answer here is because the icons are not a child of the draggable

https://codesandbox.io/s/material-ui-list-with-react-beautiful-dnd-50qjh

So when we move the draggable and apply styles to the draggable element, they are not impacting the buttons

**Comment by project-owner** [comment]
I'm not sure that I follow your answer. The following screenshot was made from your link and it shows that the icon is the child of the Draggable:

![drag](https://user-images.githubusercontent.com/16547956/68177286-b1588580-ff3c-11e9-85aa-3411fc832b14.jpg)

Please clarify.

**Comment by alexreardon** [comment]
1. Open up the DOM inspector
2. You will see that the edit button is not a child of the draggable DOM node - it is currently a sibling. 

<img width="475" alt="Screen Shot 2019-11-05 at 3 52 26 pm" src="https://user-images.githubusercontent.com/2182637/68179532-5e3a0d80-ffe4-11e9-91a8-1a841d02fd8e.png">

**Comment by project-owner** [comment]
Thank you. Do you mean this the issue in the Draggable component implementation?

**Comment by alexreardon** [comment]
It looks like even though you are expressing a parent child relationship in react - material ui is rendering the two parts as siblings. You will need to explore whether the material ui api will allow you to add props to the containing `li` element

**Comment by project-owner** [comment]
Thank you for explanation. I'm just a consumer of this library. So, I'll let its developers to explore that ;)

**Comment by danieldelcore** [comment]
Seems like this issue has been resolved. Please reopen if this is still an issue
