### ISSUE TITLE
Unable to find drag handle when id is integer

### ISSUE THREAD

**Issue by SiebeVE** [atlassian/react-beautiful-dnd#1512]
### Expected behavior
When using a `draggableId` that is an *int*, the library is unable to find the drag handle.
This is due to the strict check on: https://github.com/atlassian/react-beautiful-dnd/blob/dev/src/view/get-elements/find-draggable.js#L17.
We get this id by fetching it from the dom, but comparing it to the id received from react (that can be an int or a string)

### Actual behavior
Renders with errors and doesn't enable drag 'n drop.
Given error:
> A fatal error has occurred. Any existing drag will be cancelled.> Invariant failed:
> Draggable[id: 309]: Unable to find drag handle

### Steps to reproduce
Create a component and make sure you give the draggable id an integer value

### Suggested solution?
Don't use a strict check or cast to integer when possible?

### What version of `React` are you using?
16.9.0

### What version of `react-beautiful-dnd` are you running?
12.0.0-beta-1

### What browser are you using?
Latest chrome

### Demo
https://codesandbox.io/embed/vertical-list-vs189

**Comment by alexreardon** [comment]
This is a tricky one as we do state that `draggableId` needs to be a string. It is a bit of a rabbit hole to start treating it as maybe an `int`

**Comment by alexreardon** [comment]
Perhaps we should throw if `draggableId` is not a string

**Comment by alexreardon** [comment]
`12.0` would be a good opportunity to add this check

**Comment by SiebeVE** [comment]
That sounds like a good idea!

I will try to write a PR for this check

**Comment by alexreardon** [comment]
#950 #921

**Comment by alexreardon** [comment]
Don't worry about creating a PR @SiebeVE. I'll make the change as I want to test out a few things with it

**Comment by alexreardon** [comment]
This has been changed in `12.0.0-beta.3`. An error will now be thrown if `draggableId` or `droppableId` is not a string

**Comment by alexreardon** [comment]
#1317

**Comment by Alan-Fisher** [comment]
> draggableId needs to be a string

Probably should be in the docs...

**Comment by omeremreelmali** [comment]
> This is a tricky one as we do state that `draggableId` needs to be a string. It is a bit of a rabbit hole to start treating it as maybe an `int`

This was the solution for me. I converted draggableId as string.
