### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createContext' of undefined     at eval (Context.js:6)     at Module../node_modules/react-redux/es/components/Context.js 

### ISSUE THREAD

**Issue by alexvibealex** [atlassian/react-beautiful-dnd#1520]
Hi it is not at all mentioned that react-beautiful-dnd uses react-redux .
We are getting error including react-beautiful-dnd with react-redux which is required.

Uncaught TypeError: Cannot read property 'createContext' of undefined     at eval (Context.js:6)     at Module../node_modules/react-redux/es/components/Context.js 

we want to import the react, react-dom, react-redux  externally .

This is out webpack.js

var webpack = require('webpack');
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'js/bundle.js'
  },
  externals: {
    react: {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react',
      umd: 'react',
    },
    'react-dom': {
      root: 'ReactDOM',
      commonjs2: 'react-dom',
      commonjs: 'react-dom',
      amd: 'react-dom',
      umd: 'react-dom',
    },
    'react-redux':'react-redux'
  },
  module: {
    rules: [
    {
            exclude: /node_modules/,
            test: /\.js$/,
            loader: 'babel-loader'
        }],

  },
  plugins: []
};

Please check this screenshot : http://prntscr.com/pcwbjd

Is it any way to include react-beautiful-dnd without importing react-redux , react etc ?

**Comment by alexreardon** [comment]
We cannot dive into assist with custom build configurations. Any suggestions @TrySound? Don't feel like you need to dive into it though
