### ISSUE TITLE
TCP/HTTP?

### ISSUE THREAD

**Issue by IDONTSUDO** [atlassian/react-beautiful-dnd#1527]
When using HTTP. I am losing reactivity. Although I am waiting for the exact moment when the data ends up in state?

What could be the problem?
------------------------------
P.S. I can remove  demo GIF and send the source code

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
