### ISSUE TITLE
Mouse click event following onDragEnd has e.defaultPrevented set to true in 12.0.0-beta.3, when using portals

### ISSUE THREAD

**Issue by johnbell84** [atlassian/react-beautiful-dnd#1528]
When using portals with react-beautiful-dnd, the event following a successful onDragEnd has its defaultPrevented property set to true when used with version 12.0.0-beta.3.  This can cause problems with (for example) react-router-dom Link elements, which only act on click events when defaultPrevented is set to false.

A reproduction case is available [here](https://codesandbox.io/embed/react-beautiful-dnd-83fpk), adapted from the [portal example](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/portal/portal-app.jsx) - please note that for some reason this doesn't occur unless you break the example out of the iframe (the button with the overlapping squares to the right of the address bar does this).  There are no console warnings to suggest what might have gone wrong.

### Expected behavior

MouseEvent clicks outside of the DragDropContext (following onDragEnd) should not have had preventDefault() called on them.

### Actual behavior

The first MouseEvent clicks outside of the DragDropContext (following onDragEnd) appears to have had preventDefault() called on them.

### Steps to reproduce

Please see reproduction case: https://codesandbox.io/embed/react-beautiful-dnd-83fpk

1. Break example out of iframe
2. Drag & drop an element
3. Click link on first line (nothing happens because defaultPrevented is true)
4. Click link on first line again (hidden text displays)

### Suggested solution?

For my own project I've been detecting this case & re-dispatching synthetic clones of any such events (without preventDefault having been called), but ofc that's a pretty unpleasant hack.  TBH I've not been using this library long & suspect the cause is probably sufficiently involved that I'm unlikely to be able to suggest a decent solution.

### What version of `React` are you using?

16.8.0

### What version of `react-beautiful-dnd` are you running?

12.0.0-beta.3

### What browser are you using?

Chrome Version 77.0.3865.90 (Official Build) (64-bit) on macOS Mojave 10.14.6 (18G87)
(also occurs in Firefox and Safari)

### Demo

https://codesandbox.io/embed/react-beautiful-dnd-83fpk

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/how-we-use-dom-events.md

After a successful drag we intentionally call event.preventDefault on the next click. However, this should only be done for the current drag inputs (ie the only click that is blocked is the one that would occur after a mouseup).

I am guessing that you are reporting that the next click unrelated to a drag is being blocked?

**Comment by alexreardon** [comment]
I can see that it is an issue with portals. It looks like the click event from the drag doesn't occur because the element is reparented.

I will ensure that the next unrelated click is not prevented when using portals

**Comment by alexreardon** [comment]
This is now fixed in `12.0.0-beta.5`

**Comment by johnbell84** [comment]
Great!  Thanks very much for tackling this.
