### ISSUE TITLE
How to achieve smooth transition while dragging

### ISSUE THREAD

**Issue by satya-dash** [atlassian/react-beautiful-dnd#1532]
### Expected behavior
While dragging a draggable the droppable area should not increase its area unexpectedly. It should give a smooth behaviour. My use case is like below
![image](https://user-images.githubusercontent.com/6594397/66181865-17c55c00-e690-11e9-9087-b994003c8698.png)

So draggable (task) can be dragged within a task type smoothly.

### Actual behavior

While dragging a draggable (task) it is hiding the group heading and the spacing is behaving weirdly. e.g. - In my example, if you star dragging **Attend standup** in **Office work** group to the top it reaches down. I don't know why?

### Steps to reproduce
https://codesandbox.io/s/horizontal-list-0bnx1?fontsize=14

### What version of `React` are you using?
16.0.0

### What version of `react-beautiful-dnd` are you running?
4.0.0

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/s/horizontal-list-0bnx1?fontsize=14

**Comment by joseph-yu-procore** [comment]
I'm having the same/similar issue. Any update regarding this bug?

**Comment by alexreardon** [comment]
Please try and upgrade to 12.x. We do not support old versions of the library
