### ISSUE TITLE
Console errors looping and crashing browser

### ISSUE THREAD

**Issue by mateusbds** [atlassian/react-beautiful-dnd#1535]
I just started trying react-beautiful-dnd and had a crash when following the getting started guide. For some reason, when I don't provide a draggableId, index or ref to any of the components that require those props, and hit save, react reloads the page and no error message is shown on screen, but my cursor was "flashing", and then, firefox stopped working and then windows crashed. I tried again and with some debugging found what was causing this crash. Console was looping through the same error message over and over...

I know that I have to provide those props, but it's  a frustrating development experience if I end forgetting, or miss something, and my computer crashes again :(

[Just a print of my console and browser screen](https://imgur.com/a/RFBU6Cj)

I was able to reproduce with the code from [this sample](https://codesandbox.io/s/k260nyxq9v) but removing the droppableId prop from the first Droppable component inside the render function.

Edit: After some digging inside dnd code and testing other versions, when I use 10.1.1, the error behavior works fine, 11.0 it stats with the weird error loop. Another point is that when I use  `throw new Error("Test");` it works fine, but if I do `throw new Error("Invariant failed");` 
triggers the loop.

React: 16.10.2
React-dom: 16.10.2
React-beautiful-dnd: 11.0.5

**Comment by alexreardon** [comment]
This is a known issue with `11.x`. Please try `12.0.0-beta.4`

**Comment by mateusbds** [comment]
Ohhh, sure!!! Thanks sir.
