### ISSUE TITLE
Suggest droppable positions while dragging

### ISSUE THREAD

**Issue by jai1331** [atlassian/react-beautiful-dnd#1539]
Thanks for the awesome library but I'm stuck at this requirement, how do we show position or placeholder to drop items while drag an item like below:

![Capture](https://user-images.githubusercontent.com/8530380/66393199-8fc4b680-e9ef-11e9-9dfd-44a093eec0e5.PNG)

So here, the left side is a simple list which contains list items. Left side is :

1. This is not droppable, draggable only 
2. After drag, this list remains there same all the time.

On the right side, the dragged item will be dropped here.

1. Once the user dragged an item from left side, the other side/ right side should indicate a placeholders to user where they can drop.(placeholder in the sense droppable area letting users know you can drop it here)
2.  All the dropped items on the right side can be swappable within right side.

I'm not sure how do I achieve this, since I'm using this awesome library for small to-do and list drag and drop functionalities.

@alexreardon I deliberately need this feature in my project, I'm having hard time to work with this, can you suggest me whether this can be achievable by using this lib ?

**Comment by suryarsp** [comment]
Refer this link [https://codesandbox.io/s/ql08j35j3q](https://codesandbox.io/s/ql08j35j3q)

**Comment by jai1331** [comment]
@suryarsp Thanks, but i need something similar to this https://react-email-editor-demo.netlify.com/. When a user dragging an item from one side to canvas/droppable area. I need to show drop-zones/suggestible droppable areas to drop those items. After dragged the first item, Now the user will drag a next item to the droppable area where I need to show they can drop that item like top/bottom/left/right of the first dropped item. You can refer more on this https://stackoverflow.com/questions/58183717/react-drag-and-drop-plugin-suggestion

**Comment by alexreardon** [comment]
We rely on movement to communicate positioning rather than other affordances. You can know what list is being dragged over with the `DroppableStateSnapshot` and you can know where an item is exactly with `DragUpdate`. You could use that to draw something if you like
