### ISSUE TITLE
How can i drop an item to the top or end of a list when the item is out of droppable context?

### ISSUE THREAD

**Issue by dgesteves** [atlassian/react-beautiful-dnd#1546]
### Expected behavior
I want to be able to set any item of the list to the top or bottom if i drag out of the container

### Actual behavior
[Exemple code](https://codesandbox.io/s/zqwz5n5p9x)

### What version of `React` are you using?
"^16.10.2"

### What version of `react-beautiful-dnd` are you running?
"^11.0.5"

### What browser are you using?
Chrome

**Comment by EstevesDiogo** [comment]
How can i access to the position of each item on the list?

**Comment by Sandreu** [comment]
Hello,

Here is a fork of this example to view why it can be a strange UX effect... Just by putting a live index on the draggable element...

[Here is the fork](https://codesandbox.io/s/using-react-beautiful-dnd-with-hooks-vkqhx)

Regards.

**Comment by alexreardon** [comment]
Can you explain what you are trying to achieve a bit more? I am struggling to visual it

**Comment by Sandreu** [comment]
You must try to drag the first element to the bottom of list then go outside the droppable then drop... The draggable goes back at beginning then to bottom.
Regards.

**Comment by EstevesDiogo** [comment]
Ok thank you for the help.

**Comment by danieldelcore** [comment]
Looks like this issue has been resolved 😄 

Will close for now, but feel free to reopen if you're still experiencing this issue 👋
