### ISSUE TITLE
Is custom drag element possible through this library?

### ISSUE THREAD

**Issue by sanakr** [atlassian/react-beautiful-dnd#155]

**Comment by alexreardon** [comment]
You are welcome to use the `snapshot.isDragging` property to change the dragging component when it is dragging. However, it is strongly advised that you do not change the size or width of the component as this will result in a strange user experience. 

So to answer your question: you can use that prop to render a totally different component if you like. However, it is recommended that you rather just add some styling changes to the original component. Things like adding a shadow, a background colour and so on
