### ISSUE TITLE
z-index issue while dragging on iOS Safari

### ISSUE THREAD

**Issue by leantide** [atlassian/react-beautiful-dnd#1569]
### Expected behavior
z-index for dragged item appears in front of column drop target on iOS as it does on desktop

### Actual behavior
z-index for dragged item appears behind column drop target on iOS, but just while dragging.  It drags in front of its own column as expected, and after dropping into new column, it appears in the new column as expected. The issue is limited to the item being dragged over another drop target column, appearing behind the column while dragging. This issue is not observed on Chrome on my Mac desktop, only observed so far on iOS browsers. Not sure about Android.

### Steps to reproduce
Drag item between 2 drop target columns

### Suggested solution?
This could be my issue and not your components. Just wondering if anyone else sees this.

### What version of `React` are you using?
16.11.0

### What version of `react-beautiful-dnd` are you running?
12.0.0

### What browser are you using?
Safari iOS 13

### Demo
Not easy to extract a demo. If you do not see this behavior, will assume that it is in my code and this can be closed.

**Comment by alexreardon** [comment]
I haven't been able to produce this

**Comment by alexreardon** [comment]
Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
