### ISSUE TITLE
Images are not loading correctly on mobile browsers

### ISSUE THREAD

**Issue by raoulcimpean** [atlassian/react-beautiful-dnd#1570]
I use images as items. Sometimes, but not always on mobile browsers, images are not loading correctly, they are very small. After i interact with an item from DragDropContext , the image is "refreshed" and appear at parent container size(correct size).

On desktop works perfectly.
I have this: shouldRespectForcePress={true} .

**Comment by alexreardon** [comment]
See https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/avoiding-image-flickering.md

Let me know if that doesn't assist
