### ISSUE TITLE
Is there a way to override the 1/2 width threshold?

### ISSUE THREAD

**Issue by ZYinMD** [atlassian/react-beautiful-dnd#1574]
![demo](https://user-images.githubusercontent.com/32368482/67899343-76b7ad00-fb38-11e9-84b0-1061dd26689c.gif)

In this demo, I need to move items into different folders. Each folder name on the left is a small droppable, so I can simply drop items into them. However, my items are so wide I can't drag more than 1/2 out of the list, so they're still dropping back to the list. Is there a way to override the 1/2 rule? 

If not, I guess I could just go to `node_modules` and change the source code because this is all I need for dnd in my project. Is it feasible? Where should I look? (I'm still on v11.0.4 for the sake of dynamic addition/removal) 

Another thought is that since I have a very small drag handle, can I tell rbd to use the drag handle's dimensions as opposed to the whole draggable?

Thanks!

**Comment by alexreardon** [comment]
Let's track this here: #1505

**Comment by ZYinMD** [comment]
Hi @alexreardon , thanks for your reply. I don't see any remote connection between this issue and #1505. The "1/2 threshold" here is not about combining. It happens when dragging horizontally, the item needs to be dragged at least 1/2 outside of the list border to be considered "out". As the gif shows, each folder on the left is a droppable, but the draggables can't reach there.

**Comment by alexreardon** [comment]
> I don't see any remote connection between this issue and #1505

Please keep your language friendly.

I can see that you are trying to move a large item into a small area. I think this falls into #930

**Comment by ZYinMD** [comment]
Hi @alexreardon sorry about that, I edited the title to better describe summarize the issue.
