### ISSUE TITLE
Move away from redux

### ISSUE THREAD

**Issue by chaffeqa** [atlassian/react-beautiful-dnd#1576]
With hooks + context, it seems the trend is for applications to not default to including redux as the centralized state manager.

I was wondering how difficult it would be to move from redux to pure react.  Would that seem feasible with the current implementation or more of a massive lift?

**Comment by alexreardon** [comment]
One big challenge is a fast deep state updates

https://github.com/facebook/react/issues/13739

For us, Context is too slow. We have a lot of shared state that needs to be consumed by a lot of components. `react-redux` allows us to have blazingly fast state updates

**Comment by fmendez89** [comment]
Maybe moving to Recoil when it gets a bit more mature would be a real option. Currently is on beta, but already powerful and flexible. 

Take a look here 
https://recoiljs.org/

**Comment by afzalsayed96** [comment]
@alexreardon another interesting alternative to consider: https://github.com/dai-shi/react-tracked

Total size is only around [3.8Kbs](https://bundlephobia.com/result?p=react-tracked@1.4.1) minified as compared to 21Kbs+ for redux + react-redux

From their [Benchmarks](https://github.com/dai-shi/react-tracked/blob/master/website/docs/comparison.md)

> React Tracked provides useSelector hook from React Redux. So, the transition from React Redux hooks to React Tracked should be easy.


<img alt="benchmark result" src="https://user-images.githubusercontent.com/490574/62705335-28f34300-ba28-11e9-84ea-8f785c445ff4.png" width="600" />
