### ISSUE TITLE
Invariant failed: Announcement node already mounted

### ISSUE THREAD

**Issue by Mangatt** [atlassian/react-beautiful-dnd#1584]
### Expected behavior
There should be no such warnings in the console.

### Actual behavior
After HMR update, react-beautiful-dnd throws error that is catched by it's error boundary. Error is throwed on every update, no matter if updated Component is inside or outside DragDropContext.

### What version of `React` are you using?
16.11.0

### What version of `react-beautiful-dnd` are you running?
12.0.0

### What browser are you using?
Google Chrome 78.0.3904.8

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by Mangatt** [comment]
@alexreardon How can I emulate HMR problem on `codesandbox.io`?

**Comment by alexreardon** [comment]
Sorry, what does HMR stand for?

**Comment by alexreardon** [comment]
oh, hot module reload?

**Comment by alexreardon** [comment]
I can see why this could occur

**Comment by Mangatt** [comment]
Yes, hot module reloading.
