### ISSUE TITLE
Support adding Draggable during drag for non-virtual/normal lists

### ISSUE THREAD

**Issue by bradbesserman** [atlassian/react-beautiful-dnd#1587]
### Description

12.0.0 included an undocumented breaking change related to virtual lists.  In 11.0.4, you could create draggables in onDragStart.  This feature is useful for something like expanding a hidden/collapsed drop target onDragStart.  With the virtual-list change in 12.0.0, this is only possible if you use virtual lists.  This breaks existing interactions.  `rbd` logs this warning to the console:

`You are attempting to add or remove a Draggable while a drag is occurring. This is only supported for virtual lists.`

Please consider re-adding support for creating Draggables during drag, without requiring the use of virtual lists.  I only want to maintain feature parity with 11.0.4, without the additional overhead of adding virtual lists.

**Comment by alexreardon** [comment]
> In 11.0.4, you could create draggables in onDragStart

That was not known or supported behaviour

> ### Hyrum's Law
> With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.

Good news though - we are hoping to add a `DragDropContext | onBeforeCapture` responder to support your use case and others

Tracking that new feature here: #1588
