### ISSUE TITLE
TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.

### ISSUE THREAD

**Issue by on3iro** [atlassian/react-beautiful-dnd#159]
## Bug or feature request?
Bug/Documentation clarity

### Expected behaviour
Render simple dnd-example taskboard with multiple columns and a few cards.

### Actual behaviour
`TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.`
when dragging a card.

### Steps to reproduce
Not sure if this is an issue with the library or rather me using it wrong.

### Browser version

Firefox 57

### Demo

At this point I am unable to provide a working bin, as I am not even sure if I use the library correctly.
I tried to build a working example by referencing the docs. My current implementation looks like this:

```javascript
const renderCardsFromTasks = (tasks) => {
  return tasks.map(({ id, title }) =>
    <Draggable key={id} draggableId={`card-${id}`} type='CARD'>
      {
        (provided, snapshot) => (
          <div>
            <div
              ref={provided.innerRef}
              style={provided.draggableStyle}
              {...provided.dragHandleProps}
            >
              <Card title={title} />
            </div>
            {provided.placeholder}
          </div>
        )
      }
    </Draggable>
  )
}

const renderProcessColumns = (processesWithTasks) => {
  return processesWithTasks.map(({ id, title, tasks }) => {
    return (
      <Droppable key={id} droppableId={`list-${id}`} type='CARD'>
        {
          (provided, snapshot) => (
            <Column title={title} ref={provided.innerRef}>
              { renderCardsFromTasks(tasks) }
            </Column>
          )
        }
      </Droppable>
    )
  })
}

const TaskBoard = ({ processesWithTasks }: {
  processesWithTasks: Array<{
    id: string,
    title: string,
    tasks: Array<{
      id: string,
      title: string,
      procId: string
    }>
  }>
}) => {
  return (
    <Wrapper>
      <DragDropContext
        onDragStart={() => console.log('dragging')}
        onDragEnd={() => console.log('stop dragging')}
      >
        { renderProcessColumns(processesWithTasks) }
      </DragDropContext>
    </Wrapper>
  )
}

```

**Comment by on3iro** [comment]
Ok, I think I figured it out.

Apparently i really need the `<div>` around my `<Column />`-Component. I thought passing the `ref` directly to the Column would work, but it doesn't.

**Comment by alexreardon** [comment]
Remember that `ref` on a `ReactComponent` returns the instance of the component, whereas `ref` on a `ReactElement` returns the dom node. You would need to add a prop such as `innerRef` to publish the inner dom ref of the `Column` component.

More information: https://reactjs.org/docs/refs-and-the-dom

**Comment by alexreardon** [comment]
I think this is an easy trap to fall into @on3iro. I might add a note to the docs to prevent others from falling into the same trap

**Comment by on3iro** [comment]
Thanks for the clarification @alexreardon . A note inside the docs is definitely a good idea.
Speaking of the docs: the note which says that moving a draggable between two droppables is currently not supported is still in there. But I think this was shipped with **2.2.0** if I am not mistaken (at least it is working fine inside my project)?

Thanks for the awesome lib btw - really appreciate your work.

**Comment by alexreardon** [comment]
Need to remove that one. Good find. You are welcome to raise a PR :)

**Comment by on3iro** [comment]
Sure thing. I am currently at work, but I will fork the project and create a PR as soon as I get home.
