### ISSUE TITLE
A context menu appears when I try to drag and drop on the mobile

### ISSUE THREAD

**Issue by AlexCotano** [atlassian/react-beautiful-dnd#1592]
### Expected behavior
Drag and drop of the card

### Actual behavior
A context menu appears when I hold a card

### What browser are you using?
Android System WebView (ver. 6.8.121-2017112010)
Android 6.0
Flyme 6.3.1.0G
Meizu M5 build/MRA58K

### Screenshot
http://i.piccy.info/i9/4e68802ef1be46af38d6a477d08ccda9/1573229223/60332/1345103/photo_2019_11_08_18_01_18.jpg

**Comment by alexreardon** [comment]
We are currently opting out of context menus.. hmm

```
// Long press can bring up a context menu
    // need to opt out of this behavior
    {
      eventName: 'contextmenu',
      fn: (event: Event) => {
        // always opting out of context menu events
        event.preventDefault();
      },
    },
```

Can you please try to use the example of of the iframe and see if you get the same behaviour? Click the button in the top right that looks like a litt le share button 
<img width="67" alt="Screen Shot 2019-11-11 at 5 21 28 pm" src="https://user-images.githubusercontent.com/2182637/68565470-b753e680-04a7-11ea-9335-8f35cc0bff2f.png">

**Comment by AlexCotano** [comment]
> We are currently opting out of context menus.. hmm
> 
> ```
> // Long press can bring up a context menu
>     // need to opt out of this behavior
>     {
>       eventName: 'contextmenu',
>       fn: (event: Event) => {
>         // always opting out of context menu events
>         event.preventDefault();
>       },
>     },
> ```
> 
> Can you please try to use the example of of the iframe and see if you get the same behaviour? Click the button in the top right that looks like a litt le share button
> <img alt="Screen Shot 2019-11-11 at 5 21 28 pm" width="67" src="https://user-images.githubusercontent.com/2182637/68565470-b753e680-04a7-11ea-9335-8f35cc0bff2f.png">


Thanks for the answer!
Everything works in Chrome.

**Comment by alexreardon** [comment]
Sometimes iframes can be a big funny
