### ISSUE TITLE
trouble using react-beautiful-dnd(12.0.0) with react-table(6.10.0) using custom styling via scss and

### ISSUE THREAD

**Issue by aruniverse** [atlassian/react-beautiful-dnd#1598]
Hi. Im using react-table to define a custom themed table via scss, with some special columns. I would like to add drag and drop functionality, and came across this library. I'm running into issues when dragging my draggable over other rows, where it seems to fall below some of the rows. And some times the translation of the rows being dragged over is off, and my row disappears. 

I assume the answer is to use the cloning api introduced in v12. If thats the solution, then in my renderClone, i will need to totally redefine what my rows and cells look like. From the demo shown below, is the only solution to use the cloning api, and re write all of my themed row and cell components?

### Expected behavior
Smooth drag and drop where the row being dragged doesnt fall underneath other rows.
### Actual behavior
Watch Demo

### What version of `React` are you using?
^16.8.6

### What version of `react-beautiful-dnd` are you running?
^12.0.0

### What browser are you using?
chrome / chromium edge.

### Demo
![YQ0XuCKLbc](https://user-images.githubusercontent.com/11051042/68613798-9088b680-048d-11ea-829b-fb106bc52eda.gif)

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
