### ISSUE TITLE
Property 'shouldRespectForceTouch' does not exist on type Draggable

### ISSUE THREAD

**Issue by DED8IRD** [atlassian/react-beautiful-dnd#1599]
Testing on iOS (iPad Pro)

Drag & drop works great with fingers, but doesn't with the Apple Pencil. 
Judging from #[1192](https://github.com/atlassian/react-beautiful-dnd/pull/1192), this can be prevented by setting `shouldRespectForceTouch={false}` on `<Draggable />`.

Trying this, I get the following TypeScript error:
```
Type '{ children: (provided: DraggableProvided, snapshot: DraggableStateSnapshot) => Element; draggableId: string; index: number; shouldRespectForceTouch: boolean; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Draggable> & Readonly<DraggableProps> & Readonly<{ children?: ReactNode; }>'.
      Property 'shouldRespectForceTouch' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Draggable> & Readonly<DraggableProps> & Readonly<{ children?: ReactNode; }>'.  TS2769
```
### Expected behavior
Force press is disabled

### Actual behavior
TypeScript compile error

### Steps to reproduce
CRA w/ TypeScript with the following versions:
``` 
"typescript":  "3.6.2"
"@types/react-beautiful-dnd": "11.0.3",
"react-beautiful-dnd": "12.0.0"
```

### Suggested solution?
Update `@types/react-beautiful-dnd` `DraggableProps` to include `shouldRespectForceTouch`

### What browser are you using?
FF and Safari on iPad

**Comment by alexreardon** [comment]
Currently, the typescript types are maintained by the community in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). It looks like the types are missing that property (as well as not being updated to 12.0). 

We do hope to move this project over to a native TS implementation #982
