### ISSUE TITLE
Extra files are published to npm

### ISSUE THREAD

**Issue by bengummer** [atlassian/react-beautiful-dnd#16]
https://unpkg.com/react-beautiful-dnd@1.0.0/

Some of the files that are published but (probably) not needed on npm are:

* yarn-error.log (253kb)
* yarn.lock (236kb)
* flow-typed/
* .vscode
* .travis.yml
* .storybook/
* .babelrc
* .eslintrc

Can be removed from npm publish by settings `files` setting in `package.json`

**Comment by alexreardon** [comment]
ah - even though they are git ignored they are not npm ignored so that lib gets published.

Looks like the `.npmignore` will need to be a little smarter.

**Comment by leandrowd** [comment]
Any reason to keep .babelrc? It's actually breaking the build and I need to delete it manually:

```
ERROR in ./~/react-beautiful-dnd/~/reselect/es/index.js
Module build failed: ReferenceError: Unknown plugin "transform-export-extensions" specified in "/Users/llemos/src/ZZZZ/node_modules/react-beautiful-dnd/.babelrc" at 3, attempted to resolve relative to "/Users/llemos/src/ZZZZ/node_modules/react-beautiful-dnd"
```

**Comment by alexreardon** [comment]
Sounds reasonable to delete it!

**Comment by alexreardon** [comment]
Can you submit a PR @leandrowd ?

**Comment by leandrowd** [comment]
Done!
