### ISSUE TITLE
How to disable keyboard dragging

### ISSUE THREAD

**Issue by CedricJAnslinger** [atlassian/react-beautiful-dnd#1601]
How can I disable the keyboard support for certain elements? I couldn't find it in the documentation

**Comment by super861** [comment]
@CedricJAnslinger  delete props.onKeyDown in the renderItem works.

**Comment by alexreardon** [comment]
Perhaps we should expose the default `sensors` as public api. That way you can just pass in the ones you want (and exclude the ones you don't)

**Comment by alexreardon** [comment]
> delete props.onKeyDown in the renderItem works.

That won't work in 12.0

**Comment by gabriel-os-sousa** [comment]
Is it working on 13.0?

**Comment by gabriel-os-sousa** [comment]
I have same problem. I have keyboard shortcuts in my application thats use spacebar ('ctrl+space' and 'space'), and I need disable the drag only by keyboard, by mouse i wanna that works.

Its possible on 13.0?

**Comment by danieldelcore** [comment]
Hi @gabriel-os-sousa @CedricJAnslinger 👋 

> Perhaps we should expose the default sensors as public api. That way you can just pass in the ones you want (and exclude the ones you don't)

This is now possible in the latest version since we now export the default sensors. 

Will close this for now, reopen if it's still an issue for you
