### ISSUE TITLE
Portal based drag broken with touch

### ISSUE THREAD

**Issue by TrySound** [atlassian/react-beautiful-dnd#1604]
## Common issues setup guide

https://react-beautiful-dnd.netlify.com/?path=/story/board--dragging-a-clone

## Check your console

All clear

## Are you new to rbd?

I'm an old one

## Duplicates

I believe similar behaviour was before portals fix.

### Actual behavior

![Kapture 2019-11-14 at 1 15 53](https://user-images.githubusercontent.com/5635476/68809155-592c2c80-067c-11ea-902e-bdb4db533f1f.gif)

### Steps to reproduce

Run devtools in mobile mode. I use iphone 5

### What version of `React` are you using?

16.9

### What version of `react-beautiful-dnd` are you running?

12.0.0

### What browser are you using?

Chrome, safari ios

### Demo
https://react-beautiful-dnd.netlify.com/?path=/story/board--dragging-a-clone

**Comment by alexreardon** [comment]
Try loading it out of the iframe and see what happens

**Comment by alexreardon** [comment]
<img width="133" alt="Screen Shot 2019-11-14 at 9 21 39 am" src="https://user-images.githubusercontent.com/2182637/68809515-328fe500-06c0-11ea-84fc-6906b41edb9f.png">
Try the little expand button

**Comment by TrySound** [comment]
Same

**Comment by alexreardon** [comment]
I just tested it on my iOS device (latest OS) and it seems to be working correctly. What version of safari / iOS are you using?

**Comment by alexreardon** [comment]
I know safari made some changes to mobile stuff in the last update which did impact mobile a bit

**Comment by TrySound** [comment]
I use simulator with iOS 13.1 and chrome devtools with touch mode. Though in simulator the problem look differently

![Kapture 2019-11-14 at 1 29 37](https://user-images.githubusercontent.com/5635476/68810040-461a5c00-067e-11ea-9304-cdca34ac368c.gif)

**Comment by alexreardon** [comment]
It might be an issue with the simulator?

**Comment by TrySound** [comment]
My boss got it on his iPhone in production

**Comment by TrySound** [comment]
Will try to provide better reproduce

**Comment by alexreardon** [comment]
Cheers

**Comment by TrySound** [comment]
My tester has these glitches on her iPhone.
https://vimeo.com/373931892

**Comment by alexreardon** [comment]
Hey @TrySound, it feels like we are getting closer!

Can I confirm what version of iOS is being run?

**Comment by alexreardon** [comment]
Interesting! Can you please open it up out of the iframe and confirm the issue is still occurring?f

**Comment by TrySound** [comment]
Looks like the problem is iframe. Now even simulator stopped glitching. Don't know the reason. Thanks :)

**Comment by alexreardon** [comment]
I’m super glad it is all good!

**Comment by jankuss** [comment]
I'm still having the same issue.

This is broken for example:
https://react-beautiful-dnd.netlify.com/iframe.html?id=portals--using-your-own-portal&viewMode=story

I use Chrome in the Touch Simulation mode. The `touchstart` on the Draggable element is recognized and is transitioned into the dragging state and moved into a portal. Subsequent `touchmove` events on the other hand don't seem to be recognized. It seems the `touchend` event is not being recognized aswell, as when I release the draggable it is still stuck in the dragging state.

When the Draggable is stuck in this state and I `touchstart` it again, everything works fine.

![ezgif-4-30bf966d0fb1](https://user-images.githubusercontent.com/1659532/70235387-264cf400-1763-11ea-9019-701b5563dced.gif)

**Comment by Merynek** [comment]
Why is this issue closed???
You can reproduce this issue in your own example so why closed??
Just open your examle with portal on your mobile and try dragging.
It is works only when you touch twice so it doesnt fixed.

https://react-beautiful-dnd.netlify.app/iframe.html?id=portals--using-your-own-portal&viewMode=story

**Comment by DavGarcia** [comment]
I had the same issue, but with react-dnd and react-dnd-touch-backend. I wonder if the issue is caused by some change in browser touch behavior or iOS rather than a library issue? Anyone find a fix?

**Comment by Merynek** [comment]
No the problem is in library, bcs I found the commit what caused it.
This issue: https://github.com/atlassian/react-beautiful-dnd/issues/2111
