### ISSUE TITLE
Please update @types/react-beautiful-dnd for v 12.1.0. 

### ISSUE THREAD

**Issue by ksolov** [atlassian/react-beautiful-dnd#1609]
Hello!

I need getContainerForClone prop for Droppable, but my TS are report:
Property 'getContainerForClone' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Droppable> & Readonly<DroppableProps> & Readonly<{ children?: ReactNode; }>'

**Comment by engp79715** [comment]
Hi,

I installed v12.1.0, but @types/react-beautiful-dnd is still version 11.0.3 in https://www.npmjs.com/package/@types/react-beautiful-dnd. Can you publish the types for v12.1.0? I need it support for virtual list.

Thanks!

**Comment by aruniverse** [comment]
I have a PR up for this. Just needs to get approved. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40309

**Comment by alexreardon** [comment]
Tracking this on ^
