### ISSUE TITLE
onBeforeCapture callback not called

### ISSUE THREAD

**Issue by leantide** [atlassian/react-beautiful-dnd#1612]
### Expected behavior
onBeforeCapture callback is called, like the other responders.

### Actual behavior
onBeforeCapture callback does not seem to be called. I do get console statements for the other callbacks.

### Steps to reproduce

```
const onBeforeCapture = useCallback(() => console.log('onBeforeCapture'), []);
const onBeforeDragStart = useCallback(() => console.log('onBeforeDragStart'), []);
const onDragStart = useCallback(() => console.log('onDragStart'), []);
const onDragEnd = useCallback(() => console.log('onDragEnd'), []);

return (<DragDropContext
   onBeforeCapture={onBeforeCapture}
   onBeforeDragStart={onBeforeDragStart}
   onDragStart={onDragStart}
   onDragEnd={onDragEnd}> ...
```

### What version of `React` are you using?
React 16.11

### What version of `react-beautiful-dnd` are you running?
rbd 12.1

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
Are you using the right version of `rbd`?

I have pasted your code here and it seems to work fine

https://codesandbox.io/s/mystifying-gates-7bo18

**Comment by leantide** [comment]
npm list gives react-beautiful-dnd@12.1.0.

This is weird. Should be so straight forward. Must be something I am doing different.

I am using 3 <DragDropContext>, but they are not nested and are on different routes so would not be mounted together. Maybe that is messing something up.

**Comment by leantide** [comment]
Started working after I rebooted my machine. Things going on that I do not understand. Maybe it was my browser cache or maybe it was my `npm start` not doing a full build.

Sorry to bother you.

**Comment by alexreardon** [comment]
Nah, it is all good!
