### ISSUE TITLE
items can't move !!

### ISSUE THREAD

**Issue by shipcake** [atlassian/react-beautiful-dnd#1617]
when I open console log  Warning: Prop `data-rbd-draggable-context-id` did not match. Server: "11" Client: "0"
![image](https://user-images.githubusercontent.com/30076862/69047054-e7156800-0a2c-11ea-842c-a54a0afb01a5.png)

**Comment by alexreardon** [comment]
Looks like you are having a SSR issue. See here: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/reset-server-context.md

**Comment by nodabladam** [comment]
I have Next.js working like this:
```
// _document.js
static async getInitialProps(ctx) {
    const originalRenderPage = ctx.renderPage;

    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: App => props => {
          resetServerContext();
          return <App {...props} />;
        }
      });

    const initialProps = await Document.getInitialProps(ctx);

    return { ...initialProps };
  }
```

but when I try and turn on the new [`reactStrictMode`](https://nextjs.org/blog/next-9-1-7#react-strict-mode-compliance-and-opt-in), I get these errors back:
```
// next.config.js
module.exports = {
  reactStrictMode: true
}
```

Any ideas on how I should be doing Next.js  `resetServerContext();` so global `reactStrictMode` can be set?
