### ISSUE TITLE
[BUG] - Issues moving "1st items" between columns

### ISSUE THREAD

**Issue by albertocevallos** [atlassian/react-beautiful-dnd#1624]
### Expected behavior

I move the first task in column 1 to an empty column and the first task will now be the first one in the new column.

### Actual behavior

I have 3 columns, I pull the first task in column 1 to column 2 (or column 3). The Droppable component recognizes a task component is hovering on top of it  and changes background color but does not stay in the new empty column.

### Steps to reproduce
Grab task 1 in column 1 and drag to any empty column or the 1st position of any column that is empty or occupied with other tasks.

### Suggested solution?

Not sure if this is a key or index problem or a logic problem within onDragEnd.

### What version of `React` are you using?
    "react": "^16.11.0",

### What version of `react-beautiful-dnd` are you running?

    "react-beautiful-dnd": "^12.1.1",

### What browser are you using?

Chrome Version 78.0.3904.97 (Official Build) (64-bit)

### Demo

https://codesandbox.io/s/react-dnd-bug-alberto-y1g61

It works when you move any task that is not in the 1st position of any column to any first position of any column. This is not the same for the 1st position of any column.

<img width="668" alt="Screen Shot 2019-11-21 at 3 01 25 AM" src="https://user-images.githubusercontent.com/27132021/69332302-3e712f00-0c0b-11ea-8e66-535ad3083b6c.png">

**Comment by albertocevallos** [comment]
@alexreardon also worth mentioning I had some issues during the egghead tutorial where I had to use the core-js, not sure if this has anything to do. Thanks!

**Comment by alexreardon** [comment]
Your sandbox is now running

(Sorry for the delay on this one)

I suspect that you need to ensure that there is a min-height on your droppable area to make room for the draggables
