### ISSUE TITLE
[QUESTION] How to make changes persistent?

### ISSUE THREAD

**Issue by scheung38** [atlassian/react-beautiful-dnd#1631]
How to make changes persistent, i.e if this is inside a modal window, and i click an OK button in this modal window to persist it? 

Is it best practice to save to local json or need full blown dB thanks. Sorry not sure why there is a wontfix label here?

**Comment by tianna1121** [comment]
I am trying to persist the droppable to my firebase firestore database for later use. I have already push/set the droppable items (stringified json object) to the remote database. However, when I pull/get those infos from the database and set the droppable via this.setState() in a new browser window, the id (generated by uuid() ) has already been changed. So, everything seems not working. 
Any suggestions?

**Comment by danieldelcore** [comment]
Hey @scheung38, 
Where you manage the state of RBD is completely up to you. If you want to persist it between modal instances, then you'll have to manage that state higher up the react tree. If you need to manage it in firebase that is also totally an option 😊

> Is it best practice to save to local json or need full blown dB thanks. Sorry not sure why there is a wontfix label here?

That depends on the use case. If you simply want to open and close a modal and have the state persisted, then i would recommend simply moving the state up the react tree. 

If you want to persist the state between user sessions. ie, a user can log off and have all of the draggables in the same place when they get back, then i would recommend storing the state in a database or whatever suits you.

> Is it best practice to save to local json or need full blown dB?

The library does not have any opinions about how you approach persistence, it's not a concern of this library, totally up to you 😊


Will close this issue for now, please feel free to reopen if you need to discuss it further 👍
Cheers!
