### ISSUE TITLE
A call for examples - please share what you have achieved!

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#164]
I was thinking it would be a good idea to put together a showcase of interfaces that people have put together using `react-beautiful-dnd`. It may even play into #163. Please add them here!

❤️

**Comment by flipchart** [comment]
Not sure if you're wanting commercial examples, but we're using react-beautiful-dnd in our product [Comb](https://www.withcomb.com) for the task list inside the app. 

I wanted to thank you for the library - it's a fantastic product and made it really easy to do what we're doing with it. And it looks great 😄

**Comment by humphreybc** [comment]
As you know, [Dovetail](https://dovetailapp.com) uses react-beautiful-dnd.

**Comment by Shawn-Williams** [comment]
[Here](https://github.com/Shawn-Williams/Jammming-CA) is the repo for my small Spotify playlist application that I build while learning React. I used react-beautiful-dnd to provide the functionality to sort the user created playlist prior to saving. I'm new to this and it was fun and challenging!

The application can be found [here](http://jammming-ca.surge.sh).

**Comment by adeshas** [comment]
Hello @alexreardon and all,
Please can you share a simple example (i.e sample code) of your implementation of multiple lists in a board.
I would like simple one-pager similar to the sample code in the docs.
Thank you

**Comment by epicallan** [comment]
We use it to on this page in re-arranging selection options. http://data.devinit.org/unbundling-aid
<img width="1164" alt="screen shot 2017-11-30 at 12 12 12" src="https://user-images.githubusercontent.com/6281527/33422744-b8e29174-d5c7-11e7-9e53-9918ada787f6.png">

**Comment by nicubarbaros** [comment]
Hey, we made a calendar at [Planable](https://app.planable.io/).

**Comment by Geczy** [comment]
@nicubarbaros any example code you can share about that calendar? Looks exactly like what I need to build

**Comment by loaibassam** [comment]
We're using React Beautiful on [Plutio.com ](https://plutio.com), here is a screenshot 👍 

![screen recording 2018-01-05 at 03 17 pm](https://user-images.githubusercontent.com/4785390/34615209-fdf14528-f22b-11e7-813b-8ffde89d06e6.gif)

**Comment by abhidnyag** [comment]
Is it possible to drag multiple items at once in a board view?
