### ISSUE TITLE
Example for using hooks in multi-column situation

### ISSUE THREAD

**Issue by NickEmpetvee** [atlassian/react-beautiful-dnd#1642]
Hi there. Just wanted to know if there's a guide or an example for dragging / dropping across two columns using functional components. I've managed to do this with Component classes, but am having some difficulty figuring out how to deal with state values with Functional components.

Thank you!

**Comment by carlosagsmendes** [comment]
Hi @NickEmpetvee, what's the difficulty you're experiencing?

**Comment by NickEmpetvee** [comment]
Hi @carlosagsmendes. Generally speaking, how to go about the whole conversion. For example, for places where I use state like:
```
       const newState =
        {
            columns:
            {
              ...this.state.columns,
              [newStart.id]: newStart,
              [newFinish.id]: newFinish,
            },
        };
```
Will it still work with the libraries if I switch to:
```
setColumns(prevColumns => ({
  ...prevColumns,
  [newStart.id]: newStart,
  [newFinish.id]: newFinish,
}));
```

**Comment by carlosagsmendes** [comment]
Have you checked [this example](https://codesandbox.io/s/ql08j35j3q) from the [examples](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/examples.md) page?

The code should be the same

**Comment by danieldelcore** [comment]
Looks like this issue has been resolve, so will close for now 😄 
Please feel free to reopen if you're still having problems.

**Comment by NickEmpetvee** [comment]
> Looks like this issue has been resolve, so will close for now 😄
> Please feel free to reopen if you're still having problems.

Yes thank you.
