### ISSUE TITLE
Invariant failed: Expected phase to be DRAGGING after INITIAL_PUBLISH

### ISSUE THREAD

**Issue by millerdev** [atlassian/react-beautiful-dnd#1647]
I'm trying to render a virtual list that flows with other content (both above and below the list) on the page. The virtual list component I'm trying to use is [`react-virtual-list`](https://github.com/developerdizzle/react-virtual-list). Unfortunately it appears to not play nicely with RBD.

Background: all virtual list examples that I could find (except possibly [react-virtualized `WindowScroller`](https://react-beautiful-dnd.netlify.com/?path=/story/virtual-react-virtualized--window-list)) require setting a "virtual window" height on the scrollable container, which means the virtualized list content is in a separate scroll region from other page content. Solutions like [`AutoSizer`](https://github.com/bvaughn/react-virtualized-auto-sizer) do not work because they do not play nicely with content rendered below the last item in the virtual list, which should only be seen after scrolling beyond the bottom of the virtual list.

### Expected behavior

RBD in tandem with `react-virtual-list` should allow items to be dragged instead of logging errors.

### Actual behavior

Cannot drag items, and getting two messages in the console:

> Warning: 
> An error was caught by our window 'error' event listener while a drag was occurring.
The active drag has been aborted.
>
> Error:
> Invariant failed: Expected phase to be DRAGGING after INITIAL_PUBLISH

### Steps to reproduce

- Open the Demo below.
- Try to drag an item to a new position in the list.
- Note warning and error in console.

### What browser are you using?

Tested on latest versions of Chrome and Firefox.

### Demo

https://codesandbox.io/s/simple-virtual-list-dark-m6wme

Based on the [`react-window` Basic list](https://codesandbox.io/s/simple-virtual-list-dark-c6wqc) example.

At first I thought the issue was that the list items were not absolutely positioned within the container, so I hacked together an adaptation of `react-virtualized-list`, but alas [it has the same issue](https://codesandbox.io/s/simple-virtual-list-dark-t3p5w) (as well as an initial styling/rendering glitch).

**Comment by millerdev** [comment]
@alexreardon is there more information I can provide here to help diagnose the issue?

**Comment by millerdev** [comment]
I realized my sandbox, which I forked from an example, was using rbd v12.0.0-beta3. I updated it to v12.2.0. Now I see a new error message in the console, but otherwise behavior is the same.

New console message:

> react-beautiful-dnd
>
> An error was caught by our window 'error' event listener while a drag was occurring.
The active drag has been aborted.

**Comment by millerdev** [comment]
After more debugging I've realized the virtual list component I'm using has some seriously twisted initialization logic, and that is causing the issue. Closing for now since I've gotten past the invariant failure.

**Comment by rolandjohann** [comment]
@millerdev can you share what the actual problem was? I ran into this issue as well. As soon as I want to pass additional props to the row renderer of the virtual list (with itself then renders `Draggable`) I get the DND error you described initially.

```js
import { FixedSizeList as VirtualList, areEqual } from "react-window"

// works
<VirtualList {...virtualListProps}>
  {DraggableRow}
</VirtualList>

// leads to error: Invariant failed: Expected phase to be DRAGGING after INITIAL_PUBLISH
<VirtualList {...virtualListProps}>
  {virtualRowProps => <DraggableRow {...virtualRowProps} />}
</VirtualList>

// this is wat I need
<VirtualList {...virtualListProps}>
  {virtualRowProps => <DraggableRow {...virtualRowProps} snapshot={snapshot} />}
</VirtualList>
```

I workaound this by populating the snapshot variable of `Droppable` via react context.

**Comment by vasanthkumar123** [comment]
Im facing the same issue where I Lazy load the boards with react-window-infinite-scroller

**Comment by vasanthkumar123** [comment]
> @millerdev can you share what the actual problem was? I ran into this issue as well. As soon as I want to pass additional props to the row renderer of the virtual list (with itself then renders `Draggable`) I get the DND error you described initially.
> 
> ```js
> import { FixedSizeList as VirtualList, areEqual } from "react-window"
> 
> // works
> <VirtualList {...virtualListProps}>
>   {DraggableRow}
> </VirtualList>
> 
> // leads to error: Invariant failed: Expected phase to be DRAGGING after INITIAL_PUBLISH
> <VirtualList {...virtualListProps}>
>   {virtualRowProps => <DraggableRow {...virtualRowProps} />}
> </VirtualList>
> 
> // this is wat I need
> <VirtualList {...virtualListProps}>
>   {virtualRowProps => <DraggableRow {...virtualRowProps} snapshot={snapshot} />}
> </VirtualList>
> ```
> 
> I workaound this by populating the snapshot variable of `Droppable` via react context.

I got this Same issue, Can u please help me with the work around

**Comment by Radzell** [comment]
Did anyone figure this out I am having the same issue with `import TrackVisibility from 'react-on-screen';` I get errors ass rbd is loading draggable it is causing errors to occur when I try to initialize a drag.

**Comment by ConorTighe1995** [comment]
Im having the same issue after adding a react portal inside the Draggable.

**Comment by hoangvvo** [comment]
To those who face the same problem, I also get stuck on this for hours too. It's basically what rolandjohann was saying. The way I solve this is to create the function `Row` as suggested by the documentation.

Seems like this does not work:

```js
<List>
  {(props) => { /* ... */ }}
</List>
```
It must be this:
```js
<List>
  {Row}
</List>
```

The reason I went with the first one initially because I want to get some variables from the outer scope:

```js
const [someState] = useState();
return (
  <Droppable>
    <List>
      {(props) => <Draggable><Component  someState={someState} /></Draggable>}
    </List>
  <Droppable />
)
```

However, it does not seem to work that way so either you have to create a Context, or pass that into the `itemData` of `<List>`

**Comment by krnbatta** [comment]
> > @millerdev can you share what the actual problem was? I ran into this issue as well. As soon as I want to pass additional props to the row renderer of the virtual list (with itself then renders `Draggable`) I get the DND error you described initially.
> > ```js
> > import { FixedSizeList as VirtualList, areEqual } from "react-window"
> > 
> > // works
> > <VirtualList {...virtualListProps}>
> >   {DraggableRow}
> > </VirtualList>
> > 
> > // leads to error: Invariant failed: Expected phase to be DRAGGING after INITIAL_PUBLISH
> > <VirtualList {...virtualListProps}>
> >   {virtualRowProps => <DraggableRow {...virtualRowProps} />}
> > </VirtualList>
> > 
> > // this is wat I need
> > <VirtualList {...virtualListProps}>
> >   {virtualRowProps => <DraggableRow {...virtualRowProps} snapshot={snapshot} />}
> > </VirtualList>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I workaound this by populating the snapshot variable of `Droppable` via react context.
> 
> I got this Same issue, Can u please help me with the work around

Were you able to solve your issue?
