### ISSUE TITLE
Draggable inside the same droppable overlap a non draggable component

### ISSUE THREAD

**Issue by rzk666** [atlassian/react-beautiful-dnd#1649]
Hey guys, I probably just missed something but I've seen the egghead.io tut and worked a while with rbd (and I'm super happy about it!), but there's one minor thing I can't figure out - its more a call for help then a bug report, but I honestly don't know where to go now.

----

I've been using react dnd and to generate a list of draggable items inside a tab:
![image](https://user-images.githubusercontent.com/48220988/69959677-636d7800-1510-11ea-8fda-6f3ac4c80c1f.png)

The ad component you see in the middle is NOT a draggable (see code below). What happens when I drag and switch places with items next to the ad component, the items overlap it:
![Draggable Overlap](https://user-images.githubusercontent.com/48220988/69959707-7d0ebf80-1510-11ea-86d2-511c68725c28.gif)

How can I cause the items to only switch places with themselves and 'skip' the ad component? Adding the code below Thanks!!

```
data.items.map((item, index) => !item.delete &&
          (
            <React.Fragment>
              { ad && ad.displayIndex === index &&
                <div
                  className={classNames({
                    [styles.itemListAdContainer]      : !isAdRemoved,
                    [mobileStyles.itemListAdContainer]: !isAdRemoved,
                    })}
                >
                  { !isAdRemoved &&
                    <ItemListAd
                      data={ad.data}
                      onClose={() => this.setState({ isAdRemoved: true })}
                    /> }
                </div>
              }

              <Draggable
                key={item.id}
                draggableId={item.id}
                index={index}
              >
                {(provided, snapshot) => (
                  <div
                    ref={provided.innerRef}
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                  >
                    <Item
                      showDivider={ad.displayIndex !== index + 1 || isAdRemoved}
                      data={item}
                      key={item.id}
                      onChange={data => onItemChange(item, data)}
                    />
                  </div>
                )}
              </Draggable>
            </React.Fragment>
        ))
```

This is the map function rendering the items inside the category\tab component (the big container). The whole category\tab component is a droppable

### What version of `React` are you using?
16.2.0

### What version of `react-beautiful-dnd` are you running?
10.0.4

### What browser are you using?
Chrome

Thanks!

**Comment by alexreardon** [comment]
What you are after is currently not supported. We currently expect draggables to be pushed up next to each other without gap

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#draggable-s-should-be-visible-siblings

Anything is possible! But the interaction you are after currently is not supported.

There might be a few round about ways to unblock you

- One thing you could do is remove the add in `onBeforeCapture`. However, that might result in a strange experience if there is an add in your list before the dragging item as it will jump up
- You could make the draggables bigger and position the add absolutely between them. Then when the drag starts you hide the add but the dimensions of the dragging items stays the same - they will just be a bit bigger

**Comment by rzk666** [comment]
Thanks for the answer!
