### ISSUE TITLE
isDraggingOver doesn't work for Droppables with isDropDisabled set to true.

### ISSUE THREAD

**Issue by rajats920** [atlassian/react-beautiful-dnd#1651]
### Expected behavior
The isDraggingOver flag should be true for a Droppable if a Draggable component is being dragged over it.

### Actual behavior
isDraggingOver flag remains false.

### Steps to reproduce
Set a Droppable with isDropDisabled flag as true.
Check isDraggingOver flag while dragging a Draggable component over it.

### Suggested solution?
NA

### What version of `React` are you using?
16.9.0

### What version of `react-beautiful-dnd` are you running?
11.0.5

### What browser are you using?
Google Chrome

### Demo
https://codesandbox.io/s/vertical-list-gd5ly

**Comment by alexreardon** [comment]
When a Droppable is disabled it is ignored

**Comment by alexreardon** [comment]
We excluded disabled items from our collision engine.

I think it would be strange to be 'over' a list that is disabled. It would then mean we would need to allow a user to be over a list, but that items wouldn't move out of the way. What would we do if the user dropped on the list?

**Comment by rajats920** [comment]
What we needed was to change the style of the disabled droppable component when a draggable is dragging over it, i.e. a style to show that dropping is disabled.
But looks like this is not possible. Do you know of any workaround that I can use for this?
