### ISSUE TITLE
The item shouldn't be turned back to the list when deleted.

### ISSUE THREAD

**Issue by RomanProkhodsky** [atlassian/react-beautiful-dnd#1652]
### Expected behavior

When the user drags the item out of the list and drops it outside, it should be deleted. The item shouldn't go back to the list.

### Actual behavior

The item goes back to the list and then deleted.

### Steps to reproduce

Drag the item, drop it outside of the list.

### Suggested solution?
Switch off drop animation, but how?

### What version of `React` are you using?
^16.8.0

### What version of `react-beautiful-dnd` are you running?
12

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/s/react-beautiful-dnd-ndjwl

**Comment by alexreardon** [comment]
Here you go: [skip the drop animation](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/drop-animation.md)
