### ISSUE TITLE
https://react-beautiful-dnd.netlify.com/ is   not accessible

### ISSUE THREAD

**Issue by itLeo** [atlassian/react-beautiful-dnd#1664]
When I visit https://react-beautiful-dnd.netlify.com/, the website fails to load, and I found through F12 that a script loading was rejected I switch to another computer to access the same。

**Comment by danieldelcore** [comment]
Hey @itLeo, which browser (and version) are you using? Is the issue still happening for you?

**Comment by alexreardon** [comment]
Please comment if this is still occurring and we can investigate
