### ISSUE TITLE
OnDragStart removes original space before OnDragEnd

### ISSUE THREAD

**Issue by justsolarry** [atlassian/react-beautiful-dnd#1665]
### Expected behavior
When clicking and dragging, the space below should be retained before letting go
### Actual behavior
When clicking and dragging, the space below is not  retained before letting go

### Steps to reproduce
1 - Create a list of items
2 - Add an index counter as a sibling to the `Draggable` component like below

![image](https://user-images.githubusercontent.com/21080305/70528699-7bb84500-1b57-11ea-94e8-3d434d1bdc93.png)

![image](https://user-images.githubusercontent.com/21080305/70528734-8ffc4200-1b57-11ea-997d-498fbd1000dd.png)

3 - Click and drag any item and the counter space will shrink.

### Suggested solution?

Somehow retain the original space `onDragStart`

### What version of `React` are you using?
16.10.2

### What version of `react-beautiful-dnd` are you running?
12.2.0

### What browser are you using?
Chrome

### Demo

![Dec-10-2019 14-20-30](https://user-images.githubusercontent.com/21080305/70529037-452efa00-1b58-11ea-9f77-c2c1649c729a.gif)

Please let me know if this makes sense. Thanks!

**Comment by justsolarry** [comment]
I see that when drag starts, the position is fixed and moved with translate, hence the sibling div auto adjusts the height. I'm not sure if there is a workaround for this.

**Comment by VladKopylov** [comment]
Try    {provided.placeholder}
`<Droppable droppableId="droppable">
                            {provided => (
                                <div ref={provided.innerRef}>
                                    {fields.map(
                                        (
                                            detail: any,
                                            index: number
                                        ): JSX.Element => (
                                            <div
                                                key={index}
                                                detail={detail}
                                                
                                                index={index}
                                                setRef={this.setRef}
                              
                                            />
                                        )
                                    )}
                                      **{provided.placeholder}**
                                </div>
                            )}
                        </Droppable>`

**Comment by VladKopylov** [comment]
Try    {provided.placeholder}
` 
<Droppable droppableId="droppable">
                            {provided => (
                                <div ref={provided.innerRef}>
                                    {fields.map(
                                        (
                                            detail: any,
                                            index: number
                                        ): JSX.Element => (
                                            <div
                                                key={index}
                                                detail={detail}
                                                
                                                index={index}
                                                setRef={this.setRef}
                              
                                            />
                                        )
                                    )}
                                      **{provided.placeholder}**
                                </div>
                            )}
                        </Droppable>`

**Comment by VladKopylov** [comment]
Try    {provided.placeholder}
![carbon](https://user-images.githubusercontent.com/15313594/70727051-acd77780-1d07-11ea-93a7-c50ff9b018e6.png)

**Comment by justsolarry** [comment]
![image](https://user-images.githubusercontent.com/21080305/70731732-d8f6f680-1d0f-11ea-835b-32b8d0140242.png)
@VladKopylov  I already have that. That doesn't solve anything.

**Comment by VladKopylov** [comment]
@justsolarry 
need code on codesandox

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
