### ISSUE TITLE
Droppable typescript renderClone

### ISSUE THREAD

**Issue by jMoulis** [atlassian/react-beautiful-dnd#1666]
I'm using the 12.2.0 rbd version and react-beautiful-dnd": "^11.0.3 types.
When I want to use renderClone method on Droppable component I have an error TS2769:
`Property 'renderClone' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Droppable> & Readonly<DroppableProps> & Readonly<...>'`.
I checked the index.d.ts and this method is not typed.
I'm I missing something?

**Comment by danieldelcore** [comment]
Hi @jMoulis, 
Looks like `renderClone` was introduced in `~v12`. Looks like the type definitions have fallen behind. Since these types are maintained by the rbd community, it's probably best to raise an issue here:
https://github.com/DefinitelyTyped/DefinitelyTyped

Cheers.

**Comment by ArielFrischer** [comment]
Hey just updating this thread that I posted this issue on the appropriate channel [definatelyTyped github issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41456).

**Comment by alexreardon** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40309
