### ISSUE TITLE
Clicking a button inside a Draggable component focuses parent 

### ISSUE THREAD

**Issue by Bwatada** [atlassian/react-beautiful-dnd#1667]
### Expected behaviour
Clicking on a nested button in a draggable object shouldn't focus its parent.

### Actual behaviour
 Clicking on a nested button focuses the parent div

### Steps to reproduce
- Using the demo at https://react-beautiful-dnd.netlify.com/?path=/story/nested-interative-elements--stress-test
- Make sure dragging from interactive elements is disabled
- Click on any of the buttons

### What browser are you using?
Safari Version 13.0.3 (15608.3.10.1.4)

**Comment by danieldelcore** [comment]
Hey thanks for raising the issue, looks like it's safari specific 👀 
Will have a bit of a look into it now

**Comment by alexreardon** [comment]
How strange! It looks like it is Safari (webkit) only. I'll take more of a look soon

**Comment by alexreardon** [comment]
This is actually standard browser behaviour in safari. We are not doing any event prevention or focus manipulation for interactive elements. 

have a look at this in chrome and then in safari

https://codepen.io/alexreardon/pen/LYEdveK

**Comment by umar-khan** [comment]
@alexreardon 
We're also seeing the same issue in Firefox.
Looks like Chrome is the outlier here.

**Comment by alexreardon** [comment]
It is a standard browser behaviour. Not sure if we should be doing anything about it
