### ISSUE TITLE
cross origin error when trying both horizontal and vertical drag and drop

### ISSUE THREAD

**Issue by soju7** [atlassian/react-beautiful-dnd#1668]
i was trying to implement horizontal and vertical drag and drop but i ended up with this error. any help?
here is the fiddle
https://codesandbox.io/embed/horizontal-list-4oev7?fontsize=14&hidenavigation=1&theme=dark

**Comment by danieldelcore** [comment]
Hi there! 

Looks like you need to either update or downgrade some of your dependencies. You're using an older version of `react-beautiful-dnd` and `react`. It's possible to simply update the version to the following to get your to example to work:

![image](https://user-images.githubusercontent.com/3030010/70765684-95ec6000-1daf-11ea-823d-208d3a22174b.png)

Let me know how that goes for you,
Cheers 😄

**Comment by danieldelcore** [comment]
Will close this issue for now, since it's likely a configuration related issue. If you would like to continue the conversation feel free to reply to this issue and we can reopen it if needed.
