### ISSUE TITLE
Highlight Droppable zones when Dragging

### ISSUE THREAD

**Issue by lucbas** [atlassian/react-beautiful-dnd#1688]
Hi all

Thanks for this fantastic library, I'm just getting started and was wondering how I can achieve to highlight (change the background color) of all enabled Droppable zones when starting a drag.

The background color change is already working with `isDraggingOver`, but as it says, only while dragging over the one dropzone.

I used inline styling as shown in the example so far:

```
<Droppable droppableId={item.uuid}>
                    {(provided, snapshot) => (
                      <div
                        ref={provided.innerRef}
                        {...provided.droppableProps}
                        style={{
                          backgroundColor: snapshot.isDraggingOver
                            ? "grey"
                            : "gainsboro"
                        }}
                      >
</Droppable>

```

Thank you a lot!

**Comment by alexreardon** [comment]
You will find this helpful: https://egghead.io/lessons/react-customise-the-appearance-of-an-app-during-a-drag-using-react-beautiful-dnd-snapshot-values

Let me know if that is not what you were after

**Comment by shivambajpai099** [comment]
Hi, the above tutorial helps in highlighting a single droppable zone when a draggable is moving over it, but in case we have 2-3 different droppable zones, we would like to highlight all the droppable zones where the item can be dropped in and not just the one over which the item is currently being dragged.

**Comment by ro0t** [comment]
> Hi, the above tutorial helps in highlighting a single droppable zone when a draggable is moving over it, but in case we have 2-3 different droppable zones, we would like to highlight all the droppable zones where the item can be dropped in and not just the one over which the item is currently being dragged.

You could use the events from the DragDropContext:
**onDragStart** and **onDragEnd** and set a className to the <body> tag. Once dropped, remove the className.

Thats how I'm doing this at the moment.
