### ISSUE TITLE
Nested droppable

### ISSUE THREAD

**Issue by gustavomauricio** [atlassian/react-beautiful-dnd#1689]
Im trying to implement a nested droppable zone, List A with a List B inside where elements from A and B are only draggable betweem themselves. Then a 2nd column on the right which elements can be dragged to either list A or B. Is this achievable with this library? been having some trouble with this implementation

Thanks in advance everyone!

**Comment by jakemayfield** [comment]
@gustavomauricio It's my understanding that nested droppables are not natively possible with this library right now and isn't a high priority item on the roadmap.

I suggest you take a look at [#1001](https://github.com/atlassian/react-beautiful-dnd/issues/1001), [#1107](https://github.com/atlassian/react-beautiful-dnd/issues/1107), and have a look [here](https://github.com/atlassian/react-beautiful-dnd/issues/1109#issuecomment-475118595) on #1109.

Others have suggested using @atlaskit/tree in some ways.
