### ISSUE TITLE
Elements that are not dragged were pushed to the end

### ISSUE THREAD

**Issue by isemaj** [atlassian/react-beautiful-dnd#1696]
### Expected behavior

Elements that are not drag should remain on their position unless the element that is drag cross to one of them.

### Actual behavior

Elements that are not drag push to the other end.

### Steps to reproduce

[![Edit laughing-pond-59fs0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-pond-59fs0?fontsize=14&hidenavigation=1&theme=dark)

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
