### ISSUE TITLE
Please export the default sensors from the npm package

### ISSUE THREAD

**Issue by nerdkid93** [atlassian/react-beautiful-dnd#1698]
### Description
I am creating a drag-and-drop interaction where the end users will either use a mouse or a touch screen. Keyboard/screenreaders have a different interaction where they get to click the destination lists to move the item from the starting position to the ending position. I would like a way to basically just implement the 2 sensor APIs that I want, while leaving the Keyboard sensor API effectively disabled. But I can't do that the way the NPM package is published. The sensor hooks are not part of the export, and there isn't a way to import them from a standalone file either.

e.g. `<DragDropContext sensors={[useMouseSensor, useTouchSensor]} enableDefaultSensors={false} />`

**Comment by alexreardon** [comment]
Sounds good to me! Maybe we don't need `enableDefaultSensors` anymore if we just export the default sensors 🤔

**Comment by nerdkid93** [comment]
I can make a PR for the additional exports, but I'm not sure what it should look like if `enableDefaultSensors` is to be removed

**Comment by alexreardon** [comment]
don't worry about `enableDefaultSensors` for now, we can just export the sensors 👍

**Comment by alexreardon** [comment]
PR welcome!
