### ISSUE TITLE
api.tryReleaseLock does not abort an existing drag

### ISSUE THREAD

**Issue by nerdkid93** [atlassian/react-beautiful-dnd#1699]
### Expected behavior
I'd expect `useKeyboardSensor` to reset the lock state when it aborts before it can call `api.drop()` on a `Droppable`, or phrased another way, I'd expect to be able to `tryGetLock` after having successfully called `tryReleaseLock` on the sensorApi.

### Actual behavior
`useKeyboardSensor` only cleans up it's event handlers but doesn't reset the state of the `DragDropContext` so nothing can get drag-and-dropped until you either refresh or force re-render the parent component.

### Steps to reproduce
Make a `<DragDropContext sensors={[useNoKeyboardSensors]} />` where `useNoKeyboardSensors` is the following hook:
```javascript
function useNoKeyboardSensors( api ) {
	const abortKeyboardSensor = useCallback( ( e ) => {
		if ( ![" ", "Spacebar" ].includes( e.key ) ) {
			return;
		}

		const draggableId = api.findClosestDraggableId( e );
		if ( !draggableId ) {
			return;
		}

		const canLock = api.canGetLock( draggableId );
		if ( !canLock ) {
			api.tryReleaseLock();
		}

		const preDrag = api.tryGetLock( draggableId );
		if ( preDrag !== null ) {
			// unreachable code as of `rbd@12.2.0`
			preDrag.abort();
		}
	}, [api]);

	useEffect(() => {
		window.addEventListener( 'keydown', abortKeyboardSensor );
		return () => window.removeEventListener( 'keydown', abortKeyboardSensor );
	}, [abortKeyboardSensor]);
}
```

### Suggested solution?
I'm not sure I have any ideas for a good solution to this problem :disappointed: 

### What version of `React` are you using?
16.11.0

### What version of `react-beautiful-dnd` are you running?
12.2.0

### What browser are you using?
Both Chrome Dev and Chrome Stable (v79 and v80)

### Demo
https://codesandbox.io/s/vertical-list-c6fod

**Comment by alexreardon** [comment]
I think we will fix your issue by allowing you to disable the keyboard sensor. But i think it is also worth looking into the issue you are experiencing too

**Comment by alexreardon** [comment]
I'm struggling to wrap my head around this:

> I'd expect useKeyboardSensor to reset the lock state when it aborts before it can call api.drop() on a Droppable, or phrased another way, I'd expect to be able to tryGetLock after having successfully called tryReleaseLock on the sensorApi.

Can you please phrase it another way?

**Comment by alexreardon** [comment]
I can see the issue.

If a lock is forcefully aborted using api.tryReleaseLock and there is an active drag; that drag is not aborted (just the sensor lock is releases)

I should have a fix up soon
