### ISSUE TITLE
Information about the drop target

### ISSUE THREAD

**Issue by oyeanuj** [atlassian/react-beautiful-dnd#17]
Hi @alexreardon, this library looks great - thank you for putting it out! I have a usecase where on drop, I'd like to distinguish between if the item was dropped between two items or on top of an item. 

So, I am wondering if you foresee the API supporting that, and/or boundaries within a target (that helps determine intent of drop - like middle 50% is considered dropping on the target)?

Thank you!

**Comment by alexreardon** [comment]
This would be a useful feature for 'grouping'. However, it is not on the current roadmap. There are a lot of other features I want to ship before this one. It may not even have a place in the library depending on some investigation. There would need to be a good amount of work on our end to see what this would look like and would probably require running the Droppable in a different mode.

I am keen to look at this - but as mentioned - it is not a priority right now. I will close this issue for now and look at it in the future.

Thanks for reaching out @oyeanuj !

**Comment by oyeanuj** [comment]
@alexreardon Just wanted to loop back in to see if how your thoughts have evolved on this issue given all the big changes to the library?

Again my usecase is to be able to distinguish between something dropped on top of an item vs between two items. And I'm wondering how might that be done best with this library?

Thanks for all your work on it!

**Comment by oyeanuj** [comment]
@alexreardon Just wanted to check to see if you had any thoughts here?

**Comment by alexreardon** [comment]
Still no progress on this one at this point - but we *might* be looking at this problem in the coming months
