### ISSUE TITLE
Grabbing cursor icon

### ISSUE THREAD

**Issue by heymartinadams** [atlassian/react-beautiful-dnd#170]
## Bug or feature request?
Feature request

Might be nice for the cursor `onmouseover` to be set to `cursor: -webkit-grab;` and then to `cursor: -webkit-grabbing;` during dragging.

ps: excellent work, so grateful for it.

**Comment by alexreardon** [comment]
Hi @heymartinadams,

The library itself does not dictate what cursor you should use. You are welcome to set the cursor as you like in response to hooks and props

https://github.com/atlassian/react-beautiful-dnd#add-a-cursor-style-and-block-selection

**Comment by madarosca** [comment]
> Hi @heymartinadams,
> 
> The library itself does not dictate what cursor you should use. You are welcome to set the cursor as you like in response to hooks and props
> 
> https://github.com/atlassian/react-beautiful-dnd#add-a-cursor-style-and-block-selection

How can we do that?

**Comment by heymartinadams** [comment]
Sorry, @madarosca I haven’t interacted with this package since 2017/18 so I’m no longer up to speed on the particulars.

**Comment by OmarAl-Ayoubi** [comment]
@alexreardon 
can you give an example
