### ISSUE TITLE
Stuck on 11.0.5 due to new (broken?) collision detection

### ISSUE THREAD

**Issue by lvpro** [atlassian/react-beautiful-dnd#1700]
Within our product, I used the multi drag example shown here, which worked excellent up through 11.x: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

I made a slight modification to the example wherein items are selected by clicking them first, rather than holding down a control key.  Otherwise it's pretty much the same.

Starting with 12.x, the collision detection and item movement is really buggy.  The only change was bumping the dep.  Anyone else notice this?

11.0.5:
![11 0 5](https://user-images.githubusercontent.com/5854781/71934862-f7afa800-316a-11ea-920a-4f19608fda42.gif)

12.2.0:
![12 2 0](https://user-images.githubusercontent.com/5854781/71934869-fbdbc580-316a-11ea-854d-2f9b3414f9dc.gif)

**Comment by alexreardon** [comment]
have a look at your console. Are there any warnings being printed?

**Comment by alexreardon** [comment]
I suspect you are not adding the `droppableProvided.placeholder` to the list

**Comment by lvpro** [comment]
Thank you for your reply, Alex.  I do have the placeholder in place, and the only console warning is one regarding nested scroll containers, which also existed on 11.x.

I now believe the issue is related to how we handle hidden items (note the "show all" box), which for whatever reason didn't manifest as an issue on 11.x (could be a difference in event order?).  I'll dig deeper and will either close this issue or submit an example project.

**Comment by alexreardon** [comment]
Here is our boilerplate: https://codesandbox.io/s/k260nyxq9v

If you can reproduce your issue there we would be happy to take a look for you

**Comment by lvpro** [comment]
The issue ended up being non-sequential indexes.  I erroneously failed to report the console warning to you when on 12.x.  This was noted in the changelog, so my fault (I had forgotten most of this part of our code even though I wrote it :-)).  

In 11.x, it let me get away with non-sequential indexes without any issue, which actually worked very well for hiding a subset of items within the list easily.  To do so in 12.x takes some extra gymnastics in tracking state, but I can swing it.

Thank you all for this awesome component.

**Comment by alexreardon** [comment]
I'm really glad you got to the bottom of your issue

**Comment by alexreardon** [comment]
> Thank you all for this awesome component

Thanks for the encouragement
