### ISSUE TITLE
Simple example, works on sandbox, doesn't on GatsbyJS (?)

### ISSUE THREAD

**Issue by kuworking** [atlassian/react-beautiful-dnd#1701]
I am trying to use the library with a GatsbyJS site, and I am having problems with the behavior

I was running out of ideas so I decided to ask here, and I made a sandbox version

https://codesandbox.io/s/using-react-beautiful-dnd-with-hooks-bfwzl?fontsize=14&hidenavigation=1&theme=dark

The surprise is that the code works well in the sandbox

And I am using the exactly same code in local, but within a GatsbyJS development

This is as simple as it can gets (the same code in `index.js` except for the pure React part), but once I move an item, if I try to move the same item I cannot, and get this warning 

![image](https://user-images.githubusercontent.com/4474004/71966402-c930dc00-3201-11ea-83f1-4b99fbc418ed.png)

I can do a github repo if useful, but before I wanted to ask whether it is something known or if there's something I'm missing here

Thanks,

**Comment by kuworking** [comment]
Closing it, it is solved by moving the components inside the app

From

```js
  const Columns = ({ arr }) =>
    arr.map((col, i) => (
      <Droppable droppableId={col.columnId} key={i}>
        {(provided, snapshot) => (
          <Ul ref={provided.innerRef}>
            <Elements arr={col.items} />
            {provided.placeholder}
          </Ul>
        )}
      </Droppable>
    ))

  const Elements = ({ arr }) =>
    arr.map((el, j) => (
      <Draggable draggableId={el.id} index={j} key={j}>
        {(provided, snapshot) => (
          <Li ref={provided.innerRef} {...provided.draggableProps} {...provided.dragHandleProps}>
            {el.text}
          </Li>
        )}
      </Draggable>
    ))

export default () => {
  const [elements, setElements] = useState(myElements)

  const onDragEnd = result => {
    const { destination, source, draggableId } = result
    console.log(result)

    if (!destination) return
    if (destination.droppableId === source.droppableId && destination.index === source.index) return

    const new_elements = reorder(elements, source.droppableId, destination.droppableId, source.index, destination.index)
    setElements(new_elements)
  }

  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Grid>
        <Columns arr={myElements} />
      </Grid>
    </DragDropContext>
  )
}
```

To 

```js
export default () => {
  const [elements, setElements] = useState(myElements)

  const onDragEnd = result => {
    const { destination, source, draggableId } = result
    console.log(result)

    if (!destination) return
    if (destination.droppableId === source.droppableId && destination.index === source.index) return

    const new_elements = reorder(elements, source.droppableId, destination.droppableId, source.index, destination.index)
    setElements(new_elements)
  }

  const Columns = ({ arr }) =>
    arr.map((col, i) => (
      <Droppable droppableId={col.columnId} key={i}>
        {(provided, snapshot) => (
          <Ul ref={provided.innerRef}>
            <Elements arr={col.items} />
            {provided.placeholder}
          </Ul>
        )}
      </Droppable>
    ))

  const Elements = ({ arr }) =>
    arr.map((el, j) => (
      <Draggable draggableId={el.id} index={j} key={j}>
        {(provided, snapshot) => (
          <Li ref={provided.innerRef} {...provided.draggableProps} {...provided.dragHandleProps}>
            {el.text}
          </Li>
        )}
      </Draggable>
    ))

  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Grid>
        <Columns arr={myElements} />
      </Grid>
    </DragDropContext>
  )
}
```

**Comment by alexreardon** [comment]
Thanks for sharing your experience for others to find if they hit the same issue 👍

**Comment by kuworking** [comment]
Hi @alexreardon, indeed now I find this behavior on one website I'm working on, and this is indeed problematic:

I am depicting a component called `<Card>` that is defined in a file where all types of Cards are defined

But I'm finding this sort-of-bug that react-beautiful-dnd cannot find the draggables (that have correct id's)

```
Unable to find draggable with id: post-6
```

So now I guess I'll have to define this type of Card in the same main component I'm defining the drag-n-drop stuff, which means the logic encapsulation is gone

If that's something you want to jump in, I'm more than happy to prepare a gatsby starter that can reproduce this behavior, in any case I need to say a big thanks for your work with this library :)

**Comment by kuworking** [comment]
I've prepared the repo, and actually it doesn't work even without the components issue that I've mentioned earlier

So in summary, I don't know why this code doesn't work (when running in Gatsby)

```
git clone https://github.com/kuworking/gatsby-beautiful-dnd
yarn
gatsby develop
```
 Visit `localhost:8000` and once you start moving the items you'll soon see warnings and non-working drag-n-drop experience

(you need NodeJS and run `npm install -g gatsby-cli` if it's your first gatsby site, https://www.gatsbyjs.org/tutorial/part-zero/)

**Comment by kuworking** [comment]
I may have solved it by changing this

```
{elements.map((col, i) => (
--    <Droppable droppableId={col.columnId} key={i}>
++    <Droppable droppableId={col.columnId} key={col.columnId}>
```

and

```
col.items.map((post, j) => (
--    <Draggable draggableId={post.id} index={j} key={j}>
++    <Draggable draggableId={post.id} index={j} key={post.id}>
```

Does it make sense?

**Comment by alexreardon** [comment]
using index as your key is a bad idea with react :)

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#keys-for-a-list-of-draggable-
