### ISSUE TITLE
onDrag Hook

### ISSUE THREAD

**Issue by djason-lv** [atlassian/react-beautiful-dnd#171]
On drag hook that would pass result object parameter similar to the onDragEnd hook, but the destination would the be destination if the user were to drop the item.

This would be beneficial to provide some kinda of real time validation of a drag.  For instance changing the cursor to `no-drop` or changing the dragging item's background to red, etc.

**Comment by alexreardon** [comment]
`Droppable` > `isDropDisabled` will disable the dropping but will not give you an opportunity to change the cursor as `snapshot.isDraggingOver` will not fire when it is disabled. I will need to do some more thinking about this one.

**Comment by alexreardon** [comment]
I have been thinking about this one and I think it is best to not go forward with it. This is with the understanding that it could be used to detect if you are over a disabled droppable.

Reasons:

- Doing this would be a significant change to a lot of internal logic that strip out disabled droppables from lots of calculations
- While this might be a useful hook for mouse dragging it does not really make sense for keyboard dragging where we really do not want to allow dragging over these disabled areas.

This sounds like a 'mouse only' dragging interaction - as such you *could* add your own `onmouseover` listener to the `Droppable` to add the invalid cursor when it is being dragged over (and an `onmouseleave` to go back when it leaves). This is not fool proof as we detect what `Droppable` you are over by using the center position of the `Draggable` and not the mouse position. However, it might get you where you want to go.

Cheers
