### ISSUE TITLE
Drag and Drop using Selenium in Java - The element get selected, but it does not move to the specified drop point and the Hold stays in loop

### ISSUE THREAD

**Issue by Poncheqa** [atlassian/react-beautiful-dnd#1718]
I have tried various options, but when the test runs, I see the element get selected, but it does not move to the specified drop point and the hold stays in loop, the element is not released until I move the mouse. URL the site: http://the-internet.herokuapp.com/drag_and_drop
See image:
![image](https://user-images.githubusercontent.com/60186596/72910855-bd174500-3cfe-11ea-8404-3449af5bca8c.png)

Here's how I defined the function in my latest attempt:

<code>
	public boolean waitAndDragAndDrop(WebElement from, WebElement to) 
        {
		try {
			if(waitForElementVisible(from) && waitForElementVisible(to)) {
				Actions act = new Actions(driver);
				act.dragAndDrop(from, to).build().perform();
				return true;
			}
			else
				return false;
			
		}catch (Exception e) {
			System.out.print("Error in the \"class: BasePage\" typeOnElement event:\n" + e);
			return false;
		}
	}
</code>

Also tried the following (same result), moving element slightly and then performing a drag operation (variations on this theme also tried and failed).

<code>
public boolean waitAndDragAndDrop(WebElement from, WebElement to) {

Actions act = new Actions(driver);

act.dragAndDrop(from, to).build().perform();

act.clickAndHold(from).perform();

act.pause(Duration.ofSeconds(1));

act.moveByOffset(10,0).perform(); 

act.moveToElement(to).perform();

act.moveByOffset(10,0).perform();

act.release();

act.build();

act.perform();

return true;
}
</code>

<code>
	Actions act = new Actions(driver);
	act.clickAndHold(from)
	.moveByOffset(-10, 0)
	.moveToElement(to)
	.release()
	.perform();
</code>

The elements are identified using id:

<code>
@FindBy(id = "column-a")
private WebElement box_A;

@FindBy(id = "column-b")
private WebElement box_B;
</code>

See image:
![image](https://user-images.githubusercontent.com/60186596/72915822-8ba27780-3d06-11ea-93d3-f2603f40b904.png)

Thanks in advance.

**Comment by alexreardon** [comment]
I personally use keyboard instructions as they are easier to get right for these types of tests.

1. focus on element
2. spacebar to lift
3. move with arrow key
4. spacebar to drop

If you did want to use mouse here is some sudo code:

1. mouse down on the element
2. move the mouse 5px in any direction (this will start the drag)
3. move the element where you want to with mousemove
4. mouseup

**Comment by alexreardon** [comment]
Let me know how you go

**Comment by Poncheqa** [comment]
> 
> 
> Let me know how you go

Thank you

**Comment by Poncheqa** [comment]
> I personally use keyboard instructions as they are easier to get right for these types of tests.
> 
> 1. focus on element
> 2. spacebar to lift
> 3. move with arrow key
> 4. spacebar to drop
> 
> If you did want to use mouse here is some sudo code:
> 
> 1. mouse down on the element
> 2. move the mouse 5px in any direction (this will start the drag)
> 3. move the element where you want to with mousemove
> 4. mouseup

I also tried to move the element slightly and then perform a drag operation (variations on this issue were also tested failed). I tried to use the Actions class to move the element, the element is selected but it does not move; I have also noticed that when the "moveToElement" method of the Actions class is used, the mouse does not move to the element indicated by parameter.

<code>
new Actions(driver)
                .moveToElement(from).perform();
<code/>

All code
<code>
				new Actions(driver)
                .moveToElement(from)  	//Moves the mouse to an offset from the top-left corner of the element.
                .pause(Duration.ofSeconds(1))
                .clickAndHold(from)   	//Clicks (without releasing) in the middle of the given element.
                .pause(Duration.ofSeconds(1))
                .moveByOffset(1, 0)		//Moves the mouse from its current position (or 0,0) by the given offset.
                .moveToElement(to)
                .moveByOffset(1, 0)
                .pause(Duration.ofSeconds(1))
                .release();		//Releases the depressed left mouse button at the current mouse location.
<code/>

Then I thought about using the Robot class to move the mouse over the element; but when using the "clickAndHold" method it stays in loop.

<code>
				Actions act = new Actions(driver);
				Robot robot = new Robot(); 
				int xFrom = from.getLocation().x; 
				int yFrom = from.getLocation().y; 
				int xTo = to.getLocation().x; 
				int yTo = to.getLocation().y; 
				robot.mouseMove(xFrom + 50, yFrom + 150);//Move the mouse over the element
				act.clickAndHold(from).moveByOffset(xFrom + 50, yFrom + 150).pause(Duration.ofSeconds(1)).perform(); // :v Stays in loop
				act.moveToElement(to).perform(); //Method for performing the actions without calling build() first.
				robot.mouseMove(xTo + 50, yTo + 150); //Move the mouse to 'To' element
				act.release(to).build(); //RELEASE -> Releases the depressed left mouse button, in the middle of the given element. BUILD -> Generates a composite action containing all actions so far
<code/>

Find out how to do it in javascript and the following code worked for me:
<code>
				JavascriptExecutor js = (JavascriptExecutor) driver;
				js.executeScript("function createEvent(typeOfEvent) {\n"
						+ "var event = document.createEvent(\"CustomEvent\");\n"
						+ "event.initCustomEvent(typeOfEvent,true, true, null);\n" + "event.dataTransfer = {\n"
						+ "data: {},\n" + "setData: function (key, value) {\n" + "this.data[key] = value;\n" + "},\n"
						+ "getData: function (key) {\n" + "return this.data[key];\n" + "}\n" + "};\n"
						+ "return event;\n" + "}\n" + "\n" + "function dispatchEvent(element, event,transferData) {\n"
						+ "if (transferData !== undefined) {\n" + "event.dataTransfer = transferData;\n" + "}\n"
						+ "if (element.dispatchEvent) {\n" + "element.dispatchEvent(event);\n"
						+ "} else if (element.fireEvent) {\n" + "element.fireEvent(\"on\" + event.type, event);\n"
						+ "}\n" + "}\n" + "\n" + "function simulateHTML5DragAndDrop(element, destination) {\n"
						+ "var dragStartEvent =createEvent('dragstart');\n"
						+ "dispatchEvent(element, dragStartEvent);\n" + "var dropEvent = createEvent('drop');\n"
						+ "dispatchEvent(destination, dropEvent,dragStartEvent.dataTransfer);\n"
						+ "var dragEndEvent = createEvent('dragend');\n"
						+ "dispatchEvent(element, dragEndEvent,dropEvent.dataTransfer);\n" + "}\n" + "\n"
						+ "var source = arguments[0];\n" + "var destination = arguments[1];\n"
						+ "simulateHTML5DragAndDrop(source,destination);", from, to);

<code/>


However, I will try to use your recommendation (use the keyboard instructions) and then publish my results.

Thank you for reply.

**Comment by mikkopori** [comment]
Anyone looking for Selenium python code sample here is what I used to make this work as per suggestion by @alexreardon:

`   action = ActionChains(driver)
    for i in range(20):
        action.send_keys(Keys.TAB)
    action.send_keys(Keys.SPACE)
    action.send_keys(Keys.ARROW_RIGHT)
    action.send_keys(Keys.SPACE)
    action.perform()
`

Also spent half a day in vain trying other other solutions that might work so I recommend anyone looking to implement with keys and be done with it :)

**Comment by danieldelcore** [comment]
Will close this for now since it seems to be resolved!

**Comment by hsuraweera** [comment]
This is what I used.
`Actions actions = new Actions(driver);
actions.clickAndHold(FromElement)
                    .moveByOffset(0, startingYOffset)
                    .moveToElement(ToElement, 0, startingYOffset)
                    .release().build().perform();`

**Comment by hsuraweera** [comment]
This is what I used.
`Actions actions = new Actions(driver);
actions.clickAndHold(FromElement)
.moveByOffset(0, startingYOffset)
.moveToElement(ToElement, 0, startingYOffset)
.release().build().perform();`
