### ISSUE TITLE
Touch doesn't drag card but block in nested vertical list (Android only)

### ISSUE THREAD

**Issue by ThomasJuster** [atlassian/react-beautiful-dnd#173]
## Bug or feature request?
Bug

### Expected behavior
In this [example](https://react-beautiful-dnd.netlify.com/?selectedKind=complex%20vertical%20list&selectedStory=nested%20vertical%20lists&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) in the `second level` block, the user should be able to drag and drop the cards using touch.

### Actual behavior
Using touch drags the whole `second level` block rather than just the card.

### Steps to reproduce
Go to [this doc page](https://react-beautiful-dnd.netlify.com/?selectedKind=complex%20vertical%20list&selectedStory=nested%20vertical%20lists&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) with your phone (or Chrome in mobile mode) and try to swap the two cards in the `second level` block

### Browser version

Android: Chrome 62.0.3203.84
Computer: Chrome 62.0.3202.89 (Official Build) (64-bit)

**Comment by alexreardon** [comment]
Super strange. It only seems to be the case on android. It works as expected on iPhone. Must have something to do with how it publishes events. Super surprising that the outer element event handler gets called before the inner one

**Comment by alexreardon** [comment]
We now prevent the propagation of the touchstart event while being careful to not call prevent default so as to maintain as much standard browser behaviour as possible

**Comment by humphreybc** [comment]
@alexreardon I bumped the version to 2.6.1 just now. I've been playing around on our staging environment and I'm running into this issue—so thanks for fixing—but I also can't scroll on the list anymore. Is this all related to this issue?

**Comment by alexreardon** [comment]
Thanks for raising this @ThomasJuster.

Not sure @humphreybc. I am about to do a new release. Please check against that or master. If you are still having issues please raise a seperate issue - cheers 👍

**Comment by alexreardon** [comment]
@humphreybc done.

Also, regarding scrolling - take a look at this: https://github.com/atlassian/react-beautiful-dnd/tree/v2.6.2#opting-out-of-native-scrolling

**Comment by humphreybc** [comment]
@alexreardon Thanks! Read through that and opened up an issue.
