### ISSUE TITLE
NotFoundError: Node was not found

### ISSUE THREAD

**Issue by dogofpavlov** [atlassian/react-beautiful-dnd#1758]
I am getting this error in my application and have no idea what it could be.... if I comment out the DND component my app no longer has the error.

### Actual behavior
I am getting this error in my app when I unmount the component.  Oddly enough... the code sample I followed to setup the component (https://codesandbox.io/s/k260nyxq9v)  in my app seems to also have the error... even weirder though... the code sample will reproduce the error if I simply type 1 letter/character/space/return.

I am hoping whatever the error is can help me track down why its also occurring in my app.

### Steps to reproduce 
Visit the URL to the sample code provided here https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/examples.md .. specifically this one... https://codesandbox.io/s/k260nyxq9v

open up the code editor and type 1 space. 

### Suggested solution?
I have no idea what is happening.

### What version of `React` are you using?
16.12

### What version of `react-beautiful-dnd` are you running?
12.2.0

### What browser are you using?
FIrefox

### Demo
LIterally just type a space into the code editor here: https://codesandbox.io/s/k260nyxq9v

**Comment by dogofpavlov** [comment]
anyone? Just literally type a space into the code of the link that shared all across the docs... there's just NO WAY I'm the only person.

**Comment by alexreardon** [comment]
Looks like it might be an issue with the sandbox. Try this one (i just bumped the deps): https://codesandbox.io/s/k260nyxq9v

**Comment by dogofpavlov** [comment]
This new URL does the same thing. It also gives the error. 

 The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.
