### ISSUE TITLE
Update version for react-motion to 0.5.2

### ISSUE THREAD

**Issue by nassimbenkirane** [atlassian/react-beautiful-dnd#177]
Hello,
Thanks for this awesome library !

When I use react-beautiful-dnd with react 16, I am getting an error from react-motion :
`react-motion@0.5.0" has incorrect peer dependency "react@^0.14.9 || ^15.3.0`

react-motion 0.5.2 has updated it's peer dependencies to "react": "^0.14.9 || ^15.3.0 || ^16.0.0" so upgrading to it in the beautiful-dnd's peer dependencies to '0.5.2' should remove the warnings

**Comment by alexreardon** [comment]
We cannot do this until we bump to the latest flow as 0.5.1 is incompatible with our current version. I hope to do that soon. #113
