### ISSUE TITLE
Error when running rbd with next.js (server side rendering)

### ISSUE THREAD

**Issue by AndysonDK** [atlassian/react-beautiful-dnd#1775]
### Expected behavior

react-beautiful-dnd should run without warnings and errors when using SSR with next.js

### Actual behavior

Receiving the following errors when trying to run react-beautiful-dnd with next.js:

![image](https://user-images.githubusercontent.com/28491857/76127690-a143d600-6002-11ea-8b82-263ee49478e1.png)

As you can see, I'm calling
`resetServerContext();`
Which according to other issues should resolve the problem with the client, server id mismatches when using SSR.
But it's not resolved for me sadly.

Does anyone know a solution or a tip?

### Steps to reproduce

Install the next.js, react-beautiful-react-dnd, react versions that I'm using
Follow this tutorial: https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd

In this tutorial the attribute innerRef is being used. Don't use it. Instead use the ref attribute!

### What version of `react-beautiful-dnd` and `react` are you running?

I'm using the following dependencies (listed in my package.json file):

![image](https://user-images.githubusercontent.com/28491857/76128087-a2c1ce00-6003-11ea-80be-c8b5651aa574.png)

### What browser are you using?

Chrome Version 80.0.3987.132 (64 bit) (latest version)

**Comment by alexreardon** [comment]
https://nextjs.org/docs/advanced-features/custom-document

It looks like you are using a different API to what is suggested^


Did you try this API?
https://nextjs.org/docs/advanced-features/custom-document#customizing-renderpage

**Comment by tettoffensive** [comment]
@AndysonDK What did you end up doing for this? I _think_ I'm following the api, but I'm still getting the error.  

I'm new to next so I must not be understanding something. @alexreardon I'm also using emotion, so I'm trying to merge examples. Am I missing something?

**Here's what my _document.tsx looks like:**
```ts
import Document, { Head, Main, NextScript } from 'next/document';
import { extractCritical } from 'emotion-server';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const page = ctx.renderPage();
    const styles = extractCritical(page.html);
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps, ...page, ...styles };
  }

  render() {
    return (
      <html lang="en-US">
        <Head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <style data-emotion-css={this.props.ids.join(' ')} dangerouslySetInnerHTML={{ __html: this.props.css }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by AndysonDK** [comment]
@tettoffensive Actually I gave up on this, I didn't end up with a solution in the end, sorry 😕
Hope you can solve this!

**Comment by AshwinTayson** [comment]
@tettoffensive Did u fix this issue?

**Comment by Revolt9k** [comment]
still actual :(

**Comment by spenweb** [comment]
This solution on StackOverflow worked for me in addition to the comment to disable React strict mode:
https://stackoverflow.com/a/64242579/6010889
