### ISSUE TITLE
onDragEnd 经常性不执行

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [atlassian/react-beautiful-dnd#1784]
onDragEnd在拖动结束时 会不执行，特殊情况 在浏览器有滚动条的情况下发生

**Comment by Junzibuzhengyibuqi** [comment]
message: "Invariant failed"

**Comment by Junzibuzhengyibuqi** [comment]
Invariant failed: Cannot find draggable entry with id [1909]"  为什么变成了数组

**Comment by Bubblex** [comment]
请问怎么解决的

**Comment by Junzibuzhengyibuqi** [comment]
我记得好像是嵌套滚动条了，多层滚动条导致的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "atlassian/react-beautiful-dnd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 上午9:22
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [atlassian/react-beautiful-dnd] onDragEnd 经常性不执行 (#1784)





 
请问怎么解决的
