### ISSUE TITLE
Typescript in "invariant.js"

### ISSUE THREAD

**Issue by Davenporten** [atlassian/react-beautiful-dnd#1787]
I'm sorry if this is stupid question, but I've been Googling this for awhile now and cannot figure it out. `invariant.js` is used throughout beautiful-dnd. It's clearly ts in a .js file. Does this get transpiled somewhere. I have been trying to work with it and get the error 

>./node_modules/react-beautiful-dnd/src/invariant.js
>SyntaxError: C:\Users\RClinto\merlin_proto\Falcon2-Webapp-Prototype\node_modules\react->beautiful-dnd\src\invariant.js: Unexpected token (3:18)
>
>  1 | // @flow
>  2 | /* eslint-disable no-restricted-syntax */
> 3 | const isProduction: boolean = process.env.NODE_ENV === 'production';
>    |                  ^
>  4 | const prefix: string = 'Invariant failed';
>  5 | 
>  6 | // Want to use this:

I couldn't get things to format correctly, but the carrot is pointing at the `:`. 

Any help would be much appreciated. Thanks in advance!

**Comment by tarjei** [comment]
@Davenporten did you find a solution?

**Comment by Davenporten** [comment]
@tarjei Unfortunately no, I ended up moving to another lib: https://www.npmjs.com/package/muuri-react

**Comment by tarjei** [comment]
@alexreardon I do not think this issue should be closed. IMHO there needs to be an explanation in the Readme wrt to the src files of the project and the need for a typescript interprenter to use rbd.

**Comment by tarjei** [comment]
Also: Downgrading to 11.0.5 is a workaround for now.
