### ISSUE TITLE
Object doesn't support property or method 'repeat' and 'table'

### ISSUE THREAD

**Issue by TijsDeBelie** [atlassian/react-beautiful-dnd#1797]
### Expected behavior
Supported browser IE11
### Actual behavior
Hard crash (white page) after dragging an element, element is also not moved to the correct position (resets to default position).

Logs these errors in console while using polyfills for IE 11:  
Object doesn't support property or method 'table'
Object doesn't support property or method 'repeat'

### Steps to reproduce
Drag item to another location in a droppable zone and drop it. 

### Suggested solution?
Some sort of polyfill? 

### What version of `React` are you using?

"react": "16.12.0"

### What version of `react-beautiful-dnd` are you running?

"react-beautiful-dnd": "^13.0.0"

### What browser are you using?
IE 11

**Comment by alexreardon** [comment]
We are using none of those in the codebase. We recently moved from We have moved from @babel/runtime-corejs2 to @babel/runtime: https://github.com/atlassian/react-beautiful-dnd/releases/tag/v13.0.0

Previously we were accidentally polyfilling. We are no longer doing so. I suspect that you where unknowingly relying on our polyfilling

**Comment by alexreardon** [comment]
I have closed this as I cannot find any uses of .table or .repeat in our source
