### ISSUE TITLE
provided.innerRef has not been provided with a HTMLElement.

### ISSUE THREAD

**Issue by erganmedia** [atlassian/react-beautiful-dnd#1812]
Hi,

first of all here is a sandbox of my code -> [here](https://codesandbox.io/s/zen-forest-yqs4z?file=/src/App.js)

I sticked with the egghead tutorial and tried to play around with react-beautiful-dnd.
I have no idea why but I always get following error:

`provided.innerRef has not been provided with a HTMLElement.`

do you guy know why?..

**Comment by adenisovgit** [comment]
Just use "ref" instead of "innerRef" prop:
```
          <div ref={provided.innerRef} {...provided.droppableProps}>
```

**Comment by danieldelcore** [comment]
Hey @erganmedia, thanks for raising the issue. Does the above suggestion fix it for you? 

BTW, it looks like the codesandbox you provided is empty. If you're still stuck, would you be able to provide another one and we can then look into it.

**Comment by fbfdsouza** [comment]
> Just use "ref" instead of "innerRef" prop:
> 
> ```
>           <div ref={provided.innerRef} {...provided.droppableProps}>
> ```

can't believe it I had the same issue and it was so simple to fix it... thanks buddy

**Comment by danieldelcore** [comment]
Looks like this issue has been resolved 😄 

Will close for now, but feel free to reopen if you're still experiencing this issue
