### ISSUE TITLE
Need more maintainers

### ISSUE THREAD

**Issue by chuckWu1989** [atlassian/react-beautiful-dnd#1819]
Hi, folks. Thanks for author and maintainers given us so wonderful dnd library.

I like this library very much. It solved my pains in my project. However, I found there are so many issues and PR waiting for CR. If we can add some maintainers?

It's a suggestion. I'm not sure if it is a feature... If it's wrong, please let me know, thanks. 🙏

**Comment by danieldelcore** [comment]
Thanks for raising this issue, will close this one for now since it's a duplicate of [this ticket](https://github.com/atlassian/react-beautiful-dnd/issues/2037). Please feel free to join the discussions there!
