### ISSUE TITLE
Drag and Drop causes form elements to lose value

### ISSUE THREAD

**Issue by FatehAK** [atlassian/react-beautiful-dnd#1824]
Describe the bug
I am facing an issue with react-beautiful-dnd when used alongside a form library (react-hook-form). I am trying to achieve drag and drop with field arrays. But there is an issue that while dragging and dropping the field array loses its value.

1. Go to 'https://codesandbox.io/s/modern-shape-6v9d6?file=/src/App.js'
2. Drag first point down to the second point
3. Click on the debug button which calls getValues()
4. You can see that the 0th element of the Field Array has lost the Address key

Codesandbox link (Demo)
https://codesandbox.io/s/modern-shape-6v9d6?file=/src/App.js

Expected behavior
Field key should not get removed after drag and drop completed.

**Comment by dineshu07** [comment]
Hi, I am also facing the same issue. When we have form as draggable items then we will get issue.

**Comment by ravgeetdhillon** [comment]
@FatehAK Were you able to solve this issue?
