### ISSUE TITLE
Styling not preserved while dragging

### ISSUE THREAD

**Issue by maltebaer** [atlassian/react-beautiful-dnd#1829]
### Expected behavior
- Being able to make a table with draggable rows using `react-beatiful-dnd`
- Using `<tbody` as a child of `<Droppable>`
- Using `<tr>` as a child of `<Draggable>`
- Dragging a row will preserve styling, e.g. width of `<td>`

### Actual behavior
- When draging a row the width of the cells collapse to minimum instead of spaning the whole table width.

### Steps to reproduce
- Modify example of vertical list from docs (https://codesandbox.io/s/k260nyxq9v) to render a table

### What version of `React` are you using?

- `16.13.1`

### What version of `react-beautiful-dnd` are you running?

- `13.0.0`

### What browser are you using?

- Brave `V1.8.86`
- Firefox `75.0`

### Demo

https://codesandbox.io/s/table-with-react-beautiful-dnd-k7xrj

**Comment by maltebaer** [comment]
Never mind, just found the extensive documentation about tables (https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md) and your provided solutions.

**Comment by jgozal** [comment]
@maltebaer how did you fix this? The proposed solutions in the docs didn't work for me (or maybe I misunderstood them..)

**Comment by maltebaer** [comment]
Hey @jgozal 👋🏽 It didn't work "out of the box" for me, but after applying dimension locking, as described in this example [https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md#strategy-2-dimension-locking](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md#strategy-2-dimension-locking), everything looked nice again.

**Comment by adamhrdsy** [comment]
@maltebaer Hi, I'm really trying to get this off the ground but the dimension locking is not working for me. Could you help us out with some example code please? Thank you in advance.

**Comment by maltebaer** [comment]
Hey guys, I've updated my demo from above to make use of dimension locking. You can find the code here: [https://codesandbox.io/s/table-with-react-beautiful-dnd-with-dimension-locking-gx0r2?file=/src/App.js](https://codesandbox.io/s/table-with-react-beautiful-dnd-with-dimension-locking-gx0r2?file=/src/App.js).

But basically I just followed the example from the Storybook (this is the underlying code: [https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/table/with-dimension-locking.jsx](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/table/with-dimension-locking.jsx)) but passed the `isDragging` value via props and not context.
