### ISSUE TITLE
[help] wrong position in vertical list when dragging top item in v6.0.2

### ISSUE THREAD

**Issue by ilp64** [atlassian/react-beautiful-dnd#1830]
I am using v6.0.2 version react-beautiful-dnd in an old react 15 project.
Check the vertical sort list demo, when dragging top item, the bottom item will over the top item. In v7.0.0, there is no such bug.
![](https://img.alicdn.com/tfs/TB1C.ezE.Y1gK0jSZFCXXcwqXXa-784-1534.jpg)

I want fork this repo and make a custom build from v6.0.2 to fix this bug, but I don't know how to resolve this problem. Can someone give me some tips?

v6.0.2 demo
[https://codesandbox.io/s/vertical-list-8y3u5?file=/index.js](https://codesandbox.io/s/vertical-list-8y3u5?file=/index.js)

v7.0.0 demo
[https://codesandbox.io/s/vertical-list-3s7uq?file=/index.js](https://codesandbox.io/s/vertical-list-3s7uq?file=/index.js)

**Comment by ilp64** [comment]
Sorry, I found `placeholder` usage.

**Comment by elva329** [comment]
> Sorry, I found `placeholder` usage.

Hi, I may have encountered the same issue as yours. Could you please explain that usage you have found for the placeholder, thank you.
