### ISSUE TITLE
Can I use Droppables to simulate a Y Axis

### ISSUE THREAD

**Issue by Radzell** [atlassian/react-beautiful-dnd#1836]
### Description
I wanted to ask if there is a way of adding 10 droppables to 10 columns each and using whether this droppable as a way of figure out a Y-axis for dropping draggable. I was thinking of a workaround to a problem I was having.

My client wants to drag in a column but also to make swim lanes so that you can align items across columns. Can this be done?

**Comment by alexandrutasica** [comment]
Do you want to have a grid structure? Check this example: https://codesandbox.io/s/-w5szl 
The droppable's are in columns. If you want to have a grid, using flex-box or some custom CSS you can limit the number of columns per row. Don't forget to set min-height for each row.

**Comment by Radzell** [comment]
I fixed it by using multiple droppables to make columns if anyone wants to know how it works it worked pretty well.
<img width="915" alt="Screen Shot 2020-06-06 at 6 03 25 PM" src="https://user-images.githubusercontent.com/264775/83959046-01c6f700-a82e-11ea-9d26-0dd56ef0f379.png">
