### ISSUE TITLE
Disabling keyboard shortcuts

### ISSUE THREAD

**Issue by arnarthor** [atlassian/react-beautiful-dnd#185]
## Bug or feature request?
Feature request

Can I somehow disable keyboard shortcuts? I'm using this on an element that has inputs as well and now I can't type spaces in the text input anymore because dnd grabs it first.

If this is not something you want to support feel free to close this, but I feel like it's pretty limiting to be forced to skip space interactions all together.

Otherwise great work on this library, it just works ™️ 🎉

**Comment by lukebatchelor** [comment]
If it helps, there is a section in the readme about draggables with interactive children.

 There is an example of patching the letdown handler and looking for a target of "input" that might help you.

**Comment by arnarthor** [comment]
Oh cool! Didn't see that one. I'll check that out, thanks!

**Comment by arnarthor** [comment]
That fixed it, thanks for pointing it out to me 👍
