### ISSUE TITLE
Margin top glitch on drop

### ISSUE THREAD

**Issue by ibraheemdev** [atlassian/react-beautiful-dnd#1855]
#### Expected behavior
![dndbug2](https://user-images.githubusercontent.com/34988408/83811337-9f33f680-a687-11ea-9b48-70a3c4078195.gif)
Usually the dropped card smoothly moves into place
#### Actual behavior
![dndbug](https://user-images.githubusercontent.com/34988408/83810990-fd140e80-a686-11ea-9cec-960f307b43c3.gif)
When moving to the top, the dropped card first directly above the card below, and then the top margin is applied
#### Steps to reproduce
Create list with each card having a `margin top` of 2, and `:first margin-top` of 0

**Comment by redline-gh** [comment]
I fixed this my changing the margin to a margin bottom on the list title, but is that the only way to solve this issue?

**Comment by ZacharyKearns** [comment]
I had the same issue and fixed it by making sure the margin was applied to the component receiving the draggable and draghandle props and not any of it's children
```typescript
function CardContainer(props: Props) {
  return (
    <div
      {...props.draggableProps}
      {...props.dragHandleProps}
      ref={props.innerRef}
      className="mb-2"
    >
      {props.children}
    </div>
  );
}
```

**Comment by ali-farooq0** [comment]
Seeing the same issue. Had to resolve it by using padding instead of margins.

**Comment by ibraheemdev** [comment]
I think this is expected behavior, as adjusting the margin fixes it. I'm not sure any other action can be taken.

**Comment by rnowm** [comment]
We were able to find a fix for that issue, just replace:
´
<div
  ref={provided.innerRef}
  {...provided.draggableProps}
  {...provided.dragHandleProps}
>
  {render(item, index)}
</div>
´

with:

`
{(provided) =>
    React.cloneElement(render(item, index), {
      ref: provided.innerRef,
      ...provided.draggableProps,
      ...provided.dragHandleProps,
    })
}
`

**Comment by CubedEye** [comment]
You can solve this by creating the margin space using `:after` on the container element

```js
 <div
    ref={provided.innerRef}
    {...provided.draggableProps}
    {...provided.dragHandleProps}
    class="card-root"
  >
    {render(item, index)}
  </div>
  ```
  and
  ```css
  .card-root:after {
        display: block;
        content: " ";
        height: 5px; // Margin height
    }
 ```

**Comment by Anishali2** [comment]
use div with height outside of the draggable 

```
 <>
  <Draggable
        key={item.id}
        draggableId={item.id}
        index={index}
        >
    {(provid: any) => (
              <li
                   {...provid.draggableProps}
                   {...provid.dragHandleProps}
                   ref={provid.innerRef}
               >
             <item.component />
        </li>
      )}
   </Draggable>
  <div className="h-2" /> // here
</>

```
