### ISSUE TITLE
Invariant failed: Cannot find droppable entry with id xxxx

### ISSUE THREAD

**Issue by mdodge-ecgrow** [atlassian/react-beautiful-dnd#1867]
I'm running into this issue when I drag an object around quickly from one column to another multiple times.  I'm sure I'm doing this wrong, but what I'm trying to do is after the order gets dropped I want it to stay the same color as when it was being dragged for another 2 seconds so the user can easily identify which order they just dropped among all the orders.  So I have this code in my onDragEnd:
```
		// change the background color and fade back to blue
		setDroppedOrderID(theOrder.orderNumber);
		setTimeout(() => {
			setDroppedOrderID('');
		}, 2000);
```
I suspect the issue is arising when someone tries to drag that same order again before the 2 seconds is up.  I tried adding `setDroppedOrderID('');` to onDragStart, but I get an error stating something like 'cannot modify and object as it is being dragged'.

I'm using the droppedOrderID state variable in the class list of the actual order itself like so:
```
	<MyOrder
		id={orderNumber}
		className={`order size-${size} ${
			droppedOrderID === orderNumber ? ' dropped' : ''
		} ${palletLoc === 'OUTSIDE' ? 'outside' : ''}`}
```

I'm sure I'm doing something wrong and this probably isn't technically a bug.  But if anyone knows of a better way to do this, I'd love to hear it.

**Comment by jonah-cod** [comment]
just remove React.strictMode tag on your index.jsx/index.tsx file
