### ISSUE TITLE
Select tag doesn't work in draggable items

### ISSUE THREAD

**Issue by epicallan** [atlassian/react-beautiful-dnd#189]
## Bug or feature request?

Bug

### Expected behavior

I should be able to select dropdown options in a select tag with in a draggable item

### Actual behavior

I cant select dropdown options

### Steps to reproduce

Add a select tag with in a draggable item

### Browser version

chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Demo

Webpack bin demo: https://www.webpackbin.com/bins/-KzSfuwwfHyFbx2FNUEk

**Comment by lukebatchelor** [comment]
This section of the readme will likely help

https://github.com/atlassian/react-beautiful-dnd/blob/master/README.md#interactive-child-elements-within-a-draggable

**Comment by epicallan** [comment]
thanks @lukebatchelor
