### ISSUE TITLE
Improved default for child interactive elements

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#190]
Currently [we suggest monkey patching](https://github.com/atlassian/react-beautiful-dnd#interactive-child-elements-within-a-draggable) event handlers to block dragging on interactive elements. This was a simple technique based on the proposition that not many people would want interactive elements within their drag handles anyway. However, this has been a constant source of issues for the repo.

#189, #185, #149, #110 (there are probably others)

I propose that we block dragging on child interactive elements by default - with an ability to opt out. If a consumer does opt out they are still welcome to introduce their own monkey patching logic for more complex scenarios. I think this would help the library 'just work' for more people out of the box.

If the type of the `event.target` (the element actually interacted with - `event.currentTarget` is the one with the listener [more](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)) is one of the following nodes, then a drag is prevented by default:

- `input`
- `textarea`
- `select`
- `option`
- `button`

The consumer could opt out this by adding a prop to `Draggable`. Something like `disableInteractiveChildrenBlocking` (name pending 👍 ). They could then do monkey patching if they liked

**Comment by alexreardon** [comment]
Are there any other elements you think should be added to the list @seancurtis ?

**Comment by alexreardon** [comment]
It would be good to get your thoughts @jaredcrowe, @lukebatchelor

**Comment by bradleyayers** [comment]
Don’t forget `[contenteditable]`.

**Comment by lukebatchelor** [comment]
Thats brilliant.

How will it affect people with already patched methods? Their current logic would keep them opted out I suppose? 

What's your current way for making a breaking change like this? Could it be worth having a high level "feature flag" type of thing to make the entire behaviour opt in? So you could support both methods still?

My gut says no, but worth considering

**Comment by alexreardon** [comment]
People who have currently patched will not be affected more than others. I would prefer to not support that sort of forking as supporting both behaviours. Either we think it makes sense or not.

I am not 100% sure what type of version bump this should be.

**Comment by lukebatchelor** [comment]
Would have to be breaking right?people with interactive elements in draggables would suddenly break if they updated.

**Comment by alexreardon** [comment]
Technically perhaps - but the interactive element would not have worked as intended without monkey patching previously.

**Comment by alexreardon** [comment]
You could see it as fixing a bug with nested interactive elements

**Comment by lukebatchelor** [comment]
I definitely would not see it like that. :p

**Comment by seancurtis** [comment]
`optgroup`, `audio`, and `video` might be the only others that I'd add.

**Comment by alexreardon** [comment]
Great suggestion @seancurtis
