### ISSUE TITLE
Getting Error, when trying to init DND

### ISSUE THREAD

**Issue by trayan16** [atlassian/react-beautiful-dnd#1910]
`Hello, I am using that sample : https://codesandbox.io/s/k260nyxq9v?file=/index.js:1697-2782
But that error occurs. Looks like something connected to dragHandleProps, but I can't resolve it.

![image](https://user-images.githubusercontent.com/16117267/89713242-1430ee80-d99f-11ea-879d-5941d1d845bf.png)

This is my render : 
``
![image](https://user-images.githubusercontent.com/16117267/89713291-7be73980-d99f-11ea-8bf8-1e3738a262cf.png)

**Comment by danieldelcore** [comment]
Hi there, this is a very common issue where both the Draggable and droppable `provider` properties are named the same, so there is some ambiguity between them. Please rename provider so something else like `draggableProvider`

Closing for now, thanks
