### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by victorsmits** [atlassian/react-beautiful-dnd#1917]
```
Failed to compile.

./node_modules/react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context.jsx 2:21
Module parse failed: Unexpected token (2:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // @flow
> import React, { type Node } from 'react';
| import type { Responders, ContextId, Sensor } from '../../types';
| import ErrorBoundary from './error-boundary';


```

I got this error after installing the package and I can't figure out how to fix it

**Comment by aferrari94** [comment]
Hi @victorsmits,
Could you share the code where are you using the library? 

I encounter a similar error and I was opening a bug too but finally I discover that I was importing library components in the wrong way. Are you importing <DragDropContext> in the following way?

```javascript
import DragDropContext from "react-beautiful-dnd/src/view/drag-drop-context";
```

This is wrong and I fix my problem importing components in this way:

```javascript
import {DragDropContext, Droppable, Draggable} from "react-beautiful-dnd";
```

Let me know it is useful to solve your problem.
I hope so.

Regards,
Ale

**Comment by danieldelcore** [comment]
Closing this issue for now, please feel free to reopen if you're still having an issue.
