### ISSUE TITLE
Droppable Type different between onDragStart and onDragEnd

### ISSUE THREAD

**Issue by ouyangatang** [atlassian/react-beautiful-dnd#1923]
### Expected behavior
For nested Droppables within specific `div`s, I have the type set to the name of each `div` with a variable. I.e.: 

`<Droppable type={frameName}>` 

### Actual behavior
The type printed out `onDragStart` is different from the type printed out `onDragEnd`, and is incorrect. Thus, it's not recognizing the other Droppables with the same type. When I display the variables in the Droppable, it displays correctly, but the type printed out `onDragStart` contains the variable name of a different `div` on the page.

### What version of `React` are you using?
"^16.12.0"

### What version of `react-beautiful-dnd` are you running?
"^13.0.0"

### What browser are you using?
Chrome

**Comment by ouyangatang** [comment]
Turns out, the cause was that I had Droppables with the same Id (even though they were in different lists) -- saw on the [Identifiers](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/identifiers.md) page that they had to be unique even if they're in different lists! 

This was insanely hard to diagnose because it was affecting the Type and only in a specific case (onDragStart and not on onDragEnd) and only for some Droppables (and also wasn't throwing any errors!).

**Comment by davedash** [comment]
Might be worth raising a warning in the console if this happens.  I assume at onDragEnd it returns to it's parent Droppable and it gets the right type, but while in flight the query for the right Droppable picks the last one.
