### ISSUE TITLE
Mention this library seems unsupported

### ISSUE THREAD

**Issue by popey456963** [atlassian/react-beautiful-dnd#1926]
No PRs have been approved or issues answered for a while, you should let people know this package is unsupported on the front page.

**Comment by trevyn** [comment]
Yeah, it would definitely help to have a comment from @alexreardon addressing if Atlassian will assign someone else to maintenance or if we should start thinking about a fork or new external maintainer?

**Comment by danieldelcore** [comment]
https://github.com/atlassian/react-beautiful-dnd/pull/2035 should fix this 😄 
Thanks for your patience on this everyone, apologies about the lengthy delay. 

Planning to cut a release in the coming days 👍

**Comment by danieldelcore** [comment]
Hey @popey456963 👋 

I've just responded to a similar ticket: https://github.com/atlassian/react-beautiful-dnd/issues/2037
Will close this issue for now, please feel free to keep the conversation going there!
