### ISSUE TITLE
How do I achieve dragging in only one direction？

### ISSUE THREAD

**Issue by longhaha1998** [atlassian/react-beautiful-dnd#1927]
How do I achieve dragging in only one direction, such as only horizontally or only vertically？？？

**Comment by jamiebullock** [comment]
@longhaha1998 did you ever resolve this? I have the same question.

**Comment by longhaha1998** [comment]
> @longhaha1998 did you ever resolve this? I have the same question.

const getItemStyle = (isDragging, style) => {
  const overrideStyles = {};

  const currentTransformMatch = style && style.transform &&
      style.transform.match(/translate\((-?\d+)px,\s+(-?\d+)px\)/);
  if (currentTransformMatch) {
      console.log('overriding transform:', style && style.transform);
      const yTransform = parseInt(currentTransformMatch[2]);
      overrideStyles.transform = `translate(0, ${yTransform}px)`;
  }

  return {
    // some basic styles to make the items look a bit nicer
    userSelect: "none",
    padding: grid * 2,
    margin: `0 0 ${grid}px 0`,

    // change background colour if dragging
    background: isDragging ? "lightgreen" : "grey",

    // styles we need to apply on draggables
    ...style,
    ...overrideStyles
  };
};
