### ISSUE TITLE
Swipe on I pad , triggering drag start.

### ISSUE THREAD

**Issue by nodefiend** [atlassian/react-beautiful-dnd#193]
## Feature Request

Greetings !

I am using this library in a production application that is a kanban board with multiple scrollable columns, scrolls fine on desktop, but on Ipad , the columns are not scrolling at all :(

I read that we have to opt out of native scrolling , because it would mess up the ordering. But I was wondering , is there a way to delay drag start through monkey patching the drag handler ? That way we could delay the drag long enough to detect a swipe up on an i pad?

Sorry , if I my question is off, im sure im just lacking an understanding of the library , i have searched through the issues , and haven't found this mentioned.

ken

**Comment by alexreardon** [comment]
Right now there is no way to avoid blocking native scrolling. However, we are hoping to move to long press dragging which would make the behaviour you are talking about possible. You can follow the progress of that work here: #176 

Thanks for reaching out

**Comment by nodefiend** [comment]
thank you so much for the quick response ! your library has been immensely useful to our team!

**Comment by alexreardon** [comment]
Glad to hear @nodefiend. Check out the examples on master - they have the updated technique. We plan on doing a release early next week

**Comment by alexreardon** [comment]
It would be great to get a screen cast of our app on #164 👍

**Comment by nodefiend** [comment]
Let me contact our lead and ill see if that would be okay!
