### ISSUE TITLE
Dragging item to end of scrollable list glitches out

### ISSUE THREAD

**Issue by zachgibson** [atlassian/react-beautiful-dnd#1930]
# Expected behavior
Dragging item to very end of scrollable list works without any jitter.

### Actual behavior
Dragging item to very end of scrollable list jitters/glitches out.
![Screen Recording 2020-08-28 at 2 23 18 PM](https://user-images.githubusercontent.com/10658888/91608058-76479880-e93a-11ea-9893-81adef185991.gif)

### Steps to reproduce
Codesandbox reproduction: https://codesandbox.io/s/horizontal-list-forked-8y6yy?file=/index.js

### Suggested solution?
Not sure.

### What version of `React` are you using?
16.4.1

### What version of `react-beautiful-dnd` are you running?
10.0.0

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/s/horizontal-list-forked-8y6yy?file=/index.js

**Comment by zachgibson** [comment]
Updating React and ReactDOM to 16.13.1 and react-beautiful-dnd no longer contains this bug.

**Comment by natopedroso** [comment]
Im having that issue with react and react-dom 17.0.2
