### ISSUE TITLE
how to make SOrtable tree?

### ISSUE THREAD

**Issue by Alkaraawi-Ali-Husham-Shakir** [atlassian/react-beautiful-dnd#1959]
In the following sandbox I'm trying to create a sortable tree list but I have no idea how to drop children from parent to other parents
https://codesandbox.io/s/dnd-zjdjd?file=/src/App.js

**Comment by danieldelcore** [comment]
Hi there, thanks for raising an issue. Trees are currently not supported but we have an issue that discusses it here: https://github.com/atlassian/react-beautiful-dnd/issues/1547  Please feel free to jump into the discussion there!
