### ISSUE TITLE
Is there a readonly mode?

### ISSUE THREAD

**Issue by sabbiu** [atlassian/react-beautiful-dnd#1969]
### Description

I want to add a props `readonly` and I want it to stop me from performing any drag and drop actions. Is there a way I can achieve this?

**Comment by andrei9669** [comment]
`Draggable` has an optional prop called `isDragDisabled`
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#draggable-props

**Comment by sabbiu** [comment]
@andrei9669 Thanks! Totally missed it out.
