### ISSUE TITLE
Custom drag handle does not work as intended if draggable item contains an iframes.

### ISSUE THREAD

**Issue by itsakt** [atlassian/react-beautiful-dnd#1974]
### Expected behavior
Smooth dragging of item over list.
### Actual behavior
Item stops moving when mouse moves over iframe
### Steps to reproduce
https://codesandbox.io/s/vertical-list-forked-yid36
Try to drag second item and drop it on top of first. Dragged item stops moving as soon as your mouse reaches the iframe's border.
### What version of `React` are you using?
16.13.1

### What version of `react-beautiful-dnd` are you running?
13.0.0

### What browser are you using?
Edge

### Demo
https://codesandbox.io/s/vertical-list-forked-yid36

**Comment by itsakt** [comment]
Fixed it by setting `pointer-events` to `none`.

**Comment by MrPeak** [comment]
> pointer-events

Want to know where to do this! PLZ...

**Comment by itsakt** [comment]
@MrPeak You can do something like this.

````
 <div style={{ pointerEvents: dragStartStatus ? 'none' : 'initial' }}>
    <iframe ...
````

Keep track of status using `onDragStart` and `onDragEnd` events.
