### ISSUE TITLE
How do I use the library in this layout? Please help me

### ISSUE THREAD

**Issue by linxianxi** [atlassian/react-beautiful-dnd#1980]
![image](https://user-images.githubusercontent.com/47104575/96333521-0386ae00-109d-11eb-8905-b1e8f469f5c7.png)

**Comment by tannerPriest** [comment]
If you can give more context as to whats going on, it would help us out more as to what you're trying to accomplish. I have an idea from the picture but i dont know if your rearranging the photos or just dragging them to the upload block
