### ISSUE TITLE
Just to say thanks you

### ISSUE THREAD

**Issue by Axel-KIRK** [atlassian/react-beautiful-dnd#1983]
Sorry to let this here,

I just want to take time to thanks all your dev team : 
Your error message are the best I ever seen, it's short clear and understandable,
Your tutorial with "Component with inner ref working"  is well writing, I spend only like 30 min to get this beautiful drag and drop,
it should be applause !! 
Thanks!

**Comment by maddhruv** [comment]
Thanks a lot, @Axel-KIRK for appreciating 🤝
