### ISSUE TITLE
Select inside draggable does not work

### ISSUE THREAD

**Issue by on3iro** [atlassian/react-beautiful-dnd#199]
## Bug or feature request?
Bug

### Expected behavior
`<select>` inside `draggable` should work properly.

### Actual behavior
Nothing happens when I click on the select. Binding a handler to `onClick` actually fires, but
`onChange` does nothing (the select does not react in anyway).
I tried to stop propagation, but that did not help either.

### Steps to reproduce
Create a select element inside a draggable container.

### Browser version
FF Dev Edition 58

### Demo
https://www.webpackbin.com/bins/-KzyD9o_2bh5ns32FVps

**Comment by tobiasandersen** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/189

**Comment by on3iro** [comment]
Ah sorry. I was at work and wrote the issue in a hurry. I just skimmed open issues and did not see anything comparable.

**Comment by alexreardon** [comment]
This should be shipping today 🤘

**Comment by on3iro** [comment]
Great :)
