### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by AndreiBehel** [atlassian/react-beautiful-dnd#1993]
Dependency conflict happens when react-beautiful-dnd is added to a new react application

```
# npm resolution error report

2020-10-26T14:20:21.162Z

While resolving: project
Found: react@17.0.1
node_modules/react
  dev react@"^17.0.1" from the root project

Could not resolve dependency:
peer react@"^16.8.5" from react-beautiful-dnd@13.0.0
node_modules/react-beautiful-dnd
  react-beautiful-dnd@"^13.0.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

### Suggested solution?
Update dependencies

### What version of `React` are you using?

- React: 17.0.1

### What version of `react-beautiful-dnd` are you running?

- react-beautiful-dnd: 13.0.0

**Comment by trevyn** [comment]
This project is dead, see https://github.com/atlassian/react-beautiful-dnd/issues/1926

**Comment by danieldelcore** [comment]
https://github.com/atlassian/react-beautiful-dnd/pull/2035 should fix this 😄 

Thanks for your patience on this everyone, apologies about the lengthy delay. 

Planning to cut a release in the coming days 👍
