### ISSUE TITLE
Inverted Vertical Lists

### ISSUE THREAD

**Issue by nrankin18** [atlassian/react-beautiful-dnd#1994]
I have functioning vertical columns of fixed heights with items that can be dragged and dropped between them. However, I want the items to fall to the bottom of the list instead of float to the top. I created a column-reversed flexbox inside the Droppable component, but the animations from DND show the items going to the top before they appear at the bottom. Is there an easier way of doing this?
https://codesandbox.io/s/flightstrip-drrty?file=/src/components/bay.jsx
![striptest](https://user-images.githubusercontent.com/13542023/97370529-8bcb3700-1885-11eb-9575-aa30d6c54e63.gif)

**Comment by Android789515** [comment]
Having the same issue.
