### ISSUE TITLE
Support transitioning between lists

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#2]

**Comment by NotAmaan** [comment]
@alexreardon, is there a rough ETA on this?

**Comment by alexreardon** [comment]
We do not really work on ETA's - but we are starting work on this in the next week or two

**Comment by alexreardon** [comment]
Additional things that need to be considered for keyboard dragging:

- [ ] Do we allow transitioning with only a keyboard? I hope so
- [ ] We need to figure out which is the intended list the user wanted to go to
- [ ] Where do we insert the item into the list? The closest position or the top of the list. Regardless of approach, the item might actually be off the screen for the user so we will need to scroll to it if required
- [ ] Do we support looping? Ie when you get to the last list should it loop back around? I think no

There will surely be other questions. I'll add them here

**Comment by alexreardon** [comment]
Things are well underway for this one!

The result of a whiteboard session with @jaredcrowe

![2017-08-24 14 30 54](https://user-images.githubusercontent.com/2182637/29649878-81c8e542-88da-11e7-8974-52b946effb91.jpg)

**Comment by alexreardon** [comment]
The really hard part one about this one will be getting the keyboard story right. We are really sweating the details to make it work as naturally as possible

**Comment by dashed** [comment]
@alexreardon will there be support for moving between nested lists?

**Comment by alexreardon** [comment]
At this stage I will say no - we may look into it in the future though

**Comment by NotAmaan** [comment]
@alexreardon I would definitely vote for nested lists as well. I think the whole Drag and Drop behaviour is mostly used for Kanban boards (btw would be sick to see this being used in Trello) and UI/Page/Layout builders. The latter is what I use react-dnd for, can't wait to switch to react-beautiful-dnd though.

**Comment by alexreardon** [comment]
At this stage we are not targeting support for interacting Draggables between nested lists for the initial version of this. It adds a lot of complexity which will hold up us delivering this feature. We can look into the ability of transitioning between nested lists as a seperate issue in the future

**Comment by alexreardon** [comment]
Keep in mind that there will be support for dropping on lots of different Droppables - just not nested Droppables initially.

**Comment by alexreardon** [comment]
Some more thinking about how transitioning between lists with a keyboard will work

![2017-08-25 10 29 36](https://user-images.githubusercontent.com/2182637/29694705-8a369394-8981-11e7-95f0-e02d90590b3b.png)
![2017-08-25 10 29 28](https://user-images.githubusercontent.com/2182637/29694706-8a394b34-8981-11e7-8b07-55c2bd05b1d0.png)

**Comment by alexreardon** [comment]
Some things we still need to consider:

- [ ] When dragging over a droppable - nothing should move if it is not enabled. We will need to publish whether the droppable is enabled into the store
- [ ] Placeholder for new list to create space when needed
- [ ] Placeholder in source list should collapse if dropping in another list

**Comment by alexreardon** [comment]
Branch we are using for this feature: https://github.com/atlassian/react-beautiful-dnd/tree/moving-between-lists

**Comment by poryzhao** [comment]
when will be ready to support moving between nested lists?

**Comment by alexreardon** [comment]
We are looking at landing a whole range of features before looking into transitioning between nested lists

**Comment by alexreardon** [comment]
It might seem quiet - but we are busy at work with this one! I just had a break through today with keyboard dragging

**Comment by alexreardon** [comment]
![keyboard-transition-preview mov-scaled-0 2](https://user-images.githubusercontent.com/2182637/30049737-17d511c2-925f-11e7-84df-4b45073548b1.gif)

Making some great progress on keyboard transitioning (so hard!!!). The devil is in the details so there is a still a way to go - but getting closer

**Comment by alexreardon** [comment]
Still rough, but you can have a play with our work in progress [here](https://deploy-preview-73--react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=task%20board&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) 

Try using the keyboard - it is awesome.

Some of the examples are still a little wonky - still a work in progress

**Comment by hakunin** [comment]
@alexreardon very nice! One thing I could imagine being improved (outside of this PR) is that when the card isn't lifted, the card focus would move so that I can easily select a different one with arrow keys.

**Comment by alexreardon** [comment]
@hakunin you are welcome to add that on top of the library. You would need to patch the `onKeyDown` drag handle function and handle the arrow key actions yourself (while a drag is not occurring of course). 

When nothing is dragging `react-beautiful-dnd` does not override any standard browser behaviour. Arrow keys are usually reserved for scrolling the page.

**Comment by hakunin** [comment]
@alexreardon thanks, makes sense. Trello uses `hjkl` for walking, which is pretty standard so thats what I am going to use as well.

**Comment by tobiasandersen** [comment]
@alexreardon Crazy stuff, looks absolutely amazing!

**Comment by arthurcamara1** [comment]
Can't wait to see progress on this @alexreardon Nice work 🙌

**Comment by alexreardon** [comment]
We are hoping to ship today or tomorrow!!

**Comment by alexreardon** [comment]
Shipped!

![hi-five](https://user-images.githubusercontent.com/2182637/30426925-36982b60-9991-11e7-8c29-63b46801f1be.gif)

**Comment by poryzhao** [comment]
can there only be one placeholder in a board?

**Comment by alexreardon** [comment]
@poryzhao this needs some more thinking I agree. The challenge with removing the original placeholder is that the list size can collapse. Perhaps it is better to keep the space at the bottom of the list rather than in place. What do others think?

**Comment by alexreardon** [comment]
@poryzhao I am keen to make this a bit nicer. I created this with my thoughts on it: #94
