### ISSUE TITLE
Droppable without provided.placeholder

### ISSUE THREAD

**Issue by itamardavidyan** [atlassian/react-beautiful-dnd#2015]
example: [codesandbox.io](https://codesandbox.io/s/vertical-list-forked-t3e03?file=/index.js)

When I drag an item from the list to the trash the `trash-droppable` component height grows up, and when I delete the `provided.placeholder` I get warning.

The warning:
```
Droppable setup issue [droppableId: "trash-droppable"]:DroppableProvided > placeholder could not be found.
Please be sure to add the {provided.placeholder} React Node as a child of your Droppable.
```

What is the meaning of this error? Why `provided.placeholder` is required?
There is an option to pass prop for Droppable to let him know that his child component doesn't include `provided.placeholder`?

**Comment by AttilaPravda** [comment]
<span style={{ display: 'none' }}>{provided.placeholder}</span>

**Comment by killabeeez** [comment]
@AttilaPravda This doesn't work with the latest versions of react and dnd. Any updates on this behavior?

**Comment by Didbar** [comment]
> @AttilaPravda This doesn't work with the latest versions of react and dnd. Any updates on this behavior?

The same for me not working!

**Comment by garvae** [comment]
Make sure you are using "provided" from <Droppable/> not <Draggable/>. 

`
<DragDropContext onDragEnd={onDragEnd}>
          <Droppable droppableId={droppableId} >
            {/* ↓↓↓ this 'provided' */}
            {(droppableProvided) => (
              <div
                {...droppableProvided.droppableProps}
                ref={droppableProvided.innerRef}
              >
                {options.map((opt, index) => (
                  <Draggable key={String(opt.id)} draggableId={String(opt.id)} index={index}>
                    {/* ↓↓↓ not this 'provided' */}
                    {(provided, snapshot) => (
                      <div
                        ref={provided.innerRef}
                        {...provided.dragHandleProps}
                        {...provided.draggableProps}
                      >
                        Your content
                        {/* ↓↓↓ correct 'placeholder' */}
                        {droppableProvided.placeholder}
                      </div>
                    )}
                  </Draggable>
                ))}
              </div>
            )}
          </Droppable>
        </DragDropContext>
`

**Comment by peaceabiodun** [comment]
i'm having this same issue, i have added {droppableProvided.placeholder} and it's still not working

**Comment by Araf-Khatri** [comment]
```
 <Droppable droppableId="resource-drop">

              {provided => (
                <div
                  className="d-flex flex-column"
                  ref={provided.innerRef}
                  {...provided.droppableProps}
                >
                  <>
                    {resources.map((data, idx) => (
                        <ResourceComponent
                          index={idx}
                          key={data.id}
                          data={data}
                          currentTabResources={currentTabResources}
                          updateResource={updateStateHandler(idx)}
                          deleteHandler={deleteResourceHandler(data.id)}
                        />
               
                    )}
                    {provided.placeholder}
                  </>
                </div>
              )}
 </Droppable>
```
            

-  Add a React.Fragment as a parent of mapped array & provided.placeholder

ERROR:
```
ReactNode' is not assignable to type 'React.ReactNode'.
  Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
    Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2322).
```
