### ISSUE TITLE
I want to get the location of the currently moved element. What should I do

### ISSUE THREAD

**Issue by shijunwen** [atlassian/react-beautiful-dnd#2017]

**Comment by 2stash** [comment]
What do you mean location? like the x and y coordinates of the object you are dragging?

**Comment by shijunwen** [comment]
Right! Do you have any way?

**Comment by shijunwen** [comment]
I've now found a way to listen for the mouse to lift on the div I'm going to place. This will give you the x and y coordinates of the mouse

**Comment by davidbejarcaceres** [comment]
> I've now found a way to listen for the mouse to lift on the div I'm going to place. This will give you the x and y coordinates of the mouse

How did you managed to get the x & y coordinates of the item while dragging?

**Comment by shijunwen** [comment]
Monitor the movement of the mouse and calculate the offset
