### ISSUE TITLE
Moving to React 16 in early 2018 💥

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#202]
The plan is to move `react-beautiful-dnd` to `React 16` in early 2018. This will allow us to:

- Move to a portal based solution for more robust styling #192
- Clean up the api to remove the need to bind `ref` functions or insert the `placeholder`s. #8
- Avoid the need to create your own wrapper elements around a draggable. Will facilitate semantic table drag and drop

This shift would mean that the library would no longer work with `React 15`. 

I wanted to give people the heads up now that this is the planned direction rather than springing it on people at the last minute.

Cheers

**Comment by crapthings** [comment]
i love u

**Comment by inthedeepend** [comment]
All for it, thanks for the heads up.

**Comment by tim-soft** [comment]
Sounds great! Most other libs have followed suite, I think the timing is about right

**Comment by drew-walker** [comment]
Any plans to test/support React 16 (as a peer dependency) with the current API?

**Comment by alexreardon** [comment]
Hey @drew-walker! 

The current api works with React 16. If you are feeling enthusiastic you could raise a PR to change the deep dep range in the package.json.

**Comment by alexreardon** [comment]
Thanks @drew-walker #249

**Comment by denniscual** [comment]
This is so cool. Any updates for this @alexreardon ?

**Comment by alexreardon** [comment]
It is still high priority. We hope to start working on it soon

**Comment by denniscual** [comment]
@alexreardon that awesome.  👍

**Comment by alexreardon** [comment]
If you are interested you can check out the [new `Draggable` api](https://github.com/atlassian/react-beautiful-dnd/issues/8#issuecomment-379142374) 🎉

**Comment by alexreardon** [comment]
Closed by #406

**Comment by mdbadiyuzamaevoke** [comment]
react-beutiful-dnd supports react 15 version
