### ISSUE TITLE
redux connect(Droppable) returns state of library

### ISSUE THREAD

**Issue by olsem25** [atlassian/react-beautiful-dnd#2023]
When using the connect(Card) the status returned is 
```
{
    completed: null
    phase: "IDLE"
    shouldFlush: false
}
```
So I have component `Card` inside `DragDropContext` and inside `Droppable`. `Card` component return the `Draggable` with some extra markup. And when I am using connect - the issue is happened.

But when i try to reproduce it on sandbox - it is ok. No problem with it.
Am I doing something wrong?

### What version of `React` are you using?
16.9.0

### What version of `react-beautiful-dnd` are you running?

12.2.0

### What browser are you using?
I am using the last version of chrome

**Comment by 2stash** [comment]
Do you have a repo or more code to post? I can't think of a reason why it would not be compatible with Redux.

Just checking. You wrote "connect(card)". Shouldn't it be something else? Like "connect()(Card)". In the empty ( ) you would put the imported props from redux, mapstatetoprops, etc.

**Comment by olsem25** [comment]
I really cannot find out why the difference between codesandbox and the project

Yes, i use connect(mapStateToProps, mapDispatchToProps)(Card)

**Comment by 2stash** [comment]
Good morning! Can you please link the codesandbox and the project.

**Comment by danieldelcore** [comment]
Will close for now since there is no additional info provided. Please feel free to reopen if this is still an issue.
