### ISSUE TITLE
Option to remove extra body elemends

### ISSUE THREAD

**Issue by d07RiV** [atlassian/react-beautiful-dnd#2027]
I don't need screen reader support in my app, and extra elements added to body can cause some conflicts. There doesn't seem to be an option to disable those currently?

**Comment by danieldelcore** [comment]
Hi there, currently there is no option to remove additional a11y elements. Our goal is for RBD to be accessible for everyone by default. This is achieved in many different ways, from keyboard navigation, to announcements and [more](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/accessibility.md). 

It will be really challenging to make the right tradeoff here at a level that works for everyone. So will close this issue for now, thanks
