### ISSUE TITLE
[Question] - Where is official page/part for @atlaskit/tree ?

### ISSUE THREAD

**Issue by damikun** [atlassian/react-beautiful-dnd#2029]
Where is official page and documentation for @atlaskit/tree?

In GitHub I feel like it is maybe part of DND or maybe not.. I don't see any separate package or folder hire for it...

1) When I try to login over bitbucket - **I get missing permissions**
2) I found only this link https://atlaskit.atlassian.com/packages/confluence/tree..  (This one is for now working... ).... In many pages that refer to this link after open it is broken and show up only **Ooops** or that you are **not authorized** to see it...  Official link from _npm_ is also not working... 
3) Which atlas docs are current i found like 3 different pages refering to **atlas** ui components (i found few of them... https://atlaskit.atlassian.com  or  https://atlassian.design/components  etc... )

Thx

**Comment by AndrewOCC** [comment]
Hi Damikun – the official documentation page for the Tree component is the [page you linked from the Atlaskit website](https://atlaskit.atlassian.com/packages/confluence/tree). The documentation can also be viewed in the source code for the component. Apologies for any confusion about the location for these docs; we're currently in the process of moving the docs for some components (specifically, components grouped under `design-system`) to a new website, `atlassian.design`. Tree will remain on the Atlaskit website as it's not a design system component.

Unfortunately the repository linked on NPM is to the internal Atlassian repository where the components are built, which has restricted access. However, we mirror our public @atlaskit packages on the **Design System Mirror** (here's the link to the Tree source code: https://bitbucket.org/atlassian/atlassian-frontend-mirror/src/master/confluence/tree/). For more details on the mirror, check out the community post about the mirror here [[link]](https://community.developer.atlassian.com/t/new-expanded-mirror-repository-including-source-for-all-public-atlaskit-packages/42178)

**Comment by damikun** [comment]
Cool Andrew thx for answer...

**Comment by anniesexton-personal** [comment]
@AndrewOCC Sorry to dig this issue up again, but I'm getting a 404 when trying to access the Tree documentation mentioned above: https://atlaskit.atlassian.com/packages/confluence/tree now (with the error message `Not found - Request ID: bf7ae64e-11e8-4b67-be0f-5875b12a427c-931042`) I remember being able to access it just a couple days ago, just checking in to see if this issue is on your radar.

For now I can get by with the docs that are included in the source code, but hopefully the docs are live again soon. `@atlaskit/tree` has been a dream to use, absolutely love it!

**Comment by AndrewOCC** [comment]
Thanks for the message @anniesexton-personal; on inspection the entire Atlaskit site appeared to be down. The site has now been returned to operation and the tree documentation should be available again.

**Comment by bassamIHabash** [comment]
Hi @AndrewOCC 

I'm not able to use @atlaskit/tree library after upgrading my react project to the latest version 18.2.0, is there any fork? or coming update to support react 18?

**Comment by AndrewOCC** [comment]
@bassamIHabash, React 18 support is planned, but is not currently available for @atlaskit packages. I can't give a specific timeframe on when that work will be completed though.

**Comment by bassamnutanix** [comment]
> @bassamIHabash, React 18 support is planned, but is not currently available for @atlaskit packages. I can't give a specific timeframe on when that work will be completed though. 

Thanka for replay, is there any github repo ? So I can fork it and I can make the changes to support latest.

**Comment by AndrewOCC** [comment]
@bassamnutanix as mentioned above, the source code for Atlaskit packages lives in a bitbucket repo here: 

[https://bitbucket.org/atlassian/atlassian-frontend-mirror/src/master/confluence/tree/](https://bitbucket.org/atlassian/atlassian-frontend-mirror/src/master/confluence/tree/)

Generally I'd recommend reaching out on the [Atlassian Developer Community forums 
](https://community.developer.atlassian.com/t/introducing-the-spacing-scale-the-beginnings-of-an-atlassian-spacing-system/65393) for questions about Atlaskit components, as they are not directly related to this GitHub project.

**Comment by iformal42** [comment]
can we integrate @atlaskit/tree with react-beautiful-dnd . In my project at left side of page there is nested folder and right side grid view / grid component all of them under <DragDropContext> but while dragging element from grid view to nested folder for fewer folder the placement of element is kind of not working. So I thought the nested component code under @atlaskit/tree and grid view under RBD  by this can achieve what I want?
