### ISSUE TITLE
Is it time for the community to fork this project and maintain it? 🤔

### ISSUE THREAD

**Issue by 100terres** [atlassian/react-beautiful-dnd#2037]
### Description

Is this repo still being maintained? Should the community take over and start its own fork? :bulb: No one gave an answer when theses question were asked months ago :point_right: https://github.com/atlassian/react-beautiful-dnd/issues/1926 

![Screenshot from 2020-12-13 23-12-22](https://user-images.githubusercontent.com/4420524/102039888-2251aa00-3d99-11eb-9f68-43345d48e97e.png)

EDIT: A community "fork" is on the way (https://github.com/atlassian/react-beautiful-dnd/issues/2037#issuecomment-1044002349)
- https://github.com/react-forked/dnd/issues/159

**Comment by carlosagsmendes** [comment]
Atlassian says they will maintain it but won't be able to add new features:

["Hey there! Thanks for getting in touch. Checking with our Design team, they've let us know that while we aren't able to implement new features/functionality to the library as of late, we do work to fix any bugs/issues if they are brought to our attention."](https://twitter.com/OskariOfficial/status/1334062553006272512)

**Comment by 100terres** [comment]
Thank you @carlosagsmendes this answer my question :ok_hand:

**Comment by 100terres** [comment]
Then I think I’ll try to fork this project and continue where Atlassian left off and have something up in the upcoming days/weeks. I'll make an annoucement once it's ready, but here is the [repo](https://github.com/react-forked/dnd) where it is going to happen. :slightly_smiling_face:

**Comment by danieldelcore** [comment]
Hey all 👋 

I'm from Atlassian's Design System Team, I just wanted to chime in to this issue to shed some light over what's actually happening with this project.

I just want to apologise for the radio silence that you've been experiencing! That's not on and it's something we're working on addressing at the moment. At the very least you should expect a few of us to be monitoring and responding to issues in a KTLO capacity. We love this project and most definitely don't want it do die!

_But why is this the case?_ Lately our team has been juggling a few competing priorities internally, which means this project has not been getting the same attention and love as it was before. Unfortunately for the short-term this means we won't be proactively adding features to this library in the coming months. But don't let that discourage you, please continue to open issues and pull requests against the repo! We'll try our best to support!

_Is this project dead?_  I want to reassure you that RBD has not been abandoned. It is still heavily depended on throughout Atlassian and drives almost all of our DnD experiences! 

I'm going to leave this issue open, but in the meantime, please feel free to ping me if you need anything 👍. I'll try my best to respond and keep you unblocked 😄 👋

**Comment by bmueller-sykes** [comment]
I don't want to speak for the entire userbase of this great library, but I personally would be pretty happy with just making sure dependencies and such are kept up-to-date with this library. Not sure how much work would be involved with that, but if that happened, that would reduce the changes that, say, some future version of React broke this library because of some peer dependency that also needs to be updated.

**Comment by danieldelcore** [comment]
> I personally would be pretty happy with just making sure dependencies and such are kept up-to-date with this library.

That's a really good point, there's a PR open at the moment which configures the repo with [renovate](https://github.com/renovatebot/renovate). It might be able to help automate some of that work for us. 

I'm also thinking about installing [atlassian/changesets](https://github.com/atlassian/changesets) to automate our release notes + publishing. 🤔 I'll do a little bit of digging on this!

**Comment by danieldelcore** [comment]
Added a note for me to investigate: https://github.com/atlassian/react-beautiful-dnd/issues/2118

**Comment by danieldelcore** [comment]
Renovate added 😄 ✅

**Comment by 100terres** [comment]
FYI :upside_down_face: 

- https://github.com/react-forked/dnd/issues/159

Not released yet (currently in alpha is you want to give a try)

What's included:

- Repo migrated from Flow to TypeScript https://github.com/react-forked/dnd/pull/41
- All libraries (dev included) bump to the latest version https://github.com/react-forked/dnd/pull/142
- Make sure tests run with react v16 and v17 https://github.com/react-forked/dnd/pull/149
- Help needed to https://github.com/react-forked/dnd/issues/132
- and more

The goal is to continue on the great work that has been done by the team at atlassian by maintaining the codebase, providing new features and improvements :slightly_smiling_face: 

All suggestions are welcome and I'll need help from the community! :slightly_smiling_face:

**Comment by 100terres** [comment]
v14.0.0 has been released :slightly_smiling_face: Here's a blog post about it https://dev.to/100terres/rbd-is-dead-long-life-rfd-1n9e

**Comment by 100terres** [comment]
Is you see this comment you can try to migrate this library: https://github.com/hello-pangea/dnd :slightly_smiling_face:
