### ISSUE TITLE
Wrong draggable item position inside container with translateX property

### ISSUE THREAD

**Issue by Kontsedal** [atlassian/react-beautiful-dnd#204]
## Bug or feature request?
Bug

### Expected behavior

Correct draggable item position during drag

### Actual behavior

Wrong draggable item position during drag

### Steps to reproduce

Use Droppable inside element with transform: translateX property

### Browser version
Chrome (62.0.3202.94) Firefox(57.0)

### Demo
https://www.webpackbin.com/bins/-L-17XMBg-57nzCdD4aW
![ezgif-1-e1f619eb36](https://user-images.githubusercontent.com/9898226/33314954-e64a403a-d437-11e7-9b7d-a44e6a002a56.gif)

**Comment by kasperpihl** [comment]
I managed to get this to work with Portal from react-dom without changing styles etc.

I added a dom element into my html

```
<div id="draggable"></div>
```

Added the following styles
```
position: absolute;
pointer-events: none;
height: 100%;
width: 100%;
```

And then added this to the Draggable
```
import React, { PureComponent } from 'react';
import { createPortal } from 'react-dom';

const _dragEl = document.getElementById('draggable');

class DraggableGoal extends PureComponent {
  optionalPortal(styles, element) {
    if(styles.position === 'fixed') {
      return createPortal(
        element,
        _dragEl,
      );
    }
    return element;
  }
  render() {
    const { item } = this.props;
    return (
      <Draggable>
        {(provided, snapshot) => {
          return (
            <div>
              {this.optionalPortal(provided.draggableStyle, (
                <div
                  ref={provided.innerRef}
                  style={provided.draggableStyle}
                  {...provided.dragHandleProps}
                >
                  {item}
                </div>
              ))}
              {provided.placeholder}
            </div>
          );
        }}
      </Draggable>
    );
  }
}
```

Hope this helps :)

**Comment by alexreardon** [comment]
Thanks @Kontsedal and @kasperpihl! We are tracking this work here: #192

**Comment by rauleite** [comment]
The createPortal, is client feature. I think this solution unfortunately isn't compatible with SSR.
