### ISSUE TITLE
onDragEnd

### ISSUE THREAD

**Issue by kostisPodaras** [atlassian/react-beautiful-dnd#2041]
### Expected behavior
I use beautiful-dnd with react-final-form. When drop ends, form values should be the the correct ones. I save the values into an array, and values are correct when I log them into jsx.
### Actual behavior
Values are always one step behind in onDragEnd. So if I make one drag, nothing change, when I make another drag, then I see the first change to my console.log. Even though UI works perfect
### What version of `React` are you using?
17.0.1

### What version of `react-beautiful-dnd` are you running?
^13.0.0

**Comment by andrei9669** [comment]
could you give minimal reproducible code?

**Comment by danieldelcore** [comment]
Will close for now, but feel free to reopen if you're still experiencing this issue 👋
