### ISSUE TITLE
Text jitters between renders

### ISSUE THREAD

**Issue by supasus** [atlassian/react-beautiful-dnd#2042]
Expected behavior
I use beautiful-dnd with Draft.js. Each text component is a draggable component that stores it's state taken from the props. Through a useEffect method I'm updating the components state whenever the props change, expecting a smooth transition

Actual behavior
Text ends up jittering between the blocks. I'm sure the issue seems to be in the constant state updates instead of taking it straight from the props. But I cannot avoid that. 

What version of React are you using?
17.0.1

What version of react-beautiful-dnd are you running?
^13.0.0

What browser are you using?
Chrome

[Image](https://i.imgur.com/qU9FRlW.gif)
Don't mind the position change, that one I've got figured out, it's just the jittering that I'm having trouble with. Previously I fixed the same issue just by taking the props instead of having a midway state. Now I can't avoid that and I'm having trouble.

**Comment by danieldelcore** [comment]
Hi there 👋, 

Looks like there is some sort of issue with the state as draggables move between dragging to static. Are you able to share a code reproduction with me, preferably in [codesandbox](https://codesandbox.io/s/new) 🙏

**Comment by brian-gonzalez** [comment]
For people still experiencing this issue, it likely is happening due to using `index` as `key` within a template map. For more info see here: https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318
