### ISSUE TITLE
Use in Browser

### ISSUE THREAD

**Issue by adminR28** [atlassian/react-beautiful-dnd#2045]
Good morning

I've tried to use this lib in a browser as a script but I can't make it work.
What are the steps to use it without Node server ?

Thank you,
ATH

**Comment by danieldelcore** [comment]
Hi there 👋

AFAIK we don't support importing RBD directly as a HTML script. We usually recommend using a bundler to package RBD and its dependencies.

For a more detailed explanation on getting started check-out [this great tutorial series](https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd)

**Comment by danieldelcore** [comment]
Btw hope that helps! I'll close this one for now but please let me know if I've misunderstood the question 🙋‍♂️
