### ISSUE TITLE
Want to d'n'd A -> A, A -> B, B -> B, but *not* B -> A.

### ISSUE THREAD

**Issue by imnasnainaec** [atlassian/react-beautiful-dnd#2046]
### Description

I want to have two `<Droppable />`s, A and B, from which I can drag and drop items within and between them *except* in one direction from B to A. It looks I [cannot do this simply with types](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#conditionally-dropping); is there another way?

**Comment by mleutenegger** [comment]
I think your best option ist to use the [`isDropDisabled`](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#optional-props) prop on the `<Droppable/>` component to build this custom logic.

This could be achieved by using the [`onDragStart`](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/drag-drop-context.md#dragdropcontext-) (or `onBeforeDragStart`) handler on the `<DragDropContext/>` to update the state of your component rendering the board, passing it down to the `<Droppable/>` components or using an additional context which is consumed by the component rendering them.

A simple example using hooks:

```jsx
import React, { useState } from 'react';
// ...

const Board = () => {
  const [ dragSource, setDragSource ] = useState(null);
  const isDropDisabled = (dragTarget) => {
    // your logic here using dragTarget & dragSource
    return isDropDisabled
  }
  // ...
  return (
    <DragDropContext
      onDragStart={({source}) => setDragSource(source.droppableId)}
      // ...
    >
      {/* ... */}
        <Droppable
          droppableId="A"
          isDropDisabled={isDropDisabled("A")}
          // ...
        >
          {/* ... */}
        </Droppable>
      {/* ... */}
    </DragDropContext>
  );
}
```

I hope this helps!

**Comment by imnasnainaec** [comment]
Thank you, @mleutenegger for a clean example. I ended up using the `droppableId`s and putting the necessary logic in the `DragDropContext`'s `onDragEnd` function.
