### ISSUE TITLE
react-beautiful-dnd  A setup problem was encountered.  > Invariant failed:  provided.innerRef has not been provided with a HTMLElement.

### ISSUE THREAD

**Issue by jeremy-de** [atlassian/react-beautiful-dnd#2047]
I'm pretty sure the issue is reasond by my own fault, may you can help me to find the point what I'm doing wrong.

### The console output is:
react-beautiful-dnd
A setup problem was encountered.
> Invariant failed: 
provided.innerRef has not been provided with a HTMLElement. 

### WishList:

import React, { Component } from 'react';
import { incrementCounter, addWish } from '../actions/index';
import { connect } from 'react-redux';
import WishAdd from "./WishAdd";
import Panel from "./Panel";
import WishListItem from "./WishListItem"
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";

// a little function to help by reordering the result
const reorder = (list, startIndex, endIndex) => {
    const result = Array.from(list);
    const [removed] = result.splice(startIndex, 1);
    result.splice(endIndex, 0, removed);
  
    return result;
};

const grid = 8;

const getItemStyle = (isDragging, draggableStyle) => ({
    // some basic styles to make the items look a bit nicer
    userSelect: "none",
    padding: grid * 2,
    margin: `0 0 ${grid}px 0`,
  
    // change background colour if dragging
    background: isDragging ? "lightgreen" : "grey",
  
    // styles we need to apply on draggables
    ...draggableStyle
});

  

class WishList extends Component {
    
    constructor(props) {
        super(props);

        this.onDragEnd = this.onDragEnd.bind(this);
    }
    
    onDragEnd(result) {
        // dropped outside the list
        if (!result.destination) {
          return;
        }
    
        const wishes = reorder(
          this.state.wishes,
          result.source.index,
          result.destination.index
        );
    
        this.setState({
            wishes
        });
    }

    
    render() {
        return (
            <div>
                <DragDropContext onDragEnd={this.onDragEnd}>
                <Droppable droppableId="droppable">
                {(provided, snapshot) => (                

                    <Panel title="Wunsch-Liste">
                      
                      {this.props.wishes.map((wish, index) => (
                        
                        <Draggable key={wish.id} draggableId={wish.id.toString()} index={index}>
                          {(provided, snapshot) => (
                            <WishListItem
                                text={wish.title}
                                innerRef={provided.innerRef}
                                provided={provided}
                                style={getItemStyle(
                                    snapshot.isDragging,
                                    provided.draggableProps.style
                                )}
                            />
                            
                        )}
                        </Draggable>
                    ))}
                    {provided.placeholder}
                    </Panel>
                )}
                </Droppable>
                </DragDropContext>

                <br />
                <WishAdd onAdd={(title) => {this.props.addWish(title)}} />
            </div>
        )
    }
}

let mapStateToProps = (state) => {
    return {
        wishes: state.wishes
    }
}

let mapDispatchToProps = {
    addWish: addWish
}

let WishListContainer = 
    connect(mapStateToProps, mapDispatchToProps)(WishList);

export default WishListContainer;

### WishListItem
import React, { Component} from 'react';
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";
import ReactDOM from 'react-dom';

class WishListItem extends Component {
    setRef = (ref) => {
        // keep a reference to the dom ref as an instance property
        this.ref = ref;
        // give the dom ref to react-beautiful-dnd
        this.props.innerRef(ref);
    };

    render() {
        const { provided, innerRef } = this.props;
        return (
            <div>
                <div 
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                    ref={this.setRef}
                    width={250}
                    p={2}
                >
                    {this.props.text}
                </div>
            </div>
        )
    }
}

export default WishListItem;

### Background:

Sorry for some complecated code parts - I'm new with programming in React....

**Comment by mleutenegger** [comment]
Hi,

It looks like the ref is not properly passed to the `div`.  I don't think that you need to use a callback ref here, either...

have you tried passing it through directly?
```jsx
render() {
    const { provided, innerRef } = this.props;
    return (
      // ...
                ref={innerRef}
      // ...
    )
}
```

Another thing I would recommend is to try and render the encapsulating div in the `WishList`-component's render function, instead of passing `provided` and `innerRef` through. 
```jsx
<Draggable key={wish.id} draggableId={wish.id.toString()} index={index}>
      {(provided, snapshot) => (
        <div
          ref={provided.innerRef}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
        >
          <WishListItem
              text={wish.title}
              // use a prop if you want to style the WishListItem during dragging
              dragging={snapshot.isDragging}
          />
        </div>
    )}
</Draggable>
```
This helps keeping the codebase simple and components clean and separated.

Hope this helps!

**Comment by jeremy-de** [comment]
Thanks for your help. Both recommended changes did not avoid the error messages. Here how I understand your idears:

**render funktion Wish-List:**
return (
            <div>
                <DragDropContext onDragEnd={this.onDragEnd}>
                <Droppable droppableId="droppable">
                {(provided, snapshot) => (                
                    <Panel title="Wunsch-Liste">
                      {this.props.wishes.map((wish, index) => (
                        <Draggable key={wish.id} draggableId={wish.id.toString()} index={index}>
                              {(provided, snapshot) => (
                                <div
                                  ref={provided.innerRef}
                                  {...provided.draggableProps}
                                  {...provided.dragHandleProps}
                                >
                                  <WishListItem
                                      text={wish.title}
                                      dragging={snapshot.isDragging}
                                  />
                                </div>
                            )}
                        </Draggable>
                    ))}
                    {provided.placeholder}
                    </Panel>
                )}
                </Droppable>
                </DragDropContext>
            </div>
        ) 

**render funktion WishListItem:**

        const { provided, innerRef } = this.props;
        return (
                <div 
                    ref={innerRef}
                    width={250}
                    p={2}
                >
                    {this.props.text}
                </div>
        )

Hope I understood you in the right way....

**Comment by mleutenegger** [comment]
I think you mixed up my suggestions. Don't worry, Ill go into a bit of detail:

The first suggestion was to directly pass through the ref to the outer `div` of the `WishListItem`, without changing anything else about your code. I was not expecting this to work when I wrote it, but in the meantime I have looked up the ["Forwarding Refs"](https://reactjs.org/docs/forwarding-refs.html) pattern and am sure that this won't work by just passing it through.


The second suggestion was aimed at the way your components are structured. I will try to explain it as detailed as possible to help you on your journey with react 😉 . In the example code you provided, you passed down the `provided` and `innerRef` down to the render function of a further component. As far as I can tell, this would (functionally) not a be Problem with `provided`, but React abstracts `refs` in a way that might introduce errors like the one you encountered. Aditionally, When you pass down provided as a prop like so, every change (and `provided` updates a lot) forces a rerender of the component, leading to more renders and in term to a bad user experience.
Generally, I like to refer to the [*"Thinking in React"*](https://reactjs.org/docs/thinking-in-react.html) guide when it comes to component composition. In your case, I think you might be better off restructuring how you render The dnd components in your app. When it comes to `react-beautiful-dnd`, I would sketch a mental model of your Wishlist like so:

![Untitled Diagram(5)](https://user-images.githubusercontent.com/1339379/103439490-b5199200-4c3d-11eb-9b1f-6b69a5afd619.png)

This model is rather detailed but shows all the components this library works with. In your case (1 column), we can simplify this and combine the `DragDropContext` with the `Droppable` in the `WishList` and the `Daggable` with the `Wish` to the `WishListItem`. We then end up with this:

![Untitled Diagram(6)](https://user-images.githubusercontent.com/1339379/103439538-0b86d080-4c3e-11eb-8e2e-729d9c3c409e.png)
*I will explain why I would render the `Wish` as a separate component in the end.*

With this in mind, you can build your components (you are free to rename anything 😉). I use function components as I am more fluid with them, but you should be able to translate them back to classes:

`DraggableWishList`, which renders the `DragDropContext` and `Droppable` and takes care of the state of the list (the array of the Items)
```jsx
const DraggableWishList = (props) => {
  const { whishes } = props;
  function onDragEnd(event) => {
    // handle the drop event here
  }
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Droppable droppableId="list">
        {(provided) => (
          <div
            className="whishlist"
            {...provided.droppableProps}
            ref={provided.innerRef}
          >
            {whishes.map((Whish, index) => (
              <DraggableWishListItem Whish={Whish} key={Whish.id} index={index} />
            ))}
            {provided.placeholder}
          </div>
        )}
      </Droppable>
    </DragDropContext>
  )
}
```

`DraggableWishListItem`, which renders the `Draggable`
```jsx
const DraggableWishListItem = (props) => {
  const { Whish, index } = props;
  return (
    <Draggable draggableId={Whish.id} index={index}>
      {(provided, snapshot) => (
        <div
          className="whishlist__draggable"
          ref={provided.innerRef}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
        >
          <Whish Whish={Whish} dragging={snapshot.isDragging}/>
        </div>
      )}
    </Draggable>
  )
}
```

`Wish`, which renders your whish
```jsx
const Whish = (props) => {
  const { Whish } = props;
  return (
    {/* render your whish here */}
  )
}
```

**Why I would render `Whish` separately:** react-beautiful-dnd uses the HTMLElement which recieves the `innerRef` to calculate size of the dragged object and for positioning it during dragging. I have made the experience that the resulting `style` contains a `transition`, which might interfere with animations defined in a separate stylesheet.


-------

PS: you can paste code with highlighting in Github like [this](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) 😉

**Comment by jeremy-de** [comment]
Thank you for that awesome explanation, which helps me a lot to understand how it works! 

But after translating it into my classes, it didn't change the result.

I guess that maybe the reason is how I try to put it into the dom. In all tutorials it happens with:
```
ReactDOM.render(<App />, document.getElementById("root"));
```
So I assume, that I have to put my Component WishList separately to the DOM. Could this be the reason?

**Comment by mleutenegger** [comment]
This is difficult to say without seeing your code. Basically, the `render()` function hooks your `<App/>`into the DOM, which is the way to actually render anything in more complex apps. How have you started your App? [create-react-app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) ore some similar toolchain?

can you post the two classes you now have created?

**Comment by jeremy-de** [comment]
Sorry for the last comment, it wasn't quite the same error message. I only didn't recognize that the Id have to be a string. Now it works!!! Big big thanks for your patient and awesome help!! You did not only help to fix my problem, you also helped me to understand react and react-beautiful-dnd better.
Have a great new year!!

**Comment by NamanRajputXXI** [comment]
I got the some problem with this code, can anyone help me.
Problem1 : A setup problem was encountered.

code 👍 
import React, { useState } from "react";
import CardNavigationButton from "./Buttons/CardNavigationButton";
import Image from "next/image";
import house from "./../assets/house.jpg";
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";

import { onBoardUiStore } from "../globalStore/Navigation-Store/templateCardStore/onBoardUiStore";

interface NewDesignProps {
  handleClickOnNewDesign: () => void;
}

const TemplateCard = ({ handleClickOnNewDesign }: NewDesignProps) => {
  const {
    isEuropaCardOpen,
    isJayantiCardOpen,
    isYamunaCardOpen,
    openEuropaCard,
    openJayantiCard,
    openYamunaCard,
  } = onBoardUiStore();
  const cards: Array<{
    name: string;
    id: number;
    size: string;
    price: string;
    myfunc: () => void;
    styleWhenEuropaCardOpen: string;
    styleWhenYamunaCardOpen: string;
    styleWhenJayantiCardOpen: string;
    src: string;
  }> = [
    {
      name: "Europa",
      id: 1,
      size: "4 bhk",
      price: "4 L",
      myfunc: openEuropaCard,
      styleWhenEuropaCardOpen:
        "z-20 md:animate-none md:h-[364px] h-96  animate-fade-card ",
      styleWhenYamunaCardOpen: "md:h-[364px] translate-y-[90px] h-[320px]",
      styleWhenJayantiCardOpen:
        "md:h-[364px] z-10 translate-y-[55px]   h-[320px] ",
      src: "",
    },
    {
      name: "Yamuna",
      id: 2,
      size: "3 bhk",
      price: "25 L",
      myfunc: openYamunaCard,
      styleWhenEuropaCardOpen:
        " md:h-[364px] z-10    translate-y-[55px]  h-[320px] ",
      styleWhenYamunaCardOpen:
        "md:h-[364px] z-20  md:animate-none  h-96 animate-fade-card",
      styleWhenJayantiCardOpen: "md:h-[364px] translate-y-[90px] h-[320px]",
      src: "",
    },
    {
      name: "Jayanti",
      id: 3,
      size: "4 bhk",
      price: "4 L",
      myfunc: openJayantiCard,
      styleWhenEuropaCardOpen: "md:h-[364px] h-[320px] translate-y-[90px]",
      styleWhenYamunaCardOpen: "md:h-[364px] h-[320px]  translate-y-[55px]",
      styleWhenJayantiCardOpen:
        "mt-0 z-20 md:h-[364px] h-96  md:animate-none animate-fade-card ",
      src: "",
    },
  ];
  const [state, setState] = useState(cards);
  const reOrderCards = (
    cards: Array<object>,
    startIndex: number,
    endIndex: number
  ) => {
    const newCardsList = Array.from(cards);
    const [removed] = newCardsList.splice(startIndex, 1);
    newCardsList.splice(endIndex, 0, removed);
    return newCardsList;
  };

  const onDragEnd = (result: any) => {
    const { source, destination } = result;
    if (!destination) return;
    if (
      destination.droppableId === source.droppableId &&
      destination.index === source.index
    ) {
      return;
    }
    const { cards }: any = state;
    const newCards = reOrderCards(cards, source.index, destination.index);
    const newState = {
      ...state,
      cards: newCards,
    };
    setState(newState);
  };
  const onDragUpdate = (result: any) => {
    const { source, destination } = result;
  };
  const onDragStart = (result: any) => {
    const { source, destination } = result;
  };

  return (
    <main className="flex flex-col relative  left-[50%] translate-x-[-50%]  md:my-8 md:gap-4 my-0 gap-2  justify-center items-center ">
      <h1 className="text-[25px] select-none font-medium font-Roboto text-[#000000] leading-[29px] ">
        Choose your Base model
      </h1>
      <p className="text-[14px] select-none font-light leading-[16px]  text-center">
        Your dream home is a special place.
        <br /> Dream your dream house with just a few clicks!
      </p>
      <div>
        <DragDropContext
          onDragStart={onDragStart}
          onDragUpdate={onDragUpdate}
          onDragEnd={onDragEnd}
        >
          <Droppable droppableId="card">
            {(droppableProvided) => (
              <div
                {...droppableProvided.droppableProps}
                ref={droppableProvided.innerRef}
                className={`h-96  md:w-[700px]   md:border-[1px] gap-[10px] select-none relative flex md:flex-row flex-col  overflow-hidden justify-center text-center items-center  md:border-zinc-300 from-[180deg_rgba(255_255_255_0.7)_0%] to-[rgba(255_245_245_0.35)_100%] rounded-[20px] shadow-xl
          
          `}
              >
                {cards.map((e, index) => (
                  <Draggable
                    key={e.id}
                    draggableId={e.name.toString()}
                    index={index}
                  >
                    {(draggableProvided, draggableSnapshot) => (
                      <div
                        {...draggableProvided.draggableProps}
                        {...draggableProvided.dragHandleProps}
                        ref={draggableProvided.innerRef}
                        className={`h-[364px] touch-pan-y   w-[220px] md:translate-y-0  md:static  duration-500 transition-all fixed border-[1px] items-center py-[10px] md:shadow-md shadow-xl md:mt-0 flex flex-col bg-white border-amber-300  rounded-[15px]
         ${isEuropaCardOpen === true ? e.styleWhenEuropaCardOpen : ""}
         ${isYamunaCardOpen === true ? e.styleWhenYamunaCardOpen : ""}
         ${isJayantiCardOpen === true ? e.styleWhenJayantiCardOpen : ""}
        
         `}
                      >
                        <div
                          className="w-[190px] relative  object-fill overflow-hidden bg-zinc-300 h-[300px] border-[1px] border-amber-300 rounded-[12px]"
                          onClick={handleClickOnNewDesign}
                        >
                          <Image
                            src={house}
                            className="object-cover object-[top_0px_left_-100px]  w-full"
                            alt=""
                            layout="fill"
                          />
                        </div>
                        <div
                          onClick={e.myfunc}
                          className={`flex select-none items-center justify-between mt-4 cursor-pointer w-44
            
     
             `}
                        >
                          <h2 className="font-Bodoni select-none text-xl font-light leading-[18px] ">
                            {e.name}
                          </h2>
                          <p className="font-Roboto select-none text-[15px] font-light leading-[18px]">
                            {e.size}
                          </p>
                          <p className="font-Roboto select-none text-[15px] font-thin leading-[18px]">
                            {e.price}
                          </p>
                        </div>
                      </div>
                    )}
                  </Draggable>
                ))}
              </div>
            )}
          </Droppable>
        </DragDropContext>
      </div>
      {isEuropaCardOpen === false && <CardNavigationButton />}
      <div
        className={`text-[15px]  md:mt-0  font-light leading-[18px]
      ${isEuropaCardOpen === true ? "mt-[9vh]" : ""}
      `}
      >
        <span className="italic font-Roboto text-sky-500">Learn more</span>{" "}
        <span className="font-Roboto">about this model</span>
      </div>
    </main>
  );
};

export default TemplateCard;

**Comment by sourman** [comment]
Adding explicit values for the boleans resolved the error. looks like dnd wants devs to be explicit
```
<Droppable droppableId="campaigns" isDropDisabled={false} isCombineEnabled={false} ignoreContainerClipping={false}>
```
