### ISSUE TITLE
Unable to drop to another columns

### ISSUE THREAD

**Issue by u-uysal** [atlassian/react-beautiful-dnd#2050]
I successfully drag and drop inside the column but I am not able to drop another column. It doesn't give any error but when I log the console I see the destination is null. What do I need to do? @alexreardon 

![react-dnd](https://user-images.githubusercontent.com/54946794/103436881-fc455a00-4c20-11eb-9452-4c82310914a6.gif)

**Comment by mleutenegger** [comment]
Can you provide some code?

Anyways, this looks like the columns are not rendered in the same context ( `DragDropContext` rendered separate for each column). If this is the case, try to move the Context up:
![Untitled Diagram(7)](https://user-images.githubusercontent.com/1339379/103440888-be106080-4c49-11eb-99ac-cd53c242ed6f.png)

**Comment by u-uysal** [comment]
Hi, @mleutenegger Thank you so much for your answer. In my case, It solved by adding a min-height feature to each column :)

**Comment by Ies19999** [comment]
@mleutenegger thank you so much , especially for the picture, i found that i had 2 DragDropContexts one inside the other :)
