### ISSUE TITLE
Where to discuss atlaskit/tree issues?

### ISSUE THREAD

**Issue by anniebabannie** [atlassian/react-beautiful-dnd#2062]
The issue tracker link for `@atlaskit/tree` seems to be unavailable to the public, when I visited https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236 it said I don't have access to that portal.

It would be super nice if `@atlaskit/tree` had a repo in Github for tracking issues. I absolutely adore the library, but there are still a number of glaring holes that I'm curious about. For example, the `onDragUpdate` method in `DragDropContext` doesn't appear to be passed down from the parent `Tree` component, making it hard to manage the behavior/appearance of tree items while they're being dragged.

All that to say, could you point me to the best forum for discussing the atlaskit tree package? Alternatively, is there a guide for creating a nested tree using _only_ `react-beautiful-dnd`?

Thanks in advance for the help!

Please head to the [`@atlaskit/tree` issue tracker](https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236).

We do not track `@atlaskit/tree` issues in the `react-beautiful-dnd` project

**Comment by tarikcaliskan** [comment]
I have the same problems. Library itself is nice to use but on the other hand, it would be nice to discuss issues about it and offering the new enhancements. 

Thanks for your efforts!

**Comment by danieldelcore** [comment]
Hi there 👋 

We're tracking Tree issues in this pinned issue https://github.com/atlassian/react-beautiful-dnd/issues/1547. Feel free to jump into the discussion there 😄 It would be really helpful to start to consolidate all of these requests into that ticket. 

Are you sure this URL does not work for you? https://ecosystem.atlassian.net/servicedesk/customer/portal/24

You might have to sign in first but it should still be open to the public (let me know if not)

For now i'll close this one, please feel free to reopen if you still need help 👋

**Comment by kernelguardian** [comment]
Such a shame 😢
