### ISSUE TITLE
Keep getting "Warning: Each child should have a unique 'key' prop"

### ISSUE THREAD

**Issue by yoanndw** [atlassian/react-beautiful-dnd#2066]
Hello. I was trying to do a simple drag & drop between two lists. But because of problems, I tried to do with just one list.
I have a `Board` component (which is `Droppable`), which contains `Block`'s (`Draggable`).
Boards and blocks data are stored in an object in `MiddlePart` (the place in which are the boards), like this:
```js
this.state = {
    boards: [
        {
            droppableId: "board-conds",
            blocks: [
                { id: "block-0", content: 'tilt: "false"' },
                { id: "block-1", content: 'game_start: "true"' },
                { id: "block-2", content: 'game_in: "true"' },
            ],
        },
        {
            droppableId: "board-actions",
            blocks: [
                { id: "block-3", content: "score += 1000" },
                { id: "block-4", content: "play bonus sound" },
            ],
        },
    ],
};
```
In this test with one list, I just render `boards[0]` (in `MiddlePart.js`):
```js
<div className="board-display">
    <DragDropContext>
        <Droppable droppableId="board-conds">
            {(provided) => (
                <div ref={provided.innerRef}>
                    <Board blocks={this.state.boards[0].blocks} />
                </div>
            )}
        </Droppable>
    </DragDropContext>
</div>
```

And boards and blocks are rendered like this:
```js
// Board
// this.state.blocks is initialized via props
render() {
    return (
        <div className="board">
            {this.state.blocks.map((b, index) => (
                <Block id={b.id} index={index} content={b.content} />
            ))}
        </div>
    );
}

// Block
class Block extends React.Component {
    render() {
        return (
            <Draggable
                key={this.props.id}
                draggableId={this.props.id}
                index={this.props.index}
            >
                {(provided) => (
                    <div
                        className="block"
                        ref={provided.innerRef}
                        {...provided.draggableProps}
                        {...provided.dragHandleProps}
                    >
                        {this.props.content}
                    </div>
                )}
            </Draggable>
        );
    }
}
```
### The problem
The issue is that anywhere I place `key` prop, I always have this error in the console:
```
Warning: Each child in a list should have a unique "key" prop.
```

### Steps to reproduce
I've put all my code on https://codesandbox.io/s/elated-germain-tf73f. You just have to load the page, the error appears at loading.

### What version of `React` are you using?
`^17.0.1`

### What version of `react-beautiful-dnd` are you running?
`^13.0.0`

### What browser are you using?
Firefox 86.0

**Comment by mleutenegger** [comment]
Hi, the message you are getting is from react, not from this library. If you change Block rendered in the `Board` to
```jsx
 <Block key={b.id} id={b.id} index={index} content={b.content} />
```
it will disappear. You can read up on keys [on the official react docs](https://reactjs.org/docs/lists-and-keys.html#keys) if you are interested.

Hote this helps!

**Comment by yoanndw** [comment]
Hi, it works ! Thank you !
I've already read the docs, but I don't understand it : where go `key` when I have nested elements ?

Now, I've tried to change `MiddlePart` to render from `this.state.boards`:
```js
render() {
    return (
      <div className="board-display">
        <DragDropContext>
          {this.state.boards.map((b) => (
            <Droppable droppableId={b.id}>
              {(provided) => (
                <div ref={provided.innerRef}>
                  <Board blocks={b.blocks} />

                  {provided.placeholder}
                </div>
              )}
            </Droppable>
          ))}
        </DragDropContext>
      </div>
    );
  }
```
(the code is updated on codesandbox: https://codesandbox.io/s/elated-germain-tf73f?file=/src/MiddlePart.js)
But I have this warning again.

**Comment by mleutenegger** [comment]
You need to add a key to the `Droppable` in the map function.

Without going too much into how react renders stuff, I would summarise it like so ([in Depth explanation](https://reactjs.org/docs/reconciliation.html#recursing-on-children)):
When react updates a dom node, it loops over its children (both new and old) and applies a mutation to the DOM when necessary. In the case of lists, this can lead to situations where the entire list is updated, when only one Item needs to be changed. Take this example from the docs:
```jsx
// old:
<ul>
  <li>Duke</li>
  <li>Villanova</li>
</ul>
// new:
<ul>
  <li>Connecticut</li>
  <li>Duke</li>
  <li>Villanova</li>
</ul>

// ----------
// or with map:
// old:
<ul>
  {['Duke', 'Villanova'].map(item => (
    <li>{item}</li>
  ))}
</ul>
// new:
<ul>
  {['Connecticut', 'Duke', 'Villanova'].map(item => (
    <li>{item}</li>
  ))}
</ul>
```
Without a key, react can't decide which nodes to keep or to update, so it will update each `<li>...</li>`. In the case of a large list, this can quickly lead to performance issues. By adding a key, react can skip a DOM mutation for items which dont need any change:
```jsx
// old:
<ul>
  {['Duke', 'Villanova'].map(item => (
    <li key={item} >{item}</li>
  ))}
</ul>
// new:
<ul>
  {['Connecticut', 'Duke', 'Villanova'].map(item => (
    <li key={item} >{item}</li>
  ))}
</ul>
// assuming the names are and will stay unique!
```
in this example the nodes of `'Duke'` and `'Villanova'` dont need to be updated and only a single DOM node, `'Connecticut'` has to be inserted. More often than not you use an id in your data model which can be used as key.

So as a rule of thumb: the first node in a `map()` always needs a `key` prop, which is identified by most linters and react itself.

**Comment by danieldelcore** [comment]
Thanks for jumping in @mleutenegger! Yes will close this issue since it's related to react rather than this library. 

React has a great page on this issue [here](https://reactjs.org/docs/lists-and-keys.html)
