### ISSUE TITLE
Dragging not working on Windows 7 (Electron)

### ISSUE THREAD

**Issue by pedro-surf** [atlassian/react-beautiful-dnd#2078]
### Expected behavior
Drag grid rows

### Actual behavior
Dragging doesn't work on Windows 7.

### Steps to reproduce
Create a multi draggable grid and try to use run on Win7

### Suggested solution?
Transpile output code that is in es6 to es5

### What version of `React` are you using?
CRA 3.4.3

### What version of `react-beautiful-dnd` are you running?
13.0.0

### What browser are you using?

Chromium? (ElectronJS)
![image](https://user-images.githubusercontent.com/40304742/106373365-859e9800-6357-11eb-93d1-d7d3df3c7c88.png)

**Comment by khan94** [comment]
@pedro-surf could you share your code?

**Comment by pedro-surf** [comment]
It was a logic/data bug, sorry for not closing this earlier
