### ISSUE TITLE
Nested Sortable Tree

### ISSUE THREAD

**Issue by Merynek** [atlassian/react-beautiful-dnd#2079]
### Description
Hello,
your package is awesome.
I found the note in your readme file: "Independent nested lists - a list can be a child of another list, but you cannot drag items from the parent list into a child list".
I would like to use  this perfect package for this solution.
Is is possible  in future?

Example:
![example](https://user-images.githubusercontent.com/6883795/106463188-6444c580-6497-11eb-94a0-a8b430f40f38.gif)

Thanks

**Comment by danieldelcore** [comment]
Hi there, thanks for raising an issue. Trees are currently not supported but we have an issue that discusses it here: https://github.com/atlassian/react-beautiful-dnd/issues/1547

**Comment by Pines-Cheng** [comment]
Has any updates?
