### ISSUE TITLE
Is it possible to drag an item from another react-beatiful-dnd list into the tree?

### ISSUE THREAD

**Issue by JoeVanGundy** [atlassian/react-beautiful-dnd#2081]
I can't access the issue tracker, so I'm posting here.

I need to be able to drag an item from another list into the atlaskit/tree.

Is this supported?

**Comment by danieldelcore** [comment]
Hi there 👋 

We're going to try to consolidate all of the tree related discussion & requests into this ticket https://github.com/atlassian/react-beautiful-dnd/issues/1547
Please feel free to jump into the discussion there.

As for the issue tracker, can you try this URL? It should still work and be available to the public 🤔. LMK if not 😄
