### ISSUE TITLE
The Course is off line ?

### ISSUE THREAD

**Issue by shpsyte** [atlassian/react-beautiful-dnd#2089]
Can you check please? It's not working 

https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd

**Comment by danieldelcore** [comment]
Can you please give me more information? 
What is not working for you? The URL or is the page locked?

**Comment by shpsyte** [comment]
I was getting a time-out, but it works now....
BTW: Awesome component

**Comment by danieldelcore** [comment]
Thanks! Glad it's working for you now :) Enjoy!
