### ISSUE TITLE
Cannot get React-Virtualizer to work with with React-Beautiful-DND (Demo Included)

### ISSUE THREAD

**Issue by DaleSalcedo** [atlassian/react-beautiful-dnd#2098]
### Expected behavior
For the list to be virtualized in combination with drag and drop

### Actual behavior
With Autosizer: The list isn't even visible.

Without AutoSizer: Once I start scrolling, it turns blank

### Suggested solution?
I'm really not sure, I do believe I'm just missing something small.. maybe I'm using one of the props incorrectly?  I feel like it's a semantic error that's wrong somewhere.

I've seen the example provided [here](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/virtual/react-virtualized/list.jsx).

I also have successfully got react-beautiful-dnd to work on it's own.  I've also gotten react-virtualizer to work on it's own.  But I cannot get them to work together for some reason.

I've tried on my production project, and now I tried even in the sandbox demo without AutoSizer and now I can't even get it to run.  Maybe if I can get this Sandbox running I can translate it to my work project.

### What version of `React` are you using?
16.13.1

### What version of `react-beautiful-dnd` are you running?
13.0.0

### What browser are you using?
Chrome

### Demo
[Without Autosizer](https://codesandbox.io/s/vertical-list-forked-umk7d?file=/index.js)
[With Autosizer](https://codesandbox.io/s/vertical-list-forked-9tpo2?file=/index.js)  <-- Prefer with Autosizer to work

**Comment by imbavirus** [comment]
@DaleSalcedo 

I'm struggling with the same set of problems currently, just in a bit of a bigger scale, as for your issue, on the one without the autosizer I managed to get that functioning by wrapping the draggable in the div with the list element's style and fixing the row height.

As for the one with the autosizer, I have had that working too in my tests, but haven't yet spotted the problem in yours, however I would suggest taking a look at react-window instead of react-virtualized

**Comment by DaleSalcedo** [comment]
hey @imbavirus thanks for the response!  I took a look at react-window with react-beautiful-dnd but it's the same problem actually because I need the AutoSizer.  if your project isn't private, any way i can get a link to the file/github that shows you using both?  I think if I could see just one example of the AutoSizer with react-beautiful-dnd I can maybe figure it out.  Thanks regardless

**Comment by imbavirus** [comment]
@DaleSalcedo unfortunately the project is private, but I did get it working with the autosizer on your code too: [here](https://codesandbox.io/s/vertical-list-forked-qz5vj?file=/index.js:2678-2700) basically you need a cellmeasurercache and something that has a size value around the autosizer (I think in this case it had no parent to get a height value from)

**Comment by DaleSalcedo** [comment]
@imbavirus this is great!!! thank you!!  going to close this ticket now, but i guarantee someone else will be having the same problem I did and will find this a useful resource.  thanks again

**Comment by DaleSalcedo** [comment]
Ah man I tried relaying this to my private project and while it's close.. it starts blinking and and freaking out after scrolling down a little bit.  I spent some time reading the API and docs again but can't figure it out.  I'll leave this open for a little bit jus incase there's any suggestions, but I guess it's hard to fix without a codesandbox of the actual project.  Thanks again though!

**Comment by imbavirus** [comment]
@DaleSalcedo  do you have the div with the list's style wrapped around your draggable?

**Comment by DaleSalcedo** [comment]
@imbavirus wow i didn't catch that.  but YES it works!  i've been working on a production project at work that uses long playlists and this is going to be a life saver... seriously though; i've been trying to implement the two together for days and i just gave up on it.  thank you sincerely

**Comment by DaleSalcedo** [comment]
lol sorry one last one @imbavirus do you happen to know off the top of your head why the style i created for my items goes away when dragging?  it didn't do that before i applied the virtualizer and autosizer... so every time i drag and drop the original style goes away.  if not don't worry about it; you helped me a ton.

**Comment by chaomao** [comment]
here is the demo of dynamic height per row with `react-beautiful-dnd` + `react-virtualized` + `cellMeasurer`, please check it out, https://codesandbox.io/s/react-beautiful-dnd-react-virtualized-cell-measurer-xue6h

However I found there is one issue, if you move one card down to a far place, like below 50 cards, the list position will jump a little bit after drag finished. I cannot figure it out... would you guys have any suggestion?

![list-jump-after-drag](https://user-images.githubusercontent.com/817897/120894715-7d7b9f80-c64c-11eb-908b-03046df49a89.gif)

**Comment by comerc** [comment]
@chaomao have you found a solution?

**Comment by 55Cancri** [comment]
@chaomao I converted your example to React.18, typescript, hooks, and the more supported @hello-pangea/dnd (fork of rbd) https://codesandbox.io/s/react-beautiful-dnd-react-virtualized-cell-measurer-forked-stpyxs?file=/index.tsx and still the issue persists. Also if I try to scroll all the way to the bottom, the list gets stuck halfway. Did you ever find a solution this?

**Comment by 55Cancri** [comment]
@comerc did you ever find a solution?

**Comment by 55Cancri** [comment]
@chaomao @comerc I found this article: https://blog.logrocket.com/rendering-large-lists-react-virtualized/#calculating-height-row-automatically which suggests using render props for the CellMeasure component and attaching the registerChild ref to your item ref and possibly even using the measure function to remeasure the component at some point. It looked like this:
```typescript
function renderRow({ index, key, style, parent }) {
  return (
    <CellMeasurer
      key={key}
      cache={cache}
      parent={parent}
      columnIndex={0}
      rowIndex={index}>
      {({registerChild, measure}) => (
        <div style={style} className="row" ref={registerChild}>
          <Collapsible title={list[index].name} onChange={measure}>
            <div className="image">
              <img src={list[index].image} alt="" />
            </div>
            <div className="content">
              <div>{list[index].name}</div>
              <div>{list[index].text}</div>
            </div>
          </Collapsible>
        </div>
      )}
    </CellMeasurer>
  );
}
```
However this did not work for me.
