### ISSUE TITLE
not able to drop in phase: 'PREPARING'

### ISSUE THREAD

**Issue by crapthings** [atlassian/react-beautiful-dnd#210]
im play dnd with meteor, and i've found "not able to drop in phase: 'PREPARING'" when i set 50 "decks and many cards".

i think i might use it in wrong way inside a container

https://github.com/crapthings/beautiful-dnd-issue

how to provide the data the best practice

```
curl https://install.meteor.com/ | sh
git clone https://github.com/crapthings/beautiful-dnd-issue.git && cd beautiful-dnd-issue
meteor npm i
meteor
```

**Comment by pcsforeducation** [comment]
I'm having the same issue. I have Droppable/Draggables nested 4 layers deep, with about 200 or so total leaves at the bottom of the nesting. Whenever I attempt to drag anything, I get the error message.

**Comment by crapthings** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/86

https://github.com/atlassian/react-beautiful-dnd/issues/116

i'll try https://github.com/atlassian/react-beautiful-dnd/issues/116#issuecomment-332066196 first
