### ISSUE TITLE
Issue with bottom anchored lists

### ISSUE THREAD

**Issue by amytych** [atlassian/react-beautiful-dnd#211]
When multiple draggable lists are anchored to the bottom of a container (e.g. using `display: flex` or `display: table`) there is an issue when dragging items between them. I suspect it is because of position calculations being based on the top left coordinate of the list. When the item is dropped, the placeholder element is removed from the DOM causing the top left coordinate to change. This results in the dropped item being briefly placed incorrectly, lower than it should, only then to revert to the proper position, as illustrated in the gif below:

![nov-30-2017 10-03-44](https://user-images.githubusercontent.com/998924/33422414-ee9be0ac-d5b5-11e7-8d7e-bf3f2fd45dab.gif)

Just to reiterate, everything works beautifully with regular lists, problem appears when they're attached to the bottom, that's the only change.

I tried many ways to work around this but didn't succeed. Was that scenario ever considered? Maybe someone was able to make it work? Any pointers would be greatly appreciated, even one saying that bottom anchored lists are out of scope of this library.

In any case, thank you!

**Comment by alexreardon** [comment]
Bottom arranged lists had not crossed my mind! For now they are out of scope as you put forward. You could get something working by collapsing the droppable so that it tightly surrounds the list. This is not optimal as it would prevent the user from dropping on the visual space above. It might be super strange, but you could add an invisible Draggable to the top of each list that fills the space that has the `isDragDisabled` prop on it. It might be quite strange when it comes to movement though - but you could try it out!

**Comment by edzis** [comment]
I am also in need for bottom-based lists, adding items to them and dragging between them. Will try out the idea of an empty placeholder.

**Comment by edzis** [comment]
@alexreardon I tried several approaches with spacer element, `align-items: flex-end;`, placeholder order and for none of those I could get a combination of accurate placeholder logic and drag-end animation target.

Then explored the logic and modified the generated js in my test project. By introducing logic in a couple of places I managed to get further. Here is my result - https://imgur.com/a/dIuDB

This exploration is currently brutal but the changes seemed to be in places where configuration can easily alter it.

For my next exploration I want to find a way to change which droppables should be moved - the ones before the insert point. Do you have any recommendations or concerns about this approach?
