### ISSUE TITLE
Has this library been abandoned?

### ISSUE THREAD

**Issue by bmueller-sykes** [atlassian/react-beautiful-dnd#2117]
There hasn't been a release in about a year, and there are an awful lot of open issues that haven't been tended to of late.

Is it time for those of us who use (and love) this library to look elsewhere?

**Comment by danieldelcore** [comment]
Hey @bmueller-sykes 👋 

I've just responded to a similar ticket: #2037
Will close this issue for now, please feel free to keep the conversation going there!
