### ISSUE TITLE
Performance with react-virtualized

### ISSUE THREAD

**Issue by synapse** [atlassian/react-beautiful-dnd#214]
I experienced some performance issues with a lot of items mostly while rendering them and at the initial drag where the item is not lifted up but instead jumps into position (check gif).

I was curious if there's a way to use [react-virtualized](https://github.com/bvaughn/react-virtualized) or any other technique to have a better performance when having a big list or some more complex items.

![IDrag example](https://i.imgur.com/0MAjN4t.gif)

**Comment by alexreardon** [comment]
Hi @synapse, we are about to start some work on both the things that you described:

#86 
#68 

They are a big priority for the library

**Comment by alexreardon** [comment]
So hopefully you will not need to wait too long for this!

**Comment by dcporter44** [comment]
@alexreardon Do you plan on implementing virtualization using react-virtualized or a custom implementation? Is there any kind of ETA on this? I'd love to use react-beautiful-dnd on project, but it's going to be impossible without virtualization.
