### ISSUE TITLE
Draggable without a Droppable (drag, no drop)

### ISSUE THREAD

**Issue by cactusjosh** [atlassian/react-beautiful-dnd#2154]
### Description
I want to be able to drag an 'item' around the page (think 'free drag'). Think of it like a 'widget' that I want to be able to reposition so I can focus on the content in front of me. I only see examples of moving an item into lists, which is not what I need. 

I'd like to see either:
Docs explaining how to have a single draggable inside a single droppable container
or:
A draggable component that when moved, stays there (and doesn't snap back to it's original position).

**Comment by josh--newman** [comment]
I've been researching different interaction libraries and I think what you're describing might be a good use case for [react-use-gesture](https://github.com/pmndrs/react-use-gesture)

**Comment by cactusjosh** [comment]
Thanks, @josh--newman. I'm short on time so I went with this for now: https://www.npmjs.com/package/react-draggable which does exactly what I need. For anyone else that has a similar problem `react-draggble` is a good solution for now.

Not ideal since I now have two drag libraries in the codebase but I'll checkout use-gesture for when I have time.
