### ISSUE TITLE
OnDragEnd not triggerring

### ISSUE THREAD

**Issue by saravanan0701** [atlassian/react-beautiful-dnd#2161]
whenever item is dragged and dropped it is still in draggable (isDragging) state, any css should be added to the parent div?

**Comment by fzaninotto** [comment]
I can confirm the bug. I suspect it comes from one of react-beautiful-dnd dependencies.

**Comment by danieldelcore** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on codesandbox.io using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!
