### ISSUE TITLE
Is there any way I can control drag whether to change position?

### ISSUE THREAD

**Issue by pisces-wanfeng** [atlassian/react-beautiful-dnd#2177]
I want to achieve a similar effect to a file manager.

For example:
```ts
- FolderA  |
/          |  <-- FileC can't move to there
- FolderB  |  <-- I want to move FileC to FolderB, and not trigger position change
- FileC
- FileD
```
I want folders(FolderA, Folder B) always on top, and Files(FileC, FileD) always on bottom. It means FileC never displayed between FolderA and FolderB.

And, files can drop in folders.

I tried **isCombineEnabled** and **isDropDisabled**, but the problem is when I set isDropDisabled true that combine is also not working.

So, how can I solve this problem?

Any help is appreciated.

**Comment by 2stash** [comment]
@pisces-wanfeng Hi! I think this is definitely doable! Can you share your source code? Or can you explain how you want the folders and files to display in a little bit more detail? How do you plan on displaying the folders and the folder contents? Are the folders always displaying their contents (like not a real windows folder you need to double click to open)? Are the folders ever draggable? How are files added? Do new files get added to the bottom outside a folder and then someone needs to drag them to a folder. Are new folders created?

**Comment by pisces-wanfeng** [comment]
@2stash Thanks.List just like
```
- FolderA
- FolderB
- FileC
- FileD
```
Folder's contents is not display.
Click FolderA then change list just like
```
- FolderC
- FileE
- FileF
- FileG
```
Folder is draggable, is sortable with Folder.Also File is draggable, is sortable with File.

But File is not sortable with Folder.

Folder and File can put into Folder.

Very appreciated.

**Comment by 2stash** [comment]
@pisces-wanfeng Ok, so just going to mention I've been doing Java for 3 months, so rusty on React and front-end, which is why I'm looking for something fun to work on :) .

https://codesandbox.io/s/react-drag-and-drop-folders-react-beautiful-dnd-djip9?file=/src/index.js

Here is a demo of what you described. It is basic! Can start to add more features. I really just wanted to start with dragging a item to a folder, and have it disappear nicely. 

Let me know if I am on the right track and I will start working on getting the folders draggable and droppable into other folders, which I think is doable.

**Comment by pisces-wanfeng** [comment]
@2stash Very appreciated, but I'm sorry.What I expected is like that:
![Kapture 2021-04-19 at 20 29 23](https://user-images.githubusercontent.com/47812865/115236817-693c1b80-a14e-11eb-9234-fee2242d5e4e.gif)

**Comment by 2stash** [comment]
@pisces-wanfeng HI! Does your example work with dropping the folders? 

Yeah my example I wanted to do the easy thing first. I will make the folders draggable next.

**Comment by pisces-wanfeng** [comment]
@2stash Yeah, folder can drop into folder, and file can drop into folder too.
I achieved it with react-beautiful-dnd, but the question is that I cannot prevent file change position with folder —— File can drop into folder, but cannot change position with folder.

I am grateful for your help.

**Comment by 2stash** [comment]
@pisces-wanfeng Looking at your example, the folder doesn't seem to change position with the file when you move the file over the folder. Or do you want the folder to move when file goes past it?

**Comment by pisces-wanfeng** [comment]
@2stash The demo is what I wanted. I did it with react-dnd. Sorry it may not be valuable.
React-beautiful-dnd is great too, so I am looking forward to similar functions.

**Comment by 2stash** [comment]
@pisces-wanfeng Ok nice work! So should this issue be closed? Or are you asking for a specific feature request?

**Comment by pisces-wanfeng** [comment]
@2stash Yeah, I'm so grateful.
