### ISSUE TITLE
Collision detection problem when dragging a big item from another row.

### ISSUE THREAD

**Issue by toulondu** [atlassian/react-beautiful-dnd#2180]
I create a Demo based on your example.[https://codesandbox.io/s/mixed-size-problem-se92v](https://codesandbox.io/s/mixed-size-problem-se92v)
When I drag a big item from the second row's first column to the first row, I can not drop it to the second or third column.

![drag-problem](https://user-images.githubusercontent.com/61454266/114692100-e4ff2800-9d4a-11eb-8469-c72aae057eab.gif)

I have read your [article](https://dev.to/alexandereardon/overhauling-our-collision-engine-962) about the collision engine.
By reading it I know the bug is caused by the **furthest away** strategy.

But I dont know how to solve it,  is there any solution for it?

**Comment by 2stash** [comment]
@toulondu Hi! Can you think of a use case for this? I think if we can think of a reasonable use case it might be easier to determine a fix or more likely, an elegant work around. 

I made this example https://2stash.github.io/algoschedule/ 
Which is a schedule creator for studying algorithms that lets you sort 100 problems from algoexpert.io, I had trouble finding a way to sort by category, because each category is an entire column. Specifically I did not get the responses I wanted when having multiple rows of columns.

Reading the article you posted, the logic for large columns looks like it was written for going up and down, or left and right in the same row or column, and the logic looks like it would get messed up when going up or down a row. Specifically in your codepen you can put the large table in the outer columns because the logic seems to be looking at the end of the large column and what it is crossing.

**Comment by toulondu** [comment]
@2stash Thanks for your response!  Actually, My use case is like this(don't have an online site yet):
<img width="1384" alt="useCase" src="https://user-images.githubusercontent.com/61454266/115104779-3d256c80-9f8d-11eb-99c4-1482b9ee0616.png">

It's an architecture site to design a Page. Each card presents a well-made content. 
On this page, you can add any rows you like and split each row into any columns. The card will auto expands to fit the column.

The problem is caused when I want to implement the request to move cards across any columns of any rows.  Such as move the HeadLines to the above of the Todo Card.

I have thought of some alternative implementation, such as shrink the card to a small size when I drag it. But it is a little difficult, so I want to know if there is any other way to solve it.

**Comment by 2stash** [comment]
@toulondu I just found this example while searching through the list of issues. It changes size of draggable when you start to drag. I think this is a good solution to get working and see if it brings up any other problems.  I haven't looked through the code yet, but will soonish. I have been trying to use "onBeforeCapture" but not successfully. The state is not updated when it is executed, so I haven't figured out how to use it yet besides console logging  things lol.

https://react-beautiful-dnd.netlify.app/?path=/story/mixed-sizes--with-large-droppable-size-variance-experiment

The only other option I thought of, is basically have a standard header that you drag around that is locked in size.  So for example, your "Headlines" could actually be the element you are dragging visually, not the whole "headlines" + "content". So lets say you drag "Headlines", you could turn the current "Headline" column a different color to indicate it is moving, but the piece size is small and you can move it around easily.  Another example that might example the concept better is if you had a list of Todos, the left is the todo Id, and is draggable, but the right is just static output of the todo, so you would only move the ids around, and the static content of the todo would rerender after the reorder.  In either case it would more be on your logic doing it. If this sounds interesting I can put a demo together.

**Comment by toulondu** [comment]
@2stash This demo is cool, I looked up the code, it's using this `onBeforeCapture`, I did not know this event before,  I could give it a try then.

And I also had thought about your second solution by set the `provided.ref` to a small item on the card, but the effect and the user interaction are not good enough for me. 

Thank you. I'll give a response if the first solution works!

**Comment by 2stash** [comment]
@toulondu Good luck! Also here is the source code for the demo, which can be hard to find.

https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/mixed-sizes/mixed-size-lists-experiment.jsx

**Comment by toulondu** [comment]
@2stash This method works for me! Thanks a lot for your help.
These guys did a great job. Maybe they should put this in their documentation.
