### ISSUE TITLE
事件延申穿透问题

### ISSUE THREAD

**Issue by zjmzy1001** [atlassian/react-beautiful-dnd#2192]
### Description
场景：
每一个拖拽元素是antd得一个<card/> 通过按钮<Button/>打开antd中的<Drawer/>组件 内置时间选择器<DatePicker/>
问题：
1.点击空白无法关闭<DatePicker/>标签
2.还可在<Drawer/>中进行拖动

**Comment by Juntao-Qiu** [comment]
@zjmzy1001 你好，你可以提供一个`codepen`或者`codesandbox`里的一个可以运行的例子吗？我不太明白你的意思，谢谢 😄
