### ISSUE TITLE
Cannot resolve module while commiting changes to github repo

### ISSUE THREAD

**Issue by emrahkarademir** [atlassian/react-beautiful-dnd#2193]
Hello, and thanks for the amazing work with Dnd :)

### Expected behavior
When commiting the changes in github, modules should be resolved.

### Actual behavior
The build of the existing react project, the Dnd list and drag&drop items are working as expected.

When commiting the changes on github repo, I'm getting the following output:

**Error ---------------------------------------- node_modules/react-beautiful-dnd/src/view/drag-drop-context/index.js:2:45
Cannot resolve module `./drag-drop-context`.
   2| export { default, resetServerContext } from './drag-drop-context';
                                                                         ^^^^^^^^^^^^^^^^^^^^^
Error ------------------------------------------------ node_modules/react-beautiful-dnd/src/view/draggable/index.js:2:44
Cannot resolve module `./draggable-api`.
   2| export { PublicDraggable as default } from './draggable-api';
                                                                        ^^^^^^^^^^^^^^^^^
Error --------------------------------- node_modules/react-beautiful-dnd/src/view/droppable/connected-droppable.js:29:23
Cannot resolve module `./droppable`.
   29| import Droppable from './droppable';
                                             ^^^^^^^^^^^^^**

### Steps to reproduce
1- In an existing project, chekout a new branch, then run _npm install react-beautiful-dnd_
2- Create a new component where you import Dnd package and run some good Dnd stuff.
3- The build should work.
4- Commit the changes to your new branch

### Suggested solution?
...

### What version of `React` are you using?
react version: 17.0.2
react version on the project: 16.9

**package.json:**

  "dependencies": {
...
    "react": "16.9",
    "react-beautiful-dnd": "^13.1.0",
...

### What version of `react-beautiful-dnd` are you running?
Dnd version: 13.1.0

### What browser are you using?
Last version of Chrome

**Comment by emrahkarademir** [comment]
So, The issue was that the file where I was using the package was a JS file, not a JSX...

**Comment by danieldelcore** [comment]
No worries, in that case I'll close this for now 👍
