### ISSUE TITLE
Where is a current link to the Tree? The other link is dead.

### ISSUE THREAD

**Issue by Braweria** [atlassian/react-beautiful-dnd#2197]
On [this page](https://github.com/atlassian/react-beautiful-dnd/blob/2360665305b854434e968e41c7b4105009b73c40/docs/guides/combining.md) there is the following quote  
> 🌲 If you are looking to build a tree view, we have built one already! @atlaskit/tree    

And it links to this site: https://atlaskit.atlassian.com/packages/core/tree Which only gives me   

> Oops!
> Couldn't find this page.  

So where can I find the correct link to it?

**Comment by madou** [comment]
Hey mate you can find it here https://atlaskit.atlassian.com/packages/confluence/tree

Full context: I believe it uses an older version of rbd and isn't compatible with the latest version.

**Comment by Braweria** [comment]
> Full context: I believe it uses an older version of rbd and isn't compatible with the latest version.

Oh no, that would be bad. I need that tree structure in my project!

**Comment by danieldelcore** [comment]
Hi there 👋 I've updated the docs to reflect the correct URL. 
Will close this issue for now, please feel free to leave comments on your previous ticket #2199 and/or the main ticket #1547 moving forward 😄
