### ISSUE TITLE
Disable all drag functionality including pick up

### ISSUE THREAD

**Issue by dcporter44** [atlassian/react-beautiful-dnd#222]
## Feature Request

It would be useful to have a prop on DragDropContext to completely disable all dragging. Is there currently a way to replicate this functionality for the short term?

**Comment by alexreardon** [comment]
You can achieve this by using the `Droppable > isDropDisabled` and `Draggable > isDragDisabled` props. There is currently no master switch at the root level - but using the provided props will enable you to achieve the behaviour you are after.

**Comment by ericbiewener** [comment]
Perhaps this could be added to the docs somewhere? There is no mention of these props anywhere.
