### ISSUE TITLE
Conditional logging

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#223]
Currently we do a lot of logging to the console in the case of errors. However, this is a lot of strings to ship to production. My idea is to create a `log` module which will only log to the console if `process.env.NODE_ENV !== 'production'`. That way these logs can be tree shaken out for production.

The draw back would be no error logging in production which would make problems harder to diagnose.

**Comment by ajaymathur** [comment]
If ok, I can work on this over the week end. 🙂

**Comment by ajaymathur** [comment]
Idea ( not sure if it would be the best way ) :  how about creating a babel plugin to remove `console.log` when NODE_ENV is production (not case sensitive) and in case if we really need any log to be in production we can update syntax as `console.log('#PROD: <message>')` , plugin will only remove #PROD: from this message, this way we will only remove code for prod and not add any line of code as all.

Thoughts 💭 ?

**Comment by ajaymathur** [comment]
This will give us some control over console logs, in case we want to replace them with api calls to log failures, 🤔

**Comment by alexreardon** [comment]
I think that will be too heavy to maintain for this project. My ideal is just to have a module that exposes a 'warn' and 'error' function that only logs to console if `process.env.NODE_ENV !== 'production'`. There are existing tree shaking tools to remove this code when then this conditional is not met.

Something like:

```js
export const warn = (...args: mixed[]) {
  if(process.env.NODE_ENV !== 'production') {
    console.warn(...args);
  }
}
```

**Comment by alexreardon** [comment]
The main purpose of this is to reduce the production bundle size

If it is too difficult then we won't worry about it. We should only be logging in error scenarios

**Comment by alexreardon** [comment]
Done as part of #255
