### ISSUE TITLE
Error compiling react-beautiful-dnd

### ISSUE THREAD

**Issue by nrmad** [atlassian/react-beautiful-dnd#2235]
I have had react-beautiful-dnd installed and functional for a while and out of nowhere I am now getting an error from node_modules about create-react-app being unable to compile the file position.js in the react-beautiful-dnd package. I have looked into breaking changes being pushed to their repo but nothing is different 2 months back, I invalidated my cache and restarted (on webstorm) nothing, finally I deleted my node_modules and reinstalled them but still the error occurs.

./node_modules/react-beautiful-dnd/src/state/position.js

SyntaxError:  /node_modules/react-beautiful-dnd/src/state/position.js Unexpected token, expected ","

// @flow 
import {type Position} from 'css-box-model';
                   ^
What could be causing the error?

Thank you

**Comment by danieldelcore** [comment]
🤔 Hmm this is a weird one. My initial gut-feel is that it's running into flow's syntax and breaking. 
But that would only happen if we're importing from the src directory. 
Could you share some code with me so i can get a better idea of what might be going wrong?

**Comment by nrmad** [comment]
I am not familiar with flow however I would assume everything needed for its operation would be included within the react-beautiful-dnd package? The only code in my project which uses react-beautiful-dnd does not seem to blame because i commented out the entire component and was still receiving the error. What code would you require?

**Comment by danieldelcore** [comment]
No worries at all mate! Happens to me all the time haha! Will close out this issue for now
