### ISSUE TITLE
Support drag along both x-axis and y-axis

### ISSUE THREAD

**Issue by cpylua** [atlassian/react-beautiful-dnd#224]
## Feature request

I just switched from `react-dnd` to `react-beautiful-dnd` for simple list drag-and-drop in my projects, it's awesome!

I did read your design philosophy, but I'm a bit confused about the [Application 5: no drag axis locking](https://github.com/atlassian/react-beautiful-dnd#application-5-no-drag-axis-locking) section (not a native speaker).

So any plan to support drag along both x-axis and y-axis, like this list? Basically it's a single list that wraps to new lines when overflow.

![image](https://user-images.githubusercontent.com/726800/33978119-0732d35e-e0d9-11e7-85cd-96ed0467daa6.png)

Thanks!

**Comment by alexreardon** [comment]
drag axis locking is where you put the draggable item on 'rails' and prevent the user moving at all in a particular direction.

What you are referring to is more of a 'grid' style of layout. At this stage we are not looking to support it - but we may at some point in the future

**Comment by Bexy-Lyn** [comment]
Hi, is there any chance, that this feature may be implemented? It is quite important for my application and I am sure it might be for others, too...

I am wrapping my list with flexbox, so the user is able to see all of his items without scrolling. The list is of dynamic length and the page responsive so I cannot hard code this really.
And currently it only works to move items between rows, with whole rows snapping, but not placing them at a desired position in a row. This is a very confusing user experience :/

I do not want to fix this with a nested dnd workaround, as I am sure that the accessibility would decrease... For now I will make the list single lined and scrollable. But it would be great if there was a way to show all items. I am open to other ideas :)

**Comment by Niubility-SunLight** [comment]
today is 2023、this feature has been worked？

**Comment by brianarpie-forme** [comment]
Hi, my team is also looking for this capability. Reordering a task list that overflows into the next row or column - a grid-style layout. Think of sortable "tiles" on a screen that span multiple columns or rows.

**Comment by brianarpie-forme** [comment]
For those looking, I found https://muuri.dev/ as a good alternative for Grid support.
