### ISSUE TITLE
Source code for examples? 

### ISSUE THREAD

**Issue by philest** [atlassian/react-beautiful-dnd#228]
I'm trying to find the code for the examples— particularly the horizontal list examples— and can't find anything. @alexreardon Where would this be? And where would a tutorial be?

I haven't had much luck just relying on the README to build a multiple horizontal list example. 

Thanks!

**Comment by alexreardon** [comment]
A horizontal list is a simple as aligning your items horizontally (such as using `flex-direction: row`) and then settings the `Droppable > direction` prop to `horizontal`. You will find some examples of this in our [storybook](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/2-single-horizontal-story.js)

**Comment by alexreardon** [comment]
I think when we move to a more comprehensive doc solution we could look at adding a horizontal example #163

**Comment by ilyjs** [comment]
@alexreardon
I need a real working code to start. 
Maybe I'm dumb, but I do not understand how to start without examples. To just copy an example and try it. 
I read the dock and then read it again. Information is confused in the head without an example in which you can try to apply information from the documentation.

**Comment by Slapbox** [comment]
This should really not be closed. This looks like a great library, but I'll almost certainly never get to use it because there's just no guides.

>Oh look at this cool thing!

>That is cool! How do I used it?

>`Closed`

**Comment by alexreardon** [comment]
We are implementing this as a part of our documentation site

**Comment by alexreardon** [comment]
We are also creating a quick start guide and video series. This issue was
closed as the source for all the examples is in the repo

**Comment by tpdineshtp** [comment]
Even i also can not find Source for examples

**Comment by namklabs** [comment]
The examples you see at [All Examples](https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) appear to be loaded from the stories .js files here: [https://github.com/atlassian/react-beautiful-dnd/tree/fc4e6380c63c9b394119937d312a2693f4e5a13b/stories](https://github.com/atlassian/react-beautiful-dnd/tree/fc4e6380c63c9b394119937d312a2693f4e5a13b/stories)

If you look at a file in `/stories` for the example you're interested in, you'll see that it imports a unique component for that example, such as `<InteractiveElementsApp/>` for the Interactive Elements example in `/stories/7-interactive-elements-story.js`. That component's source code will be located in `/stories/src/interactive-elements`.

**Comment by webCoderJ** [comment]
Why don't provide the source code of examples , that's a faster way to get the lib start than read the api-doc and to learn your concept...

**Comment by hsluoyz** [comment]
Video is good. But I don't have time to view all the videos. I need some quick example code to start with. We should have the simplest example showcase together with the code. Like how other projects do it: https://ant.design/components/transfer/
