### ISSUE TITLE
Re-render/flicker after dropping a draggable

### ISSUE THREAD

**Issue by GNDF5000** [atlassian/react-beautiful-dnd#2303]
### Problem / Expected behavior

I have a classic kanban-board type of app which just needs basic drag and drop functionality. Everything works but after dropping a task(draggable) tasks re-render with old order before updating with the actual new order from the parent component. 

### Actual behavior

https://user-images.githubusercontent.com/5756352/131696464-075df132-03d7-4d62-9c66-dc4b5fbfdbe9.mp4

### Steps to reproduce
project is structured like this: 

Parent component which gets data from redux store and passes data to columns which then pass data to tasks

Project (data from redux store) -> BoardView (DragDropContext) -> BoardColumn (Droppable) -> Task (Draggable)

### Suggested solution?
It seems like the problem is the BoardColumn component which passes data to tasks. Once the draggable is dropped provided props change which causes the rerender with old order and after 10ms the main component rerenders and passes new props with the correct order. 

### What version of `React` are you using?
    "react": "^17.0.2",

### What version of `react-beautiful-dnd` are you running?
    "react-beautiful-dnd": "^13.1.0",

### What browser are you using?
Chrome - Version 92.0.4515.159 (Official Build) (64-bit)

### Demo

https://user-images.githubusercontent.com/5756352/131702321-6239fecc-2f13-453d-8fae-4ac2b28e63dd.mp4

**Comment by GNDF5000** [comment]
Solved it for now by combining BoardView (DragDropContext) & BoardColumn (Droppable) into one component

**Comment by huanghaiyang** [comment]
> Solved it for now by combining BoardView (DragDropContext) & BoardColumn (Droppable) into one component

I have same problem , do you have the code

**Comment by Sundvallen** [comment]
@GNDF5000 Did you find a better fix?

**Comment by KatFishSnake** [comment]
Hmm started to have this issue after upgrading to react 18, if anyone else has an issue like that, message here, please so we can debug as a community 🙏

**Comment by okkjoo** [comment]
> Hmm started to have this issue after upgrading to react 18, if anyone else has an issue like that, message here, please so we can debug as a community 🙏

I have the same problem
At the end of the drag,It flashed to another position, and then returned to its rightful position

![GIF](https://user-images.githubusercontent.com/72183335/185729785-9707668a-8029-4a1b-bd8b-e3c5eadeb3e9.gif)

**Comment by R-Bower** [comment]
Also seeing this on React v18.2.0 and NextJS 12.3.1

**Comment by abereghici** [comment]
Did you guys find a workaround for react 18?
