### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by philest** [atlassian/react-beautiful-dnd#233]
I'm creating a list with 26+ draggable elements. I'm guessing that an event listener is added to each. That seems like it might be creating some sort memory leak which seems to ultimately crash the app. Not so sure about how to proceed here. 

`(node) warning: possible EventEmitter memory leak detected. %d listeners added.`

**Comment by alexreardon** [comment]
Interesting. Without having more information it will be hard to action this. Would you be able to create a reproducible example? Here is a boilerplate to start from:

https://www.webpackbin.com/bins/-Kr9aE9jnUeWlphY8wsw

**Comment by alexreardon** [comment]
Until more information comes forward i'll close this one for now
