### ISSUE TITLE
Long press does not work with Apple Pencil

### ISSUE THREAD

**Issue by brianarpie** [atlassian/react-beautiful-dnd#234]
Long pressing elements with the apple pencil doesn’t make them draggable as expected. Any idea why this doesn’t work ? Any insight as to how mobile support was added with regards to touch events ?

**Comment by alexreardon** [comment]
I currently do not have access to this hardware so it is a little hard to see if the issue is with the library itself or its usage. Can you please confirm if it works on our [boilerplate](https://www.webpackbin.com/bins/-Kr9aE9jnUeWlphY8wsw)?

**Comment by brianarpie** [comment]
Thanks for the response. I played with the boilerplate for a while and was able to get it to work consistently but only when holding the pencil at an angle (about < 45 degrees with respect to the iPad screen). Without this trick and instead using the pencil more naturally it works maybe 1 out of every 5 attempts. I was less fortunate testing out this technique with my own implementation (which is inside of a scrolling container) which I only got to work maybe 1 out of every 15 attempts.

**Comment by bradleyayers** [comment]
If I was to guess, I’d say iOS uses a more sensitive hysteresis threshold for a pencil than a finger for determining when it has moved from it’s starting position. I’d guess it’s just really hard to keep the pencil truely stationary for long enough to trigger the dnd lift.

You could confirm this by playing with a touchstart / touchmove demo that shows you the events that are emitted and see if you’re able to avoid having the touchmove event emitted

**Comment by alexreardon** [comment]
I tried it out on a surface pro last night and it worked great. I suspect it might have something to do with force press action.

**Comment by brianarpie** [comment]
@bradleyayers I played with a touchstart / touchmove demo and you're absolutely right, with the apple pencil it's impossible to trigger a touchstart event without firing a series of touchmove events afterwards. Although I'm skeptical that translates to an explanation as to why initiating the touchstart with the pencil at an angle had a different effect than when held perpendicularly. 🤔

**Comment by brianarpie** [comment]
@alexreardon Thanks for the suggestion! I just played around with the boilerplate again and discovered something new. It's not actually the angle of the pencil that matters, it's the amount of pressure I apply when making the gesture. If I apply any reasonable amount of pressure (easier to do with the pencil perpendicular) the lift is not triggered. If I apply no to barely any pressure the dnd lift works every time. 🎉

**Comment by alexreardon** [comment]
We do some calculations to figure out if a user was attempting to force press. If they are we opt out of the drag. This allows for maximum flexibility with other elements. You could change this behaviour for yourself by adding a `touchforcechange` event handler to the element and calling `event.stopPropigation()` (and probably `event.preventDefault()`) on the event. This would prevent the library from being aware of the event and so it would not stop a drag. Keep in mind that by doing this you would be disabling force press events for that element. I suspect this will be exactly what you are after.

Cheers

**Comment by ct-gilford** [comment]
@alexreardon Hi, it seems that Apple Pencil is still unable to drag. I tested with the [Simple List](https://react-beautiful-dnd.netlify.app/iframe.html?id=single-vertical-list--basic) example too and it's not working. Is there any documentation that shows a workaround method to make it work?
