### ISSUE TITLE
redux warning in development mode

### ISSUE THREAD

**Issue by eunju-jung** [atlassian/react-beautiful-dnd#2345]
### Expected behavior
When using react-beautiful-dnd in the development environment, 
I want to disappear the redux warning like the image.
How can I get rid of this warning?
![image](https://user-images.githubusercontent.com/85203750/145149114-affe6664-cfcc-48ed-ad86-12a45e51bbd2.png)

### Actual behavior
I already use redux in my project. (ver4.0.5) 
![image](https://user-images.githubusercontent.com/85203750/145149406-f299d98c-cd96-4491-a5bd-1d5587210b61.png)

React-beautiful-dnd is also using redux. When the NODE_ENV is development , it seems to be crashing.

### Steps to reproduce
When the NODE_ENV is development, yarn start. 

### What version of `React` are you using?
^17.0.2

### What version of `react-beautiful-dnd` are you running?
^13.1.0

### What browser are you using?
google chrome

**Comment by eunju-jung** [comment]
self solved!

**Comment by ahvocado** [comment]
@eunju-jung Can you share how you solved?

**Comment by ahvocado** [comment]
Can you share how you solved? I want to get rid of this warning, remaining webpack development mode:)
