### ISSUE TITLE
ES module build

### ISSUE THREAD

**Issue by foisonocean** [atlassian/react-beautiful-dnd#235]
## Bug or feature request?
feature request

Could you provide es module build, which make tree-shaking available in build tools like `webpack` and `rollup`?

**Comment by alexreardon** [comment]
We currently have a distribution build, but an esmodule one would be useful as well.

![21i2jk](https://user-images.githubusercontent.com/2182637/34277213-ea53a260-e6f8-11e7-903e-2f03f80edd0f.jpg)

**Comment by alexreardon** [comment]
Closed by #369
