### ISSUE TITLE
Use react-beatiful-dnd with images masonry grid

### ISSUE THREAD

**Issue by nowiko** [atlassian/react-beautiful-dnd#2358]
Hello,  this is not the bug, but more the help request.
I am trying to create the draggable images masonry, but I am not sure how to properly integrate two separate packages.
For masonry I am using the [masonic](https://github.com/jaredLunde/masonic), which is based on the [react-virtualized](https://github.com/bvaughn/react-virtualized).

I tried to follow:
- [official virtual lists documentation](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/virtual-lists.md)
- [tutorial](https://www.freecodecamp.org/news/how-to-add-drag-and-drop-in-react-with-react-beautiful-dnd/)

My code sample is [here](https://codesandbox.io/s/masonic-example-forked-z4t2t?file=/src/index.js) 

I am constantly getting `Unable to find draggable element with id:` error.

Please, could somebody help me to define what I am doing wrong/missing?

**Comment by MustafovaSemra** [comment]
hi, I managed to combine react-beatiful-dnd with MUI image masonry. So far performing well together.

**Comment by nowiko** [comment]
Hi @MustafovaSemra thanks, it would be great if you are able to share a small code snippet. Also, my concern, if its possible to make the masonry virtual, to not load the large images list.

**Comment by MustafovaSemra** [comment]
I upload images from my local machine and display them in masonry.

`  const renderImages = (uploadedFiles: any[]) => {
    return (
      <DragDropContext onDragEnd={handleOnDragEnd}>
        <Droppable droppableId="images">
          {(provided) => (
            <ImageList
              {...provided.droppableProps}
              ref={provided.innerRef}
              sx={{ width: "100%", height: "fit-content" }}
              variant="masonry"
              cols={2}
              gap={10}>
              {uploadedFiles.map((item, index) => {
                return (
                  <Draggable key={item.title} draggableId={item.title} index={index}>
                    {(provided) => (
                      <ImageListItem {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef}>
                        <img
                          src={item.link}
                          srcSet={item.link}
                          alt={item.title}
                          style={{ borderRadius: "10px", zIndex: 3 }}
                          loading="lazy"
                        />
                      </ImageListItem>
                    )}
                  </Draggable>
                )
              })}
              {provided.placeholder}
            </ImageList>
          )}
        </Droppable>
      </DragDropContext>
    );
  };`

**Comment by nowiko** [comment]
@MustafovaSemra thanks for your help, I mark this issue as closed.
