### ISSUE TITLE
Drag and Drop multiple select items

### ISSUE THREAD

**Issue by alakdam07** [atlassian/react-beautiful-dnd#2364]
I am using React js for my app. I am trying create an Drag and drop app. For Drag and drop I am using [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md). From this package, I can able to drag and drop an item from one table to another table. **[Here is my current app](https://codesandbox.io/s/drag-drop-f7k2n).**

I want to select multiple items by using tab keyboard and then drop it to dropzone. [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md) has keyboard press option.

**Issues:**
 1. I am having issue with with selecting multiple items by pressing `Tab keyboard`. I found a [demo-app](https://codesandbox.io/s/stoic-shockley-kxmls?file=/src/components/MultiDrag/task-app.jsx:1013-1020), where user can select multiple items by using tab. Code author created a Javascript helper function, where user can select multiple items from drag. I don't understand the helper function. I want to create helper function like the [demo-app's helper function](https://codesandbox.io/s/stoic-shockley-kxmls?file=/src/components/MultiDrag/utils.js).

 2. I really don't get from [demo-app](https://codesandbox.io/s/stoic-shockley-kxmls?file=/src/components/MultiDrag/task-app.jsx:1013-1020), how to get multiple selected items `DragDropContext's` `onDragEnd`. currently when I console the `onDragEnd's` result I can see only one item object even though I dragged and dropped multiple items.

**Reproduced the app**

I Reproduced my app and share to [code-sandbox](https://codesandbox.io/s/drag-drop-f7k2n).

**Really appreciate if someone help me out 🙏🏾🙏🏾**

**This is my drag and drop parent code**

    import React, { CSSProperties, useState } from "react";
    import {
      DragDropContext,
      DraggingStyle,
      Droppable,
      NotDraggingStyle,
    } from "react-beautiful-dnd";

    import Multipicking from "./Multipicking";

    const getItemStyle = (
      isDragging: boolean,
      level: number,
      draggableStyle?: DraggingStyle | NotDraggingStyle
    ): CSSProperties => {
      const isTopLevel = level === 2;
      return {
        display: "flex",
        alignItems: "center",
        userSelect: "none",
        padding: "1rem",
        height: isTopLevel ? 58 : 40,
        margin: "0 0 0.5rem 0",
        borderLeftColor: "lightblue",
        borderLeftWidth: isTopLevel ? 0 : 3,
        borderLeftStyle: "solid",
        backgroundColor: "#6a93cb",
        backgroundImage: "linear-gradient(315deg, #6a93cb 0%, #a4bfef 74%)",
        ...draggableStyle,
      };
    };

    const DROPPABLE_GROUP_LIST = "droppableGroupList";

    const ZoneGroups = () => {
      const displayGroups = [
        {
          id: "GF",
          level: 2,
          name: "book",
          parent: "G",
        },
        {
          id: "FA",
          level: 2,
          name: "fruit",
          parent: "F",
        },
        {
          id: "FEAABA",
          level: 6,
          name: "fish",
          parent: "FEAAB",
        },
        {
          id: "HB",
          level: 2,
          name: "juice",
          parent: "H",
        },
      ];

      const SelectedGroups = [
        {
          id: "LF",
          level: 2,
          name: "Laptop",
          parent: "G",
        },
        {
          id: "AJ",
          level: 2,
          name: "Fridge",
          parent: "F",
        },
        {
          id: "SKSK",
          level: 6,
          name: "TV",
          parent: "FEAAB",
        },
        {
          id: "HB",
          level: 2,
          name: "Bed",
          parent: "H",
        },
      ];

      const [selectedGroups, setSelectedGroups] = useState(SelectedGroups);
      const isDisabledAddGroup = false;

      return (
        <DragDropContext
          onDragEnd={(res): void => {
            const group = displayGroups.find((g) => g.id === res.draggableId);
            if (res.destination?.droppableId === DROPPABLE_GROUP_LIST && group) {
              // After selected the item, push to local state.
              setSelectedGroups((selectedGroups) => [...selectedGroups, group]);
            }
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
            }}
          >
            <div style={{ marginRight: 20 }}>
              <h1>Drop in here</h1>
              <Droppable droppableId={DROPPABLE_GROUP_LIST}>
                {(provided, snapshot): React.ReactElement => (
                  <div
                    style={
                      snapshot.isDraggingOver ? { border: `5px solid grey` } : {}
                    }
                  >
                    <div ref={provided.innerRef} style={{ height: "100%" }}>
                      {selectedGroups.map((item) => (
                        <div
                          key={item.id + item.level}
                          style={getItemStyle(false, item.level)}
                        >
                          {`${item.level} ${item.name}`}
                        </div>
                      ))}
                      {provided.placeholder}
                    </div>
                  </div>
                )}
              </Droppable>
            </div>
            <div>
              <h1>Drag from here</h1>
              <Droppable droppableId="droppable2">
                {(provided): React.ReactElement => (
                  <div ref={provided.innerRef}>
                    {displayGroups.map((item, index) => (
                      <Multipicking
                        selected={index}
                        key={index}
                        isDisabledAddGroup={isDisabledAddGroup}
                        item={item}
                        index={index}
                      />
                    ))}
                    {provided.placeholder}
                  </div>
                )}
              </Droppable>
            </div>
          </div>
        </DragDropContext>
      );
    };

    export default ZoneGroups;

**This is the dragging item component**  

    import React from "react";
    import {
      Draggable,
      DraggingStyle,
      NotDraggingStyle,
    } from "react-beautiful-dnd";

    const multiSelect = (itemId) => {
      console.log(itemId);
    };

    const getItemStyle = (
      isDragging: boolean,
      level: number,
      draggableStyle?: DraggingStyle | NotDraggingStyle
    ): CSSProperties => {
      const isTopLevel = level === 2;
      return {
        display: "flex",
        alignItems: "center",
        userSelect: "none",
        padding: "1rem",
        height: isTopLevel ? 58 : 40,
        margin: "0 0 0.5rem 0",
        borderLeftColor: "lightblue",
        borderLeftWidth: isTopLevel ? 0 : 3,
        borderLeftStyle: "solid",
        background: isDragging ? "lightblue" : "#01baef",
        ...draggableStyle,
      };
    };

    const multipicking = ({ selected, item, index, isDisabledAddGroup }) => {
      const onKeyDown = (event: KeyboardEvent): void => {
        event.preventDefault();
        performAction(event);
      };

      const wasMultiSelectKeyUsed = (event: KeyboardEvent): boolean =>
        event.shiftKey; // check if user pressed shift or not

      const performAction = (event): void => {
        if (wasMultiSelectKeyUsed(event)) {
          return multiSelect(item); // multiSelect function
        }
      };

      return (
        <Draggable
          key={item.id}
          draggableId={item.id}
          index={index}
          isDragDisabled={isDisabledAddGroup}
        >
          {(provided, snapshot): React.ReactElement => (
            <div
              ref={provided.innerRef}
              {...provided.draggableProps}
              {...provided.dragHandleProps}
              style={getItemStyle(
                snapshot.isDragging,
                item.level,
                provided.draggableProps.style
              )}
              onKeyDown={onKeyDown}
            >
              {`${item.level} ${item.name}`}
            </div>
          )}
        </Draggable>
      );
    };

    export default multipicking;

**Comment by peeyush-drag** [comment]
@alakdam07 Were you able to implement this feature? If so will you please share an example?

**Comment by alakdam07** [comment]
Sorry! I don't remember. It was long time ago
