### ISSUE TITLE
Nested vertical list: Cannot drop in droppable that just mounted

### ISSUE THREAD

**Issue by Liboul** [atlassian/react-beautiful-dnd#2377]
Hey 👋 Love the library ❤️

### Expected behavior

In a nested vertical list (orderable groups containing items that can be moved across groups), with a variable number of groups, it's impossible to drop "long enough" items into a group that just mounted.

Minimal use case available here with comments: https://codesandbox.io/s/react-beautiful-dnd-cannot-drop-in-droppable-that-just-mounted-de1ev6

### Actual behavior

Newly mounted `Droppable`s should behave like `Droppable`s that were mounted at the same time as the `DragDropContext`.

### Steps to reproduce

After creating a nested vertical list (draggable items across draggable groups):
  1. Witness that you can drag and drop every item into every group, even empty groups (which have a min-height as the doc suggests)
  2. Mount a new empty-group (again, with a min height)
  3. Witness that you can you drop one-line items into the newly mounted group
  4. Witness that you cannot drop longer items into the newly mounted group, no matter if you drag the item from the top or the bottom

### Suggested solution?

I haven't investigated the internals of the library. My best guess would be that some kind of miscalculation happens, but only for newly mounted droppables.

### What version of `React` are you using?

16.14. Bug confirmed with other versions (18-next, 17.0.2, ...)

### What version of `react-beautiful-dnd` are you running?

13.1.0. Bug also confirmed with 12.2.0.

### What browser are you using?

Latest version of Chrome. Bug also confirmed with latest version of Safari

### Demo

https://codesandbox.io/s/react-beautiful-dnd-cannot-drop-in-droppable-that-just-mounted-de1ev6

Here's a picture summing up the bug:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/16024169/156741194-659850b0-9a13-4233-97fd-f69304496efc.png">

**Comment by awais000** [comment]
Hey, I just looked at the sandbox and I don't think the issue is with new added group/ dropable.  If the card above "long enough" doesn't have some height then it's causing the issue.

https://codesandbox.io/s/react-beautiful-dnd-cannot-drop-in-droppable-that-just-mounted-forked-zgf0tt?file=/index.js

**Comment by Liboul** [comment]
Update: Moving to [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) fixed the issue
