### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by ximex** [atlassian/react-beautiful-dnd#2388]
add `react` `^18.0.0` and `react-dom` `^18.0.0` as `peerDependencies`

**Comment by jacokok** [comment]
This will be great. Also running strict mode with react 18 does not work.

**Comment by Paul6552** [comment]
This library is not supported anymore. 

But have a look here: [react-forked/dnd](https://github.com/react-forked/dnd/issues/293). 
Support for react 18 is on the way

**Comment by 100terres** [comment]
Hi! As mentionned by @Paul6552, I'll work to add support for react v18 on [`@react-forked/dnd`](https://github.com/react-forked/dnd) package. It's a fork of react-beautiful-dnd. You can read [this blog post](https://dev.to/100terres/rbd-is-dead-long-life-rfd-1n9e) for more info :slightly_smiling_face: 

I'll keep you updated here in this issue and on the [issue](https://github.com/react-forked/dnd/issues/293) on [`@react-forked/dnd`](https://github.com/react-forked/dnd) repo. 

You can also follow the progress here in this [draft PR](https://github.com/react-forked/dnd/pull/316).

**Comment by mehrnaznazari** [comment]
[@react-forked/dnd] doesn't work with React 18 and StrictMode.
https://codesandbox.io/s/determined-bouman-k81oqv

**Comment by Xhale1** [comment]
🎉 [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) now supports React 18 and react strict mode!

1. `npm install @hello-pangea/dnd`
2. Replace all imports of `react-beautiful-dnd` with `@hello-pangea/dnd`
3. Enjoy :)

**Comment by danieldelcore** [comment]
Hey folks, this is available in the latest version. Let's continue the conversation around strictmode here: https://github.com/atlassian/react-beautiful-dnd/issues/2350

**Comment by danieldelcore** [comment]
https://github.com/atlassian/react-beautiful-dnd/releases

Latest patch should have it 😄.

Sorry no plans there, I've been helping with this lib in a personal capacity at the moment.
