### ISSUE TITLE
While dragging (holding a card), the window won't scroll down

### ISSUE THREAD

**Issue by TylerL-uxai** [atlassian/react-beautiful-dnd#24]
The window doesn't scroll down like you need it to while holding a card. Good luck!

**Comment by alexreardon** [comment]
I am unable to replicate this issue

Can you please provide some more information:

- browser
- ideally a link to an example that replicates the issue

Cheers!

**Comment by TylerL-uxai** [comment]
Okay, but atlassian really should be paying me for all this work I put into their project

http://i.imgur.com/tPtrUWk.gifv

**Comment by alexreardon** [comment]
Oh, i see. Yeah - auto scrolling is currently not a supported feature

**Comment by alexreardon** [comment]
Closing as duplicate #27

**Comment by alexreardon** [comment]
Thanks for reaching out @TylerL-uxai and for the gif!

![dance](https://user-images.githubusercontent.com/2182637/29201875-cbea3e76-7ea5-11e7-80c9-6733726f19b9.gif)

**Comment by alexreardon** [comment]
Also, the work around is to scroll with your mouse (not ideal i know!)
