### ISSUE TITLE
Unable to install w/react 18

### ISSUE THREAD

**Issue by Ddupasquier** [atlassian/react-beautiful-dnd#2408]
I'm attempting to install this onto a React 18 application. From what I've read in the other issues is that it should install, but not function properly in strict mode. So I pulled out the strict mode and attempted to install, but instead got this:

`npm install react-beautiful-dnd@latest

npm ERR! code ERESOLVE

npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR! 

npm ERR! While resolving: practice-typsescript@0.1.0

npm ERR! Found: react@18.1.0

npm ERR! node_modules/react

npm ERR!   react@"^18.1.0" from the root project

npm ERR! 

npm ERR! Could not resolve dependency:

npm ERR! peer react@"^16.8.5 || ^17.0.0" from react-beautiful-dnd@13.1.0

npm ERR! node_modules/react-beautiful-dnd

npm ERR!   react-beautiful-dnd@"13.1.0" from the root project

npm ERR! 

npm ERR! Fix the upstream dependency conflict, or retry

npm ERR! this command with --force, or --legacy-peer-deps

npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Seems to me that it's mad that I'm using React 18. Any workarounds? Or is this just deprecated?

**Comment by hnrtk** [comment]
I'm having the same problem, even with react forked lib..

**Comment by jvitoralmeida01** [comment]
I was having the same issue. One work around I found was to use "npm install --save react-beautiful-dnd --legacy-peer-deps" instead.

Basically npm will ignore the version dependency that the lib has with react 16. It's not ideal, but will install it

**Comment by wslp12** [comment]
I am using more than React 18 and npm 8 versions. The above problems are occurring, and you can consider using a lower version of npm and yarn temporarily.

The answer is that this library supports React 18 version, but I have one question.

Why is there a react on peerDependencies?

Is there a big problem with dependencies? Is there a problem with node_modules capacity increasing exponentially?

**Comment by KrzysztofZiemski** [comment]
same

**Comment by aalrayes** [comment]
same issue

**Comment by ErikHovhannisyanAmotek** [comment]
> I was having the same issue. One work around I found was to use "npm install --save react-beautiful-dnd --legacy-peer-deps" instead.
> 
> Basically npm will ignore the version dependency that the lib has with react 16. It's not ideal, but will install it

Wont work for typescript

**Comment by alex-pominov** [comment]
I made it work by switching to `ReactDom.render` method, instead of new `ReactDom.createRoot` api. This way you can still use DnD with react 18 and StrictMode.

**Comment by thanhnam46** [comment]
> I was having the same issue. One work around I found was to use "npm install --save react-beautiful-dnd --legacy-peer-deps" instead.
> 
> Basically npm will ignore the version dependency that the lib has with react 16. It's not ideal, but will install it

I followed the above instruction and it works fine

**Comment by aashutoshshr** [comment]
`npm install --save react-beautiful-dnd --legacy-peer-deps` worked for us as well

**Comment by Meligy** [comment]
There's a workaround here:
https://github.com/atlassian/react-beautiful-dnd/issues/2399#issuecomment-1167427762

**Comment by Xhale1** [comment]
I released a fork of this project which natively supports React 18 and strict mode (with the new `createRoot` api)

A few changes had to be made to the library to get it to work with React 18's development mode changes. Hoping to continue development there. It's built off of @100terres's incredible work (they converted the library to TypeScript).

Run `npm install @hello-pangea/dnd` and replace all imports of `react-beautiful-dnd` with `@hello-pangea/dnd` (I just did a find all and replace)

https://github.com/hello-pangea/dnd

**Comment by EdmundsEcho** [comment]
@Xhale1 Thank you!!  This is a great package. I am thankful for your choosing to continue to support the critical up-keep. - E

**Comment by danieldelcore** [comment]
Hey folks, have accepted this PR, closing this issue now. Will cut a release of RBD today

https://github.com/atlassian/react-beautiful-dnd/pull/2429

**Comment by masadamsahid** [comment]
> 🎉 [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) now supports React 18 and react strict mode!
> 
> 1. `npm install @hello-pangea/dnd`
> 2. Replace all imports of `react-beautiful-dnd` with `@hello-pangea/dnd`
> 3. Enjoy :)

Worked on TS. Nice. Thanks👍
