### ISSUE TITLE
Bug - Not supported

### ISSUE THREAD

**Issue by khanfaysal** [atlassian/react-beautiful-dnd#2416]
## Note: Not supported react-beautiful-dnd with React 18.2.0 version

When I want to try react-beautiful-dnd with the latest version of React then occur error.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: drag-drop-app@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.5 || ^17.0.0" from react-beautiful-dnd@13.1.0
npm ERR! node_modules/react-beautiful-dnd
npm ERR!   react-beautiful-dnd@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.     
npm ERR!
--->

**Comment by Ridermansb** [comment]
Same here

**Comment by danieldelcore** [comment]
Accepted react versions have been updated. Thanks for the patience on this folks
