### ISSUE TITLE
Draggable that is not inside a Droppable

### ISSUE THREAD

**Issue by kontrafiktion** [atlassian/react-beautiful-dnd#242]
## Bug or feature request?
feature request

I have a "source list" with images (a list of "exercises" for a workout)
I want to drag an "exercise" from the source list to a target list (the "workout").

An element in the source should not immediately disappear. The source list rather is a list of "templates" and dragging creates an "instance", so removing the item from the source list is not intuitive.

The source should not be a Droppable. 

On the target list I would like to use all the features of react-beautiful-dnd.

Perhaps some of this is already possible, but https://github.com/atlassian/react-beautiful-dnd/issues/188 would make this even more difficult. 

You say that react-beautiful-dnd "is not a general purpose drag and drop library" but I really like the 'physicality' so I would really love to be able to use it.

**Comment by alexreardon** [comment]
At this time we are not support clone dragging. For an explanation see here: https://github.com/atlassian/react-beautiful-dnd/issues/229#issuecomment-352328855
