### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by shestakov-vladyslav** [atlassian/react-beautiful-dnd#2428]
Please update dependencies
![image](https://user-images.githubusercontent.com/18069756/178742257-c6b1d2fc-1984-40ae-9d57-34455d4759a0.png)

**Comment by Xhale1** [comment]
This is resolved with [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) (a drop-in fork of this lib)

1. Run `npm install @hello-pangea/dnd`
2. Replace all instances of `react-beautiful-dnd` with `@hello-pangea/dnd`
3. You should be good to go

If you run into any issues please open an issue in the [Pangea Dnd](https://github.com/hello-pangea/dnd/issues) repo

**Comment by oskarwrobel** [comment]
@danieldelcore 🙏 

![atlassian](https://user-images.githubusercontent.com/1057056/186501739-d28d9726-428f-47ef-bb75-317d470a844f.jpeg)

**Comment by danieldelcore** [comment]
Haha! I'd be happy to look at a pr if you folks are up to it!

**Comment by oskarwrobel** [comment]
@danieldelcore Thanks. There is already a PR for that https://github.com/atlassian/react-beautiful-dnd/pull/2429 prepared by @jankanty. Unfortunately, one CI check has failed ([test-a11y](https://app.circleci.com/pipelines/github/atlassian/react-beautiful-dnd/525/workflows/54e76c3e-62ac-4bf6-b6f9-8011d3e3efd5/jobs/18959)) but it might not be related to the peer dependencies update.

**Comment by danieldelcore** [comment]
Yeah looks unrelated, I'm trying to figure out what's going on now, but mostly looks fine to me

**Comment by danieldelcore** [comment]
Accepted react versions have been updated. Thanks for the patience on this folks
