### ISSUE TITLE
mobile can not scroll when dragged

### ISSUE THREAD

**Issue by belief-cyf** [atlassian/react-beautiful-dnd#243]
![0gd303 kn ae g mb z 7s](https://user-images.githubusercontent.com/19991842/34507091-e37989fe-f06d-11e7-84a6-bbb3c3cd8f20.png)

Android ipad after I dragged，
The browser can not scroll。
github demo also like this.

**Comment by lukebatchelor** [comment]
Hiya @belief-cyf, We are aware of this, it's a current limitation that is mentioned in the readme and is planned to be looked at as a part of #27 

I'll close this issue for now, but feel free to follow that one.

Cheers

**Comment by belief-cyf** [comment]
ok, thank you ~
Cheers
