### ISSUE TITLE
Performances and scrolling issues 

### ISSUE THREAD

**Issue by loaibassam** [atlassian/react-beautiful-dnd#244]
We're using this plugin for our tasks boards on Plutio.com, which looks like this:

<img width="1465" alt="image 2018-01-03 at 7 11 59 pm" src="https://user-images.githubusercontent.com/4785390/34535524-0d2d829a-f0ba-11e7-8f4d-ea7906b0455a.png">

1) The tasks list could get long, so we wanted to try and limit its hight to the hight of the window, and have a scrollable body for each task groups, just like on Trello. 

When we tried that however, we couldn't figure out how to make it scroll as we are dragging the tasks. 

2) When we have around 100 tasks or more, dragging and dropping becomes laggy, has anyone elze experienced this before?

You can login to the test account here: test.plutio.com demo-team@loaidesign.com 5749388

**Comment by alexreardon** [comment]
Hi @loaibassam,

Thanks for reaching out

Regarding 1: auto scrolling - we will be working on this soon #27 
Regarding 2: performance - this is already almost shipped #226 

Unrelated: could you add some gifs of your app to our #164 page? Your app looks great!

**Comment by loaibassam** [comment]
@alexreardon thank you so much! I've just done that :D
