### ISSUE TITLE
 Invalid child context Warning

### ISSUE THREAD

**Issue by tnrich** [atlassian/react-beautiful-dnd#250]
Hey there, I just started using this library and am encountering the following warning (I'm using multiple horizontal lists within one DragDropContext): 

```
Warning: Failed child context type: Invalid child context `private-drag-drop-key-do-not-use-store-droppable-id` of type `number` supplied to `Droppable`, expected `string`.
    in Droppable (created by Connect(Droppable))
    in Connect(Droppable) (created by Editor)
```

Do you have any idea what might be causing this warning to show up?

I can give more informative details if necessary but am just curious if someone has an idea about this.

**Comment by alexreardon** [comment]
Hi @tnrich,

It looks like you are using a `droppableId` of type `number` on a `Droppable` when it should be a `string`. 

```diff
- <Droppable droppableId={5}>
+ <Droppable droppableId={'5'}>
```

Cheers!

**Comment by tnrich** [comment]
Ah okay perfect I was indeed doing that and didn't realize it needed to be
a string. I'll change that. Thanks!
