### ISSUE TITLE
Drag Content doesn't back to original position, when drag it to index 0

### ISSUE THREAD

**Issue by crapthings** [atlassian/react-beautiful-dnd#255]
v4

https://youtu.be/Yf3PShBgDaA

i didn't finish save state procedure, but u can see after i release mouse button, the deck doesn't go back to original position if i drag it to index 0

https://github.com/crapthings/kanban-prototype

if u don't have meteor

```bash
curl https://install.meteor.com/ | sh
```

then

```bash
git clone https://github.com/crapthings/kanban-prototype
cd kanban-prototype
meteor npm i
meteor
```

open http://localhost:3000

v4 is really really fast good job
this example was made 2.6.4 before upgrade to 4
it freezes browser while dragging.

**Comment by alexreardon** [comment]
Ensure that you comply with the new api. Watch for the style tag difference. Also and index is now required. without a stand alone demo it is hard to debug. If u could create a webpack bin that would be most helpful

**Comment by alexreardon** [comment]
The DraggableProvided has changed shape a bit

**Comment by alexreardon** [comment]
Also your repo looks like it is private

**Comment by crapthings** [comment]
i did add index, oh its a fork, let me set it to public

**Comment by crapthings** [comment]
curl https://install.meteor.com/ | sh

git clone https://github.com/crapthings/react-beautiful-dnd-255
cd kanban-prototype
meteor npm i
meteor

**Comment by alexreardon** [comment]
If u could move into a webpack bin and see if u can reproduce what you are seeing?

**Comment by MateuszSzerszynski** [comment]
I was able to reproduce similar problem, it happened only with newest API.
Steps to reproduce:
- create `DragDropContext`, `Draggable` and a list of `Draggable`. First `Draggable` has index === 0
- try to move the first item

Row was not moved (drag didn't start) and there were some errors on the console.
![image](https://user-images.githubusercontent.com/6825492/34831741-14c16902-f6e8-11e7-87cd-4a856406b78d.png)


Looks like problem is in this line: https://github.com/atlassian/react-beautiful-dnd/blob/master/src/state/dimension-marshal/dimension-marshal.js#L287 - `request` has id `0` 

Workaround in my case was quite simple: I did not use index `0`, everything works fine after that 🙂

**Comment by alexreardon** [comment]
Super strange! I think I know the issue. Looks like 0 is failing a truthy check somewhere which should be testing for undefined

**Comment by alexreardon** [comment]
Can you please put your setup in a webpack bin so I can reproduce? Cheers

**Comment by alexreardon** [comment]
It looks like you are setting the Id as the number 0. Is the correct?

**Comment by alexreardon** [comment]
@MateuszSzerszynski it looks like your issue is that you are using the number `0` as your draggableId rather than a string (which could be the string `"0"`). You might be getting away with some implicit conversion around the place, but things could go back in the future if we do some more string operations on the value. (contrived example: `draggableId.toLowerCase()`). I can replicate it here by changing the id's from strings to numbers: https://www.webpackbin.com/bins/-L2b0MwJ3Kantxbm2BQp

@crapthings I am still not sure what your issue is. If you could create

**Comment by alexreardon** [comment]
I am not super keen to install meteor to debug this issue 😄

**Comment by crapthings** [comment]
LoL

try move any deck onto index 0 then release mouse you will see that it won't go back to original position, it goes index 1 first then back to original position

https://www.webpackbin.com/bins/-L2bvibJN4L2-3tkHuG_

**Comment by alexreardon** [comment]
Thanks for creating an example. Your onDragEnd function is not actually reordering results (which is part of the contract). I have forked your example and fixed it by reordering the results onDragEnd:

https://www.webpackbin.com/bins/-L2c9vDApF582FFbHsxW

**Comment by crapthings** [comment]
i think the issue is not about save result.

it looks weird to me if i drag deck to index 0, other position is okay only index 0.
imagine deck 0 is locked then u reorder/drag deck to 0, the dragging context will failed to reorder then overlay on index 1 then go back to original position, this only happend on index0,  others seem fine.

**Comment by alexreardon** [comment]
I am not following sorry. Can you please phrase your observation another way? I'll try to a take a look on monday
