### ISSUE TITLE
Aesthetics of DND

### ISSUE THREAD

**Issue by maasha** [atlassian/react-beautiful-dnd#261]
I love the notion that beautiful DND is about moving objects as in the real world. I have two observations regarding the [examples](https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)...

1. When you click on a item the hand cursor should switch to grab. That is what you do in real life: you grab the object and then move it.
2. Dragged objects are highlighted by a nifty green color. While this is nice, that never happens to me in real life. Rather I would expect a shadow of the object.

Just my 5 cent ...

**Comment by alexreardon** [comment]
Hi @maasha,

All good points! The library is unopinionated about styling so as a consumer you can style `Draggable` and `Droppable` components how you like. The examples use fairly intense changes (eg a green background) for the purpose of illustration and to keep within a cartoonish style - it is adventure time flavoured. However, you are welcome to use whatever styles, including cursor styles, you like!

Also, as of `4.0.` we now ship with out [of the box cursor styles](https://github.com/atlassian/react-beautiful-dnd#preset-styles) which has your exact cursor suggestion. 

Thanks for thinking critically about these things

Cheers

**Comment by maasha** [comment]
> Also, as of 4.0. we now ship with out of the box cursor styles which has your exact cursor suggestion.

Right now the cursor hand closes only when you start moving the object. It should in my mind close when you click the object!
