### ISSUE TITLE
Dimension clipping does not account for mid-drag scroll correctly when multiple Droppables share a scroll container

### ISSUE THREAD

**Issue by jaredcrowe** [atlassian/react-beautiful-dnd#266]
## Bug or feature request?
Bug

### Expected behavior
Clipped dimensions account for mid-drag scrolling when multiple Droppables share a scroll container.

### Actual behavior
When multiple Droppables share a scroll container it does not appear as if the subject's scroll position is updated during a drag.

### Steps to reproduce
1. [View the multiple vertical lists stress test story.](https://react-beautiful-dnd.netlify.com/?selectedKind=multiple%20vertical%20lists&selectedStory=stress%20test&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)
2. Lift an item with the mouse and drag it over the Zeta list.
3. While still dragging, scroll the container down then drag the item over the top of the Eta list. The app should still behave as if you're dragging over the Zeta list.

### Demo
[Video demo here.](http://i.imgur.com/7dJUplx.gifv)

### Browser version
Chrome 63.0.3239.132

**Comment by alexreardon** [comment]
Fun times. If they share a parent I can reproduce. Thanks @jaredcrowe

**Comment by alexreardon** [comment]
I found the issue. It is to do with the placeholder spacing addition in `get-draggable-over`. I'll put up a PR with the fix and tests soon

**Comment by jaredcrowe** [comment]
FWIW I still get the rapid flickering between Zeta and Eta when I lift from Zeta, so it might not be only to do with the placeholder stuff.

**Comment by alexreardon** [comment]
Thanks @jaredcrowe . I think it is the same issue :). I'll make a pr soon for us to check
