### ISSUE TITLE
Auto scrolling

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#27]
Current mitigation: use your trackpack or mouse to scroll while you are dragging. There was actually a lot of work done to make sure scroll is being listened to directly

Currently when dragging with a mouse the window will not automatically scroll. Nor will scroll containers automatically scroll. We *could* support this behaviour.

A few things to consider:

**Scroll containers**
- Currently the library does not do too much with the DOM - it just works. Introducing a feature like this might require an additional export: a scrollable container. Perhaps also even an option for Droppables to support auto scrolling. Should it be opt in or default?
- Window auto scrolling would be relatively simpler and could probably be turned on by default.

**Comment by kulakowka** [comment]
Sounds cool. I've seen this behavior when dragging boards in trello.com. This is very convenient and it seems that this should work by default.

**Comment by alexreardon** [comment]
Yeah it is very convenient - just need the time to do it!

**Comment by tim-soft** [comment]
I would personally love this feature, although I'm a little unsure of how I'd integrate auto scrolling into all of my other containers where applicable. DOM magic via CSS selectors?

**Comment by alexreardon** [comment]
I am super keen to work on this @tim-soft . We are currently working on #2 which is our primary focus for now. Once that ships I am really keen to get onto auto scrolling and touch support #11 

We already know all the droppable scroll containers - so i am expecting we can create some interesting scroll propagator for them as well as the window. We will also need to consider keyboard and ensuring that the page / containers scroll as expected with that also

**Comment by kupkovski** [comment]
Hi guys. Congrats for the excellent work!
Do you have an estimate on how long will it take to be shipped?

**Comment by alexreardon** [comment]
@kupkovski I try not to give out time estimates - but this is huge priority for us. After we solve the big scale performance we will be on this like bees on honey - sweet glorious honey

**Comment by TimNZ** [comment]
Sorry everyone, I'm going to look entitled and ungrateful, but auto scrolling is essential and should have been baked into v1.

Love everything about this library otherwise.

This library might be useful for inspiration and implementation time saving.

https://github.com/StreakYC/react-draggable-list

**Comment by alexreardon** [comment]
We are planning on working on it very soon. We also have a number of competing internal priorities. The plan is to work on it after #86 is shipped.

**Comment by jonaskello** [comment]
FWIW, [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) has this feature.

**Comment by alexreardon** [comment]
Yep. It will be added soon

**Comment by alexreardon** [comment]
I am now starting work on this. If there any great examples people are aware of feel free to post them. I am currently researching!

**Comment by joshuacrowley** [comment]
https://app.asana.com and https://www.notion.so both have block based drag and drop, built with React.

**Comment by TimNZ** [comment]
I'll state the obvious - Trello :)

**Comment by alexreardon** [comment]
Assorted thought on behaviour

## Mouse / Touch

### Window scrolling

Once the user gets close to the edge of the window and the window is able to be scrolled - then we scroll the window.

### Droppable scrolling

If the user drags near the edge of a scrollable Droppable we scroll the droppable. If the user goes beyond the edge of the container we continue to scroll at maximum speed. This is unless we are now over the top of a new Droppable - in which case we stop auto scrolling

### Priority

If an auto scroll would be activated for both the window and the Droppable at the same time then we give preference to [TO BE DECIDED]

## Keyboard scrolling

If ever an item is moved within a list or into a new list and its location is partially invisible then the container or window will be scrolled so that it becomes visible.


## Approach

I am still considering where the best place for this logic to live is. Initially I thought a redux middleware (or similar) location would be perfect - but we need to have access to the elements themselves to update their scroll which is not available from the state. Either we split the logic between `Draggable` and `Droppable` components which might get hard when it comes to prioritising types of auto scroll, or we put it in a location that has access to both - the dimension marshal. My initial thoughts are that I am not super keen to put it in the marshal as it extends its responsibilities - perhaps too far. 🤔...

**Comment by alexreardon** [comment]
@jaredcrowe and I are white boarding behaviour

![img_2548](https://user-images.githubusercontent.com/2182637/35018295-ee596d78-fb74-11e7-991a-d8761dcbec7b.JPG)

**Comment by alexreardon** [comment]
```bash
git checkout -b auto-scroll
```

😄

**Comment by alexreardon** [comment]
Still in very early stages of fiddling around. But it is fun to play with!

![early-auto-scroll](https://user-images.githubusercontent.com/2182637/35081854-8874d7c6-fc6a-11e7-973e-19f143a46cac.gif)

**Comment by alexreardon** [comment]
I am wrestling with an issue on mobile safari where a touchmove event provides an incorrect clientX / clientY value after a manually triggered scroll event. The values are then correct on the next touchmove 🙃. Still investigating if it is me or safari

![lame-touch-move](https://user-images.githubusercontent.com/2182637/35206665-64eedb46-ff92-11e7-95c6-def566c89b8e.png)

**Comment by alexreardon** [comment]
I have [raised a but in webkit](https://bugs.webkit.org/show_bug.cgi?id=181954) about this one. I can reproduce it in an isolated example. After a scroll a touchmove does not correctly account for clientX, clientY intermittently.

I tried to create a work around for this but I was unable to given that:

- it occurs  intermittently
- there can be a few incorrect touchmove events in a row (it could be 0 it could be 3 - or more!).
- i have found no way to know if the touchmove event is accurate or not

Given that the webkit team is responding to the bug I will proceed with the bug exposed in the library. It sucks, but I cannot get around it at the moment. The result of this will be some jittering of a draggable as a window is auto scrolling on iOS11

**Comment by alexreardon** [comment]
I think #291 is essential for this so it will be shipping with it. Sadly #291 comes with a minor api break so it will push the version to `5.0` 😊

**Comment by alexreardon** [comment]
It may seem a little quiet but this is well underway. There is a lot of complexity in doing this well for all of the different input types

**Comment by alexreardon** [comment]
Here is our [work in progress](https://auto-scroll--react-beautiful-dnd.netlify.com/)

- [x] mouse auto scroll for window and droppables
- [x] touch auto scroll for window and droppables
- [x] keyboard in a single list with window and droppable scroll
- [ ] keyboard in multiple lists


We have put **an extreme** amount of love ❤️ into every interaction to make it feel great regardless of your page composition. We have also been giving keyboard lots of attention which is slowing things down a bit. Auto scrolling with a keyboard is a completely different beast to pointer input dragging

**Comment by tim-soft** [comment]
@alexreardon you're a wizard harry! Is this branch still React v15 compatible?

**Comment by alexreardon** [comment]
Yep @tim-soft

**Comment by alexreardon** [comment]
This is the mess I am currently working through:

https://twitter.com/alexandereardon/status/959195944326643713

The browsers update document.documentElement.scrollTop and window.pageYOffset
differently as the window scrolls.

### Webkit

documentElement.scrollTop: no update. Stays at 0
window.pageYOffset: updates to whole number

### Chrome

documentElement.scrollTop: update with fractional value
window.pageYOffset: update with fractional value

### FireFox

documentElement.scrollTop: updates to whole number
window.pageYOffset: updates to whole number

### IE11

documentElement.scrollTop: updates to whole number
window.pageYOffset: updates to whole number

### Edge (same as webkit)

documentElement.scrollTop: no update. Stays at 0
window.pageYOffset: updates to whole number

**Comment by TimNZ** [comment]
@alexreardon Sending you a virtual pat on the back, and a cup of tea with a biscuit.

**Comment by belief-cyf** [comment]
good luck

**Comment by Alebron23** [comment]
I sent you an email today inquiring about this feature before I found this post. Do you have an estimation when this feature will be ready?

**Comment by alexreardon** [comment]
We do not give out time estimates. It is actively being worked on so it *should* not be too much longer 👍

**Comment by alexreardon** [comment]
This is so close 🔥. There has been some really great work done to ensure this entire experience works in an initiative, beautiful and performant way with mouse, keyboard and touch. Getting keyboard working was a world of pain - but super worth it. It is looking fantastic

Thank you for your patience everyone

**Comment by alexreardon** [comment]
Branch just went green - getting closer!

<img width="392" alt="screen shot 2018-02-20 at 4 11 02 pm" src="https://user-images.githubusercontent.com/2182637/36408640-cafb6a1a-165a-11e8-95a4-d4d2f0bf954f.png">

**Comment by alex6633** [comment]
Appreciate your efforts on this !!! 🥇  
Need this feature very badly to make my component work.

**Comment by alex6633** [comment]
Hi @alexreardon ,
How Can I avail this window auto-scroll feature ?

**Comment by Alebron23** [comment]
You da man!!

**Comment by shruti8789** [comment]
> Still in very early stages of fiddling around. But it is fun to play with!
> 
> ![early-auto-scroll](https://user-images.githubusercontent.com/2182637/35081854-8874d7c6-fc6a-11e7-973e-19f143a46cac.gif)

Here, we can see a definite area after which it starts to auto-scroll (both above and down the pane/palette) . Can we customize this area?

**Comment by aalian66loop** [comment]
any updates on this ;(
