### ISSUE TITLE
Support lists with different alignments (eg RTL alignment)

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#270]
Right now we only support lists that are aligned to the start of the container. We could look to support lists of any alignment (end, middle and so on)

#211: end aligned
#265: middle aligned

**Comment by developerium** [comment]
Support for RTL in horizontal is very much appreciated

**Comment by gulaszboy** [comment]
Hey,
Have you found any solution to this problem?

**Comment by alexreardon** [comment]
We will track this one here: #270

**Comment by abforce** [comment]
@alexreardon  I also need support for RTL horizontal lists. If it's not yet supported why have you closed the issue?

**Comment by Aarbel** [comment]
@alexreardon little update, maybe you missed it because it was closed.
Could be a huge enhancement of the lib

**Comment by redline-gh** [comment]
Is there any update on this? Or any potential solutions?

**Comment by c0mm4nDer** [comment]
Any progress?

**Comment by mkermani144** [comment]
Such a quiet issue.

**Comment by hosseinmd** [comment]
Why this issue closed

**Comment by mamadoo** [comment]
Do you find any solution for this problem?

**Comment by blendaddict** [comment]
This would be such a great improvement

**Comment by zlasa** [comment]
Way not to respond to this. RTL is such a great library, and not offering alternatives is a little surprising.

**Comment by skbsh** [comment]
that might not be a solution but I use `direction: ltr; justify-content: end;` for `div` inside `Dropable` and render `Draggable`s as children of that `div`. Also it's needed to reverse `Draggable` list.
