### ISSUE TITLE
Release Schedule - Post Information

### ISSUE THREAD

**Issue by paustint** [atlassian/react-beautiful-dnd#272]
## Bug or feature request?
(answer here)
**Feature Request**
Hi there, I have seen the latest release notes and the new release looks amazing! Great job.  Shout out to @alexreardon for the amazing [Medium article](https://medium.com/@alexandereardon/dragging-react-performance-forward-688b30d40a33)!

I am really excited to check out the changes and noticed it was not yet released to npm, and after looking around the repo to figure out what the cadence for npm releases, I couldn't find any information.
### Questions
1. Is there an estimated timeline for the release?
1. In general, what is the cadence for npm release after a github release?
1. Would it be possible to include an estimated npm publish date with future release notes to keep people like me at bay? (assuming this is known)

Thanks again for the amazing work!

**Comment by alexreardon** [comment]
Hi @paustint,

The recent performance changes have been released to npm as 4.0: https://www.npmjs.com/package/react-beautiful-dnd

> 4.0.0 is the latest of 26 releases

We currently have a few minor pending changes in `master` than are unreleased. At this stage the release schedule is fairly add hoc. Usually new changes / fixes in `master` are released within a few days.

**Comment by paustint** [comment]
@alexreardon - thanks! I could have sworn I checked and saw an older version ;)  total mistake on my part - thanks for the response!
