### ISSUE TITLE
Add support for id's of type number

### ISSUE THREAD

**Issue by maasha** [atlassian/react-beautiful-dnd#274]
## Bug or feature request?
Bug?

### Expected behavior
I am working on a variant of the [Basic usage example](https://github.com/atlassian/react-beautiful-dnd#basic-usage-example)

I would expect it possible to drag and drop the first element.

### Actual behavior

It is not possible to drag and drop the first element. I get the following errs:

- Cannot start capturing dimensions with an invalid request 0
- could not find draggable in store after lift
- not able to drop in phase: 'IDLE'

I believe the reason is that `id: 0` is messing up (classic problem, eh?). I have the following item list:

```
const items = [
  { id: 0, content: 'nul' },
  { id: 1, content: 'en' },
  { id: 2, content: 'to' },
  { id: 3, content: 'tre' },
  { id: 4, content: 'fire' },
];
```

If I remove the first item from the list, then all is good ...

**Comment by alexreardon** [comment]
Ids need to be a string. People keep hitting against this though. Perhaps
it is worth extending ids so they can also be numbers

**Comment by maasha** [comment]
Why not ;o)

**Comment by alexreardon** [comment]
![both](https://user-images.githubusercontent.com/2182637/35016972-0306a0fc-fb6f-11e7-825c-dafa9e45560d.png)

**Comment by balnagy** [comment]
This seems to be working already: https://codesandbox.io/s/k3vjp3qz0o

**Comment by alexreardon** [comment]
There are some situations where an id of 0 will fail truthy checks in some files

**Comment by InteriorNature** [comment]
Is numeric support necessary? I'm used to db identifiers being numeric - but the react apollo/graphql transports them as strings. On the other end, render ids in HTML5 are string <element id="id">, and passing ids other ways, like jsonwebtoken, are passed as string, as well.

**Comment by alexreardon** [comment]
For now, I think we can just keep it as a string. This is easy for consumers to cast
