### ISSUE TITLE
Add different box size for drag and drop

### ISSUE THREAD

**Issue by avenCN** [atlassian/react-beautiful-dnd#277]
feature request
Here is demo for different box drag and drop https://packery.metafizzy.co/

**Comment by lukebatchelor** [comment]
Hi @avenCN , are you referring to the "Draggable Masonry layout" or the "Draggable dashboard" example?

The "Draggable Masonry layout" should definitely be possible currently.
Take a look at the first example here: https://react-beautiful-dnd.netlify.com/
Inspect the first card and add an inline style to the anchor element with `height: 150px`. You'll see it works fine.

The other example might be trickier. The [readme](https://github.com/atlassian/react-beautiful-dnd#currently-supported-feature-set) says:

> Independent nested lists - a list can be a child of another list, but you cannot drag items from the parent list into a child list

Which would make the "Draggable dashboard" example interaction not possible.

**Comment by alexreardon** [comment]
At this stage we are not supporting a grid drag and drop system. The goal of this library is:

> Beautiful, accessible drag and drop for **lists** with React.js

Thank you for seeking to make this library even better! However, at this stage we are keen to avoid scope creep.

**Comment by avenCN** [comment]
Ok, just hope make more power. Another demo: it's can resize element size and limit resize all power.

http://dsmorse.github.io/gridster.js/demos/resize-limits.html

**Comment by rizwan92** [comment]
is there any example or source code for grid drag and drop ?
