### ISSUE TITLE
Dragging a List with 200+ cards causes the web stucked in a board view

### ISSUE THREAD

**Issue by poryzhao** [atlassian/react-beautiful-dnd#281]
## Bug or feature request?
Bug

### Expected behavior

Drag and Drop smoothly

### Actual behavior

When I drag a List with 200+ cards in it to another position, The list cannot be placed to right position and the page is stucked, the function requestAnimationFrame is triggered many times which can be watched in the Console in Chrome

### Steps to reproduce

Drag a List with 200+ cards in it to another position

### Browser version

Chrome 63.0.3239.132

**Comment by alexreardon** [comment]
I am unable to replicate your issue [on our large board example](https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=large%20data%20set&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)

Can you please provide a reproducible example of the issue you are experiencing? Here is a [boilerplate](https://www.webpackbin.com/bins/-Kr9aE9jnUeWlphY8wsw) to start from

**Comment by poryzhao** [comment]
I cant use boilerplate in China maybe because of the firewall, I tried a lot and found out the problem came from the inner <Draggable>, like your demo components < InnerQuoteList >(see from https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/primatives/quote-list.jsx).

When I delete the inner draggables,  the outer draggables can be placed smoothly.

Do u have any ideas?

**Comment by humphreybc** [comment]
@alexreardon FYI we are also seeing this in Dovetail when a project has a lot of items. Our draggable components (and their children) are more complex than your storybook examples, but I'll try to put together some more information next week.

**Comment by crapthings** [comment]
i've a gif that demonstrate large board is not problem
https://github.com/atlassian/react-beautiful-dnd/issues/268

**Comment by alexreardon** [comment]
I am not sure I am following this issue correctly - but this is worth reading: https://github.com/atlassian/react-beautiful-dnd#recommended-droppable-performance-optimisation

We recommend you implement some optimisations within your Droppable to avoid rendering children when `isDraggingOver` changes
