### ISSUE TITLE
DragDropContext functions only with one child

### ISSUE THREAD

**Issue by lukebarnard1** [atlassian/react-beautiful-dnd#285]
## Bug or feature request?

Bug

### Expected behavior

The DragDropContext can function with multiple children.

### Actual behavior

When the DragDropContext has multiple children, it causes an error to be thrown in `DragDropContext.render()`, (which is surprising, given that it just returns `this.props.children`.

### Steps to reproduce

Implement beautiful DND with a `DragDropContext` that has multiple children, where some of the children have `Droppable`s, which have `Draggable`s nested in them.

### Browser version

Chrome 63

### Demo

This demo *should* demonstrate the issue, but I couldn't confirm -
 webpackbin itself was 404ing ... https://www.webpackbin.com/bins/-L3UZwuT_FKp_5AWhFNp

**Comment by alexreardon** [comment]
Yep! `DragDropContext` only supports a single child. 

We call this out in the docs:

```js
type Props = {|
  ...Hooks,
  children: ?Node,
|}
```

If you are using React > 16.2 you can use [fragments](https://reactjs.org/docs/fragments.html) to effectively have multiple children.

**Comment by lukebarnard1** [comment]
Ah okay. I wonder if it would be worth spelling this out in the documentation, or even providing more useful error messages than an error being thrown in `DragDropContext.render()`?
