### ISSUE TITLE
Cannot drop a draggable on a droppable which partially overlaps another droppable

### ISSUE THREAD

**Issue by vladimir-konnov** [atlassian/react-beautiful-dnd#288]
## Bug or feature request?
(answer here)
I think it's a bug

Hi @alexreardon! I enjoy using your library, thank you very much! But I found an issue that I cannot resolve myself, because I think it's inside your library.
I have a panel which slides down when I'm dragging a draggable with the areas like 'Trash' in order to be able to visually remove draggables from the lists. So I think it's quite a frequent case for the users of your library.
I have colums/lists implemented as droppables and also I have a tool panel where some other droppables reside. And a kanban card as a draggable. So when droppables aren't overlapped everything works just fine. But when a droppable is partially overlapped with another droppable, the drop event isn't fired for that another droppable, but is fired for that first one that is 'under' another droppable. By saying 'under' I mean that 1. It looks 'on top of' the first droppable and 2. It has z-index much more than 'underlying' droppable, but sure less than 5000 (which has a 'draggable' kanban card) in order to let the kanban card drag over the droppable.
To be more clear on what I'm talking about I've shot a video, please take a look at it
https://monosnap.com/file/48ulOAeOGMpCKpTf2qXZjheEPHMXmW
I'm new to your library and I haven't yet understood how (and where) a drag over is detected and how a droppable is looked up. I understood only that it ignores the z-index of droppables and fires a drag over event only for the (first) found droppable (tell me if I'm wrong please)
I would appreciate any advices on why it behaves like that and what can be done to properly detect the appropriate droppable during a drag over (unfortunately removing/moving away a tool panel is not an option :) )

### Expected behavior
It should detect a droppable with the greatest z-index (but below 5000) when dragging over a draggable

### Actual behavior
It detects the first droppable which is 'under' the overlapping one during drag over event

### Steps to reproduce
1. Partially overlap the first droppable with the second one, which is 'on top' of the first droppable
2. Drag a draggable over a second droppable.

Result: the first droppable is detected for a drag over event.

### Browser version
Chrome v.63.0.3239.132 (64 bit), MacOS High Sierra 10.13.2

### Demo
https://monosnap.com/file/48ulOAeOGMpCKpTf2qXZjheEPHMXmW

**Comment by alexreardon** [comment]
Right now we do not support adding a `Droppable` after a drag has started. You will probably see some warnings in your console explaining this. We plan on supporting it as a part of #68. 

To get around this you could great a visually invisible droppable which you then make visible after the drag starts. Right now we do not have a `dragWillStart` hook or similar which would also be of use to you. Once we support #68 your could should just work :)

**Comment by vladimir-konnov** [comment]
@alexreardon but why it works ok before scrolling down? It means that I already have an invisible droppable on the page. It just gets displayed `onDragStart` and drag over works just fine over them.
Is it a problem with overlapping droppables?

**Comment by alexreardon** [comment]
If you are moving a droppable after the drag start then it's dimensions have changed which is unsupported right now: https://github.com/atlassian/react-beautiful-dnd#block-updates-during-a-drag

**Comment by vladimir-konnov** [comment]
@alexreardon yes, I was getting these `Uncaught Error: Cannot get dimension for unpublished draggable` errors in the console. Now I see why, thank you!
But I guess it's a frequent case when a toolbar/panel gets appeared on drag start (like with the 'Trash' area for example), is it? Users may want to completely remove an item, but always displaying a Trash bin isn't always convenient, especially on small screens of mobile devices/tablets. And probably websites as well.

**Comment by alexreardon** [comment]
Agreed. Once we support #68 then you should be able to have this experience for real.

**Comment by vladimir-konnov** [comment]
Hi @alexreardon! I saw you've done a lot of improvements, so I'd like to upgrade from v.4.0.1 to 6.0.2.
But I found a problem with my issue. In order to somehow work around the scroll which changes the dimensions/positions of Won/Lost/Trash boxes on top of the page (see demo video related to the issue), I decided to `preventDefault` any scroll event that may change the scrollTop of the page. Like the following:
```
  $(document).on('mousedown', function(e) { e.preventDefault() if e.which == 2});
  # catch other kinds of scrolling
  $(document).on('mousewheel DOMMouseScroll wheel touchmove', function(e){
    e = e || window.event
    e.preventDefault() if e.preventDefault
    e.returnValue = false
  });
  # disable scrolling with keyboard
  $(document).on('keydown', function(e) { e.preventDefault() if e.which == 2});
```
It looks like bruteforce but it works.
But recently there was an `auto scroll` feature introduced when a draggable moves at the top/bottom of a droppable and it starts increasing the `scrollTop` of a nearest scrollable (it seems to be a window object in my case). Correct me if I didn't get the way it does the scroll.
So in this case my issue is reproduced: the positions of Won/Lost/Trash boxes are changed and hover malfunctions again. See my video https://monosnap.com/file/n72kQ8y0evWzzSmAgAXdwJZsCsYsuS
Once I hover the Won/Lost/Trash boxes they get highlighted with border. But as long as I scroll the page with autoscroll feature it stops working, also when I scroll down and the position of the boxes equals to initial positions it's back working.
So my question is how can I switch off somehow the autoscroll feature? Passing a special option or attribute value?
I will appreciate any ideas, thank you.
