### ISSUE TITLE
Wrong scroll position after drop in scroll container

### ISSUE THREAD

**Issue by komlew** [atlassian/react-beautiful-dnd#290]
## Bug or feature request?
Bug

### Steps to reproduce
1. Open storybook frame with "Droppable is a scroll container" (https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=Droppable%20is%20a%20scroll%20container&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel).
2. Grab one of the elements at the top of the list.
3. Scroll the container down until you reach the bottom.
4. Drop the element at the last position.

### Expected behavior
The draggable block is moved to the last position, scroll position of the container is at its end, so you **can** see the element you've just dropped (it's at the bottom of the container).

### Actual behavior
The draggable block is moved to the last position, the container is scrolled until the new element, so you  **can't** see the element you've just dropped (it's bellow the container scroll position).

### Browser version
Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)

### Demo
Added animated gif (8mb) below...

![scroll_container](https://user-images.githubusercontent.com/2599862/35267888-f78c77e8-0027-11e8-8694-c7e5efc3a05b.gif)

**Comment by alexreardon** [comment]
Spot on @komlew. We will track this in #291.

Thanks!

**Comment by komlew** [comment]
Thanks, @alexreardon

That's after reading your great article https://medium.com/@alexandereardon/dragging-react-performance-forward-688b30d40a33
