### ISSUE TITLE
Maintain scroll position post-drop

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#291]
When dropping an item it is up to a consumer to update their state syncronously. However, this change can result in a shift in the scroll of the container / viewport that the user is interacting with. Ideally there would be no shift after a drop.

I have avoiding this until we do #27. That feature makes this very obvious. I have been hesitant to do this until now as it involves doing some post-drop work (potentially correcting scroll's) which we are not doing at this point. However, I think it is time.

**Comment by alexreardon** [comment]
Duplicate: #290

**Comment by alexreardon** [comment]
I can confirm that the scroll is shifted by the size of the dropped item. I am currently attempting to create a reproducible example and then i'll explore ways of getting around it

**Comment by alexreardon** [comment]
I have set up a little independent demo that has a list with changing items. Unable to replicate issue. I have been digging into React internals to see if it is doing some scroll magic

**Comment by alexreardon** [comment]
It turns out the issue is only occurring in Chrome. This got me thinking that it is probably not react.

It turns out the issue is caused by Chrome trying to be clever with [Scroll Anchoring](https://css-tricks.com/almanac/properties/o/overflow-anchor/). To get around this permanently we will add this style (probably to a droppable)

```css
overflow-anchor: none;
```

**Comment by alexreardon** [comment]
As a work around you can add the style for yourself in the meantime

**Comment by alexreardon** [comment]
Unfortunately to add this it will be a breaking change as we need to add a style property to droppables 😕😙

**Comment by alexreardon** [comment]
Closed by #321

**Comment by mdodge-ecgrow** [comment]
FYI, for anyone coming here looking for answers.  I have done something that doesn't look super great, it scrolls after that state is saved and scrolled to the top.  And it is very hacky, but it does work to get the dropped item into focus at the top of the scroll container.
I stuck this code into my onDragEnd function.
```
// scroll the order into view
		const target = document.getElementById(theOrder.orderNumber);
		const whereToScroll =
			target.offsetTop -
			document.getElementById(destination.droppableId).offsetTop -
			55;
		setTimeout(() => {
			document.getElementById(
				destination.droppableId
			).scrollTop = whereToScroll;
		}, 5);
```

**Comment by altmshfkgudtjr** [comment]
@mdodge-ecgrow 
I have problem same as yours, and my solution is same too. Is there really any better way than this one? 😭😭😭
