### ISSUE TITLE
some problem with drag and drop for group

### ISSUE THREAD

**Issue by nhandh2013** [atlassian/react-beautiful-dnd#299]
Hi,
Currently, I have some problem with react-beautiful-dnd. I hope you may help me.
How can I drag and drop list data and filter by group?
I saw the demo on https://react-beautiful-dnd.netlify.com, but can't found the code example for that.
Please help me, give me the code example demo for that.
Thanks bro

**Comment by alexreardon** [comment]
Hi there! I am not entirely sure what you mean by 'filter by group'. We have a few filtering mechanisms you can use: https://github.com/atlassian/react-beautiful-dnd#conditionally-dropping

All the source code for the examples can be found here: https://github.com/atlassian/react-beautiful-dnd/tree/master/stories

Let me know if you needed more assitance

**Comment by nhandh2013** [comment]
I got it, thanks @alexreardon
