### ISSUE TITLE
Drag Handles

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [atlassian/react-beautiful-dnd#303]
## feature request

Looking through the documentation I couldn't find any reference to being able to set up custom drag points (drag handle or move button etc.) and was wondering if that sort of UX is possible or inline with the vision of this library.

**Comment by bmueller-sykes** [comment]
You can do custom drag handles:

https://github.com/atlassian/react-beautiful-dnd#example-custom-drag-handle

**Comment by alexreardon** [comment]
Thanks @bmueller-sykes !

**Comment by FrankAst** [comment]
@bmueller-sykes , have you an example now?

**Comment by FrankAst** [comment]
I've found it in course here: https://egghead.io/lessons/react-designate-control-of-dragging-for-a-react-beautiful-dnd-draggable-with-draghandleprops

Thank you, @alexreardon for your great work!

**Comment by alexreardon** [comment]
All good - i was going to post that 👍

**Comment by haatchi** [comment]
The yolk essence of the egghead: move {...provided.dragHandleProps} into your handle:

    <div className='mydraghandle' {...provided.dragHandleProps}></div>

**Comment by lonelyua** [comment]
..and we can delete isDragging={snapshot.isDragging} from container
