### ISSUE TITLE
Differently-styled drag items "flash" on drop

### ISSUE THREAD

**Issue by bmueller-sykes** [atlassian/react-beautiful-dnd#304]
## Bug or feature request?
Bug

### Expected behavior
Imagine I've got a list of draggable items, and I want the backgrounds of each item to be different (e.g. on a Kanban board, maybe background colors would indicate status in some way). When I drag to rearrange the items, I want the styles to accompany the dragged items, obviously.

### Actual behavior
The styles *mostly* follow the dragged item. However, for a millisecond after the drop action, there is a perceptible "flash" where the two styles appear to be at their initial location, before snapping to the updated location.

### Steps to reproduce
Drag the items in the Sandbox (below), and the flash should appear.

### Browser version
Latest version of Chrome

### Demo
https://codesandbox.io/s/21o3w0xkj

**Comment by alexreardon** [comment]
I have had a play with the demo but I am not sure what the issue is that you are referring to. Can you please provide more information about the 'flash'?

**Comment by bmueller-sykes** [comment]
Thanks for the reply. What I see is this: if I drag "Item 1", which is yellow, over "Item 0" which is white, right after I drop...uh...holy crap. This might be entirely my fault. (-; Gimme a few minutes here...

**Comment by bmueller-sykes** [comment]
Yeah, never mind. I did something stupid. Sorry!!

Great library, by the way. Off topic, so go ahead and ignore, but I only wish there were a nice way to abstract the `Draggable` component away into a container, so I could just have something like:

```
<DragItem
  id={id}
  index={index}
  type='MY_DRAG_TYPE'
  {...etc}
>
stuff to be dragged
</DragItem>
```

...but I couldn't figure out how to abstract stuff away *and* have a custom drag handle in my child code, like:

```
<DragItem
  id={id}
  index={index}
  type='MY_DRAG_TYPE'
  {...etc}
>
<div>
  <div {...dragHandleProps}>my handle</div>
</div>
</DragItem>
```

Maybe there's a way to do this that I just haven't figured out yet. Anyway, carry on!

**Comment by alexreardon** [comment]
Glad to hear you got it sorted!

Let me know how you go creating your own abstraction 💃

**Comment by bmueller-sykes** [comment]
Here's the abstraction I've got. I'm using JSS for styling, so assume that's handled outside this component. There's nothing particularly special about it at the moment. What I was hoping to avoid was to expose the function-as-child in normal code. It's powerful, but a little ugly, and can make it easier to make mistakes. But I'm not sure there's a way to pass down `provided` (or perhaps just `provided.dragHandleProps`) and make that object available to an arbitrary descendant. I could attach `provided.dragHandleProps` to the first child, using `React.cloneElement()`, but that's not useful. I briefly experimented with the technique the React Router guys use, and I had a `render` prop:

```
<DragItem id={id} index={index} type='TYPE' render={() => (render stuff here)} />
```

...but I couldn't find a way to pass provided and/or snapshot down. Perhaps that's the right solution, so I may poke at that a bit more.

```
// NOTE: this class is only useful if you don't need a custom drag handle.
// If you do need a custom drag handle, then you need to directly invoke <Draggable />
// in your code.
export class DragItem extends Component {

  static propTypes = {
    id: PropTypes.string.isRequired,
    index: PropTypes.number.isRequired,

    itemClass: PropTypes.string,
    itemDragClass: PropTypes.string,
    wrapperClassName: PropTypes.string,
    dragHandle: PropTypes.element,
    dragStyle: PropTypes.object,
    type: PropTypes.string
  }

  static defaultProps = {
    itemClass: '',
    itemDragClass: '',
    type: 'DEFAULT',
    wrapperClassName: null,
  }

  classes = (isDragging) => {
    const { itemClass, itemDragClass } = this.props;
    return classnames({
      [itemClass]: true,
      [itemDragClass]: (isDragging)
    })
  }

  render () {
    const { children, id, index, type, wrapperClassName } = this.props;

    return (
      <Draggable
        draggableId={id}
        index={index}
        type={type}
      >
      {(provided, snapshot) => {
        return (
          <div
            className={wrapperClassName}
          >
            <div
              ref={provided.innerRef}
              {...provided.draggableProps}
              {...provided.dragHandleProps}
              style={provided.draggableProps.style}
              className={this.classes(snapshot.isDragging)}
            >
              {children}
            </div>
            {provided.placeholder}
          </div>
        )
      }}
      </Draggable>
    )
  }
}
```

**Comment by bmueller-sykes** [comment]
@atalebagha Sorry, I barely remember now. (-; I was doing something stupid with how I was handling the data on re-renders, which was causing the flash. That's not a very helpful response on my part...sorry.  The link to the code sandbox in my initial post has things working properly (e.g. no flashing after drop), so you're free to use that as an example if you're running into a similar issue.
