### ISSUE TITLE
Draggable child Input (type range) is not blocking the ability to drag, when moving the slider.

### ISSUE THREAD

**Issue by isoceles** [atlassian/react-beautiful-dnd#312]
## Bug or feature request?
Bug

### Expected behavior
Interactive child elements within a Draggable

It is possible for your Draggable to contain interactive elements. By default we block dragging on these elements. By doing this we allow those elements to function in the usual way. Here is the list of interactive elements that block dragging from by default:

- input

### Actual behavior
When attempting to move the slider on the Input type "range", the draggable element drags.
### Steps to reproduce
Add an
`<input type="range" min="1" max="100" value="50" id="myRange" />`
into a draggable element and try to move the slider.

### Browser version
Chrome 63.0.3239.132 (macOs)

**Comment by alexreardon** [comment]
Cool, we'll check it out

**Comment by alexreardon** [comment]
This actually has nothing to do with react-beautiful-dnd. By adding a `value` without an onChange function the input becomes read only. If you remove the value or add an onChange handler you should be all good

```
// react warning
warning.js:33 Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

**Comment by isoceles** [comment]
I actually pasted the wrong input on here. This one below is the one that is giving me the issue:

`<input
              type="range"
              id="seekBar"
              value="0"
              onMouseDown={this.seekPause}
              onMouseUp={this.seekPlay}
              onChange={this.updateSeek}
            />`

**Comment by alexreardon** [comment]
I suspect that you might be calling prevent default or stop propagation in your event handlers. Can you please post a stand alone example? 

Here is a boilerplate: https://codesandbox.io/s/k260nyxq9v

I have created an example on my local machine with an input type of range and it is working correctly

**Comment by isoceles** [comment]
I finally had time to return to this issue. It turns out I was on an older version of react-beautiful-dnd. Everything is working as expected. Thanks!

**Comment by alexreardon** [comment]
Good to know! 🎉

**Comment by alexreardon** [comment]
Thanks for the follow up post @isoceles!

**Comment by bogdan-Kozlovsky** [comment]
Hello,
I have a similar problem, dragging the element itself when changing the input value. event.stopPropagation() does not help
Custom InputSlider using the rs-slider library
const Test: React.FC = () => {
  const [items, setItems] = useState<Item[]>(initialItems);
  const [value, setValue] = useState(1);

  const onDragEnd = (result: DropResult): void => {
    if (!result.destination) return;

    const reorderedItems = Array.from(items);
    const [movedItem] = reorderedItems.splice(result.source.index, 1);
    reorderedItems.splice(result.destination.index, 0, movedItem);

    setItems(reorderedItems);
  };

  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Droppable droppableId="droppable">
        {provided => (
          <ul {...provided.droppableProps} ref={provided.innerRef} className={s.list}>
            {items.map((item, index) => (
              <Draggable key={item.id} draggableId={item.id} index={index}>
                {/* eslint-disable-next-line @typescript-eslint/no-shadow */}
                {provided => (
                  <li
                    className={s.item}
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                    ref={provided.innerRef}
                  >
                    {item.content}

                    <div style={{ marginTop: '10px' }}>
                      <InputSlider
                        min={1}
                        max={3}
                        value={value}
                        onChange={() => setValue(value + 1)}
                      />
                    </div>
                  </li>
                )}
              </Draggable>
            ))}
            {provided.placeholder}
          </ul>
        )}
      </Droppable>
    </DragDropContext>
  );
};

Advice on how to solve the problem!
