### ISSUE TITLE
onDrop is not trigerred on draggable

### ISSUE THREAD

**Issue by PcFrontEndAcademy** [atlassian/react-beautiful-dnd#315]
found on your lib     
_this.onDrop = function () {
      _this.throwIfCannotDrag();
      _this.props.drop(); // maybe should be this,props.onDrop()
    };

Also saw that this.props.onDrop is passed but never used. Check in : draggable.js

**Comment by PcFrontEndAcademy** [comment]
Also saw that this.props.onDrop is passed but never used. Check in : draggable.js

**Comment by alexreardon** [comment]
It is passed to drag handles using:

```js
const callbacks: DragHandleCallbacks = {
      onLift: this.onLift,
      onMove: this.onMove,
      onDrop: this.onDrop,
      onCancel: this.onCancel,
      onMoveBackward: this.onMoveBackward,
      onMoveForward: this.onMoveForward,
      onCrossAxisMoveForward: this.onCrossAxisMoveForward,
      onCrossAxisMoveBackward: this.onCrossAxisMoveBackward,
      onWindowScroll: this.onWindowScroll,
    };
```

It is working as intended
