### ISSUE TITLE
Horizontal and vertical combined example

### ISSUE THREAD

**Issue by iConic21** [atlassian/react-beautiful-dnd#318]
Hi, After following your Docs and some example for hours,
I did manage to get single dnd working, but I wanted to create nested dnd.

I tried to use one of your examples and combine the two https://codesandbox.io/s/8l826881n9 
I'm not sure what I'm doing wrong based on the docs it should work (I think?)

Thanks.

**Comment by alexreardon** [comment]
I'll be creating an example that shoes off this in detail soon #163

**Comment by YashZolmajdi** [comment]
actually solved my issue using the example from this issue [https://github.com/atlassian/react-beautiful-dnd/issues/293](https://github.com/atlassian/react-beautiful-dnd/issues/293)
