### ISSUE TITLE
The drag and drop doesn't for me in IE-11

### ISSUE THREAD

**Issue by alex6633** [atlassian/react-beautiful-dnd#319]
#Hi @alexreardon ,

This is the best library for Drag And Drop I have seen till date. It works perfectly for me in chrome. But it doesn't work in IE. Do I need to add some Polyfill to make it work ?

It throws me the below error each time I try to drag:

Object doesn't support property or method 'find'

**Comment by alexreardon** [comment]
Hi there,

Yes, babel will usually take care of this for you if you polyfill Array.prototype.find. However, it is probably best if we (the library) avoid using the .find method altogether. 

We add these polyfills in the examples. You will find that [this example](https://auto-scroll--react-beautiful-dnd.netlify.com/iframe.html?selectedKind=single%20vertical%20list&selectedStory=large%20data%20set&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) works correctly in ie11. However, I think we should not force consumers to add this polyfill. We could

- tell consumers what polyfills are needed
- not use .find at all

👍

**Comment by alexreardon** [comment]
I'll close this and track the work in #320.

For now if you polyfill Array.prototype.find you should be good to go

**Comment by alex6633** [comment]
Hi @alexreardon ,

Thank you so much 👍  it works for me now. I used babel polyfill.
