### ISSUE TITLE
Triggering drag through input element

### ISSUE THREAD

**Issue by humphreybc** [atlassian/react-beautiful-dnd#322]
## Bug or feature request?
Feature request

## Description

I'd like to let the user to start dragging a Draggable, even when there's an `<input />` or `<textarea />` element on top of the draggable.

e.g. In Trello, list headers have a textarea which you can click to change the name of the list. I believe the textarea is focused on `mouseup`, not `mousedown`, so when you mousedown and move, it'll trigger a drag, even though you've actually clicked the textarea. 

Is something like this possible with react-beautiful-dnd?

**Comment by alexreardon** [comment]
Have a look at [this section](https://github.com/atlassian/react-beautiful-dnd#interactive-child-elements-within-a-draggable) and let me know if that is what you are after

**Comment by alexreardon** [comment]
I'll close this for now given there is a section describing how to work with this behaviour. Let me know if you are still unable to achieve what you are after.

**Comment by ArseniyX** [comment]
> I'll close this for now given there is a section describing how to work with this behaviour. Let me know if you are still unable to achieve what you are after.

I cant find any information how to achieve this behavior
