### ISSUE TITLE
Way to reset data-react-beautiful-dnd-draggable for server side rendering 

### ISSUE THREAD

**Issue by czechdave** [atlassian/react-beautiful-dnd#323]
## Bug or feature request?
Bug

### Expected behavior
`data-react-beautiful-dnd-draggable` shouldn't increment based on how many times it was run on the server but start fresh for each request.

### Actual behavior
Each time the server render is hit `data-react-beautiful-dnd-draggable` is incremented by 1.
i.e. after 6 reloads console throws:
```
Warning: Prop `data-react-beautiful-dnd-draggable` did not match. Server: "6" Client: "0"
```

### Steps to reproduce
Server side render and reload couple times, each reload the `data-react-beautiful-dnd-draggable` gets incremented by 1.

### Browser version
Chrome

https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/style-marshal/style-marshal.js#L11

Possible solution to this would be to expose a function that resets the counter that one could call during a server side render like so:
```
export function resetCounter() {
    count = 0;
}
```

**Comment by alexreardon** [comment]
How interesting!! Sounds very useful indeed!

**Comment by alexreardon** [comment]
The trouble will be exposing this api in a nice way.. Any reason your server is requiring the file multiple times?

**Comment by czechdave** [comment]
I am not requiring the file multiple times. This happens because my express server loads once and then serves multiple requests. Each request needs to be handled in its own context but instead each is calling the same `count` variable.

**Comment by alexreardon** [comment]
I am following now. Let's think about how we can solve this!

**Comment by alexreardon** [comment]
My current thinking: an additional prop to `DragDropContext` to set the style context manually. However, this feels like a leak of an internal... hmmm

**Comment by alexreardon** [comment]
@Blasz would you be keen to take a look at this one?

**Comment by alexreardon** [comment]
Options:

1. remove the namespace (might be a bit lame when we support #302)
2. Provide an api option to `DragDropContext` to explicitly control the style context. This is probably the most flexible option - but it feels lame to expose this internal concern..
3. ?

**Comment by Blasz** [comment]
@alexreardon sure!

**Comment by czechdave** [comment]
I took a stab at this. This [PR #337](Add `resetContext` method for server side rendering #337) does exactly what I need to fix server side rendering though from your comments it seems this is not what you want.
