### ISSUE TITLE
Wrap the items or create more than one row in a dropzone?

### ISSUE THREAD

**Issue by JWaldenback** [atlassian/react-beautiful-dnd#333]
How do I wrap the items or create more than one row in a dropzone if the combined items are wider than the width of the container?

How it works right now (a scroll appears):
![image](https://user-images.githubusercontent.com/19432538/36312331-66931e30-132e-11e8-82f0-5f5a6f2267fd.png)

How I want it to work (the items are wrapped and a second row appear, it's all part of the same dropzone though):
![image](https://user-images.githubusercontent.com/19432538/36312357-7ce19298-132e-11e8-9384-227f35007798.png)

**Comment by ron-camaron** [comment]
This would be a "grid" function which I think is not supported by the library right now.

**Comment by JWaldenback** [comment]
I see. Is it a function that's supposed to be supported in the future? If not, does anyone have a suggestion how I make a behaviour as similar as possible to this?

**Comment by anuragl94** [comment]
@JWaldenback This is currently not being considered. Here is an earlier issue requesting the same feature:
#316 
Would love to have something like this soon though.

**Comment by JWaldenback** [comment]
Okay, thank you for the answer. I think a support for wrapping items would greatly improve the number of potential use cases.

**Comment by alexreardon** [comment]
Thanks @anuragl94 and @ron-camaron for responding to this one :)
