### ISSUE TITLE
Differentiate between dropped on self vs non-droppable area

### ISSUE THREAD

**Issue by ssilve1989** [atlassian/react-beautiful-dnd#336]
## Bug or feature request?

Feature Request

It would be useful to know onDragEnd, if the source was dropped on itself or the destination really was null (i.e. not a droppable area)

My particular use case, is that I am creating "tear-out" tabs (a la Chrome). How I determine whether or not to "tear-out" is by checking if the destination was null, meaning the user has dragged a tab outside the droppable area. With no way to differentiate between dropped on self vs non-droppable area, the tear-out action occurs when the former occurs.

Alternatively, it could be useful to get access to the event onDragEnd to determine the mouse position. (Please if I missed that somewhere let me know)

### Expected behavior

Destination could be populated with the self-index instead of null when dropping on self.

### Actual behavior

Destination is null

### Steps to reproduce

Drag an item around a droppable area, but end the drag on its original position.

**Comment by alexreardon** [comment]
Sounds good. Thankfully we are already making this change as  part of #321 

🎉

**Comment by CrocoDillon** [comment]
I have a similar use-case where I want to delete items from a list if they are dragged outside of the droppable. Functionally it works... but briefly before the item is deleted it still animates back into its original position.

How did you solve this for your use-case?
