### ISSUE TITLE
Is there a way to set the droppable area's height dynamically?

### ISSUE THREAD

**Issue by alex6633** [atlassian/react-beautiful-dnd#339]
Hi @alexreardon,
I am using this react-beatiful-dnd along with an accordion library i.e, react-sanfona (https://daviferreira.github.io/react-sanfona/) 
I have a scenario where in I am implementing this drag and drop inside an expandable and collapsible div (accordion) so when  accordion collapses the droppable area of that accordion is overlapping with the next accordion's droppable area thereby resulting in the drop of an element in the unintended position. Is there a way that I can set the droppable area's height to the accordion's collapsed height. currently  when I collapse the accordion it's respective droppable area is spread across the next accordion thereby overlapping with the next accordions droppable area.

**Comment by alexreardon** [comment]
Currently you cannot change the dimension of a `Droppable` or `Draggable` after a drag has started. We might be able to loosen this restriction as part of #68

**Comment by alexreardon** [comment]
Or are you talking about dragging without changing the open / closed status of a an accordion?

**Comment by alex6633** [comment]
I am trying to drop an element into the closed accordion.

**Comment by selfishl0v3** [comment]
Hi @alexreardon , I have exactly this issue. I got a list of items with a hidden textarea and each one of them got an accordion opened by default if textarea is not empty. My idea is to close accordion when drag starts and restore the status when drag ends but the droppable area seems to be fixed at initial height (when accordion is open).
Any hints?

**Comment by ssaric** [comment]
Any updates on this? @alexreardon
