### ISSUE TITLE
Create standalone doc website

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#343]
The main purpose of this is to split up our large `readme.md` files into more manageable chunks.

Core deliverables:
- split up our large readme file into small chunks that can be easily navigated to
- all documentation files are able to be written as plane `.md` files
- ideally we want to have as little custom code as possible to drive the site

Ideals
- mobile friendly (the library is - so our docs should be too!)
- have examples integrated within the site. Ideally we can drop our storybooks

**Comment by alexreardon** [comment]
Related to #163

**Comment by basitsattar** [comment]
Any update?

**Comment by Noviny** [comment]
Working on this right now. Hoping to have it up by the end of the week.

**Comment by alexreardon** [comment]
Soon

<img width="725" alt="screen shot 2018-04-12 at 10 06 55 am" src="https://user-images.githubusercontent.com/2182637/38649491-47846ecc-3e3a-11e8-9d0a-3a9507ba3901.png">

Related: #363

**Comment by joshuagautham** [comment]
@alexreardon - Any tentative date of release? Want to use this piece.

**Comment by alexreardon** [comment]
Getting closer...

<img width="764" alt="screen shot 2018-04-16 at 2 43 15 pm" src="https://user-images.githubusercontent.com/2182637/38790443-b0ff6d0a-4184-11e8-9c74-1a07c93aea49.png">

**Comment by alexreardon** [comment]
Trello board to track this one: https://trello.com/b/McyW8upT/react-beautiful-dnd-website

**Comment by ng-hai** [comment]
Hi @alexreardon, I had used `react-beautiful-dnd` to implement [an app like Trello](http://simple-trello.netlify.com), which was featured on [appendto.com](https://appendto.com/2018/08/25-public-react-repos-apps-to-inspire-your-next-project-part-1-2/) as an inspiration project. Could I make a PR to submit my project to the docs?

**Comment by dgdosen** [comment]
The docs aren't very discoverable. Sure there are titles... But they're not really organized for a new user...

**Comment by alexreardon** [comment]
@dgdosen for now we have decided to focus on some critical features and park the website build.

Assuming we are only using github for now, how do you think we could better organise our existing content?

**Comment by dgdosen** [comment]
I'll revise my comment after finding the API section in the readme... IMO - it's buried way down there.  Most components lead with API information! It's much more important than say, drop animations, etc..

**Comment by alexreardon** [comment]
Perhaps we could look at:

- restructuring the content
- breaking the big `README.md` into seperate markdown files
- adding a small table of contents to the start of the `README.md`

Do you think these would be helpful @dgdosen ?

**Comment by alexreardon** [comment]
I am also keen to get your thoughts @Noviny

**Comment by Noviny** [comment]
If we could get a nice clear information structure that breaks down the existing docs, it should be very easy to build a quick website on top of it. If you can break them up, and link them together assuming github, I can sort out the other bit.

**Comment by alexreardon** [comment]
@dgdosen I have done some major documentation refactoring. You can read about it here: [10.1 release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0)

How do you feel about them now?

**Comment by alexreardon** [comment]
I will close this issue for now. I think we are getting further than I expected with simply using markdown files

**Comment by alexreardon** [comment]
I am keen to add a stand alone site though!
