### ISSUE TITLE
Auto scrolling doesn't work when dragging individual list items horizontally between lists - as long as every list and the board both have their own scroll container.

### ISSUE THREAD

**Issue by yogaboll** [atlassian/react-beautiful-dnd#344]
## Bug or feature request?
Bug

### Expected behavior

Dragging a list item (that is part of a vertical list) horizontally should cause the container to scroll in that direction.

### Actual behavior

It doesn't, as long as:
(1) The board is inside its own scroll container (meaning a div, not the window).
(2) The lists are inside their own scroll containers.

Otherwise, autoscrolling works just as expected, including if either one of the two conditions apply.

### Steps to reproduce

I've changed [these two files](https://github.com/yogaboll/react-beautiful-dnd/tree/horizontal-scroll/stories/src/board) on my fork to illustrate the problem (see the gif below). Clone the branch on my fork or just copy these files and look at the board examples in storybook.

### Browser version
Google Chrome 65.0.3325.88 beta,
Mozilla Firefox 58.0.2

### Demo

<img src="https://media.giphy.com/media/7XB4Z4x6RYlmKnvOSF/giphy.gif" />

Autoscrolling works great otherwise, but this tiny bug is preventing my project from working as it should. I'll try to look into the source code later to see if I can fix it.

**Comment by yogaboll** [comment]
Looks like the amount of code relating to autoscrolling is pretty huge. I can't fix this myself.

**Comment by poryzhao** [comment]
I encountered the same problem, It seems that when the vertical list is set an 'overflow' attribute, the problem will come.

I can't quite understand these decriptions as well (https://github.com/atlassian/react-beautiful-dnd#scroll-containers)

**Comment by yogaboll** [comment]
That description is a bit hard to understand, but it sounds to me like this use case is *not* supported. @alexreardon, do you have any thoughts on this?

**Comment by alexreardon** [comment]
Correct - it is not supported for now. I can improve the clarity of that section.

Supported:
A Droppable that is a scroll container
A Droppable that is not a scroll container but sits inside of one scroll container

Your usage falls outside of that: it contains nested scroll containers

This is the issue related to this functionality: #131

**Comment by bmueller-sykes** [comment]
To jump in here...I'm using this library to build a kanban board, where both the kanban columns and the cards within each column are draggable.

If I drag to reorder my columns, autoscrolling works (e.g. horizontal overflow scrolling). Also, if I drag a card from one column to another, horizontal autoscrolling works.

However, if I drag to reorder a card within a single column, that column will not autoscroll (e.g. short column, lots of cards). Basically, exactly the behavior at the top of this issue. But your release notes for 5.0.0 has a screen grab of exactly this behavior (e.g. screen grab shows columns being reordered as well as cards within each column reordered), and auto-scrolling working both horizontally and vertically. Specifically, the screen grab with the title "Mouse and Touch". 

So I must be missing something here, right?

(This library is great, by the way)

**Comment by 1renhaO** [comment]
I fixed this to comment the inner <Droppable> css style  `overflow-y: scroll;`, it just worked.

**Comment by gregoryforel** [comment]
@1renhaO Would you have a working example, or could you please check [mine](https://codesandbox.io/s/jovial-moser-y05q4xk6j1)? I can't figure the solution and I've been 2 days working on it.

**Comment by 1renhaO** [comment]
this may help you 
https://react-beautiful-dnd.netlify.com/?path=/story/board--simple (resize the browser until you can find the horizontal scroller, and drag the card,  you can find that the the window will auto scroll horizontally)
this is the code
https://github.com/atlassian/react-beautiful-dnd/tree/master/stories/src/board

**Comment by 1renhaO** [comment]
@gregoryforel

**Comment by 1renhaO** [comment]
@gregoryforel

**Comment by 1renhaO** [comment]
![image](https://user-images.githubusercontent.com/19664590/76676222-4743a180-65fc-11ea-9421-88b0992fc91c.png)

comment the overflow style, it can scroll, may the style caused it can't be auto scroll horizontal

**Comment by alexcyfong** [comment]
@1renhaO for your example raised 
https://react-beautiful-dnd.netlify.app/iframe.html?id=board--simple

The scroll works when it is on desktop mode but when you switch the browser to mobile or small screen, it does not work. Does it support mobile size browser?

**Comment by yoryi** [comment]
Dont we have solution on this? I am building something like trello board, and facing the auto scroll problem for dnding draggable items between columns, and getting warning `unsupported nested scroll container detected`, 
Each vertical lists have its own scrollbar and entire board has also horizontal scrollbar, I can confirm trello works perfect for nested scrollbar for this feature.

@alexreardon dont we have solution for making auto scrolling like trello using this library?

**Comment by sbacorp** [comment]
@yoryi Did you find the answer?
