### ISSUE TITLE
Avoid auto scrolling when picking up a Draggable near a container edge

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#349]
Currently if you pick up a `Draggable` near the edge of a scroll container or the window and auto scroll will start immediately. I think we could improve this.

Idea: only allow auto scrolling after the user has moved in the direction of the edge we are trying to scroll.

**Comment by quandhz** [comment]
Anyone has a workaround for this yet? Is there a way to temporarily disable auto-scrolling?

**Comment by OmriAharon** [comment]
Was just entering the issue list to see if this was already reported - would be great to see this fixed.
