### ISSUE TITLE
Multiple droppable destination = negative integer

### ISSUE THREAD

**Issue by michaelryancaputo** [atlassian/react-beautiful-dnd#35]
## Bug or feature request?
bug

### Expected behaviour
destination index should be a positive integer

### Actual behaviour
it is a negative integer

### Steps to reproduce
Example provided.

### Demo
https://www.webpackbin.com/bins/-KrfpepwyWQ_atxgqqn8

**Comment by alexreardon** [comment]
At this time transitioning between lists is not supported. The initial cut has a sort of half working multi list experience but it has not been finished yet.

#2 

We are starting work on this very soon.

**Comment by michaelryancaputo** [comment]
Appreciate the response
