### ISSUE TITLE
Animation (bug?) on Firefox

### ISSUE THREAD

**Issue by Amev** [atlassian/react-beautiful-dnd#357]
## Bug or feature request?
Bug may be ?

### Expected behavior

No re-render of the animation.

### Actual behavior & Steps to reproduce

On Firefox, when you right clic on an element and have it in selection and then move it down in the list, the elements placed before the new position have their animation re-render or something like this... Is this a normal behavior ?

[Demo](https://codesandbox.io/s/k260nyxq9v)

### Browser version

Firefox 58.0.2

### Demo

This is from your vertical list basic usage:

![](https://thumbs.gfycat.com/BronzeRevolvingDeer-max-1mb.gif)

**Comment by alexreardon** [comment]
I can reproduce. I have an explanation and fix. I’ll put both up on Monday

**Comment by Amev** [comment]
Ok perfect ! Thank you :)
