### ISSUE TITLE
(Bug ?) Nested interactive elements : Button with other than only text

### ISSUE THREAD

**Issue by LouisCuvelier** [atlassian/react-beautiful-dnd#359]
Firstly, thanks for this amazing work !

## Bug or feature request?
Nested interactive elements works very well. But, when you put something in the button, other than text, (`<strong></strong>` for example) dragging is no more blocked.

### Expected behavior
Dragging should be blocked no matter what button contains. Useful for svg icons for example.

### Actual behavior
I can drag an element if it's not only text in the button. 

### Steps to reproduce
Just put `<strong>Text</strong>` in a button.

### Browser version
Chrome 64.0.3282.186

### Doubt
Maybe I'm wrong and it's not a bug. So, is there a workaround ?

**Comment by alexreardon** [comment]
Interesting: elements within a `button`. It is permitted to have [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) within a `button`. I am not sure if this is limited to one level or multiple. 

Regardless we will need to update our check for `button` elements by walking the parent tree as we do for content editable elements

**Comment by LouisCuvelier** [comment]
Thanks for your update.

But, a button like this isn't blocked :
```
<button>
    <div>
        <svg>
            ...
        </svg>
    </div>
</button>
```

Is there a way to manage this with this 6.0.0 ?
