### ISSUE TITLE
Readme example uses old version

### ISSUE THREAD

**Issue by ChristopherChudzicki** [atlassian/react-beautiful-dnd#360]
## Bug or feature request?
Bug (in documentation)

### Expected behavior
Codepen example in [README/distribution-bundle](https://github.com/atlassian/react-beautiful-dnd#distribution-bundle) would use current version of `react-beautiful-dnd`.

### Actual behavior
Codepen example in [README/distribution-bundle](https://github.com/atlassian/react-beautiful-dnd#distribution-bundle) uses old version 3.0 and does not work in recent (5.0) version. 

### Steps to reproduce
Change example from docs (https://codepen.io/alexreardon/project/editor/ZyNMPo) to use version 5.0 of `react-beautiful-dnd`

### Browser Version
Chrome 64.0.3282.186

### Demo
Here are codepens comparing the behavior:

- [Codepen from documentation: uses 3.0: works fine](https://codepen.io/alexreardon/project/editor/ZyNMPo)
- [Same codepen, but using 5.0: dragging is broken](https://codepen.io/ChristopherChudzicki/project/editor/XkWeNd)

### Comment
This was confusing for me (and probably other newcomers): the first thing I did when trying to learn about this library was run the codepen example offline. But NPM installed version 5.0 and the API has changed slightly. Behavior can be fixed by changing `provided.draggableStyle` to `provided.draggableProps.style` as mentioned in [this stackoverflow](https://stackoverflow.com/a/48431236/2747370) question.

Admittedly, the distribution-bundle section of the README is probably not the best place for me to grab examples from, but the codepen was very convenient.

Still, it would be great for the README to use examples that work in the current version.

**Comment by alexreardon** [comment]
Good call. Let's fix it

**Comment by alexreardon** [comment]
I have updated the codepen to work with the latest version 🎉

**Comment by alexreardon** [comment]
Thanks for picking this up @ChristopherChudzicki

**Comment by abnish07** [comment]
Hi, I have implemented drag and drop functionality in my project. I have used 'DIV' to implement these functionalities. When I use 'Button' instead of 'DIV', it won't work for me. But When I changed it to "DIV", it works fine for me. 
So, I would like to ask, Does drag and drop is not working for Button?
Answers should be appreciated.
Thank you in Advance.
