### ISSUE TITLE
onDrop event callback

### ISSUE THREAD

**Issue by brandonmowat** [atlassian/react-beautiful-dnd#361]
Hey All,

Just wondering if there are any events available for me when a user `mouseUp`'s and a Draggable begins animating to it's final position?

Any help is appreciated!

**Comment by alexreardon** [comment]
Currently we do not expose this as it is an implementation detail. For keyboard or touch dragging you would not receive a mouseup. You are welcome to bind your own event handlers to try and sniff out these events but it would not be advised. You could do this by add event handlers to the window after onDragStart. You could probably need to add these as `capture` phase handlers as we prevent default and stop propagation on the events normally.

Why are you interested in this event?

**Comment by brandonmowat** [comment]
I want to add an expanding animation to a draggable when the user releases it.

Thanks!

**Comment by alexreardon** [comment]
Let me know if that did not help you achieve what you wanted to!
