### ISSUE TITLE
Quick start guide

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#363]
We should create a guide that walks people through creating a board setup. This will introduce people to the core ideas of the library and help them get up and running quickly.

**Comment by LuoweiC** [comment]
I am a beginner and there is no more detailed documentation to support my successful operation locally

**Comment by atav32** [comment]
@LuoweiC I am *not* a beginner and I still want a guide 😂

**Comment by jacobwicks** [comment]
I wrote a simple project that lets you move draggable objects between two droppable lists. Hope this is helpful to someone.

https://github.com/jacobwicks/rbdnd-2-list-example

**Comment by alexreardon** [comment]
I am really keen to write this. I was mostly through one, but I have stopped progress on it during our upgrade to React 16 #406 and adding our new website #343. Rationale:

- The API will change as a part of React 16
- How we author the docs will change due to the new website

So for now we are in a lame situation of no starter docs. However, this situation will change soon!

**Comment by atav32** [comment]
How about editing the README to make the Codepen example easier to find?

**Comment by alexreardon** [comment]
The codesandbox examples are already up the top of the docs
https://github.com/atlassian/react-beautiful-dnd#basic-usage-examples

**Comment by fihawkins** [comment]
Any news on the quick start guide? Want it so bad!!!!

**Comment by Sayvai** [comment]
@alexreardon you could also add [Multi Drag](https://react-beautiful-dnd.netlify.com/?selectedKind=Multi%20drag&selectedStory=pattern&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) under advanced topics. 😃

**Comment by alexreardon** [comment]
I have been actively working on a screencast series to help people get started quickly with the project 🤘🎉🤩

![img_3105](https://user-images.githubusercontent.com/2182637/39866991-3d2fcf58-5496-11e8-8659-34cefe274fcd.JPG)

More details coming soon

**Comment by alexreardon** [comment]
This should be landing soon 💃

**Comment by samundrak** [comment]
This is 3rd time i am trying to work with this library, but i always fail to understand from start, please do some videos/article sooner :+1:

**Comment by jamiebuilds** [comment]
@samundrak I understand you're frustrated, but that was not the right way to engage with an open source project.

It's like: If you were going out of your way to do a favor for a stranger, you wouldn't appreciate them yelling at you to do it faster. It's inappropriate.

**Comment by samundrak** [comment]
Hey, first of all, I am very sorry, I didn't mean to be bad,
I was just excited about this library and your video, please forgive me,

**Comment by cheshireoctopus** [comment]
Looking forward to the screencasts, @alexreardon - thank you 👍

Possible to include a portion on writing basic testing? Enjoying using the library but having trouble testing it effectively.

**Comment by annie-mathis** [comment]
super excited for the quick start guide! The name is fitting - it really is a beautiful library. I look forward to understanding it in more depth.

**Comment by alexreardon** [comment]
So am @annie-mathis! We are just waiting in the egghead.io course release queue 👍 

@cheshireoctopus we have an issue to add some testing docs #623

**Comment by alexreardon** [comment]
The course is available!

[Course: Beautiful and accessible drag and drop with `react-beautiful-dnd`](https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd)


![overview](https://user-images.githubusercontent.com/2182637/43372795-2680071e-93e8-11e8-8d4a-2114df0431dc.gif)

**Comment by icehongssii** [comment]
@alexreardon  May God bless this guy with lots of force

**Comment by nchathu2014** [comment]
I am trying to drag an isolated button it did not work for me. Any thoughts?

**Comment by atav32** [comment]
Wooow, this is waaay beyond my expectations! @alexreardon how can I buy you a beer? 🍺
