### ISSUE TITLE
Resizable columns when used with re-resizable

### ISSUE THREAD

**Issue by gavrichards** [atlassian/react-beautiful-dnd#364]
In my project I have draggable columns (much like the board demo) the main difference being that each column is also horizontally resizable, by dragging the right hand edge.
For the resizing functionality I'm using the Re-resizable library: [https://github.com/bokuweb/re-resizable](url)
Independently, I've got the draggable columns and resizable columns both working - but I'm having no luck trying to get them working together.

The problem appears to be related to how the `ref` prop is used.

I have a Column component, and it is currently returning the following. I've removed some properties from <Resizable> which aren't relevant for this question, to keep the code clutter down to what's important.
```
return (
    <Draggable draggableId={'col-' + this.props.col.id} type="COLUMN">
        {(provided, snapshot) => (
            <Resizable
                className={colClass}
                ref={c => { provided.innerRef = c; }}
                {...provided.droppableProps}
            >
                {this.column(provided.dragHandleProps)}
            </Resizable>
        )}
    </Draggable>
)
```

This is giving me this error in the console:
> Updating draggable dimension handler without a targetRef (draggable-dimension-publisher.js:141)

If I change the ref line so that it reads exactly as instructed in the docs here, i.e.
```
ref={provided.innerRef}
```

Then I get no errors until I try and drag the handle, at which point I get this error:
> Uncaught TypeError: Cannot read property 'defaultView' of undefined

I would appreciate any help you can give.

**Comment by alexreardon** [comment]
Working with `refs` can be hard. The `ref` callback of a `Component` (including `Resizer`) returns the instance of the class. This is how you can call `.updateSize` on the ref [in their example](https://github.com/bokuweb/re-resizable#instance-api). On a dom element such a `div` the `ref` callback returns the dom node itself. We require you to provide the dom node to be bound to. Having a look at resizer it looks like it does not expose the DOM node itself that it is bound to. 

Your code needs to call innerRef and not assign it

```js
ref={c => { provided.innerRef(c); }}
or
ref={provided.innerRef}
```

So you have a few options:

- Either you could ask resizer to add another prop (such as `innerRef`) which exposes the dom node ref for the component and then provide that to our `provided.innerRef`. They do expose the dom node in the event handlers but not on mount which seems a bit strange
- You could use `ReactDOM.findDOMNode` to get the dom node from resizer for yourself 
- Bind your draggable to a node a different node within a Resizable

**Comment by alexreardon** [comment]
Let me know how you go

**Comment by gavrichards** [comment]
Thank you @alexreardon, that's so helpful.

**Comment by gavrichards** [comment]
I ended up managing to separate the elements out. It was your clarity about how the difference in use of `ref` works that helped me understand this though, so thank you @alexreardon.

```
return (
    <Draggable
        draggableId={'col-' + this.props.col.id}
        type="COLUMN"
    >
        {(provided, snapshot) => (
            <div
                className="si-col-positioner"
            >
                <div
                    className="si-col-draggable"
                    ref={provided.innerRef}
                    {...provided.draggableProps}
                >
                    <Resizable
                        className="si-col"
                        size={{ width: width, height: '100%' }}
                    >
                        {this.column(provided.dragHandleProps)}
                    </Resizable>
                </div>
                {provided.placeholder}
            </div>
        )}
    </Draggable>
)
```

In case it helps, my CSS looks like this:

```
.si-col-positioner {
    display: flex;
    flex-direction: column;
}

.si-col-draggable {
    display: flex;
    flex-direction: column;
    margin-left: 5px;
    height: 100%;
}

.si-col {
    height: 100%;
    background-color: #fff;
    vertical-align: top;
    white-space: normal;
    position: relative;
}
```

I'm now suffering really bad frame rate drop when dragging the columns, even though I've got `shouldComponentUpdate` in place, and have console logs in to prove rendering is not taking place. Anyway, that's a separate issue.

**Comment by marcelorl** [comment]
@gavrichards if you have a thousand console.log printing for every render, then you may get this "frame rate drop". try turning them off (including redux-logger).

**Comment by gavrichards** [comment]
@marcelorl it ended up being because Resizable was directly inside the Draggable function, and was being rerendered when it didn’t need to be. The solution I think was to put Resizable inside another component I controlled and then use shouldComponentUpdate to prevent this from happening.

**Comment by pushpanjalip** [comment]
@gavrichards  can you please share your code for reference. It will be really helpful.

**Comment by kaptux** [comment]
@gavrichards [here ](https://codesandbox.io/s/m5r8322wwj) I leave a sample of a resizable-orderable column table using re-resizable. Can help for other use cases.

**Comment by CMDezz** [comment]
> @pushpanjalip [here ](https://codesandbox.io/s/m5r8322wwj) I leave a sample of a resizable-orderable column table using re-resizable. Can help for other use cases.

it hepled me alots, thanks mate!
