### ISSUE TITLE
Improve flow for dispatch maps

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#366]
A few places in our code base we write code like this:

```js
const callbacks: DimensionMarshalCallbacks = {
      cancel: () => {
        this.store.dispatch(clean());
      },
      publishDraggable: (dimension: DraggableDimension) => {
        this.store.dispatch(publishDraggableDimension(dimension));
      },
      publishDroppable: (dimension: DroppableDimension) => {
        this.store.dispatch(publishDroppableDimension(dimension));
      },
      bulkPublish: (droppables: DroppableDimension[], draggables: DraggableDimension[]) => {
        this.store.dispatch(bulkPublishDimensions(droppables, draggables));
      },
      updateDroppableScroll: (id: DroppableId, newScroll: Position) => {
        this.store.dispatch(updateDroppableDimensionScroll(id, newScroll));
      },
      updateDroppableIsEnabled: (id: DroppableId, isEnabled: boolean) => {
        this.store.dispatch(updateDroppableDimensionIsEnabled(id, isEnabled));
      },
    };
```

Were we create a function with the same signature as the inner function just so we can use `dispatch` the inner function without the consumer knowing. This wrapping is done to ensure that the functions have the correct flow type. Ideally we could create a helper to do this internal wrapping while maintaining the correct type signature for the inner function.

Something like:

```js
withDispatch({
  cancel: clean,
  bulkPublish: bulkPublishDimensions,
  //...
});
```

Where the `cancel` and `bulkPublish` functions would have the same type as `clean` and `bulkPublishDimensions` respectively

**Comment by wuweiweiwu** [comment]
@alexreardon can I take this?:)

**Comment by alexreardon** [comment]
Yes @wuweiweiwu that would be great!

**Comment by alexreardon** [comment]
I am completing this one as a part of #493
