### ISSUE TITLE
Move from push state to pull state

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#367]
We currently use `redux` and `react-redux` to propagate changes to our components. This allows us to only render components in a tree that need to in response to a state updates. However, this comes at a cost: lots of memoization checks in connected components. Fundamentally this is because every subscriber to the store gets notified of a change and needs to determine whether to render. Ideally only component subscribers would be called if they are the ones that needed to update. 

Potentially this could be done with [`MobX`](https://github.com/mobxjs/mobx) and specifically the [`Mobdux` pattern](https://medium.com/@cameronfletcher92/mobdux-combining-the-good-parts-of-mobx-and-redux-61bac90ee448).

Things we would need to investigate:

- How much of a performance win do we get?
- How much work would be required to move from redux?
- How much kb would it add? It looks like the lib costs 58kb minified - bigger than our whole lib!

**Comment by jamiehill** [comment]
FWIW, we're using `react-beautiful-dnd` in a project, also using `mobx`, so am a bit aggrieved that I'm also having `react-redux`, `redux` and `redux-thunk` added to my bundles.

That said, this is a great module, so can live with that hit.

**Comment by TrySound** [comment]
There is also small alternative [derivable.js](https://github.com/ds300/derivablejs). It's only 9kb minified.

https://unpkg.com/derivable@2.0.0-beta.3/dist/

**Comment by alexreardon** [comment]
I think for now we'll wait and see where things land with the new `Context` api. I think this will open up all new optimisation paths. I am hopeful that redux will be able to leverage it directly and we might get some nice perf gains from that

**Comment by alexreardon** [comment]
@Feiyang1 can you please create a seperate issue, it looks like it is not related to this issue.

I will keep this thought on the back burner, but for now we will stay with redux
