### ISSUE TITLE
Upgrade to the latest version of flowtype

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#37]
Details:
https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

/cc @thejameskyle how would this change play with your prop type generator?

**Comment by thejameskyle** [comment]
I need to rework it to lookup `Props` from the type parameter instead of from the class property.

**Comment by alexreardon** [comment]
I am thinking of dropping prop types... not sure

**Comment by alexreardon** [comment]
https://flow.org/en/docs/react/

**Comment by alexreardon** [comment]
I tried to upgrade, but sadly I am unable to until eslint is fixed: https://github.com/yannickcr/eslint-plugin-react/issues/1376

**Comment by thejameskyle** [comment]
https://github.com/yannickcr/eslint-plugin-react/issues/1376#issuecomment-325101762

**Comment by alexreardon** [comment]
I think we should be good to start on this one now

**Comment by alexreardon** [comment]
I tried to upgrade today but the eslint plugin is still yet to be fixed. No harm in waiting for now

**Comment by alexreardon** [comment]
Closed by #181
