### ISSUE TITLE
Shortcuts customization

### ISSUE THREAD

**Issue by kulakowka** [atlassian/react-beautiful-dnd#38]
You did an amazing library. But to use it is not very convenient. Let me propose my own version:

**When element is't selected:**
<kbd>tab</kbd> - move focus to next element
<kbd>shift</kbd> + <kbd>tab</kbd> - move focus to previous element
<kbd>space</kbd> - for select element

**When element is selected:**
<kbd>tab</kbd> to move selected element to next position
<kbd>tab</kbd> + <kbd>tab</kbd> to move selected element to previous position
<kbd>esc</kbd> or <kbd>space</kbd> - to remove selection from element

It seems to me more convenient and intuitive.

Do you plan to add a customization to shortcuts?

**Comment by alexreardon** [comment]
We spent a fair amount of time to find default keyboard bindings that work across a number of scenarios. Something to keep in mind is that we will soon support horizontal dragging and transitioning between lists. At that point using the arrows will be a bit more powerful.

However, yes - we are planning on allowing a level of control over the keyboard bindings. However, the details of this have yet to be confirmed.

We will track it in #40 

Thanks for the suggestions!

**Comment by danieldelcore** [comment]
Related: https://github.com/atlassian/react-beautiful-dnd/issues/40
