### ISSUE TITLE
Passing extra info for Source And Destination on drag end 

### ISSUE THREAD

**Issue by rishantagarwal** [atlassian/react-beautiful-dnd#380]
## Bug or feature request?
Looking for some help

## Question

Is there a way to pass in extra info for source and destination in Drag End ?

<img width="835" alt="screen shot 2018-03-12 at 12 02 50" src="https://user-images.githubusercontent.com/2218422/37263833-53315434-25ed-11e8-975f-b04c48e3d997.png">

**Comment by alexreardon** [comment]
Right now we just expose the id of the droppable that you start on and end on as you can see. You should be able to use this id to look up whatever information you like from your own state
