### ISSUE TITLE
Dynamically created droppable with auto scrolling on drag

### ISSUE THREAD

**Issue by nicubarbaros** [atlassian/react-beautiful-dnd#385]
Hey community, thanks for the auto-scrolling. It's just what we need to create a better experience with the calendar I am building. However, I am facing a small problem. I could not find it in the opened/closed issues.

So my plan is to add new weeks/months to the calendar while I scroll. Each day/cell it is a  droppable and the things inside are draggables. 

## Bug or feature request?
Bug

### Expected behavior
Expected behavior is to keep scrolling after the new droppable/s was/where rendered
### Actual behavior
It looks like the system does not know about the newly loaded droppable/s and does not want to autoscroll further after the new week was added.

### Steps to reproduce
Load new droppable as you scroll down or up.
### Browser version
Chrome Version 65.0.3325.162 (Official Build) (64-bit)

### Demo
http://recordit.co/h2F82mhZyj

**Comment by nicubarbaros** [comment]
Update:
getting this error
`Cannot scroll a droppable with no closest scrollable`

**Comment by alexreardon** [comment]
We do not currently support adding `Droppable` or `Draggable` components after a drag has started. We will be adding support for this as a part of #68

**Comment by nicubarbaros** [comment]
Ahh too bad. Thanks anyway.
