### ISSUE TITLE
Incorrect return for areLocationsEqual

### ISSUE THREAD

**Issue by philnova** [atlassian/react-beautiful-dnd#393]
## Bug or feature request?
Bug

I have an application with nested Droppables (higher-level Draggables contain Droppables, which contain inner-level Dragables). For the inner-level Draggables, `areLocationsEqual` in hook-caller.js incorrectly returns true when I click on a Draggable for the first time (before I have actually dragged it anywhere), and the destination has an off-by-one error (-1 from what it should be). This causes items to incorrectly reorder if I let go of the Draggable.

**Comment by philnova** [comment]
Figured this one out. My inner-level Draggables needed to be wrapped in a div of fixed height. Possibly related to [this issue](https://github.com/atlassian/react-beautiful-dnd/issues/103).

**Comment by alexreardon** [comment]
Glad you got it sorted. I was about to ask for a stand alone example :)
