### ISSUE TITLE
Support transitioning from a vertical to horizotonal list and visa versa

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#4]

**Comment by oyeanuj** [comment]
@alexreardon Thanks for creating this library! Would/could this example also include dragging between grids (instead of a horizontal/vertical only)?

**Comment by alexreardon** [comment]
At this stage grids are out of scope @oyeanuj. Perhaps at some point in the future. For now the focus is lists

**Comment by alexreardon** [comment]
We are hoping to do this as part of #2

**Comment by alexreardon** [comment]
Closing as part of #2
