### ISSUE TITLE
Remove temporary iOS 11.3 fix

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#417]
As a part of #413 and #416 we introduced an always active `touchmove` listener to get around a [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=184250). Once the bug is fixed in webkit I am keen to remove the hack.

Also, the hack was only to get touch dragging working again. Currently any other calls to `event.preventDefault()` will not do anything in webkit (eg `mousemove` is currently not being prevented during a mouse drag). This goes against our [how we use DOM events guide](/docs/guides/how-we-use-dom-events.md). 

When webkit is fixed we will be able to:

1. remove the workaround
2. have consistent event prevention on webkit browsers

**Comment by alexreardon** [comment]
The bug has been fixed in safari and should be released in iOS 12. Once that soaks for a few weeks we will remove the work around from our code

**Comment by alexreardon** [comment]
See the [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=184250) for more info

**Comment by acampagna** [comment]
But there is a followup bug that needs to be fixed: https://bugs.webkit.org/show_bug.cgi?id=185656

**Comment by alexreardon** [comment]
I have included a smaller fix in 11.0.5 and 12.x

**Comment by alexreardon** [comment]
#1407
