### ISSUE TITLE
Control + mouseclick starts a drag event

### ISSUE THREAD

**Issue by smogg** [atlassian/react-beautiful-dnd#420]
### Bug
Opening a context menu with Ctrl+Click starts a drag.

### Expected behavior
Drag shouldn't be started, draggable item should stay in place

### Actual behavior
Draggable element "follows" the mouse even when mouse button is not pressed

### Steps to reproduce
Ctrl + click draggable item, click outside the context menu, move your mouse

### Demo
![control click](https://user-images.githubusercontent.com/1500714/38307183-38b71cbe-3813-11e8-9269-771c3fab4886.gif)

**Comment by alexreardon** [comment]
For sure! We should not start a drag when this happens

**Comment by alexreardon** [comment]
I have created a PR that fixes this issue 🎉

**Comment by smogg** [comment]
🎉 Thank you, sir!
