### ISSUE TITLE
Cannot move with keyboard out of a isDropDisabled list

### ISSUE THREAD

**Issue by nmain** [atlassian/react-beautiful-dnd#430]
## Bug or feature request?
Bug.  Possibly related to issue #400, but doesn't seem to be the same thing.  Unlike that issue, everything is contained on the page and there are no weird overflows.

### Expected behavior

Moving items using the keyboard works.

### Actual behavior

Console Error: Cannot handle keyboard movement event if direction is not provided

### Steps to reproduce

Open this repro: https://codesandbox.io/s/qlxpwkl2xw
Move everything from the first list to the second list.
Then, using the keyboard, try to move an item from the second list back to the first list.

### Browser version

Chrome 65

**Comment by alexreardon** [comment]
Sorry for the delay on this one. It got a bit lost. I am not able to reproduce your issue..

**Comment by alexreardon** [comment]
I misread, I didn't realise I needed to move everything. I can look into this asap

**Comment by alexreardon** [comment]
I am struggling to reproduce this locally

**Comment by nmain** [comment]
Thanks for looking into this!  It will help out my application a lot.
