### ISSUE TITLE
Make bundle size checking fuzzy

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#431]
@TrySound recently made a fantastic change: adding bundle size snapshots to our repo. 

I have changed our package.json so that on install we no longer generate the dist. This means that the bundle size snapshot is not updated automatically on install anymore.

This can cause a bit of friction when automatically merging from master as the snapshot size changes. The hope is to make the bundle size check fuzzy so that we can continue to support basic master merge bumps

https://github.com/TrySound/rollup-plugin-size-snapshot/issues/6

**Comment by alexreardon** [comment]
Change is going in as a part of #406

**Comment by TrySound** [comment]
Ready to go

**Comment by alexreardon** [comment]
Sweet! We'll get onto this soon.

Thanks @TrySound

**Comment by alexreardon** [comment]
Thanks @TrySound !!
