### ISSUE TITLE
Draggables unable to be dragged nor clicked

### ISSUE THREAD

**Issue by rush-levint** [atlassian/react-beautiful-dnd#436]
Hi, I couldn't get server side rendering to work with Next.js [using custom _document.js](https://github.com/zeit/next.js/blob/9ec81c00fad040154df571701b73cb6e3b1b86fa/examples/with-styled-components/pages/_document.js) and then via `resetServerContext()` (inserted at line 6) as mentioned in the docs.

It still display mismatches on the browser console.

Am I missing something?

**Comment by alexreardon** [comment]
That should be all that is required. Can you please post a stand alone
example for us to poke around with? Ideally on codesandbox.io

Cheers

**Comment by rush-levint** [comment]
My bad, it turns out that it's working. The error was from a different source.

```
```

**Comment by nodabladam** [comment]
For those searching how exactly to get Next.js working, this was my _document.js attempt:
```
  static async getInitialProps(ctx) {
    const originalRenderPage = ctx.renderPage;
    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: App => props => {
          resetServerContext();
          return <App {...props} />;
        }
      });
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }
```

**Comment by eddyw** [comment]
@nodabladam you don't need to overwrite `renderPage`. This should be enough for NextJS:

```javascript
CustomDocument.getInitialProps = async (ctx) => {
  resetServerContext() // <<
  return Document.getInitialProps(ctx)
}
```

For a little bit more complex example, this is what I had with NextJS + React-JSS + TS:
```javascript
CustomDocument.getInitialProps = async (ctx: DocumentContext) => {
  resetServerContext() // <<

  const sheets = new ServerStyleSheets()
  const originalRenderPage = ctx.renderPage

  ctx.renderPage = () => {
    return originalRenderPage({
      enhanceApp : App => props => sheets.collect(<App {...props} />),
    })
  }

  const initialProps = await Document.getInitialProps(ctx)

  return {
    ...initialProps,
    styles: [...React.Children.toArray(initialProps.styles), sheets.getStyleElement()],
  }
}
```

**Comment by stephen-dahl** [comment]
@eddyw isnt there a chance of your method messing up under heavy load since getInitialProps is async and not guaranteed to be immediately followed by the render call for the current request? something like this

```
request 1 getInitialProps
request 2 getInitialProps
request 1 render
request 2 render <-- was not reset
```

**Comment by mactanner** [comment]
> For those searching how exactly to get Next.js working, this was my _document.js attempt:
> 
> ```
>   static async getInitialProps(ctx) {
>     const originalRenderPage = ctx.renderPage;
>     ctx.renderPage = () =>
>       originalRenderPage({
>         enhanceApp: App => props => {
>           resetServerContext();
>           return <App {...props} />;
>         }
>       });
>     const initialProps = await Document.getInitialProps(ctx);
>     return { ...initialProps };
>   }
> ```

I guess you haven't enabled reactStrictMode, have you?
In strict mode this is not working for me...
