### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by dthree** [atlassian/react-beautiful-dnd#440]
Hi @alexreardon

Great work on this project, really like it.

I just wanted to give a suggestion on the readme, which I think will help get more users.

It's pretty massive. I was just trying to get started with a basic list drag and drop. I was looking for the getting started section and API, and I had to scroll down quite a bit. I got a little anxious as I didn't know if all the content before that was vital to know or not - whether I was reading features or important notes to getting started. This almost turned me off from using it.

Some examples:

- It's very interesting how animations are composed - this shouldn't be written before the user learns how to install it. I would suggest the carefully designed animations section should be reduced to a single sentence, at least on the readme with links to more data.

- Same applies to the detailed write-ups of its 5 applications. They can be summarized in bullets with a wiki link to the full details.

Because there's a ton going on, I would suggest breaking a lot of your readme off into wiki, and then providing the bare essentials in the readme that directs experienced users to the right API data / gotchas, and new users straight into how to install and get started with some basics.

---

Anyways, just a suggestion, and you can take it with a grain of salt if you'd like :)

**Comment by alexreardon** [comment]
I agree with all your points. I am a big fan of starting simple and growing from there. Originally we started with a single `readme.md` file. This was to allow us to focus on solving other problems. However, it has reached a point where it is not a useful strategy any more. We are in the process of creating a stand alone website #343 and a quick start guide #363 which should resolve these issues.

Thanks for reaching out and offering your advice - it is valuable

Cheers

**Comment by dthree** [comment]
Nice! A website is a great idea :)
