### ISSUE TITLE
Fix rollup UMD bundle size regression

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#447]
Caused by #446. We had a non-trivial bump due to a rollup upgrade. This issue is to track getting those kb's back

**Comment by TrySound** [comment]
This also can be fixed when babel will upgrade `core-js` with esm format.

Ref https://github.com/babel/babel/pull/7646

**Comment by alexreardon** [comment]
I think this is good now @TrySound 

Reference: #590
