### ISSUE TITLE
not able to drop in all droppable container in nested draggable hiearchy,

### ISSUE THREAD

**Issue by gogoku** [atlassian/react-beautiful-dnd#451]
Hey,

I have created a nested draggable hiearchy, this is where i have reached so far

[Code Sandbox link for example](https://codesandbox.io/s/x3wzy4zxn4) 

I want to move each section into any place in the Container

But right now i am only able to drag a section and drop it within its enclosing Droppable area
I tried giving same type for both Draggable and Droppable , but that ends up making all sections move randomly

Need help on this , Thanks

**Comment by gogoku** [comment]
> [``](

- 

- [ ]# 1. url

)

**Comment by gogoku** [comment]
sorry accidentally close it

**Comment by alexreardon** [comment]
We currently do not support a draggable moving into a nested item. You can only rearrange in flat structures at this stage

**Comment by gogoku** [comment]
Problem with implementing a flat structure is i will not know the hierarchy when i drop a dragged item

I am aiming to build something like this
http://tamagokun.github.io/example-react-dnd-nested/ 

Any idea on how i can achieve this.?

**Comment by bridgewaterlabs** [comment]
hierarchy should be supported, there are many use cases for it... 
is there any specific reason for not supporting it? any issue you see as big problem?

I can dive into the code maybe but if you decded not to do it maybe there is a good reason

**Comment by stevegula** [comment]
Any chance at revisiting this? I'd like to be able to go multiple levels deep
