### ISSUE TITLE
Adding or removing a Droppable during a drag is currently not supported

### ISSUE THREAD

**Issue by nicubarbaros** [atlassian/react-beautiful-dnd#452]
I couldnot see anything about this breaking change in the log of the new release. 

Before 7. I could load new Droppables and my Draggable will be intact. But couldnot drop on it. Now my droppable dissapears when I am loading a new Droppable. 

Have I missed something?

**Comment by lukebatchelor** [comment]
Hiya,

Would you mind creating a small reproducable test case that shows what you mean? 

https://codesandbox.io/s/k260nyxq9v

**Comment by nicubarbaros** [comment]
It will take me some time to create a reproducible test but here are 2 Gifs. 

`Version. 6.0.2 `
I am grabbing a `Draggable` and scrolling down. It loads the next month (a bunch of Droppables). I can't Drop (I know this), however my `Draggable` it is still draggable.
http://recordit.co/3UP6dzuvO6

`Version 7.0.2`
The same workflow, however now my `Draggable` disappears (it goes back to its Droppable) and I get the error.
http://recordit.co/kzY47R7133

Thank you and hopefuly this will clarifiy a little bit about the issue (If it as is supposed to be, or it is a bug).

**Comment by alexreardon** [comment]
This was an intentional change. It was technically not supported before so it may have had some unexpected consequences in particular cases. We now are more explicitly locking out this functionality to avoid bugs. We will be re adding this as a part of #68

**Comment by synapse** [comment]
I'm having the same issue and I don't understand how to fix this. I have a column rows example. It gives me this error after i move a column and I try to move a row. The first time it shows me the error but the second time it works (until I move a column again).

**Comment by alexreardon** [comment]
Dynamically adding or removing draggables or droppables is currently not supported. We are looking at adding support in the future #484
