### ISSUE TITLE
When I use multiple lists, the display interface fails

### ISSUE THREAD

**Issue by vuductuyen** [atlassian/react-beautiful-dnd#453]
Error only show on repo on my pc, 
does not appear on codesandbox  https://codesandbox.io/s/mj5x0z3qxy
![err](https://user-images.githubusercontent.com/26272336/38970009-5d9179b6-43bd-11e8-85bf-4aa5f716cd7a.png)

**Comment by alexreardon** [comment]
Does it appear on codesandbox on your pc?

**Comment by alexreardon** [comment]
I am not following. Can you please explain a different way?

**Comment by vuductuyen** [comment]
@alexreardon Thank you for your attention! when i download code from your codesandbox account, i seen package have version 7.0.2, i check my version on my pc it's 4.0.1. 
I think it is the main problem! because i downloaded example on the docs, and it's version 4.0.1!
