### ISSUE TITLE
Guidance on integrating `provided.innerRef` with custom Components

### ISSUE THREAD

**Issue by datadidit** [atlassian/react-beautiful-dnd#455]
## Question

Hi, 

Love all the examples and have been able to follow along well with them. I'm wondering if someone can provide guidance on best ways to integrate `provided.innerRef` with Custom Components. The examples do a great job of showing how to natively integrate with native html elements like `<div>` and `<tr>`. When I try to integrate say a Material UI [TableBody](https://material-ui-next.com/api/table-body/) component with droppable and [TableRow](https://material-ui-next.com/api/table-row/) with draggable I run into this error:

```
Uncaught TypeError: Cannot read property 'defaultView' of undefined
``` 

Here's my sample code for [this](https://github.com/datadidit/react-sandbox/blob/master/src/react-beautiful-dnd/MUITableExample.js)

I think I need to do something like what's done in the Table Example code from the examples [here](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/table/with-fixed-columns.jsx#L97). Figured I'd ask to see what best practices might be and if this is even possible. 

Thanks in advance.

**Comment by datadidit** [comment]
@alexreardon Thanks for the feedback.

**Comment by JohnWestwig** [comment]
Wondering if this will make it into the docs anytime soon.

**Comment by alexreardon** [comment]
Soon 😊

**Comment by alexreardon** [comment]
My "soon" was fairly accurate 👍

**Comment by alexreardon** [comment]
Here is the link to the new guide: [using `innerRef` guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md)

**Comment by biancadennis** [comment]
Could you update the readme? It's still linking here: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-inner-ref.md

**Comment by alexreardon** [comment]
sure

**Comment by alexreardon** [comment]
done :)

**Comment by buddythumbs** [comment]
Before I open a new issue on this I said I would comment here as I am having exact same issue with `react-beautiful-dnd@3.0.0`  and `styled-components^2.4.0` and `react^16.5.2`.

I have a styled component (div) as my draggable component. When I use `ref={provided.innerRef}` I get `TypeError: Cannot read property 'defaultView' of undefined`. When I swap out my styled component for a div and change nothing else it sort of works. By sort of, I mean the placeholder shows when I drag the task into another droppable but the actual task itself doesn't visually move at all with the cursor.

Any ideas?
