### ISSUE TITLE
ETA on dragging to nested droppables

### ISSUE THREAD

**Issue by BennievanderWel** [atlassian/react-beautiful-dnd#456]
As I understand, dropping a draggable from a droppable to another droppable with is a sibling of the draggable, is not supported. 

Is this correct? And if so, is it on the roadmap?

Other than that, great work on the package!

**Comment by alexreardon** [comment]
It is not on our immediate roadmap but we hope to support it at some point. We do not give out any dates for any feature - things will ship when they are ready and when we are happy with the level of polish. 

> great work on the package!

Thanks! 😊

**Comment by lxcid** [comment]
Look forward to having this functionality! Just for the record 😁
