### ISSUE TITLE
Droppable is a scroll container doesn't allow to drop

### ISSUE THREAD

**Issue by izorg** [atlassian/react-beautiful-dnd#461]
## Bug or feature request?
bug

### Expected behavior

https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=Droppable%20is%20a%20scroll%20container&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

### Actual behavior

https://codesandbox.io/s/nr14lx21pl

### Steps to reproduce

https://codesandbox.io/s/nr14lx21pl

### Browser version

Chrome 65

### Demo

https://codesandbox.io/s/nr14lx21pl

![screencast 2018-04-20 14-55-49](https://user-images.githubusercontent.com/417096/39052090-1845b5ae-44ab-11e8-8dc1-60004846a00b.gif)

**Comment by alexreardon** [comment]
Good find. I will work on this asap.

In the mean time if you wrap your droppable in a scroll container it should be all good.

We have lots of tests for droppables that are scroll containers, but obviously this was missed. Sadly none of our examples exercise this directly
