### ISSUE TITLE
What's the best way to fix the height of a "Droppable" container.

### ISSUE THREAD

**Issue by bfang711** [atlassian/react-beautiful-dnd#462]
I would like to make several lists ("droppable" containers) and I would like to fix the height of each of "droppable" container, so that it can contain 10 draggable elements maximum (for simplicity, lets assume elements heights are all equal). In other words, no matter it has 1 element, or 10 elements, the container size is not changing, and not to expand/shrink when I drag and drop a element from/to other lists.

thank you.

**Comment by alexreardon** [comment]
css?

We do not control what you render or how you render it. 

If you know the height of each item you can hard code your list sizes to be x10 of that and set overflow:hidden. Keep in mind that if a list already has 10 things in it and a user wants to move another one there we will try to create room in the new list for the new item.

**Comment by MehdiJarraya** [comment]
I suggest using {provided.placeholder} to fix droppable height while dragging an element

**Comment by sanderfish** [comment]
> I suggest using {provided.placeholder} to fix droppable height while dragging an element

Lol, thanks. Gets me every single time I set up a new dnd 😭
