### ISSUE TITLE
Tabbing a list, dragging a list item with space + up/down arrows, then clicking on dragged item causes item to move back to original position

### ISSUE THREAD

**Issue by ambrwlsn** [atlassian/react-beautiful-dnd#467]
## Bug or feature request?

Bug

### Expected behavior

Tabbing through a list of items, using spacebar and up/down arrow keys to move (drag) them, then clicking on a moved item that is still in focus should NOT cause it to move back to where it started.

### Actual behavior

https://codesandbox.io/s/6jlyl9rxqk

See codesandbox example from wschuster-nm. 

When items in list 1 are highlighted/focused using `TAB`, they can be moved by pressing `SPACE` and using `UP` or `DOWN` arrow keys. When clicking on an item in focus that has been moved, it moves back to where it started.

### Steps to reproduce

Focus on list items using `TAB`
Move (drag) a list item by pressing `SPACE` and using `UP` or `DOWN` arrow keys 
Click on a moved (dragged) list item using mouse.
It will move back to where it started.

### Browser version

All browsers

### Demo

https://codesandbox.io/s/6jlyl9rxqk

See codesandbox example from wschuster-nm.

**Comment by alexreardon** [comment]
While an item is dragging with a keyboard, any mouse down interaction will cancel the drag.

If you press `SPACE` again after you have moved the item then you are free to click on it.
