### ISSUE TITLE
Horizontal list with scroller doesn't work when need to scroll

### ISSUE THREAD

**Issue by supnate** [atlassian/react-beautiful-dnd#468]
## Bug or feature request?
Bug

### Expected behavior
When dragging an item with scrolling, the target position should be correct
### Actual behavior
The drop position is incorrect
### Steps to reproduce
Access the example: https://codesandbox.io/s/mmrp44okvj
Narrow the preview window to show scroll bar then drag over the right border.
### Browser version
Chrome latest

### Demo
https://codesandbox.io/s/mmrp44okvj

**Comment by alexreardon** [comment]
See #268

We need to add some docs about this
