### ISSUE TITLE
Drop on cursor

### ISSUE THREAD

**Issue by csalvatori** [atlassian/react-beautiful-dnd#474]
Feature request

Currently when dragging an item, it determines the selected droppable based on the center of the draggable. Can we get an option to either use the center of the draggable or the current cursor position.

**Comment by alexreardon** [comment]
Not at this stage. This goes against our metaphor of physicality we are going for

https://github.com/atlassian/react-beautiful-dnd#driving-philosophy-physicality

Is there a specific interaction you are looking to power?
