### ISSUE TITLE
Allow dynamic additions / removals of dimensions during a drag

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#484]
This would need to work for both Draggable and Droppable dimensions

Needed to facilitate virtualisation #68.

It would also be useful as its own thing. By supporting this we then unlock lazy loading lists during a drag

**Comment by alexreardon** [comment]
On paper

![img_3073](https://user-images.githubusercontent.com/2182637/39457021-35729256-4d2e-11e8-9a11-4d7d6b31d798.JPG)

**Comment by alexreardon** [comment]
On paper:

![img_3075](https://user-images.githubusercontent.com/2182637/39457044-5f9a0c3a-4d2e-11e8-887f-e14ea1e27d6a.JPG)

**Comment by alexreardon** [comment]
Removals is actually a bit more complicated. If we remove a Draggable from a list then we really need to capture the dimensions for everything after the removed item as well as the list itself. Good times

**Comment by alexreardon** [comment]
Here I am thinking things would be easy. I was wrong.

### My troubles

As soon as you introduce dimension changing there are a few things that can happen:

Adding anything can push other items around
- Adding a Draggable to a Droppable can move other Draggables down
- Adding a Draggable to a Droppable can change the size of the Droppable
- Adding a Draggable to a Droppable can push other Droppables and its children Draggables around
- Adding a Droppable can push other Droppable's around, and its children Draggables

Removing anything can push other items around for similar reasons

### Option 1: Saftey

The only safe option is to recapture all dimensions when anything is added or removed. This feels super heavy. Thankfully we already have an optimised pipeline for this. We can also batch many updates into a single collection phase: eg if you add 5 Draggable's at a time then this would be just one recapture phase.

Additionally, we would need to improve how we handle cancel animations. Currently this is done by animating back to the original position. However, that may no longer be the actual position. Therefore we will need to use our exisiting getHomeOffset function to calculate the drop location. This is not that bad as we already do this when dropping in any other location.

### Option 2: restrictions

We could have a more optimised solution if we enforce a number of limitations on the experience. I am not totally sure what they would all be yet. Things like:

- You cannot add dimensions that would impact the natural starting position of a Draggable
- You cannot add ... WIP

**Comment by alexreardon** [comment]
What we need for virtualisation:

- to capture elements as they are added
- allow dimensions to be removed
- We might need to account for the change in droppable scroll at the time of the mount of a draggable

What we do not need to do:

- recompute the dimensions of the list
- recompute any other dimensions of captured draggables
- assume that anything about a draggable changes during a drag (index, etc)

What need to account for with dynamic additions and removals to lists:

- changing draggable index's
- changing draggable starting coordinates
- growing / shrinking droppables incl foreigns with placeholders...

**Comment by alexreardon** [comment]
## WIP thoughts

Going deep into this problem we are starting to run into limitations of using a virtualised dimension model. At some point there we will need to draw a line around what we will allow to change during a drag. To not to so is to introduce a world of complexity that I do not think we should be adopting.

## Not permitted

- Removing Droppables during a drag (we cannot truely detect if this would impact the placement of other Droppables and Draggables during a drag. Although I guess the same could be said for adding Droppables. Is it best to allow it and just call it out as not supported?)

## Permitted

- Adding Droppables during a drag
- Adding and removing Draggables during a drag

### Limitations:

#### Adding Droppables

- You can only add Droppable's that do not impact the placement of any other Draggable or Droppable components

#### Adding Draggables

- You can only add / remove Draggable's in a Droppable that is a scroll container
- The Droppable needs to be the only Droppable within the scroll container, or a scroll container itself (This is actually an application of the rule *You can only add Droppable's that do not impact the placement of any other Draggable or Droppable components*)

**Comment by alexreardon** [comment]
![img_3091](https://user-images.githubusercontent.com/2182637/39729050-3012822a-529d-11e8-8fc6-f33d51f8f0f4.JPG)

A new internal state model to power these changes

**Comment by alexreardon** [comment]
The approach I am looking into should allow an extreme amount of flexibility. I'll post details as it firms up

Early signs are positive

![dynamic](https://user-images.githubusercontent.com/2182637/39729120-8a7c5d1c-529d-11e8-94ca-cef6b0695047.gif)

**Comment by alexreardon** [comment]
Current dynamic ruleset:

- Don't change the visible dimensions of any draggable / droppable during a drag (width, height, margin, padding, border width). A Droppable can change size based on removals and additions of Draggables
- You are welcome to add draggables and droppables during a drag
- You cannot remove the dragging draggable or the droppable that it started in (critical components)
- Except for critical components, you are free to remove any other droppable or draggables

**Comment by alexreardon** [comment]
I am getting really far with this in #493.

However, I am not happy with the performance at scale as the solution requires a lot of DOM reads whenever a Draggable or Droppable is added or removed. I think if I impose some reasonable limitations we will have a faster experience - and one that is more ready for virtual lists #68 

### Proposed limitations 
> for speed 🚀 and simplicity 🦅 

- Cannot change dimensions of a Draggable or Droppable after mounting (to facilitate no recollecting). 
- Can add new Droppables *1
- Can add new Draggables *2

*1 You can add a new Droppable as long as it does not impact the visual placement of any existing Droppable. Eg a Droppable cannot be added above another one that would push it down
*2 You can add a new Draggable as long as it does not impact the dimensions of a Droppable. Eg it cannot make a Droppable take up more space on the page if that increase would shift any other Droppable. A simple way of overcoming this is to use scroll containers

**Comment by alexreardon** [comment]
Thanks to @Noviny for his help bike shedding this

**Comment by nicubarbaros** [comment]
hey, @alexreardon do you have an ET for this new awesome feature? ^_^

**Comment by alexreardon** [comment]
![soon](https://user-images.githubusercontent.com/2182637/42603170-0e9db024-85b0-11e8-89f9-22f6f88daf86.gif)

**Comment by nicubarbaros** [comment]
https://giphy.com/gifs/5VKbvrjxpVJCM

**Comment by alexreardon** [comment]
![lots-of-paper](https://user-images.githubusercontent.com/2182637/42666816-bd7a0afe-868a-11e8-8ad5-336c92a2f3de.gif)

34 pages of paper (and growing) to figure this one out. That is a record for me

**Comment by alexreardon** [comment]
Not to mention white boarding 😲

**Comment by alexreardon** [comment]
It might not seem that impressive, but getting these tests passing almost broke me

<img width="997" alt="screen shot 2018-07-13 at 3 30 18 pm" src="https://user-images.githubusercontent.com/2182637/42674126-cfea2fbc-86b1-11e8-871f-78d6189147ef.png">

**Comment by justinjdickow** [comment]
NEED

**Comment by justinjdickow** [comment]
@alexreardon Will this also include the ability to dynamically add Droppables as well?

**Comment by alexreardon** [comment]
Well, that is the plan right now! 😊

**Comment by afcastano** [comment]
Following this closely. Thanks!

**Comment by alexreardon** [comment]
The challenge is avoiding shifting other Droppables with additions / removals. 

What we have almost working: adding and removing draggables within a droppable that has a scroll container. The rule is that these changes cannot shift other draggable / droppable components.

Allowing adding / removing of droppables is a bit tricker because it is super easy to make changes that shift the placement of other draggables / droppables. Adding could be a bit safer - but it would need to only be additive and not impact the placement of others.

My current thinking is that in order to improve stability we only allow the addition / removals of draggables within a droppable that has a scroll container. This is the safest

I could make it more flexible and give a warning about not shifting other draggable / droppables but I feel like that might cause friction with consumers.

Thoughts @afcastano, @justinjdickow, @nicubarbaros ?

**Comment by afcastano** [comment]
I personally wouldn't mind either way. Warning or scroll container in droppables works for me since my use case would be to add elements at the end of the list.

=)

**Comment by justinjdickow** [comment]
@alexreardon 
My use case is to add a droppable when the drag starts and if it's not used then remove it when the drag ends. Like a shortcut for adding a new column to a board when dragging an item. If this was natively supported by beautiful-dnd it would be amazing, but I think I can also hide the extra column with styling and unhide it during drag start without changing it's size or position as a workaround.

**Comment by alexreardon** [comment]
I’ll see what I can do

**Comment by nicubarbaros** [comment]
I think is better to block (not give a warning), cuz you know people like to experiment :D. 

My case is fairly complicated, I'm building a calendar where I have a DragDropContext as a scrollable and multiple draggable and droppable inside. Each day has multiple draggable and droppable. To save performance I am rendering the current, previous, and next month. And if the user drags and scrolls to the bottom of the calendar I am loading the next + 1 month. (with plenty of draggable and droppable inside). 

Now the ideal for me would be to always have like 3 months (rendered) (no matter how much the user will scroll). This will mean to drop some droppable and add newly droppable into the context.

**Comment by justinjdickow** [comment]
@alexreardon What about allowing draggables/droppables to be shifted but provide a callback to the DragDropContext which causes it to recalculate, rather than continuously monitoring? In the case of a Draggable/Droppable being added to the scroll container, that callback could be made automatically assuming the user passes the correct prop.

This rule sounds like a dealbreaker for @nicubarbaros
>You cannot remove the dragging draggable or the droppable that it started in (critical components)

**Comment by alexreardon** [comment]
![lazy-loading](https://user-images.githubusercontent.com/2182637/43057059-2eacec6e-8e83-11e8-98bb-4d8d832c429a.gif)

**Comment by tjramage** [comment]
Nice work, @alexreardon! Will this allow us to _change_ existing dimensions of draggables too? A common use case of our app is to shrink the draggables on drag start so that it's easier to reposition...

**Comment by IsenrichO** [comment]
can't wait for this. thanks for all your work @alexreardon

**Comment by philliperodrigues-hotmart** [comment]
Hey @alexreardon, awesome work with this plugin! Congrats!
So, do you have any idea when this will be live? I'm having a hard time to implement one solution, maybe you can think of something: I have a draggable accordion with nested draggables ... When I drag the parent draggable, I have to shrink / ignore the nested draggables, but the plugin considers the height of the nested draggables as well ... Any ideas?

**Comment by salvoravida** [comment]
any news? we need it for auto-expand a droppable tree, and resize draggable items while dragging.

thanks for all your grate work!

**Comment by salvoravida** [comment]
@philliperodrigues-hotmart ok thanks, but what happens if user click on draggable item, so mousedown event is not related to future drag event ?

**Comment by philliperodrigues-hotmart** [comment]
@salvoravida I'm using a element as the dragHandler so I could avoid this kind of problem using a onMouseUp handler.

**Comment by salvoravida** [comment]
> @salvoravida I'm using an element as the dragHandler so I could avoid that kind of problem using a onMouseUp handler.

@philliperodrigues-hotmart i do not understand how you differentiate from onClick event and onStartDrag event. if the user just take mouse down for 2 second you will resize the item, and if then he just do the mouseUp without dragging, you will have a ugly 2 seconds resizing effect.
Am i wrong?

**Comment by salvoravida** [comment]
@philliperodrigues-hotmart i have founded a workaround for dispatch an event justBeforStartDragging -> if you subscribe on internal Store and listen for a "PREPARE" action -> justBeforeStartDragging -> this.setState in your component for changing drop/drag dimension items. 

there is only one problem, the draggable item is in the new position correctly, but mouse pointer is not corrected update. so i lost mouse pointer on it.

My use case is:
a VerticaDropContainer with 10 elements, when user start dragging the number 9, we have to hide [3-4-5-6] items for example. 

any ideas?

**Comment by philliperodrigues-hotmart** [comment]
Well, that would be harder because the browser will resize it's viewport and that is probably what is causing this behavior. You could create a wrapper that keeps the height as it is before the drag to prevent that, but, I think the visual result would not be cool...

**Comment by torre76** [comment]
@salvoravida @philliperodrigues-hotmart 
May I suggest to move your discussion on another issue or maybe into a Gist?
This issue is mainly for waiting @alexreardon update on dynamic additions and removals and it is not such a good thing receive a lot of notifications on a particular problem you are facing.

Thank you!

**Comment by alexreardon** [comment]
I have been thinking of starting a community on slack / something else. That would have been a good place for that discussion. 

Thanks @torre76 for pulling this issue back

**Comment by salvoravida** [comment]
@alexreardon @torre76 sorry for off-topic.

**Comment by alexreardon** [comment]
Closed by #838

**Comment by nicubarbaros** [comment]
## Feature request?
Hey, @alexreardon do you guys plan to work on this feature in the nearest feature? 

```You cannot add or remove a Droppable during a drag. We did this to avoid accidental shifting of other Droppables```. 

At least on adding/removing droppable at the top/bottom of the list. Any ETA?

**Comment by nyshchota0999** [comment]
> I have a app that has the need that maybe is similar to what some guys have here: I have draggable elements with nested draggables (Modules with pages inside the modules). So, when the user starts dragging the Module, I needed to shrink it. So I made a custom onMouseDown handler. This event is called before the onDragStart, so I could shrink the elements before the react-beautiful-dnd could get the dimensions of the elements.
> 
> ```
> <Draggable type={ type } draggableId={id} id={ id } index={ index }>
>         {(provided, snapshot) => {
>           const onMouseDown = (() => {
>             // dragHandleProps might be null
>             if (!provided.dragHandleProps) {
>               return onMouseDown;
>             }
>             // creating a new onMouseDown function that calls my dragOnMouseDown as well as the drag handle one.
>             return event => {
>               dragOnMouseDown && snapshot
>                 ? dragOnMouseDown(event, this.closeModule, provided.dragHandleProps.onMouseDown)
>                 : provided.dragHandleProps.onMouseDown(event);
>             };
>           })();
>           {...}
> </Draggable>
> ```
> 
> Maybe this helps somebody, or lights up a little bit until the new version is released. =)

Hi, Can you send full source where you use this func, it would rly help me

**Comment by juandata** [comment]
Hello Guys, I was able to make this work with a very simple workaround. What I did was to add onBeforeCapture={recalculateHeight}, that function runs before OnDragStart, so within OnBeforeCapture you must change the dimesions of the child elements that are going to be calculated. For example: const recalculateHeight = ()=>setShowOnlyInput(true); what setShowOnlyInput does is that it changes the elements to be displayed of each li item, for example by showing only the title input and no other inputs: 
`if (showOnlyInput) {
    return (
      <Paper
        className={classNames(classes.container, {
          [classes.selected]: isSelected,
        })}
        onClick={onClick}
        elevation={isSelected ? 4 : 0}
        square
      >
        <Grid item xs={12} sm={8}>
          <QuestionInput
            id="question-text"
            label="Question text"
            type="text"
            value={question.text}
            onChange={handleChange('text')}
            margin="normal"
            multiline
            rowsMax="3"
            fullWidth
          />
        </Grid>
      </Paper>
    );
  } //only show title if true, else show the full content of the li item (which in this case is a Paper element)
  return (
    <Paper
      className={classNames(classes.container, {
        [classes.selected]: isSelected,
      })}
      onClick={onClick}
      elevation={isSelected ? 4 : 0}
      square
    >
      <Grid container spacing={2}>
        <Grid item xs={12} sm={8}>
          <QuestionInput
            id="question-text"
            label="Question text"
            type="text"
            value={question.text}
            onChange={handleChange('text')}
            margin="normal"
            multiline
            rowsMax="3"
            fullWidth
          />
        </Grid>
      </Grid>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={8}>
          <TextField
            label="Question name"
            type="text"
            value={question.name || ''}
            onChange={handleChange('name')}
            margin="normal"
            required
            fullWidth
          />
        </Grid>
        <Grid item xs={12} sm={4}>
          <Select
            id="type"
            label="Question type"
            onChange={handleTypeChange}
            value={question.type}
            options={SURVEY_QUESTION_TYPES}
            margin="normal"
            required
            fullWidth
          />
        </Grid>
      </Grid>
      {!!question.type && QuestionTypeForm && (
        <QuestionTypeForm.component
          onChange={handleChange}
          options={question.options}
          nextQuestion={nextQuestion}
          onClickOption={handleSelectOption}
          selectedOption={selectedOption}
          hidden={hidden}
        />
      )}
      {!hidden && (
        <>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={8}>
              <TextField
                margin="normal"
                label="Default next question"
                type="text"
                value={question.defaultNextQuestion}
                onChange={handleChange('defaultNextQuestion')}
                fullWidth
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <Tooltip
                        title="Can be set to Outro to direct to outro instead of another question."
                        placement="top-start"
                      >
                        <IconButton>
                          <InfoIcon />
                        </IconButton>
                      </Tooltip>
                    </InputAdornment>
                  ),
                }}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <Select
                id="pos"
                label="Question position (index)"
                onChange={handleChange('position')}
                value={question.position}
                options={Array.from({ length: size }, (_, i) => i + 1).map((i) => ({
                  value: i,
                  text: i,
                }))}
                margin="normal"
                required
                fullWidth
              />
            </Grid>
          </Grid>
          <div className={classes.questionActionsContainer}>
            {!!onDelete && (
              <Tooltip title="Delete question">
                <IconButton onClick={onDelete}>
                  <DeleteIcon />
                </IconButton>
              </Tooltip>
            )}
            <Tooltip title="Additional settings">
              <IconButton onClick={handleOpenDialog}>
                <MoreIcon />
              </IconButton>
            </Tooltip>
          </div>
        </>
      )}
      {!isEmpty(question) && (
        <QuestionOptionsDialog
          open={openDialog}
          onClose={() => setOpenDialog(false)}
          onChange={handleChange}
          question={question}
        />
      )}
    </Paper>`
In the code above, I only show the title input if the prop mentioned is true, else I show the full content. Finally, when handleOnDragEnd runs the items of each list must be reset, so run setShowOnlyInput(false); within handleOnDragEnd to make each list item recover the full height. 

I hople this helps.
