### ISSUE TITLE
Example code for vertical list fails to run

### ISSUE THREAD

**Issue by Auchindoun** [atlassian/react-beautiful-dnd#488]
## Bug or feature request?
Bug

### Expected/Actual behavior
I'm trying to run the example code for the vertical list on my page to get started, but as soon as I write in `<Draggable ...>` I get an error in the console saying:

```
invariant.js:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `DragHandle`.
```

### Steps to reproduce
Copied code from [example](https://codesandbox.io/s/k260nyxq9v) entirely and rendered in one of my components.

Also just a note, the hosted example does not seem to work as fluently as the basic example in the Storybook does.

**Edit:** This is also happening on all code that I incorporate using Draggable. I can render Droppable just fine but when I add Draggable the app crashes. An example of my personal code is (using material-ui Lists):

```
render () {
  return (
    <DragDropContext onDragStart={this.onDragStart} onDragEnd={this.onDragEnd}>
      <Droppable droppableId='droppable'>
        {(provided, snapshot) => (
          <List ref={provided.innerRef} {...provided.droppableProps}>
            {
              this.state.participants.map((participant, index) => (
                <Draggable key={participant.id} draggableId={participant.id} index={index}>
                  {(provided, snapshot) => (
                    <ListItem
                      innerRef={provided.innerRef}
                      {...provided.draggableProps}
                      {...provided.dragHandleProps}
                    >
                      <ListItemText primary={participant.user.name} />
                    </ListItem>
                  )}
                </Draggable>
              ))
            }
            {provided.placeholder}
          </List>
        )}
      </Droppable>
    </DragDropContext>
  )
}
```

### Browser version
Chrome 66

**Comment by alexreardon** [comment]
It is an environment issue. If it is working on codesandbox then it sounds like your react environment is not set up correctly

You can use [Create React App](https://github.com/facebook/create-react-app) to set up one.

You might not also be using the correct version of react (>16.3)

**Comment by Auchindoun** [comment]
Hmm, I was on React 16.0.0 this morning but upgraded later in the day thinking that might have been the case, but didn't see any successful results. I'll spend some time upgrade my dependencies tomorrow. Thanks :)

**Comment by Auchindoun** [comment]
Sorry to bother @alexreardon, but I updated to React 16.3.2 and the error changed to `Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.` rather than undefined. Is this expected? I don't see anywhere in the docs what other dependencies are needed.
