### ISSUE TITLE
Provide guidance on stripping invariant messages in production

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#490]
We use [`tiny-invariant`](https://github.com/alexreardon/tiny-invariant) for `invariant` checks:

```js
invariant(someConditionThatNeedsToBeTrue, 'Condition was not passed')
```

It would be good to provide a tool to help consumers strip out the second argument to invariant functions for production. This would save a tonne of kb's in production as we would not need to ship lots of messages. It could be an extension to https://github.com/rollup/rollup-plugin-strip or something else. 

It would simply do this:

```diff
- invariant(someConditionThatNeedsToBeTrue, 'Condition was not passed')
+ invariant(someConditionThatNeedsToBeTrue)
```

/cc @lukebatchelor @jamiebuilds I would be keen to get your valuable thoughts on this one

**Comment by alexreardon** [comment]
We do not want to strip the messages out of this library in our esm and cjs builds as we want consumers to know why things fail if they are doing the wrong thing. However, it would be good to have guidance for consumers on how to do this for their production builds.

We could add the invariant stripping for our umd production build

**Comment by alexreardon** [comment]
Maybe just use this one? https://github.com/bloodyowl/strip-invariant

**Comment by jamiebuilds** [comment]
I don't know why you would want to strip the checks altogether because that modifies your code, but you may want to replace the strings with error codes and be able to match them up later

**Comment by alexreardon** [comment]
this is an old issue. We are using `babel-plugin-dev-expression` to remove the invariant messages from production builds, but always keeping the invariant call itself so there is no modified behaviour
