### ISSUE TITLE
**SOLVED** Using <Droppable />, <Draggable /> in app breaks app at run-time

### ISSUE THREAD

**Issue by vrrajkum** [atlassian/react-beautiful-dnd#491]
## Bug or feature request?
Bug

### Expected behavior
App runs properly using standard boilerplate code (minus styling) given here: https://codesandbox.io/s/k260nyxq9v

### Actual behavior
Using `<Droppable />` and `<Draggable />` in my app gives me this run-time error: 
![capture](https://user-images.githubusercontent.com/33333417/39646002-0126dbd4-4fa8-11e8-8c26-3acae43069ef.PNG)

No build-time error logs to the console when I run `yarn start`. When I remove `<Droppable />` and `<Draggable />` from my code the app starts working again.

### Steps to reproduce
Unknown. The exact same code works fine in the following CodeSandbox: https://codesandbox.io/s/81pwo9r1oj

Here is my repository: https://github.com/vrrajkum/contacts

When I add react-beautiful-dnd as a dependency in my app, the console logs that it has an incorrect peer dependency react-16.3.1 (current version of React is 16.3.2), but I don't know if that's the reason for the error. I have tried running `yarn install` , `yarn upgrade`, `yarn remove react-beautiful-dnd && yarn add react-beautiful-dnd`, `rm -r node_modules && yarn install`, but none of them have solved the problem.

### Browser version
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit) on Windows 7 x64 Pro SP1

### Demo
https://codesandbox.io/s/81pwo9r1oj

**Comment by vrrajkum** [comment]
My app's version of React was outdated, updating the version in my `package.json` and re-running `yarn install` fixed the problem.

**Comment by lukebatchelor** [comment]
Thanks @vrrajkum
