### ISSUE TITLE
Example on Documentation

### ISSUE THREAD

**Issue by luthfirrahmanb** [atlassian/react-beautiful-dnd#492]
Hi guys, thanks for this awesome library, but can you give us some good Example on this part https://github.com/atlassian/react-beautiful-dnd#block-updates-during-a-drag, because if you just explain this, it's reall confusing for me, thank you

**Comment by alexreardon** [comment]
I have added this new doc section to hopefully remove confusion:

https://github.com/atlassian/react-beautiful-dnd#how-do-you-block-updates
