### ISSUE TITLE
Any possible to dragging with the wrapped row ?

### ISSUE THREAD

**Issue by crapthings** [atlassian/react-beautiful-dnd#495]
![may-08-2018 14-28-28](https://user-images.githubusercontent.com/1147704/39741338-2128d6c2-52cc-11e8-9c43-f2aedce59fca.gif)

this list is copy from

https://codesandbox.io/s/mmrp44okvj

but i want to make it work with wrapped row, any possible to make this happen ?

**Comment by crapthings** [comment]
it looks someone asked before, close.

https://github.com/atlassian/react-beautiful-dnd/issues/333
https://github.com/atlassian/react-beautiful-dnd/issues/316

**Comment by statico** [comment]
For other people looking for a solution, in #316 @crapthings pointed to a good one: https://github.com/clauderic/react-sortable-hoc#grid-support
