### ISSUE TITLE
Issue changing the state of items...

### ISSUE THREAD

**Issue by NickEmpetvee** [atlassian/react-beautiful-dnd#500]
Hey guys. Great library!

I want to be able to re-render this component with values sent in from redux (this.props...) when the user clicks a specific button in another container. Working with the example here: https://codesandbox.io/s/k260nyxq9v, I inserted the below code to modify the `items` array in the `render()` method:

```
    this.state = {
        items: [{ id: `1`, content: 'this.prop1.from.redux'},
                { id: `2`, content: 'this.prop2.from.redux'},
                { id: `3`, content: 'this.prop3.from.redux'}]
                ...
    }
```

It partially works. The button click causes the the original list to re-render with the new values in `items`. However the drag/drop no longer works. I can drag, and the drag looks like it's dropping appropriately on mouse button release, but the list order snaps back to the original order a split second later.

Any thoughts or advice? Basically, if the value of `this.state.items` changes from what's set in the constructor, there's trouble.

**Comment by alexreardon** [comment]
Can you please provide some more information about your use case? I am not able to entirely understand what you are trying to achieve

**Comment by NickEmpetvee** [comment]
Thank you for the reply. I want to have a React container (maybe named `<BeautifulDND>`) that houses the code at the link above . In another container (maybe named `<BrowseProducts>`), I'd like to display a button or link that, when clicked, updates the list in `<BeautifulDND>` with new values that are still draggable/droppable. Does that make it more clear?

I'm able to update the list in `<BeautifulDND`> by inserting the following into render():

```
        this.state = {
            items: [new values...]
        }
```

I know that's making render() impure so it's not a solution, and it breaks the drag/drop part anyway. I've tried to use `static getDerivedStateFromProps(nextProps, prevState)` to do this without any luck either.

**Comment by NickEmpetvee** [comment]
One more note - I've properly connected redux to `<BeautifulDND>`. That's verified by being able to update the list values in `<BeautifulDND>`, albeit improperly.

**Comment by alexreardon** [comment]
I am still not following 😊

Can you please create a little stand alone example?

**Comment by alexreardon** [comment]
I will close this for now. We can reopen if new information comes to light
