### ISSUE TITLE
Draggable items are below items in the lists to the right.

### ISSUE THREAD

**Issue by joetidee** [atlassian/react-beautiful-dnd#501]
I am using the lates version of this package. I have three vertical Droppable lists. When dragging items from the first or second list, the draggable item appears beneath the items in third list. When dragging across the screen in the opposite direction the draggable item appears above the items. Is there a reason why the draggable item appears beneath the other items like this?

(Difficult to provide a working example as the application is complex, but wondering if someone has experienced this first hand)

**Comment by joetidee** [comment]
Appreciate the comment. That inspired me to look further and found that the container of the draggables had a z-index set. Even though it was lower (40) than the z-index that is auto set on the Draggables (5000) it messed around with the logic. Once I removed the z-index from the containing element it worked fine :)

**Comment by alexreardon** [comment]
Nice
