### ISSUE TITLE
Drag while style zoom 50%, element is not locked to the mouse cursor

### ISSUE THREAD

**Issue by vavdav** [atlassian/react-beautiful-dnd#503]
## Bug or feature request?
Probably bug

### Expected behavior
I have iframe inside my React app, when I want to drag this iframe is scaled (then a user can see more  content to make drag easier). Zoom is made by `body.style.zoom = '50%';`

When user dragging element while zoomed it should follow mouse cursor speed

### Actual behavior
When dragging while zoomed iframe, the element is moving slower than mouse cursor.

### Steps to reproduce
 dragging elements inside zoomed iframe

### Browser version
chrome

### Demo
you can see it on provided example
https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

just inspect inner iframe and set css property zoom to 50% on body tag. Then try dnd.
<img width="740" alt="screen shot 2018-05-15 at 15 39 45" src="https://user-images.githubusercontent.com/215969/40060180-53509060-5856-11e8-8090-32b4c9565457.png">

**Comment by alexreardon** [comment]
Very interesting. css zoom is not a well-supported feature:

[css-tricks](https://css-tricks.com/almanac/properties/z/zoom)

> The zoom property in CSS allows you to scale your content. It is non-standard, and was originally implemented only in Internet Explorer. Although several other browsers now support zoom, it isn't recommended for production sites.

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom)

> Non-standard
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

Given that it is a non-standard feature that is not well supported we won't be investing effort in supporting it. However, somebody is else is welcome to look into this a bit more if they want to!

**Comment by alexreardon** [comment]
It looks like the native api's are returning incorrect values when everything is scaled. We could try to account for this but it is not on our roadmap at all. Feel free to investigate and propose a solution. Cheers
