### ISSUE TITLE
Horizontal drang and drop with multiple lines instead of scroll

### ISSUE THREAD

**Issue by alex6633** [atlassian/react-beautiful-dnd#504]
Hi @alexreardon ,
Thank you so much for this amazing Library !!!
absolutely in love with this.
I am using it for horizontal DND . Is there any way I could create horizontal droppable area with multiple rows in it. so that I don't see the scroll bar and i want to see 4 images in a row and rest in the next rows..
Is it possible ?

Thanks in advance,
Alex

**Comment by alexreardon** [comment]
We do support overflowing within a single droppable at this stage. You would need to create a new droppable for each row. 

Thanks for the affection! ❤️

**Comment by ebonny** [comment]
Shat

**Comment by sefirosweb** [comment]
@alexreardon still is not supported multiple lines right?

I want to add dynamic rows when is inserted a new image, but for a now seems can't do it appear a glitch
And add droppable dynamically seems can break all the logic

![image](https://user-images.githubusercontent.com/20754836/135731683-2b75fd58-91b5-456e-beae-72c719991b30.png)
