### ISSUE TITLE
Usage with custom scrollbars...

### ISSUE THREAD

**Issue by joetidee** [atlassian/react-beautiful-dnd#508]
I am using this package, but am also using the package `react-scrollbar` for the parent of the Droppable. Problem is that `react-scrollbar` enforces `overflow: hidden` on the parent container, so I cannot take advantage of the amazing autoscrolling feature of your package. Can you think of a work-around, i.e. perhaps providing a function to retrieve some positional information that can be used in conjunction with the `scrollYTo()` function provided by `react-scrollbar`?

**Comment by alexreardon** [comment]
If we supported nested scroll containers then this would not be an issue  #131 

But yeah, something could provide some extra info... but seems a bad direction. Can you simply disable the overflow hidden?

**Comment by joetidee** [comment]
I think the reason why it sets `overflow: hidden` is disable the browsers natural behaviour and  implement it's own customisable scrollbar which programmatically moves the contents of the container. Currently, the contents of the container is my `Droppable`.

**Comment by alexreardon** [comment]
This issue should go away when we support nested scroll containers #131. So i'll close this as a duplicate
