### ISSUE TITLE
Add combining support (aka grouping, merging)

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#511]
Adding the ability to hover a `Draggable` on top of another one. 

- This would change the sliding of items to allow for a period of overlap
- The onDragUpdate > DragUpdate type would need to be updated to include the grouping information
- The onDragEnd > DragResult type would also need to be updated
- keyboard interactions would need to be aware of grouping
- A `Droppable` would need to opt into allowing it's child `Draggables` to be groupable (still need to figure out what the opt in story looks like)

**Comment by offerijns** [comment]
Really interesting idea! I wonder if this would enable the following use case:

Let's say you have a sidebar on the left with a list of `projects`, which can be reordered. On the right side, you have a list of `items` within the currently selected `project`, which can be reordered as well. You can also drag an `item` to the sidebar, hovering over a `project`, at which point it will be moved to that particular `project` when dropped.

I think this would require some kind of `groupableType` prop on `Droppables`. The `Droppable` of the sidebar would be something like `<Droppable type="project" groupableType="item" />`.

What do you think @alexreardon ? Also, note that the Trello link you shared is not working, it shows the following error:

> **Card not found.**
> This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.

**Comment by alexreardon** [comment]
Making progress

![grouping-teaser](https://user-images.githubusercontent.com/2182637/44073300-a1ef2a48-9fd6-11e8-81b8-b0f85d936f97.gif)

**Comment by offerijns** [comment]
Looks awesome, @alexreardon !

Would it be possible to add some kind of attribute like `groupableType`, so you can only group items of a certain type on an item? That would be really helpful for the use case I described above.

**Comment by alexreardon** [comment]
![grouping-with-keyboard](https://user-images.githubusercontent.com/2182637/45340494-2438cb80-b5da-11e8-9777-9c83fe9ef828.gif)

Combining with a keyboard 👍

**Comment by yduman** [comment]
I am really looking forward for this feature, since it will be one of the core actions of my project. You said on another issue that this will be landing on version 10. When can we expect this version? Any approximate date?

**Comment by mpseidel** [comment]
Nice one. Looking forward to using it for feature I plan to build.

**Comment by alexreardon** [comment]
Closed by #838. [See version 10 release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)
