### ISSUE TITLE
Moving super large items offscreen

### ISSUE THREAD

**Issue by nedp** [atlassian/react-beautiful-dnd#512]
## Bug or feature request?
Feature request

### Desired behavior

When a large item is dragged towards the edge of the screen, it can be moved such that its centre is offscreen. When a droppable is off screen, we don't allow it to be dropped into. This is usually fine since we don't want to drop items into droppables we can't see.

However when a droppable is only partially visible, it can be difficult to drop an item into it. You need to drag the item far enough that its centre is over the droppable, but if you drag too far then the draggable's centre will be offscreen, so outside of the droppable's bounding box.

### Existing behaviour

In the gif below, when the Draggable is dragged too far to the right, its centre is offscreen. Even though the Droppable extends off the screen too, its dnd dimensions are bounded to the screen. The offscreen card therefore isn't considered within the Droppable, so the Droppable deactivates.

![offscreen-drag](https://user-images.githubusercontent.com/6904248/40217341-c6788cc6-5a5b-11e8-98aa-1fb1109be209.gif)

**Comment by alexreardon** [comment]
I think you might have something strange going on in your example. It looks like we are not performing page visibility checks as a part of detecting which droppable you are after:

https://github.com/atlassian/react-beautiful-dnd/blob/master/src/state/get-droppable-over.js

Without a standalone example, we cannot tell what is going on here.

Something to keep in mind: moving a super wide item over a skinny column will be kinda strange with keyboard dragging.

**Comment by nedp** [comment]
I've got a standalone example here: https://codepen.io/nedp/project/editor/DBjQWr

In the end I was able to get the behaviour I want by adding `overflow-x: hidden` at line 48. This allows me to drag an item past the edge of the screen and drop it in the red zone; counterintuitively, using `overflow-x: visible` prevents me from dropping in the red div past the edge of the screen.

Is this behaviour reliably not going to change? If so, I'll go ahead and use this since it satisfies my use case.

**Comment by alexreardon** [comment]
I doubt it will change

**Comment by nedp** [comment]
Great, thanks. I've updated the codepen at https://codepen.io/nedp/project/editor/DBjQWr to include drag handle usage to effectively shift the drop-point from the centre of the draggable items, further to the right.

Another problem I'm trying to solve is that we’d like to make it so that instead of checking whether the centre of a card is over the top of a Droppable, instead we check that a point near the edge of the card.

To do this, I’m using a drag handle. The drag handle matches the visual width of the card, and the draggable is smaller than that. In the codepen, when you pick up a card, the green area is the draggable and the black are is the drag handle. Visually it’s like this:

```
+--+
|  |   = list
+--+

[     ] = card, drag handle
<   > = draggable
* = point of the card which must be inside the dropzone to active it

Old "Drop point" in the centre of the cards:
+--------------------+
| < [     *      ] > |
| < [     *      ] > |
| < [     *      ] > |
| < [     *      ] > |
+--------------------+

New "Drop point" at the right edge of the cards:
+--------------------+
| [          < * > ] |
| [          < * > ] |
| [          < * > ] |
| [          < * > ] |
| [          < * > ] |
| [          < * > ] |
+--------------------+
```
Is there a more idiomatic way of doing what i’m trying to do?

**Comment by alexreardon** [comment]
Super interesting. Worth playing around with

**Comment by alexreardon** [comment]
Is this still an issue? I think you found a work around after speaking IRL. I'll close this and if you have any futher thoughts we can reopen this

**Comment by alexreardon** [comment]
Related: 

- https://github.com/atlassian/react-beautiful-dnd/issues/930
