### ISSUE TITLE
Add property for pointing to ScrollContainer

### ISSUE THREAD

**Issue by Chariyski** [atlassian/react-beautiful-dnd#519]
Hi,
In my case the scroll container is few levels upper that the dragContext. 

It would be perfect if there is a way to use the auto scroll option.

Best regards,
Chariyski

**Comment by alexreardon** [comment]
That should be fine. As long as there is only one scroll container

**Comment by Chariyski** [comment]
I've found the problem.
My scroll container has `overflow-x: hidden;  overflow-y: overlay;`.
In chrome the auto scroll is not working until removing the `overflow-x: hidden;` , but in Firefox it is working perfectly with both of the css properties.

Any ideas ?

**Comment by alexreardon** [comment]
`overflow-y: overlay` 😕 

That is deprecated and might be causing your issues

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

Can you create a standalone example for me to play with?

**Comment by Chariyski** [comment]
Removing the overflow-y: overlay fixes the issue.
