### ISSUE TITLE
Getting the id of the items above and below where the drop occurred

### ISSUE THREAD

**Issue by joetidee** [atlassian/react-beautiful-dnd#520]
Is there a way to get the id of the item above and the id of the item below where the Draggable was dropped in the list? For example:

List
----------------
1
(Draggable dropped here)
2

If my Draggable is dropped in between items 1 and 2, can I get the ids of these items? Ideally, `result` that is passed to `onDragEnd` could contain this information.

Reason behind the question: When storing a sortable list in the database it is common to use a floating point to store the item order. This means that only the order value of the item that was dropped needs to be updated in the database. In order to calculate this value, the floating point order value of the items before and after needs to be known.

Example:
If you to position "red" after "blue", but before "yellow", then you just need to calculate:
`red.position = ((yellow.position - blue.position) / 2) + blue.position`

**Comment by alexreardon** [comment]
We return the id of the thing that was dragging, and its starting position and finishing position. As long as you have a local representation of your state on your client you should be able to look up a relative target from these values. You can then use these relative values to pass through to your database.

Feel free to continue this discussion
