### ISSUE TITLE
Cant auto scroll horizontally when droppables are inside a scroll container

### ISSUE THREAD

**Issue by aditigoel23** [atlassian/react-beautiful-dnd#521]
## Bug or feature request?
Not sure. I couldn't find an example in storybook. 

Sample  - https://codesandbox.io/s/zn96v9q77p

### Expected behavior
When an item is picked from 1st lane and dragged over to the second the container should auto scroll to the right.

### Actual behavior
Cant auto scroll on drag.

### Steps to reproduce
https://codesandbox.io/s/zn96v9q77p
I put a comment in the VerticalScrollContainer styled element - "comment out the below styles to see the left to right scroll work". Removing out the styles after that comment allows for horizontal scroll correctly. Those styles are essentially converting lanes to vertical scroll container.

### Browser version
Chrome 66.

### Demo
https://codesandbox.io/s/zn96v9q77p

**Comment by alexreardon** [comment]
We currently do not support nested scroll containers. We are hoping to add support for this soon #131

**Comment by zhangxuanou** [comment]
Why close this question
