### ISSUE TITLE
Trim some fat! 🥗

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#525]
There are some simple things we can do as a part of our build to *hopefully* drop some significant KB weight. 

- [babel-plugin-dev-expression](https://github.com/4Catalyzer/babel-plugin-dev-expression): remove all of our `invariant` message from production builds. Related: move all console.error expressions and move to invariant for consistent error handling (doing as a part of #493)
- [prepack](https://github.com/facebook/prepack) try to reduce some functions into their static results
- investigate our uglify options and see if there are any other approaches we can take advantage of

**Comment by TrySound** [comment]
I could take a look after major state refactor merge

**Comment by TrySound** [comment]
Do we have any components which can be unused in some cases?

**Comment by alexreardon** [comment]
Hey @TrySound, I almost have a stable branch that this work can start on. Are you keen to pick it up?

**Comment by alexreardon** [comment]
No pressure though, I am okay to do it too. I just wanted to give you the opportunity if you would like too!

**Comment by TrySound** [comment]
I'll take a look

**Comment by alexreardon** [comment]
okay sure, the branch is the `major-state-refactor`

**Comment by alexreardon** [comment]
it is green now, and should stay mostly intact

**Comment by alexreardon** [comment]
it also has a lot of bumped dependencies

**Comment by alexreardon** [comment]
Actually, I have created a new branch 'dev' which now has the latest. Can you please start that?

**Comment by alexreardon** [comment]
@TrySound I have bumped the rollup dependencies and it looks like the uglify plugin and your size plugin are no longer working. Feel free to roll them back to a stable version.

**Comment by alexreardon** [comment]
Shipped in version 9
