### ISSUE TITLE
onDragUpdate destination is null when isDropDisabled true

### ISSUE THREAD

**Issue by Reaverart** [atlassian/react-beautiful-dnd#530]
## Bug or feature request?
Bug

Lets say I need to disable drop to 0 position, I'm using onDragUpdate to check current `destination` index and toggling `isDropDisabled` with it.  Or maybe there is another way of doing it?

### Expected behavior
onDragUpdate should be fired with correct destination object according to docs `This can be null if the user is currently not dragging over any Droppable` but its over droppable

### Actual behavior
onDragUpdate fires `null` as destination and as result I cant check should I toggle dropping to enabled back or not

### Steps to reproduce
1) Open sandbox https://codesandbox.io/s/0q270wpm9l  **and sandbox console**
3) Take any item except first and move it to top position and then move on to last position without mouse release.

### Demo
https://codesandbox.io/s/0q270wpm9l

**Comment by alexreardon** [comment]
Once a list has been disabled we exclude the entire list from calculations. 

You might be able to add some visual affordance to indicate that movement into a particular position is not allowed - such as changing the background colour of your list to red

**Comment by alexreardon** [comment]
It is expected that when dragging over a disabled droppable that there is no destination

**Comment by Reaverart** [comment]
I see, thank you, this way wont prevent from dropping, we will take different UX approach probably. Wonder can it be a feature request if anybody else interested in this functionality?

**Comment by dimitarnestorov** [comment]
Well unless you need to disable some item in the middle you can just not render Draggable in those spots?
Example: https://codesandbox.io/s/vy5yv6nyl5

**Comment by alexreardon** [comment]
Feel free to raise a feature request :)
