### ISSUE TITLE
For large size list item can't be placed at desired index

### ISSUE THREAD

**Issue by AbhishekSinghBais** [atlassian/react-beautiful-dnd#534]
In case of horizontal list try these steps:

1) Increase grid size up to 50
2) Pick an item from 0th index
3) Try to drag it till 25th index
4) Now try to drop it

Expected : Item is dropped at 25th index
Actual : Item is not dropped

Demo : https://codesandbox.io/s/2olq99k3qy

**Comment by dimitarnestorov** [comment]
That's because this library isn't meant to have it's Droppable innerRef to be scrollable (none of the examples have a scrollable Droppable innerRef)

Here's your issue fixed by creating a scrollable container of the Droppable innerRef: https://codesandbox.io/s/4wrv2v0lo9

**Comment by alexreardon** [comment]
This issue was fixed in [7.1.1](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v7.1.1)

If you update the dependency in your example - everything should work as expected

https://github.com/atlassian/react-beautiful-dnd/releases/tag/v7.1.1

https://codesandbox.io/s/ovr6nwyq5z
