### ISSUE TITLE
Jank when trying to place an item after the last one

### ISSUE THREAD

**Issue by dimitarnestorov** [atlassian/react-beautiful-dnd#536]
## Bug or feature request?
Bug

### Expected behavior
No jank, easily putting an item after the last one

### Actual behavior
![kapture 2018-06-01 at 3 35 15](https://user-images.githubusercontent.com/8790386/40815123-e6963c8c-654c-11e8-8fbc-a15dbc4a4e24.gif)

### Steps to reproduce
1. Take any item but the last one.
2. Try to put it after the last one

### Browser version
Chrome 67

### Demo
https://codesandbox.io/s/ovr6nwyq5z

**Comment by humphreybc** [comment]
Is this related to https://github.com/atlassian/react-beautiful-dnd/issues/338?

**Comment by alexreardon** [comment]
I got it working by moving from display: flex, to display: inline-flex

Horizontal expansions in the browser is brutal as it works quite differently to horizontal. I am planning on putting together a guide at some point

**Comment by dimitarnestorov** [comment]
Not quite sure that is the fix, by making it `inline-flex` you made the body the scroll container.
Also adding a div(scroll container) breaks auto scrolling:
![kapture 2018-06-06 at 15 17 18](https://user-images.githubusercontent.com/8790386/41037726-c7adab30-699c-11e8-9b6b-70929e6ea4c7.gif)
Demo: https://codesandbox.io/s/x7pqvmw5z

**Comment by dimitarnestorov** [comment]
Alright: Switching the `display` of the items to `inline-block` and the `white-space` of the container to `nowrap` doesn't cause this effect.

**Comment by alexreardon** [comment]
@dimitarnestorov could you some information to the docs?

**Comment by dimitarnestorov** [comment]
@alexreardon I'm not sure I understand you, I'm presuming you mistyped

**Comment by alexreardon** [comment]
Updated :)

**Comment by dimitarnestorov** [comment]
In `docs/guides`?

**Comment by alexreardon** [comment]
sure

**Comment by TazmanianD** [comment]
A note I'd like to add that tripped me up. I found that when I switched to using `inline-block` that when I started a drag, the non-dragging items would shift position. I didn't entirely figure out why but the cause was because the browser was aligning the items differently at different baselines. My fix was to set `vertical-align: top` on the draggable item to make that stop.

**Comment by TazmanianD** [comment]
BTW, this bug is still visible on the horizontal items example referenced from the main page: https://codesandbox.io/s/mmrp44okvj.
