### ISSUE TITLE
Drop permission with a function rather than a string (type)

### ISSUE THREAD

**Issue by Frozenlock** [atlassian/react-beautiful-dnd#537]
### Drop Permission by Function

It would be nice if the drop permission test could be made by a function given by the user.

This would allow much more advanced behaviors.

As a simple example, let's imagine 3 different bins:

- Meat;
- Vegetables;
- My shopping cart.

Meat should accept a single type "meat".
Vegetables should accept a single type "vegeable".

However, we immediately see the limit of using a type string when building the shopping cart : This bin should be able to accept "meat", "vegetable" and potentially many more types. There might also be other limiting factors, such as a maximum number of items or erroneous combinations.

**Comment by alexreardon** [comment]
You could achieve this today using isDropDisabled

**Comment by Frozenlock** [comment]
My apologies, I stopped reading as soon as I saw this

> (...) Currently the type of the Draggables within a Droppable must be the same. This restriction might be loosened in the future if there is a valid use case.

As is turns out, the `isDropDisabled` was described just after.
