### ISSUE TITLE
More flexibility for Droppable props: type

### ISSUE THREAD

**Issue by oahehc** [atlassian/react-beautiful-dnd#540]
## Bug or feature request?
feature request

About the type props for Droppable, current document say

> Currently the type of the Draggables within a Droppable must be the same. This restriction might be loosened in the future if there is a valid use case.

If I have 3 draggable list,
```
<TodoA> ... </TodoA>
<TodoB> ... </TodoB>
<WorkInProcess> ... </WorkInProcess>
```
And item in TodoA/B should be able to drag to WorkInProcess and drag back too,
but should not be drag between TodoA/B,
I thinks if type props have more flexibility and able to accept an array or 'ALL' might be helpful for this scenario?
Currently the only solution I thought is to change isDropDisabled setting dynamically.
But it's not easy to maintain if I have multiple list with more complex drag/drop logic.

So I thinks more flexibility for type props will be helpful,
Or is there any suggestion for handle this kind of scenario?

thanks for help~

**Comment by alexreardon** [comment]
Try using `Droppable` > `isDropDisabled`. You can use this to implement any logic you like

**Comment by oahehc** [comment]
Thanks @alexreardon 
A little tricky to allow drag back from WorkInProcess to original ToDoList, but it's work by using isDropDisabled.

thanks for the help and quick response.

**Comment by alexreardon** [comment]
👌
