### ISSUE TITLE
Draggable jumps off screen when scrolled down on a modal

### ISSUE THREAD

**Issue by SNicholson99** [atlassian/react-beautiful-dnd#542]
## Bug or feature request?
Bug

### Expected behavior
Draggable item sticks to cursor when dragging around screen, when in a modal

### Actual behavior
Draggable item jumps above cursor, sometimes off page when in a modal

### Steps to reproduce
Create a dnd within a modal, then attempt to drag the draggable item  

### Browser version
Chrome Version 66.0.3359.181

### Demo
![react-beautiful-dnd-bug](https://user-images.githubusercontent.com/29401432/41024642-aedab9ac-6967-11e8-9599-b799ba09beae.gif)

**Comment by alexreardon** [comment]
Hi @SNicholson99,

Try [using a portal](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md).

Please feel free to reopen this issue if it does not work for you. If you do need to reopen this issue if you could please add a standalone example that would be great

**Comment by tanmynguyen** [comment]
@alexreardon . Thanks you. I tried and successfully.

**Comment by craigdanj** [comment]
@alexreardon Is this portal approach possible with v6.0.2? Im using an older version cause my project doesn't use React16.

**Comment by dmikester1** [comment]
> 
> 
> Hi @snicholson99,
> 
> Try [using a portal](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md).
> 
> Please feel free to reopen this issue if it does not work for you. If you do need to reopen this issue if you could please add a standalone example that would be great

That link no longer works.  I'm also trying to figure out drag and drop in a modal and the item goes off the modal when I try and drag no matter how I play around with the position(absolute/relative) of the containers.

**Comment by patrickml** [comment]
I am also having this issue. Are there any other ways to resolve?

**Comment by bemlw** [comment]
Same issue here. The package doesn't appear to work inside of a fixed position modal

**Comment by sidharth-ping** [comment]
This issue arises due to the way the translate is calculated. It should be recalculated based on current window scroll not the initial scroll value
