### ISSUE TITLE
Items to hold it's place until dropped over?

### ISSUE THREAD

**Issue by sbutkaliuk** [atlassian/react-beautiful-dnd#546]
## Question
Is it possible to have next behavior with react-beautiful-dnd:

- have 2 lists A and B with elements
- when item from list B is dragged over list A items in A are not moving or rearranging. (each item holds it's place)
- when item (b) from list B is dropped over item (a) from list A - (a) is replaced with (b) AND (a) moves to list B

**Comment by alexreardon** [comment]
I am struggling to visualise this in my head. I would suggest that you have a read of this section and see how you go:

https://github.com/atlassian/react-beautiful-dnd#conditionally-dropping

Let me know how you go
