### ISSUE TITLE
Items at the bottom of a long Droppable can't be placed

### ISSUE THREAD

**Issue by justintemps** [atlassian/react-beautiful-dnd#547]
## Bug or feature request?
Bug

### Expected behavior

Items at the bottom of a long, vertical droppable list should be placeable just like items at the top. This seems like a very similar issue to #534, which should have been fixed with 7.1.1. However, I'm using 7.1.3 and the issues persists.

### Actual behavior

Draggables that appear below the vertical height of the screen cannot be dropped. Announcement says "you are currently dragging over a non-droppable area" even when inside the droppable container. 

### Steps to reproduce
I based my code on this [example](https://codesandbox.io/s/ovr6nwyq5z). Here's the relative section in render:

```
      <DragDropContext onDragEnd={this.onDragEnd}>
        <Droppable droppableId="droppable">
          {(provided, snapshot) => (
            <div
              className="droppable"
              ref={provided.innerRef}
              style={getListStyle(snapshot.isDraggingOver)}
              {...provided.droppableProps}
            >
              {this.state.items.map((item, index) => (
                <Draggable key={item._id} draggableId={item.index} index={index}>
                  {(prov, snap) => (
                    <div
                      ref={prov.innerRef}
                      {...prov.draggableProps}
                      {...prov.dragHandleProps}
                      style={getItemStyle(
                        snap.isDragging,
                        prov.draggableProps.style
                      )}
                    >
                      <Entry
                        content={item}
                        edit={`${path}/edit/${collection}/${item._id}`}
                        showModal={showModal}
                      />
                    </div>
                  )}
                </Draggable>
              ))}
              {provided.placeholder}
            </div>
          )}
        </Droppable>
      </DragDropContext>
```

### Browser version
Chrome 66.0.3359.181 

### Demo
![react-dnd](https://user-images.githubusercontent.com/12401179/41360359-e364acbc-6f2c-11e8-9141-f96107de1778.gif)

**Comment by justintemps** [comment]
Apologies, it looks like all I had to fix this was add `ignoreContainerClipping` to `<Droppable />`. Works as expected now.

**Comment by alexreardon** [comment]
👍
