### ISSUE TITLE
Does this package works with graphQL relay?

### ISSUE THREAD

**Issue by xap5xap** [atlassian/react-beautiful-dnd#548]
## Bug or feature request?
Bug

### Expected behavior
To work with GraphQL

### Actual behavior
Getting the following when adding the dependencies for GraphQL. The same error shows either when working with apollo-client or react relay:

Error in observer.next 
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.

**Comment by lukebatchelor** [comment]
Can you please create a code sandbox that shows the issue as described in the issue template? 

There's not enough information here to help. Thanks

**Comment by TrySound** [comment]
@xap5xap Which version of react do you use?

**Comment by xap5xap** [comment]
@TrySound I am using react version 15.4.2

**Comment by TrySound** [comment]
@xap5xap Here's the thing
https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L107-L109

**Comment by alexreardon** [comment]
This library has no opinions about how you manage your state. There are other projects that I know of that are already using GraphQL with react-beautiful-dnd. 

You are using the wrong React dependency version which is most likely the cause of your issue. Things might not also be wired up correctly but it is hard to tell without an example to look at.

Please create a stand alone example on codesandbox if you would like us to look into this further.

**Comment by TrySound** [comment]
@suyashgithub react-beautiful-dnd requires react v16.3.1 or greater.

**Comment by xap5xap** [comment]
@suyashgithub I was able to use react-beautiful-dnd with react 15.4.2 by using the version 6.0.2 of this package. Look at the examples of this tag because some of the latests examples might not work with version 6

**Comment by TrySound** [comment]
Why not upgrade? It's painless.

**Comment by xap5xap** [comment]
@TrySound In my case, I have a very big app with hundreds of "old" react classes. It would take a lot of time and money to upgrade all those classes.

**Comment by TrySound** [comment]
@xap5xap Facebook has a lot of "old" react classes. Everything still works fine.
https://www.npmjs.com/package/create-react-class

**Comment by Ankit895** [comment]
uncaught at loadRules Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol

react version: 16.6
