### ISSUE TITLE
Draggable Placeholder in Table

### ISSUE THREAD

**Issue by sanjamkr** [atlassian/react-beautiful-dnd#554]
## Bug or feature request?
Bug

While dragging in a table, the row at the drag source overlaps with the row above/below it. And there's no placeholder being created. But this issue is not observed while dropping the element.

I've used React-Table library for the table.

### What version of `React` are you using?

react": "^15.3.0

### What version of `react-beautiful-dnd` are you running?

"react-beautiful-dnd": "^6.0.2"

### What browser are you using?

Chrome

### Demo

![reactdnd](https://user-images.githubusercontent.com/22677557/41539615-dd487540-732b-11e8-8fff-abb7883b477e.gif)

**Comment by alexreardon** [comment]
1. you are using an unsupported version of react
2. you are using an old version of `react-beautiful-dnd` (we are currently on 7.1+)
3. we have [a table guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md) for assisting people in building reorderable tables

Try addressing those points. If you are still having issues feel free to let us know
