### ISSUE TITLE
firing action in onDragStart

### ISSUE THREAD

**Issue by 12tp12** [atlassian/react-beautiful-dnd#557]
## Bug or feature request?
Bug

### Expected behavior
Hey, 
I want to fire an action in redux that indicates if i'm on drag right now or not, so i'll update some components in my code, later.  I thought of calling it in onDragStart function.
### Actual behavior
when firing an action from onDragStart I get
![screen shot 2018-06-20 at 14 58 16](https://user-images.githubusercontent.com/12761398/41657082-cfeb4b1e-749a-11e8-8d84-f9c0c9b4280a.png)

### Steps to reproduce
none
### What version of `React` are you using?
"react": "^16.3.2",

### What version of `react-beautiful-dnd` are you running?
"react-beautiful-dnd": "7.1.3",

### What browser are you using?
chrome

### Demo

actually when i'm firing an action in onDragEnd its fired not like in onDragStart. 

Thanks!

**Comment by alexreardon** [comment]
Can you please create an example for us to play with? The error indicates that you are adding or removing Draggable or droppable components during a drag, which is currently not supported

**Comment by alexreardon** [comment]
I will close this due to inactivity. Please reopen if you have more information
