### ISSUE TITLE
Bad positioning when dragging while zoomed in (mobile)

### ISSUE THREAD

**Issue by shawninder** [atlassian/react-beautiful-dnd#562]
## Bug or feature request?
Bug

### Expected behavior
Whether zoomed in or not, the items I drag should follow along under my finger

### Actual behavior
When zoomed in, items I drag follow the movement of my finger but don't stay directly under it

### Steps to reproduce
- Make a simple page with lots of draggables
- Open page on mobile (touch-enabled)
- Zoom in (with a reverse-pinch gesture) and scroll down a bit
- Drag a draggable
- Notice the dragged item is no longer well position with respect to the dragging finger

### What version of `React` are you using?
16.3.1

### What version of `react-beautiful-dnd` are you running?
7.1.3

### What browser are you using?
Same behaviour in all browsers I try (Safari, Chrome, Firefox, all on iPhone 5)

### Demo
You can actually reproduce this using the demo boilerplate you provide here (in the new issue comments): https://codesandbox.io/s/k260nyxq9v
- Visit https://k260nyxq9v.codesandbox.io with a mobile phone
- Zoom in (with a reverse-pinch gesture) and scroll down a bit
- Drag a draggable
- Notice the dragged item is no longer well position with respect to the dragging finger

**Comment by alexreardon** [comment]
We are a bit at the mercy of the positions that the device publishes. It sounds like zooming messes up the internal coordinate system.

It looks like zoom in the browser is a bit of a mess:

https://stackoverflow.com/a/5078596

We would need to:
- know what the zoom level is (difficult)
- know what the impact of the zoom level is on the coordinate system (i suspect this will be different between browsers)
- account for the difference

I am happy for somebody to explore this, but for now I would recommend one of these:

- not allowing zooming on interfaces that you want to support drag and drop on
- setting isDragDisabled to false if not on the default zoom

Thoughts?
