### ISSUE TITLE
Not all items are reacting on dragging (depend on the screen size).

### ISSUE THREAD

**Issue by vadimuz** [atlassian/react-beautiful-dnd#569]
Hello. 
You built an amazing library! I very like it!

Today I noticed an issue, that probably I'm not noticed before.
I use React, and I created a long list, where each Item is draggable and related to the droppable container, and I change the order of the list. 
Right now I see, that not all items in the list reacting on the draggable event. Only those items that are placed on the first screen of the browser, others, under the scrolling no reaction.

I have decreased the height of browser size, and I see reaction only for visible elements. I purpose the problem related to scrolling. But scrolling works fine. It is a pretty weird bug.

Could you help me figure out, what is wrong, and how probably I can fix it?

Thanks!

**Comment by vadimuz** [comment]
Omg, the problem with:

`body {
  overflow-y: scroll;
}`

Without this property, all works fine.

**Comment by Obiwarn** [comment]
Omg. this took me hours.

Thanks.
