### ISSUE TITLE
<DragDropContext /> - onDragUpdate - doesn't trigger

### ISSUE THREAD

**Issue by Hazantip** [atlassian/react-beautiful-dnd#572]
There is an issue  with **onDragUpdate** method of **DragDropContext**.

When dragging from **index 1** to **index 0**, onDragUpdate doesn't trigger at all.

see [video](https://monosnap.com/file/5sqeOIxFgQcl6Zi00lqJDcTHqJj3VG)

**Comment by alexreardon** [comment]
Can you please create an independent example that shows off this behaviour? Without that we cannot figure out what is going on. We have a lot of tests for this behaviour so I suspect your issue is a setup on

**Comment by Hazantip** [comment]
@alexreardon While trying to prepare for you independent example i've found an issue in my code.

my onDragUpdate has some logic, and when draggable goes outside of droppable, this method triggers with destination equals `null` and for prevent execution of my script in this case i have used 
```
onDragUpdate = ({ draggableId, source, destination }) => {
		if (!destination || !destination.index) {
			return;
		}
```
but destination.index with "0" is also false, so thats my dumb fail. `!destination` is enough
