### ISSUE TITLE
plan of translate chinese  🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [atlassian/react-beautiful-dnd#573]
## readme translate request

https://github.com/chinanf-boy/react-beautiful-dnd-zh

**Comment by chinanf-boy** [comment]
And I think the https://github.com/atlassian/react-beautiful-dnd#translations links is so far away to readers

**Comment by alexreardon** [comment]
Agreed @chinanf-boy, it should be near the top. How would you like us to proceed on this one?

**Comment by chinanf-boy** [comment]
Seem like the `Docs` start at https://github.com/atlassian/react-beautiful-dnd#examples-

Just **put a `h2`|`h*` with the translate list**

> like https://github.com/ronami/minipack#read-this-in-other-languages

## That to go

---

### 1. change UI, more simple

---

```

## Read this in other languages

- [![kr](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/South-Korea.png) **한글/Korean**](https://github.com/LeeHyungGeun/react-beautiful-dnd-kr)

- [🇨🇳 **中文/Chinese**](https://github.com/chinanf-boy/react-beautiful-dnd-zh)

```

## Read this in other languages

- [![kr](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/South-Korea.png) **한글/Korean**](https://github.com/LeeHyungGeun/react-beautiful-dnd-kr)

- [🇨🇳 **中文/Chinese**](https://github.com/chinanf-boy/react-beautiful-dnd-zh)

---

> `the chinese country flag link`, I no find , may you please 😊

### 1.5 more friendly country name by own language

> if you come from the country that use EN , you will like the english

> just like I am Chinese, i would love the 中文 style docs

> if need the en name `own language/english`; **한글/Korean** **中文/Chinese**

---

### 2. Tips is no necessary 

i don't think other language readers really care about 
`These translations are maintained by the community and are not reviewed or maintained by the maintainers of this library. Please raise issues on the respective translations if you would like to have them updated.`

because YOUR repo is `main docs`

**the Warnning ⚠️ More should appear the translate's repo**

### Ending

Yeah, just like `minipack`

**Comment by alexreardon** [comment]
Sounds good. Want to make a PR?

**Comment by chinanf-boy** [comment]
#579 

you check this, anything Up fix 🆕

**Comment by chinanf-boy** [comment]
Good
