### ISSUE TITLE
How do i become a contributer to this project ?

### ISSUE THREAD

**Issue by gautamz07** [atlassian/react-beautiful-dnd#574]
Hi, i am not here to report a bug , but i have to use this package(react-beautiful-dnd) for one of my projects, i started using react about a year ago.  I'd really like to go though this project and understand it at a deeper level , i have a few questions:

- is src the folder is which all the functional parts for this project are written ? I.E. where will i find most of the meat and patatos of this project ?  are there any other important folders that i need to know about ? 

I would appreciate anyones effort in guiding me in understanding better.

Thanks alot and cheers.

**Comment by dimitarnestorov** [comment]
>is src the folder is which all the functional parts for this project are written ?

Yes.

Also in stories you can see examples on how to use the library.

**Comment by alexreardon** [comment]
Yep, the `src` directory contains the source for the project. You're welcome to have a poke around!

**Comment by gautamz07** [comment]
Thanks aloot ! :) much appreciated. one more question , any please like slack etc , that you guys gather to discuss the dynamics of this project ?

**Comment by alexreardon** [comment]
Not at this stage. Trying to minimise noise. Do you think one would be
worthwhile?
