### ISSUE TITLE
Problem to drag elements between lists with different width

### ISSUE THREAD

**Issue by yoksel** [atlassian/react-beautiful-dnd#576]
## Bug?

I try to drag a big element to narrow list. Narrow list begins to "listen" element only when big element touch it with its central part or with tail, not with head.

![screen shot 2018-06-25 at 14 14 36](https://user-images.githubusercontent.com/2571308/41847290-2baac228-7882-11e8-9cd8-b71dde1abd19.png)

### Expected behavior

It would be nice if narrow list begins to "listen" element when big element touch it with its head.

### Steps to reproduce

Demo: https://codesandbox.io/s/qkp26n713j
Try to drag element from right side to the left

### What version of `React` are you using?

16.3.1

### What version of `react-beautiful-dnd` are you running?

7.0.0

### What browser are you using?

Latest Chrome

### Demo

https://codesandbox.io/s/qkp26n713j
Try to drag element from right side to the left

**Comment by alexreardon** [comment]
At this stage the impact of a Draggable is based on its centre of gravity.
This allows for the most natural and consistent experience.

**Comment by yoksel** [comment]
Thank you for the answer
