### ISSUE TITLE
If I don't enable ignoreContainerClipping then items won't drag into position

### ISSUE THREAD

**Issue by i2chris** [atlassian/react-beautiful-dnd#577]
Bug??

### What version of `React` are you using?

16.4.0

### What version of `react-beautiful-dnd` are you running?

7.1.3

### What browser are you using?

Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

I spent a long time trying to figure out why I couldn't move items in lists that were near bottom of the browser window.  The item I was dragging would move but the other items in the list woudn't and I couldn't change any of the positions.

Enabling ignoreContainerClipping fixed it and I'm not really sure why.  My lists are only small with about 10 items in and they do not go off the screen.

**Comment by alexreardon** [comment]
> `ignoreContainerClipping`: When a Droppable is inside a scrollable container its area is constrained so that you can only drop on the part of the Droppable that you can see. Setting this prop opts out of this behavior, allowing you to drop anywhere on a Droppable even if it's visually hidden by a scrollable parent. The default behavior is suitable for most cases so odds are you'll never need to use this prop, but it can be useful if you've got very long Draggables inside a short scroll container. Keep in mind that it might cause some unexpected behavior if you have multiple Droppables inside scroll containers on the same page.

Are you using a scroll container with long items inside?

Can you provide some more information about your setup? Perhaps an independent example?

**Comment by alexreardon** [comment]
Feel free to reopen this if there is any confusion
