### ISSUE TITLE
Not able to drag and drop on mobile using React Portal

### ISSUE THREAD

**Issue by Chariyski** [atlassian/react-beautiful-dnd#582]
## Bug or feature request?
Bug

### Expected behavior
To be able to drag and drop items on mobile.

### Actual behavior
The items are marked as draggable, but can't be dragged.

### Steps to reproduce
Go to  https://codesandbox.io/s/3465m7xmw6 and open mobile emulation.

### What version of `React` are you using?
16.3

### What version of `react-beautiful-dnd` are you running?
7.1.3

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
We'll track as a part of #567

**Comment by alexreardon** [comment]
React issue created: https://github.com/facebook/react/issues/13113

**Comment by alexreardon** [comment]
I'll update the docs to let people know about this issue

**Comment by alexreardon** [comment]
This is surpising as I thought I tested using portals on mobile... very confusing.

Oh well, I am able to reproduce it outside of this library so for now we cannot really do too much :(

**Comment by alexreardon** [comment]
I have created a warning in the docs: https://github.com/atlassian/react-beautiful-dnd/pull/583

**Comment by alexreardon** [comment]
This is also caused by the removing of the existing node and re-creating of one. It looks like there could be a workaround which I will explore: https://github.com/facebook/react/issues/13113#issuecomment-410311889

**Comment by Chariyski** [comment]
Hello,
any news about the problem ?

**Comment by alexreardon** [comment]
i have not digged into this one yet

**Comment by paceto256** [comment]
Any chance to use this solution https://github.com/facebook/react/issues/13113#issuecomment-438901454 ?

**Comment by alexreardon** [comment]
This *might* be fixed as a part of our event changes for #1293

**Comment by alexreardon** [comment]
I am looking into this as a part of #1293

**Comment by alexreardon** [comment]
I can confirm I have found a workaround for this as a part of #1293. The new pattern also works with dragging clones which is needed for virtual lists

/cc @TrySound

**Comment by TrySound** [comment]
Awesome

**Comment by alexreardon** [comment]
#1317

**Comment by alexreardon** [comment]
Fixed in `12.0.0-alpha.7`
