### ISSUE TITLE
Add test to ensure bundling occurs correctly

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#588]
It would be good to have a test that runs our bundling process to ensure that no errors occur. This test should only run on travis as it will be fairly expensive to run locally.

**Comment by TrySound** [comment]
I do this for powerplug.
https://github.com/renatorib/react-powerplug/blob/master/package.json#L23-L25

**Comment by alexreardon** [comment]
We are now running bundle size snapshot checks in our build. This should fail if the bundle itself fails to build
