### ISSUE TITLE
onDragEnd hook will not execute on childs components

### ISSUE THREAD

**Issue by Juliopo** [atlassian/react-beautiful-dnd#598]
## Bug or feature request?
Feature request/Bug, (don't really know)

### Expected behavior
On this example you presented on a previous issue https://codesandbox.io/s/vmm0nplz5y you showed to us how to make a draggable with several nested lists, the problem is that the function `onDragEnd` passed on the DragDropContext will only execute in the root Component, but if I overwrite this hook on the child components it will not be  executed. (in the example you can see that `ServiceCommandUnit.js` has a function onDragEnd that will never trigger)

So, how Can I make `onDragEnd` hook be triggered on child components?

### Actual behavior
`onDragEnd` function will be hooked only in the component that has the DragDropContext
### What version of `React` are you using?
15.3.0 - React.
15.0.0 - React Dom

### What version of `react-beautiful-dnd` are you running?
6.0.0 - react-beautiful-dnd

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/s/vmm0nplz5y

**Comment by alexreardon** [comment]
I am not sure what you mean 'So, how Can I make onDragEnd hook be triggered on child components?'

Also, please upgrade to the latest version `7.1.3` to ensure what you are seeing has not already been fixed

**Comment by alexreardon** [comment]
Currently `DragDropContext` cannot be nested. So for now there is only one onDragEnd callback for the app. We are looking at enhancing this #498

I'll close this as a duplicate as I think #498 covers this. Feel free to comment and we can reopen this if it does not
