### ISSUE TITLE
Add support for horizontal lists that grow to the left

### ISSUE THREAD

**Issue by dirivero** [atlassian/react-beautiful-dnd#599]
When dropping something into an horizontal list the translations pushing elements move them to the right to make room. 

If the list is horizontally aligned to the right (for instance through justify-content: flex-end), it would be nice to have a way to tell that so the translations to make room move items to the left so there's no overflow when dragging over or jumping when the drag ends.

Here is an example of such a list:

![list](https://user-images.githubusercontent.com/7670773/42125540-755774cc-7c4f-11e8-972d-60a1ed07efbe.gif)

**Comment by alexreardon** [comment]
Hey @dirivero. Interesting suggestion!

We are tracking that idea here: #270

Cheers
