### ISSUE TITLE
Can not expand a combo box that is inside a draggable element

### ISSUE THREAD

**Issue by dontfireme** [atlassian/react-beautiful-dnd#61]
## Bug or feature request?
Feature Request/Help wanted

Basically, as the title says. When there is a combo box inside a draggable element, it can not be expanded. Same goes for input elements - those can not be focused.

### Demo
[https://codesandbox.io/s/n4krm8x0y0](https://codesandbox.io/s/n4krm8x0y0)

Any workaround for this behaviour?

Thanks!

**Comment by alexreardon** [comment]
we add an `onMouseDown` event handler to the element which calls `preventDefault`. This is what prevents the select from working. However, you are welcome to patch the event handler to achieve what you are after. Have a look at the 'patching' section in the readme. I have fixed your example by patching the `onMouseDown` event:

https://codesandbox.io/s/yvn0llx1r1
