### ISSUE TITLE
Dragging items width gets screwed up when droppable containers are different widths.

### ISSUE THREAD

**Issue by Jdoyle112** [atlassian/react-beautiful-dnd#614]
I have two droppable containers that have different widths. The issue is that when I drag an item from the big list to the small one, the width of the draggable item is not recalculated when dragging into the smaller droppable container. It only recalculates after I drop it. This is not desired because it blows up the width of the smaller droppable container before I drop the item. 

I need the item to resize it's width according to the droppable containers width whenever it enters the area. How can this be accomplished?

**Comment by alexreardon** [comment]
This is a little tricky as we lock the dimensions during a drag. If we were to change them we can run into other problems such as overflow impacting the height of the element and so on. 

You can technically achieve this today.

You can patch the `Draggable > DraggableStyles > width` youself during a drag in response to its movement around. You could transition the width of the element based on the width of the column it is over. 

I will close this as i think this is too opinionated to bake into the library. 

However, there is a way you could achieve this for yourself today 👍

**Comment by kiraahmad** [comment]
any solution to this ?
