### ISSUE TITLE
Form fields as Draggable children can get focus after version 8.0.0

### ISSUE THREAD

**Issue by eduludi** [atlassian/react-beautiful-dnd#615]
### Expected behavior

Form fields/inputs to be included into `Draggable`s descendants.

Here is an working example using version`7.1.3`: https://codesandbox.io/s/y3q550084j

### Actual behavior

Form inputs can't get focus (see Demo).

### What version of `React` are you using?

16.3.1

### What version of `react-beautiful-dnd` are you running?

8.0.0

### What browser are you using?

Chrome and Safari, macOS

### Demo

Example using version `8.0.0`: https://codesandbox.io/s/n92y04ll2j

**Comment by alexreardon** [comment]
Looks bad! I'll take a look asap

**Comment by alexreardon** [comment]
Good news - I have a fix and i'll put up a PR soon

**Comment by alexreardon** [comment]
This was released in `8.0.1`

**Comment by eduludi** [comment]
Awesome! Thanks for the quick answer and great work! 🥇
