### ISSUE TITLE
Error when updating state inside onDragStart

### ISSUE THREAD

**Issue by ntelkedzhiev** [atlassian/react-beautiful-dnd#617]
I'm calling setState inside onDragStart and I'm getting the following error:

`Error: Invariant failed: Attempting to move in an unsupported phase PREPARING`

### What version of `React` are you using?

16.3.2

### What version of `react-beautiful-dnd` are you running?

8.0.1

### What browser are you using?

Chrome

**Comment by alexreardon** [comment]
Can you please provide a stand alone example on codesandbox? Hard to know
what is causing your issue otherwise

**Comment by ntelkedzhiev** [comment]
Thank you!

**Comment by ntelkedzhiev** [comment]
I now get an error when I try to update the state so that `isDropDisabled` is set to true. 

**Error: Trying to set droppable isEnabled to true but it is already true.**

**Comment by alexreardon** [comment]
Can you please post an independent example? I am keen to resolve this

**Comment by ntelkedzhiev** [comment]
https://codesandbox.io/s/vm528x79w3

**Comment by alexreardon** [comment]
I have a fix - PR incoming

**Comment by ntelkedzhiev** [comment]
Works fine now! Thanks once again.

**Comment by alexreardon** [comment]
You’re welcome! Thanks for the independent example. It made it easy to
action
