### ISSUE TITLE
question about triggering drag start

### ISSUE THREAD

**Issue by chrisjlee** [atlassian/react-beautiful-dnd#620]
## Bug or feature request?

This is actually a question. Is there a way to trigger a drag start through a function ? I'm trying to write an example unit test to test the start of the drag without having to use or simulate a click with enzyme.

**Comment by alexreardon** [comment]
There is no programatic way to do it at this time. However, a simple way that I use is to trigger a `keydown` on the `Draggable`:

```js
// Enzyme wrapper
wrapper.simulate('keydown', { keyCode: keyCodes.space });
```

We have an issue to add some testing docs which should cover this in more detail #623 👍
