### ISSUE TITLE
Comparison with RubaXa/Sortable

### ISSUE THREAD

**Issue by dandv** [atlassian/react-beautiful-dnd#621]
Thank you for a carefully thought-out package!

Just wondering how it compares with @RubaXa's Sortable ([demo](http://rubaxa.github.io/Sortable/)), which has been around [since 2013](https://github.com/RubaXa/Sortable/commit/6ace554483b9731b12b09f3c01c3859589c30c52), has 13k stars, and supports React; or, what the reasons were for creating a new sortable list package.

Some packages have a Prior Art section that I've found very useful when comparing alternatives.

**Comment by alexreardon** [comment]
Hi @dandv, I am not sure how valuable a full comparison of feature sets between Sortable, or other drag and drop libraries out there would be. Our feature set is drastically different to even six months ago.

I would point you to two sections of our documentation:

1. [Our philsolophy](https://github.com/atlassian/react-beautiful-dnd#driving-philosophy-physicality)
2. [Not for everyone](https://github.com/atlassian/react-beautiful-dnd#not-foreveryone)

My blog [Rethinking drag and drop](https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b) gives a good overview of the 'why' we created this library.

Driving ideas of this library (which may have some overlap with others)

- Trying to offer a more physical and relatable drag and drop experience
- Fanastic accessibility (keyboard dragging and first class screen reader support)
- State driven (unlocks really any input type)

I hope you found that explaination helpful!
