### ISSUE TITLE
When user in the bottom of scrollable list, scroll up is not working

### ISSUE THREAD

**Issue by SimchaShats** [atlassian/react-beautiful-dnd#628]
Bug: When user in the bottom of scrollable list, and drag bottom item to the top, scroll top is not working.

Expected behaviour: List should scroll up when user move draggable item to the top of the list

Actual behaviour: List is not scrollable

Steps to reproduce: Basic example from library with updates: https://codesandbox.io/s/3457zo2kn1

What version of `React` are you using: 16
What version of `react-beautiful-dnd` are you running: latest
What browser are you using: Chrome
Operating system: OSX (mac)

Demo ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19427778/42432879-72fc8d2c-8355-11e8-89c4-60060a63c9b6.gif)

**Comment by alexreardon** [comment]
Please provide the information requested in our [ISSUE_TEMPLATE](https://github.com/atlassian/react-beautiful-dnd/blob/master/ISSUE_TEMPLATE.md) or we cannot action this

**Comment by alexreardon** [comment]
I cannot seem to reproduce what you are seeing

https://codesandbox.io/s/o4yljr6999

**Comment by alexreardon** [comment]
Here is another example that exercises the same use case:

https://react-beautiful-dnd.netlify.com/?selectedKind=Super%20simple&selectedStory=vertical%20list%20with%20scroll&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by SimchaShats** [comment]
Ah ok thanks, but what wrong with my example? I took there basic example from the library page. I had same issue in my project...

**Comment by alexreardon** [comment]
I cannot reproduce it in FireFox or Chrome

**Comment by alexreardon** [comment]
Using the example you provided...

**Comment by SimchaShats** [comment]
Ah may be because I'm using mac, I attached `gif` from now.

**Comment by SimchaShats** [comment]
Ah found, it doesn't work if there is exististing horizontal scroll, if remove it - it works. Not sure if it's a bug or now...

**Comment by alexreardon** [comment]
Can you please provide some more details?

**Comment by SimchaShats** [comment]
Here the example: https://ufile.io/4qd3a

**Comment by alexreardon** [comment]
I am keen to solve the underlying issue though :)
