### ISSUE TITLE
Expose flowtypes

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#63]
There are some `flow` types in the system that would be worth exporting. At a minimum flow should know that `react-beautiful-dnd` contains three exports (`DragDropContext`, `Droppable` and `Draggable`). But it would be good to also expose the types that are documented in `README.md` so that people using `flow` can type their code correctly.

I am not sure what the best practice is for this.

My thought is to import all the types I want to export into `src/index.js` and then export them from there. However, I am not sure what to do from there - should we just copy an `index.js.flow` into the generated `/lib` folder - is that enough?

The path we choose should not expose every type in the system. There are some types such as `State` which are not public API and purely for internal use.

**Comment by alexreardon** [comment]
@thejameskyle can you advise how you would go about this one?

**Comment by thejameskyle** [comment]
https://github.com/AgentME/flow-copy-source

**Comment by alexreardon** [comment]
Yep, but how would I expose public types for consumers? Would it simply be a matter of exporting the public types from `index.js`.

Ideally I want consumers to be able to do this:

```js
import type {DraggableProvided} from 'react-beautiful-dnd';
```

I am hoping I do not need to write a `flow-typed` lib def

**Comment by thejameskyle** [comment]
Yeah, just `export type` it

**Comment by alexreardon** [comment]
👌
