### ISSUE TITLE
Draggable Component throw  error: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by jyjin** [atlassian/react-beautiful-dnd#634]
I tried example code which on the codesandbox, but always get the warning error by Droppable component. And then  I try to remove my logic code, until simple like follow code, but nothing change, still throw the warning. Please help ~
```
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';

...

render() {
        return (
            <DragDropContext onDragEnd={this.onDragEnd}>
                <Droppable droppableId="droppable">
                    {(provided, snapshot) => (
                        <div
                            ref={provided.innerRef}
                            style={getListStyle(snapshot.isDraggingOver)}
                        >
                            <Draggable key={1} draggableId={1} index={1}> //------------- here
                                {(provided, snapshot) => <div ref={provided.innerRef}>Drag me!</div>}
                            </Draggable>

                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
            </DragDropContext>
        );
    }

```

ERROR like this:

`
bundle.js:17556 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.
    in DragHandle (created by DoubleRenderBlocker)
    in DoubleRenderBlocker (created by Motion)
    in Motion (created by Moveable)
    in Moveable (created by Draggable)
    in DraggableDimensionPublisher (created by Draggable)
    in Draggable (created by Connect(Draggable))
    in Connect(Draggable) (created by Droppable)
    in div (created by Droppable)
    in DroppableDimensionPublisher (created by Droppable)
    in Droppable (created by Connect(Droppable))
`

**Comment by alexreardon** [comment]
Hi @jyjin, it looks like you have not setup your draggable correctly. If we had #363 this could have been avoided

```diff
<Draggable key={1} draggableId={1} index={1}>
 {(provided, snapshot) => (
  <div 
    ref={provided.innerRef}
+    {...provided.draggableProps}
+    {...provided.dragHandleProps}
  >
      Drag me!
  </div>
 )}
</Draggable>
```

**Comment by jyjin** [comment]
Thanks, I found my react version is 15.x , but 16.x is the currently package dependency, that is the reason

**Comment by alexreardon** [comment]
cheers!

**Comment by icodinglee** [comment]
hi， my react version is 15.x ,  which package  veison should I use ？ @alexreardon @jyjin

**Comment by shivangi231** [comment]
import React from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components';
import {Draggable} from 'react-beautiful-dnd'
import './Task.scss'


const Container = styled.div`
padding: 8px;
border: 1px solid #A9A9A9;
border-radius: 2px;
margin-bottom: 8px;
`;


export const Task = (props) => {
  console.log('IN tASK', props);
  return(
      <Draggable key={props.task.id} draggableId={props.task.id} index={props.index}>
        {provided => (
          <Container  innerRef={provided.innerRef}
        {...provided.draggableProps}
        {...provided.dragHandleProps}
        >
        {props.task.content}
        </Container>
        )
        }
      </Draggable>

  )
}
export default Task;



Showing error : -
invariant.js:42 Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.
    at invariant (invariant.js:42)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:72)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:364)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)

**Comment by teodoraciont** [comment]
Hi. I tried to install this component, I looked over all the issues about this error and still persist yet.

 I've attached a picture of the configuration I have in package.json.

 I'm trying to include this example: https://codesandbox.io/s/vmq83z5n55

<img width="331" alt="screen shot 2018-10-24 at 13 58 14" src="https://user-images.githubusercontent.com/17424789/47426108-f926c780-d794-11e8-970a-f68b3ba65829.png">

 Thank you

**Comment by radumiron** [comment]
@teodoraciont, I'm bumping into the same issue, code works on Codesandbox, doesn't work in my environment.

**Comment by alexreardon** [comment]
Check your react version

**Comment by radumiron** [comment]
> version

@alexreardon , thanks for your reply, at the same time it's not helping too much. Which React version are you using?

**Comment by alexreardon** [comment]
it is listed as a peer dependency. It is `16.3.1`

**Comment by claytron5000** [comment]
I'm getting a similar error:
```
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.
```
from packages.json:
```
"react": "^15.4.2",
"react-beautiful-dnd": "^9.0.2",
```

My `DraggableOption`:

```
import React from 'react';
import { Draggable } from 'react-beautiful-dnd';

export default class DraggableOption extends React.Component {
    render() {
        const { safeName, value } = this.props.filter;
        return (
            <Draggable>
                {(provided) => (
                    <option
                        value={value}
                        ref={provided.innerRef}
                        {...provided.draggableProps}
                        {...provided.dragHandleProps}
                    >{safeName}</option>
                )}
            </Draggable>
        )
    }
}
```

**Comment by claytron5000** [comment]
I read up on peer dependencies and now have some idea what's going on. I downgraded `react-beautiful-dnd` to version 6.0.2 and it no longer throws that error.

**Comment by mackermedia** [comment]
@claytron5000 : I'm seeing the same thing and downgrading to `^6.0.0` fixes it here too. I'm not in love with the functionality of `6.0.x` though, any ideas on how to get it to work with a newer version?
