### ISSUE TITLE
Unknown plugin `transform-runtime' error in a React-Native app

### ISSUE THREAD

**Issue by nixvalentine** [atlassian/react-beautiful-dnd#64]
## Bug
First of all, I'm super noob so maybe this error is obvious.
I tried to use this in an React-Native app I'm developing. But It shows this error.

`Unknown plugin `transform-runtime' `

then I tried to fix using

`npm install babel-plugin-transform-runtime`

then it turns to this

`TransformError: /Users/Adalbert/project/QuestLog - todolist/build/QUESTLOG/node_modules/react-beautiful-dnd/lib/index.js: [BABEL] /Users/Adalbert/project/QuestLog - todolist/build/QUESTLOG/node_modules/react-beautiful-dnd/lib/index.js: Unknown option: /Users/Adalbert/project/QuestLog - todolist/build/QUESTLOG/node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options. (While processing preset: "/Users/Adalbert/project/QuestLog - todolist/build/QUESTLOG/node_modules/react/index.js")

ABI19_0_0RCTFatal
ABI19_0_0RCTSetFatalHandler
ABI19_0_0RCTSetFatalHandler
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>`

I'm quite sure this error is an noob error but I couldn't find answer anywhere that can solve it.
So I hope someone here can help? Really appreciate your helping.

Also thanks for sharing this awesome package. Love to see more of it soon.

**Comment by alexreardon** [comment]
It looks like your having a babel issue. I won't look into it too much as we are currently not targeting React Native. Native devices already have their own drag and drop lists. We may take a look at supporting React Native in the future - but that would be a long time off.
