### ISSUE TITLE
"ReferenceError: SVGElement is not defined" when test Create React App

### ISSUE THREAD

**Issue by 1ike** [atlassian/react-beautiful-dnd#640]
## Bug or feature request?

Bug. When run test app created by Create React App with react-beautiful-dnd [Simple vertical list](https://codesandbox.io/s/k260nyxq9v).  Problem only with testing, in browser "Simple vertical list" work fine.

### Actual behavior
throw error when run test
```
console.error node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:3821
    ReferenceError: SVGElement is not defined
        at throwIfSVG (/somePrivatePath/my-app/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:4683:29)
```
`var isSVG = el instanceof SVGElement;` - fall at this expression.

### Steps to reproduce
- clone [sample repo](https://github.com/1ike/rbdnd-cra): `git clone https://github.com/1ike/rbdnd-cra
`
- `npm i`
- `npm test` 
- "Press `a` to run all tests".

 or

- create app: `npx create-react-app my-app`
- add dnd : `npm i react-beautiful-dnd`
- change App component from boilerplate to App from [Simple vertical list](https://codesandbox.io/s/k260nyxq9v)
- run test: `npm test`

### What version of `React` are you using?

16.4.1

### What version of `react-beautiful-dnd` are you running?

8.0.3

### Demo

Have a [sample repo](https://github.com/1ike/rbdnd-cra) with CRA boilerplate (via `npx create-react-app my-app`) and official sample react-beautiful-dnd for Simple vertical list.

**Comment by alexreardon** [comment]
Throwing for the wrong reasons 😊. What browser are you using?

**Comment by 1ike** [comment]
In browser it's work fine (in FF Dev and Chrome). That problem only for testing (node.js v8.11.3).

**Comment by alexreardon** [comment]
Ah. Perhaps the version of jsdom does not know about it. What testing
framework are you using and what version?

**Comment by 1ike** [comment]
I use [Create React App](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests) as generator for boilerplate. It uses jest within.

**Comment by alexreardon** [comment]
Thanks

**Comment by alexreardon** [comment]
I was able to verify this with the latest create react app. It looks like the jsdom version being used does not understand `SVGElement`. I will create a PR to this library to be more defensive in its usage of `SVGElement`

**Comment by 1ike** [comment]
Thank you very much.

**Comment by alexreardon** [comment]
The PR is currently blocked as there is a downstream travis issue which is causing all our PR's to be red :(
