### ISSUE TITLE
Create a dynamic drag and drop 

### ISSUE THREAD

**Issue by shariqmagic** [atlassian/react-beautiful-dnd#644]
Hi, I am trying to develop a multiple drag and drop list . Suppose a drag list contains 4 objects and these 4 draggable objects will drop in 4 different droppable objects div. The onDragend event does not give me enough data to much the drag and drop condtion. Like wise we do in jquery we can set multiple drag and drop (one to one, many to one , many to many).

Please if you do have any reference then please let me know.

**Comment by shariqmagic** [comment]
<DragDropContext  onDragEnd={this.onDragEnd}>
                {this.state.items.map((item, index) => (
                <Droppable droppableId={item.dropId}>
                    {(provided, snapshot) => (
                        <div className="drag-container"
                            ref={provided.innerRef}>
                                <Draggable
                                    data-checkid={item.id}
                                    key={item.id}
                                    draggableId={item.id}
                                    index={index}>
                                    {(provided, snapshot) => (
                                        <div
                                            className={item.class}
                                            ref={provided.innerRef}
                                            {...provided.draggableProps}
                                            {...provided.dragHandleProps}
                                            >
                                            {item.content}
                                        </div>
                                    )}
                                </Draggable>
                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
                    ))}
                <div className="droppable-container">
                {this.state.selected.map((item, index) => (
                <Droppable droppableId={item.dropId}>
                    {(provided, snapshot) => (
                        <div
                            ref={provided.innerRef}
                            >
                                <Draggable
                                    key={item.id}
                                    draggableId={item.id}
                                    index={index}>
                                    {(provided, snapshot) => (
                                        <div
                                            className={item.class}
                                            ref={provided.innerRef}
                                            {...provided.draggableProps}
                                            {...provided.dragHandleProps}>
                                            {item.content}
                                        </div>
                                    )}
                                </Draggable>
                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
                    ))}
                </div>
            </DragDropContext>

**Comment by shariqmagic** [comment]
[ <DragDropContext  onDragEnd={this.onDragEnd}>
                {this.state.items.map((item, index) => (
                <Droppable droppableId={item.dropId}>
                    {(provided, snapshot) => (
                        <div className="drag-container"
                            ref={provided.innerRef}>
                                <Draggable
                                    data-checkid={item.id}
                                    key={item.id}
                                    draggableId={item.id}
                                    index={index}>
                                    {(provided, snapshot) => (
                                        <div
                                            className={item.class}
                                            ref={provided.innerRef}
                                            {...provided.draggableProps}
                                            {...provided.dragHandleProps}
                                            >
                                            {item.content}
                                        </div>
                                    )}
                                </Draggable>
                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
                    ))}
                <div className="droppable-container">
                {this.state.selected.map((item, index) => (
                <Droppable droppableId={item.dropId}>
                    {(provided, snapshot) => (
                        <div
                            ref={provided.innerRef}
                            >
                                <Draggable
                                    key={item.id}
                                    draggableId={item.id}
                                    index={index}>
                                    {(provided, snapshot) => (
                                        <div
                                            className={item.class}
                                            ref={provided.innerRef}
                                            {...provided.draggableProps}
                                            {...provided.dragHandleProps}>
                                            {item.content}
                                        </div>
                                    )}
                                </Draggable>
                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
                    ))}
                </div>
            </DragDropContext>](url)](url)

**Comment by shariqmagic** [comment]
I have attatched my code please check to see how would i able to implement that.
[dnd.zip](https://github.com/atlassian/react-beautiful-dnd/files/2200407/dnd.zip)

**Comment by alexreardon** [comment]
See our guide: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

Let me know if that is not what you were after

**Comment by shariqmagic** [comment]
No i am not looking for this . I have a  list of draggable objects but their drop location are different. You have a single drop location with multiple items. I have to develop a single drop with single item.
