### ISSUE TITLE
flow: discrepancies between flow-typed/redux@4 and react-beautiful-dnd

### ISSUE THREAD

**Issue by chmanie** [atlassian/react-beautiful-dnd#650]
## Bug or feature request?

Feature request (tooling)

## Feature request

Currently you're just stubbing out the redux types: https://github.com/atlassian/react-beautiful-dnd/blob/master/flow-typed/npm/redux_vx.x.x.js

When using the "inofficial" redux types from `flow-typed` (here: https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/redux_v4.x.x/flow_v0.55.x- ) there seem to be a lot of conflicts. Being not super comfortable with the redux types I can't say where the issues originate from. I set up a repo to illustrate the issues: https://github.com/chmanie/redux-flow-beautiful-dnd (this build is probably helpful: https://travis-ci.org/chmanie/redux-flow-beautiful-dnd/builds/405318548).

When using redux and this library in a project I have to either not use the redux types or ignore type checking of this library (none of these options excite me a lot, really).

Have you considered aligning your project with the redux flow-types provided? I'd be happy to help in any way I can to move this forward.

**Comment by alexreardon** [comment]
Happy to have these improved. I would have expected there is no issues given that react-beautiful-dnd does not expose redux as api, but flow is probably only keeping one definition around. 

Upgrading to the version 4 redux types would be great. I think we needed to use the stubs as we where early adopters. A PR would be great

/cc @TrySound

**Comment by alexreardon** [comment]
Fixed by #673

**Comment by chmanie** [comment]
You are amazing ❤️

**Comment by alexreardon** [comment]
I try 😊
