### ISSUE TITLE
Usage as dropzone

### ISSUE THREAD

**Issue by O4epegb** [atlassian/react-beautiful-dnd#651]
I am trying to use `react-beautiful-dnd` as dropzone for some items. For example, I have kanban-like list, and delete-zone at the bottom, you can drag items to other lists, or you can drag them to delete-zone to remove them. It works fine, but the library warns that I am not using `{provided.placeholder}`. 
Is it ok to ignore this warn if I don't need placeholder?
Am I using library correctly at all? I am just worrying that some day it may remove support for such case :)

**Comment by alexreardon** [comment]
You should be fine adding `{provided.placeholder}` into these empty lists:

https://github.com/atlassian/react-beautiful-dnd#droppable

You insert it as a child of the list for the library to add space to the list if it needs to

If you are happy to ignore the warning then you should be fine to continue on as you are for now. We may have some more aggressive checks in the future but it is not on the roadmap

**Comment by O4epegb** [comment]
Ok, thank you very much!
