### ISSUE TITLE
Background color of empty space

### ISSUE THREAD

**Issue by erselnordlys** [atlassian/react-beautiful-dnd#652]
I want to customize background color of empty space between items, when I drag an item there. 
Something like this grey area bellow the dragged component: https://ibb.co/cAhjPJ

Still haven't found the option like this. Is there any way to do this? Thank you.

**Comment by alexreardon** [comment]
At the moment there is no way to do this.

Here is some context:

> #### Application 3: no drop shadows
> Drop shadows are useful in an environment where items and their destinations snap around. However, with `react-beautiful-dnd` it should be obvious where things will be dropping based on the movement of items. This might be changed in the future - but the experiment is to see how far we can get without any of these affordances.

- https://github.com/atlassian/react-beautiful-dnd#application-3-no-drop-shadows

**Comment by norayr93** [comment]
Hello , still no support for that feature ?
