### ISSUE TITLE
(Not an issue) , is it possible to integrate react bigcalender with React beautiful dnd

### ISSUE THREAD

**Issue by gautamz07** [atlassian/react-beautiful-dnd#657]
Just out of curiosity, is it possible to integrate react-bigcalender with react-beautiful-dnd ?

React bigcalender link ::- http://intljusticemission.github.io/react-big-calendar/examples/index.html

**Comment by alexreardon** [comment]
I would say probably not as react-beautiful-dnd is targeted at lists. You might be able to make something work but it could be a battle.

Others in the community may have already tried - but i have not

**Comment by gautamz07** [comment]
@alexreardon  thanks , just wanted to know if it can be easily integrated or not . TY.
