### ISSUE TITLE
[BUG] Material UI Header offsets draggable item

### ISSUE THREAD

**Issue by GarrettFleischer** [atlassian/react-beautiful-dnd#668]
### Expected behavior
The Draggable item is under the mouse cursor

### Actual behavior
The item is shifted down by the same pixel height as the Material UI Header component.
Note that the issue only occurs when the header is outside the DragDropContext component.

![image](https://user-images.githubusercontent.com/18196120/43352392-a0352d04-91d7-11e8-8efa-2aeba3b8d88e.png)

### Steps to reproduce

1. install @material-ui/core package
2. Use the Header component
3. Paste [this example code](https://codesandbox.io/s/ql08j35j3q) and render it below the Header.

### What version of `React` are you using?

"react": "^16.4.1",

### What version of `react-beautiful-dnd` are you running?

"react-beautiful-dnd": "^8.0.5",

### What browser are you using?

Latest version of Google Chrome

### Demo

[dropbox link](https://www.dropbox.com/s/wz9jn8hjxa31fwh/rbdnd.gif?dl=0) to gif.

**Comment by GarrettFleischer** [comment]
I personally solved this issue by creating a "Page" component that I used in all my top-level routes. Including inside the DragDropContext.
This is somewhat of a hack though.

**Comment by alexreardon** [comment]
You might want to try our [using a portal guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md)

That should give you more resilient positioning

**Comment by RinatRezyapov** [comment]
In case that someone is reading this closed issue. 
Can confirm that portals solve problems with material-ui appBar, toolBar etc.
This example of using portal could be helpful (https://codesandbox.io/s/88n6j1xlnj).
