### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by baiyuming** [atlassian/react-beautiful-dnd#672]
like this

![image](https://user-images.githubusercontent.com/13130499/43388182-07bc92f6-941b-11e8-966e-f6143aa1de74.png)
![image](https://user-images.githubusercontent.com/13130499/43388370-7b61f822-941b-11e8-9bad-3871c5cb135a.png)
![image](https://user-images.githubusercontent.com/13130499/43388378-7f633f26-941b-11e8-989c-719ba9c3ae39.png)

**Comment by alexreardon** [comment]
Without an independent example we cannot action this.

Here is a boilerplate you can fork from: https://codesandbox.io/s/k260nyxq9v

**Comment by alexreardon** [comment]
I am going to close this due to inactivity. Please provide a code sandbox if you would like us to look into it more
