### ISSUE TITLE
Support auto-scrolling and bounds detecting when there is no doctype

### ISSUE THREAD

**Issue by faiwer** [atlassian/react-beautiful-dnd#674]
Hello. I've probably found 1 bug or something "special". It's about `DOCTYPE` and `<html/>.clientHeight` value. I found this in the code of the library:

```
  // var getViewport = (function () {
  var doc = document.documentElement;
  !doc ? process.env.NODE_ENV !== "production"
    ? invariant(false, 'Could not find document.documentElement')
    : invariant(false)
    : void 0;
  var width = doc.clientWidth;
  var height = doc.clientHeight;
  var right = left + width;
  var bottom = top + height;
```
And `bottom` value was bigger than `<html/>.offsetHeight` value in my case. This code ^ uses the `doc.clientHeight` property. `Doc` is `<html/>` tag. So, `getViewPort` counts on `html.clientHeight` === `visible area height`. But it's not always true. Sometimes (e.g. DOCTYPE is missing on the page) `html.clientHeight === html.offsetHeight`, but `body.clientHeight === visible area height`. [More about it](https://stackoverflow.com/a/27175045/892741).

I have fixed this problem by using `<!DOCTYPE html>`. Maybe it's a good idea to check this situation inside `react-beautiful-dnd` too. Also, there's a kind of applications, which are placed to the page as they are, I mean "injected to the page". In these situations we don't have the power to set a correct doctype :)

**Comment by alexreardon** [comment]
No doctype? 🤯Interesting!

**Comment by alexreardon** [comment]
Can you think of a more robust alternative? Should we just use body.clientHeight and body.clientWidth rather than document.documentElement.*?

**Comment by faiwer** [comment]
> Should we just use body.clientHeight and body.clientWidth rather than document.documentElement.*?

There's a problem there. If a page has a doctype - `<body/>` doesn't fit this decision. If a page hasn't a doctype, it fits. Strange behaviour, isn't it?

I think that better solution can be something like this
```
const isNodeHasScroll = node => node.clientHeight < node.offsetHeight;

const viewbox = isNodeHasScroll(document.documentElement) 
    ? document.documentElement 
    : document.body;
```
But I'm not sure. The idea it next: if there's a scroll on the page, then the first of [html, body] what contains scroll - provides the viewbox information. So we can check at first `<html/>`, and if it fits - use it. If not - check `<body/>`. If it fits use `<body/>`, else use `<html/>`.

**Comment by alexreardon** [comment]
After internal discussion, we have decided not to support this for now. It is a very dark route to start looking into the different behaviours across doc types.

If you feel strongly about this please feel free to add suggestions and explorations
