### ISSUE TITLE
Is it possible to achieve a drag panning effect like google map

### ISSUE THREAD

**Issue by lonelydatum** [atlassian/react-beautiful-dnd#679]
I have a large element that is scaled where I would like to drag the element in order view other parts of the element.

Thank you :)

**Comment by alexreardon** [comment]
I am not sure what you are referring too. However, I suspect it falls outside of the scope of this library which deals with lists. You might find that building an experience with lower level primitives, such as with react-dnd, will get you where you want to go

Feel free to add more explanation if you feel like it falls in scope

**Comment by lonelydatum** [comment]
Hi Alex and thanks for getting back. I was not aware that this library only focuses on lists. I looked into react-dnd and it does do what I'm looking for. Thanks again.
