### ISSUE TITLE
Rendering Virtualization Support

### ISSUE THREAD

**Issue by carlosagsmendes** [atlassian/react-beautiful-dnd#68]
## Feature request

We are evaluating D&D libraries and we found that some, like [React Sortable](https://github.com/clauderic/react-sortable-hoc) have virtualization features or, work with libraries such as [React Virtualized](https://github.com/clauderic/react-sortable-hoc).

Is rendering virtualization support part of the current plans?

**Comment by alexreardon** [comment]
We where talking about this the other day. Right now it is not on our roadmap - but it would be cool to see if we could get this working

**Comment by danielg2002** [comment]
I'm using react-infinite wrapped with react-sortable-hoc.

That's can be done with react-beautiful-dnd ?

**Comment by alexreardon** [comment]
Not at this stage - we have not built for it. It would probably require #86 before we could tackle this one

**Comment by alexreardon** [comment]
This will need to be considered as part of the solution for #86

**Comment by OriR** [comment]
We're using this library and it works flawlessly!
But we've started to encounter issues when rendering hundreds of complex draggable components, when in fact we need to manage thousands at a time 😞 

Is there any way to promote this?

**Comment by alexreardon** [comment]
Right now we have a few other core features that we are looking to build out. Mobile and auto scrolling. Once those are completed we can re evaluate 👍

**Comment by OriR** [comment]
@alexreardon Thanks! that would be great!

Unfortunately we do need this right now, so I was thinking of doing a virtualization by hand (removing the elements that are outside the viewport), do you think I would encounter any issues by removing `Draggable` components? should I do `display: none` on them instead?

**Comment by alexreardon** [comment]
I am not sure @OriR as I have not looked into it yet. 

You will probably run in to trouble though. The way we do things today is that before a drag officially starts we grab all the dimensions of everything and then proceed from there. So if something is not there - or if it does not have its true dimensions then things will go wrong.

This will be thought of as apart of #86

**Comment by OriR** [comment]
Thanks!
I'll see how far I can go with this and post the results here in case someone else is interested with an interim solution👍

I also think this should be taken into account when doing #27 since virtualization relies heavily on scrolling.

**Comment by OriR** [comment]
@alexreardon I see #86 is closed and that #192 is marked with "priority: low" while this is "priority: medium".
Is there any way to extract only the essentials for this issue from #192 ? or is the move to a portal solution the issue itself?
What I'm asking is basically - what's blocking this issue now?

**Comment by OmriAharon** [comment]
@alexreardon Autoscroll day is celebrated today!
Please make our day and say this one is next on the list 🙏

**Comment by Frozenlock** [comment]
I'm using both `react-virtualized` and `react-beautiful-dnd` in my projects. Making them compatible would be heaven.

**Comment by dlee** [comment]
> Right now it is not on our roadmap - but it would be cool to see if we could get this working

Just to confirm, this is now *on* the roadmap, right?

**Comment by kazazor** [comment]
>Still weighing up if this is the right approach or if we should lean on async rendering

@alexreardon Wouldn't you still have a problem when the list is long?
async rendering will help in the way it will work nicely for the first X draggable items, but once dragging lower and lower in the list more items will be async rendered and then the problem will remain.. It will help rendering the DOM elements, but once it's in the DOM it will move slow when dragging.. Isn't it?

**Comment by nerdo** [comment]
I'm new to react, so please excuse my newbish-ness in advance. I'm working on something where I'm attempting to use virtualization (react-virtualized) and would like to combine it with react-beautiful-dnd.

Is this still out-of-the-question right now?

**Comment by Approxipix** [comment]
Do you have any progress on this issue?

**Comment by TrySound** [comment]
@Approxipix Yes, https://github.com/atlassian/react-beautiful-dnd/pull/719 is a step forward to solve this issue.

**Comment by nerdo** [comment]
Ditto @TrySound , thanks!

The way you framed it makes it sounds like #719 doesn't *completely* resolve the issue and more work is needed. Am I reading into that correctly?

**Comment by TrySound** [comment]
Yes

**Comment by hpeikari** [comment]
We have been using both react-virtualized and react-beautiful-dnd in our project. But the incompatibility of the two is unfortunately forcing us to switch to a different library (react-dnd).

**Comment by OmriAharon** [comment]
We are also forced to drop the use of `react-beautiful-dnd` as well in one of our main features due to lack of virtualization. Would be great to hear if this is getting any attention soon.

**Comment by alexreardon** [comment]
We hope to work on it in the coming months

**Comment by MagerlinC** [comment]
We use React Virtualized at our company, and have been using React-DnD up to this point. We tried switching to React Beautiful DnD and absolutely prefer the style of your framework, but are having trouble using it due to its incompatibility with React Virtualized lists. If this was changed, we would most definitely use React Beautiful DnD for our platform.

**Comment by alexreardon** [comment]
We hope to work on this in the coming months

**Comment by tjramage** [comment]
That would be great @alexreardon. Our app has A LOT of drop targets, so performance starts to drop once this gets beyond a certain size. We're very keen to see progress in this area if possible! 👍

**Comment by OriR** [comment]
@alexreardon Looking at the [changelog for v10](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0), other than the fact that just the release notes themselves look amazing!
The fact that you were able to achieve all of this without technically breaking anything even more astounding!

A particular change in the release notes that caught my eye is the ability to add/remove items during drag, which to me as a layman in D&D, feels like a huge milestone towards virtualization support!

Do you think it's possible to achieve some basic virtualization support just with this feature?
By following the guide you posted [here](https://github.com/atlassian/react-beautiful-dnd/blob/v10.0.0/docs/guides/changes-while-dragging.md), the rules seem to be allow it assuming all the virtualized item are only draggables and not droppables, right?

**Comment by alexreardon** [comment]
It is a big step towards virtualisation support 👍

**Comment by neooleg** [comment]
@alexreardon thanks for tracking activity in milestones for letting everybody know that it's in progress now! 👍

Can you let us know any ETA/due dates for this milestone (with virtualization feature inside)?

Thanks in advance!

**Comment by navneet-g** [comment]
Has anyone successfully used react-virtualized or any other virtualization library with react-beautiful-dnd?

**Comment by martingronlund** [comment]
Work harder! 🤠

**Comment by nerdo** [comment]
It’s open-source... contribute! :)

**Comment by navneet-g** [comment]
I am open to contributing, I will go through the docs. 

1. I am pretty new to the library, and there is lot of concepts, which one should I prioritize in scope of this issue?
2. Are there any specific design docs for contributors?

**Comment by alexreardon** [comment]
It is fairly addhoc at the moment @navneet-g. Even if you have a crack and get 80% of the way through that is valuable so we can see how you went about it 👍

**Comment by navneet-g** [comment]
Thanks @alexreardon , I noticed that you marked it as priority:high. I have yet to start ramping up on the code, and it will take me sometime (read few weekends) to be comfortable enough to propose any changes.

**Comment by amiral-jion** [comment]
I want to contribute to this issue, anyone can guide me what should be done (an idea)

**Comment by navneet-g** [comment]
I have not gotten anytime to work on this, and most likely won't get any time next couple of weeks :(.

**Comment by tjramage** [comment]
We are running react-beautiful-dnd on our production app and, for the most part, it's great! However, there are cases where our users have ~1000+ droppables, and you can really feel the performance / lag. @alexreardon, you mentioned above that you were hopeful to work on this in the coming months – are you able to confirm if this is still the case? 🙏

**Comment by pureZjr** [comment]
> I'm using both `react-virtualized` and `react-beautiful-dnd` in my projects. Making them compatible would be heaven.

 I'm using both `react-virtualized` and `react-beautiful-dnd` in my projects，too. but when i scroll ,it error 'Cannot remove the dragging item during a drag'。you have any solutions，thank you。

**Comment by dimitarnestorov** [comment]
@pureZjr can you share an example?

**Comment by nicubarbaros** [comment]
@pureZjr That's how it is designed the library for now. You can remove everything else other than the current dragged item. Check the changelogs of the 10.0 v when it came out

**Comment by KhogaEslam** [comment]
any updates about using  [React Virtualized](https://github.com/bvaughn/react-virtualized) with [React Beautiful DnD](https://github.com/atlassian/react-beautiful-dnd/) ?

**Comment by dcporter44** [comment]
Any updates on this?

**Comment by chrbala** [comment]
It looks like it'll be in the 12.0 release. https://twitter.com/alexandereardon/status/1138960614447915014

**Comment by alexreardon** [comment]
It will ship in 12.0. I will combine this issue with #1225

**Comment by Aarbel** [comment]
Thanks a lot @alexreardon for your work ;)

**Comment by alexreardon** [comment]
#1225 contains the alpha releases which you can use to try this out

**Comment by Aarbel** [comment]
@alexreardon is it working great under stable version now ?

**Comment by alexreardon** [comment]
Soon! I am aiming for next week

**Comment by Aarbel** [comment]
@alexreardon here is a croissant with the hope to see the release soon : 🥐

**Comment by nicubarbaros** [comment]
@alexreardon Thank you so much for the release!!! You are amazing!

**Comment by alexreardon** [comment]
This has been released in 12.0 :D

**Comment by mbielecki3** [comment]
Hello, is there any plan for release new version of https://www.npmjs.com/package/@types/react-beautiful-dnd/v/11.0.3 for this virtualized list feature?
