### ISSUE TITLE
Can I 'duplicate' the Draggable item so I'm dragging a clone and the original stays in the same place?

### ISSUE THREAD

**Issue by davewthompson** [atlassian/react-beautiful-dnd#680]
Please pardon me if this isn't the correct forum to ask, but is there a way I can clone the item being Dragged, so instead of moving it I'm moving a clone of it - a little like a "toolbox" effect?

I looked through the documentation and skimmed the code but I couldn't find a nice way to do this (apart from re-inserting an item in the list during the onDragStart handler, which seems a bit messy)

Also, many thanks for the awesome library!

**Comment by davewthompson** [comment]
I would state, after some investigation, that this is a resounding "probably not"; there is a Placeholder element which keeps the same size as the dragged element, but there's no way to clone the element that is dragged. I suppose it would be possible by forking the repo and adding a way to call React.cloneElement before the drag starts, but that looks like a considerable about of work.

**Comment by alexreardon** [comment]
Here is an issue with some more information about this:

https://github.com/atlassian/react-beautiful-dnd/issues/216

**Comment by ohiowebtechdevteam** [comment]
Hello @davewthompson 
Check this link : [](https://github.com/atlassian/react-beautiful-dnd/issues/216#issuecomment-423708497)
