### ISSUE TITLE
Invariant failed: MOVE not permitted in phase IDLE

### ISSUE THREAD

**Issue by chellman** [atlassian/react-beautiful-dnd#683]
## Bug or feature request?

Bug, or maybe just a sanity check

I assume this is probably more an issue with how I'm using the library, but maybe there's some subtle issue I'm uncovering.  I think this library is super, and I would certainly like to keep using it unless something about my use case precludes it. I didn't see any issues like this, so if this is developer error, and I can get a nudge in the right direction, that would be great.

### Expected behavior

The app I'm building has several lists in columns, powered by a big JSON blob, with inspectors for every item that appear on click, so drag and drop is only supported within columns. There is another mechanism for moving items between columns.  When I use the move function, the state of the JSON updates fine, and everything looks good (to me at least) when re-rendered.

I'm expecting that after an item is moved to a new list, drag and drop will keep working, but it does not.

### Actual behavior

Once the item has been moved, drag and drop no longer works. Nothing looks weird until I perform any interaction that would trigger a drag.  Then the console gets loaded with errors like this:

`Error: Invariant failed: MOVE not permitted in phase IDLE`

Here's a screenshot of the stack trace:

![Stack trace](http://www.shooflydesign.org/f/beautiful-dnd-stack-trace.png)

### What version of `React` are you using?

16.4.2

### What version of `react-beautiful-dnd` are you running?

8.0.7

### What browser are you using?

This happens in any browser I've tried: Firefox 61, Safari 11.1.2, Chrome 68.

### Demo

[Here's a short screencast of the issue manifesting.](http://www.shooflydesign.org/f/beautiful-dnd-issue.mp4)

What I think are the important parts of the code are roughly like this.  The <LastColumn> component has nothing draggable in it, so it's not included.

```js
// App.js

methodThatBuildsColumns() {
    // eventually gets to this:
    this.setState({items: [
        <Column ...>,
        <Column ...>,
        ...,
        <LastColumn>
    ]);
}

render() {
    return (
        <main>
            <DragDropContext onDragEnd={this.onDragEnd}>
                {this.state.items}
            </DropDropContext>
        </main>
    );
}

// Column.js

render() {
    const items = this.props.items.map((node, idx) => {
      return (
        <Draggable
          key={node.id}
          draggableId={node.id}
          index={idx}
          type={`col-${this.props.columnNumber}`}
          isDragDisabled={this.props.columnNumber === 1}
        >
          {provided => (
            <li
              ref={provided.innerRef}
              {...provided.draggableProps}
              {...provided.dragHandleProps}
              onClick={e => this.handleEntryClick(node, e)}
            >
              {itemContent}
            </li>
          )}
        </Draggable>
      );
    });

    return (
        <Column>
            <Droppable
              droppableId="droppable"
              type={`col-${this.props.columnNumber}`}
              isDropDisabled={this.props.columnNumber === 1}
            >
              {provided => <ul ref={provided.innerRef}>{items}</ul>}
            </Droppable>
        </Column>
    );
}
```

**Comment by alexreardon** [comment]
This should definitely not be happening. Thanks for raising it. Without a reproducible example, it is hard to action.

Here is a boilerplate you can start from: https://codesandbox.io/s/k260nyxq9v

**Comment by chellman** [comment]
Thanks, @alexreardon.  I think I found the issue, or at any rate I found a fix, and as I assumed, it was developer error.  Note in the example above that droppableId just set to "droppable".  As the docs say, these must be unique in the app. Once I did that:

```js
droppableId={`droppable-${this.props.columnNumber}`
```

everything started working.  So if anyone else see errors like this, one thing to check: make sure your droppableIds are unique!

The only thing I can say is maybe there should be warnings in the console if someone make this kind of silly mistake. I'm not in a position to be able to offer that right now (family += 1 any day soon), but if that sounds like a good idea, I would look into it once I'm able.

**Comment by alxndr** [comment]
We are seeing an error similar to this being thrown by `react-beautiful-dnd` when our app is under test via our [Cypress framework](https://cypress.io) test suite and it interacts with the component which is using `react-beautiful-dnd`:

```
Invariant failed: Cannot be IDLE
```
