### ISSUE TITLE
react-beautiful-dnd breaks react-router

### ISSUE THREAD

**Issue by Amol023** [atlassian/react-beautiful-dnd#685]
## Bug or feature request?

Bug

### Expected behavior
Routes should change as expected

### Actual behavior
We have a tab based UI based on routes and even though the URLs change, the view doesn't

### What version of `React` are you using?
V 16.3.1

### What version of `react-beautiful-dnd` are you running?

8.0.7

### What browser are you using?

Chrome

### Demo

```
 <Route
       path="__SOME_DYNAMIC_PATH"
       render={({
            match: {
            params: { view, thread },
            url,
            },
            history,
        }) => {
```
The `view` should ideally change when changing tabs - attaching DragAndDropContext doesn't update the view anymore.

I tried putting DragAndDropContext 
1. In App.js
2. At a component level - the one where I use Draggable and Droppable

No difference

**Comment by alexreardon** [comment]
Can you please create a stand alone example on code sandbox?

**Comment by alexreardon** [comment]
I have created a little example that uses `react-router` and I cannot reproduce the issue you are seeing:

https://codesandbox.io/s/8zzx72nm48

If you are still experiencing an issue please provide a stand-alone example for us to understand what you are seeing.

Cheers

**Comment by Amol023** [comment]
Hey @alexreardon, thank you for taking the time to create a condesandbox example!
The problem however, is that we've a giant commercial application where we've redux and we use `connected-react-router` along with react-router. It'd be a lot of work to sandbox this

The problem still persists though! The routing gets messed up as soon as <DragDropContext> is added to our app (regardless of where in the app we put it) - i.e. The `view` doesn't get updated at all in `Route`'s render method, 
https://reacttraining.com/react-router/web/api/Route/render-func

**Comment by alexreardon** [comment]
Without a reproducible example we are unable to assist you
