### ISSUE TITLE
Create addon for physics based dragging item

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#689]
We could implement a similar dragging system to the blog: [How to fix dragging animation in UI with simple math](https://uxdesign.cc/how-to-fix-dragging-animation-in-ui-with-simple-math-4bbc10deccf7) by [Nash Vail]( https://twitter.com/NashVail).

![](https://cdn-images-1.medium.com/max/2000/1*mzUTDrvpsdQrV8xu_exM1Q.png)

We could implement this as a seperate npm package for consumers to opt in. Unlike the blog which is based on mouse position we could patch the `DraggingStyle > transform` directly. The `x,y` values can be pulled out of that, and the `transform` can be monkey patched. 
I am thinking it should be a seperate package as it makes it clear how users could consume it without making it an option. If we are happy with the experience generally we could look at pulling it into the core library

I am thinking something like this:

```js
import {patchTransform} from '....';

class Item extends React.Component {
	render() {
		return (
			<Draggable draggableId="draggable" index={0}>
				(provided, snapshot) => (
				 <div 
					{...provided.draggableProps} 
					{...provided.dragHandleProps}
					ref={provided.innerRef}
                    style={patchTransform(snapshot.isDragging, provided.draggableProps.style)
                 >
					Drag me!
				</div>
			</Draggable>
		)
	}
}
```

```js
const patchTransform = (isDragging, style) => {
  if(!isDragging) {
    return style;
  }
  if(!style.transform) {
    return style;
  }

  // pull out the x,y values from the transform
  // apply an additional rotate transform
  return patched;
}

```

**Comment by theKashey** [comment]
It probably should be a stateful component, so:
```js
<Draggable draggableId="draggable" index={0}>
   {(provided, snapshot) => (
          <FancyDragAnimationOnSprings style={provided.draggableProps.style}>
              { style => 
		<div 
		  {...provided.draggableProps} 
		  {...provided.dragHandleProps}
		  ref={provided.innerRef}
                  style={style}
                >
		  Drag me!
		</div>
               }
       </FancyDragAnimationOnSprings>
   )}
</Draggable>
```

**Comment by alexreardon** [comment]
To avoid multiple people working on this - if you are interested it working on this just say so here 👍

**Comment by rokborf** [comment]
working on it

**Comment by rokborf** [comment]
https://github.com/rokborf/natural-drag-animation-rbdnd

**Comment by alexreardon** [comment]
Brilliant!!!

**Comment by alexreardon** [comment]
We should add a section to the docs to let people know that this exists! An add-on section?

**Comment by alexreardon** [comment]
I tweeting about the add on: https://twitter.com/alexandereardon/status/1038924306447720448

**Comment by alexreardon** [comment]
We now need to add a section to the docs 👍

**Comment by rokborf** [comment]
I'll create PR

**Comment by alexreardon** [comment]
Thanks @rokborf!! #841

**Comment by cluk3** [comment]
Hey @alexreardon ! First of all thx for this amazing library and for the add-on, they're both super useful!

I wanted to checkin if the add on is still supposed to work with v13 and if there are currently other solutions built in the library.
Actually it's not working for me and I couldn't find anything related in the documentation apart from this issue.
In my app i'm using a custom hook which is using the core logic of @rokborf's natural-drag-animation-rbdnd package.

You can see the code and play with it [here](https://codesandbox.io/s/-34nim?file=/src/usePatchTransform.js)

If this is of interest I can create an npm package.
