### ISSUE TITLE
Which development environment should be used?

### ISSUE THREAD

**Issue by pashadow** [atlassian/react-beautiful-dnd#690]
I'm going to build this code locally in order to check some ideas.
Could your please give me suggestions which environment should I have?
I've tried to build it on my Windows 7 PC with no success, I've got a lot of errors about yarn, python and modules like babel-cli, rollup, etc.

The main questions are:
1. OS ?
2. node version ?
3. npm version?
4. python version?
5. other dependencies?

**Comment by alexreardon** [comment]
I will try to get to this tomorrow

**Comment by TrySound** [comment]
@pashadow I don't think python is required in this package. Could you show us errors you get?

**Comment by alexreardon** [comment]
OS: up to you
Node version: Use latest stable
npm version: use latest stable
phython: not needed
other: yarn (https://yarnpkg.com/en/docs/install#mac-stable)

Other steps:
1. clone repo
2. install dependencies (run yarn)
3. start development environment (yarn storybook)

**Comment by pashadow** [comment]
@TrySound @alexreardon 
The very first problem was with repo
![image](https://user-images.githubusercontent.com/6725216/43824322-57fb0348-9afa-11e8-9162-0e31d3f5bb51.png)
Symbol "?" isn't allowed as part of the filename in Windows.

**Comment by pashadow** [comment]
`yarn install` and `yarn storybook` help me make code work for the latest master on Windows PC.
But I didn't get success with v6.0.2, which I'm trying to build.
The full log can be found here https://pastebin.com/rApezFg1
Sorry, I didn't specify that I'm using v6.0.2 version in my first post.

**Comment by TrySound** [comment]
1. There's not file with `?`. AFAIK it's not allowed in mac os too. Probably tortoise bug, use git cli directly as an alternative or try another client
2. Try to remove website folder and the run yarn

**Comment by pashadow** [comment]
@TrySound 
1. This is a file with ? in filename and in MacOS I'm able to make such file.
https://github.com/atlassian/react-beautiful-dnd/blob/master/test/unit/view/drag-handle/%08touch-sensor.spec.js
2. It didn't help. I see loop when run `yarn install` without website folder. It seems yarn is trying to build code but never stops.

**Comment by lukebatchelor** [comment]
I think it's a backspace character, judging by the Uri encoding there. I'll see if I can fix it here.

Super weird though

**Comment by lukebatchelor** [comment]
Fix is above^

👍

**Comment by pashadow** [comment]
@lukebatchelor Thank you. Yes, it might be backspace. It is shown as "?" in TortoiseGit log (see screenshot)
