### ISSUE TITLE
animation for the drop sometimes jumps to unexpected location

### ISSUE THREAD

**Issue by cch5ng** [atlassian/react-beautiful-dnd#691]
### Expected behavior

I'm trying to use react-beautiful-dnd in the context of a drag and drop form editor.

In general, the animation works great and I'm enjoying this library (thanks for the detailed work on it). In my current code, I'm getting some unexpected animation behavior when dropping a draggable on a 2nd droppable (in particular if I drag below about the 3rd row of draggable items).

### Actual behavior

 Sometimes the draggable appears to fly to a lower corner (either 1-2 rows below the expected location or to the very lowest corner of the browser). Sometimes I don't see the drop animation. A couple of gifs below.

The actual drop event looks OK and after the animation completes, the draggable displays in the appropriate list location. But occasionally I'm concerned the drop animation might confuse users.

### Steps to reproduce

1 Drag items from the right column to the left column.

2 Drop somewhere below the 3rd existing draggable (on left). Sometimes the drop animation ends where expected but sometimes it drops further down than the expected row. Sometimes the animation for drop doesn't show. But the dropped draggable does appear in the correct order afterward.

* Is this related to having droppables of different widths? 

* Since we're working on a drag and drop form editor, the draggable is expected to change (size and contents) after the dragEnd event. Would this cause the issue with the drop animation? Is there any workaround for this?

* Do you know if anyone else is using react-beautiful-dnd in a similar way?

### What version of `React` are you using?

16.4.1

### What version of `react-beautiful-dnd` are you running?

8.0.7

### What browser are you using?

Chrome 68.0.3440.84 (Official Build) (64-bit)
on Windows 10 (via parallels)

### Demo

https://codesandbox.io/s/4217lz084

(gif example)

![toolbox_drop_animation_glitch080318](https://user-images.githubusercontent.com/4755432/43725197-23a6f0f4-9959-11e8-8104-81f9c0d059f4.gif)

**Comment by alexreardon** [comment]
It looks like your reorder logic is a little bit broken: https://codesandbox.io/s/lx9rx4wzk7
It is creating a copy on drop some times.

Also, keep in mind that it is currently not possible to move an item into a nested list at this stage. Otherwise your example seems to be working as expected..

**Comment by cch5ng** [comment]
I tried a couple of changes (https://codesandbox.io/s/rjz8y9rj2o)

* when a draggable is dropped, 1 remove/replace it from original ids list; 2 add it to new ids list (for droppable)

* removed the draggable which contained a nested list; I think maybe this was affecting the drop animation even though in my testing, I was only dropping an item at the outer list level

**Comment by cch5ng** [comment]
I'm sorry @alexreardon but I will ask to close this issue (or should I). I am nearly certain that the drop animation behavior reported is related to how I was rendering the nested list. we are not at a point where there is a clear way the final draggables will be rendered. when we get to that point if there is still an issue with the drop animation, I'll reopen an issue. sorry to take your time and I appreciate your help.
