### ISSUE TITLE
Hook functions require a void return type

### ISSUE THREAD

**Issue by chrbala** [atlassian/react-beautiful-dnd#695]
I'm not sure if this should be filed under bug or feature request.

Basically the hooks have a void return type, which means that you can't return any value, whether the return value is used or not. 

```javascript
type OnDragStartHook = (start: DragStart, provided: HookProvided) => void;
type OnDragUpdateHook = (update: DragUpdate, provided: HookProvided) => void;
type OnDragEndHook = (result: DropResult, provided: HookProvided) => void;
```

This means that we can't do:
```
<DragDropContext onDragStart={someFunctionThatReturnsValue} />
```

Instead, we have to proxy the function like this:
```
<DragDropContext onDragStart={(...args) => { someFunctionThatReturnsValue(...args) }} />
```

Since the return isn't used anyway, is there a reason why these aren't typed with a ``mixed`` return type? This is how I typically type event handlers in order to give more freedom.

**Comment by alexreardon** [comment]
If we change the return type to `mixed` it might imply that we are doing something with the return value, which we are not. I think this could be a source of confusion for people

**Comment by alexreardon** [comment]
Fair enough! Happy to update the types. I think it would be also worth calling out in the docs that we do not use the return type

**Comment by alexreardon** [comment]
I think this would be a good candidate for a first contribution 😊

**Comment by alexreardon** [comment]
This will ship in our next release! Thanks @kylehalleman!!
