### ISSUE TITLE
Version for older version of React.

### ISSUE THREAD

**Issue by sarates** [atlassian/react-beautiful-dnd#699]
Hi! What version of this library I should use with React 15.5.4. Thanks a lot.
Currently I have an error : `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

**Comment by alexreardon** [comment]
Hi there,

We are currently not supporting older versions of react. We are leaning on newer features, and supporting old versions would add to our complexity and slow us down. 

Version 6 was the last version that supported react 15 👍

**Comment by sarates** [comment]
@alexreardon  thanks for reply. Currently Im trying versions 6 and 5, but all of them have issue with wrong destination index. I use basic code from examples. 

https://drive.google.com/file/d/1H0KcomDIvII3gDEvCVDRaSBs5bjbyG7_/view

Could you check pls, maybe you have some tips.

**Comment by joesalloum** [comment]
@sarates did you manage to fix the wrong index on drag release ?
