### ISSUE TITLE
Ensure that library works well with screen readers

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#7]
It would be worth auditing how well this library works with screen readers and if there are any improvements that can be made

**Comment by svinkle** [comment]
As mentioned over in https://github.com/a11yproject/a11yproject.com/issues/513#issuecomment-324498371, here are a few instructions/audible cues that would be helpful to people who rely on screen readers:

- How to pick up and put down items
- Which order items are now in after dropping
- How many items there are in total
- Semantic meaning for each item (currently announced as, "link")

I just did a quick pass to check things over with Chrome + VoiceOver on maxOS. This needs to be tested with other browser/screen reader combinations as well.

Time permitting, I'd like to jump in and conduct more testing and dive into the code to see where these types of announcements and semantics could be added.

All that said, the keyboard support is really fantastic! 👍

**Comment by alexreardon** [comment]
Thanks for looking into this @svinkle !!

**Comment by alexreardon** [comment]
Super relevant: https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09

**Comment by alexreardon** [comment]
Thanks @seancurtis for the link!

**Comment by alexreardon** [comment]
Another good article: https://www.smashingmagazine.com/2018/01/dragon-drop-accessible-list-reordering

**Comment by alexreardon** [comment]
I am looking into api options for this. Currently:

```
onDragStart(start: DragStart, {announce: (message) => void})
```

where you call announce with your message. If you do not call it then we use a default message

or

```
onDragStart(start: DragStart): string
```

We use the string you return from the handler. If not is returned then we use a default...

**Comment by alexreardon** [comment]
@svinkle this will be shipping in v5 👍

**Comment by svinkle** [comment]
@alexreardon Awesome! Any method available where I could test the work being done so far?

**Comment by alexreardon** [comment]
We are publishing to npm tomorrow

**Comment by alexreardon** [comment]
But the example storybook website has it now

**Comment by alexreardon** [comment]
This has been completed as a part of #321 

It feels (and sounds) great!
