### ISSUE TITLE
Move from react-motion to CSS for drop animation

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#709]
We currently use `react-motion` for our drop animation. I want to explore using just CSS animations to achieve a similar natural drop feel.

Why?

- Using the`react-motion` currently adds 5kb gzip to our bundle, which is a 25% of the total
- Drop animations are done on the CPU rather than the GPU. If we could move the work to the GPU then they would be much lighter on the system
- Currently all movements need to go through `react-motion`. Dropping `react-motion` would (probably) yield a nice perf win for normal drags (need to confirm)
- We currently have some yuck workarounds for using `react-motion` throughout the code that I hope to get rid of

**Comment by dimitarnestorov** [comment]
Is the drop animation the only animation that requires `react-motion`?

**Comment by alexreardon** [comment]
Yes

**Comment by alexreardon** [comment]
We want to have a nice feeling drop as much as possible.

Ideally we just have one animation curve, but we could also dynamically create a curve based on the distance required to travel

**Comment by alexreardon** [comment]
Great news on this front. We have managed to find a CSS only solution that replicates the exact spring based animation curve we obtained with `react-motion`. 

This will be going out in our next major release. #719 

I will write more extensively about this in the release notes

**Comment by alexreardon** [comment]
Closes #442 #443 #437

**Comment by souporserious** [comment]
Couldn't tell from the PR if you're going with a simple bezier curve or a library, but these might help get closer to a spring in just CSS:
https://github.com/tannerlinsley/springer
https://github.com/sktt/springish-css

**Comment by alexreardon** [comment]
We are creating a bezier curve with a dynamic duration that matches the same visual experience of a previous spring on react-motion 👍

**Comment by alexreardon** [comment]
thanks for the links @souporserious

**Comment by alexreardon** [comment]
Shipped in [10.0](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)
