### ISSUE TITLE
An issue about DragDropContext

### ISSUE THREAD

**Issue by Steve3029** [atlassian/react-beautiful-dnd#710]
### I wrapped my 'App' component up with 'DragDropContext' and the code is follow:
`
  render () {

    return (
      <DragDropContext onDragEnd={this.onDragEnd}>
         const stepList = this.state.instruction.stepIds.map(stepId => this.state.steps[stepId])
        <Instruction title={this.state.instruction.title} steps={stepList}></Instruction>
      </DragDropContext>
    )
  }
`

Then I have got an error: 'stepList is un-defined'. I fixed it through moving the definition of stepList out of return expression. The code looks like this:
`
render () {

    const stepList = this.state.instruction.stepIds.map(stepId => this.state.steps[stepId])
    return (
      <DragDropContext onDragEnd={this.onDragEnd}>
        <Instruction title={this.state.instruction.title} steps={stepList}></Instruction>
      </DragDropContext>
    )
  }
`
I am confusing about what reason caused this problem.

### react version 16.4.2 & react-beautiful-dnd version 9.0

**Comment by alexreardon** [comment]
It looks like you are having some issues with `JSX`. It can be a little confusing.

Here are some resources you will probably find helpful:

- [React JSX docs](https://reactjs.org/docs/introducing-jsx.html)
- [JSX in depth](https://reactjs.org/docs/jsx-in-depth.html)
- [JSX lesson](https://egghead.io/lessons/react-replace-react-createelement-function-call-with-jsx)
