### ISSUE TITLE
Memory leak & onFatalError in DragDropContext

### ISSUE THREAD

**Issue by faiwer** [atlassian/react-beautiful-dnd#715]
Hello. I started to check memory leaks in our application, and found a lot of them :( 
One of them relies on react-beautiful-dnd. The leak is in the DragDropContext. Let's dive in:

- We have class-component `<DragDropContext/>`
- This class contains: `onFatalError = (error: Error) => {...}`
- and `onWindowError = (error: Error) => this.onFatalError(error)`
- and in `componentDidMount` method we make a subscription: `window.addEventListener('error', this.onWindowError)`
- ... in `componentWillUnmount` - `window.addEventListener('error', this.onWindowError);`

What's wrong with it? These subscriptions retain in memory `<DragDropContext/>` instances forever. And all their links too, of course. They aren't removed from the memory because of `onWindowError` and `onFatalError`. Both of these methods are declared in the class-scope and have link to `this` object. So we have memory leak.

![img_17_08_01_049a068531d](https://user-images.githubusercontent.com/744114/44262407-c3b5a900-a23c-11e8-91fd-70cdcfa6d42a.png)
^^^ a lot of them :)

![img_17_08_01_8efde6c043c](https://user-images.githubusercontent.com/744114/44262447-eb0c7600-a23c-11e8-9d38-77b9f7769c6b.png)

I don't know why DragDropContext needs these subscriptions, but it would be much better to remove them, or rewrite this code without memory leaks ;)

**Comment by faiwer** [comment]
There's also 1 more memory leak. But I haven't understood them yet. This one is more intricate. It's about this code:
```
  var unbind = function unbind() {
    if (!isBound) {
      return;
    }

    isBound = false;
    unbindEvents(getWindow(), pointerEvents, {
      capture: true
    });
  };
```
`bind` and `unBind` methods in `createPostDragEventPreventer`. 
![img_17_08_01_d0ed444efcd](https://user-images.githubusercontent.com/744114/44266004-bc959780-a24a-11e8-889d-80519951fdb2.png)

We again have window object and some relations with subscriptions. But.. also we have a matreshka of `unbindWindowEvents` :)

**Comment by alexreardon** [comment]
Let me know if you see any others

**Comment by alexreardon** [comment]
Also, what tool are you using?

**Comment by faiwer** [comment]
It's about the previous one. These unbind methods retain all their HTML & Fiber nodes. 
![img_17_08_01_cd8f2ae3390](https://user-images.githubusercontent.com/744114/44266636-0bdcc780-a24d-11e8-9930-3d1f9d42dde0.png)

But I can't say the certain place in the code and certain reason, that occurs this leak.

> Also, what tool are you using?

I use ChromeDevTools. Their Memory tab.
- I make a snapshot of the application
- then I work with my application (click, click, click, click...)
- then click to "collect garbage" icon (trash-icon)
- then I make another snapshot
- then I compare them and search in differences what they are and why they are :) 

It's a tricky deal, but it's only what I know about how to fight with memory leaks :)

**Comment by alexreardon** [comment]
I can fix the first one easily. The second one will take some more investigation
