### ISSUE TITLE
QUESTION: control auto-scrolling when dragging the top item.

### ISSUE THREAD

**Issue by iliran11** [atlassian/react-beautiful-dnd#716]
1. Start to drag an item which is located in the top of the viewable area
2. Immediately on start drag, there is a fast auto scroll upwards which requires you to scroll down again so you can return to where you have been.

Is there is a way to control this auto-scroll behavior?
Couldn't find anything on docs.

![auto-scrolling](https://user-images.githubusercontent.com/24987188/44262833-2438ec00-a225-11e8-80bf-096f169d1fb0.gif)

**Comment by alexreardon** [comment]
Thanks for raising this.

We are tracking it here: https://github.com/atlassian/react-beautiful-dnd/issues/349
