### ISSUE TITLE
Problem with drag end and context api

### ISSUE THREAD

**Issue by thomvilla** [atlassian/react-beautiful-dnd#717]
Hi i am using context api, I need to make a list with data that come from context api. 
this data is variable so it can change, so I can not save it in the state of this component.
I could implement dnd but it does not work as I expect, when I click it appears as if it were in the first position and only drops in the last position. please any help is welcome.

my code: [https://gist.github.com/thomvilla/106c9d3652eab0ee4ee5901cddc36db0](url)

**Comment by alexreardon** [comment]
Can you please fork our `codesandbox` stand alone example? https://codesandbox.io/s/k260nyxq9v

Without a running example we cannot action this

Cheers

**Comment by thomvilla** [comment]
i can resolvit with other library equally thanks u !!
