### ISSUE TITLE
flow not working

### ISSUE THREAD

**Issue by conradkay** [atlassian/react-beautiful-dnd#721]
## Bug or feature request?
bug
(answer here)
react-beautiful-dnd 8 or 9 makes flow not check file saves, making me have to restart my editor.

### Expected behavior
flow detects errors about type when saving files.
### Actual behavior
flow does not
### Steps to reproduce
CRA 
package.json:
{
  "jest": {
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  },
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "babel-eslint": "^8.2.6",
    "enzyme-adapter-react-16": "^1.2.0",
    "eslint": "^4.19.1",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jest": "^21.20.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.0",
    "flow-bin": "0.78.0",
    "radium": "^0.24.1",
    "react-beautiful-dnd": "9.0.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^1.1.4",
    "redux": "^4.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "test:lint:js": "eslint --ext=js --ext=jsx .",
    "build": "react-scripts build",
    "flow": "flow",
    "babel-eslint": "^8.2.6",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "enzyme": "^3.4.1",
    "enzyme-to-json": "^3.3.4",
    "eslint-plugin-flowtype": "^2.50.0",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "^16.4.2",
    "redux-devtools-extension": "^2.13.5",
    "regenerator-runtime": "^0.12.1"
  }
}

### What version of `React` are you using?
16.4.2

### What version of `react-beautiful-dnd` are you running?
9.0.0

### What browser are you using?
none

**Comment by TrySound** [comment]
@conradkay Which editor do you use? Perhaps the problem is flow integration with it.

**Comment by conradkay** [comment]
@TrySound Atom nuclide, the error persists even when using flow in the terminal.

**Comment by TrySound** [comment]
Which error?

**Comment by conradkay** [comment]
@TrySound flow does not seem to update, I need to restart atom for a save.

**Comment by conradkay** [comment]
I have since migrated to react-sortable-hoc but if you need it I can pull up the old version with react-beautiful-dnd.

**Comment by TrySound** [comment]
Yes, try to reproduce in repository please. It will help to understand what's the problem.

**Comment by alexreardon** [comment]
Without more information, this is hard to action.

Our CI server is constantly running flow against the project and it is working fine

**Comment by conradkay** [comment]
repo here: https://github.com/conradkay/todo-app-jest-flow-router-react-redux/tree/6802ecc2a4e8c662d365d5f75c8c2f5d532b615e

**Comment by conradkay** [comment]
The repo is currently not using react-beautiful-dnd but you can mess with the actions.js folder and change the first variable from type number to type string and see if running flow shows an error.

**Comment by conradkay** [comment]
I think this issue should be closed(i will move to flow repo) as I experienced this error with another package, meaning it is most likely a problem with flow itself.

**Comment by alexreardon** [comment]
Thanks for the follow up
