### ISSUE TITLE
Object doesn't support property or method 'find' in IE11

### ISSUE THREAD

**Issue by wzc19920413** [atlassian/react-beautiful-dnd#724]
## Bug or feature request?

Bug

### Expected behavior
To be able to drag and drop on IE11
### Actual behavior
App can not be opened and cause error:

SCRIPT438: Object doesn't support property or method 'find'

### Steps to reproduce
I think this is related to [#320](https://github.com/atlassian/react-beautiful-dnd/issues/320)

The console error points to the file [supported-page-visibility-event-name.js](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/drag-handle/util/supported-page-visibility-event-name.js)

Not sure whether there are other files that would cause the error
### What version of `React` are you using?
16.2.0

### What version of `react-beautiful-dnd` are you running?
9.0.0

### What browser are you using?
IE11

**Comment by alexreardon** [comment]
Related: #320 

For now you can polyfill .find

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

**Comment by alexreardon** [comment]
I don't think we will stop using `.find`, but we should be clearer about what polyfills are required for IE11.

**Comment by alexreardon** [comment]
Sure @wuweiweiwu. At this stage we would be after a guide that states that we require `.find` to be polyfilled for ie11

**Comment by tgormtx** [comment]
I've added polyfills to my app and it doesn't solve the problem. Why is filter, which is support, not being used?

**Comment by alexreardon** [comment]
@tgormtx this has now been resolved in `version 10` which should be shipping soon. We will no longer require any poly filling for ie 11

#838

**Comment by wuweiweiwu** [comment]
Should the README be updated?

**Comment by alexreardon** [comment]
Yep! PR welcome!
