### ISSUE TITLE
Droppable in position: fixed container on scrollable page

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#757]
If a Droppable or one of it's parents is using `position: fixed` then it will not move with the page during a scroll. This breaks one of our assumptions about how Droppable's work. 

A droppable should be aware if it is in a position:fixed container and ignore any page scroll changes for it's calculations

**Comment by alexreardon** [comment]
Related #529

**Comment by alexreardon** [comment]
We will be shipping a basic version of this in version 10

**Comment by alexreardon** [comment]
Limitation: we will disable window auto scrolling as well as cancelling if we detect a manual window scroll. 

This will allow you to have a functional fixed list with its own scroll

Getting it to work along side a changing page scroll is more difficult. So I’ll create another issue for that work

**Comment by pbrandone** [comment]
@alexreardon I have a fixed positioned bottom drawer to archive some draggable content. Whenever I try to drag something there, the window just scrolls away, messing with the perceived coordinates of this drawer.

Is there any temporary workaround (like disabling auto scroll) or will it be exclusively for version 10? Is there any ETA?

Thanks 👍

**Comment by alexreardon** [comment]
Shipped in [10.0](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)

**Comment by pbrandone** [comment]
@alexreardon cheers 🎉 

I'm not finding anything in the docs about the behaviour of fixed elements vs. the auto-scroll feature.
Imagine a scenario like:
```
---------------------
|                   |
|    dnd columns    |
|  vertical scroll  |
|                   |
---------------------
|     fixed div     |
---------------------
```

Before, when I tried to drag an item from the dnd columns to the fixed div, the auto-scroll would trigger and react-beautiful-dnd's perceived location of my fixed div would get all messed up.

Is this fixed in version 10?

**Comment by pbrandone** [comment]
@alexreardon great work on the release. most of the problems I had in my previous attempt to use this library are pretty much fixed (auto window scroll being the main one).
The window scroll lock works fine now but it seems there's a problem calculating the fixed `Droppable` size.

You can take a look at these examples:
Fixed: http://drops.significa.co/react-beautiful-dnd-fixed1.mp4
Not fixed: http://drops.significa.co/react-beautiful-dnd-fixed2.mp4

As you can see the fixed Droppable isn't correctly detecting `snapshot.isDraggingOver`

Am I missing. anything or is this a bug?

**Comment by pbrandone** [comment]
Just gonna leave this here:
working correctly: https://codesandbox.io/s/nnp9yrrwlp
not working correctly: https://codesandbox.io/s/rw8w0zm7ko

It apparently has something to do with the order of the DOM elements.
Don't have the time to really look into it now, but hopefully these code sandboxes help in some way
