### ISSUE TITLE
How to make multiline item drag drop work

### ISSUE THREAD

**Issue by techhysahil** [atlassian/react-beautiful-dnd#768]
i am not able to multiline item drag and drap work. It's only allowing drag and drop in either direction but i want tags to move around both ways.

I am adding a video link for just showing the problem. In GIF, i am not able to drop item in bottom row. in short Grid drag and drop like feature like this.
http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=1a63mg
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7847056/44709490-671d7e00-aac7-11e8-8819-47a6fbfd69ea.gif)

**Comment by alexreardon** [comment]
We currently do not support grid based layouts #133

**Comment by komagic** [comment]
i created a demo https://codesandbox.io/s/react-grid-drag-k3utz

**Comment by minhnhat1303** [comment]
> i created a demo https://codesandbox.io/s/react-grid-drag-k3utz

great! this is what I really need now
