### ISSUE TITLE
The meta key is incorrect for toggling selection in a group on Windows.

### ISSUE THREAD

**Issue by waynebloss** [atlassian/react-beautiful-dnd#769]
## Bug or feature request?

Bug

### Expected behavior

On Windows, the `Ctrl` key is used to toggle selection in a group. See the behavior of Windows Explorer for an example _(from Windows 95 through Windows 10)_.

### Actual behavior

This library defaults to using the `meta` key which on Windows is the `Windows` key. However, this is completely unusable due to the fact that whenever the `meta/Windows` key is released, Windows displays the start menu, as it should.

### What version of `React` are you using?

^16.3.1

### What version of `react-beautiful-dnd` are you running?

Latest

### What browser are you using?

Chrome

### Demo

[Multi-drag pattern demo](https://react-beautiful-dnd.netlify.com/?selectedKind=Multi%20drag&selectedStory=pattern&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[Documentation](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md#event-handlers) explaining that the `Windows` key is the key that activates "toggling selection in a group".

**Comment by alexreardon** [comment]
Interesting. I based the example off the mac finder experience. 

From the guide:

> #### Event handlers
>
> We perform this action if the user performs a `click` or presses the **enter** <kbd>⏎</kbd> key in addition to holding the the [meta key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey).
>
> Note: On Macintosh keyboards, this is the `⌘ Command` key. On Windows keyboards, this is the Windows key (`⊞ Windows`) - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey)

You are suggesting we use the `ctrl` key rather than the `meta` key? Perhaps the code would need to be a little more sophisticated and conditionally use `meta` or `ctrl` based on environment. You might use `navigator.platform` to do the switch. I would welcome a PR to the guide and the example that backs it to implement this change.
