### ISSUE TITLE
Animated placeholders when transitioning between lists

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#77]
When transitioning between lists there is some snapping that occurs:

- when entering a new list the placeholder snaps to the correct height without animating
- when dropping in a foreign list, the original placeholder in the home list does not animate and disappears instantly when the drop completes

The goal is to have both of these scenarios animated. However, in order to ship #2 it was decided that this feature was not critical enough to hold up the release. The interaction still feels really nice - it would just be even better with animated placeholders.

**Comment by souporserious** [comment]
I'd love to help out here as well if possible. If you have any sort of roadmap or ideas for this I can start a PR.

**Comment by souporserious** [comment]
I landed on this implementation for now which somewhat works, just need to update the dimensions snapshot somehow:

```
function SortableItem({ id, index, children }) {
  return (
    <SortableContainerContext.Consumer>
      {sortableContainerSnapshot => (
        <Draggable draggableId={id} index={index}>
          {(provided, snapshot) => (
            <div>
              <div
                ref={provided.innerRef}
                {...provided.draggableProps}
                {...provided.dragHandleProps}
                style={getItemStyle(
                  snapshot.isDragging,
                  provided.draggableProps.style
                )}
              >
                {children}
              </div>
              {provided.placeholder && (
                <div
                  style={{
                    height: sortableContainerSnapshot.isDraggingOver ? 51 : 0,
                  }}
                >
                  {provided.placeholder}
                </div>
              )}
            </div>
          )}
        </Draggable>
      )}
    </SortableContainerContext.Consumer>
  )
}
```

@alexreardon is there anything exposed right now that would allow me to fire a recalculation of dimensions?

**Comment by souporserious** [comment]
Needs some internal work to clean things up, as well as use React Motion, but pretty cool interaction! 

![animate-on-leave](https://user-images.githubusercontent.com/2762082/36129929-9ea10552-101e-11e8-92c6-8f1f10ab721d.gif)

**Comment by yogaboll** [comment]
I would love to see this fixed. Any progress on this issue?
I can't get @souporserious workaround to function properly since my list-items have differing heights.

**Comment by souporserious** [comment]
@yogaboll you should be able to measure the DOM node and provide that to the height of a wrapper around `provided.placeholder`. The only thing is the drag and drop get's thrown off because the snapshot of the DOM is out of sync with react-beautiful-dnd. Not sure if there is a way to tell it to update that snapshot after the animation completes.

**Comment by yogaboll** [comment]
Thanks, I got it working by measuring the list-item.

Unfortunately, this method causes a couple of new visual glitches so I don't think it's worth it for me.

**Comment by alexreardon** [comment]
I am hoping to see if we can get this working as a part of #8

**Comment by lanefelker** [comment]
Hi @alexreardon, I see #8 was closed. Was this included in that change? I'm still experiencing the snapping placeholders when dragging between lists

**Comment by alexreardon** [comment]
Aye, this has not been fixed - but I hope to after `next` #719  lands

**Comment by woohling** [comment]
It seems like I forgot to take into scrollable droppable list into account...
I think the default behavior should be when you drag over a foreign list which doesn't have a scrollbar, the active area should expand to the length(or width depending on droppable direction) of the draggable, but when there's a scrollbar existed already, there's no need to expand the active area.

**Comment by alexreardon** [comment]
## Behaviour (wip):

General rule: there should only ever be one gap in all lists to show where a `Draggable` would end up if dropped

### Where is the gap?

(this is already what we have today)

- Over home droppable: in the home list
- Over foreign droppable: in the foreign list
- Over no droppable: in the home list in the lift position (this is where the item would end up if dropped)

### Animation behaviour

#### Home droppable

- When lifting: placeholder will be inserted into home location. No animation of placeholder
- When moving into foreign list: animate placeholder collapse
- When moving from foreign list to no droppable: animate placeholder expansion
- When moving from foreign list to home droppable: animate placeholder expansion

#### Foreign droppable

- When moving into foreign list: animate placeholder expansion
- When moving out of foreign list: animate placeholder collapse

### Performance

Ideally, we render as few `Droppables` as possible. We might need to animate a mount / unmount for foreign lists in order to achieve this

**Comment by alexreardon** [comment]
Things still to overcome:

- strange animations in home list when changing foreign list
- margin collapsing related to placeholder removal
- colouring home list in examples to indicate home (easy to implement - but i want to see how it looks)

**Comment by alexreardon** [comment]
## Early prototype

It looks great! 👍 

![animate-movement](https://user-images.githubusercontent.com/2182637/50124649-b9262180-02b9-11e9-9bf4-0d892e7cdf17.gif)

**Comment by alexreardon** [comment]
Here is a prototype that is showing great potential: https://deploy-preview-1086--react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple&full=0&addons=0&stories=1&panelRight=0

**Comment by alexreardon** [comment]
It is hard to get looking smooth across many use cases

**Comment by alexlouden** [comment]
Looks great! Very excited for this - keep up the amazing work! 😃

**Comment by alexreardon** [comment]
This was released in [10.1](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0)

**Comment by alexreardon** [comment]
#1096

**Comment by Yggdrasilqh** [comment]
> Here is a prototype that is showing great potential: https://deploy-preview-1086--react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple&full=0&addons=0&stories=1&panelRight=0

Hello, where can I get the source code of this sample ?

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/board/board.jsx
