### ISSUE TITLE
react 15

### ISSUE THREAD

**Issue by zhuhongyan** [atlassian/react-beautiful-dnd#772]
## Bug or feature request?
 where could I find the demo apply react@15
Compatibility problem or Syntax error？😂

![image](https://user-images.githubusercontent.com/20653605/44828990-0ae46680-ac4d-11e8-91ad-63e1aed60b9e.png)

### Demo
https://codesandbox.io/s/ox70z2ln95

**Comment by alexreardon** [comment]
We are not maintaining compatibility with older versions of React. I think 6.x was the last one compatible with react 15
