### ISSUE TITLE
Is that possible to make a Draggable also a Droppable ?

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#778]
Hi teams, i'm trying to implement a drag an drop feature for files list, especially drag and drop a file inside a folder, like that : (the image is a screenshot from Google Drive).

![image](https://user-images.githubusercontent.com/25119847/44934239-707b4480-ad6c-11e8-98dc-aeec1a273ae6.png)

What should be the best way to do it with React-Dnd ? (Letting the first element appear with low opacity, and show the draging element as dropable on the other element)

Thanks a lot !

**Comment by alexreardon** [comment]
You can get `react-beautiful-dnd` to work with the file drag and drop api (we do it internally) but there is currently no published examples. For now I would suggest using another library.

**Comment by lindekaer** [comment]
@Aarbel @alexreardon 
Hi guys! Any ideas/tips/trick how to make a `draggable` work as a `droppable` too?

**Comment by Aarbel** [comment]
Put a droppable inside a draggable

**Comment by alexreardon** [comment]
See our new combining feature that we shipped in [10.0](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)

🚀
