### ISSUE TITLE
Optimise bundle

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#78]
Right how the generated source code is fairly simple: just run everything through babel. However, we could use tools like [rollup](https://rollupjs.org/) and [prepack](https://github.com/facebook/prepack) to optimise the bundle before it is ever consumed.

**Comment by alexreardon** [comment]
I am keen to get your thoughts @treshugart @thejameskyle @lukebatchelor

**Comment by treshugart** [comment]
I attempted adding Rollup in #81. There's still some issues that are mentioned in the tasks in the issue.

**Comment by alexreardon** [comment]
Do you think we need a umd build? I was thinking of using rollup for the standard es build

**Comment by treshugart** [comment]
If you want a standard es build then you probably won't be using Rollup. You'd just babel with `{ modules: false }`, right?

**Comment by alexreardon** [comment]
I guess so? I am fairly new to the bundling a library thing. let's chat on monday

**Comment by alexreardon** [comment]
For now we will let consumers worry about optimising their bundle
