### ISSUE TITLE
issue Dropping vertical Draggable to horizontal Droppable

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#787]
Hi back @atlassian teams,

I try to drop a vertical element (with a width of 100%) on a Droppable which is in `horizontal mode`.

# Screenshots 
## Step 1 - I want to drag the element `I’m the deep deep directory` (Draggable) on the `Beautifull mexican directory` (Droppable) element
![image](https://user-images.githubusercontent.com/25119847/45170628-96876580-b200-11e8-9a5f-8497bab2d764.png)
## Step 2 - nothing happens when the top left of Draggable is over the Droppable
![image](https://user-images.githubusercontent.com/25119847/45170843-22998d00-b201-11e8-9efa-6e2f70956c89.png)
## Step 3 - if i drag the Draggable more on the left of the screen, the Droppable's "isDraggingOver" prop becomes true (in that case i change the color to blue) 
![image](https://user-images.githubusercontent.com/25119847/45170987-8ae86e80-b201-11e8-8a88-41791f3a2a7f.png)

# Conclusion
It seems that the Droppable listens to the first center of Draggable before the Drag, and not exactly the Draggable element during the Drag.

Do you know how i could fix that ? (= when top left of Draggable element is over a Droppable element, "isDraggingOver" is true )

Again, thanks a lot for your help and this powerfull library

**Comment by Aarbel** [comment]
After some other test, the purpose of this issue is : how to set that a Droppable listens to `top left` of a Draggable to trigger `isDraggingOver`

**Comment by alexreardon** [comment]
Can you please create an independent example for us to play with? Here is our boilerplate: https://codesandbox.io/s/k260nyxq9v

**Comment by Aarbel** [comment]
https://codesandbox.io/s/l7xpx18p29

Try to drag an item into yellow Droppable.
=> as you can see i change the `Droppable width` if it's dragging. Then it gets quite hard to drop the yellow Droppable.

**Comment by Aarbel** [comment]
@alexreardon what do you think about it ?

**Comment by Aarbel** [comment]
@alexreardon, this issue is blocking me right now, do you know a way to fix it ? Thanks a lot for your time 👐

**Comment by Aarbel** [comment]
It's quiet here.
Here is a slice of pizza for who can help me. 🍕

Thanks a lot !

**Comment by Aarbel** [comment]
Still blocked by this issues, @alexreardon absolutely no solutions ?

**Comment by Aarbel** [comment]
@alexreardon do you know a way to hack it ?

**Comment by Aarbel** [comment]
Send me your work address, i will deliver you a pizza ;)

**Comment by alexreardon** [comment]
Google Atlassian Sydney 😅

**Comment by Aarbel** [comment]
Here ? Do you think i can find a workaround for my issue ? :)
![image](https://user-images.githubusercontent.com/25119847/48678455-ee890380-eb83-11e8-815d-2905cdcb77ff.png)

**Comment by abnish07** [comment]
for me, When I set Droppable direction 'vertically', is works vertically, and when I set direction to 'horizontally', it works for me horizontally. But I want Both directions  work for me. How it can be possible? 
I am attaching the screen short
![question plate](https://user-images.githubusercontent.com/59315687/96439346-563ea200-1224-11eb-8faa-2e3bb6245caf.png)
