### ISSUE TITLE
Add a real browser test

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#79]
I am not sure if we need this - but I thought I would raise it anyway

Generally I am quite against browser tests. However, I think it could be worthwhile having one smoke test that runs in a real browser. I am fairly keen to use [puppeteer](https://github.com/GoogleChrome/puppeteer) for this one. It would not need to run in all browsers. This is purely just a small smoke test.

Criteria

- Would need to be able to run on travis (I think if we run chrome in headless mode this should be fine)
- Needs to be crazy simple with minimal config - I do not want to spend heaps of time maintaining this.

**Comment by Judahmeek** [comment]
As a new user, I'd love to know your suggestions on best options for integration testing with `react-beautiful-dnd`, specifically the dragging of an element from one list to another. Do you know of anyone who has successfully done this with Puppeteer or another headless browser like Selenium Chrome?

**Comment by alexreardon** [comment]
As long as you can trigger mouse events then you should be fine to use any browser driver @Judahmeek. For what is it worth - Puppeteer looks amazing.

In a previous project that used a precursor to this library we have integration tests setup that used webdriver

**Comment by alexreardon** [comment]
Well done @RajaBellebon 
#407
