### ISSUE TITLE
allow `dnd` on interactive elements based on distance

### ISSUE THREAD

**Issue by cusxio** [atlassian/react-beautiful-dnd#790]
## Question/Feature Request

I am aware that `react-beautiful-dnd` currently blocks dragging of [interactive elements](https://github.com/atlassian/react-beautiful-dnd#interactive-child-elements-within-a-draggable) by default.

However, while I was reading the documentation, I couldn't help but wonder why the [same approach](
https://github.com/atlassian/react-beautiful-dnd#sloppy-clicks-and-click-prevention-) for handling anchor tags, couldn't be used for interactive elements? 

i.e. If the user's cursor moved passed a certain threshold (distance), a drag event is triggered. 

## Use case

Currently I have a `contenteditable` `div` in a TODO list, and the TODO list can't be sorted, unless `contenteditable=false`.

**Comment by alexreardon** [comment]
This is a bit tricky as some interactive elements have keyboard behaviour and we cannot know if the keyboard input is for the interactive element or the drag

**Comment by alexreardon** [comment]
Given that interactive elements have their own keyboard behaviour, this one will be tricky to achieve in a generic way. I would recommend turning off our interactive element blocking and patch the provided event listeners
