### ISSUE TITLE
Mobile DND issue

### ISSUE THREAD

**Issue by nikitaulshin** [atlassian/react-beautiful-dnd#791]
Hello!

I faced a problem that when I drag the cards between the columns on the mobile device, the container does not scroll automatically.
I read the documentation and found that in the [example for mobile devices](https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple) this error is reproduced.

Tell me please, is there really such a problem? Where can I track it?

**Comment by lukebatchelor** [comment]
Can confirm.

Afaik, horizontal autoscrolling is not supported, it's only for scrolling down a list, but Alex would deffs be the best person to answer.

**Comment by alexreardon** [comment]
Auto scrolling horizontally should work fine. I am unable to reproduce this
issue on my iOS device

**Comment by nikitaulshin** [comment]
Updating my meta fixed this issue for me.
I added following rules: maximum-scale=1.0, user-scalable=no
My meta now looks like this: 

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0, user-scalable=no">

Thanks for your help!
