### ISSUE TITLE
Feature Request: Simple Drop Zone

### ISSUE THREAD

**Issue by abettadapur** [atlassian/react-beautiful-dnd#795]
## Bug or feature request?

Feature Request

It's possible that this does not fit within the philosophy of the library, but I figured I'd ask to make sure.

I have a grid of `Droppable` elements, with rows that can be collapsed.
![image](https://user-images.githubusercontent.com/2415669/45502503-0170f900-b739-11e8-8b9e-ddaef00184b2.png)

I wanted to make the `RowHeader` component a `Droppable`, where if I dropped an item there, it would move to the same column of the next row. The animation however, makes this look really strange.

![beautiful-dnd-zone](https://user-images.githubusercontent.com/2415669/45502630-57de3780-b739-11e8-9c9b-add021ff0be6.gif)

Ideally, I would make this a `DropZone`, where the item doesn't have a destination, but is rather 'swallowed' by the zone. This probably violates 'Application 1' in the guiding principles, but I saw this scenario as sort of a special case.

What are your thoughts?

**Comment by abettadapur** [comment]
Another, perhaps too specific solution, would be to specify a `Droppable` destination. For example, the `RowHeader` component could 'redirect' drops to another `Droppable` id it knows about.

**Comment by alexreardon** [comment]
The drop animation should just work in `next`. And if it does not, you have the ability to more tightly control or disable the drop animation entirely in the new version


If that doesn't work, then in `next` you could try

- make your target a Droppable with a single `Draggable`. Then set `isCombineEnabled` to true for the `Droppable`. This will allow the `Draggable` to be combined with. However, there might not be the ability to disable the reordering of that item so it might be a bit strange...

**Comment by abettadapur** [comment]
Ok ill try that. Thanks

**Comment by alexreardon** [comment]
I'll close this as a part of #719

**Comment by alexreardon** [comment]
#823
