### ISSUE TITLE
Can't use in react-frame-component

### ISSUE THREAD

**Issue by jdillick** [atlassian/react-beautiful-dnd#796]
## Bug or feature request?

Bug

### Expected behavior
When binding react-beautiful-dnd into an iframe portal, for the functionality to continue to work inside the iframe.

### Actual behavior

You will get a number of Invariant errors, such as: "provided.innerRef has not been provided with a HTMLElement."

### Steps to reproduce

```jsx
import React from 'react';
import MyDNDComponent from './MyDNDComponent';
import Frame from 'react-frame-component';

export default (props) => {
  return (<Frame><MyDNDComponent /></Frame>);
}; 
```

### What version of `React` are you using?

^16.4.1

### What version of `react-beautiful-dnd` are you running?

^9.0.1

### What browser are you using?

Chrome latest

### Demo

Notice that when instanceof is used to check an element in the iframe by the parent window, it will fail. Duck typing these checks will bring back the functionality while retaining some manner of type safety.

```
document.write('<iframe id="testing-iframe"></iframe>')

const doc = document.getElementById('testing-iframe').contentDocument;
doc.open('text/html', 'replace');
doc.write('<div id="internal-html-element"></div>');
doc.close();
doc.body.children[0] instanceof HTMLElement
// false

doc.body.children[0] instanceof document.getElementById('testing-iframe').contentWindow.HTMLElement
// true
```

**Comment by alexreardon** [comment]
Each iframe get's it's own context / objects. And instanceof just checks the prototype chain - which is why this is failing.

Some sort of duck typing could be okay. Although I think it should be hidden behind some helpers and the helpers should have the correct flow types so that the library thinks that it is a HTMLElement

**Comment by alexreardon** [comment]
Portaling something into an iframe is a fairly interesting use case

**Comment by alexreardon** [comment]
I would be keen to see the logic in #797 pulled into some helpers to hide this crazy!

**Comment by jamesmcintyre** [comment]
Just adding that the @jdillick 's branch (https://github.com/jdillick/react-beautiful-dnd/tree/bugfix/duck-type-dom-objects) worked for me (I'm using react-frame-component).

**Comment by camdagr8** [comment]
@alexreardon maybe accept @jdillick 's fix and then request for the helpers?

**Comment by alexreardon** [comment]
We will look at getting something like this in soon

**Comment by minhtranite** [comment]
That issue block me upgrade to from version 7 to newer.

**Comment by vladkucherov** [comment]
I have the same issue

**Comment by alexreardon** [comment]
I think if we had a small, accurate and shared duck type checker this would be fine to add!

**Comment by alexreardon** [comment]
I am thinking something like this:

```js
const isHTMLElement = (el: mixed): boolean => {
 return Boolean(el && el.prototype.hasOwnProperty('something');
}
```

Just need to find something unique to HTMLElement that is fairly trival to compute: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

**Comment by alexreardon** [comment]
This should be possible now #1067

**Comment by minhtranite** [comment]
Hi @alexreardon 

I'm trying to update to v12 and it seam that it not work react-frame-component.

![image](https://user-images.githubusercontent.com/5418628/71069392-3628f700-21ab-11ea-83d1-7dc77e14975c.png)


I create a sample here: https://codesandbox.io/s/vertical-list-psw70

**Comment by Steve1820** [comment]
Same here. Cannot use this library in an iframe.

**Comment by Steve1820** [comment]
Ended up using this fork: react-beautiful-dnd-iframe

**Comment by jdillick** [comment]
I'd suggest opening a new ticket for this, because the issue is closed it's probably not noticed by anyone, and the root cause of this regression appears to be different from the original problem.
