### ISSUE TITLE
Can a component be both draggable and droppable at the same time ? 

### ISSUE THREAD

**Issue by justduy** [atlassian/react-beautiful-dnd#800]
I would like to know if this is possible, for a component to be both draggable and droppable. The use case can for example be a file tree where folders are both droppable and draggables. I've tried to search for the answer, but haven't found anything yet.

**Comment by alexreardon** [comment]
We do not support that. Although, the new `combining` API will allow you to combine Draggables. That might get you where you want to #511

**Comment by alexreardon** [comment]
The same component being a draggable and a droppable - i have not tested it. It probably will not work as we expect droppable's to stay in the same place during a drag
