### ISSUE TITLE
Text inputs should loose focus when a drag starts

### ISSUE THREAD

**Issue by tslocke** [atlassian/react-beautiful-dnd#801]
## Bug or feature request?

Bug

### Expected behavior

If a text input, textarea or contenteditable element has the focus, it should loose the focus, and the onblur event should fire, when starting a drag and drop operation.

Note this is not just a pedantic thing - it's actually causing a bigger bug in my app, which needs to do some clean-up when on-blur fires, before any other state changes happen in the app.

### Actual behavior

The focus remains in the text input during the drag, with the caret visible, and remains there after the drag.

### Steps to reproduce

Visit [nested interactive elements stress test](https://react-beautiful-dnd.netlify.com/?selectedKind=nested%20interative%20elements&selectedStory=stress%20test&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), focus one of the text inputs or textareas, start a drag-and-drop

### What version of `React` are you using?

Your version (storybook)

### What version of `react-beautiful-dnd` are you running?

Your version (storybook)

### What browser are you using?

Chrome 68

### Demo

(see steps to repro)

**Comment by alexreardon** [comment]
We do not force a `drag-handle` to get focus when it drags. If it has focus we work hard to maintain it though.

So what you can do is simply do an `element.focus()` when you know the drag is starting to ensure the handle as focus rather than the element (of you can just blur the focus so that any inputs loose it)

**Comment by gadiGuesty** [comment]
@alexreardon can you elaborate and show a small example how to do it?

**Comment by GraemeFulton** [comment]
You can add something liek this on the drag handle:
```
 {/* Drag handle */}
<div onMouseDown={(e)=>{
    e.target.focus({preventScroll: true})
}}>
```
if `e.target.focus` doesnt' work, do it on the parent of the drag handle - jquery exampel: `$(e.target).parent().trigger('focus')`

**Comment by boneyao** [comment]
> @alexreardon can you elaborate and show a small example how to do it?

https://codesandbox.io/s/vertical-list-forked-wdk1r?file=/index.js

I fixed it, use this code.
`
 {/* Drag handle */}
<div  onMouseDown={(e)=>{
     if(document.activeElement.tagName=="TEXTAREA") {
        document.activeElement.blur();
     }
}} />
`

**Comment by GraemeFulton** [comment]
@boneyao ooh that's a great idea, thanks for sharing!
