### ISSUE TITLE
React 16.5 + dev tools performance drop

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#808]
I have noticed that the `new profiler` is causing significant performance drops when running in `process.env.NODE_ENV !== 'production`. These drops occur even if you are not running the profiler. 

I have not tested, but I expect this would not impact performance builds. It looks like there is an issue with the profiler. You can track progress on that issue here: https://github.com/facebook/react-devtools/issues/1106

**Comment by alexreardon** [comment]
Until the underlying issue is fixed, I am thinking of logging a warning if we detect react 16.5+. Thoughts @lukebatchelor ?

**Comment by pixelass** [comment]
Thank you. This helped me understand the lag I'm experiencing.

I can confirm that with `react 16.5.2` the performance goes down drastically when in dev mode.


### Dev

<img width="943" alt="screen shot 2018-10-04 at 02 35 08" src="https://user-images.githubusercontent.com/1148334/46446724-37c0f780-c77e-11e8-8703-01c56b6dfaec.png">

### Prod

<img width="1018" alt="screen shot 2018-10-04 at 02 34 28" src="https://user-images.githubusercontent.com/1148334/46446725-37c0f780-c77e-11e8-8c32-2a8fe078ddf2.png">

**Comment by alexreardon** [comment]
Yep. There seems to be issues with the react profiler ☹️

**Comment by alexreardon** [comment]
This issue seems to have gone away 🙄
