### ISSUE TITLE
Unit testing React-beautiful-dnd components

### ISSUE THREAD

**Issue by manguesh** [atlassian/react-beautiful-dnd#814]
Feature request

We were trying to unit test components built with this module using jest/enzyme. We noticed that whenever we update the props of the component, somehow it would not work.

Example:

            const wrapper = mount(<ProductsList {...props} />);

            const newProps = {
                ...wrapper.props(),
                products: [
                    {
                        id: 111,
                        solutionId: 456,
                        technology: 'tech 1',
                    },
                ],
            };

            wrapper.setProps(newProps)

We looked at the react-dnd and it seems to provide a testing backend:

https://github.com/react-dnd/react-dnd-test-backend

Is there any similar module for testing components containing react-beautiful-dnd? What approach can we follow besides this?

**Comment by alexreardon** [comment]
Happy for input on this one! There are a lot of ways of doing this, but there is no recommended pattern for now

#623
