### ISSUE TITLE
Where did you find these beautiful AT quotes ?

### ISSUE THREAD

**Issue by tim-field** [atlassian/react-beautiful-dnd#816]
https://github.com/atlassian/react-beautiful-dnd/blob/fc4e6380c63c9b394119937d312a2693f4e5a13b/stories/src/data.js#L53

**Comment by alexreardon** [comment]
I think these ones:

- https://www.ranker.com/list/best-adventure-time-quotes/crystal-brackett
- http://adventuretime.wikia.com/wiki/Category:Quotes

There might have been others too!

😎
