### ISSUE TITLE
Strongable droppable rules

### ISSUE THREAD

**Issue by bustEXZ** [atlassian/react-beautiful-dnd#822]
Hi there!

In docs i see:

> Technically you do not need to use type and do all of your conditional drop logic with the isDropDisabled **function**. The type parameter is a convenient shortcut for a common use case.

But **isDropDisabled** is only boolean option. How can i create hard rules for droppable components?

Scheema what i need:
Rows i can drag: REGULAR, GROUP, VIRTUAL (has different logic to append into container)
Droppable containers (SOURCE): 4 containers. GROUP and VIRTUAL can drop only on 1-3 containers, REGULAR can drop into all of 4 containers. 
In droppable container could be droped GROUP. In GROUP i can drop only REGULAR rows. 

I realized all this logic, except for the last paragraph.

How can i do this? Dont see examples about this, only "lite" list's rules.

**Comment by alexreardon** [comment]
You can create your own complex rules, as long as the result is eventually a boolean.

[This lesson](https://egghead.io/lessons/react-conditionally-allow-movement-using-react-beautiful-dnd-draggable-and-droppable-props) in our getting started course should be of assistance to you

**Comment by alexreardon** [comment]
about the ~2:50m mark 👍
