### ISSUE TITLE
Is it possible to reverse the positioning?

### ISSUE THREAD

**Issue by lonelydatum** [atlassian/react-beautiful-dnd#825]
Is it possible to reverse the positioning when stacked on top of each other. For example I'd like an array of ["a", "b", "c"] 

To be represented like this.

|------------------|
|------- C --------|
|------------------|

|------------------|
|------- B --------|
|------------------|

|------------------|
|------- A --------|
|------------------|

I know I can simple reorder the array but doing so will cause other side effects in the app. 

Thank you so much.

**Comment by alexreardon** [comment]
You could do something like this:

```js
this.state.items.reverse().map((item, index) => {
	<Item key={item.id} index={index} item={item} />
});
```

And then in your hooks, eg `onDragEnd`, just know that all the index's are reversed

**Comment by anthify** [comment]
@lonelydatum to handle the reversed ordering, if required, you can do the following;

```javascript
    const reorderReversedArray = (arr, fromIndex, toIndex) => {
      const element = arr[fromIndex];
      arr.splice(arr.length - fromIndex - 1, 1);
      arr.splice(arr.length - toIndex - 1, 0, element);
      return arr;
    }

    const orderedArray = reorderReversedArray([...reversedArray], result.source.index, result.destination.index);

```
