### ISSUE TITLE
Turning an interactive draggable into a controlled component

### ISSUE THREAD

**Issue by mjdavidson** [atlassian/react-beautiful-dnd#829]
I have a bunch of 'items' which have a name, some text and some optional check-able fields.

![image](https://user-images.githubusercontent.com/12488396/46116763-ffcb2900-c240-11e8-9459-272bea6b296e.png)
I want to turn these check-boxes into controlled inputs.

This is how my items are currently setup:
![image](https://user-images.githubusercontent.com/12488396/46116834-44ef5b00-c241-11e8-97cb-0c7e3877d9a6.png)
and this is how they are displayed: 
![image](https://user-images.githubusercontent.com/12488396/46116869-78ca8080-c241-11e8-9703-3a4c95b6c13f.png)

**Comment by alexreardon** [comment]
I am not sure what you are asking 😊

**Comment by mjdavidson** [comment]
I want to be able to manage the state of my checkboxes which are inside a Draggable component

**Comment by alexreardon** [comment]
I think this is what you are after: https://github.com/atlassian/react-beautiful-dnd#interactive-child-elements-within-a-draggable

**Comment by mjdavidson** [comment]
Not really! But I think I have a solution thanks @alexreardon 
Long week at work ...

**Comment by alexreardon** [comment]
Ah okay! Well, it would be great to find out what your issue was and how you got around it (at least for other people to search for in the future)

**Comment by mjdavidson** [comment]
I want to be able to know what the state of each of the check boxes is. In general you do this by having each controlled elements as a top-level property of the state. It's a little harder to do with the checkbox being inside an object inside an array inside an object inside an array. So what I will do is when I get all the different items from the sever I will iterate through each of them 
![image](https://user-images.githubusercontent.com/12488396/46191279-3042be00-c33a-11e8-9357-4db907a06ec8.png)
and set up a state for each check box, then dynamically assign each checkbox it's state and onchange handler.
Then when I'm sending the information back to the server I will have to work out how to bring it all back into one object.
