### ISSUE TITLE
Cancel drag when the page looses focus

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#83]
It makes sense to cancel a current drag if the page looses focus or visibility (page visiblity api)

**Comment by grady-lad** [comment]
Hey @alexreardon I could take a look at this if it is still available?

**Comment by alexreardon** [comment]
Yes! Go for it

**Comment by alexreardon** [comment]
You will need to add a visibilty change event listener to each of the
window event bindings in each drag sensor

**Comment by alexreardon** [comment]
Ideally it would use the correct visibility change event for each browser

**Comment by alexreardon** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
