### ISSUE TITLE
but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.

### ISSUE THREAD

**Issue by Sam-Houlahan** [atlassian/react-beautiful-dnd#831]
Currently trying to build a dnd table for a project and i am getting the following error:

```Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DragHandle`.```

I haven't pasted my code as i get this exact error even when using all the code from https://codesandbox.io/s/k260nyxq9v. I am using React version 16.4.1.

**Comment by alexreardon** [comment]
You get this exact error... hmmm

Sounds like you are not importing a component correctly.

`import {Draggable} from 'react-beautiful-dnd`

Try logging out your imported components. It looks like you are trying to render a component which is null

**Comment by alexreardon** [comment]
What ended up being your issue?

**Comment by rohan-deshpande** [comment]
I'm also experiencing this using `"react-beautiful-dnd": "^9.0.2"` and `"react": "15.4.0"` in an ES5 project. Just set up some test code just like https://codesandbox.io/s/v3p0q71qn5 basically:

```javascript
var Dnd = window.ReactBeautifulDnd;
var Card = React.createClass({
  render: function () {
    var provided = this.props;
    var innerRef = provided.innerRef;

    return (
      <div
        {...provided.draggableProps}
        {...provided.dragHandleProps}
        ref={innerRef}
      >
        Card
      </div>
    );
  }
});

var List = React.createClass({
  render: function () {
    var provided = this.props.provided;
    var children = this.props.children;
    var innerRef = provided.innerRef;

    return (
      <div {...provided.droppableProps} ref={innerRef}>
        {children}
      </div>
    );
  }
});

var Board = React.createClass({
  render: function () {
    return (
      <div>
        <Dnd.Droppable droppableId={component} >
          {function (provided) {
            return (
              <List provided={provided}>
                <Dnd.Draggable draggableId={'card'}>
                  {function (provided) {
                    return <Card provided={provided} />;
                  }}
                </Dnd.Draggable>
                {provided.placeholder}
              </List>
            );
          }}
        </Dnd.Droppable>
      </div>
    );
  }
});
```

I get the exact same error

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `DragHandle`.
```

**Comment by alexreardon** [comment]
We are not supporting react 15

**Comment by alexreardon** [comment]
This issue keeps coming up. Perhaps it is worth adding a dev only warning

**Comment by rohan-deshpande** [comment]
Heya, thanks for the quick reply, I updated to `react@16.1.0` and the issue is persisting 

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `DragHandle`.
```
I'll try to set up a sandbox to see if it's not something else

**Comment by alexreardon** [comment]
That does not meet our minimum supported version. Check the package.json. I
think 16.3 is the minimum

**Comment by djsmacker01** [comment]
I also got same error.
