### ISSUE TITLE
Cand drop into draggable droppable

### ISSUE THREAD

**Issue by bustEXZ** [atlassian/react-beautiful-dnd#832]
Hi there. Can i do like this with make Draggable with Droppable inside
Example: https://codesandbox.io/s/p358pq3zz7

Droppable in group doesn't work and dont trigger snapshot.isDraggingOver

**Comment by alexreardon** [comment]
Here is an example that shows off the effect I think you are after:

https://react-beautiful-dnd.netlify.com/?selectedKind=complex%20vertical%20list&selectedStory=nested%20vertical%20lists&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Feel free to take a look at how we got it working :)

Let me know if you have any other questions

**Comment by bustEXZ** [comment]
@alexreardon If you check your example and delete "type" on draggable and droppable, you see what they are not working correctly
