### ISSUE TITLE
Ship version 10!

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#838]
Lots going out in version 10, I'll use this issue as a good point to tag things going out

**Comment by alexreardon** [comment]
We have now shipped an alpha. In order to simply support large projects, we have released the alpha under a new package name: `react-beautiful-dnd-next`

`react-beautiful-dnd-next@10.0.0-alpha.1`

I will try to update here. 

As mentioned, the release is still alpha. So keep that in mind!

The API for currently supported use cases should remain mostly unchanged. I will be doing extensive upgrade notes as we move closer to the release

**Comment by alexreardon** [comment]
`react-beautiful-dnd-next@10.0.0-alpha.2` is now out

**Comment by alexreardon** [comment]
I have a big todo list on my own `trello` board so i'll keep chipping away on things there.

My current thinking is that a stable release is 1-2 weeks away

**Comment by alexreardon** [comment]
`react-beautiful-dnd-next@10.0.0-alpha.3` is out with a new `Draggable` > `payload` prop /cc @Frozenlock

**Comment by alexreardon** [comment]
I have taken the `payload` value and prop out for now pending discussion in #498

**Comment by torre76** [comment]
Hi @alexreardon, will be #484 included in this release?

**Comment by bnewcomer** [comment]
Will #511 (grouping/combining) be included? Any timeline updates?

**Comment by alexreardon** [comment]
Yes #511 is included. There are also a lot of other things that are not listed here right now

**Comment by alexreardon** [comment]
#484

**Comment by alexreardon** [comment]
`10.0.0-alpha.4` is now out!

`yarn add react-beautiful-dnd-next@10.0.0-alpha.4` to give it a go

**Comment by alexreardon** [comment]
Descoped: #331 

> Sadly we will no longer be shipping this in version 10 #838
>
> After testing I continued to run into scenarios that would require additional sophisticated logic. They include:
> 
> - moving to an invisible logic in a scroll container
> - moving which changes the max scroll of the window
>
> We will look to this as a feature (minor) release post v10

**Comment by nicubarbaros** [comment]
> #484

@alexreardon Is that an YES? 

http://gph.is/1R12N2Z

**Comment by alexreardon** [comment]
`react-beautiful-dnd-next@10.0.0-alpha.5` is now out

It contains a few minor bug fixes

**Comment by alexreardon** [comment]
https://github.com/rokborf/natural-drag-animation-rbdnd/issues/2

**Comment by alexreardon** [comment]
Getting very close to all the tests passing:

```
Tests:       28 failed, 1219 passed, 1247 total
```

**Comment by alexreardon** [comment]
`react-beautiful-dnd-next@10.0.0-beta.1 is now out`

We have moved to `beta` releases as the build is now passing

![builds-passing](https://user-images.githubusercontent.com/2182637/47883580-9fec2180-de81-11e8-8cf8-5d51fb84b8ee.PNG)

**Comment by alexreardon** [comment]
<img width="489" alt="screen shot 2018-11-02 at 12 17 27 pm" src="https://user-images.githubusercontent.com/2182637/47888589-658e7e80-de99-11e8-9f2e-0d4f5181f5e1.png">

I have spend 4hrs + trying to overcome a flakey test. That is now resolved 👍

**Comment by alexreardon** [comment]
Up to now I have been working off a Trello board. I'll now move a todo list here to increase visibility:

### Code

- [ ] ensure placeholder in `Droppable` is hidden during recollection
- [ ] fix x2 issues that Balaz has found
- [ ] upgrade `flow` in `tiny-invariant`, `css-box-model` and `memoize-one`. Ensure `css-box-model` is on a matching version of `tiny-invariant` for kb savings
- [ ] Investigate #764 
- [ ] tests for combine screen reader messaging

### Docs

- [ ] create combining guide
- [ ] update types
- [ ] rename `hooks` to `lifecycle callbacks` to avoid name clashing with new react hooks
- [ ] update `README` with latest types
- [ ] add section about dev messaging
- [ ] fill in tree example on dynamic guide
- [ ] write release notes
- [ ] improve dynamic additions docs
- [ ] add section on IE11 and ponyfills
- [ ] add section on fixed lists
- [ ] add *limitations* section: 

- no margin collapsing between items
- no negative margins on the main axis of a list
- etc

### Examples

- [ ] add example for combine with list and board
- [ ] for `Draggable` to foreign list


### Post-release

- [ ] Write blog "Grabbing the flame 🔥"
- [ ] Update codesandbox examples to use latest version

**Comment by alexreardon** [comment]
`react-beautiful-dnd-next@10.0.0-beta.2` is now out. It features some fixes on our dynamic additions code path

**Comment by marvinjaworski** [comment]
Hey @alexreardon,
I need the onBeforeDragStart function you work on, it's possible in react-beautiful-dnd-next@10.0.0-beta.3 to use this function?

And when does the feature come in react-beautiful-dnd?

**Comment by alexreardon** [comment]
This has now shipped! [See version 10 release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)

**Comment by nicubarbaros** [comment]
Wow, congrats @alexreardon and the team. Cannot wait to upgrade and use that sexy dynamic add/remove feature. The combine feature looks sick!

**Comment by alexreardon** [comment]
Thanks @tjramage! I appreciate your encouragement!
