### ISSUE TITLE
Problem with strict peerDependency

### ISSUE THREAD

**Issue by pofigizm** [atlassian/react-beautiful-dnd#84]
Firstly, thanks for this component, it's great.

Why this component has strict peerDependency react `15.6.1`?
Have you real causes for it?
Could it be changed to somthing like `>=15.4.0`?
We cannot use your component if we have other react version.
We very disappointed about it.

Thanks.

**Comment by alexreardon** [comment]
We can totally make it a fuzzy version. I was hoping to change it but forgot. Any reason you want it to go back to 15.4? 15.5 seems like a better way to go https://github.com/facebook/react/blob/master/CHANGELOG.md

**Comment by pofigizm** [comment]
We have big project and we use version 15.4.
I didn't find any changes in react since 15.4 which can affect your component.
You increase users if you have milder restrictions.

All tests passed with react 14.4, I have checked.
It can't affect existed users because they have newer version of react.

Could I made PR with this? ;)

**Comment by alexreardon** [comment]
If all the tests are passing 15.4 sounds fine. Can you please also check the supported browsers that it is all good?
