### ISSUE TITLE
Dragging elements into nested droppables with different types

### ISSUE THREAD

**Issue by martenwallewein** [atlassian/react-beautiful-dnd#847]
## Bug or feature request?

I have a list of source elements that I want to drag into different nested droppables. To also move elements between those droppables, I added the **type** prop to them (as mentioned in the doc). 

Is there a way to allow dragging elements from one list to droppables with different types? 

Here is a small codebox sample: https://codesandbox.io/s/0xovozqj5w

I would offer you to make a PR if we find a solution for that and changes have to be made.

### Expected behavior
Support multiple types for draggables or some kind of regular expression like type={"target-list-*}.

### Actual behavior
Only one type is possible.

### What version of `React` are you using?
16.5.0

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Chromium Version 69.0.3497.100 (Offizieller Build) Arch Linux (64-Bit)

### Demo
https://codesandbox.io/s/0xovozqj5w

**Comment by martenwallewein** [comment]
I tried adding the isDropDisabled={false} prop to the droppables, but nothing changed.

**Comment by alexreardon** [comment]
> Is there a way to allow dragging elements from one list to droppables with different types?

Nope. Right now we only support one type. You could *conditionally* use `isDropDisabled` to have more complex rules

**Comment by alexreardon** [comment]
People have talked about `type` wildcards before... i am concerned it would be too hard to reason about when we already have `isDropDisabled`

**Comment by martenwallewein** [comment]
Okay, I got duplicated droppable ids in the nested droppables, nevermind... isDropDisabled is working fine. Thank you for your help!
