### ISSUE TITLE
Grabbing the top element should not make the list instantly fly off to the top

### ISSUE THREAD

**Issue by jaredreich** [atlassian/react-beautiful-dnd#848]
## Bug or feature request?

Bug

### Expected behavior

Grabbing the top element to begin a DnD should not make the list instantly fly off to the top. A user should be able to grab the top element and begin to move it before the list starts moving.

### Actual behavior

Grabbing the top element after already being scrolled a ways down a list makes the list fly off insanely fast to the top, making it unusable.

### Steps to reproduce / Demo

![dnd](https://user-images.githubusercontent.com/8563847/46571764-5539c100-c938-11e8-9d49-e54b3706109e.gif)

### What version of `React` are you using?

https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=single%20vertical%20list&selectedStory=basic

### What version of `react-beautiful-dnd` are you running?

https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=single%20vertical%20list&selectedStory=basic

### What browser are you using?

Chrome

**Comment by alexreardon** [comment]
Duplicate: #349

We hope to fix this soon!
