### ISSUE TITLE
[docs]  Example of release 4.0.0 uses `droppableProps`, but should be `draggableProps`

### ISSUE THREAD

**Issue by lpagliari** [atlassian/react-beautiful-dnd#852]
## Bug or feature request?

Documentation issue

### What version of `react-beautiful-dnd` are you running?

4.0.0

(I know this is a pretty old release, and that you're only looking into issues that are effecting the latest version, but as this looks like an easy fix and might affect teams migrating from old versions into the latest one, it might be useful for others too)

## Description

On the release notes for v. 4.0.0 (https://github.com/atlassian/react-beautiful-dnd/releases/tag/v4.0.0), the code example on section `Draggable > Props` has an (copy-paste?) issue: instead of `droppableProps`, we should use `draggableProps` (both on `{...provided.draggableProps}` and `{provided.draggableProps.style}`).

```diff
<Droppable droppableId="droppable">
   {(provided, snapshot) => (
      <div
       ref={provided.innerRef}
       style={getListStyle(snapshot.isDraggingOver)}
      >
-     {this.state.items.map((item, index) => (
-        <Draggable key={item.id} draggableId={item.id}>
+     {this.state.items.map((item, index) => (
+        <Draggable key={item.id} draggableId={item.id} index={index}>
               {(provided, snapshot) => (
                  <div>
                    <div
                      ref={provided.innerRef}
                      {...provided.droppableProps}                     <= here
                      {...provided.dragHandleProps}
                      style={getItemStyle(
                        provided.droppableProps.style,                 <= and here
                        snapshot.isDragging
                      )}
                    >
                      {item.content}
                    </div>
                    {provided.placeholder}
                  </div>
             )}
           </Draggable>
          ))}
        {provided.placeholder}
      </div>
    )}
</Droppable>
```

Kudos to @Roger-Siqueira, who found the issue.

**Comment by alexreardon** [comment]
is this fixed in the latest docs?

**Comment by lpagliari** [comment]
@alexreardon yes, I've just confirmed the latest README has the correct code: https://github.com/atlassian/react-beautiful-dnd#draggable

There's also a more recent release note (https://github.com/atlassian/react-beautiful-dnd/releases/tag/v7.0.0) with the correct code.

**Comment by alexreardon** [comment]
Given that the latest version has this correct we will not be addressing this documentation issue

We are not doing releases for older versions in order to maximise forward momentum
