### ISSUE TITLE
While adding import "@atlaskit/css-reset"; 

### ISSUE THREAD

**Issue by VinithRaj** [atlassian/react-beautiful-dnd#853]
The css file is not loading in webpack. When this package is added , it throws 

ERROR in ./node_modules/@atlaskit/css-reset/dist/bundle.css
Module parse failed: Unexpected token (19:11)
You may need an appropriate loader to handle this file type.
|   pre,
|   form,
|   fieldset {
|     margin: 0;
|     padding: 0;

I'm not an expert in react and if some one lend their hands in helping to solve this issue is highly thanked

**Comment by VinithRaj** [comment]
The css file is not loading in webpack. When this package is added , it throws 

ERROR in ./node_modules/@atlaskit/css-reset/dist/bundle.css
Module parse failed: Unexpected token (19:11)
You may need an appropriate loader to handle this file type.
|   pre,
|   form,
|   fieldset {
|     margin: 0;
|     padding: 0;

I'm not an expert in react and if some one lend their hands in helping to solve this issue is highly thanked

**Comment by lukebatchelor** [comment]
Hiya, it looks like you probably do.t have a loader configured for CSS files. 

Take a look at the webpack docs, should point you in the right direction

https://webpack.js.org/loaders/style-loader/
