### ISSUE TITLE
draggable component does not get rerendered until clicked when not using inline function

### ISSUE THREAD

**Issue by alukach** [atlassian/react-beautiful-dnd#854]
## Bug or feature request?

Bug

Similar to #156, however I'm not using MobX.

My state object is updated after move but the change is not represented in the view until I click on an element (i.e. after dropping the moved element, it appears that it has returned to its source location despite the state showing otherwise).

This only occurs when I'm not using an inline function.

Bad (Same result when using a non-arrow function):

```js
export default class TemplateEditor extends React.Component<Props, State> {

  public renderTemplateElements = (provided: DroppableProvided) => (
    <TemplateElementList
      innerRef={provided.innerRef}
      {...provided.droppableProps}
    >
      {this.props.template.layout.map((element, i) => (
        <TemplateElementComponent
          key={i}
          index={i}
          id={i.toString()}
          element={element}
        />
      ))}
      {provided.placeholder}
    </TemplateElementList>
  );

  public render() {
    return (
      <DragDropContext onDragEnd={this.onDragEnd}>
        <Container>
          <div className="m-2">Visual Editor</div>
          <Droppable droppableId="someUniqueId">
            {this.renderTemplateElements}
          </Droppable>
        </Container>
      </DragDropContext>
    );
  }
}
```

Good:

```js
  public render() {
    return (
      <DragDropContext onDragEnd={this.onDragEnd}>
        <Container>
          <div className="m-2">Visual Editor</div>
          <Droppable droppableId="someUniqueId">
            {(provided: DroppableProvided) => (
              <TemplateElementList
                innerRef={provided.innerRef}
                {...provided.droppableProps}
              >
                {this.props.template.layout.map((element, i) => (
                  <TemplateElementComponent
                    key={i}
                    index={i}
                    id={i.toString()}
                    element={element}
                  />
                ))}
                {provided.placeholder}
              </TemplateElementList>
            )}
          </Droppable>
        </Container>
      </DragDropContext>
    );
  }
```

### What version of `React` are you using?

`16.4.7`

### What version of `react-beautiful-dnd` are you running?

`7.1.2`

**Comment by garkin** [comment]
I got this issue too. Sad reason is  Redux `{pure: true}` HOC being used:
https://github.com/atlassian/react-beautiful-dnd/blob/6f71b45c13aab36807f9da952437a5d63d52d696/src/view/droppable/connected-droppable.js#L140

**Comment by garkin** [comment]
I think this is a bug. 
There is no need to check mutations in case we always send mutated `children={new lambda()}` prop. It's a CPU waste.
You should not assume function returns same result if function is the same. Dynamic composition is a whole reason to have a function in the first place.

**Comment by garkin** [comment]
I'm getting it in `"react-beautiful-dnd": "^9.0.2"`

**Comment by alexreardon** [comment]
Any thoughts on this @markerikson?

**Comment by markerikson** [comment]
Mmm... not specifically, other than `connect()`  does default to ensuring that your wrapped component only re-renders when either its data from the Redux store or the props passed to the wrapper component have actually changed.

**Comment by alexreardon** [comment]
@markerikson It looks like using an arrow function changes the `children` props (a new reference every time)

At least, that is what I thought until I set `areOwnPropsEqual` to `() => false` and every component re-rendered every time...

**Comment by markerikson** [comment]
So just to check: you're rendering `<SomeComponent constantProp={123}>{constantChild}</SomeComponent>` ?  In that case, yeah, if that component isn't extracting new values in its `mapState`, then `connect` will skip re-rendering it.  Passing in a new arrow function as that child _would_ be a new prop, so it _would_ re-render.

**Comment by alukach** [comment]
Btw, I mispoke, I am using `v9.0.2`

**Comment by markerikson** [comment]
Hmm.  That does sound odd.  Do you have a CodeSandbox or other project that repros this issue?

**Comment by alexreardon** [comment]
I can make one tomorrow

**Comment by markerikson** [comment]
@alexreardon : Did you ever dig into this issue further?

**Comment by dandelany** [comment]
Just wanted to ping this issue again, as I ran into it today ("react-beautiful-dnd": "10.0.3") and spent some time confusedly debugging before finding this ticket. Relatively easy to work around it using an arrow function, but it's hard to track down & def could cause confusion for users.

**Comment by alexreardon** [comment]
For sure, this looks like a deep react-redux issue. I am hoping it will just go away when we move to hooks #871

**Comment by alexreardon** [comment]
It could be worth calling out in the docs

**Comment by alexreardon** [comment]
PR's welcome!

**Comment by markerikson** [comment]
FWIW, I don't think I ever did see any kind of a repro project or test that I could look at with this.

**Comment by alexreardon** [comment]
I stopped digging after a while. I think I got distracted.

My understanding: if you use a render props function then your children prop is always different, which has some flow-on effects.

**Comment by alexreardon** [comment]
Can somebody check to see if this issue still exists on `12.0.0-alpha.7`?

**Comment by alexreardon** [comment]
I'll close this for now as I have not heard any updates on it. Please feel free to comment on this and we can reopen it if it is still an issue for people

**Comment by robbertbrak** [comment]
Still an issue. I ran into this today and had to waste some time debugging this before I found this ticket. How about mentioning this in the "Common setup issues"?

**Comment by SpringsTea** [comment]
Still an issue on 13...
