### ISSUE TITLE
DND is not responding with more than 1000 draggable cards

### ISSUE THREAD

**Issue by nikunjmavani** [atlassian/react-beautiful-dnd#857]
## Bug or feature request?
Bug

### Expected behavior
Can we do something like below?
-  Only those draggables should be rendered in window which are visible in droppable fix height.

### Actual behavior
I've put 1000 draggable cards in droppable which has fix height and scrollable.
- It is rendering all draggables(in my case more than 1000 divs) in droppable. 
- It takes around 400 MB in JV instance.

### What version of `React` are you using?
16.3.1

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Chrome 69.0.3497.100

**Comment by alexreardon** [comment]
We currently only recommend a max of 500. We should call this out in the docs.

At that point you start to run into performance issues with react itself - such as on persisting reordering.

Our solution will be to move to support virtual lists #68 for big data sets
