### ISSUE TITLE
React beautiful dnd not working with React Semantic UI Table

### ISSUE THREAD

**Issue by MRauca** [atlassian/react-beautiful-dnd#859]
Hello, I've tried to use react-beautiful-dnd in combination with React Semantic UI Table, but I cannot get it to work properly because of provided.innerRef issues ( https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md). I've seen some users experience similar issues with material ui too. (https://stackoverflow.com/questions/51839298/use-material-ui-table-with-react-beautiful-dnd). 
Here is the code sample which is working properly for a normal html table but not for a semantic ui react table: https://codesandbox.io/s/l467j0wj7m. 
I will appreciate any feedback, solutions or workarounds.

**Comment by alexreardon** [comment]
Have you tried looking at our [table guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md)

Let me know if that helps!

I am not sure how semantic UI exposes refs. Does it have a `innerRef` or similar named callback for exposing underlying DOM nodes?

**Comment by alexreardon** [comment]
I am not sure the exact details for how semantic UI exposes refs. Rather than digging into that personally, it would be great to get the input from somebody who is more familiar with that library

**Comment by MRauca** [comment]
> Have you tried looking at our [table guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md)
> 
> Let me know if that helps!
> 
> I am not sure how semantic UI exposes refs. Does it have a `innerRef` or similar named callback for exposing underlying DOM nodes?

Thank you very much for the help which pointed me in a direction. I found some info regarding refs in react-semantic-ui here: https://react.semantic-ui.com/addons/ref/#types-ref. I still have some trouble integrating it. Will get back with info and hopefully a working solution.

**Comment by MRauca** [comment]
Here is the working solution: https://codesandbox.io/s/84vz99mxn9. Previews attemps are commented out in the render function.

**Comment by AdamBCo** [comment]
@MRauca Thanks for providing the solution above. It really helped. I did notice that when you drag the row, the cells collapse. How were you able to address that issue? Thanks for the help.

**Comment by MRauca** [comment]
@AdamBCo Here is an official example that seems to be working properly: https://react-beautiful-dnd.netlify.com/?path=/story/tables--with-fixed-width-columns. The code for that example is here: https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/table/with-fixed-columns.jsx. Hope it helps.

```
const Row = styled.tr`
  /* stylelint-disable comment-empty-line-before */
  ${props =>
    props.isDragging
      ? `
    background: ${colors.G100};

    /* maintain cell width while dragging */
    display: table;
  `
      : ''} /* stylelint-enable */;
`;
```

**Comment by niklasdahlheimer** [comment]
Just in case someone is searching for a solution to this and still get the error
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function 
(for composite components) but got: undefined. You likely forgot to export your component 
from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `Droppable`.
```

**You have to check you module imports.**
My IDE (Webstorm) imported the `Ref`-Module automatically when I wrote the `<Ref></Ref>`-tag ... but it was the `Ref`-module from react and **not** from Sematic UI:
```
import React, {Ref, useEffect, useState} from 'react';
import {Table} from "semantic-ui-react";
```

What you obviously need to do is **import the `Ref `-module from Semantic UI**. So change this to:
```
import React, {useEffect, useState} from 'react';
import {Table, Ref} from "semantic-ui-react";

```
and you'll be fine :)
