### ISSUE TITLE
Bug, with left position calculating

### ISSUE THREAD

**Issue by FeklistovGleb** [atlassian/react-beautiful-dnd#862]
I find this bug when use component in float window. Style propetry left calculating not valid, when i dragging element, floating element left = floatwindow.left + padding.droppable.area. And similarly top propery.
![2018-10-22 2](https://user-images.githubusercontent.com/5002394/47288428-c21ead80-d5fe-11e8-9958-2d9b002aaeb6.png)

**Comment by alexreardon** [comment]
Please take a look at our [using a portal guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md)

Let me know if that helps!

**Comment by FeklistovGleb** [comment]
Thank's. I found better solution.

**Comment by alexreardon** [comment]
For others in the future, what did you go with?
