### ISSUE TITLE
Draggables not rendering properly

### ISSUE THREAD

**Issue by zachmoore12** [atlassian/react-beautiful-dnd#864]
## Bug or feature request?
Bug

### Expected behavior
When dragging a `<Draggable>` and utilizing the `snapshot.isDragging`, applying custom styles to that draggable should render properly. 

### Actual behavior
Applying custom styles to a Draggable works, but it does not re-render as you drag further down the list (causing them to keep previously applied styles and not render the new ones).

### Steps to reproduce
Demo link below, but:

- Apply a style to a Draggable above or below where that Draggable is being dragged, showing where it would be dropped
- Continue dragging the Draggable down the vertical list of Draggables
- Any Draggable that had a style applied will incorrectly maintain that style and not render without it (as you continue down the list)
- Any Draggable that had a style applied will correctly remove that style and render as you move up the list

Example:
https://www.screencast.com/t/OenzwrBWP

### What version of `React` are you using?
16.4.1

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Chrome 69.0.3497.100

### Demo
https://codesandbox.io/s/pym5jpj26m

This is a crude demo showing a list that should show a border above an item where the Draggable will be placed. It does so by comparing the index the Draggable will be dropped (determine using `onDragUpdate`) against the indexes of the items in the list. It will show a top border where appropriate, and then remove that border when the destination index changes. 

As you drag the Draggable, the styles apply, but as you continue dragging down the list, the items do not re-render and remove their border. As you drag back up, the items do appear to render and correctly lose their top border.

**Comment by JSmithCart** [comment]
@zachmoore12 we are having the same issue.  I second this.

**Comment by alexreardon** [comment]
There was a combination of things going on.

Here is your fixed example:

https://codesandbox.io/s/wyw8lx6xv5

- you needed to update your `dropIndex` when a drag starts
- it looks like there was a bug with the hook timings that is now fixed in `version 10` #838 
- if you do not render the draggable during a drag then keyboard dragging will break
- to avoid any visual jank, do not change the size of a border during a drag

For now you can use `react-beautiful-dnd-next` to get around your issue
