### ISSUE TITLE
Cannot render more than 1 droppables

### ISSUE THREAD

**Issue by sajadj313** [atlassian/react-beautiful-dnd#867]
Hello,
I am trying to integrate the react-beautiful-dnd into my react project. However I am experiencing some bugs in the code. I have followed the same demo code that you have presented in your demo pages but I still get errors

### Expected behavior
The plugin should render more than 1 droppables.

### Actual behavior
When I try to render just a single droppable, it works fine. But when I add more than 1 droppables, it throws me this error:

**Invariant Violation: DragDropContext.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.**

### Steps to reproduce
Works when I use the library like this:
`<DragDropContext>
  <Droppable>
    <Draggable>{data}</Draggable>
  </Droppable>
</DragDropContext>`

Throws me an error when I use the library like this:
`<DragDropContext>
  <Droppable droppableId="droppableId1">
    <Draggable>{data}</Draggable>
  </Droppable>
  <Droppable droppableId="droppableId2">
    <Draggable>{data}</Draggable>
  </Droppable>
</DragDropContext>`

### What version of `React` are you using?
I am using React 15.6.1 with typescript 2.4.1

### What version of `react-beautiful-dnd` are you running?
I am using react-beautiful-dnd version 6.0.2 and @types/react-beautiful-dnd 7.1.2

### What browser are you using?
I am using Google Chrome

### Demo
In this link:
https://codesandbox.io/s/yq98o0q399

**Comment by alexreardon** [comment]
We are only supporting the latest version of `react-beautiful-dnd` which currently is `9.x`

Your issue is that in the version of react you are using you can only have a single level child. Try wrapping all your `Droppables` in a single `<div>` parent

**Comment by sajadj313** [comment]
Thank you very much for the reply. This actually worked!
Best regards.
