### ISSUE TITLE
RFD: Moving to a hook api 🎣

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#871]
[`React hooks`](https://reactjs.org/docs/hooks-intro.html) have recently been announced.

Would we benefit from moving from a render props api to a hook based api for `react-beautiful-dnd`? If so, what would it even look like?

I have not thought very much about this, but I wanted to open it for discussion

**Comment by YurkaninRyan** [comment]
Oh wow this is an interesting question.  I think a hook based api would have to come along with a render prop based api.  Otherwise, you wouldn't be able to consume the hooks in non-function components.

I'm not 100% sure what a `useDraggable` or `useDroppable` would even look like.

I would assume that it would use `useEffect` and `useContext` to do its work?

**Comment by YurkaninRyan** [comment]
Yup, and if we were sticking with the way that `useState` works it would probably actually return

`const [provided, snapshot] = useDraggable({ id, index, })`

that way you could easily rename, and it is similar to the way react core works

**Comment by gnapse** [comment]
I wouldn't extrapolate that feature of `useState` to this case. I'm pretty sure `useState` does it like that to make it easier to rename the two things to your liking, since is common to use more than one state in several situations.

With something like this hypothetical `useDraggable`, that's not the case as much. Also, keep in mind there will be more stuff in that returned value, such as `isDragging`. What if you do not need everything? You'd need to remember the order of the stuff to know how to destructure it. With `useState` that's not an issue because is just two things and you pretty much always need them both.

**Comment by YurkaninRyan** [comment]
@gnapse definitely, however the way I picture it, useDraggable would only return two things.  For example, check this from the docs.

![image](https://user-images.githubusercontent.com/8742831/47592232-75114300-d940-11e8-9dda-db919d105b72.png)

Here we get a `provided` object as well as a `snapshot` object.  Whether it returns an array or an object doesn't matter so much to me, just that we have access to both.

Unless you are suggesting all the properties get merged on one `draggable` return object, which is an interesting thought, but different from the current api i'm used to

**Comment by alexreardon** [comment]
This seems like a reasonable API

```js
function Card({ itemId, index }) {
  const [provided, snapshot] = useDraggable({ draggableId: itemId, index });
  return (
    <div {...provided.draggableProps} {...provided.dragHandleProps } ref={provided.innerRef}>
      Drag me!
    </div>
  );
}
```

and 

```js
function List({ listId }) {
  const [provided, snapshot] = useDroppable({ draggableId: itemId, index });
  return (
    <div {...provided.droppableProps} ref={provided.innerRef}>
      <p>...</p>
      {provided.placeholder}
    </div>
  );
}
```

It seems to be the hook equivalent of the render props api we are providing now

**Comment by trixn86** [comment]
I like this more:

``` javascript
const {provided, snapshot} = useDraggable({ draggableId: itemId, index });
```
It is not even a single character longer.

I'd argue that the minor advantage of easily renaming the objects returned is not worth the disadvantages:

- You can't spread the whole object into a component (or something else) as props.
- If you were to add another value in the future it will have to be the third one for keeping backwards compatibility. Then it will be hard to get e.g. only the first and third value.
- [Array destructuring is currently slower](https://t.co/Rc7P7BMP6E).

The likelihood of even wanting to rename it is small so I think going with an object spreading and keeping with the current names as a convention is better.

If you really feel that you need to rename it you could still do:

``` javascript
const {provided: renamedProvided, snapshot: renamedSnapshot} = useDraggable({ draggableId: itemId, index });
```

**Comment by gnapse** [comment]
I feel the same way. I fear that because of `useState` using array destructuring (which is justified in its case for the reasons stated above) now many new hooks-enabled libraries will follow along without strong reasons.

You hardly ever use more than one draggable in the same context, and the same goes for droppable. And even if you did, you'd be better off not destructuring it, give the return value two meaningful names, and use those names' properties in the context they need to be used.

**Comment by YurkaninRyan** [comment]
While this does look awesome from the outside, I'm curious how we are going to achieve this effect.

Draggable does a lot more then just feed in those items to it's children, it also wraps those children in the handle as well as the dimension publisher.

I would argue that this is a case where render props/children as a function makes more sense then using hooks, since there is some hierarchy and extra rendering happening.

Any ideas how we could even begin to achieve this effect with hooks?

**Comment by YurkaninRyan** [comment]
> You hardly ever use more than one draggable in the same context, and the same goes for droppable. And even if you did, you'd be better off not destructuring it, give the return value two meaningful names, and use those names' properties in the context they need to be used.

I actually do agree with the object notation over the array notation in this usecase, gives more extendability down the line.

One thing that is a bit more common then double draggable or double droppable is a draggable inside of a droppable in the same render.  But the Droppable and Draggable components expose a provided and a snapshot property.

However, these cases don't feel common enough to warrant array notation

**Comment by trixn86** [comment]
@YurkaninRyan 

> Draggable does a lot more then just feed in those items to it's children, it also wraps those children in the handle as well as the dimension publisher.
> 
> Any ideas how we could even begin to achieve this effect with hooks?

That is an interesting question. I guess it should be possible to rewrite the `DragHandle` and `DimensionPublisher` to be custom hooks themselfs which will then be used by `useDraggable` hook internally. Therefore the whole current implementation as a class based components has to be rewritten as hooks which can then be wrapped by "legacy" components to keep old code working.

As far as I understood you should be able to transform any class based component logic into a hook including state and lifecycle methods and effectively make the components obsolete. The only problem would be if a component renders a context provider.

**Comment by alexreardon** [comment]
My current thinking:

- Move to hooks for everything internally
- Expose `useDraggable` and `useDroppable`
- Expose a `Draggable` and `Droppable` component with the same function as child api as we currently have. This would allow people to continue to use render props if they want to

```js
// Assuming a useDraggable(props) hook extends

function Draggable({draggableId, type, children}) {
  const [provided, snapshot] = useDraggable({draggableId, type});
  return children(provided, snapshot);
}
```

**Comment by YurkaninRyan** [comment]
I'd love to get working on some of these hooks, what hooks would make the most sense to start with?

**Comment by alexreardon** [comment]
Some bad news: there is no useProvider react hook. So there is no way for a hook to setup context. 

This is bad because `Droppable` sets up some context information to be used by `Draggable`. (type and droppableId). 

While we can still move internally to hooks, this might be a dealbreaker

**Comment by YurkaninRyan** [comment]
Could that context information instead be shifted up to DragDropContext and contained in some sort of internal map by droppable id?

**Comment by alexreardon** [comment]
Interesting @YurkaninRyan

**Comment by alexreardon** [comment]
Important milestone: everything has been converted to hooks internally, and it mounts without exploding

<img width="587" alt="Screen Shot 2019-03-18 at 2 24 21 pm" src="https://user-images.githubusercontent.com/2182637/54504865-a5a65780-4989-11e9-839e-3fef6f74bacc.png">

**Comment by alexreardon** [comment]
It then turns into a hot mess when you start to drag

**Comment by alexreardon** [comment]
I have a branch that is working and passing all tests. I am doing some finial performance testing #1208. You can play with it here: https://deploy-preview-1208--react-beautiful-dnd.netlify.com/?path=/story/single-vertical-list--basic

The branch is currently using `react-redux@7-beta` and I think we should wait until it is out of `beta` before leaning on `react-redux@7`

**Comment by alexreardon** [comment]
- [x] conduct performance tests
- [x] pull out [`useMemoOne`](https://github.com/alexreardon/use-memo-one)
- [ ] wait for stable release of `react-redux@7` /cc @markerikson

**Comment by alexreardon** [comment]
You can play with the new hooks based implementation:

```bash
yarn add react-beautiful-dnd@11.0.0-beta
```

😍

**Comment by alexreardon** [comment]
Until we a hook can setup context, we will not be moving to a hook based public API. We might investigate workarounds, but for now the render prop API will remain

**Comment by shawninder** [comment]
Pardon me for intruding, but I don't understand the need for the missing `useProvider` hook to setup context here.

> [...]there is no useProvider react hook. So there is no way for a hook to setup context.
> 
> This is bad because `Droppable` sets up some context information to be used by `Draggable`. (type and droppableId).
>
> [...]
> Until we a hook can setup context, we will not be moving to a hook based public API. [...]

Droppable is already rendering a `DroppableDimensionPublisher` which is aware of `type` and `droppableId`. Why not have it also render a context provider? That way any child (including Draggable) can `useContext(DroppableContext)`.

Am I missing something here?

**Comment by alexreardon** [comment]
We cannot have a `Droppable` be a hook right now as it sets up context for a `Draggable` to consumer. There is no way for a hook to set up context. `Droppable` has moved over to being a function component that uses hooks, and renders a Context.Provider for a `Draggable` to consume

**Comment by shawninder** [comment]
Ah, I didn't realize you were trying to make `Droppable` _purely_ a hook (avoid the Component altogether). I thought the objective was simply to remove the render props syntax.

Thanks for the clarification!

**lt;dr**
As for setting up context in a hook, perhaps a hook can instead return a component which sets up context? I started thinking along those lines and came up with the following, for what it's worth.

**Original syntax**
```jsx
import { useState } from 'react'
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd'

export default function App () {
  const [items, setItems] = useState(['one', 'two', 'three'])
  function onDragEnd ({ type, reason, destination, source }) {
    if (type === 'DEFAULT' && reason === 'DROP' && destination) {
      const newItems = Array.from(items)
      const moved = newItems.splice(source.index, 1)
      newItems.splice(destination.index, 0, moved)
      setItems(newItems)
    }
  }
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Droppable droppableId='dropzone'>
        {(droppableProvided, droppableSnapshot) => {
          return (
            <ul ref={droppableProvided.innerRef}>
              {items.map((item, idx) => {
                return (
                  <Draggable draggableId={`draggable-${item}`} index={idx}>
                    {(draggableProvided, draggableSnapshot) => {
                      return (
                        <li
                          key={item}
                          ref={draggableProvided.innerRef}
                          {...draggableProvided.draggableProps}
                          {...draggableProvided.dragHandleProps}
                        >{item}</li>
                      )
                    }}
                  </Draggable>
                )
              })}
              {droppableProvided.placeholder}
            </ul>
          )
        }}
      </Droppable>
    </DragDropContext>
  )
}
```

**Potential new syntax**
```jsx
import { useState } from 'react'
import { useDragDrop } from 'react-beautiful-dnd'

export default function App () {
  const [items, setItems] = useState(['one', 'two', 'three'])
  const [DragDropContext, makeDroppable, makeDraggable] = useDragDrop()

  function onDragEnd ({ type, reason, destination, source }) {
    if (type === 'DEFAULT' && reason === 'DROP' && destination) {
      const newItems = Array.from(items)
      const moved = newItems.splice(source.index, 1)
      newItems.splice(destination.index, 0, moved)
      setItems(newItems)
    }
  }
  const [Droppable, droppableProvided, droppableSnapshot] = makeDroppable({
    id: 'dropzone'
  })
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Droppable>
        <ul ref={droppableProvided.innerRef}>
          {items.map((item, idx) => {
            const [Draggable, draggableProvided, draggableSnapshot] = makeDraggable({
              id: `draggable-${item}`,
              index: idx
            })
            return (
              <Draggable>
                <li
                  key={item}
                  ref={draggableProvided.innerRef}
                  {...draggableProvided.draggableProps}
                  {...draggableProvided.dragHandleProps}
                >{item}</li>
              </Draggable>
            )
          })}
          {droppableProvided.placeholder}
        </ul>
      </Droppable>
    </DragDropContext>
  )
}
```
Again, I'm not sure how good of an idea this is, I'm just trying to help generate ideas...

**Comment by alexreardon** [comment]
An interesting idea @shawninder. I did consider it, but I was not sure there was much value in this pattern over just keeping with the existing render props api.


The internal hook refactor has shipped in 11.0: https://github.com/atlassian/react-beautiful-dnd/releases/tag/v11.0.0

For now, until a hook can setup context we won't be able to move to a public hook api. Based on that I will close this issue. I gave it a really good shot!

https://www.youtube.com/watch?v=MVi17tk3VsI

**Comment by mostafah** [comment]
It seems like `useProvider` is not going to happen. It is suggested and rejected in facebook/react#14534. And [this blog post](https://overreacted.io/why-isnt-x-a-hook) mentions `useProvider` as something that doesn’t work well as a hook.

**Comment by alexreardon** [comment]
It might make sense for hooks not to be able to set up context as an architectural decision. The consequence of the decision is that we cannot move to a purely hooks based api. It is not the end of the world 😊

**Comment by migueloller** [comment]
Why does the API need to be a purely hooks API though? Why not expose just `useDraggable` and leave `Droppable` as is?

I do agree it’s not a big deal though, even with hooks being a thing, the render prop API still makes sense when the abstraction is a visual one and not a logical one, which is the case for drag and drop.

Has it been explored to have a potential `useDroppable` hook that doesn’t set up context but instead registers with the top-level context so that it can then be consumed by `useDraggable`.

**Comment by shawninder** [comment]
Ok, this will be my last attempt with `useProvider` returning a function which can setup context for a subtree:

`useProvider`:
```jsx
function useProvider (Context, value) {
  return (children) => {
    return (
      <Context.Provider value={value}>{children}</Context.Provider>
    )
  }
}
```

`useDroppable`:
```jsx
function useDroppable ({ id }) {
  const droppable = useProvider(DroppableContext, { ... })
  ...
  return [droppable, droppableProvided, droppableSnapshot]
}
```

`useDraggable`:
```jsx
funciton useDraggable ({ id }) {
  const { fromContext } = useContext(DroppableContext)
  ...
  return [draggable, draggableProvided, draggableSnapshot]
}
```

Usage:

```jsx
import { useState } from 'react'
import { DragDropContext, useDroppable, useDraggable } from 'react-beautiful-dnd'

export default function App () {
  const [items, setItems] = useState(['one', 'two', 'three'])

  function onDragEnd ({ type, reason, destination, source }) {
    if (type === 'DEFAULT' && reason === 'DROP' && destination) {
      const newItems = Array.from(items)
      const moved = newItems.splice(source.index, 1)
      newItems.splice(destination.index, 0, moved)
      setItems(newItems)
    }
  }
  const [droppable, droppableProvided, droppableSnapshot] = useDroppable({
    id: 'dropzone'
  })
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      {droppable(
        <ul ref={droppableProvided.innerRef}>
          {items.map((item, idx) => {
            const [draggable, draggableProvided, draggableSnapshot] = useDraggable({
              id: `draggable-${item}`,
              index: idx
            })
            return draggable(
              <li
                key={item}
                ref={draggableProvided.innerRef}
                {...draggableProvided.draggableProps}
                {...draggableProvided.dragHandleProps}
              >{item}</li>
            )
          })}
          {droppableProvided.placeholder}
        </ul>
      )}
    </DragDropContext>
  )
}
```

[Working example of `useProvider`](https://codepen.io/shawninder/pen/jRYaqE)

I don't think this changes the conclusion for this repo, but it may be interesting for people following this discussion.

**Comment by warent** [comment]
Reading through this ticket, I can't even see the rationale behind why this decision was made. It's kind an annoying/upsetting one because now I have to introduce a completely different pattern into my codebase for this one packege.

**Comment by warent** [comment]
Reading through this ticket, I can't even see the rationale behind why this decision was made. The discussion instantly jumped into how. It's kind an annoying/upsetting decision because now I have to introduce a completely different pattern into my codebase for this one package.

**Comment by pie6k** [comment]
So what is actual status of this? I can see Hooks PR merged, but I don't really see it in Docs etc.

**Comment by trixn86** [comment]
@pie6k 

> So what is actual status of this? I can see Hooks PR merged, but I don't really see it in Docs etc.

As far as I know there is no user facing hooks API yet because react-beautiful-dnd uses react context and there is no way for a hook to set up a context. For that you need to render a `ContextProvider` which ultimately means you need a component anyways, at least for a `Droppable`.

The PR only replaced some internal logic that has been managed in class based components with hooks.
