### ISSUE TITLE
Storybook - Table Pattern

### ISSUE THREAD

**Issue by NickEmpetvee** [atlassian/react-beautiful-dnd#874]
Hi guys.

I was looking at the [table](https://react-beautiful-dnd.netlify.com/?selectedKind=Tables&selectedStory=with%20fixed%20width%20columns&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) pattern example. Is the code for this posted somewhere? I don't see a link to it in the Storybook or elsewhere in the project.

Thanks,
Nick

**Comment by tylik1** [comment]
Should be one of these. 
https://github.com/atlassian/react-beautiful-dnd/tree/master/stories/src/table

I also think it would be cool if storybook, at least provided ability to copy code, used to build particular example

**Comment by NickEmpetvee** [comment]
@tylik1 Yep thanks so much! I agree that it would be useful to see that in the storybook.

**Comment by NickEmpetvee** [comment]
@tylik1 these are Flow examples . It looks like I can't just transfer the code from one of the files (e.g. with-dimension-locking.jsx) into a create-react-app environment and point to the toplevel component from the app.js. Do you know where there's a guide that could help me get started?

**Comment by NickEmpetvee** [comment]
That is awesome thank you. Much simpler than dealing with flow.

**Comment by NickEmpetvee** [comment]
@tylik1 Had a quick question. I added one more <td> in the codesandbox example above. It still drags and drops just fine. What I noticed though is that while dragging, the two <td> elements get compressed together as one. Do you know why this might be? I updated the codesandbox example with this to demonstrate.

**Comment by tylik1** [comment]
No idea. I think you can compare and apply styles from flow example with example in sandbox. 

Also, it might be the case of fixed dimensions row vs dynamic (width-dimension-locking.jsx vs with-fixed-columns.jsx). Find out which one you need, and try to apply styles from there.

**Comment by NickEmpetvee** [comment]
Thanks that makes sense.
