### ISSUE TITLE
Egghead course issue: "Reorder a List with react-beautiful-dnd"

### ISSUE THREAD

**Issue by NickEmpetvee** [atlassian/react-beautiful-dnd#875]
## Bug or feature request?

Bug, I think

### Expected behavior

The code at the end of this module is supposed list all tasks in the column and they should be draggable.

### Actual behavior

I get this error:

```
Error: Invariant failed: Cannot get draggable ref from drag handle
▶ 22 stack frames were collapsed.
Module../src/index.js
C:/mcdev/react/task-app/src/index.js:31
  28 |     }
  29 | }
  30 | 
> 31 | ReactDOM.render(<App />, document.getElementById('root'))
```

### Steps to reproduce

Just run the code. It throws the error as soon as you save the file(s) and the site reloads.

### What version of `React` are you using?

16.6

### What version of `react-beautiful-dnd` are you running?

9.0.2

### What browser are you using?

Chrome on Win 81

### Demo

Here is the issue: https://codesandbox.io/s/wyxwwrx7yl.

**Comment by NickEmpetvee** [comment]
I resolved this by putting `ref={provided.innerRef}` before the `innerRef` in both the task and column objects.

**Comment by Pajn** [comment]
You are using a newer major version of styled-components. In version 4 they changed to using forwardRef instead of a custom property https://www.styled-components.com/releases#v4.0.0

**Comment by NickEmpetvee** [comment]
Thanks @Pajn !

**Comment by alexreardon** [comment]
It would be worth calling this out in the egghead course

**Comment by NickEmpetvee** [comment]
@alexreardon FYI, if using `ref={provided.innerRef}` without an `innerRef` tag at all with version 4 of styled-components, it works.

**Comment by alexreardon** [comment]
Yep thanks!

**Comment by scottdixon** [comment]
More info: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

**Comment by savvysqrrl3** [comment]
I am not using styled components, I am using Less files, so I am wondering how to render my component without all the style wrappers and whether an inner ref is needed to make this work.

**Comment by NickEmpetvee** [comment]
@savvysqrrl3 Did you come to a resolution on that? I'd like to use this without styled components too.

**Comment by rc1336** [comment]
Having trouble with the egghead tutorial. 

I have tried replacing ```innerRef``` with ```ref``` and ```forwardRef``` 

Yet still returning the error 
```Error: Invariant failed: Cannot get draggable ref from drag handle```

Also have a warning being thrown but cant seem to find the file the that needs to be replaced. 
```Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed```

**Comment by savvysqrrl3** [comment]
I ended up not using styled components, since I had a deadline. Since I used LESS, I figure you would have to do an event handler like /onMouseover/ or something like that.
I too had issues with the innerRef not working until I changed the order. You can see my solution at [https://github.com/savvysqrrl3/fab_grid](url)

**Comment by NickEmpetvee** [comment]
@rc1336 I compose it this way and it works:

```
            {provided => (
              <Container
                {...provided.droppableProps}
                ref={provided.innerRef}
              >
```

**Comment by skywalkerwin** [comment]
using ref={provided.innerRef} allows my tasks to be draggable, but as soon as I drag and change the order of a task, the order immediately reverts to what it was before...

**Comment by alexreardon** [comment]
@savvysqrrl3 you are welcome to use whatever styling approach you want. I would recommend you read our ref's guide.

the `ref` attribute on an element is a way of getting a pointer to the DOM element. We use this for collecting dimensions

**Comment by jvcjunior** [comment]
How did u solve @skywalkerwin ?

**Comment by jvcjunior** [comment]
@skywalkerwin  you need to use onDragEnd method to reorder your array. That's it!! :)
