### ISSUE TITLE
onDragUpdate 钩子函数里面，希望提供阻止拖拽动作的接口，

### ISSUE THREAD

**Issue by lwsyc** [atlassian/react-beautiful-dnd#885]
## Bug or feature request?
onDragUpdate 钩子函数里面，希望提供阻止拖拽动作的接口，
(answer here)

**Comment by alexreardon** [comment]
From google translate:

钩子函数里面，希望提供阻止拖拽动作的接口
"Inside the hook function, I want to provide an interface that prevents drag and drop."

您可以在拖动之前使用Draggable> isDragEnabled，或在拖动期间使用Droppable> isDropEnabed
You can use Draggable > isDragEnabled before a drag, or Droppable > isDropEnabed during a drag

您可能会觉得这很有帮助
You might find this helpful: 
https://github.com/chinanf-boy/react-beautiful-dnd-zh
