### ISSUE TITLE
code demo 

### ISSUE THREAD

**Issue by zhuhongyan** [atlassian/react-beautiful-dnd#887]
![https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple](https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple)
where could i see Source code？

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/src/board/board.jsx
