### ISSUE TITLE
Horizontal droppable with a max-width narrower than contents has jittery effect on far right

### ISSUE THREAD

**Issue by instadrew** [atlassian/react-beautiful-dnd#889]
## Bug or feature request?
Additional documentation request, and possibly a bug. Seeking more documentation on setting a horizontal droppable with more draggables inside than can be shown without scrolling due to a max-width set on the div, but without resulting in a jittery effect and difficulty dropping to the far right end of the droppable.

I'd also like to know how to hide the horizontal scrollbar after dropping as shown in one of the react-beautiful-dnd demos.

I have reviewed the tutorial at https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd, but have run into the problems described below.

### What version of `React` are you using?
16.4.1

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Chrome Version 70.0.3538.77 (Official Build) (64-bit) on MacOS 10.14

### Question
The react-beautiful-dnd "Auto scrolling" demo at: 

https://github.com/atlassian/react-beautiful-dnd#auto-scrolling 

shows:
1. a vertically bounded droppable area (not bounded by the page, but seemingly by a div with a set height) that scrolls as needed when dragging
1. a scrollbar that disappears after the draggable has been dropped

I would like to do the same thing for a horizontal droppable area.  I have tried editing the react-beautiful-dnd demo at:

https://mmrp44okvj.codesandbox.io/

by setting:

```css
max-width: 300px;
```

on the droppable div.  But this results in a jittery effect when dragging to the far right, and difficulty dropping to the right of the last draggable since no empty space opens on the far right.

So, I'm wondering:
1. how to set up a horizontal draggable with a width smaller than allows all draggables to be shown at once, but does not result in the jittery behavior described above
1. how to make the scrollbar disappear after the draggable has been dropped

**Comment by instadrew** [comment]
Is there any other information I need to provide for this to be looked at?

**Comment by alexreardon** [comment]
First thing, trying using `react-beautiful-dnd-next` to see if things just start working

**Comment by instadrew** [comment]
Thank you.  I tried using `react-beautiful-dnd-next` but the same jittery problem occurs when dragging to the far right.

**Comment by instadrew** [comment]
@alexreardon : Is the jittery behavior I described considered a bug?

**Comment by shuangq** [comment]
I had the same problem. Fixed with this solution:
https://github.com/atlassian/react-beautiful-dnd/issues/536#issuecomment-395153442 
#536

**Comment by alexreardon** [comment]
We'll track it in #536
