### ISSUE TITLE
Mention, that the index used in Draggable has to be dense

### ISSUE THREAD

**Issue by LorenzHenk** [atlassian/react-beautiful-dnd#892]
## Bug or feature request?

Problem in the docs.

https://github.com/atlassian/react-beautiful-dnd#draggable-props

The draggable props' index does not specify, that the values used for it have to be dense (e.g. 1, 2, 3, 4) and are not allowed to be sparse (e.g. 1, 3, 6, 20).

I had a lot of trouble with this problem: My draggables had the ids 1, 2 and 4, but `result.destination.index` was 3, so it did not move (because 3 is still a higher value than 2).

**Comment by alexreardon** [comment]
Strange timing! I just added this to a branch today!

**Comment by LorenzHenk** [comment]
Are you planning to add a notice to the docs or fix the problem? 
My thoughts on fixing the problem:
I think `result.source.index` and `result.destination.index` should hold the actual index value, instead of the positional index.
So for the example index values `[1, 3, 5, 6, 20]`, when dropping `20` between `5` and `6` `result.destination.index` should be `6` (the actual index) instead of `3` (the list index).

**Comment by alexreardon** [comment]
We will document that indexes must start at 0 and be dense. For now a lot
of functions assume this

**Comment by alexreardon** [comment]
#838
