### ISSUE TITLE
 I have a tree menu like this... but, I have a problem

### ISSUE THREAD

**Issue by bibiehy** [atlassian/react-beautiful-dnd#900]
"react-beautiful-dnd": "^9.0.2",
"react-dom": "16.5.2",
"react": "16.5.2",

![image](https://user-images.githubusercontent.com/35096473/48193066-8c125500-e384-11e8-93e7-adf89908702f.png)

as the picture shows

dragged 'childMenu-A-1' to 'parentMenu-B'    ->  Yes = ['childMenu-A-1', 'childMenu-B-1', ....]
dragged 'childMenu-B-1' to 'parentMenu-A'    ->  Yes = ['childMenu-B-1', 'childMenu-A-1', ....]

but
I want to drag the child to become the first level menu. -> No
or
I want to drag the  first level menu to become the child. -> No

Does this plugin support?

what should I do？

**Comment by alexreardon** [comment]
See our [version 10 release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0)

We have created a tree component for people to use 💃
