### ISSUE TITLE
How do I report a smaller draggable?

### ISSUE THREAD

**Issue by tarjei** [atlassian/react-beautiful-dnd#907]
## Bug or feature request?

Unsure. 

You can create a draggable that changes when it gets dragged:

```
 <Draggable
        draggableId={resource.id}
        key={resource.id}
        type="Resource"
        index={index}>
        {(provided, snapshot) => {
          return snapshot.isDragging ? (
            <ResourceItem
              lessonResource={{ id: 0, resource }}
              provided={provided}
              snapshot={snapshot}
              moduleId="0"
              element=""
              active
              course={{}}
              lesson={{}}
            />
          ) : (
            <div
              ref={provided.innerRef}
              {...provided.draggableProps}
              {...provided.dragHandleProps}
              className="query-result column">
              <VideoThumb viewThumbnailOnly resource={resource} />
              <div className="result-name">{resource.name}</div>
            </div>
          )
        }}
      </Draggable>
```

But if this changes the height or width of the dom element, this is not reflected in the computation of the element when you move it into the list, thus it "feels" like you are moving a huge object - instead of a small one.

### Expected behavior

Either the library should detect the change in size or provide a way to change it. 

### What version of `React` are you using?

React 16.6.

### What version of `react-beautiful-dnd` are you running?
Latest.
### What browser are you using?

Chrome 70.

**Comment by alexreardon** [comment]
Right now this is not a supported feature. We require all elements to remain the same size as when the drag starts

**Comment by alexreardon** [comment]
See #944
