### ISSUE TITLE
Request support for data prop on draggables

### ISSUE THREAD

**Issue by instadrew** [atlassian/react-beautiful-dnd#920]
## Feature request
Would like a prop on draggables that can be used to pass arbitrary data to onDragStart, onDragEnd, etc.  I'm requesting this as a feature to be considered for use with with the copy/clone feature requested in #216.  In the wonderful suggestion in #216 provided by @pixelass, each new copy of the draggable gets a new id.  However, I'd also like to be able to specify a generic id used by all copies of the draggable, which could be specified as a prop on the draggable, and made available in onDragStart, onDragEnd, etc.  (It would not work for me to use a draggable class, since all draggables in my application would be the same class.)  I imagine that this functionality could be useful for other purposes.

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by alexreardon** [comment]
Duplicate: #498

**Comment by alexreardon** [comment]
Thanks for the suggestion @instadrew! I am keen to allow some sort of `data` prop
