### ISSUE TITLE
draggableId does not accept 0

### ISSUE THREAD

**Issue by flipchart** [atlassian/react-beautiful-dnd#921]
## Bug or feature request?

Bug

### Expected behavior
No error

### Actual behavior
Console error & exception: Draggable requires a draggableId

### Steps to reproduce
Create a Draggable element with a draggableId set to 0. The props checker checks for falsey values which renders the (IMO) perfectly acceptable draggableId value of 0 as false and throws the exception

### What version of `React` are you using?
16.6.3

### What version of `react-beautiful-dnd` are you running?
10.0.1

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
I will fix this tomorrow

**Comment by alexreardon** [comment]
Are you using the number 0 or the string “0”?

**Comment by TrySound** [comment]
@alexreardon Need a null check here https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable/check-own-props.js#L12
```
invariant(props.draggableId != null, 'Draggable requires a draggableId');
```

@flipchart Could you rename the issue title to something like `draggableId does not accept 0`

**Comment by flipchart** [comment]
@alexreardon using the number `0`. 

@TrySound issue renamed. I would suggest 

    invariant(props.draggableId != null && props.draggableId != undefined, 'Draggable requires a draggableId');

unless the `undefined` check is done elsewhere?

**Comment by flipchart** [comment]
Aaah, thanks. I'm so used to triple equals (due to TSLint) that I'm not aware of the coercion rules with double equals

**Comment by alexreardon** [comment]
I can loosen the check, but keep in mind:

- we might be doing truthy checks elsewhere, so using 0 might not work anyway
- we call out that `draggableId` needs to be a string. If you want you can just use `"0"` as the `draggableId`
- even if i get it working today **there will be regressions** because it is a violation of our public types and so we won't be testing against it..

the more i think about it, the more i think maybe we should not account for this. Thoughts @lukebatchelor @TrySound ?

**Comment by TrySound** [comment]
@alexreardon Flow has a lint rule to safely handle such case.
https://flow.org/en/docs/linting/rule-reference/#toc-sketchy-null

**Comment by TrySound** [comment]
However it won't check this specific case since type is not nullable.

**Comment by alexreardon** [comment]
Based on [discussion](https://github.com/atlassian/react-beautiful-dnd/pull/925#issuecomment-438862750) in #925 I am leaning towards declining this PR. 

We only accept officially accept `string` ids at this stage.

You can overcome your issue by simply making your 0 id a string: `"0"`. In your `Responders` you can then cast this back to a number if you like with `Number(source.draggableId)`

**Comment by flipchart** [comment]
String Ids are fine with me. Didn't know there were TS typings; will use those to avoid these sorts of issues going forward
