### ISSUE TITLE
expected string but got symbol

### ISSUE THREAD

**Issue by sajadj313** [atlassian/react-beautiful-dnd#927]
### Expected behavior
The react-beautiful-dnd should work

### Actual behavior
I get a screen in red color with the following error message:
`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.`

### Steps to reproduce
Nothing special. Please check the demo code to reproduce the error.

### What version of `React` are you using?
- react: ^16.2.0
- @types/react: ^16.0.38
- typescript: ^2.7.2

### What version of `react-beautiful-dnd` are you running?
- react-beautiful-dnd: ^10.0.1
- @types/react-beautiful-dnd: ^7.1.2

### What browser are you using?
I am using Google Chrome

### Demo
Please check this Sandbox link:
https://codesandbox.io/s/j7wzkzz1zy

This is what i get once I run using Visual Studio
![untitled](https://user-images.githubusercontent.com/34274720/48531586-ce76ed00-e8c2-11e8-834a-850ee5e5b15d.png)

However, I don't get any issues when i run the same code on sandbox. I have no idea what has gone wrong. Could you please have a look at this?

Thank you Very much!

**Comment by alexreardon** [comment]
Do you see anything in your console?

**Comment by sajadj313** [comment]
Yes, the console prints the exact same error message which is in the red screen

**Comment by alexreardon** [comment]
Any react beautiful dnd warnings?

**Comment by sajadj313** [comment]
No warnings from the react beautiful dnd.
However, I did some experiments and I removed the nested <Draggable/>'s and just added an empty <div/>.

Then the component is rendered without any errors. Let me attach a sample:
![untitled1](https://user-images.githubusercontent.com/34274720/48532543-da64ae00-e8c6-11e8-944d-c99bfb9a9ae5.png)

This is my code structure now:
`<DragDropContext onDragEnd={this.onDragEnd}>
                <Droppable droppableId="droppable">
                    {(provided, snapshot) => (
                        <div
                            ref={provided.innerRef}
                            style={getListStyle(snapshot.isDraggingOver)}
                        >
                            <div>
                                Just a div
                            </div>
                            {provided.placeholder}
                        </div>
                    )}
                </Droppable>
            </DragDropContext>`

**Comment by alexreardon** [comment]
Your issue is that your not meeting the peer dep version requirement of 16.3.1

You where probably hitting an issue with react where < 16.3 you could not accept a list of `children` as a prop

**Comment by alexreardon** [comment]
If you upgrade your react version everything should be fine. Let me know how you go

**Comment by sajadj313** [comment]
I upgraded the version of react to the latest version which is **16.6.3** but unfortunately, the same issue still seems to be be there. Any idea on why it is happening?
