### ISSUE TITLE
 Like this example, I have a question

### ISSUE THREAD

**Issue by bibiehy** [atlassian/react-beautiful-dnd#928]
https://react-beautiful-dnd.netlify.com/?selectedKind=complex%20vertical%20list&selectedStory=nested%20vertical%20lists&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

open this link

The sub-items of the second-level can be dragged outside to become the first-level sub-items ?
or
The sub-menu of the first-level can be dragged into the second-level to become the second-level sub-item ?

use this plugin of the 'react-beautiful-dnd', can achieve the above two interactions?

**Comment by alexreardon** [comment]
right now you can have multiple levels of `Droppables`, but these levels cannot interact with one another. So you cannot move from one level to another
