### ISSUE TITLE
Can't use keyboard to move an item to another empty list in v10

### ISSUE THREAD

**Issue by lukyth** [atlassian/react-beautiful-dnd#932]
## Bug or feature request?

Bug

### Expected behavior
Should be able to use a keyboard to move an item to another empty list with v10.

### Actual behavior
The item is not moving.

### Steps to reproduce
1. Upgrade react-beautiful-dnd from v9.0.2 to v10.0.1
2. Using keyboard to move an item to another empty list, which used to work.
3. The item is not moving.

### What version of `React` are you using?
16.6.3

### What version of `react-beautiful-dnd` are you running?
10.0.1

### What browser are you using?
Google Chrome 70.0.3538.102 (Official Build) (64-bit)

### Demo
- Use v10.0.1 and has a bug: https://codesandbox.io/s/q878z84pm9
- Use v9.0.2 and doesn't have a bug: https://codesandbox.io/s/2x0z9l78wr

Both are based on https://codesandbox.io/s/ql08j35j3q ("vertical list with multiple drop targets" official example) but modified so that the empty list doesn't have huge space and contain some static element at the bottom.

**Comment by alexreardon** [comment]
I’ll take a look soon. We did a lot of work on this use case...

**Comment by lukyth** [comment]
@alexreardon But the item can be dragged using a mouse. Isn't it suppose to behave the same way?
![kapture 2018-11-18 at 20 48 06](https://user-images.githubusercontent.com/7040242/48673378-4a975c00-eb73-11e8-812c-1b5119388828.gif)
The gif shows that an item can be moved using a mouse, but not with a keyboard.

**Comment by alexreardon** [comment]
I'll take a look

**Comment by lukyth** [comment]
Thank you so much. Really appreciate your work :)

**Comment by alexreardon** [comment]
You’re welcome. I will be doing a patch release soon
