### ISSUE TITLE
Change the title and description of the storybook

### ISSUE THREAD

**Issue by dimitarnestorov** [atlassian/react-beautiful-dnd#935]
## Bug or feature request?

🤷‍♂️

### What version of `React` are you using?

16.6.0

### What version of `react-beautiful-dnd` are you running?

10.0.0

### What browser are you using?

Chrome

### Demo

![image](https://user-images.githubusercontent.com/8790386/48739720-7c84ed00-ec5d-11e8-9815-cbaf6aaf98a3.png)

----------
In my opinion the third result in Google deserves a more descriptive look

**Comment by alexreardon** [comment]
Agreed. Can you create a PR?

**Comment by dimitarnestorov** [comment]
Seems impossible to customize the title without hacks or tricks: https://github.com/storybooks/storybook/issues/866
Waiting for https://github.com/storybooks/storybook/pull/4086 to be merged.

The description can be changed: https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by alexreardon** [comment]
I'll close this for now as we won't be actioning it directly. But if you would like to submit a PR @dimitarnestorov you are welcome to!
