### ISSUE TITLE
Optimised placeholder placement

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#94]
Right now when you hover over a foreign list the original draggable placeholder remains. This is to avoid the list collapsing. However, I think it would be better to enable the `Droppable` placeholder for the home list to avoid collapsing but to avoid having a gap in the list.

### Full placeholder rules:

- when dragging over a home list - use the `Draggable` placeholder
- when dragging over no list - use the `Draggable` placeholder
- when dragging over a foreign list - use the `Droppable` placeholder in both the home and foreign `Droppable`.

**Comment by alexreardon** [comment]
I did a spike of this and it looks quite nice.

**Comment by souporserious** [comment]
First, thank you for such a great library! I absolutely love the workflow compared to other react sortable solutions. Any idea on when/if this might land? Just started using this library and would love this feature. I'm mainly using this for multiple vertical lists right now so it's a little wonky with the placeholder left over when moving to a foreign list. I'd love to help out with whatever if you need a lending hand. Please let me know.

**Comment by alexreardon** [comment]
I hope to look at this as we updated our placeholder logic for #202

**Comment by alexreardon** [comment]
See [10.1](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.1.0)
