### ISSUE TITLE
isDraggingOver not changing to true on dragging over to a droppable.

### ISSUE THREAD

**Issue by amarkrsinha1997** [atlassian/react-beautiful-dnd#940]
I have actually trying to make a list where I want to delete some draggable from the list so I am dropping them to a droppable delete button which I am initially hiding but when I set it to display true I can't drag list draggable to it.

```jsx
<Droppable droppableId="delete">
	{(provided, snapshot) => {
		return (
			<div
				ref={provided.innerRef}
				{...provided.droppableProps}
				>
				<Slide direction="up" in={this.state.deleteButtonShow} mountOnEnter unmountOnExit>
					<Button
						variant='raised'
						fullWidth
						className={classes.deleteButton}
						>
						<DeleteIcon/>
					</Button>
				</Slide>
				{provided.placeholder}
			</div>
		)}}
</Droppable>
```

Here the deleteButtonShow is a boolean field which set to true/false using a switch button
```jsx
toggleCourseDeleteButton = () => {
		this.setState((prevState) => {
			return {
				deleteButtonShow:!prevState.deleteButtonShow
			}
		});
	}
<Switch checked={this.state.deleteButtonShow} onChange={this.toggleCourseDeleteButton} aria-label="Collapse" />

```

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by amarkrsinha1997** [comment]
Had some problem with co-ordinate I was having the problem of overlapping 2 list found it in one of the issue's closing this one and thanks for the reply saw it today :) Happy Coding
