### ISSUE TITLE
Broken Link at react-beautiful-dnd/docs/patterns/multi-drag.md

### ISSUE THREAD

**Issue by modemmute** [atlassian/react-beautiful-dnd#954]
There's a broken link in [react-beautiful-dnd/docs/patterns/multi-drag.md](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md) in the second paragraph.

"We have created a [reference application](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/react-beautiful-dnd.netlify.com/iframe.html?selectedKind=Multi%20drag&selectedStory=pattern&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) ([source](https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/9-multi-drag-story.js)) which implements this multi drag pattern" -- the 'reference application' link is a 404 and the 'source' link doesn't seem to link to any relevant code.

**Comment by alexreardon** [comment]
This has now been fixed by #955. Thanks @modemmute

**Comment by Frankcarvajal** [comment]
The issue has not been fixed, and should be reopened. 
I created a new issue #1118 

Cheers!
