### ISSUE TITLE
Limit dragging in x-axis or y-axis

### ISSUE THREAD

**Issue by alirezavalizade** [atlassian/react-beautiful-dnd#958]
I'm trying to limit the dragging in x-axis, 

I got this idea,

```
const getItemStyle = (isDragging, { transform, ...draggableStyle }) => {
  const styles = {
    boxShadow: isDragging ? '0 0 10px rgba(0, 0, 0, 0.11111)' : 'none',
    ...draggableStyle,
  };
  if (!transform) {
    return styles;
  }
  return ({
    ...styles,
    transform: `translate(0, ${transform.substring(transform.indexOf(',') + 1, transform.indexOf(')'))})`,
  });
};
```

But it has lots of performance issues, Does Anybody has idea?
Do you have a feature to do this, like a props or something?

Thanks for this great library.

**Comment by alexreardon** [comment]
> ### Application 5: no drag axis locking
> For now, the library does not support drag axis locking (aka drag rails). This is where the user is restricted to only dragging along one axis. The current thinking is this breaks the physical metaphor we are going for and sends a message to the user that they are interacting with a piece of software rather than moving physical objects around. It is possible to ensure that a user can only drop in a single list by using props type and isDropDisabled. You can also do some visual treatment to the list onDragStart to show the user that this is the only place they can interact with.

You are welcome to add this on top of the library as you are. However, there might be some rough edges.

**Comment by alexreardon** [comment]
I will close this as won't fix. However, other people are welcome to chat about this one 👍

**Comment by sidduRam89** [comment]
Yes i want to know react dnd support dragging only in x-axis.
As my whole application is breaking while dragging through.

**Comment by Haqverdi** [comment]
i am too need for support this

**Comment by alirezavalizade** [comment]
you can do something like above example, it's working correctly for me, however I think it has performance issue on long lists. @Haqverdi

**Comment by Haqverdi** [comment]
> you can do something like above example, it's working correctly for me, however I think it has performance issue on long lists. @Haqverdi

thanks, i will try

**Comment by simeon** [comment]
@alirezavalizade Any ideas on what might resolve (or at least reduce) the performance issues?

**Comment by zeptoon** [comment]
@alexreardon Way to force your thinking onto everyone and really limit the usability of this library

**Comment by jellohouse** [comment]
Please add this option as a prop!
For example: `<Draggable direction="vertical">` would be super useful.

**Comment by butterydev** [comment]
I just do this ... capture and replace

```
let transform = provided.draggableProps.style.transform;

if (snapshot.isDragging && transform) {
  transform = transform.replace(/\(.+\,/, "(0,");
}
```

then later ... when rendering

```
style={
  snapshot.isDragging
    ? {
      ...provided.draggableProps.style,
      transform: transform,
    }
```

**Comment by mech** [comment]
Adding to what @butterydev has started:

```javascript
<Draggable>
  {(provided, snapshot) => {
    // Restrict dragging to vertical axis
    let transform = provided.draggableProps.style.transform;

    if (snapshotDrag.isDragging && transform) {
      transform = transform.replace(/\(.+\,/, "(0,");
    }

    const style = {
      ...provided.draggableProps.style,
      transform,
    };

    return (
      <li
        ref={provided.innerRef}
        {...provided.draggableProps}
        style={style}>
      </li>
    )
  }}
<Draggable>
```

**Comment by danielfpedro** [comment]
> The current thinking is this breaks the physical metaphor we are going for and sends a message to the user that they are interacting with a piece of software rather than moving physical objects around.

What a bla bla bla.

**Comment by danielfpedro** [comment]
> snapshot.isDragging
>     ? {
>       ...provided.draggableProps.style,
>       transform: transform,
>     }

Not even close to work.

**Comment by raccoman** [comment]
`
  let transform = provided.draggableProps.style?.transform
  
  if (transform) {
      transform = transform.replace(/,\s[-+]*\d+px\)/, ", 0px)");
      provided.draggableProps.style = {
          ...provided.draggableProps.style,
          transform,
      }
  }
`
It works for me, allowing only horizontal movement.

**Comment by irg1008** [comment]
> > Adding to what @butterydev has started:
> > ```js
> > <Draggable>
> >   {(provided, snapshot) => {
> >     // Restrict dragging to vertical axis
> >     let transform = provided.draggableProps.style.transform;
> > 
> >     if (snapshotDrag.isDragging && transform) {
> >       transform = transform.replace(/\(.+\,/, "(0,");
> >     }
> > 
> >     const style = {
> >       ...provided.draggableProps.style,
> >       transform,
> >     };
> > 
> >     return (
> >       <li
> >         ref={provided.innerRef}
> >         {...provided.draggableProps}
> >         style={style}>
> >       </li>
> >     )
> >   }}
> > <Draggable>
> > ```
> 
> Problem here is for me when you move the mouse outside of the dropable the placeholder disappears and you cant move the draggable anymore

Do we know how can we limit the draggable box to the parent and sisable outside drag?
