### ISSUE TITLE
Implementation of virtualization or windowing

### ISSUE THREAD

**Issue by wuweiweiwu** [atlassian/react-beautiful-dnd#959]
## Bug or feature request? Feature request

I'm wondering if there is a plan on the road map to handle list virtualization / windowing for rendering large numbers of list items. either through `react-window` `react-virtualized`. 

We have an implementation here https://github.com/frontend-collective/react-sortable-tree/ but the dnd manager is a bit outdated and I was playing around with replacing it with `@atlaskit/tree`

**Comment by alexreardon** [comment]
We hope to work on this soon #68
