### ISSUE TITLE
Will react-beautiful-dnd just support for React?

### ISSUE THREAD

**Issue by LeeHyungGeun** [atlassian/react-beautiful-dnd#97]
Will react-beautiful-dnd support for other libraries? For example: Vue or angular?

Because the license of React has changed as BSD+Patents, my company is on discussing to change our Front-end library to others. 
In addition, Is there any idea of the license issue in Atlassian?

**Comment by alexreardon** [comment]
At this stage we are not considering supporting any frameworks other than React with this library. You are welcome to try out using [`preact`](https://github.com/developit/preact) with [`preact-compat`](https://github.com/developit/preact-compat) but it is not officially supported by us at this time. 

I am not qualified to answer the license question unfortunately.

**Comment by alexreardon** [comment]
Relevant: react is moving to the MIT license https://code.facebook.com/posts/300798627056246

**Comment by kesha-antonov** [comment]
Not working with preact.
<img width="206" alt="screen shot 2018-08-19 at 21 49 46" src="https://user-images.githubusercontent.com/11584712/44311982-cf020380-a3f9-11e8-9734-6263a08b0325.png">

**Comment by alexreardon** [comment]
We do not claim to work with preact. We correctly conform to the React api. So as long as another library does that then everything should just work. 

Without an example we cannot begin to see what is going on

At this stage we won't be directly supporting any library other than react to enable us to move faster

**Comment by kesha-antonov** [comment]
Ok
Thanks!
I moved to https://github.com/Shopify/draggable
