### ISSUE TITLE
New feature request: rendering another instance while dragging and with a different renderer

### ISSUE THREAD

**Issue by gabrielenosso** [atlassian/react-beautiful-dnd#977]
The feature is a request between 2 other features I have been requested in other posts:

1) When the user starts to drag a Draggable, it duplicates the object:
it doesn't remove the Draggable from the Source list, but it creates another instance of it.

2) The component that appears during the drag is different from the one rendered in the list.
For example, as a prop: <Draggable dragRenderer={<div>Hello</div>} />
(The virtual model built for the drag operation should be based on the component specified in dragRenderer)

With these 2 features implemented, we could use the library in a lot of new different scenarios.

**Comment by alexreardon** [comment]
For now this falls outside of our [design principles](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/design-principles.md)

We will need to implement some sort of copy for #68.

For copy behaviour see #216
