### ISSUE TITLE
Error while Dropping, Id undefined. 

### ISSUE THREAD

**Issue by tanmayparmar** [atlassian/react-beautiful-dnd#979]
## Bug or feature request?
Help Wanted

## Get started
I have just coming from that tutorial. And i believe i followed every thing. I am trying to drag and drop between the list. However, when i am dropping it appears, it is failed to pick that new item id. 

## Check your console
 An error has occurred while a drag is occurring. Any existing drag will be cancelled. > Uncaught TypeError: Cannot read property 'TaxId' of undefined

### What browser are you using?
Chrome
### Demo
I tried to creat demo [Here](https://codesandbox.io/s/0017y42wrn). It is also not working

this is my column.js
` <Droppable droppableId={this.props.column.id}>
                    {(provided) => (                     
                            <ItemList
                                ref={provided.innerRef}
                                innerRef={provided.innerRef}
                                {...provided.droppableProps}
                            >
                                **{this.props.items.map((item, index) => (<Item key={item.TaxId} item={item} index={index} />))}**
                                {provided.placeholder}
                            </ItemList>
                     )}
                </Droppable>
           `
this is my DragDropcontext 
`
  <DragDropContext onDragEnd={this.onDragEnd}>
                <Container>
                    {this.state.columnOrder.map(columnId => {
                        const column = this.state.columns[columnId];
                        const items = column.itemIds.map(itemId => this.state.listitems[itemId]);
                        return <Column key={column.id} column={column} items={items} />;
                    })}
                </Container>                
            </DragDropContext>
`

![2018-12-03 15_28_45-klickbook](https://user-images.githubusercontent.com/7348352/49399757-2a89a000-f710-11e8-9b00-ba6f4c07684f.png)

**Comment by alexreardon** [comment]
I am failing to load your example: https://codesandbox.io/s/n016v3y22p

Can you please get it to a state where it prints the error you are speaking about?

**Comment by tanmayparmar** [comment]
i have updated little bit with my file structure. I will try to run it.

**Comment by tanmayparmar** [comment]
i amusing 3rd party template library so unable to create demo. However, what i believe is when i am dropping it is not saving new ids in new array. May be something wrong with me dragEnd method. 

` onDragEnd = result => {

        const { destination, source, draggableId,droppableId } = result;

        if (!destination) {
            return;
        }
        if (
            destination.droppableId === source.droppableId &&
            destination.index === source.index
        ) {
            return;
        }

        const start = this.state.columns[source.droppableId];
        const finish = this.state.columns[destination.droppableId];

        if (start === finish) {

            const newItemIds = Array.from(start.itemIds);
            newItemIds.splice(source.index, 1);
            newItemIds.splice(destination.index, 0, draggableId);

            const newColumn = {
                ...start,
                itemIds: newItemIds,
            };

            const newState = {
                ...this.state,
                columns: {
                    ...this.state.columns,
                    [newColumn.id]: newColumn,
                },
            };
            this.setState(newState);
            return;
        }
        //moving between the list

        const startItemIds = Array.from(start.itemIds);
        startItemIds.splice(source.index, 1);
        
        const newStart = {
            ...start,
            itemIds: startItemIds,
        };
     
        const finishItemIds = Array.from(finish.itemIds);
        finishItemIds.splice(destination.index, 0, draggableId);
       
        const newFinish = {
            ...finish,
            itemIds: finishItemIds,
        };
        const newState = {
            ...this.state,
            columns: {
                ...this.state.columns,
                [newStart.id]: newStart,
                [newFinish.id]: newFinish
            },
        };
        this.setState(newState);
    };`

**Comment by tanmayparmar** [comment]
Also, is there any way i can use jsonArray instead of jsonObject. foe example, something like this :
 `    listitems:[
        {
          "TaxId": "5f70e7de-7e13-4a4f-bd05-82f400c3e930",
          "TaxName": "HST"
        },
        {
          "TaxId": "780ad381-2038-4145-ae26-179ef1a8a929",
          "TaxName": "ON"
        },
        {
          "TaxId": "c358cecc-29cb-4c7a-95e4-390ae7773786",
          "TaxName": "BC"
        },
        {
          "TaxId": "316d3b42-31c0-472d-821f-415ec79d00f2",
          "TaxName": "NS"
        }],   
`
in my columns.

**Comment by alexreardon** [comment]
Is this still an issue for you? It looks like it is caused by some incorrect array modifications. Please reopen if you still need assistance
