### ISSUE TITLE
Changing draggable height on drag

### ISSUE THREAD

**Issue by dcporter44** [atlassian/react-beautiful-dnd#981]
## Bug or feature request?

Bug

### Expected behavior
Changing the height CSS property of a dragging element should adjust the height of the draggable area and drag placeholder.

### Actual behavior
The original height of the draggable is maintained in the placeholder and draggable area.

### Steps to reproduce
Use `onBeforeDragStart` callback to change the height of the draggable.

### What version of `React` are you using?
16.4.2

### What version of `react-beautiful-dnd` are you running?
9.0.1

### What browser are you using?
Chrome

**Comment by sanjeevpande** [comment]
Facing same issue where I am unable to drop a list with larger height over a smaller one.
https://imgur.com/a/e1SlMoz

**Comment by alexreardon** [comment]
#174

**Comment by alexreardon** [comment]
There are some pitfalls with this. If a user is dragging a part of an item that is suddenly not visible that could be a bit jarring.

But the current situation is sub-optimal for big items #930

I am trying to think through a robust solution that would not be too big a foot gun

**Comment by dcporter44** [comment]
Ideally:
On drag and after height change, position the center of the newly sized Draggable at the cursor position.

**Comment by knobo** [comment]
Could a hook/callback be implemented, that is run before the drag-image is created. So that I get time to resize my element before dragging is started. I want to collapse elements in my list before dragging. The callback should be optional, if you don't specify one, it's not used.

**Comment by stellarbelle** [comment]
Having the ability to close lists before dragging would be great when changing the position of list when lists are stacked horizontally. This is my current predicament. Having a hook/callback that could be called too resize the element would help greatly.

**Comment by BraunreutherA** [comment]
I'm also looking for that feature. Our components have different sizes and in best case I'd like to show an abstracted smaller view of the dragged component. Could we implement a hook where we return a Component to display on drag? 
I'd also help with a PR just scanned the code but would need some help to understand where the drag component gets initial captured.

**Comment by stellarbelle** [comment]
Hi, I thanks for this I will see if it works for our situation. I read your
other comment and I think the drag component gets captured in the
`getWindow` function on line 7341 in react-beautiful-dnd.esm.js it seems to
grab the ref and access the size of the component for there. This happened
before dragStart gets called. I hope this helps!

Thanks!

**Comment by stellarbelle** [comment]
I think the drag component gets captured in the
`getWindow` function on line 7341 in react-beautiful-dnd.esm.js it seems to
grab the ref and access the size of the component for there. This happened
before dragStart gets called. I hope this helps!

**Comment by BraunreutherA** [comment]
@stellarbelle 
I had some deeper insight in the library this afternoon. The fix I posted won't help sadly (that's why I deleted the post)

One thing that works but is against the benefits of the lib is when you register the mouse down listener and create a new component before the drag starts. Then you will lose the click listener ability to receive normal clicks aswell. 

I'd pass down the publish method from the <DraggableDimensionPublisher> (https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx) down through the <DragHandle> and then create a callback for the rendered child to create a onDrag component befor the onLift method triggers in https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/drag-handle/sensor/create-mouse-sensor.js

**Comment by pbrandone** [comment]
is there any progress on this?
I'm currently hijacking `onMouseDown` on `dragHandleProps` to call my own function first that sets the draggable ID on the state so it can be used to colapse the draggable. It works fine on desktop but the same approach on touch devices with "touchstart" simply doesn't work (maybe because of the setState rerender?).
Some official way of being able to change the height of the items before it's calculated would be great.

I have several tall items that need to be stored in a short bottom drawer and the fact that I can't collapse them combined with the calculation of the center mass VS pointer position (#930) is making me think that this might be impossible with this package...

**Comment by DypoB** [comment]
Hello. Also ran into this problem. Does anyone have a solution? Really need

**Comment by DypoB** [comment]
> Я также ищу эту функцию. Наши компоненты имеют разные размеры, и в лучшем случае я хотел бы показать абстрактное уменьшенное представление перетаскиваемого компонента. Можем ли мы реализовать хук, где мы возвращаем компонент для отображения при перетаскивании? 
> Я также помог бы с пиарщиком, который только что просканировал код, но мне нужна помощь, чтобы понять, где компонент перетаскивания изначально захвачен.



> @stellarbelle
> I had some deeper insight in the library this afternoon. The fix I posted won't help sadly (that's why I deleted the post)
> 
> One thing that works but is against the benefits of the lib is when you register the mouse down listener and create a new component before the drag starts. Then you will lose the click listener ability to receive normal clicks aswell.
> 
> I'd pass down the publish method from the (https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx) down through the and then create a callback for the rendered child to create a onDrag component befor the onLift method triggers in https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/drag-handle/sensor/create-mouse-sensor.js

Exactly the same task.

> I'm also looking for that feature. Our components have different sizes and in best case I'd like to show an abstracted smaller view of the dragged component. Could we implement a hook where we return a Component to display on drag?
> I'd also help with a PR just scanned the code but would need some help to understand where the drag component gets initial captured.

Exactly the same task. Do you have a solution ?

**Comment by alexreardon** [comment]
Related: #930

**Comment by alexreardon** [comment]
Will track as a part of #930

**Comment by BradBailey-web** [comment]
I am accomplishing this without any *noticeable* problems by doing the following: 
1) Using a drag handle. (This is so you don't get the jarring effect talked about by @alexreardon ("If a user is dragging a part of an item that is suddenly not visible that could be a bit jarring.")
2) Make a combined state that consist of snapshot.isDragging and a custom state that I call "isMouseDown". If either of these is true, the combined state is true. 
An important note is that onMouseDown and onTouchStart both trigger BEFORE onDragStart trigger.
3) Using styledComponents I pass the combined state in and render the element conditionally two different ways as seen below. This styledComponent is the direct child of Draggable (this may or may not be necessary)

`const Container = styled.div<{
  readonly combinedState: boolean;
}>'
    border:1px solid lightgrey;
    border-radius:2px;
    padding 8px;
    margin-bottom:8px;
    background-color: ${(props) => (props.combinedState ? "lightgreen" : "white")};
    width: ${(props) => (props.combinedState ? "192px !important" : "")};
    height: ${(props) => (props.combinedState ? "192px !important" : "")};
    overflow: ${(props) =>
      props.combinedState ? "hidden" : ""};
    display:flex;
';`

This works perfectly find for my build, your mileage may vary.

**Comment by mexicantexan** [comment]
> I am accomplishing this without any _noticeable_ problems by doing the following:
> 
> 1. Using a drag handle. (This is so you don't get the jarring effect talked about by @alexreardon ("If a user is dragging a part of an item that is suddenly not visible that could be a bit jarring.")
> 2. Make a combined state that consist of snapshot.isDragging and a custom state that I call "isMouseDown". If either of these is true, the combined state is true.
>    An important note is that onMouseDown and onTouchStart both trigger BEFORE onDragStart trigger.
> 3. Using styledComponents I pass the combined state in and render the element conditionally two different ways as seen below. This styledComponent is the direct child of Draggable (this may or may not be necessary)
> 
> `const Container = styled.div<{ readonly combinedState: boolean; }>' border:1px solid lightgrey; border-radius:2px; padding 8px; margin-bottom:8px; background-color: ${(props) => (props.combinedState ? "lightgreen" : "white")}; width: ${(props) => (props.combinedState ? "192px !important" : "")}; height: ${(props) => (props.combinedState ? "192px !important" : "")}; overflow: ${(props) => props.combinedState ? "hidden" : ""}; display:flex; ';`
> 
> 4. make sure your draghandle does not move when your styledComponent resizes.
> 
> This works perfectly find for my build, your mileage may vary.

Could you throw this in a Code Sandbox (or other) example?

**Comment by treehouseops** [comment]
> > I am accomplishing this without any _noticeable_ problems by doing the following:
> > 
> > 1. Using a drag handle. (This is so you don't get the jarring effect talked about by @alexreardon ("If a user is dragging a part of an item that is suddenly not visible that could be a bit jarring.")
> > 2. Make a combined state that consist of snapshot.isDragging and a custom state that I call "isMouseDown". If either of these is true, the combined state is true.
> >    An important note is that onMouseDown and onTouchStart both trigger BEFORE onDragStart trigger.
> > 3. Using styledComponents I pass the combined state in and render the element conditionally two different ways as seen below. This styledComponent is the direct child of Draggable (this may or may not be necessary)
> > 
> > `const Container = styled.div<{ readonly combinedState: boolean; }>' border:1px solid lightgrey; border-radius:2px; padding 8px; margin-bottom:8px; background-color: ${(props) => (props.combinedState ? "lightgreen" : "white")}; width: ${(props) => (props.combinedState ? "192px !important" : "")}; height: ${(props) => (props.combinedState ? "192px !important" : "")}; overflow: ${(props) => props.combinedState ? "hidden" : ""}; display:flex; ';`
> > 
> > 4. make sure your draghandle does not move when your styledComponent resizes.
> > 
> > This works perfectly find for my build, your mileage may vary.
> 
> @DanielBailey-web Could you throw this in a Code Sandbox (or other) example?

Second this, @DanielBailey-web that'd be amazing :)
