### ISSUE TITLE
Upgrade to react-redux v6, move to React.createContext and React 16.6

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#984]
`react-redux` v6 just came out, so it is time to move to `React.createContext`

I think it makes sense to move to React 16.6 in order to use [`Class.contextType`](https://reactjs.org/blog/2018/10/23/react-v-16-6.html)

Because this will change the peer dep version this will be a breaking change

**Comment by alexreardon** [comment]
The only sad thing about this is react-redux v6 is a little slower than v5. I will need to see if it has a material impact on things. Otherwise we might need to role something custom

**Comment by JamieDixon** [comment]
Thank you for react beautiful DND. It's saved me soo much time.

I'm wondering if it's possible to separate some of these items into their own PRs/Releases?

I'm using a few packages that depend on an older version of react-redux and it's going to take some time for those packages to land new releases. In the meantime I would love to see `React.createContext` implemented in this package to help reduce the number of errors I get with `StrictMode`.

What do you think? Is this feasible? 🙂

Thank you.

**Comment by mDibyo** [comment]
Hey @JamieDixon, It should be completely fine to have multiple versions of `react-redux` in your codebase. Are you worried about the increase in bundle size?

**Comment by alexreardon** [comment]
Done in 11.0
