### ISSUE TITLE
Stagnant Drop - Uplift from 9.0.2 to 10.0.2

### ISSUE THREAD

**Issue by nramamurth** [atlassian/react-beautiful-dnd#986]
## Bug or feature request?

I need help uplifting the current solution that uses v9.0.2 to v10.0.2 👋 I have provided a link to the prototypes that use 9.0.2 and 10.0.2 respectively, I notice that the drag event does not end as expected on 10.0.2. I appreciate the help.

### Expected behavior
Upon drag and drop, the card gets placed into the expected position.

### Actual behavior
Upon drag and drop, the card gets stagnant wherever it was dropped into. For the demo, I make the card turn blue upon drag and I could see that the card does not lose the color once I drop and the `onDragEnd` responder does not get hit.

### Steps to reproduce
Drag and drop any card from one container to another.

### What version of `React` are you using?
16.5.2

### What version of `react-beautiful-dnd` are you running?
10.0.2 and 9.0.2

### What browser are you using?
Google Chrome

### Demo
9.0.2 - https://codesandbox.io/s/p5owwp30x7
10.0.2 - https://codesandbox.io/s/34p3r4rmv5

**Comment by alexreardon** [comment]
```js
ref={provided.innerRef}
{...provided.droppableProps}
{...provided.dragHandleProps}
```

Should be

```diff
ref={provided.innerRef}
- {...provided.droppableProps}
+ {...provided.draggable}
{...provided.dragHandleProps}
```
