### ISSUE TITLE
"simple-trello" DEMO is buggy

### ISSUE THREAD

**Issue by yairEO** [atlassian/react-beautiful-dnd#992]
I randomly came to this project and was impressed by the huge waste of time invested in the README file :) I am shocked at the amount of words and the browser scroll height of this repo. This is a drag-n-drop script, not an Operating System..

So I imminently looked for the demo page to see what's all the fuss is about. played around and saw some bugs. I was SHOCKED. how can there be bugs in a repo with so much text in the README? it would seem all time which was invested in this project should have prevented any bugs.

![bug-3](https://user-images.githubusercontent.com/845031/49696134-f1d54500-fbad-11e8-990e-05e01a529c67.gif)

As seen above, dragging and moving an item "BBB" and releasing the mouse will drop the item at the wrong place and after few ms the item will just back to it's "original" placement.

Also shown is a problem where a list's gray container's height is "jumpy". this should not happen if there's a transition for a removed or newly dropped item. See how the "Add another card" text is jumping up and down. This looks bad..

**Comment by alexreardon** [comment]
## Code of conduct

While you raise some issues that I would have been happy to discuss, the language used in this issue is unacceptable. As such, I will be locking this issue.

> ### Our Standards
> 
> Examples of behavior that contributes to creating a positive environment include:
> 
> - Using welcoming and inclusive language
> - Being respectful of differing viewpoints and experiences
> - Gracefully accepting constructive criticism
> - Focusing on what is best for the community
> - Showing empathy towards other community members
> 
> Examples of unacceptable behavior by participants include:
> 
> - The use of sexualized language or imagery and unwelcome sexual attention or advances
> - Trolling, insulting/derogatory comments, and personal or political attacks
> - Public or private harassment
> - Publishing others' private information, such as a physical or electronic address, without explicit permission
> - Other conduct which could reasonably be considered inappropriate in a professional setting

## Your issues

1. we are fixing that 'snapping' soon #77 
2. it looks like the app is not correctly reordering the list. Here is a guide: https://egghead.io/lessons/react-persist-list-reordering-with-react-beautiful-dnd-using-the-ondragend-callback
