### ISSUE TITLE
The draggable item returns to its initial position. 

### ISSUE THREAD

**Issue by picwellwisher12pk** [atlassian/react-beautiful-dnd#997]
Help
### Expected behavior
When I drag a list item(representing an actual tab on Browser) it should drag and should stay where I drop it. 
### Actual behavior
When the dragging stops. The list item moves back to its original position. 
### Steps to reproduce
After building is done(npm start) , you need to mount the extension on either Chrome or Firefox. Then click on extension icon to open the Extension Tabs Page. There you can try dragging the list up and down. 
### What version of `React` are you using?
16.6.3
### What version of `react-beautiful-dnd` are you using?
10.0.2
### What version of `Node` are you using?
10.13.0

**Sorry for taking your valuable time. Not sure if this is worth it.** But here it is. 
@alexreardon or anyone please. 
I followed guides to implement this, but still my draggable item returns to its starting position just like a drag is canceled. Although `setState` should fix them at their places. Although new state/position get updated soon after but with a jerk. The over experience is jerky. And I am not getting any error.  **Just guide me toward right direction**.  

![screen recording 2018-12-09 at 05 30 17 34 pm](https://user-images.githubusercontent.com/1508646/50024374-f95c7a00-0003-11e9-89dd-804c335ed378.gif)

[package.json](https://github.com/picwellwisher12pk/onetab-advanced/blob/feature/drag-and-drop-to-sort/package.json)

[TabsApp.js](https://github.com/picwellwisher12pk/onetab-advanced/blob/feature/drag-and-drop-to-sort/src/scripts/TabsApp.js)

[ActiveTabs.js (DragDropContext)](https://github.com/picwellwisher12pk/onetab-advanced/blob/feature/drag-and-drop-to-sort/src/scripts/ActiveTabs.js)
```
reorder(list, startIndex, endIndex) {
    const result = Array.from(list);
    const [removed] = result.splice(startIndex, 1);
    result.splice(endIndex, 0, removed);
    return result;
  }

  onDragEnd(result) {
    const { destination, source, draggableId } = result;
    if (!destination) return;
    if (destination.droppableId === source.droppableId && destination.index === source.index ) {return; }
    const tabs = this.reorder(
      this.state.tabs,
      source.index,
      destination.index
    );
    this.setState({tabs });
    browser.tabs.move(result.draggableId, { index: result.destination.index });
    window.activeTabs.setState({tabs:window.tabs});
  }
```
```
<div className="tabs-list-container">
        <DragDropContext onDragEnd={ this.onDragEnd } key={2} >
            <Tabsgroup preferences={this.props.preferences} tabs={this.state.tabs}>
            {this.filterTabs().map(
              tab => (
                <CSSTransition
                  transitionName="fade"
                  classNames="fade"
                  appear={this.state.preferences.tabsGroup.tabsListAnimation}
                  exit={false}
                  key={tab.id}
                  timeout={{ enter: 200, exit: 0 }}
                >

                  {this.tabTemplate(tab)}
                </CSSTransition>
              )
            )}
          </Tabsgroup>
        </DragDropContext>
      </div>
```

[TabsGroup.js (Droppable)](https://github.com/picwellwisher12pk/onetab-advanced/blob/feature/drag-and-drop-to-sort/src/scripts/components/Accordion/TabsGroup/TabsGroup.js)
```
<Droppable droppableId="droppable">
        {(provided, snapshot) => (
          <ul className="tab tabs-list sortable selectable" ref={provided.innerRef}>
          {this.props.children}
          {provided.placeholder}
          </ul>
          )}
      </Droppable>
```

[Tab.js (Draggable)](https://github.com/picwellwisher12pk/onetab-advanced/blob/feature/drag-and-drop-to-sort/src/scripts/components/Accordion/TabsGroup/Tab/Tab.js)
```
 <Draggable draggableId={this.props.id} key={this.props.id} data-id={this.props.id} index={this.props.position} className={`tab-item` + (checked ? ` checked` : ` `)+ (loading||discarded ? ` idle` : ` `)}>
      {(provided,snapshot)=>{
       return <li
       {...provided.draggableProps}
       {...provided.dragHandleProps}
       ref={provided.innerRef}
```

**Comment by picwellwisher12pk** [comment]
Still waiting. Anyone? please

**Comment by treshugart** [comment]
Hey @picwellwisher12pk, sorry for the delay. Alex, the maintainer, has been on holiday.

In your example above, it seems as though there's a delay between dropping and the draggable being restored to its previous position. Do you have an async request happening that would fire a state change that causes the items to be reset?

**Comment by picwellwisher12pk** [comment]
Finally 😄 Thanks for your time and reply. 

Ok. So let me tell how it works. My extension keeps a record of tabs in current window everytime tabs event has happened. For example creation of new tab, URL change of some tab, move or removing of tabs etc. Every such event sends a new list of tabs to my extension. 
But while I am dragging, most of the time there is no event firing, so I expect it to work smoothly. On a successful drop, I would like to move/sort my tabs depending on their new positions.

I don't think such example can be replicated on codesandbox because it depends on Browser API.

**Comment by treshugart** [comment]
> I don't think such example can be replicated on codesandbox because it depends on Browser API.

https://codesandbox.io/ runs in a browser.

**Comment by picwellwisher12pk** [comment]
You mean `browser.tabs`  API will work there?

**Comment by alexreardon** [comment]
It looks like your issue is caused by update timing.

It is important that you update your list immediately after a reorder. After that you can update the tabs which might be a slow operation.

Here is what I would do:

1. when the app loads, put all of the tabs into React `state`
2. perform all rendering and reorder operations on the `state`. 
3. after a reorder, asyncornously update the tabs order

If you detect a change in the browser tabs that is not caused by your UI:

- if no drag is occurring: recreate your React `state`
- if a drag is occurring: ignore the update and let the user finish dragging. After the drop and reorder update (which might fall) recreate your React `state` from the tabs. There are a few error scenarios you will need to handle as a part of this. Alternatively you could cancel an active drag if you detect a browser tab change while dragging. Now that i think about it a bit more, this might be a bit of an edge case as it will be hard to change the tabs outside of a drag when a drag is occurring

**Comment by MonsterJacob** [comment]
@picwellwisher12pk  hello friend, have you solved this position problem. I encounter a similar question., dragging a item, but it returns to its initial position

**Comment by picwellwisher12pk** [comment]
No ,not yet. I was too busy with other things. But i shall update you soon
about this on github.

**Comment by picwellwisher12pk** [comment]
Currently, I could achieve this so far.
[Excited gem demo](https://cl.ly/be3e3ccc0e3a)

**Comment by picwellwisher12pk** [comment]
Previously I was doing it like:

1. Drag tab UI to a new position and release without persisting state (Dragged Tab UI returns to its original position.
2. Move the actual tab to the new position: 
3. Triggering update of state with updated positions by the above action 
This flow was flickering twice because first tab UI was returning to its original position and then moving to a new position because of the updated state coming from the parent component.

Now I am using Redux but I also changed the flow. 
1. Drag tab UI to a new position and persisting the state/position without pushing changes to Redux store or actually moving tab in the browser that in turn update store/state.
2. After persisting state, get the tab to move to the new position in the browser. 

This still shows flicker, some animation artifact. I tried preventing actual browser tab move to check but still same.
![ezgif com-optimize](https://user-images.githubusercontent.com/1508646/59624758-0f80f980-9151-11e9-8b1b-178372ce7730.gif)

**Comment by MonsterJacob** [comment]
@picwellwisher12pk 
wow, thanks for your replay, which really gives me a new perspective to use this good library in a new way. I used the new context API of React to solve the problem as well. I figured out the previous logic didn't work because the child component changed the state but the state got replaced by the parent's props and parent state didn't change. Thanks again :)
