### ISSUE TITLE
on drag view queries @alexreardon alexreardon thanks

### ISSUE THREAD

**Issue by zhangshuai0101** [atlassian/react-beautiful-dnd#998]
demo： https://0qrxp521zp.codesandbox.io/
problem description：When dragging from the left to the right, everything is so normal. When dragging from the right to the left, there is a problem. Can you answer it? Thank you

**Comment by zhangshuai0101** [comment]
> 适用于我的机器：
> ![](https://camo.githubusercontent.com/8b58309a94221b42093e4bbf63c9a2345818be1f/68747470733a2f2f692e696d6775722e636f6d2f47384a54696b462e676966)
> 
> 有没有我没见过的东西？

Well, when dragged from the right to the left, the left element is occluded when it moves to the left element. This is caused by position: relation. What can we do now? @markdon

**Comment by markdon** [comment]
It looks like react-beautiful-dnd creates a li element in that space and you're styling all li elements in that container to be grey. Try giving your grey elements and grey css rule a class (e.g. `li.inactive`).

I'd have given an example but I don't know how to edit your codesandbox :(

**Comment by alexreardon** [comment]
There is a lot going on in your example. Can you please reduce it to a smaller use case?

**Comment by alexreardon** [comment]
It looks like we are not handling `float` very well right now. I would not recommend using `float` generally for layouts like this. Please try just using flexbox.

Let me know if you have any issues
